Air temperature for all the utilities

In [ ]:
# https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_MONTHLY
# ERA5 Monthly Aggregates - Latest Climate Reanalysis Produced by ECMWF / Copernicus Climate Change Service
# in Kelvins (k)
# image collection: 'ECMWF/ERA5/MONTHLY'
# citation: Copernicus Climate Change Service (C3S) (2017): ERA5: Fifth generation of ECMWF atmospheric reanalyses of the global climate. Copernicus Climate Change Service Climate Data Store (CDS), (date of access), https://cds.climate.copernicus.eu/cdsapp#!/home
# terms of use:Please acknowledge the use of ERA5 as stated in the Copernicus C3S/CAMS License agreement:
#
# 5.1.1 Where the Licensee communicates or distributes Copernicus Products to the public, the Licensee shall inform the recipients of the source by using the following or any similar notice: "Generated using Copernicus Climate Change Service information (Year)".
# 5.1.2 Where the Licensee makes or contributes to a publication or distribution containing adapted or modified Copernicus Products, the Licensee shall provide the following or any similar notice: "Contains modified Copernicus Climate Change Service information (Year)".
# 5.1.3 Any such publication or distribution covered by clauses 5.1.1 and 5.1.2 shall state that neither the European Commission nor ECMWF is responsible for any use that may be made of the Copernicus information or Data it contains.

# band : mean_2m_air_temperature , measured in Kelvins. from 223.6 to 304 K


# lets use the bound for TEP (Tucson Electric Power) in 2014, full_id: AZ_24211

In [1]:
# import library
import ee
import os
import geemap
import geopandas as gpd
import pandas as pd
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from tqdm import tqdm

In [3]:
# authenticate & initilialize earth engine
ee.Authenticate()
ee.Initialize(project='ee-jfelix-netmetering')

In [5]:
# set working directory/mount drive
from google.colab import drive
drive.mount('/content/drive')

#  Set working directory inside Google Drive
drive_path = '/content/drive/My Drive/net_metering'
os.makedirs(drive_path, exist_ok=True)
os.chdir(drive_path)

print("Current working directory:", os.getcwd())

# to keep console from disconnecting ctr+shift+i to inspector and go to the console
# function ClickConnect(){
#    console.log("Working");
#    document.querySelector("colab-toolbar-button#connect").click()
#}
#setInterval(ClickConnect,60000)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Current working directory: /content/drive/My Drive/net_metering

In [28]:
# get the boundary for all the offices
# you have to mount the google drive
# load the shapefile for all the utility boundaries (This was simplified in R)
all_sf = gpd.read_file('shapefiles/utility_boundaries_simplified_annual_v2.shp')

/usr/local/lib/python3.11/dist-packages/pyogrio/raw.py:198: RuntimeWarning: shapefiles/utility_boundaries_simplified_annual_v2.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

In [15]:
all_sf['year'].max()

2023.0

In [29]:
# view the boundary shapefile
all_sf.head()
all_sf.tail()

,year,full_id,full_id_y,geometry
5148,2012.0,UT_11135,UT_11135_2012,"POLYGON ((-111.99107 41.83314, -111.64558 41.7..."
5149,2013.0,UT_11135,UT_11135_2013,"POLYGON ((-111.99107 41.83314, -111.64558 41.7..."
5150,2011.0,VA_19882,VA_19882_2011,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."
5151,2012.0,VA_19882,VA_19882_2012,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."
5152,2013.0,VA_19882,VA_19882_2013,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."

In [8]:
# bring the data from ee and select the band
temp_collection = ee.ImageCollection('ECMWF/ERA5/MONTHLY').select('mean_2m_air_temperature')

In [30]:
# List of unique utility IDs
ulist = all_sf['full_id_y'].unique().tolist()

In [62]:
# create an empty df to collect data for loop
utility_monthly_temp = []

In [63]:
# Loop over each utility
for u in tqdm(ulist):  # u = "AZ_24211_2011"
    start_time = datetime.now()

    u_sf = all_sf[all_sf['full_id_y'] == u]

    # Add an explicit check for None geometry before attempting to access its attributes
    if u_sf.empty or u_sf.geometry.is_empty.any() or u_sf.geometry.values[0] is None:
        print(f"Skipping utility {u} due to empty or invalid geometry.")
        continue

    # Convert geometry to EE
    geom_json = u_sf.geometry.values[0].__geo_interface__
    boundary = ee.Geometry(geom_json)

    # Extract year
    year = int(u_sf['year'].values[0])
    d1 = datetime(year, 1, 1)
    d2 = d1 + relativedelta(months=12)

    # Filter image collection
    monthly_image = temp_collection.filterDate(d1.strftime('%Y-%m-%d'), d2.strftime('%Y-%m-%d'))

    # Function to extract average temp for each image
    def extract_temp(image):
        date = ee.Date(image.get('system:time_start')).format('YYYY-MM-dd HH:mm')

        med_temp = image.reduceRegion(
            reducer=ee.Reducer.median(),
            geometry=boundary,
            scale=5000,
            maxPixels=1e13
        ).get('mean_2m_air_temperature')

        mean_temp = image.reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=boundary,
            scale=5000,
            maxPixels=1e13
        ).get('mean_2m_air_temperature')
        return ee.Feature(None, {'date': date, 'avg_temp': mean_temp, 'median_temp': med_temp})
    # Map over collection and get features
    temp_features = monthly_image.map(extract_temp)
    temp_table = ee.FeatureCollection(temp_features)

    # Export to client
    try:
        temp_dicts = geemap.ee_to_geojson(temp_table)
        temp_df = pd.DataFrame(temp_dicts['features'])
        temp_df['date'] = pd.to_datetime(temp_df['properties'].apply(lambda x: x['date']))
        temp_df['avg_temp'] = temp_df['properties'].apply(lambda x: x['avg_temp'])
        temp_df['median_temp'] = temp_df['properties'].apply(lambda x: x['median_temp'])
        temp_df.drop(columns=['properties', 'type', 'geometry'], inplace=True)

        # Add utility info
        temp_df['full_id_y'] = u
        temp_df['year'] = year
        temp_df['month'] = temp_df['date'].dt.month

        # save
        utility_monthly_temp.append(temp_df)

    except Exception as e:
        print(f"Failed for utility {u}: {e}")
        continue

    print(f"{u} completed in {datetime.now() - start_time}")

# Combine all data and write to CSV
result_df = pd.concat(utility_monthly_temp, ignore_index=True)

# Save to CSV
result_df.to_csv("data files/monthly_air_temp_utilities_kelvin.csv", index=False)

  0%|          | 1/4292 [00:00<26:37,  2.69it/s]

AK_1651_2011 completed in 0:00:00.372139

  0%|          | 2/4292 [00:00<34:02,  2.10it/s]

AK_7353_2011 completed in 0:00:00.547501

  0%|          | 3/4292 [00:01<29:24,  2.43it/s]

AK_19558_2011 completed in 0:00:00.333414

  0%|          | 4/4292 [00:01<27:38,  2.59it/s]

AR_814_2011 completed in 0:00:00.347905

  0%|          | 5/4292 [00:01<25:48,  2.77it/s]

AR_817_2011 completed in 0:00:00.312274

  0%|          | 6/4292 [00:02<25:35,  2.79it/s]

AR_6342_2011 completed in 0:00:00.351284

  0%|          | 7/4292 [00:02<24:39,  2.90it/s]

AR_14063_2011 completed in 0:00:00.317390

  0%|          | 8/4292 [00:02<22:24,  3.19it/s]

AR_17698_2011 completed in 0:00:00.243543

  0%|          | 9/4292 [00:03<24:58,  2.86it/s]

AZ_16572_2011 completed in 0:00:00.427300

  0%|          | 10/4292 [00:03<23:29,  3.04it/s]

AZ_19728_2011 completed in 0:00:00.282028

  0%|          | 12/4292 [00:04<19:40,  3.62it/s]

AZ_21538_2011 completed in 0:00:00.279810
AZ_24211_2011 completed in 0:00:00.187043

  0%|          | 13/4292 [00:04<19:28,  3.66it/s]

CA_11208_2011 completed in 0:00:00.265665

  0%|          | 14/4292 [00:04<27:54,  2.55it/s]

CA_14328_2011 completed in 0:00:00.664041

  0%|          | 15/4292 [00:05<24:51,  2.87it/s]

CA_14354_2011 completed in 0:00:00.248727

  0%|          | 16/4292 [00:05<25:11,  2.83it/s]

CA_14534_2011 completed in 0:00:00.364140

  0%|          | 17/4292 [00:05<25:12,  2.83it/s]

CA_16534_2011 completed in 0:00:00.353299

  0%|          | 18/4292 [00:06<26:35,  2.68it/s]

CA_16609_2011 completed in 0:00:00.418221

  0%|          | 19/4292 [00:06<30:33,  2.33it/s]

CA_17609_2011 completed in 0:00:00.556249

  0%|          | 20/4292 [00:07<26:32,  2.68it/s]

CA_19281_2011 completed in 0:00:00.240965

  0%|          | 21/4292 [00:07<27:35,  2.58it/s]

CO_3989_2011 completed in 0:00:00.421246

  1%|          | 22/4292 [00:07<25:45,  2.76it/s]

CO_6604_2011 completed in 0:00:00.300018

  1%|          | 23/4292 [00:08<27:29,  2.59it/s]

CO_9336_2011 completed in 0:00:00.442474

  1%|          | 24/4292 [00:08<31:58,  2.22it/s]

CO_15257_2011 completed in 0:00:00.596015

  1%|          | 26/4292 [00:09<23:09,  3.07it/s]

CO_15466_2011 completed in 0:00:00.298027
CO_16603_2011 completed in 0:00:00.141074

  1%|          | 28/4292 [00:09<18:41,  3.80it/s]

CO_19499_2011 completed in 0:00:00.259758
CT_19497_2011 completed in 0:00:00.161429

  1%|          | 29/4292 [00:09<17:47,  3.99it/s]

DC_15270_2011 completed in 0:00:00.220032

  1%|          | 30/4292 [00:10<18:28,  3.85it/s]

DE_5027_2011 completed in 0:00:00.281811

  1%|          | 31/4292 [00:10<18:51,  3.76it/s]

DE_5070_2011 completed in 0:00:00.277821

  1%|          | 32/4292 [00:10<19:36,  3.62it/s]

DE_5335_2011 completed in 0:00:00.300074

  1%|          | 33/4292 [00:11<25:13,  2.81it/s]

FL_6452_2011 completed in 0:00:00.538977

  1%|          | 34/4292 [00:11<29:34,  2.40it/s]

FL_6455_2011 completed in 0:00:00.558467

  1%|          | 35/4292 [00:12<26:52,  2.64it/s]

FL_7801_2011 completed in 0:00:00.289706

  1%|          | 36/4292 [00:12<23:34,  3.01it/s]

FL_9617_2011 completed in 0:00:00.223241

  1%|          | 37/4292 [00:12<22:23,  3.17it/s]

FL_18454_2011 completed in 0:00:00.275714

  1%|          | 38/4292 [00:12<20:21,  3.48it/s]

GA_3916_2011 completed in 0:00:00.219893

  1%|          | 39/4292 [00:13<23:51,  2.97it/s]

GA_7140_2011 completed in 0:00:00.450042

  1%|          | 40/4292 [00:13<22:34,  3.14it/s]

HI_8287_2011 completed in 0:00:00.275889

  1%|          | 41/4292 [00:14<22:57,  3.09it/s]

HI_10071_2011 completed in 0:00:00.333658

  1%|          | 42/4292 [00:14<27:22,  2.59it/s]

HI_11843_2011 completed in 0:00:00.530948

  1%|          | 43/4292 [00:14<24:54,  2.84it/s]

HI_19547_2011 completed in 0:00:00.269228

  1%|          | 44/4292 [00:15<26:18,  2.69it/s]

IA_9417_2011 completed in 0:00:00.416707

  1%|          | 45/4292 [00:15<27:18,  2.59it/s]

IA_12341_2011 completed in 0:00:00.415937

  1%|          | 46/4292 [00:15<25:00,  2.83it/s]

ID_9191_2011 completed in 0:00:00.273351

  1%|          | 48/4292 [00:16<20:14,  3.49it/s]

ID_14354_2011 completed in 0:00:00.283675
ID_20169_2011 completed in 0:00:00.176707

  1%|          | 49/4292 [00:16<18:24,  3.84it/s]

IL_4110_2011 completed in 0:00:00.199213
IL_12341_2011 completed in 0:00:00.202530

  1%|          | 51/4292 [00:17<20:58,  3.37it/s]

IN_9273_2011 completed in 0:00:00.420863

  1%|          | 52/4292 [00:17<25:17,  2.79it/s]

IN_9324_2011 completed in 0:00:00.499957

  1%|          | 53/4292 [00:18<29:03,  2.43it/s]

IN_15470_2011 completed in 0:00:00.534681

  1%|▏         | 55/4292 [00:18<21:58,  3.21it/s]

IN_17633_2011 completed in 0:00:00.245434
KS_10005_2011 completed in 0:00:00.192163

  1%|▏         | 56/4292 [00:19<22:51,  3.09it/s]

KS_22500_2011 completed in 0:00:00.351949

  1%|▏         | 57/4292 [00:19<21:10,  3.33it/s]

KY_10171_2011 completed in 0:00:00.244091

  1%|▏         | 58/4292 [00:19<20:35,  3.43it/s]

KY_11249_2011 completed in 0:00:00.271589

  1%|▏         | 59/4292 [00:19<22:11,  3.18it/s]

KY_19446_2011 completed in 0:00:00.364831

  1%|▏         | 60/4292 [00:20<21:53,  3.22it/s]

KY_49998_2011 completed in 0:00:00.299773

  1%|▏         | 61/4292 [00:20<19:51,  3.55it/s]

LA_11241_2011 completed in 0:00:00.213397
LA_13478_2011 completed in 0:00:00.203755

  1%|▏         | 63/4292 [00:20<19:10,  3.68it/s]

LA_17698_2011 completed in 0:00:00.300283

  2%|▏         | 65/4292 [00:21<17:32,  4.02it/s]

LA_55936_2011 completed in 0:00:00.265703
MA_6374_2011 completed in 0:00:00.198161

  2%|▏         | 66/4292 [00:21<16:00,  4.40it/s]

MA_8774_2011 completed in 0:00:00.175166

  2%|▏         | 68/4292 [00:22<16:15,  4.33it/s]

MA_11804_2011 completed in 0:00:00.338492
MA_13206_2011 completed in 0:00:00.160492

  2%|▏         | 69/4292 [00:22<20:19,  3.46it/s]

MD_1167_2011 completed in 0:00:00.423009

  2%|▏         | 70/4292 [00:22<20:08,  3.49it/s]

MD_5027_2011 completed in 0:00:00.279558

  2%|▏         | 71/4292 [00:23<19:46,  3.56it/s]

MD_15263_2011 completed in 0:00:00.267742

  2%|▏         | 72/4292 [00:23<19:16,  3.65it/s]

MD_15270_2011 completed in 0:00:00.257068

  2%|▏         | 73/4292 [00:23<21:28,  3.28it/s]

ME_3266_2011 completed in 0:00:00.377366

  2%|▏         | 74/4292 [00:24<24:15,  2.90it/s]

MI_392_2011 completed in 0:00:00.436929

  2%|▏         | 75/4292 [00:24<25:32,  2.75it/s]

MI_3828_2011 completed in 0:00:00.405692

  2%|▏         | 76/4292 [00:24<24:32,  2.86it/s]

MI_4254_2011 completed in 0:00:00.315624

  2%|▏         | 77/4292 [00:25<24:07,  2.91it/s]

MI_5109_2011 completed in 0:00:00.328839

  2%|▏         | 78/4292 [00:25<27:21,  2.57it/s]

MI_9324_2011 completed in 0:00:00.496257

  2%|▏         | 80/4292 [00:26<22:25,  3.13it/s]

MI_19578_2011 completed in 0:00:00.358352
MI_20847_2011 completed in 0:00:00.174970

  2%|▏         | 81/4292 [00:26<21:31,  3.26it/s]

MI_20860_2011 completed in 0:00:00.275343

  2%|▏         | 82/4292 [00:26<20:31,  3.42it/s]

MN_5574_2011 completed in 0:00:00.258527

  2%|▏         | 83/4292 [00:26<18:46,  3.74it/s]

MN_12647_2011 completed in 0:00:00.208362

  2%|▏         | 85/4292 [00:27<21:13,  3.30it/s]

MN_14232_2011 completed in 0:00:00.547447
MN_17267_2011 completed in 0:00:00.186803

  2%|▏         | 86/4292 [00:28<20:36,  3.40it/s]

MN_25177_2011 completed in 0:00:00.272467

  2%|▏         | 87/4292 [00:28<19:19,  3.63it/s]

MO_4675_2011 completed in 0:00:00.232015

  2%|▏         | 88/4292 [00:28<17:53,  3.92it/s]

MO_5860_2011 completed in 0:00:00.206813

  2%|▏         | 89/4292 [00:28<18:04,  3.88it/s]

MO_10000_2011 completed in 0:00:00.262842

  2%|▏         | 90/4292 [00:29<27:00,  2.59it/s]

MO_12698_2011 completed in 0:00:00.683059

  2%|▏         | 91/4292 [00:29<26:21,  2.66it/s]

MO_17833_2011 completed in 0:00:00.353703

  2%|▏         | 92/4292 [00:30<38:45,  1.81it/s]

MO_19436_2011 completed in 0:00:00.965648

  2%|▏         | 94/4292 [00:31<26:01,  2.69it/s]

MT_6395_2011 completed in 0:00:00.244356
MT_12692_2011 completed in 0:00:00.163045

  2%|▏         | 96/4292 [00:31<20:29,  3.41it/s]

MT_12825_2011 completed in 0:00:00.251019
MT_20997_2011 completed in 0:00:00.192335

  2%|▏         | 98/4292 [00:31<17:25,  4.01it/s]

NC_3046_2011 completed in 0:00:00.221269
NC_5416_2011 completed in 0:00:00.196177

  2%|▏         | 99/4292 [00:32<17:23,  4.02it/s]

NC_9837_2011 completed in 0:00:00.246890

  2%|▏         | 100/4292 [00:32<17:27,  4.00it/s]

NC_16496_2011 completed in 0:00:00.251309

  2%|▏         | 101/4292 [00:32<16:36,  4.21it/s]

NC_19876_2011 completed in 0:00:00.208370

  2%|▏         | 102/4292 [00:33<21:54,  3.19it/s]

ND_12087_2011 completed in 0:00:00.490192

  2%|▏         | 103/4292 [00:33<20:30,  3.40it/s]

ND_14232_2011 completed in 0:00:00.246017

  2%|▏         | 105/4292 [00:33<17:13,  4.05it/s]

ND_24949_2011 completed in 0:00:00.233471
NE_11018_2011 completed in 0:00:00.178491

  2%|▏         | 107/4292 [00:34<15:08,  4.61it/s]

NE_17642_2011 completed in 0:00:00.214091
NH_13441_2011 completed in 0:00:00.168854

  3%|▎         | 108/4292 [00:34<16:31,  4.22it/s]

NH_15472_2011 completed in 0:00:00.282674

  3%|▎         | 109/4292 [00:35<24:05,  2.89it/s]

NH_24590_2011 completed in 0:00:00.597802

  3%|▎         | 110/4292 [00:35<22:24,  3.11it/s]

NH_26510_2011 completed in 0:00:00.264647

  3%|▎         | 111/4292 [00:35<24:01,  2.90it/s]

NJ_963_2011 completed in 0:00:00.397809

  3%|▎         | 113/4292 [00:36<18:27,  3.77it/s]

NJ_9726_2011 completed in 0:00:00.209415
NJ_16213_2011 completed in 0:00:00.172418

  3%|▎         | 114/4292 [00:36<18:01,  3.86it/s]

NM_5701_2011 completed in 0:00:00.243856

  3%|▎         | 115/4292 [00:36<18:53,  3.68it/s]

NM_6204_2011 completed in 0:00:00.299656

  3%|▎         | 116/4292 [00:36<18:25,  3.78it/s]

NM_9699_2011 completed in 0:00:00.248570

  3%|▎         | 118/4292 [00:37<15:59,  4.35it/s]

NM_11204_2011 completed in 0:00:00.268198
NV_2008_2011 completed in 0:00:00.144696

  3%|▎         | 119/4292 [00:37<15:10,  4.58it/s]

NV_13407_2011 completed in 0:00:00.190353

  3%|▎         | 120/4292 [00:37<14:58,  4.64it/s]

NV_17166_2011 completed in 0:00:00.207562

  3%|▎         | 121/4292 [00:38<16:52,  4.12it/s]

NV_19840_2011 completed in 0:00:00.305431

  3%|▎         | 122/4292 [00:38<17:53,  3.88it/s]

NY_3249_2011 completed in 0:00:00.291107

  3%|▎         | 124/4292 [00:38<17:49,  3.90it/s]

NY_13511_2011 completed in 0:00:00.340100
NY_14154_2011 completed in 0:00:00.194787

  3%|▎         | 125/4292 [00:39<21:06,  3.29it/s]

OH_3542_2011 completed in 0:00:00.412902

  3%|▎         | 126/4292 [00:39<22:42,  3.06it/s]

OH_3755_2011 completed in 0:00:00.375896

  3%|▎         | 127/4292 [00:39<21:55,  3.17it/s]

OH_4922_2011 completed in 0:00:00.287799

  3%|▎         | 128/4292 [00:40<19:42,  3.52it/s]

OH_13998_2011 completed in 0:00:00.206846

  3%|▎         | 130/4292 [00:40<17:54,  3.87it/s]

OH_14006_2011 completed in 0:00:00.293227
OH_18997_2011 completed in 0:00:00.190427

  3%|▎         | 131/4292 [00:40<18:24,  3.77it/s]

OK_13734_2011 completed in 0:00:00.281514

  3%|▎         | 132/4292 [00:41<18:37,  3.72it/s]

OK_14063_2011 completed in 0:00:00.275260

  3%|▎         | 133/4292 [00:41<17:55,  3.87it/s]

OK_15474_2011 completed in 0:00:00.234426

  3%|▎         | 135/4292 [00:41<16:15,  4.26it/s]

OR_6022_2011 completed in 0:00:00.301709
OR_9191_2011 completed in 0:00:00.146899

  3%|▎         | 137/4292 [00:42<15:45,  4.39it/s]

OR_14354_2011 completed in 0:00:00.302441
OR_15248_2011 completed in 0:00:00.162227

  3%|▎         | 138/4292 [00:42<13:51,  5.00it/s]

OR_40437_2011 completed in 0:00:00.135413

  3%|▎         | 139/4292 [00:42<14:38,  4.73it/s]

PA_3597_2011 completed in 0:00:00.236985

  3%|▎         | 141/4292 [00:43<14:02,  4.93it/s]

PA_5487_2011 completed in 0:00:00.209741
PA_12390_2011 completed in 0:00:00.182734

  3%|▎         | 143/4292 [00:43<13:44,  5.03it/s]

PA_14711_2011 completed in 0:00:00.214516
PA_14715_2011 completed in 0:00:00.179231

  3%|▎         | 144/4292 [00:43<13:40,  5.06it/s]

PA_14716_2011 completed in 0:00:00.194359

  3%|▎         | 145/4292 [00:44<15:38,  4.42it/s]

PA_14940_2011 completed in 0:00:00.291955

  3%|▎         | 146/4292 [00:44<15:17,  4.52it/s]

PA_15045_2011 completed in 0:00:00.208375

  3%|▎         | 148/4292 [00:44<14:18,  4.83it/s]

PA_19390_2011 completed in 0:00:00.207840
PA_20334_2011 completed in 0:00:00.182433

  3%|▎         | 149/4292 [00:44<14:59,  4.61it/s]

PA_20387_2011 completed in 0:00:00.239061

  3%|▎         | 150/4292 [00:45<15:16,  4.52it/s]

RI_1857_2011 completed in 0:00:00.229956

  4%|▎         | 151/4292 [00:45<15:51,  4.35it/s]

RI_13214_2011 completed in 0:00:00.248944

  4%|▎         | 152/4292 [00:45<17:07,  4.03it/s]

SC_3046_2011 completed in 0:00:00.290120

  4%|▎         | 153/4292 [00:45<16:43,  4.13it/s]

SC_5416_2011 completed in 0:00:00.228147

  4%|▎         | 154/4292 [00:46<16:48,  4.10it/s]

SC_17539_2011 completed in 0:00:00.245881

  4%|▎         | 155/4292 [00:46<19:47,  3.48it/s]

SC_17543_2011 completed in 0:00:00.387217

  4%|▎         | 156/4292 [00:46<19:02,  3.62it/s]

SD_14232_2011 completed in 0:00:00.250065

  4%|▎         | 158/4292 [00:47<16:08,  4.27it/s]

SD_19545_2011 completed in 0:00:00.235549
SD_20401_2011 completed in 0:00:00.163069

  4%|▎         | 160/4292 [00:47<14:57,  4.60it/s]

TX_5701_2011 completed in 0:00:00.252467
TX_17698_2011 completed in 0:00:00.163743

  4%|▍         | 162/4292 [00:47<14:13,  4.84it/s]

TX_55937_2011 completed in 0:00:00.231592
UT_2010_2011 completed in 0:00:00.170918

  4%|▍         | 163/4292 [00:48<15:22,  4.48it/s]

UT_12866_2011 completed in 0:00:00.261012

  4%|▍         | 165/4292 [00:48<14:58,  4.59it/s]

UT_14354_2011 completed in 0:00:00.273412
UT_15444_2011 completed in 0:00:00.167989

  4%|▍         | 167/4292 [00:49<13:22,  5.14it/s]

UT_17845_2011 completed in 0:00:00.181718
UT_17874_2011 completed in 0:00:00.164409

  4%|▍         | 168/4292 [00:49<14:46,  4.65it/s]

VA_733_2011 completed in 0:00:00.261389

  4%|▍         | 169/4292 [00:49<15:17,  4.49it/s]

VA_17066_2011 completed in 0:00:00.239204

  4%|▍         | 171/4292 [00:50<15:29,  4.43it/s]

VA_19876_2011 completed in 0:00:00.282421
VA_40228_2011 completed in 0:00:00.188756

  4%|▍         | 172/4292 [00:50<18:34,  3.70it/s]

VT_2548_2011 completed in 0:00:00.374327

  4%|▍         | 173/4292 [00:50<17:44,  3.87it/s]

VT_7601_2011 completed in 0:00:00.228823

  4%|▍         | 174/4292 [00:50<17:54,  3.83it/s]

VT_19791_2011 completed in 0:00:00.265189

  4%|▍         | 175/4292 [00:51<17:01,  4.03it/s]

WA_3660_2011 completed in 0:00:00.216828

  4%|▍         | 176/4292 [00:51<17:40,  3.88it/s]

WA_15500_2011 completed in 0:00:00.278008

  4%|▍         | 177/4292 [00:51<16:33,  4.14it/s]

WA_17470_2011 completed in 0:00:00.202034

  4%|▍         | 179/4292 [00:52<16:45,  4.09it/s]

WA_18429_2011 completed in 0:00:00.366505
WA_20169_2011 completed in 0:00:00.160624

  4%|▍         | 180/4292 [00:52<15:30,  4.42it/s]

WI_11479_2011 completed in 0:00:00.182544

  4%|▍         | 182/4292 [00:52<14:34,  4.70it/s]

WI_13697_2011 completed in 0:00:00.214566
WI_13815_2011 completed in 0:00:00.185780

  4%|▍         | 183/4292 [00:53<17:28,  3.92it/s]

WI_20847_2011 completed in 0:00:00.353633

  4%|▍         | 184/4292 [00:53<17:41,  3.87it/s]

WI_20856_2011 completed in 0:00:00.264796

  4%|▍         | 185/4292 [00:53<17:25,  3.93it/s]

WI_20860_2011 completed in 0:00:00.244430

  4%|▍         | 186/4292 [00:53<17:50,  3.83it/s]

WV_733_2011 completed in 0:00:00.274205

  4%|▍         | 187/4292 [00:54<19:04,  3.59it/s]

WV_12796_2011 completed in 0:00:00.320300

  4%|▍         | 188/4292 [00:54<21:41,  3.15it/s]

WV_20521_2011 completed in 0:00:00.405641

  4%|▍         | 190/4292 [00:55<18:54,  3.62it/s]

WY_3461_2011 completed in 0:00:00.304043
WY_8566_2011 completed in 0:00:00.189485

  4%|▍         | 191/4292 [00:55<19:03,  3.59it/s]

WY_14354_2011 completed in 0:00:00.283009

  4%|▍         | 193/4292 [00:55<16:33,  4.13it/s]

WY_19156_2011 completed in 0:00:00.231931
WY_27058_2011 completed in 0:00:00.188775

  5%|▍         | 195/4292 [00:56<14:40,  4.66it/s]

AK_3522_2011 completed in 0:00:00.189025
AR_3093_2011 completed in 0:00:00.186232

  5%|▍         | 196/4292 [00:56<14:47,  4.62it/s]

FL_6457_2011 completed in 0:00:00.219956

  5%|▍         | 198/4292 [00:56<14:28,  4.72it/s]

MN_9417_2011 completed in 0:00:00.252945
NM_22690_2011 completed in 0:00:00.174212

  5%|▍         | 200/4292 [00:57<14:36,  4.67it/s]

TN_10331_2011 completed in 0:00:00.243426
TX_17008_2011 completed in 0:00:00.195255

  5%|▍         | 202/4292 [00:57<13:56,  4.89it/s]

WA_14354_2011 completed in 0:00:00.207340
WI_4715_2011 completed in 0:00:00.185183

  5%|▍         | 203/4292 [00:57<15:47,  4.31it/s]

AZ_19189_2011 completed in 0:00:00.294557

  5%|▍         | 205/4292 [00:58<16:46,  4.06it/s]

CT_4176_2011 completed in 0:00:00.357588
KY_22053_2011 completed in 0:00:00.190505

  5%|▍         | 207/4292 [00:59<17:25,  3.91it/s]

MA_20455_2011 completed in 0:00:00.360619
NJ_15477_2011 completed in 0:00:00.196944

  5%|▍         | 209/4292 [00:59<15:08,  4.49it/s]

NV_13073_2011 completed in 0:00:00.176450
SD_1769_2011 completed in 0:00:00.198986

  5%|▍         | 210/4292 [01:00<23:28,  2.90it/s]

CA_12745_2011 completed in 0:00:00.629772

  5%|▍         | 211/4292 [01:00<23:11,  2.93it/s]

MO_9231_2011 completed in 0:00:00.330187

  5%|▍         | 212/4292 [01:00<24:26,  2.78it/s]

IN_13756_2011 completed in 0:00:00.401874

  5%|▍         | 213/4292 [01:01<21:18,  3.19it/s]

TN_12293_2011 completed in 0:00:00.205407

  5%|▌         | 215/4292 [01:01<17:58,  3.78it/s]

KS_10000_2011 completed in 0:00:00.252752
NC_24889_2011 completed in 0:00:00.190637

  5%|▌         | 216/4292 [01:01<16:48,  4.04it/s]

CO_27058_2011 completed in 0:00:00.206937

  5%|▌         | 217/4292 [01:01<16:02,  4.24it/s]

ID_10454_2011 completed in 0:00:00.208800

  5%|▌         | 218/4292 [01:02<16:55,  4.01it/s]

IL_13032_2011 completed in 0:00:00.278812

  5%|▌         | 219/4292 [01:02<19:46,  3.43it/s]

AK_3522_2012 completed in 0:00:00.388737

  5%|▌         | 221/4292 [01:02<16:56,  4.01it/s]

AK_7353_2012 completed in 0:00:00.234458
AK_19558_2012 completed in 0:00:00.190196

  5%|▌         | 222/4292 [01:03<18:27,  3.67it/s]

AR_814_2012 completed in 0:00:00.323200

  5%|▌         | 224/4292 [01:03<16:02,  4.23it/s]

AR_817_2012 completed in 0:00:00.254576
AR_3093_2012 completed in 0:00:00.164276

  5%|▌         | 225/4292 [01:04<17:21,  3.91it/s]

AR_6342_2012 completed in 0:00:00.300156

  5%|▌         | 226/4292 [01:04<16:38,  4.07it/s]

AR_14063_2012 completed in 0:00:00.216408

  5%|▌         | 227/4292 [01:04<17:41,  3.83it/s]

AR_17698_2012 completed in 0:00:00.296587

  5%|▌         | 229/4292 [01:04<15:07,  4.48it/s]

AZ_16572_2012 completed in 0:00:00.208965
AZ_19189_2012 completed in 0:00:00.170084

  5%|▌         | 230/4292 [01:05<17:10,  3.94it/s]

AZ_19728_2012 completed in 0:00:00.321057

  5%|▌         | 232/4292 [01:05<15:57,  4.24it/s]

AZ_21538_2012 completed in 0:00:00.257035
AZ_24211_2012 completed in 0:00:00.190291

  5%|▌         | 234/4292 [01:06<15:18,  4.42it/s]

CA_11208_2012 completed in 0:00:00.257849
CA_12745_2012 completed in 0:00:00.187648

  5%|▌         | 235/4292 [01:06<17:28,  3.87it/s]

CA_14328_2012 completed in 0:00:00.332374

  6%|▌         | 237/4292 [01:06<14:26,  4.68it/s]

CA_14354_2012 completed in 0:00:00.211775
CA_14534_2012 completed in 0:00:00.140516

  6%|▌         | 238/4292 [01:07<13:53,  4.86it/s]

CA_16534_2012 completed in 0:00:00.185760

  6%|▌         | 239/4292 [01:07<13:55,  4.85it/s]

CA_16609_2012 completed in 0:00:00.206762

  6%|▌         | 241/4292 [01:07<13:40,  4.94it/s]

CA_17609_2012 completed in 0:00:00.239035
CA_19281_2012 completed in 0:00:00.169863

  6%|▌         | 242/4292 [01:07<15:02,  4.49it/s]

CO_3989_2012 completed in 0:00:00.269057

  6%|▌         | 243/4292 [01:08<15:03,  4.48it/s]

CO_6604_2012 completed in 0:00:00.222669

  6%|▌         | 244/4292 [01:08<14:44,  4.58it/s]

CO_9336_2012 completed in 0:00:00.206994

  6%|▌         | 246/4292 [01:08<14:11,  4.75it/s]

CO_15257_2012 completed in 0:00:00.212916
CO_15466_2012 completed in 0:00:00.194197

  6%|▌         | 247/4292 [01:08<13:25,  5.02it/s]

CO_16603_2012 completed in 0:00:00.171807

  6%|▌         | 249/4292 [01:09<19:23,  3.48it/s]

CO_19499_2012 completed in 0:00:00.629741
CO_27058_2012 completed in 0:00:00.191719

  6%|▌         | 251/4292 [01:10<16:39,  4.04it/s]

CT_4176_2012 completed in 0:00:00.252563
CT_19497_2012 completed in 0:00:00.175789

  6%|▌         | 252/4292 [01:10<16:37,  4.05it/s]

DC_15270_2012 completed in 0:00:00.245330
DE_5027_2012 completed in 0:00:00.204376

  6%|▌         | 254/4292 [01:10<14:58,  4.49it/s]

DE_5070_2012 completed in 0:00:00.193935

  6%|▌         | 255/4292 [01:11<17:13,  3.90it/s]

DE_5335_2012 completed in 0:00:00.333544

  6%|▌         | 256/4292 [01:11<17:25,  3.86it/s]

FL_6452_2012 completed in 0:00:00.265424

  6%|▌         | 257/4292 [01:11<18:31,  3.63it/s]

FL_6455_2012 completed in 0:00:00.312412
FL_6457_2012 completed in 0:00:00.203936

  6%|▌         | 259/4292 [01:12<16:22,  4.11it/s]

FL_7801_2012 completed in 0:00:00.217838

  6%|▌         | 261/4292 [01:17<1:22:55,  1.23s/it]

FL_9617_2012 completed in 0:00:05.034667
FL_18454_2012 completed in 0:00:00.190183

  6%|▌         | 262/4292 [01:17<1:01:43,  1.09it/s]

GA_3916_2012 completed in 0:00:00.182253

  6%|▌         | 264/4292 [01:18<39:14,  1.71it/s]

GA_7140_2012 completed in 0:00:00.361797
HI_8287_2012 completed in 0:00:00.192840

  6%|▌         | 265/4292 [01:18<34:10,  1.96it/s]

HI_10071_2012 completed in 0:00:00.332430

  6%|▌         | 266/4292 [01:18<28:09,  2.38it/s]

HI_11843_2012 completed in 0:00:00.210260

  6%|▌         | 267/4292 [01:19<27:00,  2.48it/s]

HI_19547_2012 completed in 0:00:00.361669

  6%|▌         | 268/4292 [01:19<24:06,  2.78it/s]

IA_9417_2012 completed in 0:00:00.258392

  6%|▋         | 269/4292 [01:19<22:02,  3.04it/s]

IA_12341_2012 completed in 0:00:00.256163

  6%|▋         | 270/4292 [01:19<20:03,  3.34it/s]

ID_9191_2012 completed in 0:00:00.229248

  6%|▋         | 271/4292 [01:19<18:42,  3.58it/s]

ID_10454_2012 completed in 0:00:00.231401

  6%|▋         | 272/4292 [01:20<18:07,  3.69it/s]

ID_14354_2012 completed in 0:00:00.249851
ID_20169_2012 completed in 0:00:00.201562

  6%|▋         | 275/4292 [01:20<15:21,  4.36it/s]

IL_4110_2012 completed in 0:00:00.265889
IL_12341_2012 completed in 0:00:00.168669

  6%|▋         | 276/4292 [01:21<15:22,  4.36it/s]

IL_13032_2012 completed in 0:00:00.229067

  6%|▋         | 277/4292 [01:21<15:38,  4.28it/s]

IN_9273_2012 completed in 0:00:00.242376

  7%|▋         | 279/4292 [01:21<14:34,  4.59it/s]

IN_9324_2012 completed in 0:00:00.227438
IN_13756_2012 completed in 0:00:00.183802

  7%|▋         | 280/4292 [01:22<15:45,  4.24it/s]

IN_15470_2012 completed in 0:00:00.276790

  7%|▋         | 281/4292 [01:22<17:12,  3.88it/s]

IN_17633_2012 completed in 0:00:00.307401

  7%|▋         | 282/4292 [01:22<17:00,  3.93it/s]

KS_10000_2012 completed in 0:00:00.246420

  7%|▋         | 283/4292 [01:22<18:01,  3.71it/s]

KS_10005_2012 completed in 0:00:00.304948

  7%|▋         | 284/4292 [01:23<20:13,  3.30it/s]

KS_22500_2012 completed in 0:00:00.378926

  7%|▋         | 286/4292 [01:23<18:13,  3.66it/s]

KY_10171_2012 completed in 0:00:00.308376
KY_11249_2012 completed in 0:00:00.198428

  7%|▋         | 287/4292 [01:23<16:39,  4.01it/s]

KY_19446_2012 completed in 0:00:00.193530

  7%|▋         | 288/4292 [01:24<17:27,  3.82it/s]

KY_22053_2012 completed in 0:00:00.289307

  7%|▋         | 289/4292 [01:24<18:21,  3.63it/s]

KY_49998_2012 completed in 0:00:00.305954

  7%|▋         | 290/4292 [01:24<18:26,  3.62it/s]

LA_11241_2012 completed in 0:00:00.278945

  7%|▋         | 291/4292 [01:25<17:25,  3.83it/s]

LA_13478_2012 completed in 0:00:00.224956

  7%|▋         | 292/4292 [01:25<16:24,  4.06it/s]

LA_17698_2012 completed in 0:00:00.209432

  7%|▋         | 294/4292 [01:25<16:21,  4.07it/s]

LA_55936_2012 completed in 0:00:00.332558
MA_6374_2012 completed in 0:00:00.182149

  7%|▋         | 295/4292 [01:26<17:37,  3.78it/s]

MA_11804_2012 completed in 0:00:00.308558

  7%|▋         | 296/4292 [01:26<17:10,  3.88it/s]

MA_13206_2012 completed in 0:00:00.240907
MA_20455_2012 completed in 0:00:00.202344

  7%|▋         | 298/4292 [01:26<14:58,  4.45it/s]

MD_1167_2012 completed in 0:00:00.185823

  7%|▋         | 300/4292 [01:27<14:18,  4.65it/s]

MD_5027_2012 completed in 0:00:00.225274
MD_15263_2012 completed in 0:00:00.189946

  7%|▋         | 301/4292 [01:27<14:15,  4.66it/s]

MD_15270_2012 completed in 0:00:00.212157

  7%|▋         | 302/4292 [01:27<18:20,  3.62it/s]

ME_3266_2012 completed in 0:00:00.418124

  7%|▋         | 303/4292 [01:28<17:20,  3.83it/s]

MI_392_2012 completed in 0:00:00.222160

  7%|▋         | 304/4292 [01:28<16:24,  4.05it/s]

MI_3828_2012 completed in 0:00:00.210962

  7%|▋         | 305/4292 [01:28<17:01,  3.90it/s]

MI_4254_2012 completed in 0:00:00.277150

  7%|▋         | 306/4292 [01:28<16:45,  3.97it/s]

MI_5109_2012 completed in 0:00:00.241497

  7%|▋         | 307/4292 [01:28<16:11,  4.10it/s]

MI_9324_2012 completed in 0:00:00.223031
MI_19578_2012 completed in 0:00:00.201988

  7%|▋         | 309/4292 [01:29<15:00,  4.42it/s]

MI_20847_2012 completed in 0:00:00.210061

  7%|▋         | 310/4292 [01:29<15:48,  4.20it/s]

MI_20860_2012 completed in 0:00:00.265383

  7%|▋         | 311/4292 [01:29<16:45,  3.96it/s]

MN_5574_2012 completed in 0:00:00.284597

  7%|▋         | 312/4292 [01:30<16:21,  4.06it/s]

MN_9417_2012 completed in 0:00:00.231483

  7%|▋         | 313/4292 [01:30<16:12,  4.09it/s]

MN_12647_2012 completed in 0:00:00.239079

  7%|▋         | 314/4292 [01:30<16:05,  4.12it/s]

MN_13781_2012 completed in 0:00:00.236801

  7%|▋         | 315/4292 [01:30<15:32,  4.27it/s]

MN_14232_2012 completed in 0:00:00.214491

  7%|▋         | 316/4292 [01:31<17:18,  3.83it/s]

MN_17267_2012 completed in 0:00:00.322758

  7%|▋         | 318/4292 [01:31<15:20,  4.32it/s]

MN_25177_2012 completed in 0:00:00.215747
MO_4675_2012 completed in 0:00:00.192597

  7%|▋         | 319/4292 [01:31<14:11,  4.67it/s]

MO_5860_2012 completed in 0:00:00.172507

  7%|▋         | 320/4292 [01:32<15:33,  4.25it/s]

MO_9231_2012 completed in 0:00:00.282598

  7%|▋         | 321/4292 [01:32<15:41,  4.22it/s]

MO_10000_2012 completed in 0:00:00.240718

  8%|▊         | 323/4292 [01:32<14:20,  4.61it/s]

MO_12698_2012 completed in 0:00:00.229257
MO_17833_2012 completed in 0:00:00.173660

  8%|▊         | 324/4292 [01:33<15:45,  4.20it/s]

MO_19436_2012 completed in 0:00:00.287034

  8%|▊         | 325/4292 [01:33<17:34,  3.76it/s]

MT_6395_2012 completed in 0:00:00.329688

  8%|▊         | 326/4292 [01:33<16:39,  3.97it/s]

MT_12692_2012 completed in 0:00:00.218472

  8%|▊         | 327/4292 [01:33<17:12,  3.84it/s]

MT_12825_2012 completed in 0:00:00.279218

  8%|▊         | 328/4292 [01:34<16:18,  4.05it/s]

MT_20997_2012 completed in 0:00:00.214033

  8%|▊         | 330/4292 [01:34<17:51,  3.70it/s]

NC_3046_2012 completed in 0:00:00.434476
NC_5416_2012 completed in 0:00:00.192728

  8%|▊         | 331/4292 [01:35<18:50,  3.50it/s]

NC_9837_2012 completed in 0:00:00.319758

  8%|▊         | 332/4292 [01:35<17:34,  3.75it/s]

NC_16496_2012 completed in 0:00:00.221116

  8%|▊         | 333/4292 [01:35<26:56,  2.45it/s]

NC_19876_2012 completed in 0:00:00.737721

  8%|▊         | 335/4292 [01:36<19:45,  3.34it/s]

NC_24889_2012 completed in 0:00:00.236812
ND_12087_2012 completed in 0:00:00.164280

  8%|▊         | 337/4292 [01:36<17:09,  3.84it/s]

ND_14232_2012 completed in 0:00:00.259318
ND_24949_2012 completed in 0:00:00.195828

  8%|▊         | 339/4292 [01:37<15:18,  4.30it/s]

NE_11018_2012 completed in 0:00:00.224435
NE_17642_2012 completed in 0:00:00.190409

  8%|▊         | 340/4292 [01:37<15:05,  4.36it/s]

NH_13441_2012 completed in 0:00:00.220960

  8%|▊         | 341/4292 [01:37<16:05,  4.09it/s]

NH_15472_2012 completed in 0:00:00.278838

  8%|▊         | 343/4292 [01:38<15:22,  4.28it/s]

NH_24590_2012 completed in 0:00:00.275265
NH_26510_2012 completed in 0:00:00.185374

  8%|▊         | 344/4292 [01:38<15:33,  4.23it/s]

NJ_963_2012 completed in 0:00:00.242217

  8%|▊         | 345/4292 [01:38<18:23,  3.58it/s]

NJ_9726_2012 completed in 0:00:00.379088

  8%|▊         | 347/4292 [01:39<15:55,  4.13it/s]

NJ_15477_2012 completed in 0:00:00.216045
NJ_16213_2012 completed in 0:00:00.197509

  8%|▊         | 348/4292 [01:39<14:45,  4.45it/s]

NM_5701_2012 completed in 0:00:00.182796

  8%|▊         | 349/4292 [01:39<15:48,  4.15it/s]

NM_6204_2012 completed in 0:00:00.277327

  8%|▊         | 350/4292 [01:39<15:41,  4.19it/s]

NM_11204_2012 completed in 0:00:00.233437

  8%|▊         | 352/4292 [01:40<14:31,  4.52it/s]

NM_17718_2012 completed in 0:00:00.229080
NM_22690_2012 completed in 0:00:00.184847

  8%|▊         | 353/4292 [01:40<21:21,  3.07it/s]

NV_2008_2012 completed in 0:00:00.565007

  8%|▊         | 355/4292 [01:41<17:52,  3.67it/s]

NV_13073_2012 completed in 0:00:00.278469
NV_13407_2012 completed in 0:00:00.180211

  8%|▊         | 356/4292 [01:41<21:15,  3.09it/s]

NV_17166_2012 completed in 0:00:00.442562

  8%|▊         | 357/4292 [01:42<20:14,  3.24it/s]

NV_19840_2012 completed in 0:00:00.269532

  8%|▊         | 358/4292 [01:42<19:57,  3.28it/s]

NY_3249_2012 completed in 0:00:00.291616

  8%|▊         | 360/4292 [01:42<17:35,  3.73it/s]

NY_13511_2012 completed in 0:00:00.311277
NY_14154_2012 completed in 0:00:00.178270

  8%|▊         | 361/4292 [01:43<16:29,  3.97it/s]

OH_3542_2012 completed in 0:00:00.211997

  8%|▊         | 362/4292 [01:43<21:49,  3.00it/s]

OH_3755_2012 completed in 0:00:00.522330
OH_4922_2012 completed in 0:00:00.200443

  8%|▊         | 364/4292 [01:44<18:30,  3.54it/s]

OH_13998_2012 completed in 0:00:00.255951

  9%|▊         | 365/4292 [01:44<17:40,  3.70it/s]

OH_14006_2012 completed in 0:00:00.239657
OH_18997_2012 completed in 0:00:00.204780

  9%|▊         | 367/4292 [01:44<19:37,  3.33it/s]

OK_13734_2012 completed in 0:00:00.412546

  9%|▊         | 368/4292 [01:45<18:22,  3.56it/s]

OK_14063_2012 completed in 0:00:00.235269

  9%|▊         | 370/4292 [01:45<16:55,  3.86it/s]

OK_15474_2012 completed in 0:00:00.321571
OR_6022_2012 completed in 0:00:00.178014

  9%|▊         | 371/4292 [01:46<17:57,  3.64it/s]

OR_9191_2012 completed in 0:00:00.310783

  9%|▊         | 373/4292 [01:46<14:46,  4.42it/s]

OR_14354_2012 completed in 0:00:00.209367
OR_15248_2012 completed in 0:00:00.157257

  9%|▊         | 374/4292 [01:46<13:30,  4.83it/s]

OR_40437_2012 completed in 0:00:00.160931

  9%|▊         | 375/4292 [01:46<18:10,  3.59it/s]

PA_3597_2012 completed in 0:00:00.444153

  9%|▉         | 376/4292 [01:47<17:36,  3.71it/s]

PA_5487_2012 completed in 0:00:00.249022

  9%|▉         | 377/4292 [01:47<17:21,  3.76it/s]

PA_12390_2012 completed in 0:00:00.256535

  9%|▉         | 379/4292 [01:47<15:26,  4.22it/s]

PA_14711_2012 completed in 0:00:00.240721
PA_14715_2012 completed in 0:00:00.184452

  9%|▉         | 380/4292 [01:48<15:58,  4.08it/s]

PA_14716_2012 completed in 0:00:00.263267

  9%|▉         | 381/4292 [01:48<16:58,  3.84it/s]

PA_14940_2012 completed in 0:00:00.295295

  9%|▉         | 383/4292 [01:48<14:36,  4.46it/s]

PA_15045_2012 completed in 0:00:00.202345
PA_19390_2012 completed in 0:00:00.178138

  9%|▉         | 385/4292 [01:49<13:27,  4.84it/s]

PA_20334_2012 completed in 0:00:00.202033
PA_20387_2012 completed in 0:00:00.179869

  9%|▉         | 387/4292 [01:49<12:09,  5.36it/s]

RI_1857_2012 completed in 0:00:00.191110
RI_13214_2012 completed in 0:00:00.149648

  9%|▉         | 389/4292 [01:49<11:41,  5.56it/s]

SC_3046_2012 completed in 0:00:00.220079
SC_5416_2012 completed in 0:00:00.138547

  9%|▉         | 391/4292 [01:50<11:02,  5.89it/s]

SC_17539_2012 completed in 0:00:00.185818
SC_17543_2012 completed in 0:00:00.140276

  9%|▉         | 392/4292 [01:50<15:53,  4.09it/s]

SD_1769_2012 completed in 0:00:00.417878

  9%|▉         | 394/4292 [01:51<14:52,  4.37it/s]

SD_14232_2012 completed in 0:00:00.243143
SD_20401_2012 completed in 0:00:00.192730

  9%|▉         | 395/4292 [01:51<13:23,  4.85it/s]

TN_10331_2012 completed in 0:00:00.151856

  9%|▉         | 397/4292 [01:51<13:30,  4.81it/s]

TX_5701_2012 completed in 0:00:00.241020
TX_16604_2012 completed in 0:00:00.186491

  9%|▉         | 398/4292 [01:52<31:25,  2.07it/s]

TX_17008_2012 completed in 0:00:01.127250

  9%|▉         | 399/4292 [01:53<27:18,  2.38it/s]

TX_17698_2012 completed in 0:00:00.271585

  9%|▉         | 400/4292 [01:53<23:07,  2.81it/s]

TX_55937_2012 completed in 0:00:00.203679

  9%|▉         | 401/4292 [01:53<20:26,  3.17it/s]

UT_2010_2012 completed in 0:00:00.217730

  9%|▉         | 402/4292 [01:53<18:34,  3.49it/s]

UT_14354_2012 completed in 0:00:00.218666
UT_15444_2012 completed in 0:00:00.200564

  9%|▉         | 404/4292 [01:54<17:17,  3.75it/s]

UT_17845_2012 completed in 0:00:00.276646

  9%|▉         | 405/4292 [01:54<18:13,  3.55it/s]

UT_17874_2012 completed in 0:00:00.312524

  9%|▉         | 406/4292 [01:54<17:08,  3.78it/s]

VA_733_2012 completed in 0:00:00.224382

  9%|▉         | 407/4292 [01:55<16:20,  3.96it/s]

VA_17066_2012 completed in 0:00:00.222905

 10%|▉         | 409/4292 [01:55<15:41,  4.12it/s]

VA_19876_2012 completed in 0:00:00.296054
VA_40228_2012 completed in 0:00:00.187453

 10%|▉         | 411/4292 [01:55<13:44,  4.71it/s]

VT_2548_2012 completed in 0:00:00.202384
VT_7601_2012 completed in 0:00:00.168753

 10%|▉         | 413/4292 [01:56<15:23,  4.20it/s]

VT_19791_2012 completed in 0:00:00.365046
WA_3660_2012 completed in 0:00:00.189936

 10%|▉         | 414/4292 [01:56<15:06,  4.28it/s]

WA_14354_2012 completed in 0:00:00.222495

 10%|▉         | 416/4292 [01:57<14:48,  4.36it/s]

WA_15500_2012 completed in 0:00:00.270951
WA_17470_2012 completed in 0:00:00.191524

 10%|▉         | 417/4292 [01:57<14:14,  4.54it/s]

WA_18429_2012 completed in 0:00:00.198790

 10%|▉         | 418/4292 [01:57<14:00,  4.61it/s]

WA_20169_2012 completed in 0:00:00.208091

 10%|▉         | 420/4292 [01:57<13:16,  4.86it/s]

WI_4715_2012 completed in 0:00:00.208126
WI_11479_2012 completed in 0:00:00.183743

 10%|▉         | 421/4292 [01:58<12:37,  5.11it/s]

WI_13697_2012 completed in 0:00:00.171689

 10%|▉         | 422/4292 [01:58<16:15,  3.97it/s]

WI_13815_2012 completed in 0:00:00.382263

 10%|▉         | 423/4292 [01:58<19:01,  3.39it/s]

WI_20847_2012 completed in 0:00:00.394250
WI_20856_2012 completed in 0:00:00.202984

 10%|▉         | 425/4292 [01:59<17:41,  3.64it/s]

WI_20860_2012 completed in 0:00:00.289209

 10%|▉         | 426/4292 [01:59<17:08,  3.76it/s]

WV_733_2012 completed in 0:00:00.245487

 10%|▉         | 428/4292 [02:00<15:24,  4.18it/s]

WV_12796_2012 completed in 0:00:00.282780
WV_20521_2012 completed in 0:00:00.163417

 10%|█         | 430/4292 [02:00<14:50,  4.34it/s]

WY_3461_2012 completed in 0:00:00.272389
WY_8566_2012 completed in 0:00:00.185314

 10%|█         | 431/4292 [02:00<14:37,  4.40it/s]

WY_14354_2012 completed in 0:00:00.218227

 10%|█         | 432/4292 [02:00<14:20,  4.48it/s]

WY_19156_2012 completed in 0:00:00.212410

 10%|█         | 434/4292 [02:01<13:04,  4.92it/s]

WY_27058_2012 completed in 0:00:00.239836
AK_11824_2012 completed in 0:00:00.143829

 10%|█         | 435/4292 [02:01<14:27,  4.45it/s]

NY_16183_2012 completed in 0:00:00.274551
AL_9094_2012 completed in 0:00:00.201329

 10%|█         | 438/4292 [02:02<13:30,  4.76it/s]

AL_9739_2012 completed in 0:00:00.225858
GA_3408_2012 completed in 0:00:00.185168

 10%|█         | 440/4292 [02:02<12:45,  5.03it/s]

KY_14724_2012 completed in 0:00:00.168054
KY_20130_2012 completed in 0:00:00.199623

 10%|█         | 441/4292 [02:02<13:47,  4.65it/s]

MS_6641_2012 completed in 0:00:00.251934

 10%|█         | 443/4292 [02:03<13:52,  4.62it/s]

TN_727_2012 completed in 0:00:00.245536
TN_2247_2012 completed in 0:00:00.196834

 10%|█         | 444/4292 [02:03<13:00,  4.93it/s]

TN_3408_2012 completed in 0:00:00.170648
TN_3812_2012 completed in 0:00:00.200974

 10%|█         | 447/4292 [02:04<12:59,  4.93it/s]

TN_4624_2012 completed in 0:00:00.245483
TN_5399_2012 completed in 0:00:00.171487

 10%|█         | 448/4292 [02:04<13:03,  4.91it/s]

TN_7174_2012 completed in 0:00:00.205591

 10%|█         | 450/4292 [02:04<12:37,  5.07it/s]

TN_7625_2012 completed in 0:00:00.213907
TN_9777_2012 completed in 0:00:00.172779

 11%|█         | 452/4292 [02:05<12:59,  4.93it/s]

TN_12470_2012 completed in 0:00:00.226601
TN_13216_2012 completed in 0:00:00.193838

 11%|█         | 453/4292 [02:05<13:58,  4.58it/s]

TN_17694_2012 completed in 0:00:00.253640

 11%|█         | 455/4292 [02:05<13:25,  4.76it/s]

TN_19574_2012 completed in 0:00:00.222336
TN_19898_2012 completed in 0:00:00.184198

 11%|█         | 456/4292 [02:05<12:52,  4.97it/s]

CT_20038_2012 completed in 0:00:00.179876

 11%|█         | 458/4292 [02:06<13:16,  4.81it/s]

AK_599_2013 completed in 0:00:00.237048
AK_3522_2013 completed in 0:00:00.195784

 11%|█         | 460/4292 [02:06<15:43,  4.06it/s]

AK_7353_2013 completed in 0:00:00.418887
AK_11824_2013 completed in 0:00:00.186506

 11%|█         | 461/4292 [02:07<16:21,  3.90it/s]

AK_19558_2013 completed in 0:00:00.277658

 11%|█         | 462/4292 [02:07<20:16,  3.15it/s]

AL_195_2013 completed in 0:00:00.456739

 11%|█         | 463/4292 [02:08<19:46,  3.23it/s]

AL_9094_2013 completed in 0:00:00.291123

 11%|█         | 464/4292 [02:08<19:33,  3.26it/s]

AL_9739_2013 completed in 0:00:00.297794

 11%|█         | 465/4292 [02:08<18:57,  3.36it/s]

AR_814_2013 completed in 0:00:00.274606

 11%|█         | 466/4292 [02:08<17:27,  3.65it/s]

AR_817_2013 completed in 0:00:00.218558

 11%|█         | 467/4292 [02:09<16:56,  3.76it/s]

AR_3093_2013 completed in 0:00:00.245574

 11%|█         | 468/4292 [02:09<16:26,  3.88it/s]

AR_6342_2013 completed in 0:00:00.238958

 11%|█         | 470/4292 [02:09<14:02,  4.53it/s]

AR_14063_2013 completed in 0:00:00.210081
AR_17698_2013 completed in 0:00:00.165259

 11%|█         | 471/4292 [02:09<14:16,  4.46it/s]

AZ_803_2013 completed in 0:00:00.232011

 11%|█         | 473/4292 [02:10<13:40,  4.66it/s]

AZ_16572_2013 completed in 0:00:00.295971
AZ_19189_2013 completed in 0:00:00.140846

 11%|█         | 475/4292 [02:10<12:43,  5.00it/s]

AZ_19728_2013 completed in 0:00:00.174330
AZ_21538_2013 completed in 0:00:00.192319

 11%|█         | 477/4292 [02:11<15:45,  4.03it/s]

AZ_24211_2013 completed in 0:00:00.446700
CA_9216_2013 completed in 0:00:00.185487

 11%|█         | 478/4292 [02:11<16:15,  3.91it/s]

CA_11208_2013 completed in 0:00:00.273240

 11%|█         | 479/4292 [02:11<15:34,  4.08it/s]

CA_12745_2013 completed in 0:00:00.219074

 11%|█         | 481/4292 [02:12<15:56,  3.99it/s]

CA_14328_2013 completed in 0:00:00.364069
CA_14354_2013 completed in 0:00:00.179832

 11%|█▏        | 483/4292 [02:12<13:19,  4.76it/s]

CA_14534_2013 completed in 0:00:00.193232
CA_16534_2013 completed in 0:00:00.153288

 11%|█▏        | 484/4292 [02:13<15:31,  4.09it/s]

CA_16609_2013 completed in 0:00:00.324670

 11%|█▏        | 485/4292 [02:13<15:59,  3.97it/s]

CA_17609_2013 completed in 0:00:00.268130

 11%|█▏        | 486/4292 [02:13<15:35,  4.07it/s]

CA_18260_2013 completed in 0:00:00.230697

 11%|█▏        | 488/4292 [02:13<13:58,  4.54it/s]

CA_19281_2013 completed in 0:00:00.211116
CO_3989_2013 completed in 0:00:00.183947

 11%|█▏        | 490/4292 [02:14<12:38,  5.01it/s]

CO_6604_2013 completed in 0:00:00.224496
CO_9336_2013 completed in 0:00:00.146087

 11%|█▏        | 491/4292 [02:14<12:39,  5.00it/s]

CO_12866_2013 completed in 0:00:00.200333

 11%|█▏        | 492/4292 [02:14<14:15,  4.44it/s]

CO_15257_2013 completed in 0:00:00.283056

 11%|█▏        | 493/4292 [02:15<14:18,  4.43it/s]

CO_15466_2013 completed in 0:00:00.227006
CO_16603_2013 completed in 0:00:00.201684

 12%|█▏        | 496/4292 [02:15<13:42,  4.62it/s]

CO_19499_2013 completed in 0:00:00.255191
CO_27058_2013 completed in 0:00:00.182134

 12%|█▏        | 497/4292 [02:15<13:40,  4.63it/s]

CT_4176_2013 completed in 0:00:00.213870

 12%|█▏        | 499/4292 [02:16<13:17,  4.76it/s]

CT_19497_2013 completed in 0:00:00.249576
CT_20038_2013 completed in 0:00:00.171495

 12%|█▏        | 501/4292 [02:16<12:31,  5.04it/s]

DC_15270_2013 completed in 0:00:00.200800
DE_5027_2013 completed in 0:00:00.176042

 12%|█▏        | 502/4292 [02:16<13:15,  4.76it/s]

DE_5070_2013 completed in 0:00:00.235913

 12%|█▏        | 503/4292 [02:17<13:42,  4.61it/s]

DE_5335_2013 completed in 0:00:00.232679

 12%|█▏        | 504/4292 [02:17<14:08,  4.46it/s]

DE_13519_2013 completed in 0:00:00.237487

 12%|█▏        | 505/4292 [02:17<13:54,  4.54it/s]

FL_6452_2013 completed in 0:00:00.208264

 12%|█▏        | 507/4292 [02:18<18:21,  3.44it/s]

FL_6455_2013 completed in 0:00:00.581361
FL_6457_2013 completed in 0:00:00.192881

 12%|█▏        | 509/4292 [02:18<15:04,  4.18it/s]

FL_7801_2013 completed in 0:00:00.183598
FL_9617_2013 completed in 0:00:00.187963

 12%|█▏        | 511/4292 [02:19<13:32,  4.65it/s]

FL_18454_2013 completed in 0:00:00.215922
GA_3408_2013 completed in 0:00:00.171566

 12%|█▏        | 512/4292 [02:19<13:11,  4.77it/s]

GA_3916_2013 completed in 0:00:00.195612

 12%|█▏        | 513/4292 [02:20<22:26,  2.81it/s]

GA_7140_2013 completed in 0:00:00.696698

 12%|█▏        | 514/4292 [02:20<20:55,  3.01it/s]

HI_8287_2013 completed in 0:00:00.275253

 12%|█▏        | 515/4292 [02:20<19:47,  3.18it/s]

HI_10071_2013 completed in 0:00:00.271635

 12%|█▏        | 517/4292 [02:21<19:49,  3.17it/s]

HI_11843_2013 completed in 0:00:00.487456
HI_19547_2013 completed in 0:00:00.194309

 12%|█▏        | 518/4292 [02:21<21:14,  2.96it/s]

IA_9417_2013 completed in 0:00:00.389480

 12%|█▏        | 519/4292 [02:21<19:18,  3.26it/s]

IA_12341_2013 completed in 0:00:00.234372
ID_9191_2013 completed in 0:00:00.201957

 12%|█▏        | 522/4292 [02:22<15:15,  4.12it/s]

ID_10454_2013 completed in 0:00:00.236474
ID_11273_2013 completed in 0:00:00.192492

 12%|█▏        | 523/4292 [02:22<15:32,  4.04it/s]

ID_14354_2013 completed in 0:00:00.257148

 12%|█▏        | 524/4292 [02:23<14:53,  4.22it/s]

ID_20169_2013 completed in 0:00:00.211828

 12%|█▏        | 525/4292 [02:23<14:45,  4.26it/s]

IL_4110_2013 completed in 0:00:00.229343

 12%|█▏        | 527/4292 [02:23<14:14,  4.40it/s]

IL_12341_2013 completed in 0:00:00.251239
IL_13032_2013 completed in 0:00:00.195625

 12%|█▏        | 528/4292 [02:23<13:45,  4.56it/s]

IN_9273_2013 completed in 0:00:00.200102

 12%|█▏        | 530/4292 [02:24<13:28,  4.65it/s]

IN_9324_2013 completed in 0:00:00.244802
IN_13756_2013 completed in 0:00:00.185429

 12%|█▏        | 532/4292 [02:24<14:59,  4.18it/s]

IN_15470_2013 completed in 0:00:00.383226
IN_17633_2013 completed in 0:00:00.175943

 12%|█▏        | 533/4292 [02:25<13:12,  4.74it/s]

KS_9996_2013 completed in 0:00:00.144077

 12%|█▏        | 534/4292 [02:25<14:14,  4.40it/s]

KS_10000_2013 completed in 0:00:00.264682

 12%|█▏        | 535/4292 [02:26<26:27,  2.37it/s]

KS_10005_2013 completed in 0:00:00.876878

 12%|█▏        | 536/4292 [02:26<23:37,  2.65it/s]

KS_22500_2013 completed in 0:00:00.270911

 13%|█▎        | 537/4292 [02:26<20:45,  3.02it/s]

KY_9964_2013 completed in 0:00:00.223715

 13%|█▎        | 538/4292 [02:26<19:09,  3.26it/s]

KY_10171_2013 completed in 0:00:00.246430

 13%|█▎        | 540/4292 [02:27<15:15,  4.10it/s]

KY_11249_2013 completed in 0:00:00.236286
KY_14724_2013 completed in 0:00:00.146332

 13%|█▎        | 541/4292 [02:27<15:06,  4.14it/s]

KY_19446_2013 completed in 0:00:00.235336

 13%|█▎        | 543/4292 [02:27<13:48,  4.53it/s]

KY_20130_2013 completed in 0:00:00.212279
KY_22053_2013 completed in 0:00:00.191912

 13%|█▎        | 544/4292 [02:28<13:33,  4.61it/s]

KY_49998_2013 completed in 0:00:00.207323

 13%|█▎        | 545/4292 [02:28<16:08,  3.87it/s]

LA_3265_2013 completed in 0:00:00.354348

 13%|█▎        | 547/4292 [02:29<15:19,  4.07it/s]

LA_11241_2013 completed in 0:00:00.285192
LA_13478_2013 completed in 0:00:00.195296

 13%|█▎        | 549/4292 [02:29<13:35,  4.59it/s]

LA_17698_2013 completed in 0:00:00.204789
LA_55936_2013 completed in 0:00:00.180270

 13%|█▎        | 551/4292 [02:29<14:02,  4.44it/s]

MA_6374_2013 completed in 0:00:00.278419
MA_8774_2013 completed in 0:00:00.197975

 13%|█▎        | 552/4292 [02:30<14:34,  4.28it/s]

MA_11804_2013 completed in 0:00:00.252035

 13%|█▎        | 553/4292 [02:30<16:21,  3.81it/s]

MA_13206_2013 completed in 0:00:00.328442

 13%|█▎        | 554/4292 [02:30<16:40,  3.74it/s]

MA_15748_2013 completed in 0:00:00.278590

 13%|█▎        | 555/4292 [02:30<16:22,  3.80it/s]

MA_20455_2013 completed in 0:00:00.250787

 13%|█▎        | 556/4292 [02:31<15:45,  3.95it/s]

MA_54913_2013 completed in 0:00:00.227635

 13%|█▎        | 557/4292 [02:31<15:11,  4.10it/s]

MD_84_2013 completed in 0:00:00.221948

 13%|█▎        | 558/4292 [02:31<16:02,  3.88it/s]

MD_1167_2013 completed in 0:00:00.286690

 13%|█▎        | 559/4292 [02:31<15:31,  4.01it/s]

MD_5027_2013 completed in 0:00:00.226674

 13%|█▎        | 560/4292 [02:32<14:47,  4.21it/s]

MD_15263_2013 completed in 0:00:00.205998

 13%|█▎        | 562/4292 [02:32<14:28,  4.29it/s]

MD_15270_2013 completed in 0:00:00.308058
ME_1179_2013 completed in 0:00:00.171077

 13%|█▎        | 564/4292 [02:33<13:58,  4.45it/s]

ME_3266_2013 completed in 0:00:00.253291
ME_11522_2013 completed in 0:00:00.190638

 13%|█▎        | 565/4292 [02:33<13:22,  4.65it/s]

MI_392_2013 completed in 0:00:00.191764

 13%|█▎        | 566/4292 [02:33<14:48,  4.19it/s]

MI_3828_2013 completed in 0:00:00.291816

 13%|█▎        | 567/4292 [02:33<15:41,  3.95it/s]

MI_4254_2013 completed in 0:00:00.285602

 13%|█▎        | 568/4292 [02:34<16:51,  3.68it/s]

MI_5109_2013 completed in 0:00:00.314775

 13%|█▎        | 569/4292 [02:34<18:16,  3.40it/s]

MI_9324_2013 completed in 0:00:00.346308

 13%|█▎        | 570/4292 [02:34<17:45,  3.49it/s]

MI_19578_2013 completed in 0:00:00.265805

 13%|█▎        | 571/4292 [02:35<16:57,  3.66it/s]

MI_20847_2013 completed in 0:00:00.242797

 13%|█▎        | 573/4292 [02:35<14:57,  4.14it/s]

MI_20860_2013 completed in 0:00:00.233479
MN_689_2013 completed in 0:00:00.193424

 13%|█▎        | 574/4292 [02:35<15:04,  4.11it/s]

MN_5574_2013 completed in 0:00:00.246304

 13%|█▎        | 575/4292 [02:35<14:40,  4.22it/s]

MN_9417_2013 completed in 0:00:00.221714

 13%|█▎        | 576/4292 [02:36<15:09,  4.09it/s]

MN_12647_2013 completed in 0:00:00.262020

 13%|█▎        | 577/4292 [02:36<15:51,  3.91it/s]

MN_13781_2013 completed in 0:00:00.281421

 13%|█▎        | 578/4292 [02:36<16:20,  3.79it/s]

MN_14232_2013 completed in 0:00:00.281796

 14%|█▎        | 580/4292 [02:37<15:11,  4.07it/s]

MN_17267_2013 completed in 0:00:00.273951
MN_20996_2013 completed in 0:00:00.193959

 14%|█▎        | 581/4292 [02:37<14:51,  4.16it/s]

MN_25177_2013 completed in 0:00:00.227056

 14%|█▎        | 583/4292 [02:37<13:12,  4.68it/s]

MO_4675_2013 completed in 0:00:00.214784
MO_5860_2013 completed in 0:00:00.167291

 14%|█▎        | 584/4292 [02:38<13:18,  4.64it/s]

MO_9231_2013 completed in 0:00:00.218372

 14%|█▎        | 585/4292 [02:38<13:20,  4.63it/s]

MO_10000_2013 completed in 0:00:00.216731

 14%|█▎        | 586/4292 [02:38<13:50,  4.46it/s]

MO_12698_2013 completed in 0:00:00.242286

 14%|█▎        | 587/4292 [02:38<14:27,  4.27it/s]

MO_17833_2013 completed in 0:00:00.256401

 14%|█▎        | 588/4292 [02:39<15:59,  3.86it/s]

MO_19436_2013 completed in 0:00:00.316332

 14%|█▎        | 589/4292 [02:39<15:53,  3.88it/s]

MS_6641_2013 completed in 0:00:00.253107

 14%|█▎        | 590/4292 [02:39<15:49,  3.90it/s]

MS_17647_2013 completed in 0:00:00.252922

 14%|█▍        | 591/4292 [02:39<16:02,  3.85it/s]

MT_6395_2013 completed in 0:00:00.267259

 14%|█▍        | 592/4292 [02:40<15:21,  4.01it/s]

MT_12692_2013 completed in 0:00:00.223075

 14%|█▍        | 593/4292 [02:40<17:38,  3.49it/s]

MT_12825_2013 completed in 0:00:00.371675

 14%|█▍        | 595/4292 [02:40<15:16,  4.03it/s]

MT_19603_2013 completed in 0:00:00.253478
MT_20997_2013 completed in 0:00:00.180290

 14%|█▍        | 596/4292 [02:42<37:27,  1.64it/s]

NC_3046_2013 completed in 0:00:01.447593

 14%|█▍        | 598/4292 [02:42<26:23,  2.33it/s]

NC_5416_2013 completed in 0:00:00.346963
NC_9837_2013 completed in 0:00:00.190753

 14%|█▍        | 599/4292 [02:43<23:14,  2.65it/s]

NC_16496_2013 completed in 0:00:00.257523

 14%|█▍        | 600/4292 [02:43<21:51,  2.82it/s]

NC_19876_2013 completed in 0:00:00.301351

 14%|█▍        | 601/4292 [02:43<19:22,  3.17it/s]

NC_24889_2013 completed in 0:00:00.218632

 14%|█▍        | 603/4292 [02:44<16:38,  3.69it/s]

ND_12087_2013 completed in 0:00:00.283449
ND_12301_2013 completed in 0:00:00.186907

 14%|█▍        | 605/4292 [02:44<15:11,  4.05it/s]

ND_14232_2013 completed in 0:00:00.268887
ND_19790_2013 completed in 0:00:00.186743

 14%|█▍        | 606/4292 [02:44<15:10,  4.05it/s]

ND_24949_2013 completed in 0:00:00.245366

 14%|█▍        | 607/4292 [02:45<16:41,  3.68it/s]

NE_4373_2013 completed in 0:00:00.328301

 14%|█▍        | 609/4292 [02:45<15:20,  4.00it/s]

NE_11018_2013 completed in 0:00:00.270410
NE_11251_2013 completed in 0:00:00.198555

 14%|█▍        | 610/4292 [02:45<14:28,  4.24it/s]

NE_13337_2013 completed in 0:00:00.202088

 14%|█▍        | 612/4292 [02:46<14:19,  4.28it/s]

NE_13664_2013 completed in 0:00:00.299916
NE_14127_2013 completed in 0:00:00.182246

 14%|█▍        | 613/4292 [02:46<13:37,  4.50it/s]

NE_17642_2013 completed in 0:00:00.194287

 14%|█▍        | 614/4292 [02:46<14:40,  4.18it/s]

NH_13441_2013 completed in 0:00:00.277567

 14%|█▍        | 615/4292 [02:47<14:06,  4.34it/s]

NH_15472_2013 completed in 0:00:00.207908

 14%|█▍        | 616/4292 [02:47<15:55,  3.85it/s]

NH_24590_2013 completed in 0:00:00.327956

 14%|█▍        | 617/4292 [02:47<15:14,  4.02it/s]

NH_26510_2013 completed in 0:00:00.222414

 14%|█▍        | 618/4292 [02:47<16:10,  3.79it/s]

NJ_963_2013 completed in 0:00:00.298739

 14%|█▍        | 619/4292 [02:48<16:46,  3.65it/s]

NJ_9726_2013 completed in 0:00:00.296581

 14%|█▍        | 621/4292 [02:48<14:51,  4.12it/s]

NJ_15477_2013 completed in 0:00:00.240012
NJ_16213_2013 completed in 0:00:00.192294

 15%|█▍        | 623/4292 [02:48<12:38,  4.84it/s]

NM_3287_2013 completed in 0:00:00.182125
NM_5701_2013 completed in 0:00:00.163330

 15%|█▍        | 624/4292 [02:49<11:45,  5.20it/s]

NM_6204_2013 completed in 0:00:00.157371

 15%|█▍        | 625/4292 [02:49<12:35,  4.85it/s]

NM_11204_2013 completed in 0:00:00.237236

 15%|█▍        | 626/4292 [02:49<13:10,  4.63it/s]

NM_15473_2013 completed in 0:00:00.237285

 15%|█▍        | 627/4292 [02:49<13:15,  4.61it/s]

NM_17718_2013 completed in 0:00:00.217408

 15%|█▍        | 629/4292 [02:50<15:42,  3.89it/s]

NM_22690_2013 completed in 0:00:00.451351
NV_2008_2013 completed in 0:00:00.185693

 15%|█▍        | 630/4292 [02:50<15:32,  3.93it/s]

NV_13073_2013 completed in 0:00:00.247285
NV_13407_2013 completed in 0:00:00.203035

 15%|█▍        | 632/4292 [02:51<15:37,  3.90it/s]

NV_17166_2013 completed in 0:00:00.294928

 15%|█▍        | 633/4292 [02:51<14:53,  4.09it/s]

NV_19840_2013 completed in 0:00:00.215451

 15%|█▍        | 634/4292 [02:51<14:49,  4.11it/s]

NY_3249_2013 completed in 0:00:00.239184

 15%|█▍        | 635/4292 [02:52<17:33,  3.47it/s]

NY_4226_2013 completed in 0:00:00.391482
NY_11171_2013 completed in 0:00:00.200131

 15%|█▍        | 637/4292 [02:52<20:35,  2.96it/s]

NY_13511_2013 completed in 0:00:00.514391

 15%|█▍        | 638/4292 [02:53<22:58,  2.65it/s]

NY_13573_2013 completed in 0:00:00.467853

 15%|█▍        | 639/4292 [02:53<20:09,  3.02it/s]

NY_14154_2013 completed in 0:00:00.222801

 15%|█▍        | 641/4292 [02:53<16:35,  3.67it/s]

NY_16183_2013 completed in 0:00:00.244541
OH_3542_2013 completed in 0:00:00.195221

 15%|█▍        | 642/4292 [02:54<15:32,  3.92it/s]

OH_3755_2013 completed in 0:00:00.214063

 15%|█▍        | 643/4292 [02:54<14:48,  4.11it/s]

OH_4922_2013 completed in 0:00:00.214723

 15%|█▌        | 644/4292 [02:54<14:39,  4.15it/s]

OH_13998_2013 completed in 0:00:00.234275

 15%|█▌        | 645/4292 [02:54<14:43,  4.13it/s]

OH_14006_2013 completed in 0:00:00.243662

 15%|█▌        | 646/4292 [02:55<14:21,  4.23it/s]

OH_18997_2013 completed in 0:00:00.221152

 15%|█▌        | 647/4292 [02:55<14:31,  4.18it/s]

OK_13734_2013 completed in 0:00:00.244163
OK_14062_2013 completed in 0:00:00.198707

 15%|█▌        | 649/4292 [02:55<15:00,  4.05it/s]

OK_14063_2013 completed in 0:00:00.292267

 15%|█▌        | 650/4292 [02:56<17:31,  3.46it/s]

OK_15474_2013 completed in 0:00:00.383297

 15%|█▌        | 651/4292 [02:56<18:08,  3.35it/s]

OK_19785_2013 completed in 0:00:00.321080

 15%|█▌        | 653/4292 [02:56<15:37,  3.88it/s]

OR_6022_2013 completed in 0:00:00.244325
OR_9191_2013 completed in 0:00:00.197229

 15%|█▌        | 655/4292 [02:57<15:22,  3.94it/s]

OR_14354_2013 completed in 0:00:00.334107
OR_15248_2013 completed in 0:00:00.189232

 15%|█▌        | 656/4292 [02:57<15:34,  3.89it/s]

OR_18260_2013 completed in 0:00:00.263861

 15%|█▌        | 658/4292 [02:58<14:20,  4.22it/s]

OR_40437_2013 completed in 0:00:00.271087
PA_3597_2013 completed in 0:00:00.178527

 15%|█▌        | 659/4292 [02:58<14:03,  4.31it/s]

PA_5487_2013 completed in 0:00:00.219954

 15%|█▌        | 660/4292 [02:58<14:06,  4.29it/s]

PA_12390_2013 completed in 0:00:00.233983

 15%|█▌        | 661/4292 [02:59<16:22,  3.70it/s]

PA_14711_2013 completed in 0:00:00.357255

 15%|█▌        | 662/4292 [02:59<17:24,  3.47it/s]

PA_14715_2013 completed in 0:00:00.327403

 15%|█▌        | 663/4292 [02:59<16:43,  3.62it/s]

PA_14716_2013 completed in 0:00:00.249596

 15%|█▌        | 665/4292 [03:00<14:55,  4.05it/s]

PA_14940_2013 completed in 0:00:00.247891
PA_15045_2013 completed in 0:00:00.196075

 16%|█▌        | 666/4292 [03:00<14:07,  4.28it/s]

PA_19390_2013 completed in 0:00:00.202572

 16%|█▌        | 667/4292 [03:00<14:56,  4.05it/s]

PA_20334_2013 completed in 0:00:00.277689

 16%|█▌        | 669/4292 [03:00<13:48,  4.37it/s]

PA_20387_2013 completed in 0:00:00.225891
RI_1857_2013 completed in 0:00:00.198710

 16%|█▌        | 670/4292 [03:01<14:15,  4.23it/s]

RI_13214_2013 completed in 0:00:00.252806

 16%|█▌        | 671/4292 [03:01<14:34,  4.14it/s]

SC_1613_2013 completed in 0:00:00.252241

 16%|█▌        | 672/4292 [03:01<15:01,  4.02it/s]

SC_3046_2013 completed in 0:00:00.265695

 16%|█▌        | 674/4292 [03:02<13:09,  4.58it/s]

SC_5416_2013 completed in 0:00:00.217542
SC_14398_2013 completed in 0:00:00.167604

 16%|█▌        | 675/4292 [03:02<12:54,  4.67it/s]

SC_17539_2013 completed in 0:00:00.202999
SC_17543_2013 completed in 0:00:00.203337

 16%|█▌        | 677/4292 [03:02<12:03,  5.00it/s]

SD_1769_2013 completed in 0:00:00.173597

 16%|█▌        | 678/4292 [03:02<12:20,  4.88it/s]

SD_13337_2013 completed in 0:00:00.215109

 16%|█▌        | 680/4292 [03:03<12:51,  4.68it/s]

SD_14232_2013 completed in 0:00:00.271118
SD_19293_2013 completed in 0:00:00.185963

 16%|█▌        | 682/4292 [03:03<11:55,  5.04it/s]

SD_20401_2013 completed in 0:00:00.172100
TN_727_2013 completed in 0:00:00.190231

 16%|█▌        | 683/4292 [03:03<12:00,  5.01it/s]

TN_2247_2013 completed in 0:00:00.202027

 16%|█▌        | 685/4292 [03:04<12:05,  4.97it/s]

TN_3408_2013 completed in 0:00:00.209055
TN_3812_2013 completed in 0:00:00.196018

 16%|█▌        | 686/4292 [03:04<14:15,  4.21it/s]

TN_4624_2013 completed in 0:00:00.321038

 16%|█▌        | 687/4292 [03:04<13:53,  4.33it/s]

TN_5399_2013 completed in 0:00:00.215899
TN_7174_2013 completed in 0:00:00.204903

 16%|█▌        | 689/4292 [03:05<13:47,  4.35it/s]

TN_7625_2013 completed in 0:00:00.243291

 16%|█▌        | 690/4292 [03:05<14:49,  4.05it/s]

TN_9777_2013 completed in 0:00:00.286704

 16%|█▌        | 691/4292 [03:05<14:19,  4.19it/s]

TN_10331_2013 completed in 0:00:00.217846

 16%|█▌        | 693/4292 [03:06<13:23,  4.48it/s]

TN_12470_2013 completed in 0:00:00.223966
TN_13216_2013 completed in 0:00:00.196006

 16%|█▌        | 694/4292 [03:06<13:17,  4.51it/s]

TN_17694_2013 completed in 0:00:00.216991

 16%|█▌        | 696/4292 [03:06<12:44,  4.70it/s]

TN_19574_2013 completed in 0:00:00.220277
TN_19898_2013 completed in 0:00:00.190583

 16%|█▌        | 697/4292 [03:07<12:35,  4.76it/s]

TX_5701_2013 completed in 0:00:00.203171

 16%|█▋        | 698/4292 [03:07<13:21,  4.48it/s]

TX_16604_2013 completed in 0:00:00.251875

 16%|█▋        | 699/4292 [03:07<13:13,  4.53it/s]

TX_17008_2013 completed in 0:00:00.214022

 16%|█▋        | 701/4292 [03:08<15:44,  3.80it/s]

TX_17698_2013 completed in 0:00:00.500230
TX_55937_2013 completed in 0:00:00.164408

 16%|█▋        | 702/4292 [03:08<15:14,  3.93it/s]

UT_2010_2013 completed in 0:00:00.233686

 16%|█▋        | 703/4292 [03:08<14:33,  4.11it/s]

UT_12866_2013 completed in 0:00:00.210890

 16%|█▋        | 705/4292 [03:09<14:19,  4.17it/s]

UT_14354_2013 completed in 0:00:00.309020
UT_15444_2013 completed in 0:00:00.177638

 16%|█▋        | 706/4292 [03:09<13:31,  4.42it/s]

UT_17845_2013 completed in 0:00:00.193582

 16%|█▋        | 708/4292 [03:09<13:07,  4.55it/s]

UT_17874_2013 completed in 0:00:00.255511
UT_18206_2013 completed in 0:00:00.180654

 17%|█▋        | 710/4292 [03:10<12:10,  4.90it/s]

VA_84_2013 completed in 0:00:00.182460
VA_733_2013 completed in 0:00:00.190775

 17%|█▋        | 711/4292 [03:10<11:56,  5.00it/s]

VA_17066_2013 completed in 0:00:00.186588

 17%|█▋        | 712/4292 [03:10<13:51,  4.31it/s]

VA_19876_2013 completed in 0:00:00.304357

 17%|█▋        | 713/4292 [03:10<14:57,  3.99it/s]

VA_40228_2013 completed in 0:00:00.292938

 17%|█▋        | 714/4292 [03:11<14:14,  4.19it/s]

VT_2548_2013 completed in 0:00:00.204900

 17%|█▋        | 715/4292 [03:11<14:24,  4.14it/s]

VT_7601_2013 completed in 0:00:00.247323

 17%|█▋        | 717/4292 [03:11<13:12,  4.51it/s]

VT_19791_2013 completed in 0:00:00.209466
WA_3660_2013 completed in 0:00:00.194045

 17%|█▋        | 718/4292 [03:12<13:21,  4.46it/s]

WA_14354_2013 completed in 0:00:00.228606

 17%|█▋        | 720/4292 [03:12<12:55,  4.61it/s]

WA_15500_2013 completed in 0:00:00.234315
WA_16868_2013 completed in 0:00:00.191678

 17%|█▋        | 721/4292 [03:12<12:38,  4.71it/s]

WA_17470_2013 completed in 0:00:00.200297

 17%|█▋        | 723/4292 [03:13<13:04,  4.55it/s]

WA_18429_2013 completed in 0:00:00.298663
WA_20169_2013 completed in 0:00:00.174617

 17%|█▋        | 724/4292 [03:13<12:39,  4.70it/s]

WI_4715_2013 completed in 0:00:00.195662

 17%|█▋        | 726/4292 [03:13<12:49,  4.63it/s]

WI_11479_2013 completed in 0:00:00.270749
WI_13697_2013 completed in 0:00:00.180772

 17%|█▋        | 727/4292 [03:13<12:13,  4.86it/s]

WI_13815_2013 completed in 0:00:00.180958

 17%|█▋        | 728/4292 [03:14<13:13,  4.49it/s]

WI_20847_2013 completed in 0:00:00.261124

 17%|█▋        | 729/4292 [03:14<13:36,  4.37it/s]

WI_20856_2013 completed in 0:00:00.243352

 17%|█▋        | 730/4292 [03:14<14:03,  4.22it/s]

WI_20860_2013 completed in 0:00:00.253993

 17%|█▋        | 731/4292 [03:15<18:58,  3.13it/s]

WV_733_2013 completed in 0:00:00.512492

 17%|█▋        | 733/4292 [03:15<17:16,  3.43it/s]

WV_12796_2013 completed in 0:00:00.364270
WV_20521_2013 completed in 0:00:00.191752

 17%|█▋        | 734/4292 [03:16<16:27,  3.60it/s]

WY_3461_2013 completed in 0:00:00.245359

 17%|█▋        | 735/4292 [03:16<20:06,  2.95it/s]

WY_8566_2013 completed in 0:00:00.481909

 17%|█▋        | 736/4292 [03:16<19:21,  3.06it/s]

WY_11273_2013 completed in 0:00:00.296557

 17%|█▋        | 737/4292 [03:17<17:39,  3.36it/s]

WY_14354_2013 completed in 0:00:00.230282

 17%|█▋        | 739/4292 [03:17<15:02,  3.94it/s]

WY_19156_2013 completed in 0:00:00.261341
WY_27058_2013 completed in 0:00:00.175682

 17%|█▋        | 741/4292 [03:17<12:54,  4.59it/s]

MI_10704_2013 completed in 0:00:00.188578
NE_12539_2013 completed in 0:00:00.178224

 17%|█▋        | 742/4292 [03:18<14:05,  4.20it/s]

AR_5860_2013 completed in 0:00:00.284587

 17%|█▋        | 743/4292 [03:18<13:59,  4.23it/s]

OK_5860_2013 completed in 0:00:00.231705

 17%|█▋        | 744/4292 [03:18<14:03,  4.20it/s]

AK_599_2014 completed in 0:00:00.240069

 17%|█▋        | 745/4292 [03:18<13:39,  4.33it/s]

AK_3522_2014 completed in 0:00:00.214338

 17%|█▋        | 746/4292 [03:19<14:50,  3.98it/s]

AK_7353_2014 completed in 0:00:00.296558

 17%|█▋        | 748/4292 [03:19<14:33,  4.06it/s]

AK_11824_2014 completed in 0:00:00.325893
AK_19558_2014 completed in 0:00:00.181962

 17%|█▋        | 749/4292 [03:20<17:46,  3.32it/s]

AL_195_2014 completed in 0:00:00.427088

 17%|█▋        | 750/4292 [03:20<16:19,  3.62it/s]

AL_4958_2014 completed in 0:00:00.218344

 17%|█▋        | 751/4292 [03:20<15:22,  3.84it/s]

AL_9739_2014 completed in 0:00:00.222776

 18%|█▊        | 752/4292 [03:21<19:54,  2.96it/s]

AR_814_2014 completed in 0:00:00.515175

 18%|█▊        | 753/4292 [03:21<21:31,  2.74it/s]

AR_817_2014 completed in 0:00:00.427946

 18%|█▊        | 755/4292 [03:21<16:49,  3.51it/s]

AR_3093_2014 completed in 0:00:00.234158
AR_5860_2014 completed in 0:00:00.187901

 18%|█▊        | 756/4292 [03:22<18:08,  3.25it/s]

AR_6342_2014 completed in 0:00:00.358965

 18%|█▊        | 757/4292 [03:22<17:19,  3.40it/s]

AR_14063_2014 completed in 0:00:00.259357

 18%|█▊        | 758/4292 [03:22<15:53,  3.71it/s]

AR_17698_2014 completed in 0:00:00.212459

 18%|█▊        | 759/4292 [03:23<15:45,  3.74it/s]

AZ_176_2014 completed in 0:00:00.261025

 18%|█▊        | 760/4292 [03:23<15:21,  3.83it/s]

AZ_803_2014 completed in 0:00:00.244649

 18%|█▊        | 762/4292 [03:23<13:03,  4.51it/s]

AZ_12919_2014 completed in 0:00:00.214157
AZ_16572_2014 completed in 0:00:00.161723

 18%|█▊        | 763/4292 [03:23<13:10,  4.46it/s]

AZ_19189_2014 completed in 0:00:00.227826

 18%|█▊        | 765/4292 [03:24<12:50,  4.58it/s]

AZ_19728_2014 completed in 0:00:00.234128
AZ_21538_2014 completed in 0:00:00.196877

 18%|█▊        | 766/4292 [03:24<12:51,  4.57it/s]

AZ_24211_2014 completed in 0:00:00.218079

 18%|█▊        | 767/4292 [03:24<15:13,  3.86it/s]

CA_9216_2014 completed in 0:00:00.352196

 18%|█▊        | 768/4292 [03:25<14:22,  4.09it/s]

CA_11208_2014 completed in 0:00:00.210066

 18%|█▊        | 769/4292 [03:25<13:49,  4.25it/s]

CA_12745_2014 completed in 0:00:00.213293

 18%|█▊        | 770/4292 [03:25<17:39,  3.32it/s]

CA_14328_2014 completed in 0:00:00.452619

 18%|█▊        | 772/4292 [03:26<14:46,  3.97it/s]

CA_14354_2014 completed in 0:00:00.217762
CA_14534_2014 completed in 0:00:00.193959

 18%|█▊        | 773/4292 [03:26<13:57,  4.20it/s]

CA_16534_2014 completed in 0:00:00.204846

 18%|█▊        | 774/4292 [03:26<13:55,  4.21it/s]

CA_16609_2014 completed in 0:00:00.235607

 18%|█▊        | 775/4292 [03:27<17:46,  3.30it/s]

CA_17609_2014 completed in 0:00:00.455892

 18%|█▊        | 776/4292 [03:27<16:55,  3.46it/s]

CA_17612_2014 completed in 0:00:00.254577

 18%|█▊        | 777/4292 [03:27<15:58,  3.67it/s]

CA_19281_2014 completed in 0:00:00.234251

 18%|█▊        | 778/4292 [03:27<15:39,  3.74it/s]

CO_3989_2014 completed in 0:00:00.254320

 18%|█▊        | 779/4292 [03:28<15:59,  3.66it/s]

CO_6604_2014 completed in 0:00:00.285825

 18%|█▊        | 780/4292 [03:28<15:23,  3.80it/s]

CO_9336_2014 completed in 0:00:00.237673

 18%|█▊        | 781/4292 [03:28<15:46,  3.71it/s]

CO_12866_2014 completed in 0:00:00.284516

 18%|█▊        | 782/4292 [03:28<15:15,  3.83it/s]

CO_15257_2014 completed in 0:00:00.238999

 18%|█▊        | 784/4292 [03:29<13:53,  4.21it/s]

CO_15466_2014 completed in 0:00:00.263472
CO_16603_2014 completed in 0:00:00.180323

 18%|█▊        | 785/4292 [03:29<13:29,  4.33it/s]

CO_19499_2014 completed in 0:00:00.213730

 18%|█▊        | 786/4292 [03:30<21:29,  2.72it/s]

CO_27058_2014 completed in 0:00:00.686966

 18%|█▊        | 787/4292 [03:30<20:06,  2.91it/s]

CO_56146_2014 completed in 0:00:00.287704

 18%|█▊        | 788/4292 [03:30<18:15,  3.20it/s]

CT_4176_2014 completed in 0:00:00.238204

 18%|█▊        | 789/4292 [03:30<16:41,  3.50it/s]

CT_19497_2014 completed in 0:00:00.222291

 18%|█▊        | 790/4292 [03:31<16:11,  3.61it/s]

CT_20038_2014 completed in 0:00:00.256490

 18%|█▊        | 791/4292 [03:31<14:57,  3.90it/s]

DC_15270_2014 completed in 0:00:00.206606

 18%|█▊        | 793/4292 [03:31<13:19,  4.38it/s]

DE_5027_2014 completed in 0:00:00.221972
DE_5070_2014 completed in 0:00:00.186159

 19%|█▊        | 795/4292 [03:32<11:30,  5.07it/s]

DE_5335_2014 completed in 0:00:00.187717
DE_13519_2014 completed in 0:00:00.151649

 19%|█▊        | 796/4292 [03:32<13:18,  4.38it/s]

FL_6452_2014 completed in 0:00:00.299574

 19%|█▊        | 797/4292 [03:32<14:15,  4.09it/s]

FL_6455_2014 completed in 0:00:00.282088

 19%|█▊        | 798/4292 [03:32<13:58,  4.17it/s]

FL_6457_2014 completed in 0:00:00.227297

 19%|█▊        | 799/4292 [03:33<13:55,  4.18it/s]

FL_7801_2014 completed in 0:00:00.236472

 19%|█▊        | 800/4292 [03:33<14:14,  4.09it/s]

FL_9617_2014 completed in 0:00:00.256438

 19%|█▊        | 801/4292 [03:33<13:36,  4.28it/s]

FL_18454_2014 completed in 0:00:00.203912

 19%|█▊        | 802/4292 [03:35<38:05,  1.53it/s]

GA_3916_2014 completed in 0:00:01.636412

 19%|█▊        | 804/4292 [03:35<25:51,  2.25it/s]

GA_7140_2014 completed in 0:00:00.319161
HI_8287_2014 completed in 0:00:00.188496

 19%|█▉        | 805/4292 [03:36<22:12,  2.62it/s]

HI_10071_2014 completed in 0:00:00.234895

 19%|█▉        | 807/4292 [03:36<17:13,  3.37it/s]

HI_11843_2014 completed in 0:00:00.244725
HI_19547_2014 completed in 0:00:00.191532

 19%|█▉        | 808/4292 [03:36<19:12,  3.02it/s]

IA_9417_2014 completed in 0:00:00.409921

 19%|█▉        | 809/4292 [03:37<17:24,  3.34it/s]

IA_12341_2014 completed in 0:00:00.226180

 19%|█▉        | 810/4292 [03:37<16:02,  3.62it/s]

ID_9187_2014 completed in 0:00:00.221452

 19%|█▉        | 811/4292 [03:37<15:51,  3.66it/s]

ID_9191_2014 completed in 0:00:00.265517

 19%|█▉        | 812/4292 [03:37<16:31,  3.51it/s]

ID_10454_2014 completed in 0:00:00.310467

 19%|█▉        | 813/4292 [03:38<15:12,  3.81it/s]

ID_11273_2014 completed in 0:00:00.208201

 19%|█▉        | 814/4292 [03:38<15:12,  3.81it/s]

ID_14354_2014 completed in 0:00:00.261675
ID_20169_2014 completed in 0:00:00.202934

 19%|█▉        | 816/4292 [03:38<14:05,  4.11it/s]

IL_4110_2014 completed in 0:00:00.239336

 19%|█▉        | 818/4292 [03:39<15:28,  3.74it/s]

IL_12341_2014 completed in 0:00:00.463529
IL_13032_2014 completed in 0:00:00.167307

 19%|█▉        | 820/4292 [03:40<15:33,  3.72it/s]

IL_56697_2014 completed in 0:00:00.411309
IN_9273_2014 completed in 0:00:00.169621

 19%|█▉        | 821/4292 [03:40<14:50,  3.90it/s]

IN_9324_2014 completed in 0:00:00.227458

 19%|█▉        | 822/4292 [03:40<18:51,  3.07it/s]

IN_13756_2014 completed in 0:00:00.487716

 19%|█▉        | 823/4292 [03:41<18:08,  3.19it/s]

IN_15470_2014 completed in 0:00:00.283618

 19%|█▉        | 824/4292 [03:41<17:11,  3.36it/s]

IN_17633_2014 completed in 0:00:00.258081

 19%|█▉        | 826/4292 [03:41<14:15,  4.05it/s]

KS_9996_2014 completed in 0:00:00.209506
KS_10000_2014 completed in 0:00:00.188444

 19%|█▉        | 827/4292 [03:42<14:36,  3.95it/s]

KS_10005_2014 completed in 0:00:00.266325

 19%|█▉        | 828/4292 [03:42<13:58,  4.13it/s]

KS_22500_2014 completed in 0:00:00.215605

 19%|█▉        | 829/4292 [03:42<13:25,  4.30it/s]

KY_9964_2014 completed in 0:00:00.209753

 19%|█▉        | 830/4292 [03:42<14:01,  4.11it/s]

KY_10171_2014 completed in 0:00:00.265292

 19%|█▉        | 831/4292 [03:43<16:07,  3.58it/s]

KY_11249_2014 completed in 0:00:00.363512

 19%|█▉        | 832/4292 [03:43<16:54,  3.41it/s]

KY_14724_2014 completed in 0:00:00.324891

 19%|█▉        | 833/4292 [03:43<15:46,  3.65it/s]

KY_19446_2014 completed in 0:00:00.226744

 19%|█▉        | 834/4292 [03:43<14:46,  3.90it/s]

KY_20130_2014 completed in 0:00:00.214810

 19%|█▉        | 835/4292 [03:44<14:29,  3.97it/s]

KY_22053_2014 completed in 0:00:00.240129

 19%|█▉        | 836/4292 [03:44<14:57,  3.85it/s]

KY_49998_2014 completed in 0:00:00.277248

 20%|█▉        | 837/4292 [03:44<14:31,  3.96it/s]

LA_3265_2014 completed in 0:00:00.234696

 20%|█▉        | 839/4292 [03:50<1:22:10,  1.43s/it]

LA_11241_2014 completed in 0:00:05.979521
LA_13478_2014 completed in 0:00:00.160453

 20%|█▉        | 840/4292 [03:51<1:09:20,  1.21s/it]

LA_17698_2014 completed in 0:00:00.685169

 20%|█▉        | 842/4292 [03:51<39:54,  1.44it/s]

LA_55936_2014 completed in 0:00:00.252834
MA_6374_2014 completed in 0:00:00.166756

 20%|█▉        | 844/4292 [03:52<24:41,  2.33it/s]

MA_8774_2014 completed in 0:00:00.174042
MA_11804_2014 completed in 0:00:00.174615

 20%|█▉        | 846/4292 [03:52<17:08,  3.35it/s]

MA_13206_2014 completed in 0:00:00.149553
MA_15748_2014 completed in 0:00:00.186777

 20%|█▉        | 847/4292 [03:52<15:19,  3.75it/s]

MA_20455_2014 completed in 0:00:00.193133
MA_54913_2014 completed in 0:00:00.200799

 20%|█▉        | 849/4292 [03:53<13:46,  4.16it/s]

MD_1167_2014 completed in 0:00:00.222572

 20%|█▉        | 850/4292 [03:53<13:34,  4.22it/s]

MD_5027_2014 completed in 0:00:00.227975

 20%|█▉        | 852/4292 [03:53<12:55,  4.44it/s]

MD_15263_2014 completed in 0:00:00.242589
MD_15270_2014 completed in 0:00:00.193084

 20%|█▉        | 853/4292 [03:54<12:32,  4.57it/s]

ME_1179_2014 completed in 0:00:00.202979

 20%|█▉        | 854/4292 [03:54<13:41,  4.18it/s]

ME_3266_2014 completed in 0:00:00.285308

 20%|█▉        | 855/4292 [03:54<14:59,  3.82it/s]

MI_392_2014 completed in 0:00:00.313272

 20%|█▉        | 857/4292 [03:55<13:30,  4.24it/s]

MI_3828_2014 completed in 0:00:00.244959
MI_4254_2014 completed in 0:00:00.185980

 20%|█▉        | 858/4292 [03:55<14:25,  3.97it/s]

MI_5109_2014 completed in 0:00:00.289091

 20%|██        | 859/4292 [03:55<16:51,  3.39it/s]

MI_9324_2014 completed in 0:00:00.393364

 20%|██        | 860/4292 [03:56<17:30,  3.27it/s]

MI_10704_2014 completed in 0:00:00.331566

 20%|██        | 861/4292 [03:56<16:13,  3.52it/s]

MI_19578_2014 completed in 0:00:00.230781

 20%|██        | 863/4292 [03:56<14:01,  4.07it/s]

MI_20847_2014 completed in 0:00:00.240083
MI_20860_2014 completed in 0:00:00.185575

 20%|██        | 864/4292 [03:56<12:57,  4.41it/s]

MN_689_2014 completed in 0:00:00.181859

 20%|██        | 865/4292 [03:57<12:55,  4.42it/s]

MN_5574_2014 completed in 0:00:00.224189

 20%|██        | 866/4292 [03:57<15:34,  3.67it/s]

MN_9417_2014 completed in 0:00:00.380105

 20%|██        | 867/4292 [03:57<15:04,  3.79it/s]

MN_12647_2014 completed in 0:00:00.242657

 20%|██        | 868/4292 [03:58<15:02,  3.79it/s]

MN_13781_2014 completed in 0:00:00.259320

 20%|██        | 869/4292 [03:58<15:54,  3.59it/s]

MN_14232_2014 completed in 0:00:00.312769

 20%|██        | 870/4292 [03:58<16:57,  3.36it/s]

MN_16181_2014 completed in 0:00:00.339253

 20%|██        | 871/4292 [03:59<20:04,  2.84it/s]

MN_17267_2014 completed in 0:00:00.479197

 20%|██        | 873/4292 [03:59<16:19,  3.49it/s]

MN_20996_2014 completed in 0:00:00.257537
MN_25177_2014 completed in 0:00:00.193040

 20%|██        | 874/4292 [03:59<15:28,  3.68it/s]

MO_4675_2014 completed in 0:00:00.232663

 20%|██        | 875/4292 [04:00<14:44,  3.86it/s]

MO_5860_2014 completed in 0:00:00.228156
MO_9231_2014 completed in 0:00:00.201933

 20%|██        | 877/4292 [04:00<12:44,  4.46it/s]

MO_10000_2014 completed in 0:00:00.181026

 20%|██        | 879/4292 [04:01<13:25,  4.24it/s]

MO_12698_2014 completed in 0:00:00.389334
MO_17833_2014 completed in 0:00:00.146903

 21%|██        | 881/4292 [04:01<13:15,  4.29it/s]

MO_19436_2014 completed in 0:00:00.307191
MS_3841_2014 completed in 0:00:00.174776

 21%|██        | 883/4292 [04:01<12:45,  4.45it/s]

MS_6641_2014 completed in 0:00:00.242668
MS_17647_2014 completed in 0:00:00.196200

 21%|██        | 884/4292 [04:02<12:38,  4.49it/s]

MS_19273_2014 completed in 0:00:00.217138
MT_6395_2014 completed in 0:00:00.200198

 21%|██        | 886/4292 [04:02<11:33,  4.91it/s]

MT_12692_2014 completed in 0:00:00.173715

 21%|██        | 887/4292 [04:02<12:12,  4.65it/s]

MT_12825_2014 completed in 0:00:00.240794
MT_19603_2014 completed in 0:00:00.201198

 21%|██        | 889/4292 [04:03<12:43,  4.46it/s]

MT_20997_2014 completed in 0:00:00.254469

 21%|██        | 890/4292 [04:03<14:05,  4.02it/s]

NC_3046_2014 completed in 0:00:00.304083

 21%|██        | 891/4292 [04:03<16:58,  3.34it/s]

NC_5416_2014 completed in 0:00:00.417818

 21%|██        | 892/4292 [04:04<16:08,  3.51it/s]

NC_9837_2014 completed in 0:00:00.249408

 21%|██        | 893/4292 [04:04<16:07,  3.51it/s]

NC_16496_2014 completed in 0:00:00.282901

 21%|██        | 894/4292 [04:04<14:46,  3.83it/s]

NC_19876_2014 completed in 0:00:00.205070

 21%|██        | 895/4292 [04:04<13:55,  4.06it/s]

NC_24889_2014 completed in 0:00:00.209934

 21%|██        | 896/4292 [04:05<14:37,  3.87it/s]

ND_12087_2014 completed in 0:00:00.285004

 21%|██        | 898/4292 [04:05<13:36,  4.16it/s]

ND_12301_2014 completed in 0:00:00.254822
ND_14232_2014 completed in 0:00:00.199661

 21%|██        | 899/4292 [04:05<12:59,  4.35it/s]

ND_19790_2014 completed in 0:00:00.203382

 21%|██        | 901/4292 [04:06<12:32,  4.51it/s]

ND_24949_2014 completed in 0:00:00.249136
NE_4373_2014 completed in 0:00:00.188629

 21%|██        | 903/4292 [04:06<10:50,  5.21it/s]

NE_11018_2014 completed in 0:00:00.191136
NE_11251_2014 completed in 0:00:00.141936

 21%|██        | 904/4292 [04:06<11:32,  4.89it/s]

NE_12539_2014 completed in 0:00:00.232990

 21%|██        | 905/4292 [04:07<11:37,  4.85it/s]

NE_13337_2014 completed in 0:00:00.208725

 21%|██        | 906/4292 [04:07<11:43,  4.81it/s]

NE_13664_2014 completed in 0:00:00.207626

 21%|██        | 907/4292 [04:07<12:15,  4.60it/s]

NE_14127_2014 completed in 0:00:00.238366

 21%|██        | 908/4292 [04:07<12:38,  4.46it/s]

NE_17642_2014 completed in 0:00:00.238933

 21%|██        | 909/4292 [04:07<12:31,  4.50it/s]

NH_13441_2014 completed in 0:00:00.216831

 21%|██        | 910/4292 [04:08<12:45,  4.42it/s]

NH_15472_2014 completed in 0:00:00.234643

 21%|██        | 911/4292 [04:08<12:50,  4.39it/s]

NH_24590_2014 completed in 0:00:00.230262

 21%|██        | 912/4292 [04:08<13:03,  4.31it/s]

NJ_963_2014 completed in 0:00:00.239848

 21%|██▏       | 913/4292 [04:08<13:21,  4.22it/s]

NJ_9726_2014 completed in 0:00:00.248332

 21%|██▏       | 914/4292 [04:09<13:11,  4.27it/s]

NJ_15477_2014 completed in 0:00:00.226794
NJ_16213_2014 completed in 0:00:00.201647

 21%|██▏       | 917/4292 [04:09<10:41,  5.26it/s]

NM_3287_2014 completed in 0:00:00.177433
NM_5701_2014 completed in 0:00:00.141289

 21%|██▏       | 919/4292 [04:10<10:46,  5.22it/s]

NM_6204_2014 completed in 0:00:00.199778
NM_11204_2014 completed in 0:00:00.186609

 21%|██▏       | 920/4292 [04:10<12:18,  4.56it/s]

NM_15473_2014 completed in 0:00:00.282068

 21%|██▏       | 921/4292 [04:10<13:18,  4.22it/s]

NM_17718_2014 completed in 0:00:00.277005

 21%|██▏       | 922/4292 [04:11<15:46,  3.56it/s]

NM_22690_2014 completed in 0:00:00.382518

 22%|██▏       | 923/4292 [04:11<15:27,  3.63it/s]

NV_2008_2014 completed in 0:00:00.261004

 22%|██▏       | 924/4292 [04:11<14:54,  3.77it/s]

NV_13073_2014 completed in 0:00:00.239453

 22%|██▏       | 925/4292 [04:11<14:20,  3.91it/s]

NV_13407_2014 completed in 0:00:00.229953

 22%|██▏       | 926/4292 [04:12<14:37,  3.84it/s]

NV_17166_2014 completed in 0:00:00.271003

 22%|██▏       | 927/4292 [04:12<15:09,  3.70it/s]

NV_19840_2014 completed in 0:00:00.292114

 22%|██▏       | 928/4292 [04:12<15:39,  3.58it/s]

NY_3249_2014 completed in 0:00:00.298847

 22%|██▏       | 929/4292 [04:12<16:39,  3.36it/s]

NY_4226_2014 completed in 0:00:00.338469

 22%|██▏       | 930/4292 [04:13<17:43,  3.16it/s]

NY_11171_2014 completed in 0:00:00.359637

 22%|██▏       | 931/4292 [04:13<18:29,  3.03it/s]

NY_13511_2014 completed in 0:00:00.361370

 22%|██▏       | 932/4292 [04:14<24:32,  2.28it/s]

NY_13573_2014 completed in 0:00:00.689951

 22%|██▏       | 933/4292 [04:14<20:40,  2.71it/s]

NY_14154_2014 completed in 0:00:00.207167

 22%|██▏       | 935/4292 [04:15<16:15,  3.44it/s]

NY_16183_2014 completed in 0:00:00.249221
OH_3542_2014 completed in 0:00:00.189653

 22%|██▏       | 936/4292 [04:15<16:04,  3.48it/s]

OH_3755_2014 completed in 0:00:00.278606

 22%|██▏       | 937/4292 [04:15<15:08,  3.69it/s]

OH_4922_2014 completed in 0:00:00.231387

 22%|██▏       | 938/4292 [04:15<14:36,  3.83it/s]

OH_13998_2014 completed in 0:00:00.237914

 22%|██▏       | 939/4292 [04:16<16:09,  3.46it/s]

OH_14006_2014 completed in 0:00:00.353604

 22%|██▏       | 941/4292 [04:16<14:45,  3.79it/s]

OH_18997_2014 completed in 0:00:00.308599
OK_5860_2014 completed in 0:00:00.190829

 22%|██▏       | 942/4292 [04:16<14:24,  3.87it/s]

OK_13734_2014 completed in 0:00:00.243388
OK_14062_2014 completed in 0:00:00.202516

 22%|██▏       | 945/4292 [04:19<34:26,  1.62it/s]

OK_14063_2014 completed in 0:00:02.107953
OK_15474_2014 completed in 0:00:00.186182

 22%|██▏       | 946/4292 [04:19<31:18,  1.78it/s]

OK_19785_2014 completed in 0:00:00.430477

 22%|██▏       | 947/4292 [04:20<25:47,  2.16it/s]

OR_6022_2014 completed in 0:00:00.230392

 22%|██▏       | 948/4292 [04:20<21:59,  2.53it/s]

OR_9191_2014 completed in 0:00:00.234691

 22%|██▏       | 949/4292 [04:20<18:59,  2.93it/s]

OR_14354_2014 completed in 0:00:00.214410

 22%|██▏       | 950/4292 [04:20<16:50,  3.31it/s]

OR_15248_2014 completed in 0:00:00.211838

 22%|██▏       | 952/4292 [04:21<14:20,  3.88it/s]

OR_18260_2014 completed in 0:00:00.258803
OR_40437_2014 completed in 0:00:00.182047

 22%|██▏       | 953/4292 [04:21<14:43,  3.78it/s]

PA_3597_2014 completed in 0:00:00.280429

 22%|██▏       | 954/4292 [04:21<14:44,  3.77it/s]

PA_5487_2014 completed in 0:00:00.264484

 22%|██▏       | 955/4292 [04:21<14:56,  3.72it/s]

PA_12390_2014 completed in 0:00:00.275778

 22%|██▏       | 956/4292 [04:22<20:00,  2.78it/s]

PA_14711_2014 completed in 0:00:00.572138

 22%|██▏       | 957/4292 [04:22<20:05,  2.77it/s]

PA_14715_2014 completed in 0:00:00.363763

 22%|██▏       | 958/4292 [04:23<17:43,  3.14it/s]

PA_14716_2014 completed in 0:00:00.216083

 22%|██▏       | 960/4292 [04:23<14:27,  3.84it/s]

PA_14940_2014 completed in 0:00:00.234598
PA_15045_2014 completed in 0:00:00.180888

 22%|██▏       | 962/4292 [04:23<12:28,  4.45it/s]

PA_19390_2014 completed in 0:00:00.196139
PA_20334_2014 completed in 0:00:00.185004

 22%|██▏       | 963/4292 [04:24<14:14,  3.90it/s]

PA_20387_2014 completed in 0:00:00.328641

 22%|██▏       | 964/4292 [04:24<13:39,  4.06it/s]

RI_1857_2014 completed in 0:00:00.220393

 22%|██▏       | 965/4292 [04:24<13:59,  3.96it/s]

RI_13214_2014 completed in 0:00:00.265331

 23%|██▎       | 966/4292 [04:25<14:08,  3.92it/s]

SC_1613_2014 completed in 0:00:00.255983

 23%|██▎       | 968/4292 [04:25<12:11,  4.54it/s]

SC_3046_2014 completed in 0:00:00.252531
SC_5416_2014 completed in 0:00:00.138891

 23%|██▎       | 969/4292 [04:25<15:32,  3.56it/s]

SC_14398_2014 completed in 0:00:00.420374

 23%|██▎       | 970/4292 [04:26<15:09,  3.65it/s]

SC_17539_2014 completed in 0:00:00.256780

 23%|██▎       | 971/4292 [04:26<14:42,  3.77it/s]

SC_17543_2014 completed in 0:00:00.245723

 23%|██▎       | 972/4292 [04:26<14:08,  3.91it/s]

SD_1769_2014 completed in 0:00:00.231811

 23%|██▎       | 973/4292 [04:26<13:48,  4.00it/s]

SD_13337_2014 completed in 0:00:00.234966

 23%|██▎       | 974/4292 [04:27<13:23,  4.13it/s]

SD_14232_2014 completed in 0:00:00.223532

 23%|██▎       | 975/4292 [04:27<13:59,  3.95it/s]

SD_17267_2014 completed in 0:00:00.278031

 23%|██▎       | 977/4292 [04:27<12:59,  4.25it/s]

SD_19293_2014 completed in 0:00:00.269156
SD_20401_2014 completed in 0:00:00.180045

 23%|██▎       | 978/4292 [04:27<11:55,  4.63it/s]

TN_727_2014 completed in 0:00:00.170283

 23%|██▎       | 980/4292 [04:28<11:39,  4.73it/s]

TN_4624_2014 completed in 0:00:00.234761
TN_5399_2014 completed in 0:00:00.185165

 23%|██▎       | 981/4292 [04:28<11:54,  4.63it/s]

TN_7174_2014 completed in 0:00:00.226124

 23%|██▎       | 982/4292 [04:28<12:12,  4.52it/s]

TN_10331_2014 completed in 0:00:00.233007

 23%|██▎       | 984/4292 [04:29<11:36,  4.75it/s]

TN_12470_2014 completed in 0:00:00.214714
TN_17694_2014 completed in 0:00:00.189083

 23%|██▎       | 985/4292 [04:29<11:14,  4.91it/s]

TN_19574_2014 completed in 0:00:00.187140

 23%|██▎       | 987/4292 [04:29<11:22,  4.84it/s]

TN_19898_2014 completed in 0:00:00.228944
TX_5701_2014 completed in 0:00:00.193671

 23%|██▎       | 988/4292 [04:30<12:15,  4.49it/s]

TX_16604_2014 completed in 0:00:00.259379

 23%|██▎       | 989/4292 [04:30<12:39,  4.35it/s]

TX_17008_2014 completed in 0:00:00.246312

 23%|██▎       | 990/4292 [04:30<16:39,  3.30it/s]

TX_17698_2014 completed in 0:00:00.471661

 23%|██▎       | 991/4292 [04:31<16:22,  3.36it/s]

TX_55937_2014 completed in 0:00:00.284424
UT_2010_2014 completed in 0:00:00.203998

 23%|██▎       | 993/4292 [04:31<15:05,  3.65it/s]

UT_11135_2014 completed in 0:00:00.284106

 23%|██▎       | 994/4292 [04:31<14:13,  3.86it/s]

UT_12866_2014 completed in 0:00:00.221933

 23%|██▎       | 996/4292 [04:32<13:58,  3.93it/s]

UT_14354_2014 completed in 0:00:00.360421
UT_15444_2014 completed in 0:00:00.171582

 23%|██▎       | 998/4292 [04:32<13:38,  4.03it/s]

UT_17845_2014 completed in 0:00:00.314744
UT_17874_2014 completed in 0:00:00.190856

 23%|██▎       | 1000/4292 [04:33<12:43,  4.31it/s]

UT_18206_2014 completed in 0:00:00.246769
VA_84_2014 completed in 0:00:00.193188

 23%|██▎       | 1002/4292 [04:33<11:38,  4.71it/s]

VA_733_2014 completed in 0:00:00.206808
VA_17066_2014 completed in 0:00:00.182351

 23%|██▎       | 1003/4292 [04:33<13:27,  4.07it/s]

VA_19876_2014 completed in 0:00:00.322316

 23%|██▎       | 1004/4292 [04:34<12:51,  4.26it/s]

VA_19882_2014 completed in 0:00:00.208096

 23%|██▎       | 1005/4292 [04:34<12:28,  4.39it/s]

VA_40228_2014 completed in 0:00:00.210575

 23%|██▎       | 1006/4292 [04:34<12:13,  4.48it/s]

VT_2548_2014 completed in 0:00:00.209739

 23%|██▎       | 1007/4292 [04:34<13:37,  4.02it/s]

VT_7601_2014 completed in 0:00:00.307757

 23%|██▎       | 1008/4292 [04:35<14:18,  3.83it/s]

VT_19791_2014 completed in 0:00:00.289510

 24%|██▎       | 1009/4292 [04:35<14:04,  3.89it/s]

WA_3660_2014 completed in 0:00:00.246583

 24%|██▎       | 1010/4292 [04:35<13:25,  4.07it/s]

WA_14354_2014 completed in 0:00:00.215276

 24%|██▎       | 1011/4292 [04:35<14:02,  3.89it/s]

WA_15500_2014 completed in 0:00:00.280974

 24%|██▎       | 1012/4292 [04:36<13:15,  4.12it/s]

WA_16868_2014 completed in 0:00:00.208072

 24%|██▎       | 1013/4292 [04:36<12:53,  4.24it/s]

WA_17470_2014 completed in 0:00:00.217467

 24%|██▎       | 1015/4292 [04:36<12:42,  4.29it/s]

WA_18429_2014 completed in 0:00:00.280991
WA_20169_2014 completed in 0:00:00.192349

 24%|██▎       | 1017/4292 [04:37<13:22,  4.08it/s]

WI_4715_2014 completed in 0:00:00.416705
WI_5574_2014 completed in 0:00:00.142465

 24%|██▎       | 1019/4292 [04:37<12:19,  4.43it/s]

WI_11479_2014 completed in 0:00:00.239336
WI_13697_2014 completed in 0:00:00.183674

 24%|██▍       | 1020/4292 [04:38<13:44,  3.97it/s]

WI_13815_2014 completed in 0:00:00.311646

 24%|██▍       | 1021/4292 [04:38<14:15,  3.82it/s]

WI_20847_2014 completed in 0:00:00.283480

 24%|██▍       | 1022/4292 [04:38<13:30,  4.04it/s]

WI_20856_2014 completed in 0:00:00.214335

 24%|██▍       | 1023/4292 [04:39<14:46,  3.69it/s]

WI_20860_2014 completed in 0:00:00.325380

 24%|██▍       | 1025/4292 [04:39<13:02,  4.17it/s]

WV_733_2014 completed in 0:00:00.231858
WV_12796_2014 completed in 0:00:00.190219

 24%|██▍       | 1027/4292 [04:40<14:45,  3.69it/s]

WV_15263_2014 completed in 0:00:00.460089
WV_20521_2014 completed in 0:00:00.189646

 24%|██▍       | 1028/4292 [04:40<13:09,  4.13it/s]

WY_3461_2014 completed in 0:00:00.171859

 24%|██▍       | 1029/4292 [04:40<13:21,  4.07it/s]

WY_8566_2014 completed in 0:00:00.253925

 24%|██▍       | 1030/4292 [04:40<13:11,  4.12it/s]

WY_11273_2014 completed in 0:00:00.233891

 24%|██▍       | 1031/4292 [04:41<13:30,  4.02it/s]

WY_14354_2014 completed in 0:00:00.261820

 24%|██▍       | 1032/4292 [04:41<13:43,  3.96it/s]

WY_19156_2014 completed in 0:00:00.261189

 24%|██▍       | 1033/4292 [04:41<13:07,  4.14it/s]

WY_27058_2014 completed in 0:00:00.214827

 24%|██▍       | 1034/4292 [04:41<12:57,  4.19it/s]

NE_6779_2014 completed in 0:00:00.231038

 24%|██▍       | 1035/4292 [04:41<13:04,  4.15it/s]

AK_219_2014 completed in 0:00:00.244538

 24%|██▍       | 1036/4292 [04:42<12:41,  4.28it/s]

CT_7716_2014 completed in 0:00:00.216780

 24%|██▍       | 1038/4292 [04:42<11:44,  4.62it/s]

AR_13718_2014 completed in 0:00:00.215595
KY_17564_2014 completed in 0:00:00.187035

 24%|██▍       | 1040/4292 [04:42<10:58,  4.94it/s]

NC_6235_2014 completed in 0:00:00.220292
WY_7222_2014 completed in 0:00:00.165898

 24%|██▍       | 1041/4292 [04:43<13:06,  4.14it/s]

AK_219_2015 completed in 0:00:00.332461

 24%|██▍       | 1042/4292 [04:43<12:38,  4.29it/s]

AK_599_2015 completed in 0:00:00.212446

 24%|██▍       | 1044/4292 [04:43<11:37,  4.65it/s]

AK_3522_2015 completed in 0:00:00.228674
AK_7353_2015 completed in 0:00:00.173141

 24%|██▍       | 1046/4292 [04:44<10:23,  5.21it/s]

AK_11824_2015 completed in 0:00:00.207372
AK_19558_2015 completed in 0:00:00.142324

 24%|██▍       | 1047/4292 [04:44<11:32,  4.68it/s]

AL_195_2015 completed in 0:00:00.262831

 24%|██▍       | 1048/4292 [04:44<11:45,  4.60it/s]

AR_814_2015 completed in 0:00:00.225376

 24%|██▍       | 1049/4292 [04:45<21:45,  2.48it/s]

AR_817_2015 completed in 0:00:00.833611

 24%|██▍       | 1051/4292 [04:46<16:25,  3.29it/s]

AR_3093_2015 completed in 0:00:00.223481
AR_5860_2015 completed in 0:00:00.198671

 25%|██▍       | 1053/4292 [04:46<13:30,  4.00it/s]

AR_6342_2015 completed in 0:00:00.205265
AR_13718_2015 completed in 0:00:00.191736

 25%|██▍       | 1055/4292 [04:46<11:44,  4.59it/s]

AR_14063_2015 completed in 0:00:00.165738
AR_17698_2015 completed in 0:00:00.199959

 25%|██▍       | 1056/4292 [04:46<11:21,  4.75it/s]

AZ_176_2015 completed in 0:00:00.192927

 25%|██▍       | 1057/4292 [04:47<11:55,  4.52it/s]

AZ_803_2015 completed in 0:00:00.245024

 25%|██▍       | 1059/4292 [04:47<11:17,  4.77it/s]

AZ_12919_2015 completed in 0:00:00.253278
AZ_16572_2015 completed in 0:00:00.157639

 25%|██▍       | 1061/4292 [04:48<12:09,  4.43it/s]

AZ_19189_2015 completed in 0:00:00.309332
AZ_19728_2015 completed in 0:00:00.192096

 25%|██▍       | 1063/4292 [04:48<11:03,  4.86it/s]

AZ_21538_2015 completed in 0:00:00.209684
AZ_24211_2015 completed in 0:00:00.165939

 25%|██▍       | 1065/4292 [04:49<11:43,  4.59it/s]

CA_9216_2015 completed in 0:00:00.280766
CA_11208_2015 completed in 0:00:00.190601

 25%|██▍       | 1066/4292 [04:49<11:06,  4.84it/s]

CA_12745_2015 completed in 0:00:00.178546

 25%|██▍       | 1067/4292 [04:49<15:38,  3.44it/s]

CA_14328_2015 completed in 0:00:00.486200

 25%|██▍       | 1069/4292 [04:50<13:53,  3.87it/s]

CA_14354_2015 completed in 0:00:00.271388
CA_14534_2015 completed in 0:00:00.192834

 25%|██▍       | 1070/4292 [04:50<12:33,  4.27it/s]

CA_16534_2015 completed in 0:00:00.175939

 25%|██▍       | 1071/4292 [04:50<13:18,  4.03it/s]

CA_16609_2015 completed in 0:00:00.279668

 25%|██▌       | 1073/4292 [04:51<12:10,  4.41it/s]

CA_17609_2015 completed in 0:00:00.263669
CA_17612_2015 completed in 0:00:00.164935

 25%|██▌       | 1074/4292 [04:51<11:47,  4.55it/s]

CA_19281_2015 completed in 0:00:00.202415

 25%|██▌       | 1075/4292 [04:51<11:55,  4.49it/s]

CO_3989_2015 completed in 0:00:00.228343

 25%|██▌       | 1076/4292 [04:51<11:51,  4.52it/s]

CO_6604_2015 completed in 0:00:00.217290

 25%|██▌       | 1077/4292 [04:51<12:00,  4.46it/s]

CO_9336_2015 completed in 0:00:00.229453

 25%|██▌       | 1078/4292 [04:52<12:39,  4.23it/s]

CO_12866_2015 completed in 0:00:00.263367

 25%|██▌       | 1079/4292 [04:52<12:12,  4.39it/s]

CO_15257_2015 completed in 0:00:00.207857

 25%|██▌       | 1081/4292 [04:52<11:18,  4.73it/s]

CO_15466_2015 completed in 0:00:00.224638
CO_16603_2015 completed in 0:00:00.173001

 25%|██▌       | 1083/4292 [04:53<11:13,  4.77it/s]

CO_19499_2015 completed in 0:00:00.235208
CO_27058_2015 completed in 0:00:00.187999

 25%|██▌       | 1084/4292 [04:53<11:00,  4.86it/s]

CO_56146_2015 completed in 0:00:00.195595

 25%|██▌       | 1086/4292 [04:53<09:51,  5.42it/s]

CT_4176_2015 completed in 0:00:00.217163
CT_7716_2015 completed in 0:00:00.125439

 25%|██▌       | 1087/4292 [04:53<09:45,  5.48it/s]

CT_19497_2015 completed in 0:00:00.175367

 25%|██▌       | 1089/4292 [04:55<19:16,  2.77it/s]

CT_20038_2015 completed in 0:00:01.056745
DC_15270_2015 completed in 0:00:00.164694

 25%|██▌       | 1091/4292 [04:55<14:27,  3.69it/s]

DE_5027_2015 completed in 0:00:00.175061
DE_5070_2015 completed in 0:00:00.189020

 25%|██▌       | 1092/4292 [04:55<12:58,  4.11it/s]

DE_5335_2015 completed in 0:00:00.177919

 25%|██▌       | 1093/4292 [04:55<13:19,  4.00it/s]

DE_13519_2015 completed in 0:00:00.265044

 25%|██▌       | 1094/4292 [04:56<14:04,  3.79it/s]

FL_6452_2015 completed in 0:00:00.295808

 26%|██▌       | 1096/4292 [04:56<13:20,  3.99it/s]

FL_6455_2015 completed in 0:00:00.287880
FL_6457_2015 completed in 0:00:00.200360

 26%|██▌       | 1097/4292 [04:56<12:17,  4.33it/s]

FL_7801_2015 completed in 0:00:00.184046

 26%|██▌       | 1098/4292 [04:57<11:55,  4.47it/s]

FL_9617_2015 completed in 0:00:00.206972

 26%|██▌       | 1099/4292 [04:57<11:57,  4.45it/s]

FL_18454_2015 completed in 0:00:00.224772

 26%|██▌       | 1101/4292 [04:58<19:06,  2.78it/s]

GA_3916_2015 completed in 0:00:00.960935
HI_8287_2015 completed in 0:00:00.156876

 26%|██▌       | 1103/4292 [04:58<14:34,  3.65it/s]

HI_10071_2015 completed in 0:00:00.188305
HI_11843_2015 completed in 0:00:00.193638

 26%|██▌       | 1104/4292 [04:59<12:36,  4.22it/s]

HI_19547_2015 completed in 0:00:00.150185

 26%|██▌       | 1105/4292 [04:59<12:13,  4.35it/s]

IA_9417_2015 completed in 0:00:00.212453

 26%|██▌       | 1106/4292 [04:59<12:49,  4.14it/s]

IA_12341_2015 completed in 0:00:00.266540

 26%|██▌       | 1107/4292 [04:59<13:12,  4.02it/s]

ID_9187_2015 completed in 0:00:00.265370

 26%|██▌       | 1108/4292 [04:59<12:46,  4.16it/s]

ID_9191_2015 completed in 0:00:00.220046

 26%|██▌       | 1110/4292 [05:00<11:41,  4.54it/s]

ID_10454_2015 completed in 0:00:00.207394
ID_11273_2015 completed in 0:00:00.194843

 26%|██▌       | 1111/4292 [05:00<12:44,  4.16it/s]

ID_14354_2015 completed in 0:00:00.285632

 26%|██▌       | 1112/4292 [05:00<13:06,  4.04it/s]

ID_20169_2015 completed in 0:00:00.262365

 26%|██▌       | 1113/4292 [05:01<13:43,  3.86it/s]

IL_4110_2015 completed in 0:00:00.285281

 26%|██▌       | 1114/4292 [05:01<12:59,  4.07it/s]

IL_12341_2015 completed in 0:00:00.211653

 26%|██▌       | 1115/4292 [05:01<13:36,  3.89it/s]

IL_13032_2015 completed in 0:00:00.280690

 26%|██▌       | 1117/4292 [05:02<12:11,  4.34it/s]

IL_56697_2015 completed in 0:00:00.241425
IN_9273_2015 completed in 0:00:00.177155

 26%|██▌       | 1118/4292 [05:02<16:45,  3.16it/s]

IN_9324_2015 completed in 0:00:00.517428
IN_13756_2015 completed in 0:00:00.200739

 26%|██▌       | 1120/4292 [05:03<14:04,  3.75it/s]

IN_15470_2015 completed in 0:00:00.228441

 26%|██▌       | 1122/4292 [05:03<12:34,  4.20it/s]

IN_17633_2015 completed in 0:00:00.224148
KS_9996_2015 completed in 0:00:00.200005

 26%|██▌       | 1124/4292 [05:03<10:49,  4.88it/s]

KS_10000_2015 completed in 0:00:00.146736
KS_10005_2015 completed in 0:00:00.189898

 26%|██▌       | 1125/4292 [05:04<12:52,  4.10it/s]

KS_22500_2015 completed in 0:00:00.333832

 26%|██▌       | 1126/4292 [05:04<13:10,  4.01it/s]

KY_9964_2015 completed in 0:00:00.260972

 26%|██▋       | 1127/4292 [05:04<13:46,  3.83it/s]

KY_10171_2015 completed in 0:00:00.286668

 26%|██▋       | 1128/4292 [05:05<13:56,  3.78it/s]

KY_11249_2015 completed in 0:00:00.271840

 26%|██▋       | 1130/4292 [05:05<12:03,  4.37it/s]

KY_17564_2015 completed in 0:00:00.210558
KY_19446_2015 completed in 0:00:00.180998

 26%|██▋       | 1132/4292 [05:05<11:34,  4.55it/s]

KY_22053_2015 completed in 0:00:00.234525
KY_49998_2015 completed in 0:00:00.192845

 26%|██▋       | 1133/4292 [05:06<12:55,  4.07it/s]

LA_3265_2015 completed in 0:00:00.304054

 26%|██▋       | 1135/4292 [05:06<12:29,  4.21it/s]

LA_11241_2015 completed in 0:00:00.276833
LA_13478_2015 completed in 0:00:00.194985

 26%|██▋       | 1136/4292 [05:06<12:37,  4.17it/s]

LA_17698_2015 completed in 0:00:00.245578

 27%|██▋       | 1138/4292 [05:07<11:33,  4.55it/s]

LA_55936_2015 completed in 0:00:00.217525
MA_6374_2015 completed in 0:00:00.186859

 27%|██▋       | 1139/4292 [05:07<12:09,  4.32it/s]

MA_8774_2015 completed in 0:00:00.257748

 27%|██▋       | 1141/4292 [05:07<11:06,  4.73it/s]

MA_11804_2015 completed in 0:00:00.221680
MA_13206_2015 completed in 0:00:00.170028

 27%|██▋       | 1142/4292 [05:08<10:52,  4.83it/s]

MA_15748_2015 completed in 0:00:00.195833

 27%|██▋       | 1143/4292 [05:08<11:27,  4.58it/s]

MA_20455_2015 completed in 0:00:00.243344

 27%|██▋       | 1144/4292 [05:08<11:31,  4.55it/s]

MA_54913_2015 completed in 0:00:00.222115

 27%|██▋       | 1145/4292 [05:08<12:11,  4.30it/s]

MD_1167_2015 completed in 0:00:00.261712

 27%|██▋       | 1147/4292 [05:09<11:17,  4.64it/s]

MD_5027_2015 completed in 0:00:00.242136
MD_15263_2015 completed in 0:00:00.167378

 27%|██▋       | 1149/4292 [05:09<11:05,  4.72it/s]

MD_15270_2015 completed in 0:00:00.242526
ME_1179_2015 completed in 0:00:00.182687

 27%|██▋       | 1151/4292 [05:10<10:28,  4.99it/s]

ME_3266_2015 completed in 0:00:00.203966
MI_392_2015 completed in 0:00:00.177248

 27%|██▋       | 1152/4292 [05:10<10:55,  4.79it/s]

MI_3828_2015 completed in 0:00:00.228116

 27%|██▋       | 1153/4292 [05:10<11:46,  4.45it/s]

MI_4254_2015 completed in 0:00:00.261613

 27%|██▋       | 1154/4292 [05:10<12:41,  4.12it/s]

MI_5109_2015 completed in 0:00:00.283180

 27%|██▋       | 1155/4292 [05:11<12:29,  4.18it/s]

MI_9324_2015 completed in 0:00:00.229683

 27%|██▋       | 1156/4292 [05:11<12:01,  4.34it/s]

MI_10704_2015 completed in 0:00:00.208584

 27%|██▋       | 1157/4292 [05:11<12:49,  4.07it/s]

MI_19578_2015 completed in 0:00:00.279584

 27%|██▋       | 1158/4292 [05:11<13:07,  3.98it/s]

MI_20847_2015 completed in 0:00:00.263219

 27%|██▋       | 1160/4292 [05:12<11:26,  4.56it/s]

MI_20860_2015 completed in 0:00:00.230698
MN_689_2015 completed in 0:00:00.157429

 27%|██▋       | 1161/4292 [05:12<12:01,  4.34it/s]

MN_5574_2015 completed in 0:00:00.256303

 27%|██▋       | 1162/4292 [05:12<11:45,  4.43it/s]

MN_9417_2015 completed in 0:00:00.212691

 27%|██▋       | 1163/4292 [05:12<12:24,  4.20it/s]

MN_12647_2015 completed in 0:00:00.265475

 27%|██▋       | 1164/4292 [05:13<12:16,  4.25it/s]

MN_13781_2015 completed in 0:00:00.229088

 27%|██▋       | 1166/4292 [05:13<11:49,  4.41it/s]

MN_14232_2015 completed in 0:00:00.282033
MN_16181_2015 completed in 0:00:00.168303

 27%|██▋       | 1167/4292 [05:13<12:33,  4.15it/s]

MN_17267_2015 completed in 0:00:00.272946

 27%|██▋       | 1169/4292 [05:14<16:23,  3.18it/s]

MN_20996_2015 completed in 0:00:00.690076
MN_25177_2015 completed in 0:00:00.170543

 27%|██▋       | 1170/4292 [05:15<15:01,  3.46it/s]

MO_4675_2015 completed in 0:00:00.226131

 27%|██▋       | 1171/4292 [05:15<14:25,  3.61it/s]

MO_5860_2015 completed in 0:00:00.249901

 27%|██▋       | 1172/4292 [05:15<14:42,  3.54it/s]

MO_9231_2015 completed in 0:00:00.295245

 27%|██▋       | 1173/4292 [05:15<14:00,  3.71it/s]

MO_10000_2015 completed in 0:00:00.236926

 27%|██▋       | 1175/4292 [05:16<12:22,  4.20it/s]

MO_12698_2015 completed in 0:00:00.222006
MO_17833_2015 completed in 0:00:00.197016

 27%|██▋       | 1176/4292 [05:16<11:59,  4.33it/s]

MO_19436_2015 completed in 0:00:00.213274

 27%|██▋       | 1177/4292 [05:16<12:36,  4.12it/s]

MS_3841_2015 completed in 0:00:00.268806

 27%|██▋       | 1179/4292 [05:17<11:24,  4.55it/s]

MS_17647_2015 completed in 0:00:00.240760
MT_6395_2015 completed in 0:00:00.166486

 27%|██▋       | 1180/4292 [05:17<12:17,  4.22it/s]

MT_12692_2015 completed in 0:00:00.276024

 28%|██▊       | 1181/4292 [05:17<12:31,  4.14it/s]

MT_12825_2015 completed in 0:00:00.251381

 28%|██▊       | 1182/4292 [05:17<13:02,  3.97it/s]

MT_19603_2015 completed in 0:00:00.274055

 28%|██▊       | 1183/4292 [05:18<14:08,  3.66it/s]

MT_20997_2015 completed in 0:00:00.321766

 28%|██▊       | 1184/4292 [05:18<14:18,  3.62it/s]

NC_3046_2015 completed in 0:00:00.283594

 28%|██▊       | 1185/4292 [05:18<13:23,  3.87it/s]

NC_5416_2015 completed in 0:00:00.216053

 28%|██▊       | 1186/4292 [05:18<12:43,  4.07it/s]

NC_9837_2015 completed in 0:00:00.215619

 28%|██▊       | 1187/4292 [05:19<12:40,  4.08it/s]

NC_16496_2015 completed in 0:00:00.242265

 28%|██▊       | 1189/4292 [05:19<11:25,  4.53it/s]

NC_19876_2015 completed in 0:00:00.220417
NC_24889_2015 completed in 0:00:00.180447

 28%|██▊       | 1190/4292 [05:19<14:01,  3.69it/s]

ND_12301_2015 completed in 0:00:00.387531

 28%|██▊       | 1191/4292 [05:20<14:33,  3.55it/s]

ND_14232_2015 completed in 0:00:00.305020

 28%|██▊       | 1192/4292 [05:20<13:43,  3.76it/s]

ND_19790_2015 completed in 0:00:00.227116

 28%|██▊       | 1193/4292 [05:20<13:41,  3.77it/s]

ND_24949_2015 completed in 0:00:00.262891

 28%|██▊       | 1194/4292 [05:21<13:14,  3.90it/s]

NE_4373_2015 completed in 0:00:00.235109

 28%|██▊       | 1195/4292 [05:21<14:50,  3.48it/s]

NE_6779_2015 completed in 0:00:00.359726

 28%|██▊       | 1196/4292 [05:21<15:46,  3.27it/s]

NE_11018_2015 completed in 0:00:00.346323

 28%|██▊       | 1197/4292 [05:22<15:30,  3.33it/s]

NE_11251_2015 completed in 0:00:00.287982

 28%|██▊       | 1198/4292 [05:22<14:11,  3.63it/s]

NE_12539_2015 completed in 0:00:00.214973

 28%|██▊       | 1199/4292 [05:22<15:40,  3.29it/s]

NE_13337_2015 completed in 0:00:00.370649

 28%|██▊       | 1200/4292 [05:22<15:47,  3.26it/s]

NE_13664_2015 completed in 0:00:00.310980

 28%|██▊       | 1201/4292 [05:23<18:10,  2.83it/s]

NE_14127_2015 completed in 0:00:00.460219

 28%|██▊       | 1203/4292 [05:23<14:11,  3.63it/s]

NE_17642_2015 completed in 0:00:00.216835
NH_13441_2015 completed in 0:00:00.189000

 28%|██▊       | 1204/4292 [05:24<13:10,  3.91it/s]

NH_15472_2015 completed in 0:00:00.208903

 28%|██▊       | 1205/4292 [05:24<13:31,  3.80it/s]

NH_24590_2015 completed in 0:00:00.278189

 28%|██▊       | 1206/4292 [05:24<12:58,  3.96it/s]

NJ_963_2015 completed in 0:00:00.227118

 28%|██▊       | 1207/4292 [05:24<13:45,  3.74it/s]

NJ_9726_2015 completed in 0:00:00.301943

 28%|██▊       | 1208/4292 [05:25<15:48,  3.25it/s]

NJ_15477_2015 completed in 0:00:00.399825

 28%|██▊       | 1209/4292 [05:25<16:40,  3.08it/s]

NJ_16213_2015 completed in 0:00:00.363019

 28%|██▊       | 1210/4292 [05:25<15:36,  3.29it/s]

NM_3287_2015 completed in 0:00:00.253858

 28%|██▊       | 1211/4292 [05:26<14:21,  3.58it/s]

NM_5701_2015 completed in 0:00:00.221952

 28%|██▊       | 1213/4292 [05:26<13:40,  3.75it/s]

NM_6204_2015 completed in 0:00:00.343129
NM_11204_2015 completed in 0:00:00.187947

 28%|██▊       | 1214/4292 [05:26<13:55,  3.69it/s]

NM_15473_2015 completed in 0:00:00.281409

 28%|██▊       | 1216/4292 [05:27<12:56,  3.96it/s]

NM_17718_2015 completed in 0:00:00.323169
NV_2008_2015 completed in 0:00:00.169597

 28%|██▊       | 1218/4292 [05:27<12:04,  4.24it/s]

NV_13073_2015 completed in 0:00:00.261791
NV_13407_2015 completed in 0:00:00.188888

 28%|██▊       | 1219/4292 [05:28<14:00,  3.66it/s]

NV_17166_2015 completed in 0:00:00.360463

 28%|██▊       | 1220/4292 [05:28<13:08,  3.89it/s]

NV_19840_2015 completed in 0:00:00.216981

 28%|██▊       | 1221/4292 [05:28<12:40,  4.04it/s]

NY_3249_2015 completed in 0:00:00.225764

 28%|██▊       | 1222/4292 [05:28<13:34,  3.77it/s]

NY_4226_2015 completed in 0:00:00.305861

 28%|██▊       | 1223/4292 [05:29<13:17,  3.85it/s]

NY_11171_2015 completed in 0:00:00.246464

 29%|██▊       | 1224/4292 [05:29<18:20,  2.79it/s]

NY_13511_2015 completed in 0:00:00.587957

 29%|██▊       | 1225/4292 [05:30<22:13,  2.30it/s]

NY_13573_2015 completed in 0:00:00.611804

 29%|██▊       | 1226/4292 [05:30<23:39,  2.16it/s]

NY_14154_2015 completed in 0:00:00.526950

 29%|██▊       | 1227/4292 [05:31<19:53,  2.57it/s]

NY_16183_2015 completed in 0:00:00.216495

 29%|██▊       | 1228/4292 [05:31<17:15,  2.96it/s]

OH_3542_2015 completed in 0:00:00.217726

 29%|██▊       | 1229/4292 [05:31<17:52,  2.86it/s]

OH_3755_2015 completed in 0:00:00.377440

 29%|██▊       | 1230/4292 [05:32<16:44,  3.05it/s]

OH_4922_2015 completed in 0:00:00.275485

 29%|██▊       | 1231/4292 [05:32<19:33,  2.61it/s]

OH_13998_2015 completed in 0:00:00.511304

 29%|██▊       | 1232/4292 [05:32<20:00,  2.55it/s]

OH_14006_2015 completed in 0:00:00.412717

 29%|██▊       | 1233/4292 [05:33<17:52,  2.85it/s]

OH_18997_2015 completed in 0:00:00.252503

 29%|██▉       | 1234/4292 [05:33<16:19,  3.12it/s]

OK_5860_2015 completed in 0:00:00.248763

 29%|██▉       | 1235/4292 [05:33<15:07,  3.37it/s]

OK_13734_2015 completed in 0:00:00.240492

 29%|██▉       | 1236/4292 [05:33<13:51,  3.68it/s]

OK_14062_2015 completed in 0:00:00.213313

 29%|██▉       | 1237/4292 [05:34<14:06,  3.61it/s]

OK_14063_2015 completed in 0:00:00.287396

 29%|██▉       | 1238/4292 [05:34<15:05,  3.37it/s]

OK_15474_2015 completed in 0:00:00.341200

 29%|██▉       | 1240/4292 [05:34<12:56,  3.93it/s]

OK_19785_2015 completed in 0:00:00.264301
OR_6022_2015 completed in 0:00:00.176531

 29%|██▉       | 1241/4292 [05:35<14:05,  3.61it/s]

OR_9191_2015 completed in 0:00:00.329600

 29%|██▉       | 1242/4292 [05:35<14:34,  3.49it/s]

OR_14354_2015 completed in 0:00:00.308253

 29%|██▉       | 1243/4292 [05:35<14:46,  3.44it/s]

OR_15248_2015 completed in 0:00:00.299205

 29%|██▉       | 1244/4292 [05:36<16:28,  3.08it/s]

OR_18260_2015 completed in 0:00:00.402315

 29%|██▉       | 1245/4292 [05:36<17:04,  2.97it/s]

OR_40437_2015 completed in 0:00:00.363398

 29%|██▉       | 1246/4292 [05:36<16:27,  3.08it/s]

PA_3597_2015 completed in 0:00:00.295361

 29%|██▉       | 1247/4292 [05:37<17:56,  2.83it/s]

PA_5487_2015 completed in 0:00:00.420452

 29%|██▉       | 1248/4292 [05:37<21:22,  2.37it/s]

PA_12390_2015 completed in 0:00:00.579275

 29%|██▉       | 1249/4292 [05:39<36:50,  1.38it/s]

PA_14711_2015 completed in 0:00:01.436593

 29%|██▉       | 1250/4292 [05:39<30:32,  1.66it/s]

PA_14715_2015 completed in 0:00:00.309538

 29%|██▉       | 1251/4292 [05:39<24:32,  2.06it/s]

PA_14716_2015 completed in 0:00:00.205106

 29%|██▉       | 1253/4292 [05:40<20:04,  2.52it/s]

PA_14940_2015 completed in 0:00:00.472774
PA_15045_2015 completed in 0:00:00.197359

 29%|██▉       | 1254/4292 [05:40<17:24,  2.91it/s]

PA_19390_2015 completed in 0:00:00.220489

 29%|██▉       | 1255/4292 [05:41<15:32,  3.26it/s]

PA_20334_2015 completed in 0:00:00.220564

 29%|██▉       | 1256/4292 [05:41<16:13,  3.12it/s]

PA_20387_2015 completed in 0:00:00.352068

 29%|██▉       | 1257/4292 [05:41<15:43,  3.22it/s]

RI_1857_2015 completed in 0:00:00.286663

 29%|██▉       | 1258/4292 [05:41<15:36,  3.24it/s]

RI_13214_2015 completed in 0:00:00.302289

 29%|██▉       | 1259/4292 [05:42<14:51,  3.40it/s]

SC_1613_2015 completed in 0:00:00.259476

 29%|██▉       | 1260/4292 [05:42<16:37,  3.04it/s]

SC_3046_2015 completed in 0:00:00.409878

 29%|██▉       | 1261/4292 [05:42<15:32,  3.25it/s]

SC_5416_2015 completed in 0:00:00.256846

 29%|██▉       | 1262/4292 [05:43<14:35,  3.46it/s]

SC_14398_2015 completed in 0:00:00.244958

 29%|██▉       | 1264/4292 [05:43<11:53,  4.25it/s]

SC_17539_2015 completed in 0:00:00.226568
SC_17543_2015 completed in 0:00:00.153002

 29%|██▉       | 1266/4292 [05:44<12:49,  3.93it/s]

SD_1769_2015 completed in 0:00:00.391655
SD_13337_2015 completed in 0:00:00.187258

 30%|██▉       | 1267/4292 [05:44<12:33,  4.01it/s]

SD_14232_2015 completed in 0:00:00.236303

 30%|██▉       | 1268/4292 [05:44<12:41,  3.97it/s]

SD_17267_2015 completed in 0:00:00.257366

 30%|██▉       | 1269/4292 [05:44<13:26,  3.75it/s]

SD_19293_2015 completed in 0:00:00.300253

 30%|██▉       | 1271/4292 [05:45<12:59,  3.87it/s]

SD_20401_2015 completed in 0:00:00.320598
TN_10331_2015 completed in 0:00:00.198758

 30%|██▉       | 1272/4292 [05:45<12:10,  4.14it/s]

TX_5701_2015 completed in 0:00:00.202899

 30%|██▉       | 1273/4292 [05:45<12:13,  4.11it/s]

TX_16604_2015 completed in 0:00:00.245375

 30%|██▉       | 1274/4292 [05:46<12:58,  3.88it/s]

TX_17698_2015 completed in 0:00:00.291353

 30%|██▉       | 1275/4292 [05:46<14:09,  3.55it/s]

TX_55937_2015 completed in 0:00:00.336272

 30%|██▉       | 1276/4292 [05:46<13:14,  3.80it/s]

UT_2010_2015 completed in 0:00:00.219775
UT_11135_2015 completed in 0:00:00.202508

 30%|██▉       | 1278/4292 [05:47<16:14,  3.09it/s]

UT_12866_2015 completed in 0:00:00.504278

 30%|██▉       | 1280/4292 [05:47<13:30,  3.72it/s]

UT_14354_2015 completed in 0:00:00.264999
UT_15444_2015 completed in 0:00:00.182274

 30%|██▉       | 1281/4292 [05:48<14:04,  3.56it/s]

UT_17845_2015 completed in 0:00:00.306372

 30%|██▉       | 1282/4292 [05:48<14:25,  3.48it/s]

UT_17874_2015 completed in 0:00:00.302436

 30%|██▉       | 1283/4292 [05:48<15:40,  3.20it/s]

UT_18206_2015 completed in 0:00:00.369663

 30%|██▉       | 1284/4292 [05:49<15:55,  3.15it/s]

VA_84_2015 completed in 0:00:00.328954

 30%|██▉       | 1285/4292 [05:49<14:48,  3.38it/s]

VA_733_2015 completed in 0:00:00.243199

 30%|██▉       | 1286/4292 [05:49<15:11,  3.30it/s]

VA_17066_2015 completed in 0:00:00.320167

 30%|██▉       | 1287/4292 [05:50<14:10,  3.53it/s]

VA_19876_2015 completed in 0:00:00.235062

 30%|███       | 1288/4292 [05:50<16:54,  2.96it/s]

VA_19882_2015 completed in 0:00:00.463807

 30%|███       | 1289/4292 [05:50<17:02,  2.94it/s]

VA_40228_2015 completed in 0:00:00.345292

 30%|███       | 1291/4292 [05:51<13:25,  3.73it/s]

VT_2548_2015 completed in 0:00:00.257582
VT_7601_2015 completed in 0:00:00.156288

 30%|███       | 1292/4292 [05:51<12:14,  4.09it/s]

VT_19791_2015 completed in 0:00:00.188679

 30%|███       | 1293/4292 [05:51<12:33,  3.98it/s]

WA_3660_2015 completed in 0:00:00.265385

 30%|███       | 1294/4292 [05:51<12:40,  3.94it/s]

WA_14354_2015 completed in 0:00:00.257922

 30%|███       | 1295/4292 [05:52<18:19,  2.73it/s]

WA_15500_2015 completed in 0:00:00.628133

 30%|███       | 1296/4292 [05:52<16:59,  2.94it/s]

WA_16868_2015 completed in 0:00:00.277526

 30%|███       | 1297/4292 [05:53<15:11,  3.28it/s]

WA_17470_2015 completed in 0:00:00.220184

 30%|███       | 1298/4292 [05:53<14:35,  3.42it/s]

WA_18429_2015 completed in 0:00:00.263692

 30%|███       | 1299/4292 [05:53<13:41,  3.65it/s]

WA_20169_2015 completed in 0:00:00.230822

 30%|███       | 1300/4292 [05:53<14:45,  3.38it/s]

WI_4715_2015 completed in 0:00:00.343269

 30%|███       | 1301/4292 [05:54<14:05,  3.54it/s]

WI_5574_2015 completed in 0:00:00.251048

 30%|███       | 1302/4292 [05:54<13:15,  3.76it/s]

WI_11479_2015 completed in 0:00:00.226342

 30%|███       | 1303/4292 [05:54<12:59,  3.84it/s]

WI_13697_2015 completed in 0:00:00.246931

 30%|███       | 1304/4292 [05:54<13:41,  3.64it/s]

WI_13815_2015 completed in 0:00:00.307251

 30%|███       | 1305/4292 [05:55<13:51,  3.59it/s]

WI_20847_2015 completed in 0:00:00.285348

 30%|███       | 1306/4292 [05:55<13:24,  3.71it/s]

WI_20856_2015 completed in 0:00:00.247952

 30%|███       | 1307/4292 [05:55<12:38,  3.94it/s]

WI_20860_2015 completed in 0:00:00.217125

 30%|███       | 1308/4292 [05:56<13:31,  3.68it/s]

WV_733_2015 completed in 0:00:00.312649

 30%|███       | 1309/4292 [05:56<13:05,  3.80it/s]

WV_12796_2015 completed in 0:00:00.242287

 31%|███       | 1310/4292 [05:56<15:54,  3.12it/s]

WV_15263_2015 completed in 0:00:00.451960

 31%|███       | 1312/4292 [05:57<13:03,  3.80it/s]

WV_20521_2015 completed in 0:00:00.284851
WY_3461_2015 completed in 0:00:00.152649

 31%|███       | 1313/4292 [05:57<11:10,  4.45it/s]

WY_7222_2015 completed in 0:00:00.135519

 31%|███       | 1314/4292 [05:57<13:30,  3.67it/s]

WY_8566_2015 completed in 0:00:00.381386

 31%|███       | 1315/4292 [05:57<12:56,  3.83it/s]

WY_11273_2015 completed in 0:00:00.233505

 31%|███       | 1316/4292 [05:58<13:22,  3.71it/s]

WY_14354_2015 completed in 0:00:00.289088

 31%|███       | 1317/4292 [05:58<12:57,  3.83it/s]

WY_19156_2015 completed in 0:00:00.240983

 31%|███       | 1318/4292 [05:58<12:41,  3.90it/s]

WY_27058_2015 completed in 0:00:00.242834

 31%|███       | 1319/4292 [05:58<12:07,  4.09it/s]

OR_28541_2015 completed in 0:00:00.216623

 31%|███       | 1320/4292 [05:59<12:09,  4.07it/s]

AK_219_2016 completed in 0:00:00.246303

 31%|███       | 1321/4292 [05:59<12:55,  3.83it/s]

AK_599_2016 completed in 0:00:00.296497

 31%|███       | 1323/4292 [05:59<12:45,  3.88it/s]

AK_3522_2016 completed in 0:00:00.336063
AK_7353_2016 completed in 0:00:00.196564

 31%|███       | 1324/4292 [06:00<12:45,  3.88it/s]

AK_11824_2016 completed in 0:00:00.257394

 31%|███       | 1325/4292 [06:00<12:55,  3.83it/s]

AK_19558_2016 completed in 0:00:00.268062

 31%|███       | 1326/4292 [06:00<16:03,  3.08it/s]

AL_195_2016 completed in 0:00:00.471783

 31%|███       | 1327/4292 [06:01<16:46,  2.95it/s]

AR_814_2016 completed in 0:00:00.373074

 31%|███       | 1328/4292 [06:01<15:11,  3.25it/s]

AR_817_2016 completed in 0:00:00.232241

 31%|███       | 1330/4292 [06:02<15:22,  3.21it/s]

AR_3093_2016 completed in 0:00:00.525686
AR_5860_2016 completed in 0:00:00.165749

 31%|███       | 1331/4292 [06:02<19:58,  2.47it/s]

AR_6342_2016 completed in 0:00:00.620900

 31%|███       | 1333/4292 [06:03<15:04,  3.27it/s]

AR_13718_2016 completed in 0:00:00.250452
AR_14063_2016 completed in 0:00:00.180065

 31%|███       | 1334/4292 [06:03<13:38,  3.61it/s]

AR_17698_2016 completed in 0:00:00.202564

 31%|███       | 1335/4292 [06:03<13:47,  3.57it/s]

AZ_176_2016 completed in 0:00:00.286521

 31%|███       | 1336/4292 [06:04<14:44,  3.34it/s]

AZ_803_2016 completed in 0:00:00.342966

 31%|███       | 1337/4292 [06:04<15:15,  3.23it/s]

AZ_12919_2016 completed in 0:00:00.330829

 31%|███       | 1338/4292 [06:04<14:34,  3.38it/s]

AZ_16572_2016 completed in 0:00:00.262771

 31%|███       | 1340/4292 [06:05<13:20,  3.69it/s]

AZ_19189_2016 completed in 0:00:00.319815
AZ_19728_2016 completed in 0:00:00.195689

 31%|███▏      | 1342/4292 [06:05<12:08,  4.05it/s]

AZ_21538_2016 completed in 0:00:00.258282
AZ_24211_2016 completed in 0:00:00.197935

 31%|███▏      | 1343/4292 [06:06<12:29,  3.93it/s]

CA_9216_2016 completed in 0:00:00.270424

 31%|███▏      | 1344/4292 [06:06<17:37,  2.79it/s]

CA_11208_2016 completed in 0:00:00.601667

 31%|███▏      | 1345/4292 [06:06<15:52,  3.10it/s]

CA_12745_2016 completed in 0:00:00.238863

 31%|███▏      | 1346/4292 [06:07<20:43,  2.37it/s]

CA_14328_2016 completed in 0:00:00.652766

 31%|███▏      | 1347/4292 [06:07<17:39,  2.78it/s]

CA_14354_2016 completed in 0:00:00.213068

 31%|███▏      | 1349/4292 [06:08<14:15,  3.44it/s]

CA_14534_2016 completed in 0:00:00.324329
CA_16534_2016 completed in 0:00:00.153046

 31%|███▏      | 1351/4292 [06:08<13:25,  3.65it/s]

CA_16609_2016 completed in 0:00:00.366501
CA_16655_2016 completed in 0:00:00.180585

 32%|███▏      | 1352/4292 [06:09<16:16,  3.01it/s]

CA_17609_2016 completed in 0:00:00.466384

 32%|███▏      | 1353/4292 [06:09<14:53,  3.29it/s]

CA_17612_2016 completed in 0:00:00.237105

 32%|███▏      | 1354/4292 [06:09<14:55,  3.28it/s]

CA_19281_2016 completed in 0:00:00.305672

 32%|███▏      | 1355/4292 [06:10<15:34,  3.14it/s]

CO_3989_2016 completed in 0:00:00.348992

 32%|███▏      | 1356/4292 [06:10<14:14,  3.44it/s]

CO_6604_2016 completed in 0:00:00.226416

 32%|███▏      | 1358/4292 [06:10<12:04,  4.05it/s]

CO_9336_2016 completed in 0:00:00.210888
CO_12866_2016 completed in 0:00:00.198999

 32%|███▏      | 1359/4292 [06:11<12:16,  3.98it/s]

CO_15257_2016 completed in 0:00:00.259972

 32%|███▏      | 1360/4292 [06:11<12:57,  3.77it/s]

CO_15466_2016 completed in 0:00:00.297190

 32%|███▏      | 1361/4292 [06:11<13:06,  3.73it/s]

CO_16603_2016 completed in 0:00:00.273874

 32%|███▏      | 1362/4292 [06:11<13:24,  3.64it/s]

CO_19499_2016 completed in 0:00:00.287753

 32%|███▏      | 1363/4292 [06:12<13:44,  3.55it/s]

CO_27058_2016 completed in 0:00:00.296586

 32%|███▏      | 1365/4292 [06:12<11:37,  4.20it/s]

CO_56146_2016 completed in 0:00:00.210270
CT_4176_2016 completed in 0:00:00.184206

 32%|███▏      | 1367/4292 [06:12<10:44,  4.54it/s]

CT_7716_2016 completed in 0:00:00.207286
CT_19497_2016 completed in 0:00:00.199181

 32%|███▏      | 1368/4292 [06:13<11:57,  4.08it/s]

CT_20038_2016 completed in 0:00:00.302618

 32%|███▏      | 1369/4292 [06:13<12:10,  4.00it/s]

DC_15270_2016 completed in 0:00:00.259099

 32%|███▏      | 1370/4292 [06:13<13:11,  3.69it/s]

DE_5027_2016 completed in 0:00:00.319441

 32%|███▏      | 1371/4292 [06:14<12:53,  3.78it/s]

DE_5070_2016 completed in 0:00:00.248944

 32%|███▏      | 1372/4292 [06:14<12:49,  3.79it/s]

DE_5335_2016 completed in 0:00:00.260038

 32%|███▏      | 1373/4292 [06:14<13:07,  3.71it/s]

DE_13519_2016 completed in 0:00:00.283001

 32%|███▏      | 1374/4292 [06:14<13:46,  3.53it/s]

FL_6452_2016 completed in 0:00:00.314380

 32%|███▏      | 1375/4292 [06:15<13:30,  3.60it/s]

FL_6455_2016 completed in 0:00:00.264003

 32%|███▏      | 1376/4292 [06:15<13:16,  3.66it/s]

FL_6457_2016 completed in 0:00:00.256305

 32%|███▏      | 1377/4292 [06:15<12:22,  3.93it/s]

FL_7801_2016 completed in 0:00:00.210430

 32%|███▏      | 1378/4292 [06:16<12:41,  3.83it/s]

FL_9617_2016 completed in 0:00:00.275853

 32%|███▏      | 1379/4292 [06:16<13:05,  3.71it/s]

FL_18454_2016 completed in 0:00:00.288005

 32%|███▏      | 1380/4292 [06:16<12:22,  3.92it/s]

GA_3916_2016 completed in 0:00:00.218539

 32%|███▏      | 1381/4292 [06:16<13:18,  3.64it/s]

HI_8287_2016 completed in 0:00:00.317073

 32%|███▏      | 1382/4292 [06:17<12:35,  3.85it/s]

HI_10071_2016 completed in 0:00:00.222215

 32%|███▏      | 1383/4292 [06:17<12:27,  3.89it/s]

HI_11843_2016 completed in 0:00:00.249760

 32%|███▏      | 1384/4292 [06:17<12:39,  3.83it/s]

HI_19547_2016 completed in 0:00:00.266854

 32%|███▏      | 1385/4292 [06:17<12:07,  4.00it/s]

IA_9417_2016 completed in 0:00:00.223576

 32%|███▏      | 1386/4292 [06:18<14:15,  3.40it/s]

IA_12341_2016 completed in 0:00:00.396435

 32%|███▏      | 1387/4292 [06:18<19:00,  2.55it/s]

ID_9187_2016 completed in 0:00:00.620278

 32%|███▏      | 1389/4292 [06:19<14:13,  3.40it/s]

ID_9191_2016 completed in 0:00:00.207768
ID_10454_2016 completed in 0:00:00.192223

 32%|███▏      | 1390/4292 [06:19<13:22,  3.62it/s]

ID_11273_2016 completed in 0:00:00.234186

 32%|███▏      | 1392/4292 [06:19<12:30,  3.87it/s]

ID_14354_2016 completed in 0:00:00.343801
ID_20169_2016 completed in 0:00:00.168661

 32%|███▏      | 1393/4292 [06:20<11:59,  4.03it/s]

IL_4110_2016 completed in 0:00:00.222976

 32%|███▏      | 1394/4292 [06:20<11:37,  4.16it/s]

IL_12341_2016 completed in 0:00:00.221978

 33%|███▎      | 1395/4292 [06:20<12:33,  3.84it/s]

IL_13032_2016 completed in 0:00:00.304886

 33%|███▎      | 1396/4292 [06:21<13:39,  3.53it/s]

IL_56697_2016 completed in 0:00:00.335488

 33%|███▎      | 1397/4292 [06:21<13:38,  3.54it/s]

IN_9273_2016 completed in 0:00:00.280974

 33%|███▎      | 1398/4292 [06:21<12:57,  3.72it/s]

IN_9324_2016 completed in 0:00:00.234512

 33%|███▎      | 1399/4292 [06:21<13:44,  3.51it/s]

IN_13756_2016 completed in 0:00:00.322846

 33%|███▎      | 1400/4292 [06:22<16:19,  2.95it/s]

IN_15470_2016 completed in 0:00:00.462676

 33%|███▎      | 1402/4292 [06:22<13:31,  3.56it/s]

IN_17633_2016 completed in 0:00:00.282402
KS_5860_2016 completed in 0:00:00.183619

 33%|███▎      | 1403/4292 [06:23<21:20,  2.26it/s]

KS_9996_2016 completed in 0:00:00.821344

 33%|███▎      | 1404/4292 [06:23<19:01,  2.53it/s]

KS_10000_2016 completed in 0:00:00.282665

 33%|███▎      | 1406/4292 [06:24<13:43,  3.51it/s]

KS_10005_2016 completed in 0:00:00.211915
KS_22500_2016 completed in 0:00:00.155011

 33%|███▎      | 1407/4292 [06:24<12:11,  3.94it/s]

KY_9964_2016 completed in 0:00:00.178926

 33%|███▎      | 1408/4292 [06:24<13:29,  3.56it/s]

KY_10171_2016 completed in 0:00:00.342598

 33%|███▎      | 1409/4292 [06:25<13:20,  3.60it/s]

KY_11249_2016 completed in 0:00:00.269446

 33%|███▎      | 1410/4292 [06:25<13:30,  3.56it/s]

KY_17564_2016 completed in 0:00:00.288467

 33%|███▎      | 1411/4292 [06:25<14:47,  3.25it/s]

KY_19446_2016 completed in 0:00:00.369680

 33%|███▎      | 1413/4292 [06:26<13:01,  3.68it/s]

KY_22053_2016 completed in 0:00:00.313301
KY_49998_2016 completed in 0:00:00.181180

 33%|███▎      | 1414/4292 [06:26<12:32,  3.83it/s]

LA_3265_2016 completed in 0:00:00.236770

 33%|███▎      | 1415/4292 [06:26<12:47,  3.75it/s]

LA_11241_2016 completed in 0:00:00.278947

 33%|███▎      | 1416/4292 [06:27<12:18,  3.89it/s]

LA_13478_2016 completed in 0:00:00.232408

 33%|███▎      | 1417/4292 [06:27<12:49,  3.74it/s]

LA_17698_2016 completed in 0:00:00.291640

 33%|███▎      | 1418/4292 [06:27<12:56,  3.70it/s]

MA_6374_2016 completed in 0:00:00.272954

 33%|███▎      | 1419/4292 [06:27<12:33,  3.81it/s]

MA_8774_2016 completed in 0:00:00.243214

 33%|███▎      | 1421/4292 [06:28<11:32,  4.15it/s]

MA_11804_2016 completed in 0:00:00.250134
MA_13206_2016 completed in 0:00:00.195529

 33%|███▎      | 1422/4292 [06:28<13:10,  3.63it/s]

MA_15748_2016 completed in 0:00:00.353629

 33%|███▎      | 1423/4292 [06:30<40:50,  1.17it/s]

MA_20455_2016 completed in 0:00:02.203139

 33%|███▎      | 1424/4292 [06:31<32:55,  1.45it/s]

MA_54913_2016 completed in 0:00:00.302422

 33%|███▎      | 1425/4292 [06:31<27:14,  1.75it/s]

MD_1167_2016 completed in 0:00:00.292421

 33%|███▎      | 1427/4292 [06:31<18:29,  2.58it/s]

MD_5027_2016 completed in 0:00:00.244252
MD_15263_2016 completed in 0:00:00.186827

 33%|███▎      | 1428/4292 [06:32<16:28,  2.90it/s]

MD_15270_2016 completed in 0:00:00.246762

 33%|███▎      | 1429/4292 [06:32<15:36,  3.06it/s]

MD_17637_2016 completed in 0:00:00.283855

 33%|███▎      | 1430/4292 [06:32<14:04,  3.39it/s]

ME_1179_2016 completed in 0:00:00.219656

 33%|███▎      | 1431/4292 [06:33<15:18,  3.12it/s]

ME_3266_2016 completed in 0:00:00.380040

 33%|███▎      | 1432/4292 [06:33<15:25,  3.09it/s]

MI_392_2016 completed in 0:00:00.328881

 33%|███▎      | 1433/4292 [06:33<15:32,  3.07it/s]

MI_3828_2016 completed in 0:00:00.331005

 33%|███▎      | 1434/4292 [06:34<21:48,  2.18it/s]

MI_4254_2016 completed in 0:00:00.764556

 33%|███▎      | 1435/4292 [06:34<19:32,  2.44it/s]

MI_5109_2016 completed in 0:00:00.298468
MI_9324_2016 completed in 0:00:00.202170

 33%|███▎      | 1437/4292 [06:35<15:06,  3.15it/s]

MI_10704_2016 completed in 0:00:00.244854

 34%|███▎      | 1438/4292 [06:35<13:50,  3.44it/s]

MI_19578_2016 completed in 0:00:00.228449

 34%|███▎      | 1439/4292 [06:35<14:17,  3.33it/s]

MI_20847_2016 completed in 0:00:00.322311

 34%|███▎      | 1440/4292 [06:35<13:48,  3.44it/s]

MI_20860_2016 completed in 0:00:00.266246

 34%|███▎      | 1441/4292 [06:36<15:45,  3.02it/s]

MN_689_2016 completed in 0:00:00.426329

 34%|███▎      | 1442/4292 [06:36<14:30,  3.27it/s]

MN_5574_2016 completed in 0:00:00.243950

 34%|███▎      | 1443/4292 [06:37<18:07,  2.62it/s]

MN_12647_2016 completed in 0:00:00.558229

 34%|███▎      | 1444/4292 [06:37<17:59,  2.64it/s]

MN_13781_2016 completed in 0:00:00.372559

 34%|███▎      | 1445/4292 [06:37<15:52,  2.99it/s]

MN_14232_2016 completed in 0:00:00.229848

 34%|███▎      | 1446/4292 [06:38<16:16,  2.91it/s]

MN_16181_2016 completed in 0:00:00.362326

 34%|███▎      | 1447/4292 [06:38<14:29,  3.27it/s]

MN_17267_2016 completed in 0:00:00.216440

 34%|███▎      | 1448/4292 [06:38<14:38,  3.24it/s]

MN_20996_2016 completed in 0:00:00.315372

 34%|███▍      | 1449/4292 [06:38<13:49,  3.43it/s]

MN_25177_2016 completed in 0:00:00.251068

 34%|███▍      | 1450/4292 [06:39<13:25,  3.53it/s]

MO_4675_2016 completed in 0:00:00.263170

 34%|███▍      | 1451/4292 [06:39<13:29,  3.51it/s]

MO_5860_2016 completed in 0:00:00.287210

 34%|███▍      | 1452/4292 [06:39<12:45,  3.71it/s]

MO_9231_2016 completed in 0:00:00.232107

 34%|███▍      | 1453/4292 [06:40<12:35,  3.76it/s]

MO_10000_2016 completed in 0:00:00.257569

 34%|███▍      | 1454/4292 [06:40<12:52,  3.67it/s]

MO_12698_2016 completed in 0:00:00.283528

 34%|███▍      | 1455/4292 [06:40<12:06,  3.91it/s]

MO_17833_2016 completed in 0:00:00.217081

 34%|███▍      | 1456/4292 [06:40<12:25,  3.80it/s]

MO_19436_2016 completed in 0:00:00.277649

 34%|███▍      | 1457/4292 [06:41<14:49,  3.19it/s]

MS_3841_2016 completed in 0:00:00.430055

 34%|███▍      | 1458/4292 [06:41<14:40,  3.22it/s]

MS_17647_2016 completed in 0:00:00.301856

 34%|███▍      | 1459/4292 [06:41<15:06,  3.13it/s]

MT_6395_2016 completed in 0:00:00.337582

 34%|███▍      | 1460/4292 [06:42<13:47,  3.42it/s]

MT_12692_2016 completed in 0:00:00.225563

 34%|███▍      | 1461/4292 [06:42<12:49,  3.68it/s]

MT_12825_2016 completed in 0:00:00.222539

 34%|███▍      | 1462/4292 [06:42<14:10,  3.33it/s]

MT_19603_2016 completed in 0:00:00.366956

 34%|███▍      | 1463/4292 [06:43<14:32,  3.24it/s]

MT_20997_2016 completed in 0:00:00.325942

 34%|███▍      | 1464/4292 [06:43<15:31,  3.04it/s]

NC_3046_2016 completed in 0:00:00.376921

 34%|███▍      | 1466/4292 [06:43<12:49,  3.67it/s]

NC_5416_2016 completed in 0:00:00.243177
NC_9837_2016 completed in 0:00:00.197569

 34%|███▍      | 1467/4292 [06:44<11:46,  4.00it/s]

NC_16496_2016 completed in 0:00:00.197130

 34%|███▍      | 1468/4292 [06:44<12:21,  3.81it/s]

NC_19876_2016 completed in 0:00:00.290937

 34%|███▍      | 1469/4292 [06:44<13:38,  3.45it/s]

NC_24889_2016 completed in 0:00:00.353092

 34%|███▍      | 1470/4292 [06:44<12:32,  3.75it/s]

ND_12301_2016 completed in 0:00:00.210379

 34%|███▍      | 1471/4292 [06:45<12:05,  3.89it/s]

ND_14232_2016 completed in 0:00:00.233446

 34%|███▍      | 1472/4292 [06:45<13:12,  3.56it/s]

ND_19790_2016 completed in 0:00:00.335632

 34%|███▍      | 1473/4292 [06:45<14:09,  3.32it/s]

ND_24949_2016 completed in 0:00:00.346569

 34%|███▍      | 1474/4292 [06:46<13:08,  3.58it/s]

NE_4373_2016 completed in 0:00:00.227349

 34%|███▍      | 1475/4292 [06:46<13:35,  3.45it/s]

NE_6779_2016 completed in 0:00:00.311118

 34%|███▍      | 1476/4292 [06:46<12:49,  3.66it/s]

NE_11018_2016 completed in 0:00:00.234934

 34%|███▍      | 1478/4292 [06:47<11:11,  4.19it/s]

NE_11251_2016 completed in 0:00:00.225243
NE_12539_2016 completed in 0:00:00.184816

 34%|███▍      | 1479/4292 [06:47<11:15,  4.17it/s]

NE_13337_2016 completed in 0:00:00.242228

 35%|███▍      | 1481/4292 [06:47<10:20,  4.53it/s]

NE_13664_2016 completed in 0:00:00.206934
NE_14127_2016 completed in 0:00:00.196147

 35%|███▍      | 1482/4292 [06:48<19:32,  2.40it/s]

NE_17642_2016 completed in 0:00:00.874148

 35%|███▍      | 1483/4292 [06:48<16:58,  2.76it/s]

NH_13441_2016 completed in 0:00:00.233514

 35%|███▍      | 1484/4292 [06:49<19:16,  2.43it/s]

NH_15472_2016 completed in 0:00:00.526413

 35%|███▍      | 1486/4292 [06:49<14:46,  3.16it/s]

NH_24590_2016 completed in 0:00:00.291916
NJ_963_2016 completed in 0:00:00.174846

 35%|███▍      | 1488/4292 [06:50<12:47,  3.65it/s]

NJ_9726_2016 completed in 0:00:00.300935
NJ_15477_2016 completed in 0:00:00.183869

 35%|███▍      | 1489/4292 [06:50<11:56,  3.91it/s]

NJ_16213_2016 completed in 0:00:00.211986

 35%|███▍      | 1490/4292 [06:51<24:13,  1.93it/s]

NM_3287_2016 completed in 0:00:01.131909

 35%|███▍      | 1491/4292 [06:51<20:31,  2.27it/s]

NM_5701_2016 completed in 0:00:00.254175

 35%|███▍      | 1492/4292 [06:52<17:56,  2.60it/s]

NM_6204_2016 completed in 0:00:00.254592

 35%|███▍      | 1493/4292 [06:52<16:09,  2.89it/s]

NM_11204_2016 completed in 0:00:00.256381

 35%|███▍      | 1494/4292 [06:52<15:15,  3.06it/s]

NM_15473_2016 completed in 0:00:00.280932

 35%|███▍      | 1495/4292 [06:52<14:53,  3.13it/s]

NM_17718_2016 completed in 0:00:00.301002

 35%|███▍      | 1496/4292 [06:53<14:54,  3.13it/s]

NV_2008_2016 completed in 0:00:00.317710

 35%|███▍      | 1497/4292 [06:53<13:45,  3.39it/s]

NV_13073_2016 completed in 0:00:00.233590

 35%|███▍      | 1498/4292 [06:53<13:13,  3.52it/s]

NV_13407_2016 completed in 0:00:00.254165

 35%|███▍      | 1499/4292 [06:54<17:09,  2.71it/s]

NV_17166_2016 completed in 0:00:00.564687

 35%|███▍      | 1500/4292 [06:54<17:55,  2.60it/s]

NV_19840_2016 completed in 0:00:00.422877

 35%|███▍      | 1502/4292 [06:55<14:51,  3.13it/s]

NY_3249_2016 completed in 0:00:00.399198
NY_4226_2016 completed in 0:00:00.154618

 35%|███▌      | 1503/4292 [06:55<13:12,  3.52it/s]

NY_11171_2016 completed in 0:00:00.201594

 35%|███▌      | 1504/4292 [06:55<14:43,  3.16it/s]

NY_13511_2016 completed in 0:00:00.391917

 35%|███▌      | 1505/4292 [06:56<19:38,  2.37it/s]

NY_13573_2016 completed in 0:00:00.669045

 35%|███▌      | 1506/4292 [06:56<17:08,  2.71it/s]

NY_14154_2016 completed in 0:00:00.242855

 35%|███▌      | 1508/4292 [06:57<13:32,  3.43it/s]

NY_16183_2016 completed in 0:00:00.266622
OH_3542_2016 completed in 0:00:00.181740

 35%|███▌      | 1509/4292 [06:57<12:25,  3.73it/s]

OH_3755_2016 completed in 0:00:00.211758

 35%|███▌      | 1510/4292 [06:57<11:48,  3.92it/s]

OH_4922_2016 completed in 0:00:00.222910

 35%|███▌      | 1511/4292 [06:57<11:44,  3.95it/s]

OH_13998_2016 completed in 0:00:00.248290

 35%|███▌      | 1512/4292 [06:58<11:58,  3.87it/s]

OH_14006_2016 completed in 0:00:00.270393

 35%|███▌      | 1514/4292 [06:58<10:51,  4.27it/s]

OH_18997_2016 completed in 0:00:00.247770
OK_5860_2016 completed in 0:00:00.184237

 35%|███▌      | 1515/4292 [06:58<10:35,  4.37it/s]

OK_13734_2016 completed in 0:00:00.215166

 35%|███▌      | 1516/4292 [06:59<11:26,  4.04it/s]

OK_14062_2016 completed in 0:00:00.289544

 35%|███▌      | 1517/4292 [06:59<11:28,  4.03it/s]

OK_14063_2016 completed in 0:00:00.248854

 35%|███▌      | 1518/4292 [06:59<13:31,  3.42it/s]

OK_15474_2016 completed in 0:00:00.395494

 35%|███▌      | 1519/4292 [07:00<13:04,  3.53it/s]

OK_19785_2016 completed in 0:00:00.259755

 35%|███▌      | 1520/4292 [07:00<12:48,  3.61it/s]

OR_6022_2016 completed in 0:00:00.262546

 35%|███▌      | 1521/4292 [07:00<14:35,  3.17it/s]

OR_9191_2016 completed in 0:00:00.405255

 35%|███▌      | 1522/4292 [07:01<13:53,  3.32it/s]

OR_14354_2016 completed in 0:00:00.264581

 35%|███▌      | 1523/4292 [07:01<13:11,  3.50it/s]

OR_15248_2016 completed in 0:00:00.249842

 36%|███▌      | 1524/4292 [07:01<15:39,  2.95it/s]

OR_18260_2016 completed in 0:00:00.463306

 36%|███▌      | 1525/4292 [07:01<14:23,  3.20it/s]

OR_28541_2016 completed in 0:00:00.247500

 36%|███▌      | 1526/4292 [07:02<15:27,  2.98it/s]

OR_40437_2016 completed in 0:00:00.388633

 36%|███▌      | 1527/4292 [07:02<15:44,  2.93it/s]

PA_3597_2016 completed in 0:00:00.355619

 36%|███▌      | 1528/4292 [07:03<15:41,  2.94it/s]

PA_5487_2016 completed in 0:00:00.337692

 36%|███▌      | 1529/4292 [07:03<14:15,  3.23it/s]

PA_12390_2016 completed in 0:00:00.235858

 36%|███▌      | 1530/4292 [07:03<14:24,  3.20it/s]

PA_14711_2016 completed in 0:00:00.319857

 36%|███▌      | 1531/4292 [07:04<28:52,  1.59it/s]

PA_14715_2016 completed in 0:00:01.359961

 36%|███▌      | 1532/4292 [07:05<24:54,  1.85it/s]

PA_14716_2016 completed in 0:00:00.339525

 36%|███▌      | 1533/4292 [07:05<21:18,  2.16it/s]

PA_14940_2016 completed in 0:00:00.280187

 36%|███▌      | 1534/4292 [07:05<19:57,  2.30it/s]

PA_15045_2016 completed in 0:00:00.365239

 36%|███▌      | 1535/4292 [07:06<18:22,  2.50it/s]

PA_19390_2016 completed in 0:00:00.316822

 36%|███▌      | 1536/4292 [07:06<16:24,  2.80it/s]

PA_20334_2016 completed in 0:00:00.257020

 36%|███▌      | 1537/4292 [07:06<17:14,  2.66it/s]

PA_20387_2016 completed in 0:00:00.416306

 36%|███▌      | 1538/4292 [07:07<15:15,  3.01it/s]

RI_1857_2016 completed in 0:00:00.230229

 36%|███▌      | 1539/4292 [07:07<13:39,  3.36it/s]

RI_13214_2016 completed in 0:00:00.215738

 36%|███▌      | 1540/4292 [07:07<12:45,  3.59it/s]

SC_1613_2016 completed in 0:00:00.231954

 36%|███▌      | 1541/4292 [07:07<11:53,  3.86it/s]

SC_3046_2016 completed in 0:00:00.214065

 36%|███▌      | 1542/4292 [07:08<11:30,  3.98it/s]

SC_5416_2016 completed in 0:00:00.230509

 36%|███▌      | 1543/4292 [07:08<12:03,  3.80it/s]

SC_14398_2016 completed in 0:00:00.290893

 36%|███▌      | 1544/4292 [07:08<11:19,  4.04it/s]

SC_17539_2016 completed in 0:00:00.209190

 36%|███▌      | 1545/4292 [07:08<13:18,  3.44it/s]

SC_17543_2016 completed in 0:00:00.390913

 36%|███▌      | 1546/4292 [07:09<13:21,  3.43it/s]

SD_1769_2016 completed in 0:00:00.293181

 36%|███▌      | 1547/4292 [07:09<13:22,  3.42it/s]

SD_13337_2016 completed in 0:00:00.293342

 36%|███▌      | 1548/4292 [07:09<13:55,  3.28it/s]

SD_14232_2016 completed in 0:00:00.331631

 36%|███▌      | 1549/4292 [07:10<15:51,  2.88it/s]

SD_17267_2016 completed in 0:00:00.445607

 36%|███▌      | 1550/4292 [07:10<15:18,  2.98it/s]

SD_19293_2016 completed in 0:00:00.306380

 36%|███▌      | 1551/4292 [07:10<14:49,  3.08it/s]

SD_20401_2016 completed in 0:00:00.298343

 36%|███▌      | 1552/4292 [07:11<13:27,  3.39it/s]

TN_10331_2016 completed in 0:00:00.224236

 36%|███▌      | 1553/4292 [07:11<12:48,  3.57it/s]

TX_5701_2016 completed in 0:00:00.246630

 36%|███▌      | 1554/4292 [07:11<13:26,  3.39it/s]

TX_16604_2016 completed in 0:00:00.326243

 36%|███▌      | 1555/4292 [07:12<13:20,  3.42it/s]

TX_17698_2016 completed in 0:00:00.286012

 36%|███▋      | 1556/4292 [07:12<16:22,  2.78it/s]

TX_55937_2016 completed in 0:00:00.514092

 36%|███▋      | 1557/4292 [07:12<14:28,  3.15it/s]

UT_2010_2016 completed in 0:00:00.219496

 36%|███▋      | 1558/4292 [07:13<13:07,  3.47it/s]

UT_11135_2016 completed in 0:00:00.218931

 36%|███▋      | 1559/4292 [07:13<12:44,  3.57it/s]

UT_12866_2016 completed in 0:00:00.259442

 36%|███▋      | 1560/4292 [07:13<15:27,  2.94it/s]

UT_14354_2016 completed in 0:00:00.478332

 36%|███▋      | 1561/4292 [07:13<14:02,  3.24it/s]

UT_15444_2016 completed in 0:00:00.234485

 36%|███▋      | 1562/4292 [07:14<12:56,  3.52it/s]

UT_17845_2016 completed in 0:00:00.227397

 36%|███▋      | 1563/4292 [07:14<13:28,  3.38it/s]

UT_17874_2016 completed in 0:00:00.322715

 36%|███▋      | 1564/4292 [07:14<12:43,  3.57it/s]

UT_18206_2016 completed in 0:00:00.240449

 36%|███▋      | 1565/4292 [07:15<12:39,  3.59it/s]

VA_84_2016 completed in 0:00:00.274862

 36%|███▋      | 1566/4292 [07:15<13:21,  3.40it/s]

VA_733_2016 completed in 0:00:00.329138

 37%|███▋      | 1568/4292 [07:16<14:01,  3.24it/s]

VA_10171_2016 completed in 0:00:00.497361
VA_17066_2016 completed in 0:00:00.199941

 37%|███▋      | 1569/4292 [07:16<14:30,  3.13it/s]

VA_19876_2016 completed in 0:00:00.343436

 37%|███▋      | 1570/4292 [07:16<13:32,  3.35it/s]

VA_19882_2016 completed in 0:00:00.247647

 37%|███▋      | 1571/4292 [07:17<14:53,  3.04it/s]

VA_40228_2016 completed in 0:00:00.397795

 37%|███▋      | 1572/4292 [07:17<14:21,  3.16it/s]

VT_2548_2016 completed in 0:00:00.288088

 37%|███▋      | 1573/4292 [07:17<13:56,  3.25it/s]

VT_7601_2016 completed in 0:00:00.285984

 37%|███▋      | 1574/4292 [07:17<13:58,  3.24it/s]

VT_19791_2016 completed in 0:00:00.308699

 37%|███▋      | 1575/4292 [07:18<14:23,  3.15it/s]

WA_3660_2016 completed in 0:00:00.337806

 37%|███▋      | 1576/4292 [07:18<15:07,  2.99it/s]

WA_14354_2016 completed in 0:00:00.371879

 37%|███▋      | 1577/4292 [07:19<17:56,  2.52it/s]

WA_15500_2016 completed in 0:00:00.539981

 37%|███▋      | 1578/4292 [07:19<15:50,  2.85it/s]

WA_16868_2016 completed in 0:00:00.241815

 37%|███▋      | 1579/4292 [07:19<14:13,  3.18it/s]

WA_17470_2016 completed in 0:00:00.229348

 37%|███▋      | 1580/4292 [07:19<14:00,  3.23it/s]

WA_18429_2016 completed in 0:00:00.298924

 37%|███▋      | 1581/4292 [07:20<12:47,  3.53it/s]

WA_20169_2016 completed in 0:00:00.219670

 37%|███▋      | 1582/4292 [07:20<12:19,  3.67it/s]

WI_4715_2016 completed in 0:00:00.247822

 37%|███▋      | 1583/4292 [07:20<12:56,  3.49it/s]

WI_5574_2016 completed in 0:00:00.317378

 37%|███▋      | 1584/4292 [07:21<13:06,  3.45it/s]

WI_11479_2016 completed in 0:00:00.298223

 37%|███▋      | 1585/4292 [07:21<18:37,  2.42it/s]

WI_13697_2016 completed in 0:00:00.698449

 37%|███▋      | 1586/4292 [07:22<16:12,  2.78it/s]

WI_13815_2016 completed in 0:00:00.233525

 37%|███▋      | 1587/4292 [07:22<15:40,  2.88it/s]

WI_20847_2016 completed in 0:00:00.319457

 37%|███▋      | 1588/4292 [07:22<14:42,  3.06it/s]

WI_20856_2016 completed in 0:00:00.276154

 37%|███▋      | 1589/4292 [07:22<14:18,  3.15it/s]

WI_20860_2016 completed in 0:00:00.295597

 37%|███▋      | 1590/4292 [07:23<18:50,  2.39it/s]

WV_733_2016 completed in 0:00:00.652511

 37%|███▋      | 1591/4292 [07:23<16:20,  2.75it/s]

WV_12796_2016 completed in 0:00:00.233783

 37%|███▋      | 1592/4292 [07:24<16:23,  2.75it/s]

WV_15263_2016 completed in 0:00:00.365591

 37%|███▋      | 1593/4292 [07:24<15:43,  2.86it/s]

WV_20521_2016 completed in 0:00:00.314820

 37%|███▋      | 1594/4292 [07:24<13:59,  3.21it/s]

WY_3461_2016 completed in 0:00:00.220153

 37%|███▋      | 1595/4292 [07:24<13:05,  3.44it/s]

WY_7222_2016 completed in 0:00:00.243525

 37%|███▋      | 1596/4292 [07:25<12:20,  3.64it/s]

WY_8566_2016 completed in 0:00:00.235069

 37%|███▋      | 1597/4292 [07:25<13:33,  3.31it/s]

WY_11273_2016 completed in 0:00:00.364295

 37%|███▋      | 1598/4292 [07:25<15:25,  2.91it/s]

WY_14354_2016 completed in 0:00:00.439918

 37%|███▋      | 1599/4292 [07:27<25:48,  1.74it/s]

WY_19156_2016 completed in 0:00:01.114461

 37%|███▋      | 1600/4292 [07:27<22:05,  2.03it/s]

WY_27058_2016 completed in 0:00:00.298283

 37%|███▋      | 1601/4292 [07:27<19:13,  2.33it/s]

GA_9601_2016 completed in 0:00:00.279766

 37%|███▋      | 1602/4292 [07:28<18:42,  2.40it/s]

MS_12685_2016 completed in 0:00:00.389411

 37%|███▋      | 1603/4292 [07:28<18:45,  2.39it/s]

AK_219_2017 completed in 0:00:00.421250

 37%|███▋      | 1605/4292 [07:28<14:01,  3.19it/s]

AK_599_2017 completed in 0:00:00.246924
AK_3522_2017 completed in 0:00:00.185172

 37%|███▋      | 1606/4292 [07:29<13:04,  3.42it/s]

AK_7353_2017 completed in 0:00:00.242255

 37%|███▋      | 1608/4292 [07:29<11:39,  3.84it/s]

AK_11824_2017 completed in 0:00:00.311447
AK_19558_2017 completed in 0:00:00.172163

 37%|███▋      | 1609/4292 [07:30<14:01,  3.19it/s]

AL_195_2017 completed in 0:00:00.436142

 38%|███▊      | 1610/4292 [07:30<13:36,  3.28it/s]

AR_814_2017 completed in 0:00:00.282143

 38%|███▊      | 1611/4292 [07:30<14:37,  3.05it/s]

AR_817_2017 completed in 0:00:00.379192

 38%|███▊      | 1612/4292 [07:31<14:37,  3.05it/s]

AR_3093_2017 completed in 0:00:00.326633

 38%|███▊      | 1613/4292 [07:31<15:03,  2.97it/s]

AR_5860_2017 completed in 0:00:00.358504

 38%|███▊      | 1614/4292 [07:32<18:06,  2.46it/s]

AR_6342_2017 completed in 0:00:00.562305

 38%|███▊      | 1615/4292 [07:32<18:28,  2.41it/s]

AR_13718_2017 completed in 0:00:00.430301

 38%|███▊      | 1616/4292 [07:32<16:34,  2.69it/s]

AR_14063_2017 completed in 0:00:00.272142

 38%|███▊      | 1617/4292 [07:32<14:28,  3.08it/s]

AR_17698_2017 completed in 0:00:00.213747

 38%|███▊      | 1618/4292 [07:33<14:18,  3.11it/s]

AZ_176_2017 completed in 0:00:00.308760

 38%|███▊      | 1619/4292 [07:33<14:31,  3.07it/s]

AZ_803_2017 completed in 0:00:00.337038

 38%|███▊      | 1621/4292 [07:33<11:40,  3.81it/s]

AZ_12919_2017 completed in 0:00:00.226904
AZ_16572_2017 completed in 0:00:00.181505

 38%|███▊      | 1622/4292 [07:34<12:48,  3.47it/s]

AZ_19189_2017 completed in 0:00:00.346927

 38%|███▊      | 1623/4292 [07:34<12:10,  3.65it/s]

AZ_19728_2017 completed in 0:00:00.239485

 38%|███▊      | 1624/4292 [07:34<12:30,  3.55it/s]

AZ_21538_2017 completed in 0:00:00.298384

 38%|███▊      | 1625/4292 [07:35<17:01,  2.61it/s]

AZ_24211_2017 completed in 0:00:00.619221

 38%|███▊      | 1626/4292 [07:35<17:04,  2.60it/s]

CA_9216_2017 completed in 0:00:00.385748

 38%|███▊      | 1627/4292 [07:36<17:31,  2.53it/s]

CA_11208_2017 completed in 0:00:00.418163

 38%|███▊      | 1628/4292 [07:36<16:27,  2.70it/s]

CA_12745_2017 completed in 0:00:00.313967

 38%|███▊      | 1629/4292 [07:41<1:17:33,  1.75s/it]

CA_14328_2017 completed in 0:00:04.958810

 38%|███▊      | 1630/4292 [07:42<1:04:36,  1.46s/it]

CA_14354_2017 completed in 0:00:00.776229

 38%|███▊      | 1631/4292 [07:42<49:12,  1.11s/it]

CA_14534_2017 completed in 0:00:00.299109

 38%|███▊      | 1632/4292 [07:43<39:23,  1.13it/s]

CA_16534_2017 completed in 0:00:00.371653

 38%|███▊      | 1633/4292 [07:43<31:42,  1.40it/s]

CA_16609_2017 completed in 0:00:00.308518

 38%|███▊      | 1634/4292 [07:43<25:31,  1.74it/s]

CA_16655_2017 completed in 0:00:00.249941

 38%|███▊      | 1636/4292 [07:44<18:43,  2.36it/s]

CA_17609_2017 completed in 0:00:00.405220
CA_17612_2017 completed in 0:00:00.181671

 38%|███▊      | 1638/4292 [07:45<18:28,  2.39it/s]

CA_19281_2017 completed in 0:00:00.714560
CO_3989_2017 completed in 0:00:00.199939

 38%|███▊      | 1639/4292 [07:45<16:05,  2.75it/s]

CO_6604_2017 completed in 0:00:00.236842

 38%|███▊      | 1640/4292 [07:45<16:44,  2.64it/s]

CO_9336_2017 completed in 0:00:00.412266

 38%|███▊      | 1641/4292 [07:46<15:22,  2.88it/s]

CO_12866_2017 completed in 0:00:00.274691

 38%|███▊      | 1642/4292 [07:46<13:39,  3.23it/s]

CO_15257_2017 completed in 0:00:00.217996

 38%|███▊      | 1643/4292 [07:46<14:44,  3.00it/s]

CO_15466_2017 completed in 0:00:00.389997

 38%|███▊      | 1644/4292 [07:47<15:55,  2.77it/s]

CO_16603_2017 completed in 0:00:00.423756

 38%|███▊      | 1646/4292 [07:47<14:14,  3.10it/s]

CO_19499_2017 completed in 0:00:00.434816
CO_27058_2017 completed in 0:00:00.180671

 38%|███▊      | 1647/4292 [07:47<13:18,  3.31it/s]

CO_56146_2017 completed in 0:00:00.252437

 38%|███▊      | 1648/4292 [07:48<14:05,  3.13it/s]

CT_4176_2017 completed in 0:00:00.360531

 38%|███▊      | 1649/4292 [07:48<12:51,  3.43it/s]

CT_7716_2017 completed in 0:00:00.225976

 38%|███▊      | 1650/4292 [07:48<12:34,  3.50it/s]

CT_19497_2017 completed in 0:00:00.270446

 38%|███▊      | 1651/4292 [07:49<13:59,  3.15it/s]

CT_20038_2017 completed in 0:00:00.391356

 38%|███▊      | 1652/4292 [07:49<13:11,  3.34it/s]

DC_15270_2017 completed in 0:00:00.257021

 39%|███▊      | 1653/4292 [07:49<12:15,  3.59it/s]

DE_5027_2017 completed in 0:00:00.227887

 39%|███▊      | 1655/4292 [07:50<10:48,  4.07it/s]

DE_5070_2017 completed in 0:00:00.277081
DE_5335_2017 completed in 0:00:00.168624

 39%|███▊      | 1656/4292 [07:50<10:38,  4.13it/s]

DE_13519_2017 completed in 0:00:00.232420

 39%|███▊      | 1657/4292 [07:50<11:55,  3.68it/s]

FL_6452_2017 completed in 0:00:00.339706

 39%|███▊      | 1658/4292 [07:50<11:45,  3.74it/s]

FL_6455_2017 completed in 0:00:00.257717

 39%|███▊      | 1659/4292 [07:51<11:05,  3.96it/s]

FL_6457_2017 completed in 0:00:00.216777

 39%|███▊      | 1661/4292 [07:51<10:24,  4.21it/s]

FL_7801_2017 completed in 0:00:00.294460
FL_9617_2017 completed in 0:00:00.170062

 39%|███▊      | 1662/4292 [07:52<12:11,  3.59it/s]

FL_18454_2017 completed in 0:00:00.372842

 39%|███▊      | 1663/4292 [07:52<16:01,  2.73it/s]

GA_3916_2017 completed in 0:00:00.569358

 39%|███▉      | 1664/4292 [07:52<14:20,  3.05it/s]

GA_9601_2017 completed in 0:00:00.237323

 39%|███▉      | 1665/4292 [07:53<13:23,  3.27it/s]

HI_8287_2017 completed in 0:00:00.254078

 39%|███▉      | 1666/4292 [07:53<12:30,  3.50it/s]

HI_10071_2017 completed in 0:00:00.238316

 39%|███▉      | 1667/4292 [07:54<22:59,  1.90it/s]

HI_11843_2017 completed in 0:00:01.083756

 39%|███▉      | 1668/4292 [07:54<18:54,  2.31it/s]

HI_19547_2017 completed in 0:00:00.214516

 39%|███▉      | 1669/4292 [07:54<17:22,  2.52it/s]

IA_9417_2017 completed in 0:00:00.313823

 39%|███▉      | 1670/4292 [07:55<16:10,  2.70it/s]

IA_12341_2017 completed in 0:00:00.305838

 39%|███▉      | 1671/4292 [07:55<14:34,  3.00it/s]

ID_9187_2017 completed in 0:00:00.247409

 39%|███▉      | 1672/4292 [07:55<13:19,  3.28it/s]

ID_9191_2017 completed in 0:00:00.235203

 39%|███▉      | 1673/4292 [07:55<12:47,  3.41it/s]

ID_10454_2017 completed in 0:00:00.262760

 39%|███▉      | 1674/4292 [07:56<12:59,  3.36it/s]

ID_11273_2017 completed in 0:00:00.307239

 39%|███▉      | 1675/4292 [07:56<12:53,  3.38it/s]

ID_14354_2017 completed in 0:00:00.289675

 39%|███▉      | 1676/4292 [07:56<12:00,  3.63it/s]

ID_20169_2017 completed in 0:00:00.226542

 39%|███▉      | 1677/4292 [07:57<12:22,  3.52it/s]

IL_4110_2017 completed in 0:00:00.301250

 39%|███▉      | 1678/4292 [07:57<11:55,  3.65it/s]

IL_12341_2017 completed in 0:00:00.248295

 39%|███▉      | 1679/4292 [07:57<12:04,  3.61it/s]

IL_13032_2017 completed in 0:00:00.284426

 39%|███▉      | 1680/4292 [07:58<14:17,  3.05it/s]

IL_56697_2017 completed in 0:00:00.447072

 39%|███▉      | 1681/4292 [07:58<14:55,  2.92it/s]

IN_9273_2017 completed in 0:00:00.375571

 39%|███▉      | 1682/4292 [07:58<13:37,  3.19it/s]

IN_9324_2017 completed in 0:00:00.243085

 39%|███▉      | 1683/4292 [07:58<13:05,  3.32it/s]

IN_13756_2017 completed in 0:00:00.269342

 39%|███▉      | 1684/4292 [07:59<15:01,  2.89it/s]

IN_15470_2017 completed in 0:00:00.449872

 39%|███▉      | 1685/4292 [07:59<13:38,  3.19it/s]

IN_17633_2017 completed in 0:00:00.238495

 39%|███▉      | 1686/4292 [07:59<12:36,  3.45it/s]

KS_5860_2017 completed in 0:00:00.233759

 39%|███▉      | 1687/4292 [08:00<12:05,  3.59it/s]

KS_9996_2017 completed in 0:00:00.249721

 39%|███▉      | 1689/4292 [08:00<10:03,  4.31it/s]

KS_10000_2017 completed in 0:00:00.255848
KS_10005_2017 completed in 0:00:00.137566

 39%|███▉      | 1691/4292 [08:01<11:15,  3.85it/s]

KS_22500_2017 completed in 0:00:00.449126
KY_9964_2017 completed in 0:00:00.170667

 39%|███▉      | 1692/4292 [08:01<12:31,  3.46it/s]

KY_10171_2017 completed in 0:00:00.357124

 39%|███▉      | 1693/4292 [08:02<27:02,  1.60it/s]

KY_11249_2017 completed in 0:00:01.405944

 39%|███▉      | 1694/4292 [08:03<23:47,  1.82it/s]

KY_17564_2017 completed in 0:00:00.373454

 39%|███▉      | 1695/4292 [08:03<19:48,  2.19it/s]

KY_19446_2017 completed in 0:00:00.242462

 40%|███▉      | 1696/4292 [08:03<16:40,  2.59it/s]

KY_22053_2017 completed in 0:00:00.216092

 40%|███▉      | 1697/4292 [08:04<15:01,  2.88it/s]

KY_49998_2017 completed in 0:00:00.257838

 40%|███▉      | 1698/4292 [08:04<13:42,  3.16it/s]

LA_3265_2017 completed in 0:00:00.244717

 40%|███▉      | 1700/4292 [08:04<11:43,  3.68it/s]

LA_11241_2017 completed in 0:00:00.269449
LA_13478_2017 completed in 0:00:00.197006

 40%|███▉      | 1701/4292 [08:05<12:56,  3.34it/s]

LA_17698_2017 completed in 0:00:00.365090

 40%|███▉      | 1702/4292 [08:05<13:38,  3.17it/s]

MA_6374_2017 completed in 0:00:00.352607

 40%|███▉      | 1703/4292 [08:05<12:42,  3.39it/s]

MA_8774_2017 completed in 0:00:00.244093

 40%|███▉      | 1704/4292 [08:06<13:31,  3.19it/s]

MA_11804_2017 completed in 0:00:00.356483

 40%|███▉      | 1705/4292 [08:06<12:41,  3.40it/s]

MA_13206_2017 completed in 0:00:00.248719

 40%|███▉      | 1706/4292 [08:06<11:47,  3.65it/s]

MA_15748_2017 completed in 0:00:00.224713

 40%|███▉      | 1707/4292 [08:06<11:27,  3.76it/s]

MA_20455_2017 completed in 0:00:00.246932

 40%|███▉      | 1708/4292 [08:07<11:17,  3.81it/s]

MA_54913_2017 completed in 0:00:00.253242

 40%|███▉      | 1709/4292 [08:07<11:33,  3.73it/s]

MD_1167_2017 completed in 0:00:00.281287

 40%|███▉      | 1710/4292 [08:07<10:44,  4.01it/s]

MD_5027_2017 completed in 0:00:00.204313

 40%|███▉      | 1711/4292 [08:07<10:36,  4.05it/s]

MD_15263_2017 completed in 0:00:00.239068

 40%|███▉      | 1712/4292 [08:08<11:06,  3.87it/s]

MD_15270_2017 completed in 0:00:00.283308

 40%|███▉      | 1713/4292 [08:08<11:46,  3.65it/s]

MD_17637_2017 completed in 0:00:00.309313

 40%|███▉      | 1714/4292 [08:08<12:31,  3.43it/s]

ME_1179_2017 completed in 0:00:00.331639

 40%|███▉      | 1715/4292 [08:08<11:32,  3.72it/s]

ME_3266_2017 completed in 0:00:00.214185

 40%|███▉      | 1716/4292 [08:09<11:02,  3.89it/s]

MI_392_2017 completed in 0:00:00.228886

 40%|████      | 1717/4292 [08:09<11:18,  3.80it/s]

MI_3828_2017 completed in 0:00:00.275364

 40%|████      | 1718/4292 [08:09<11:27,  3.75it/s]

MI_4254_2017 completed in 0:00:00.273651

 40%|████      | 1719/4292 [08:10<12:14,  3.50it/s]

MI_5109_2017 completed in 0:00:00.328084

 40%|████      | 1720/4292 [08:10<12:15,  3.50it/s]

MI_9324_2017 completed in 0:00:00.285548

 40%|████      | 1721/4292 [08:10<11:41,  3.67it/s]

MI_10704_2017 completed in 0:00:00.241379

 40%|████      | 1722/4292 [08:10<11:13,  3.82it/s]

MI_19578_2017 completed in 0:00:00.235534

 40%|████      | 1723/4292 [08:11<11:02,  3.88it/s]

MN_689_2017 completed in 0:00:00.246952

 40%|████      | 1724/4292 [08:12<21:32,  1.99it/s]

MN_5574_2017 completed in 0:00:01.075644

 40%|████      | 1725/4292 [08:12<17:53,  2.39it/s]

MN_12647_2017 completed in 0:00:00.218089

 40%|████      | 1726/4292 [08:12<17:39,  2.42it/s]

MN_13781_2017 completed in 0:00:00.398619

 40%|████      | 1727/4292 [08:13<17:05,  2.50it/s]

MN_14232_2017 completed in 0:00:00.367663

 40%|████      | 1728/4292 [08:13<15:53,  2.69it/s]

MN_16181_2017 completed in 0:00:00.306332

 40%|████      | 1729/4292 [08:13<15:46,  2.71it/s]

MN_17267_2017 completed in 0:00:00.362210

 40%|████      | 1730/4292 [08:14<15:22,  2.78it/s]

MN_20996_2017 completed in 0:00:00.337200

 40%|████      | 1731/4292 [08:14<14:14,  3.00it/s]

MN_25177_2017 completed in 0:00:00.271155

 40%|████      | 1732/4292 [08:14<15:17,  2.79it/s]

MO_4675_2017 completed in 0:00:00.415123

 40%|████      | 1733/4292 [08:15<14:46,  2.89it/s]

MO_5860_2017 completed in 0:00:00.317352

 40%|████      | 1734/4292 [08:15<14:04,  3.03it/s]

MO_9231_2017 completed in 0:00:00.291142

 40%|████      | 1735/4292 [08:15<13:51,  3.07it/s]

MO_10000_2017 completed in 0:00:00.313566

 40%|████      | 1736/4292 [08:16<13:46,  3.09it/s]

MO_12698_2017 completed in 0:00:00.317630

 40%|████      | 1737/4292 [08:16<13:09,  3.24it/s]

MO_17833_2017 completed in 0:00:00.274947

 40%|████      | 1738/4292 [08:16<12:54,  3.30it/s]

MO_19436_2017 completed in 0:00:00.288885

 41%|████      | 1739/4292 [08:16<12:10,  3.50it/s]

MS_3841_2017 completed in 0:00:00.245264

 41%|████      | 1740/4292 [08:17<14:35,  2.92it/s]

MS_12685_2017 completed in 0:00:00.475075

 41%|████      | 1741/4292 [08:17<14:40,  2.90it/s]

MS_17647_2017 completed in 0:00:00.349197

 41%|████      | 1742/4292 [08:17<13:44,  3.09it/s]

MT_6395_2017 completed in 0:00:00.271578

 41%|████      | 1743/4292 [08:18<13:58,  3.04it/s]

MT_12692_2017 completed in 0:00:00.341195

 41%|████      | 1744/4292 [08:18<12:46,  3.33it/s]

MT_12825_2017 completed in 0:00:00.233841

 41%|████      | 1745/4292 [08:18<14:23,  2.95it/s]

MT_19603_2017 completed in 0:00:00.428129

 41%|████      | 1746/4292 [08:19<13:09,  3.22it/s]

MT_20997_2017 completed in 0:00:00.241448

 41%|████      | 1747/4292 [08:19<13:01,  3.26it/s]

NC_3046_2017 completed in 0:00:00.299308

 41%|████      | 1748/4292 [08:19<12:12,  3.47it/s]

NC_5416_2017 completed in 0:00:00.242382

 41%|████      | 1749/4292 [08:20<11:54,  3.56it/s]

NC_9837_2017 completed in 0:00:00.264070

 41%|████      | 1750/4292 [08:20<12:13,  3.46it/s]

NC_16496_2017 completed in 0:00:00.305019

 41%|████      | 1751/4292 [08:20<12:33,  3.37it/s]

NC_19876_2017 completed in 0:00:00.313003

 41%|████      | 1752/4292 [08:21<14:27,  2.93it/s]

NC_24889_2017 completed in 0:00:00.443443

 41%|████      | 1753/4292 [08:21<13:02,  3.25it/s]

ND_12301_2017 completed in 0:00:00.229012

 41%|████      | 1754/4292 [08:21<13:19,  3.18it/s]

ND_14232_2017 completed in 0:00:00.326394

 41%|████      | 1755/4292 [08:22<13:44,  3.08it/s]

ND_19790_2017 completed in 0:00:00.347301

 41%|████      | 1756/4292 [08:22<13:45,  3.07it/s]

ND_24949_2017 completed in 0:00:00.323211

 41%|████      | 1757/4292 [08:22<15:25,  2.74it/s]

NE_4373_2017 completed in 0:00:00.456343

 41%|████      | 1758/4292 [08:23<14:05,  3.00it/s]

NE_4911_2017 completed in 0:00:00.259697

 41%|████      | 1759/4292 [08:23<15:18,  2.76it/s]

NE_6779_2017 completed in 0:00:00.428977

 41%|████      | 1760/4292 [08:23<13:47,  3.06it/s]

NE_11018_2017 completed in 0:00:00.242009

 41%|████      | 1761/4292 [08:24<17:01,  2.48it/s]

NE_11251_2017 completed in 0:00:00.582030

 41%|████      | 1762/4292 [08:24<15:37,  2.70it/s]

NE_12539_2017 completed in 0:00:00.293189

 41%|████      | 1763/4292 [08:24<13:38,  3.09it/s]

NE_13337_2017 completed in 0:00:00.213105

 41%|████      | 1765/4292 [08:25<11:28,  3.67it/s]

NE_13664_2017 completed in 0:00:00.272609
NE_14127_2017 completed in 0:00:00.187724

 41%|████      | 1766/4292 [08:25<12:09,  3.46it/s]

NE_17642_2017 completed in 0:00:00.326031

 41%|████      | 1767/4292 [08:25<11:56,  3.52it/s]

NH_13441_2017 completed in 0:00:00.271402

 41%|████      | 1768/4292 [08:26<13:00,  3.23it/s]

NH_15472_2017 completed in 0:00:00.368010

 41%|████      | 1769/4292 [08:26<12:07,  3.47it/s]

NH_24590_2017 completed in 0:00:00.238298

 41%|████      | 1770/4292 [08:26<11:27,  3.67it/s]

NJ_963_2017 completed in 0:00:00.235375

 41%|████▏     | 1771/4292 [08:27<13:47,  3.05it/s]

NJ_9726_2017 completed in 0:00:00.456444

 41%|████▏     | 1772/4292 [08:27<12:27,  3.37it/s]

NJ_15477_2017 completed in 0:00:00.222322

 41%|████▏     | 1773/4292 [08:27<12:43,  3.30it/s]

NJ_16213_2017 completed in 0:00:00.317111

 41%|████▏     | 1775/4292 [08:28<11:52,  3.53it/s]

NM_3287_2017 completed in 0:00:00.372754
NM_5701_2017 completed in 0:00:00.186862

 41%|████▏     | 1776/4292 [08:28<11:06,  3.77it/s]

NM_6204_2017 completed in 0:00:00.221238

 41%|████▏     | 1777/4292 [08:28<11:11,  3.75it/s]

NM_11204_2017 completed in 0:00:00.270840

 41%|████▏     | 1778/4292 [08:29<12:40,  3.31it/s]

NM_15473_2017 completed in 0:00:00.384752

 41%|████▏     | 1780/4292 [08:29<10:51,  3.86it/s]

NM_17718_2017 completed in 0:00:00.290369
NV_2008_2017 completed in 0:00:00.164700

 41%|████▏     | 1781/4292 [08:29<12:07,  3.45it/s]

NV_13073_2017 completed in 0:00:00.360447

 42%|████▏     | 1782/4292 [08:30<11:23,  3.67it/s]

NV_13407_2017 completed in 0:00:00.230444

 42%|████▏     | 1783/4292 [08:30<14:16,  2.93it/s]

NV_17166_2017 completed in 0:00:00.501787

 42%|████▏     | 1784/4292 [08:30<13:16,  3.15it/s]

NV_19840_2017 completed in 0:00:00.260408

 42%|████▏     | 1786/4292 [08:31<11:04,  3.77it/s]

NY_3249_2017 completed in 0:00:00.247132
NY_4226_2017 completed in 0:00:00.190697

 42%|████▏     | 1787/4292 [08:31<11:39,  3.58it/s]

NY_11171_2017 completed in 0:00:00.311615

 42%|████▏     | 1788/4292 [08:32<12:18,  3.39it/s]

NY_13511_2017 completed in 0:00:00.330505

 42%|████▏     | 1789/4292 [08:32<18:08,  2.30it/s]

NY_13573_2017 completed in 0:00:00.759613
NY_14154_2017 completed in 0:00:00.198708

 42%|████▏     | 1791/4292 [08:33<14:38,  2.85it/s]

NY_16183_2017 completed in 0:00:00.318835

 42%|████▏     | 1793/4292 [08:33<11:49,  3.52it/s]

OH_3542_2017 completed in 0:00:00.244268
OH_3755_2017 completed in 0:00:00.198480

 42%|████▏     | 1794/4292 [08:34<12:35,  3.31it/s]

OH_4922_2017 completed in 0:00:00.344652

 42%|████▏     | 1795/4292 [08:34<13:00,  3.20it/s]

OH_13998_2017 completed in 0:00:00.332459

 42%|████▏     | 1796/4292 [08:34<13:26,  3.10it/s]

OH_14006_2017 completed in 0:00:00.346318

 42%|████▏     | 1797/4292 [08:35<13:03,  3.18it/s]

OH_18997_2017 completed in 0:00:00.292537

 42%|████▏     | 1798/4292 [08:35<12:25,  3.35it/s]

OK_5860_2017 completed in 0:00:00.262232

 42%|████▏     | 1799/4292 [08:35<11:39,  3.56it/s]

OK_13734_2017 completed in 0:00:00.236849

 42%|████▏     | 1800/4292 [08:35<11:42,  3.55it/s]

OK_14062_2017 completed in 0:00:00.283778

 42%|████▏     | 1801/4292 [08:36<13:05,  3.17it/s]

OK_14063_2017 completed in 0:00:00.392530

 42%|████▏     | 1802/4292 [08:36<14:44,  2.82it/s]

OK_15474_2017 completed in 0:00:00.447320
OK_19785_2017 completed in 0:00:00.202920

 42%|████▏     | 1804/4292 [08:37<11:19,  3.66it/s]

OR_6022_2017 completed in 0:00:00.186580

 42%|████▏     | 1805/4292 [08:37<11:30,  3.60it/s]

OR_9191_2017 completed in 0:00:00.287180

 42%|████▏     | 1806/4292 [08:37<11:59,  3.46it/s]

OR_14354_2017 completed in 0:00:00.315833

 42%|████▏     | 1807/4292 [08:37<11:19,  3.66it/s]

OR_15248_2017 completed in 0:00:00.235350

 42%|████▏     | 1808/4292 [09:37<12:25:37, 18.01s/it]

OR_18260_2017 completed in 0:00:59.395957

 42%|████▏     | 1809/4292 [09:37<8:46:32, 12.72s/it]

OR_28541_2017 completed in 0:00:00.386355

 42%|████▏     | 1810/4292 [09:38<6:12:24,  9.00s/it]

OR_40437_2017 completed in 0:00:00.317279

 42%|████▏     | 1811/4292 [09:38<4:24:29,  6.40s/it]

PA_3597_2017 completed in 0:00:00.313967

 42%|████▏     | 1812/4292 [09:38<3:08:19,  4.56s/it]

PA_5487_2017 completed in 0:00:00.261491

 42%|████▏     | 1813/4292 [09:38<2:15:33,  3.28s/it]

PA_12390_2017 completed in 0:00:00.305327

 42%|████▏     | 1814/4292 [09:39<1:38:43,  2.39s/it]

PA_14711_2017 completed in 0:00:00.310883

 42%|████▏     | 1815/4292 [09:39<1:12:32,  1.76s/it]

PA_14715_2017 completed in 0:00:00.279465

 42%|████▏     | 1816/4292 [09:39<53:26,  1.29s/it]

PA_14716_2017 completed in 0:00:00.215026
PA_14940_2017 completed in 0:00:00.202130

 42%|████▏     | 1818/4292 [09:40<32:27,  1.27it/s]

PA_15045_2017 completed in 0:00:00.365068

 42%|████▏     | 1819/4292 [09:40<27:26,  1.50it/s]

PA_19390_2017 completed in 0:00:00.381364

 42%|████▏     | 1820/4292 [09:40<22:01,  1.87it/s]

PA_20334_2017 completed in 0:00:00.228683

 42%|████▏     | 1821/4292 [09:41<19:57,  2.06it/s]

PA_20387_2017 completed in 0:00:00.367342

 42%|████▏     | 1822/4292 [09:41<17:33,  2.34it/s]

RI_1857_2017 completed in 0:00:00.290205

 42%|████▏     | 1823/4292 [09:41<16:46,  2.45it/s]

RI_13214_2017 completed in 0:00:00.362814

 42%|████▏     | 1824/4292 [09:42<15:40,  2.62it/s]

SC_1613_2017 completed in 0:00:00.318261

 43%|████▎     | 1825/4292 [09:42<13:54,  2.96it/s]

SC_3046_2017 completed in 0:00:00.237795

 43%|████▎     | 1826/4292 [09:42<12:27,  3.30it/s]

SC_5416_2017 completed in 0:00:00.220173

 43%|████▎     | 1827/4292 [09:42<11:35,  3.54it/s]

SC_14398_2017 completed in 0:00:00.232512

 43%|████▎     | 1828/4292 [09:43<11:14,  3.65it/s]

SC_17539_2017 completed in 0:00:00.253570

 43%|████▎     | 1829/4292 [09:43<11:37,  3.53it/s]

SC_17543_2017 completed in 0:00:00.303814
SD_1769_2017 completed in 0:00:00.201064

 43%|████▎     | 1831/4292 [09:44<11:54,  3.44it/s]

SD_14232_2017 completed in 0:00:00.363226

 43%|████▎     | 1832/4292 [09:44<11:49,  3.47it/s]

SD_17267_2017 completed in 0:00:00.282920

 43%|████▎     | 1833/4292 [09:44<11:53,  3.44it/s]

SD_19293_2017 completed in 0:00:00.293708

 43%|████▎     | 1834/4292 [09:44<11:04,  3.70it/s]

SD_20401_2017 completed in 0:00:00.222803
TN_10331_2017 completed in 0:00:00.203545

 43%|████▎     | 1836/4292 [09:45<10:15,  3.99it/s]

TX_5701_2017 completed in 0:00:00.249509

 43%|████▎     | 1837/4292 [09:45<10:08,  4.04it/s]

TX_16604_2017 completed in 0:00:00.240190

 43%|████▎     | 1838/4292 [09:45<10:24,  3.93it/s]

TX_17698_2017 completed in 0:00:00.269555

 43%|████▎     | 1839/4292 [09:46<10:41,  3.82it/s]

TX_55937_2017 completed in 0:00:00.276460

 43%|████▎     | 1840/4292 [09:46<09:59,  4.09it/s]

UT_2010_2017 completed in 0:00:00.203487

 43%|████▎     | 1841/4292 [09:46<10:40,  3.83it/s]

UT_11135_2017 completed in 0:00:00.296309

 43%|████▎     | 1842/4292 [09:46<10:37,  3.84it/s]

UT_12866_2017 completed in 0:00:00.256752

 43%|████▎     | 1843/4292 [09:47<11:05,  3.68it/s]

UT_14354_2017 completed in 0:00:00.297064

 43%|████▎     | 1844/4292 [09:47<10:50,  3.76it/s]

UT_15444_2017 completed in 0:00:00.250381

 43%|████▎     | 1845/4292 [09:47<10:29,  3.89it/s]

UT_17845_2017 completed in 0:00:00.236739

 43%|████▎     | 1847/4292 [09:48<09:28,  4.30it/s]

UT_17874_2017 completed in 0:00:00.275436
UT_18206_2017 completed in 0:00:00.159901

 43%|████▎     | 1848/4292 [09:48<09:03,  4.50it/s]

VA_84_2017 completed in 0:00:00.196400

 43%|████▎     | 1849/4292 [09:48<10:43,  3.80it/s]

VA_733_2017 completed in 0:00:00.357858

 43%|████▎     | 1850/4292 [09:48<10:30,  3.88it/s]

VA_10171_2017 completed in 0:00:00.244948

 43%|████▎     | 1851/4292 [09:49<10:55,  3.72it/s]

VA_17066_2017 completed in 0:00:00.292122

 43%|████▎     | 1853/4292 [09:49<12:16,  3.31it/s]

VA_19876_2017 completed in 0:00:00.544200
VA_19882_2017 completed in 0:00:00.184985

 43%|████▎     | 1854/4292 [09:50<11:28,  3.54it/s]

VA_40228_2017 completed in 0:00:00.236890

 43%|████▎     | 1855/4292 [09:50<12:10,  3.33it/s]

VT_2548_2017 completed in 0:00:00.339534

 43%|████▎     | 1856/4292 [09:50<11:52,  3.42it/s]

VT_7601_2017 completed in 0:00:00.274909

 43%|████▎     | 1857/4292 [09:51<14:23,  2.82it/s]

VT_19791_2017 completed in 0:00:00.498302

 43%|████▎     | 1858/4292 [09:51<12:39,  3.21it/s]

WA_3660_2017 completed in 0:00:00.211067
WA_14354_2017 completed in 0:00:00.199669

 43%|████▎     | 1861/4292 [09:52<09:17,  4.36it/s]

WA_15500_2017 completed in 0:00:00.204861
WA_16868_2017 completed in 0:00:00.164605

 43%|████▎     | 1863/4292 [09:52<08:47,  4.61it/s]

WA_17470_2017 completed in 0:00:00.288135
WA_18429_2017 completed in 0:00:00.146078

 43%|████▎     | 1864/4292 [09:52<09:18,  4.35it/s]

WA_20169_2017 completed in 0:00:00.258962

 43%|████▎     | 1865/4292 [09:53<15:26,  2.62it/s]

WI_4715_2017 completed in 0:00:00.734780

 43%|████▎     | 1866/4292 [09:53<14:38,  2.76it/s]

WI_5574_2017 completed in 0:00:00.315238

 43%|████▎     | 1867/4292 [09:54<13:13,  3.06it/s]

WI_11479_2017 completed in 0:00:00.245445

 44%|████▎     | 1868/4292 [09:55<21:21,  1.89it/s]

WI_13697_2017 completed in 0:00:00.997619

 44%|████▎     | 1870/4292 [09:55<14:51,  2.72it/s]

WI_13815_2017 completed in 0:00:00.253705
WI_20847_2017 completed in 0:00:00.184074

 44%|████▎     | 1871/4292 [09:56<21:04,  1.91it/s]

WI_20856_2017 completed in 0:00:00.881296

 44%|████▎     | 1872/4292 [09:56<20:18,  1.99it/s]

WI_20860_2017 completed in 0:00:00.459013

 44%|████▎     | 1873/4292 [09:57<21:36,  1.87it/s]

WV_733_2017 completed in 0:00:00.610608

 44%|████▎     | 1874/4292 [09:57<20:39,  1.95it/s]

WV_12796_2017 completed in 0:00:00.457438

 44%|████▎     | 1875/4292 [09:58<17:08,  2.35it/s]

WV_15263_2017 completed in 0:00:00.220558

 44%|████▎     | 1876/4292 [09:58<16:24,  2.45it/s]

WV_20521_2017 completed in 0:00:00.364861

 44%|████▎     | 1877/4292 [09:58<14:08,  2.85it/s]

WY_3461_2017 completed in 0:00:00.219236

 44%|████▍     | 1878/4292 [09:59<13:32,  2.97it/s]

WY_7222_2017 completed in 0:00:00.299830

 44%|████▍     | 1880/4292 [09:59<11:20,  3.55it/s]

WY_8566_2017 completed in 0:00:00.273244
WY_11273_2017 completed in 0:00:00.197506

 44%|████▍     | 1881/4292 [09:59<11:39,  3.45it/s]

WY_14354_2017 completed in 0:00:00.308244

 44%|████▍     | 1883/4292 [10:00<10:10,  3.95it/s]

WY_19156_2017 completed in 0:00:00.286208
WY_27058_2017 completed in 0:00:00.165690

 44%|████▍     | 1884/4292 [10:00<14:11,  2.83it/s]

ME_5609_2017 completed in 0:00:00.585579

 44%|████▍     | 1885/4292 [10:01<12:22,  3.24it/s]

MS_12686_2017 completed in 0:00:00.202157

 44%|████▍     | 1886/4292 [10:01<11:27,  3.50it/s]

NE_40606_2017 completed in 0:00:00.230503

 44%|████▍     | 1887/4292 [10:01<12:15,  3.27it/s]

RI_14537_2017 completed in 0:00:00.351905

 44%|████▍     | 1888/4292 [10:01<11:51,  3.38it/s]

AK_219_2018 completed in 0:00:00.272147

 44%|████▍     | 1889/4292 [10:02<12:56,  3.10it/s]

AK_599_2018 completed in 0:00:00.385218

 44%|████▍     | 1890/4292 [10:02<12:12,  3.28it/s]

AK_3522_2018 completed in 0:00:00.261078

 44%|████▍     | 1891/4292 [10:02<11:37,  3.44it/s]

AK_7353_2018 completed in 0:00:00.256451

 44%|████▍     | 1892/4292 [10:03<11:06,  3.60it/s]

AK_11824_2018 completed in 0:00:00.246872

 44%|████▍     | 1893/4292 [10:03<10:28,  3.82it/s]

AK_19558_2018 completed in 0:00:00.224639

 44%|████▍     | 1895/4292 [10:03<09:40,  4.13it/s]

AR_814_2018 completed in 0:00:00.300120
AR_817_2018 completed in 0:00:00.166958

 44%|████▍     | 1896/4292 [10:04<09:41,  4.12it/s]

AR_3093_2018 completed in 0:00:00.244042

 44%|████▍     | 1897/4292 [10:04<09:46,  4.08it/s]

AR_5860_2018 completed in 0:00:00.248991

 44%|████▍     | 1898/4292 [10:04<09:52,  4.04it/s]

AR_6342_2018 completed in 0:00:00.252717

 44%|████▍     | 1899/4292 [10:04<09:29,  4.20it/s]

AR_13718_2018 completed in 0:00:00.214680
AR_14063_2018 completed in 0:00:00.202986

 44%|████▍     | 1901/4292 [10:05<09:28,  4.21it/s]

AR_17698_2018 completed in 0:00:00.259014

 44%|████▍     | 1902/4292 [10:06<24:51,  1.60it/s]

AZ_176_2018 completed in 0:00:01.524124

 44%|████▍     | 1903/4292 [10:07<20:32,  1.94it/s]

AZ_803_2018 completed in 0:00:00.262787

 44%|████▍     | 1904/4292 [10:07<17:15,  2.31it/s]

AZ_12919_2018 completed in 0:00:00.240859
AZ_16572_2018 completed in 0:00:00.201334

 44%|████▍     | 1906/4292 [10:07<12:25,  3.20it/s]

AZ_19189_2018 completed in 0:00:00.190539

 44%|████▍     | 1908/4292 [10:08<11:16,  3.52it/s]

AZ_19728_2018 completed in 0:00:00.365590
AZ_21538_2018 completed in 0:00:00.178333

 44%|████▍     | 1909/4292 [10:08<13:20,  2.98it/s]

AZ_24211_2018 completed in 0:00:00.456362

 45%|████▍     | 1910/4292 [10:08<13:21,  2.97it/s]

CA_9216_2018 completed in 0:00:00.337278

 45%|████▍     | 1911/4292 [10:09<12:32,  3.16it/s]

CA_11208_2018 completed in 0:00:00.267015

 45%|████▍     | 1912/4292 [10:09<11:27,  3.46it/s]

CA_12745_2018 completed in 0:00:00.224164

 45%|████▍     | 1913/4292 [10:10<15:49,  2.51it/s]

CA_14328_2018 completed in 0:00:00.655855

 45%|████▍     | 1914/4292 [10:10<15:41,  2.53it/s]

CA_14354_2018 completed in 0:00:00.387282

 45%|████▍     | 1915/4292 [10:10<13:31,  2.93it/s]

CA_14534_2018 completed in 0:00:00.213514

 45%|████▍     | 1916/4292 [10:11<12:43,  3.11it/s]

CA_16534_2018 completed in 0:00:00.272475

 45%|████▍     | 1917/4292 [10:11<13:25,  2.95it/s]

CA_16609_2018 completed in 0:00:00.379281

 45%|████▍     | 1918/4292 [10:11<12:13,  3.24it/s]

CA_16655_2018 completed in 0:00:00.238017

 45%|████▍     | 1919/4292 [10:12<13:09,  3.00it/s]

CA_17609_2018 completed in 0:00:00.387079

 45%|████▍     | 1920/4292 [10:12<12:20,  3.21it/s]

CA_17612_2018 completed in 0:00:00.262109

 45%|████▍     | 1922/4292 [10:12<10:41,  3.70it/s]

CA_19281_2018 completed in 0:00:00.299987
CO_3989_2018 completed in 0:00:00.180450

 45%|████▍     | 1923/4292 [10:14<23:16,  1.70it/s]

CO_6604_2018 completed in 0:00:01.332400

 45%|████▍     | 1924/4292 [10:14<19:36,  2.01it/s]

CO_9336_2018 completed in 0:00:00.279996

 45%|████▍     | 1925/4292 [10:14<16:21,  2.41it/s]

CO_12866_2018 completed in 0:00:00.221396

 45%|████▍     | 1926/4292 [10:14<14:54,  2.65it/s]

CO_15257_2018 completed in 0:00:00.292104

 45%|████▍     | 1927/4292 [10:15<13:08,  3.00it/s]

CO_15466_2018 completed in 0:00:00.228370

 45%|████▍     | 1928/4292 [10:15<11:44,  3.35it/s]

CO_16603_2018 completed in 0:00:00.214937

 45%|████▍     | 1929/4292 [10:15<10:47,  3.65it/s]

CO_19499_2018 completed in 0:00:00.217202

 45%|████▍     | 1930/4292 [10:15<11:02,  3.57it/s]

CO_27058_2018 completed in 0:00:00.293250

 45%|████▍     | 1931/4292 [10:16<11:24,  3.45it/s]

CO_56146_2018 completed in 0:00:00.311716

 45%|████▌     | 1932/4292 [10:16<10:54,  3.61it/s]

CT_4176_2018 completed in 0:00:00.246758

 45%|████▌     | 1933/4292 [10:16<10:08,  3.87it/s]

CT_7716_2018 completed in 0:00:00.212429

 45%|████▌     | 1934/4292 [10:16<10:33,  3.72it/s]

CT_19497_2018 completed in 0:00:00.292665

 45%|████▌     | 1936/4292 [10:17<09:19,  4.21it/s]

CT_20038_2018 completed in 0:00:00.223558
DC_15270_2018 completed in 0:00:00.194366

 45%|████▌     | 1937/4292 [10:17<08:41,  4.52it/s]

DE_5027_2018 completed in 0:00:00.182821

 45%|████▌     | 1938/4292 [10:17<09:33,  4.11it/s]

DE_5070_2018 completed in 0:00:00.294469

 45%|████▌     | 1940/4292 [10:18<09:07,  4.30it/s]

DE_5335_2018 completed in 0:00:00.277270
DE_13519_2018 completed in 0:00:00.182002

 45%|████▌     | 1941/4292 [10:18<11:50,  3.31it/s]

FL_6452_2018 completed in 0:00:00.463386

 45%|████▌     | 1942/4292 [10:19<11:37,  3.37it/s]

FL_6455_2018 completed in 0:00:00.283698

 45%|████▌     | 1943/4292 [10:19<10:54,  3.59it/s]

FL_6457_2018 completed in 0:00:00.235236

 45%|████▌     | 1944/4292 [10:19<11:05,  3.53it/s]

FL_7801_2018 completed in 0:00:00.293884

 45%|████▌     | 1945/4292 [10:19<10:57,  3.57it/s]

FL_9617_2018 completed in 0:00:00.271340

 45%|████▌     | 1946/4292 [10:20<10:08,  3.86it/s]

FL_18454_2018 completed in 0:00:00.209799

 45%|████▌     | 1948/4292 [10:20<09:21,  4.18it/s]

GA_3916_2018 completed in 0:00:00.288877
GA_9601_2018 completed in 0:00:00.170705

 45%|████▌     | 1949/4292 [10:20<08:14,  4.74it/s]

HI_8287_2018 completed in 0:00:00.143471

 45%|████▌     | 1951/4292 [10:21<08:14,  4.73it/s]

HI_10071_2018 completed in 0:00:00.250479
HI_11843_2018 completed in 0:00:00.183032

 45%|████▌     | 1952/4292 [10:21<08:10,  4.77it/s]

HI_19547_2018 completed in 0:00:00.205081

 46%|████▌     | 1953/4292 [10:21<08:40,  4.49it/s]

IA_9417_2018 completed in 0:00:00.251388

 46%|████▌     | 1954/4292 [10:21<09:00,  4.32it/s]

IA_12341_2018 completed in 0:00:00.251109

 46%|████▌     | 1955/4292 [10:22<08:57,  4.35it/s]

ID_9187_2018 completed in 0:00:00.224942

 46%|████▌     | 1957/4292 [10:22<09:05,  4.28it/s]

ID_9191_2018 completed in 0:00:00.308357
ID_10454_2018 completed in 0:00:00.185373

 46%|████▌     | 1958/4292 [10:22<08:49,  4.41it/s]

ID_11273_2018 completed in 0:00:00.209746

 46%|████▌     | 1959/4292 [10:23<09:25,  4.12it/s]

ID_14354_2018 completed in 0:00:00.277924

 46%|████▌     | 1960/4292 [10:23<11:46,  3.30it/s]

ID_20169_2018 completed in 0:00:00.443350

 46%|████▌     | 1961/4292 [10:23<10:52,  3.57it/s]

IL_4110_2018 completed in 0:00:00.224667

 46%|████▌     | 1963/4292 [10:24<12:44,  3.05it/s]

IL_12341_2018 completed in 0:00:00.638531
IL_13032_2018 completed in 0:00:00.185085

 46%|████▌     | 1964/4292 [10:24<13:10,  2.94it/s]

IL_56697_2018 completed in 0:00:00.364091

 46%|████▌     | 1965/4292 [10:25<12:03,  3.22it/s]

IN_9273_2018 completed in 0:00:00.242790

 46%|████▌     | 1966/4292 [10:25<10:57,  3.54it/s]

IN_9324_2018 completed in 0:00:00.215216
IN_13756_2018 completed in 0:00:00.198596

 46%|████▌     | 1968/4292 [10:25<10:18,  3.76it/s]

IN_15470_2018 completed in 0:00:00.283547

 46%|████▌     | 1969/4292 [10:26<10:36,  3.65it/s]

IN_17633_2018 completed in 0:00:00.290450

 46%|████▌     | 1970/4292 [10:26<10:01,  3.86it/s]

KS_5860_2018 completed in 0:00:00.223348

 46%|████▌     | 1972/4292 [10:26<09:38,  4.01it/s]

KS_9996_2018 completed in 0:00:00.296346
KS_10000_2018 completed in 0:00:00.199527

 46%|████▌     | 1973/4292 [10:27<08:55,  4.33it/s]

KS_10005_2018 completed in 0:00:00.186785

 46%|████▌     | 1974/4292 [10:27<08:45,  4.41it/s]

KS_22500_2018 completed in 0:00:00.215671

 46%|████▌     | 1975/4292 [10:27<10:27,  3.69it/s]

KY_9964_2018 completed in 0:00:00.371535

 46%|████▌     | 1976/4292 [10:28<13:34,  2.84it/s]

KY_10171_2018 completed in 0:00:00.539448

 46%|████▌     | 1977/4292 [10:28<13:18,  2.90it/s]

KY_11249_2018 completed in 0:00:00.328707

 46%|████▌     | 1978/4292 [10:28<12:06,  3.19it/s]

KY_17564_2018 completed in 0:00:00.239938

 46%|████▌     | 1980/4292 [10:29<11:48,  3.26it/s]

KY_19446_2018 completed in 0:00:00.450651
KY_22053_2018 completed in 0:00:00.191715

 46%|████▌     | 1981/4292 [10:30<15:38,  2.46it/s]

KY_49998_2018 completed in 0:00:00.638704

 46%|████▌     | 1982/4292 [10:30<14:40,  2.62it/s]

LA_3265_2018 completed in 0:00:00.321441

 46%|████▌     | 1984/4292 [10:30<11:10,  3.44it/s]

LA_11241_2018 completed in 0:00:00.225486
LA_13478_2018 completed in 0:00:00.186725

 46%|████▋     | 1986/4292 [10:31<08:52,  4.33it/s]

LA_17698_2018 completed in 0:00:00.177057
MA_6374_2018 completed in 0:00:00.169306

 46%|████▋     | 1987/4292 [10:31<08:39,  4.43it/s]

MA_8774_2018 completed in 0:00:00.212517

 46%|████▋     | 1988/4292 [10:31<08:57,  4.28it/s]

MA_11804_2018 completed in 0:00:00.250816

 46%|████▋     | 1989/4292 [10:31<09:09,  4.19it/s]

MA_13206_2018 completed in 0:00:00.249295

 46%|████▋     | 1990/4292 [10:32<09:13,  4.16it/s]

MA_15748_2018 completed in 0:00:00.241665

 46%|████▋     | 1991/4292 [10:32<09:24,  4.08it/s]

MA_54913_2018 completed in 0:00:00.255810

 46%|████▋     | 1992/4292 [10:32<12:37,  3.04it/s]

MD_1167_2018 completed in 0:00:00.523907

 46%|████▋     | 1993/4292 [10:33<12:02,  3.18it/s]

MD_5027_2018 completed in 0:00:00.278377

 46%|████▋     | 1995/4292 [10:33<09:40,  3.96it/s]

MD_15263_2018 completed in 0:00:00.218839
MD_15270_2018 completed in 0:00:00.174372

 47%|████▋     | 1996/4292 [10:33<09:52,  3.87it/s]

MD_17637_2018 completed in 0:00:00.269766

 47%|████▋     | 1997/4292 [10:34<09:27,  4.05it/s]

ME_1179_2018 completed in 0:00:00.220815
ME_3266_2018 completed in 0:00:00.204065

 47%|████▋     | 2000/4292 [10:34<08:12,  4.66it/s]

ME_5609_2018 completed in 0:00:00.198063
MI_392_2018 completed in 0:00:00.192568

 47%|████▋     | 2001/4292 [10:34<09:05,  4.20it/s]

MI_3828_2018 completed in 0:00:00.291654

 47%|████▋     | 2002/4292 [10:35<09:33,  3.99it/s]

MI_4254_2018 completed in 0:00:00.278358

 47%|████▋     | 2003/4292 [10:35<10:15,  3.72it/s]

MI_5109_2018 completed in 0:00:00.310485

 47%|████▋     | 2004/4292 [10:35<09:55,  3.84it/s]

MI_9324_2018 completed in 0:00:00.239513

 47%|████▋     | 2005/4292 [10:35<09:40,  3.94it/s]

MI_10704_2018 completed in 0:00:00.238242

 47%|████▋     | 2007/4292 [10:36<08:59,  4.24it/s]

MI_19578_2018 completed in 0:00:00.244412
MN_689_2018 completed in 0:00:00.199134

 47%|████▋     | 2008/4292 [10:36<08:31,  4.46it/s]

MN_5574_2018 completed in 0:00:00.195008

 47%|████▋     | 2009/4292 [10:36<08:27,  4.50it/s]

MN_10596_2018 completed in 0:00:00.215797

 47%|████▋     | 2010/4292 [10:37<08:48,  4.32it/s]

MN_12647_2018 completed in 0:00:00.252210

 47%|████▋     | 2011/4292 [10:37<09:06,  4.18it/s]

MN_13781_2018 completed in 0:00:00.256722

 47%|████▋     | 2012/4292 [10:37<09:08,  4.15it/s]

MN_14232_2018 completed in 0:00:00.242275

 47%|████▋     | 2013/4292 [10:37<10:06,  3.76it/s]

MN_16181_2018 completed in 0:00:00.324450

 47%|████▋     | 2014/4292 [10:38<16:31,  2.30it/s]

MN_17267_2018 completed in 0:00:00.828146

 47%|████▋     | 2015/4292 [10:39<16:01,  2.37it/s]

MN_20996_2018 completed in 0:00:00.390199

 47%|████▋     | 2017/4292 [10:39<12:11,  3.11it/s]

MN_25177_2018 completed in 0:00:00.267534
MO_4675_2018 completed in 0:00:00.193398

 47%|████▋     | 2018/4292 [10:39<12:20,  3.07it/s]

MO_5860_2018 completed in 0:00:00.334270
MO_9231_2018 completed in 0:00:00.201949

 47%|████▋     | 2020/4292 [10:40<12:21,  3.07it/s]

MO_10000_2018 completed in 0:00:00.412675

 47%|████▋     | 2021/4292 [10:40<11:02,  3.43it/s]

MO_12698_2018 completed in 0:00:00.209636

 47%|████▋     | 2022/4292 [10:40<10:25,  3.63it/s]

MO_17833_2018 completed in 0:00:00.237577

 47%|████▋     | 2023/4292 [10:41<11:05,  3.41it/s]

MO_19436_2018 completed in 0:00:00.332841

 47%|████▋     | 2024/4292 [10:41<10:41,  3.53it/s]

MS_3841_2018 completed in 0:00:00.258253

 47%|████▋     | 2025/4292 [10:41<10:53,  3.47it/s]

MS_12685_2018 completed in 0:00:00.298947
MS_12686_2018 completed in 0:00:00.200883

 47%|████▋     | 2027/4292 [10:42<11:56,  3.16it/s]

MS_17647_2018 completed in 0:00:00.439988

 47%|████▋     | 2028/4292 [10:42<11:11,  3.37it/s]

MT_6395_2018 completed in 0:00:00.249956

 47%|████▋     | 2029/4292 [10:43<11:11,  3.37it/s]

MT_12692_2018 completed in 0:00:00.295932

 47%|████▋     | 2030/4292 [10:43<10:24,  3.62it/s]

MT_12825_2018 completed in 0:00:00.226791

 47%|████▋     | 2031/4292 [10:43<10:17,  3.66it/s]

MT_19603_2018 completed in 0:00:00.265843

 47%|████▋     | 2032/4292 [10:43<10:52,  3.46it/s]

MT_20997_2018 completed in 0:00:00.324302

 47%|████▋     | 2033/4292 [10:44<10:11,  3.69it/s]

NC_3046_2018 completed in 0:00:00.227232

 47%|████▋     | 2034/4292 [10:44<09:52,  3.81it/s]

NC_5416_2018 completed in 0:00:00.242434

 47%|████▋     | 2035/4292 [10:44<09:41,  3.88it/s]

NC_9837_2018 completed in 0:00:00.244934

 47%|████▋     | 2037/4292 [10:45<09:01,  4.17it/s]

NC_16496_2018 completed in 0:00:00.285185
NC_19876_2018 completed in 0:00:00.178716

 47%|████▋     | 2038/4292 [10:45<09:45,  3.85it/s]

NC_24889_2018 completed in 0:00:00.305000

 48%|████▊     | 2039/4292 [10:45<09:28,  3.96it/s]

ND_12301_2018 completed in 0:00:00.233939

 48%|████▊     | 2040/4292 [10:45<09:45,  3.84it/s]

ND_14232_2018 completed in 0:00:00.277657

 48%|████▊     | 2041/4292 [10:46<09:13,  4.06it/s]

ND_19790_2018 completed in 0:00:00.211398

 48%|████▊     | 2042/4292 [10:46<09:05,  4.12it/s]

ND_24949_2018 completed in 0:00:00.232937

 48%|████▊     | 2044/4292 [10:46<08:30,  4.40it/s]

NE_4373_2018 completed in 0:00:00.239985
NE_4911_2018 completed in 0:00:00.192139

 48%|████▊     | 2045/4292 [10:47<09:11,  4.07it/s]

NE_6779_2018 completed in 0:00:00.286815

 48%|████▊     | 2046/4292 [10:47<09:06,  4.11it/s]

NE_11018_2018 completed in 0:00:00.236848
NE_11251_2018 completed in 0:00:00.200790

 48%|████▊     | 2049/4292 [10:47<07:41,  4.86it/s]

NE_12539_2018 completed in 0:00:00.178413
NE_13337_2018 completed in 0:00:00.182319

 48%|████▊     | 2051/4292 [10:48<07:31,  4.96it/s]

NE_13664_2018 completed in 0:00:00.194473
NE_14127_2018 completed in 0:00:00.197752

 48%|████▊     | 2052/4292 [10:48<07:50,  4.76it/s]

NE_17642_2018 completed in 0:00:00.229562

 48%|████▊     | 2054/4292 [10:49<09:03,  4.12it/s]

NE_40606_2018 completed in 0:00:00.390182
NH_13441_2018 completed in 0:00:00.191229

 48%|████▊     | 2055/4292 [10:49<08:42,  4.28it/s]

NH_15472_2018 completed in 0:00:00.211105

 48%|████▊     | 2056/4292 [10:49<09:00,  4.14it/s]

NH_24590_2018 completed in 0:00:00.254926

 48%|████▊     | 2057/4292 [10:49<09:49,  3.79it/s]

NJ_963_2018 completed in 0:00:00.313603

 48%|████▊     | 2058/4292 [10:50<09:16,  4.01it/s]

NJ_9726_2018 completed in 0:00:00.214163

 48%|████▊     | 2059/4292 [10:50<08:59,  4.14it/s]

NJ_15477_2018 completed in 0:00:00.223039

 48%|████▊     | 2060/4292 [10:50<08:32,  4.35it/s]

NJ_16213_2018 completed in 0:00:00.200371

 48%|████▊     | 2061/4292 [10:50<08:52,  4.19it/s]

NM_3287_2018 completed in 0:00:00.258539

 48%|████▊     | 2062/4292 [10:50<08:42,  4.27it/s]

NM_5701_2018 completed in 0:00:00.223378

 48%|████▊     | 2063/4292 [10:51<09:47,  3.80it/s]

NM_6204_2018 completed in 0:00:00.330180

 48%|████▊     | 2064/4292 [10:51<10:17,  3.61it/s]

NM_11204_2018 completed in 0:00:00.306614

 48%|████▊     | 2065/4292 [10:51<10:48,  3.44it/s]

NM_15473_2018 completed in 0:00:00.322290

 48%|████▊     | 2066/4292 [10:52<09:52,  3.76it/s]

NM_17718_2018 completed in 0:00:00.207151

 48%|████▊     | 2067/4292 [10:52<09:57,  3.73it/s]

NV_2008_2018 completed in 0:00:00.271545

 48%|████▊     | 2069/4292 [10:52<08:56,  4.14it/s]

NV_13073_2018 completed in 0:00:00.278777
NV_13407_2018 completed in 0:00:00.169239

 48%|████▊     | 2070/4292 [10:53<09:35,  3.86it/s]

NV_17166_2018 completed in 0:00:00.299284

 48%|████▊     | 2071/4292 [10:53<09:27,  3.91it/s]

NV_19840_2018 completed in 0:00:00.246414

 48%|████▊     | 2072/4292 [10:53<10:58,  3.37it/s]

NY_3249_2018 completed in 0:00:00.391932

 48%|████▊     | 2073/4292 [10:54<10:29,  3.52it/s]

NY_4226_2018 completed in 0:00:00.252774

 48%|████▊     | 2074/4292 [10:54<09:56,  3.72it/s]

NY_11171_2018 completed in 0:00:00.232833

 48%|████▊     | 2075/4292 [10:54<10:25,  3.54it/s]

NY_13511_2018 completed in 0:00:00.310746

 48%|████▊     | 2076/4292 [10:54<10:16,  3.60it/s]

NY_13573_2018 completed in 0:00:00.267897

 48%|████▊     | 2077/4292 [10:55<09:37,  3.84it/s]

NY_14154_2018 completed in 0:00:00.219147

 48%|████▊     | 2078/4292 [10:55<09:06,  4.05it/s]

NY_16183_2018 completed in 0:00:00.214131

 48%|████▊     | 2079/4292 [10:55<09:19,  3.96it/s]

OH_3542_2018 completed in 0:00:00.264054

 48%|████▊     | 2080/4292 [10:55<09:17,  3.97it/s]

OH_3755_2018 completed in 0:00:00.249832

 48%|████▊     | 2081/4292 [10:56<09:39,  3.81it/s]

OH_4922_2018 completed in 0:00:00.284594
OH_13998_2018 completed in 0:00:00.202802

 49%|████▊     | 2083/4292 [10:56<09:49,  3.75it/s]

OH_14006_2018 completed in 0:00:00.318048

 49%|████▊     | 2084/4292 [10:57<10:40,  3.45it/s]

OH_18997_2018 completed in 0:00:00.342854

 49%|████▊     | 2085/4292 [10:57<10:05,  3.64it/s]

OK_5860_2018 completed in 0:00:00.237199

 49%|████▊     | 2086/4292 [10:57<12:19,  2.98it/s]

OK_13734_2018 completed in 0:00:00.475578

 49%|████▊     | 2087/4292 [10:57<11:04,  3.32it/s]

OK_14062_2018 completed in 0:00:00.221346

 49%|████▊     | 2088/4292 [10:58<10:15,  3.58it/s]

OK_14063_2018 completed in 0:00:00.227175

 49%|████▊     | 2089/4292 [10:58<10:59,  3.34it/s]

OK_15474_2018 completed in 0:00:00.345457

 49%|████▊     | 2090/4292 [10:58<10:49,  3.39it/s]

OK_19785_2018 completed in 0:00:00.283659

 49%|████▊     | 2091/4292 [10:59<12:24,  2.96it/s]

OR_6022_2018 completed in 0:00:00.437678

 49%|████▊     | 2092/4292 [10:59<11:29,  3.19it/s]

OR_9191_2018 completed in 0:00:00.255363

 49%|████▉     | 2093/4292 [10:59<12:19,  2.98it/s]

OR_14354_2018 completed in 0:00:00.387512

 49%|████▉     | 2094/4292 [11:00<10:57,  3.34it/s]

OR_15248_2018 completed in 0:00:00.212550

 49%|████▉     | 2095/4292 [11:00<10:13,  3.58it/s]

OR_18260_2018 completed in 0:00:00.231856

 49%|████▉     | 2096/4292 [11:00<11:10,  3.27it/s]

OR_28541_2018 completed in 0:00:00.365326

 49%|████▉     | 2097/4292 [11:00<10:50,  3.38it/s]

OR_40437_2018 completed in 0:00:00.273823

 49%|████▉     | 2098/4292 [11:01<10:50,  3.37it/s]

PA_3597_2018 completed in 0:00:00.295872

 49%|████▉     | 2099/4292 [11:01<11:14,  3.25it/s]

PA_5487_2018 completed in 0:00:00.332806

 49%|████▉     | 2100/4292 [11:01<10:10,  3.59it/s]

PA_12390_2018 completed in 0:00:00.208871

 49%|████▉     | 2101/4292 [11:02<11:18,  3.23it/s]

PA_14711_2018 completed in 0:00:00.378875

 49%|████▉     | 2102/4292 [11:02<16:23,  2.23it/s]

PA_14715_2018 completed in 0:00:00.773132

 49%|████▉     | 2103/4292 [11:03<14:41,  2.48it/s]

PA_14716_2018 completed in 0:00:00.290162

 49%|████▉     | 2105/4292 [11:03<11:31,  3.16it/s]

PA_14940_2018 completed in 0:00:00.276545
PA_15045_2018 completed in 0:00:00.198561

 49%|████▉     | 2106/4292 [11:05<23:02,  1.58it/s]

PA_19390_2018 completed in 0:00:01.368289

 49%|████▉     | 2107/4292 [11:05<18:27,  1.97it/s]

PA_20334_2018 completed in 0:00:00.213266

 49%|████▉     | 2108/4292 [11:05<16:13,  2.24it/s]

PA_20387_2018 completed in 0:00:00.301893

 49%|████▉     | 2109/4292 [11:05<13:48,  2.64it/s]

RI_1857_2018 completed in 0:00:00.223958

 49%|████▉     | 2110/4292 [11:06<13:05,  2.78it/s]

RI_13214_2018 completed in 0:00:00.314258

 49%|████▉     | 2111/4292 [11:06<12:32,  2.90it/s]

SC_1613_2018 completed in 0:00:00.308831

 49%|████▉     | 2112/4292 [11:06<11:45,  3.09it/s]

SC_3046_2018 completed in 0:00:00.272878

 49%|████▉     | 2113/4292 [11:06<10:46,  3.37it/s]

SC_5416_2018 completed in 0:00:00.232058

 49%|████▉     | 2114/4292 [11:07<10:38,  3.41it/s]

SC_14398_2018 completed in 0:00:00.284456

 49%|████▉     | 2115/4292 [11:07<11:38,  3.12it/s]

SC_17539_2018 completed in 0:00:00.384622

 49%|████▉     | 2116/4292 [11:08<16:20,  2.22it/s]

SC_17543_2018 completed in 0:00:00.752032

 49%|████▉     | 2117/4292 [11:08<14:07,  2.57it/s]

SD_1769_2018 completed in 0:00:00.246596

 49%|████▉     | 2118/4292 [11:08<12:27,  2.91it/s]

SD_14232_2018 completed in 0:00:00.236731

 49%|████▉     | 2119/4292 [11:09<12:03,  3.00it/s]

SD_17267_2018 completed in 0:00:00.306097

 49%|████▉     | 2120/4292 [11:09<12:15,  2.95it/s]

SD_19293_2018 completed in 0:00:00.351460

 49%|████▉     | 2121/4292 [11:09<12:48,  2.82it/s]

SD_20401_2018 completed in 0:00:00.389111

 49%|████▉     | 2122/4292 [11:10<12:12,  2.96it/s]

TN_10331_2018 completed in 0:00:00.298289

 49%|████▉     | 2123/4292 [11:10<11:31,  3.13it/s]

TX_5701_2018 completed in 0:00:00.274673

 49%|████▉     | 2124/4292 [11:10<11:20,  3.18it/s]

TX_16604_2018 completed in 0:00:00.301505

 50%|████▉     | 2125/4292 [11:11<12:20,  2.92it/s]

TX_17698_2018 completed in 0:00:00.406169

 50%|████▉     | 2126/4292 [11:11<15:08,  2.38it/s]

TX_55937_2018 completed in 0:00:00.599430

 50%|████▉     | 2127/4292 [11:12<13:01,  2.77it/s]

UT_2010_2018 completed in 0:00:00.223710

 50%|████▉     | 2128/4292 [11:12<12:06,  2.98it/s]

UT_11135_2018 completed in 0:00:00.276557

 50%|████▉     | 2129/4292 [11:12<13:54,  2.59it/s]

UT_12866_2018 completed in 0:00:00.501481

 50%|████▉     | 2130/4292 [11:13<13:44,  2.62it/s]

UT_14354_2018 completed in 0:00:00.369732

 50%|████▉     | 2131/4292 [11:13<12:47,  2.82it/s]

UT_15444_2018 completed in 0:00:00.292908

 50%|████▉     | 2132/4292 [11:13<14:05,  2.55it/s]

UT_17845_2018 completed in 0:00:00.476346

 50%|████▉     | 2133/4292 [11:14<16:36,  2.17it/s]

UT_17874_2018 completed in 0:00:00.623787

 50%|████▉     | 2134/4292 [11:14<14:46,  2.43it/s]

UT_18206_2018 completed in 0:00:00.290634

 50%|████▉     | 2135/4292 [11:15<13:55,  2.58it/s]

VA_84_2018 completed in 0:00:00.331193

 50%|████▉     | 2136/4292 [11:15<12:48,  2.81it/s]

VA_733_2018 completed in 0:00:00.283272

 50%|████▉     | 2137/4292 [11:15<13:12,  2.72it/s]

VA_10171_2018 completed in 0:00:00.393809

 50%|████▉     | 2138/4292 [11:16<12:23,  2.90it/s]

VA_17066_2018 completed in 0:00:00.290690

 50%|████▉     | 2139/4292 [11:16<13:14,  2.71it/s]

VA_19876_2018 completed in 0:00:00.421888

 50%|████▉     | 2140/4292 [11:16<11:40,  3.07it/s]

VA_19882_2018 completed in 0:00:00.223229

 50%|████▉     | 2141/4292 [11:17<10:52,  3.30it/s]

VA_40228_2018 completed in 0:00:00.250603

 50%|████▉     | 2142/4292 [11:17<12:08,  2.95it/s]

VT_2548_2018 completed in 0:00:00.420633

 50%|████▉     | 2143/4292 [11:17<11:28,  3.12it/s]

VT_7601_2018 completed in 0:00:00.276953

 50%|████▉     | 2144/4292 [11:18<11:14,  3.18it/s]

VT_19791_2018 completed in 0:00:00.297999

 50%|████▉     | 2145/4292 [11:18<11:26,  3.13it/s]

WA_3660_2018 completed in 0:00:00.332155

 50%|█████     | 2146/4292 [11:18<12:13,  2.93it/s]

WA_14354_2018 completed in 0:00:00.391598

 50%|█████     | 2147/4292 [11:19<12:06,  2.95it/s]

WA_15500_2018 completed in 0:00:00.331443

 50%|█████     | 2148/4292 [11:19<11:25,  3.13it/s]

WA_16868_2018 completed in 0:00:00.273799

 50%|█████     | 2149/4292 [11:19<11:39,  3.07it/s]

WA_17470_2018 completed in 0:00:00.340848

 50%|█████     | 2150/4292 [11:20<12:07,  2.94it/s]

WA_18429_2018 completed in 0:00:00.370626

 50%|█████     | 2152/4292 [11:20<10:35,  3.37it/s]

WA_20169_2018 completed in 0:00:00.343851
WI_4715_2018 completed in 0:00:00.192177

 50%|█████     | 2153/4292 [11:21<11:31,  3.09it/s]

WI_5574_2018 completed in 0:00:00.384222

 50%|█████     | 2154/4292 [11:21<10:55,  3.26it/s]

WI_11479_2018 completed in 0:00:00.266119

 50%|█████     | 2155/4292 [11:21<10:07,  3.52it/s]

WI_13697_2018 completed in 0:00:00.231379

 50%|█████     | 2156/4292 [11:21<09:30,  3.74it/s]

WI_13815_2018 completed in 0:00:00.226789

 50%|█████     | 2157/4292 [11:22<09:43,  3.66it/s]

WI_20847_2018 completed in 0:00:00.286111

 50%|█████     | 2158/4292 [11:22<13:05,  2.72it/s]

WI_20856_2018 completed in 0:00:00.588544

 50%|█████     | 2159/4292 [11:23<12:56,  2.75it/s]

WI_20860_2018 completed in 0:00:00.354070

 50%|█████     | 2160/4292 [11:23<12:54,  2.75it/s]

WV_733_2018 completed in 0:00:00.360074

 50%|█████     | 2161/4292 [11:23<11:57,  2.97it/s]

WV_12796_2018 completed in 0:00:00.274775

 50%|█████     | 2162/4292 [11:23<11:31,  3.08it/s]

WV_15263_2018 completed in 0:00:00.295131

 50%|█████     | 2163/4292 [11:24<11:32,  3.07it/s]

WV_20521_2018 completed in 0:00:00.325904

 50%|█████     | 2164/4292 [11:24<11:36,  3.06it/s]

WY_3461_2018 completed in 0:00:00.330533

 50%|█████     | 2165/4292 [11:25<12:19,  2.88it/s]

WY_7222_2018 completed in 0:00:00.394709

 50%|█████     | 2166/4292 [11:25<11:51,  2.99it/s]

WY_8566_2018 completed in 0:00:00.303571

 50%|█████     | 2167/4292 [11:25<14:09,  2.50it/s]

WY_11273_2018 completed in 0:00:00.550428

 51%|█████     | 2168/4292 [11:26<12:59,  2.72it/s]

WY_14354_2018 completed in 0:00:00.290123

 51%|█████     | 2169/4292 [11:26<12:34,  2.82it/s]

WY_19156_2018 completed in 0:00:00.326253

 51%|█████     | 2171/4292 [11:26<10:02,  3.52it/s]

WY_27058_2018 completed in 0:00:00.254975
CA_4390_2018 completed in 0:00:00.186473

 51%|█████     | 2172/4292 [11:27<09:52,  3.58it/s]

NE_27058_2018 completed in 0:00:00.267816

 51%|█████     | 2173/4292 [11:28<16:13,  2.18it/s]

NY_14711_2018 completed in 0:00:00.877761

 51%|█████     | 2174/4292 [11:28<14:10,  2.49it/s]

ME_11477_2018 completed in 0:00:00.264825

 51%|█████     | 2175/4292 [11:28<13:26,  2.63it/s]

MT_12199_2018 completed in 0:00:00.331769

 51%|█████     | 2176/4292 [11:28<11:41,  3.01it/s]

ND_12090_2018 completed in 0:00:00.215468

 51%|█████     | 2177/4292 [11:29<11:12,  3.14it/s]

RI_14537_2018 completed in 0:00:00.285090

 51%|█████     | 2178/4292 [11:29<11:11,  3.15it/s]

WY_12199_2018 completed in 0:00:00.315012

 51%|█████     | 2179/4292 [11:29<12:16,  2.87it/s]

AK_219_2019 completed in 0:00:00.417729

 51%|█████     | 2180/4292 [11:30<12:06,  2.91it/s]

AK_599_2019 completed in 0:00:00.332270

 51%|█████     | 2181/4292 [11:30<12:19,  2.85it/s]

AK_3522_2019 completed in 0:00:00.364646

 51%|█████     | 2182/4292 [11:30<11:24,  3.08it/s]

AK_7353_2019 completed in 0:00:00.263528

 51%|█████     | 2183/4292 [11:31<12:18,  2.86it/s]

AK_11824_2019 completed in 0:00:00.408755

 51%|█████     | 2184/4292 [11:31<12:16,  2.86it/s]

AK_19558_2019 completed in 0:00:00.346192

 51%|█████     | 2185/4292 [11:32<14:07,  2.49it/s]

AR_814_2019 completed in 0:00:00.524502

 51%|█████     | 2186/4292 [11:32<12:43,  2.76it/s]

AR_817_2019 completed in 0:00:00.270021

 51%|█████     | 2187/4292 [11:32<12:09,  2.89it/s]

AR_3093_2019 completed in 0:00:00.307943

 51%|█████     | 2188/4292 [11:32<10:47,  3.25it/s]

AR_5860_2019 completed in 0:00:00.216791

 51%|█████     | 2189/4292 [11:33<11:29,  3.05it/s]

AR_6342_2019 completed in 0:00:00.374009

 51%|█████     | 2190/4292 [11:33<12:45,  2.74it/s]

AR_13718_2019 completed in 0:00:00.448392

 51%|█████     | 2191/4292 [11:33<11:09,  3.14it/s]

AR_14063_2019 completed in 0:00:00.211495

 51%|█████     | 2193/4292 [11:34<09:10,  3.81it/s]

AR_17698_2019 completed in 0:00:00.246977
AZ_176_2019 completed in 0:00:00.178659

 51%|█████     | 2194/4292 [11:34<11:16,  3.10it/s]

AZ_803_2019 completed in 0:00:00.462333

 51%|█████     | 2195/4292 [11:35<10:57,  3.19it/s]

AZ_12919_2019 completed in 0:00:00.292225

 51%|█████     | 2196/4292 [11:35<10:49,  3.23it/s]

AZ_16572_2019 completed in 0:00:00.299713

 51%|█████     | 2197/4292 [11:35<10:22,  3.36it/s]

AZ_19189_2019 completed in 0:00:00.266633

 51%|█████     | 2198/4292 [11:36<10:52,  3.21it/s]

AZ_19728_2019 completed in 0:00:00.344892

 51%|█████     | 2199/4292 [11:36<11:34,  3.01it/s]

AZ_21538_2019 completed in 0:00:00.378373

 51%|█████▏    | 2201/4292 [11:36<09:46,  3.56it/s]

AZ_24211_2019 completed in 0:00:00.293429
CA_4390_2019 completed in 0:00:00.186325

 51%|█████▏    | 2202/4292 [11:37<09:49,  3.55it/s]

CA_9216_2019 completed in 0:00:00.284490

 51%|█████▏    | 2203/4292 [11:37<11:04,  3.14it/s]

CA_11208_2019 completed in 0:00:00.401499

 51%|█████▏    | 2204/4292 [11:37<10:33,  3.30it/s]

CA_12745_2019 completed in 0:00:00.267523

 51%|█████▏    | 2205/4292 [11:38<13:06,  2.65it/s]

CA_14328_2019 completed in 0:00:00.547252

 51%|█████▏    | 2206/4292 [11:38<11:55,  2.92it/s]

CA_14354_2019 completed in 0:00:00.262931

 51%|█████▏    | 2207/4292 [11:38<10:35,  3.28it/s]

CA_14534_2019 completed in 0:00:00.215038

 51%|█████▏    | 2208/4292 [11:39<10:31,  3.30it/s]

CA_16534_2019 completed in 0:00:00.297168

 51%|█████▏    | 2209/4292 [11:39<11:18,  3.07it/s]

CA_16609_2019 completed in 0:00:00.378251

 51%|█████▏    | 2210/4292 [11:39<11:07,  3.12it/s]

CA_16655_2019 completed in 0:00:00.306582

 52%|█████▏    | 2211/4292 [11:40<12:51,  2.70it/s]

CA_17609_2019 completed in 0:00:00.487395

 52%|█████▏    | 2212/4292 [11:40<12:18,  2.82it/s]

CA_17612_2019 completed in 0:00:00.316445

 52%|█████▏    | 2213/4292 [11:41<12:05,  2.86it/s]

CA_18260_2019 completed in 0:00:00.334240

 52%|█████▏    | 2214/4292 [11:41<12:21,  2.80it/s]

CA_19281_2019 completed in 0:00:00.373015

 52%|█████▏    | 2215/4292 [11:41<11:53,  2.91it/s]

CO_3989_2019 completed in 0:00:00.310146

 52%|█████▏    | 2216/4292 [11:42<11:38,  2.97it/s]

CO_6604_2019 completed in 0:00:00.319667

 52%|█████▏    | 2217/4292 [11:42<10:48,  3.20it/s]

CO_9336_2019 completed in 0:00:00.255032

 52%|█████▏    | 2218/4292 [11:42<11:22,  3.04it/s]

CO_12866_2019 completed in 0:00:00.366808

 52%|█████▏    | 2219/4292 [11:43<11:12,  3.08it/s]

CO_15257_2019 completed in 0:00:00.312278

 52%|█████▏    | 2220/4292 [11:43<10:49,  3.19it/s]

CO_15466_2019 completed in 0:00:00.287790

 52%|█████▏    | 2221/4292 [11:43<10:47,  3.20it/s]

CO_16603_2019 completed in 0:00:00.309740

 52%|█████▏    | 2222/4292 [11:43<11:18,  3.05it/s]

CO_19499_2019 completed in 0:00:00.362697

 52%|█████▏    | 2223/4292 [11:44<10:14,  3.37it/s]

CO_27058_2019 completed in 0:00:00.223867

 52%|█████▏    | 2224/4292 [11:44<09:32,  3.61it/s]

CO_56146_2019 completed in 0:00:00.228139

 52%|█████▏    | 2225/4292 [11:44<09:42,  3.55it/s]

CT_4176_2019 completed in 0:00:00.292841
CT_7716_2019 completed in 0:00:00.203922

 52%|█████▏    | 2227/4292 [11:45<09:46,  3.52it/s]

CT_19497_2019 completed in 0:00:00.342275

 52%|█████▏    | 2228/4292 [11:45<10:17,  3.34it/s]

CT_20038_2019 completed in 0:00:00.334331

 52%|█████▏    | 2229/4292 [11:45<09:59,  3.44it/s]

DC_15270_2019 completed in 0:00:00.269002

 52%|█████▏    | 2230/4292 [11:46<09:55,  3.46it/s]

DE_5027_2019 completed in 0:00:00.283740

 52%|█████▏    | 2231/4292 [11:46<10:32,  3.26it/s]

DE_5070_2019 completed in 0:00:00.348011

 52%|█████▏    | 2232/4292 [11:46<10:01,  3.42it/s]

DE_5335_2019 completed in 0:00:00.256766

 52%|█████▏    | 2233/4292 [11:47<12:21,  2.78it/s]

DE_13519_2019 completed in 0:00:00.517706

 52%|█████▏    | 2234/4292 [11:47<11:33,  2.97it/s]

FL_6452_2019 completed in 0:00:00.282727

 52%|█████▏    | 2235/4292 [11:47<11:00,  3.11it/s]

FL_6455_2019 completed in 0:00:00.282895

 52%|█████▏    | 2236/4292 [11:48<15:46,  2.17it/s]

FL_6457_2019 completed in 0:00:00.784593

 52%|█████▏    | 2238/4292 [11:49<14:23,  2.38it/s]

FL_7801_2019 completed in 0:00:00.715716
FL_9617_2019 completed in 0:00:00.147546

 52%|█████▏    | 2239/4292 [11:49<12:08,  2.82it/s]

FL_18454_2019 completed in 0:00:00.199922

 52%|█████▏    | 2240/4292 [11:49<11:23,  3.00it/s]

GA_3916_2019 completed in 0:00:00.281309

 52%|█████▏    | 2241/4292 [11:50<11:56,  2.86it/s]

GA_9601_2019 completed in 0:00:00.386218

 52%|█████▏    | 2242/4292 [11:50<11:36,  2.94it/s]

HI_8287_2019 completed in 0:00:00.316715

 52%|█████▏    | 2243/4292 [11:50<11:05,  3.08it/s]

HI_10071_2019 completed in 0:00:00.289247

 52%|█████▏    | 2244/4292 [11:51<10:42,  3.19it/s]

HI_11843_2019 completed in 0:00:00.286301

 52%|█████▏    | 2245/4292 [11:51<09:46,  3.49it/s]

HI_19547_2019 completed in 0:00:00.223207

 52%|█████▏    | 2246/4292 [11:52<12:21,  2.76it/s]

IA_9417_2019 completed in 0:00:00.537881

 52%|█████▏    | 2247/4292 [11:52<11:30,  2.96it/s]

IA_12341_2019 completed in 0:00:00.278637

 52%|█████▏    | 2248/4292 [11:52<10:28,  3.25it/s]

ID_9187_2019 completed in 0:00:00.236242

 52%|█████▏    | 2249/4292 [11:52<10:53,  3.13it/s]

ID_9191_2019 completed in 0:00:00.346806

 52%|█████▏    | 2250/4292 [11:53<10:46,  3.16it/s]

ID_10454_2019 completed in 0:00:00.304455

 52%|█████▏    | 2251/4292 [11:53<10:01,  3.40it/s]

ID_11273_2019 completed in 0:00:00.242077

 52%|█████▏    | 2252/4292 [11:53<10:10,  3.34it/s]

ID_14354_2019 completed in 0:00:00.309179

 52%|█████▏    | 2253/4292 [11:54<10:01,  3.39it/s]

ID_20169_2019 completed in 0:00:00.283878

 53%|█████▎    | 2254/4292 [11:54<09:54,  3.43it/s]

IL_4110_2019 completed in 0:00:00.282106

 53%|█████▎    | 2255/4292 [11:54<09:11,  3.69it/s]

IL_12341_2019 completed in 0:00:00.221248

 53%|█████▎    | 2256/4292 [11:54<08:55,  3.80it/s]

IL_13032_2019 completed in 0:00:00.244574

 53%|█████▎    | 2257/4292 [11:55<09:22,  3.62it/s]

IL_56697_2019 completed in 0:00:00.306101

 53%|█████▎    | 2258/4292 [11:55<09:17,  3.65it/s]

IN_9273_2019 completed in 0:00:00.267171

 53%|█████▎    | 2259/4292 [11:55<09:08,  3.71it/s]

IN_9324_2019 completed in 0:00:00.259050

 53%|█████▎    | 2260/4292 [11:55<10:04,  3.36it/s]

IN_13756_2019 completed in 0:00:00.360781

 53%|█████▎    | 2261/4292 [11:56<10:15,  3.30it/s]

IN_15470_2019 completed in 0:00:00.314996

 53%|█████▎    | 2262/4292 [11:56<09:15,  3.65it/s]

IN_17633_2019 completed in 0:00:00.204906

 53%|█████▎    | 2263/4292 [11:56<09:10,  3.68it/s]

KS_5860_2019 completed in 0:00:00.264203

 53%|█████▎    | 2264/4292 [11:57<10:09,  3.33it/s]

KS_9996_2019 completed in 0:00:00.368297

 53%|█████▎    | 2265/4292 [11:57<10:53,  3.10it/s]

KS_10000_2019 completed in 0:00:00.372083

 53%|█████▎    | 2266/4292 [11:57<10:13,  3.30it/s]

KS_10005_2019 completed in 0:00:00.255325

 53%|█████▎    | 2267/4292 [11:57<09:19,  3.62it/s]

KS_22500_2019 completed in 0:00:00.214358

 53%|█████▎    | 2268/4292 [11:58<11:08,  3.03it/s]

KY_9964_2019 completed in 0:00:00.455371

 53%|█████▎    | 2269/4292 [11:58<12:36,  2.67it/s]

KY_10171_2019 completed in 0:00:00.474711

 53%|█████▎    | 2270/4292 [11:59<12:18,  2.74it/s]

KY_11249_2019 completed in 0:00:00.343856

 53%|█████▎    | 2271/4292 [11:59<11:50,  2.85it/s]

KY_17564_2019 completed in 0:00:00.317989

 53%|█████▎    | 2272/4292 [11:59<10:30,  3.21it/s]

KY_19446_2019 completed in 0:00:00.218923

 53%|█████▎    | 2273/4292 [12:00<10:05,  3.33it/s]

KY_22053_2019 completed in 0:00:00.269880

 53%|█████▎    | 2274/4292 [12:00<09:37,  3.49it/s]

KY_49998_2019 completed in 0:00:00.253474

 53%|█████▎    | 2275/4292 [12:00<12:15,  2.74it/s]

LA_3265_2019 completed in 0:00:00.546602

 53%|█████▎    | 2276/4292 [12:01<12:55,  2.60it/s]

LA_11241_2019 completed in 0:00:00.429585

 53%|█████▎    | 2277/4292 [12:01<12:33,  2.68it/s]

LA_13478_2019 completed in 0:00:00.347973

 53%|█████▎    | 2278/4292 [12:01<11:23,  2.95it/s]

LA_17698_2019 completed in 0:00:00.258304

 53%|█████▎    | 2279/4292 [12:02<10:04,  3.33it/s]

MA_6374_2019 completed in 0:00:00.208151

 53%|█████▎    | 2281/4292 [12:02<08:54,  3.76it/s]

MA_8774_2019 completed in 0:00:00.278194
MA_11804_2019 completed in 0:00:00.197502

 53%|█████▎    | 2282/4292 [12:02<09:02,  3.70it/s]

MA_13206_2019 completed in 0:00:00.279766

 53%|█████▎    | 2283/4292 [12:03<08:51,  3.78it/s]

MA_15748_2019 completed in 0:00:00.249783

 53%|█████▎    | 2284/4292 [12:03<09:01,  3.71it/s]

MA_54913_2019 completed in 0:00:00.281356

 53%|█████▎    | 2285/4292 [12:03<08:55,  3.75it/s]

MD_1167_2019 completed in 0:00:00.258399

 53%|█████▎    | 2286/4292 [12:04<10:17,  3.25it/s]

MD_5027_2019 completed in 0:00:00.403173

 53%|█████▎    | 2287/4292 [12:04<09:24,  3.55it/s]

MD_15263_2019 completed in 0:00:00.219610

 53%|█████▎    | 2288/4292 [12:04<10:30,  3.18it/s]

MD_15270_2019 completed in 0:00:00.386473

 53%|█████▎    | 2289/4292 [12:04<10:17,  3.25it/s]

MD_17637_2019 completed in 0:00:00.288190

 53%|█████▎    | 2290/4292 [12:05<09:34,  3.48it/s]

ME_1179_2019 completed in 0:00:00.237221

 53%|█████▎    | 2291/4292 [12:07<34:11,  1.03s/it]

ME_3266_2019 completed in 0:00:02.746275

 53%|█████▎    | 2292/4292 [12:08<26:06,  1.28it/s]

ME_5609_2019 completed in 0:00:00.217559

 53%|█████▎    | 2293/4292 [12:08<21:25,  1.55it/s]

MI_392_2019 completed in 0:00:00.315490

 53%|█████▎    | 2294/4292 [12:08<17:03,  1.95it/s]

MI_3828_2019 completed in 0:00:00.205394

 53%|█████▎    | 2295/4292 [12:09<15:22,  2.16it/s]

MI_4254_2019 completed in 0:00:00.344056

 53%|█████▎    | 2296/4292 [12:09<13:12,  2.52it/s]

MI_5109_2019 completed in 0:00:00.243911

 54%|█████▎    | 2298/4292 [12:10<12:42,  2.62it/s]

MI_9324_2019 completed in 0:00:00.664657
MI_10704_2019 completed in 0:00:00.159159

 54%|█████▎    | 2299/4292 [12:10<11:56,  2.78it/s]

MI_19578_2019 completed in 0:00:00.306301

 54%|█████▎    | 2300/4292 [12:10<10:58,  3.03it/s]

MN_689_2019 completed in 0:00:00.260859

 54%|█████▎    | 2301/4292 [12:10<10:01,  3.31it/s]

MN_5574_2019 completed in 0:00:00.235667

 54%|█████▎    | 2302/4292 [12:11<11:32,  2.87it/s]

MN_10596_2019 completed in 0:00:00.454618

 54%|█████▎    | 2303/4292 [12:11<10:18,  3.22it/s]

MN_12647_2019 completed in 0:00:00.222667

 54%|█████▎    | 2304/4292 [12:11<09:54,  3.35it/s]

MN_13781_2019 completed in 0:00:00.270014

 54%|█████▎    | 2305/4292 [12:12<10:23,  3.19it/s]

MN_14232_2019 completed in 0:00:00.348120

 54%|█████▎    | 2306/4292 [12:12<11:42,  2.83it/s]

MN_16181_2019 completed in 0:00:00.446598

 54%|█████▍    | 2307/4292 [12:12<10:51,  3.04it/s]

MN_17267_2019 completed in 0:00:00.268120

 54%|█████▍    | 2308/4292 [12:13<09:54,  3.34it/s]

MN_20996_2019 completed in 0:00:00.231479

 54%|█████▍    | 2309/4292 [12:13<14:04,  2.35it/s]

MN_25177_2019 completed in 0:00:00.719090

 54%|█████▍    | 2310/4292 [12:14<12:18,  2.69it/s]

MO_4675_2019 completed in 0:00:00.246870

 54%|█████▍    | 2311/4292 [12:14<12:03,  2.74it/s]

MO_5860_2019 completed in 0:00:00.347170

 54%|█████▍    | 2312/4292 [12:14<12:15,  2.69it/s]

MO_9231_2019 completed in 0:00:00.385102

 54%|█████▍    | 2313/4292 [12:15<10:40,  3.09it/s]

MO_10000_2019 completed in 0:00:00.210839

 54%|█████▍    | 2315/4292 [12:15<09:03,  3.64it/s]

MO_12698_2019 completed in 0:00:00.307294
MO_17833_2019 completed in 0:00:00.171573

 54%|█████▍    | 2316/4292 [12:15<09:19,  3.53it/s]

MO_19436_2019 completed in 0:00:00.301098

 54%|█████▍    | 2317/4292 [12:16<09:22,  3.51it/s]

MS_3841_2019 completed in 0:00:00.286795

 54%|█████▍    | 2318/4292 [12:16<10:05,  3.26it/s]

MS_12685_2019 completed in 0:00:00.356818

 54%|█████▍    | 2320/4292 [12:16<08:37,  3.81it/s]

MS_12686_2019 completed in 0:00:00.260871
MS_17647_2019 completed in 0:00:00.188337

 54%|█████▍    | 2321/4292 [12:17<07:58,  4.11it/s]

MT_6395_2019 completed in 0:00:00.195884

 54%|█████▍    | 2322/4292 [12:17<08:25,  3.89it/s]

MT_12692_2019 completed in 0:00:00.287768

 54%|█████▍    | 2323/4292 [12:17<08:38,  3.80it/s]

MT_12825_2019 completed in 0:00:00.277656

 54%|█████▍    | 2324/4292 [12:18<16:58,  1.93it/s]

MT_19603_2019 completed in 0:00:01.107181

 54%|█████▍    | 2325/4292 [12:19<14:36,  2.24it/s]

MT_20997_2019 completed in 0:00:00.276509

 54%|█████▍    | 2326/4292 [12:19<12:40,  2.59it/s]

NC_3046_2019 completed in 0:00:00.248828

 54%|█████▍    | 2328/4292 [12:19<10:01,  3.27it/s]

NC_5416_2019 completed in 0:00:00.292668
NC_9837_2019 completed in 0:00:00.182824

 54%|█████▍    | 2329/4292 [12:20<10:05,  3.24it/s]

NC_16496_2019 completed in 0:00:00.312249

 54%|█████▍    | 2330/4292 [12:20<13:50,  2.36it/s]

NC_19876_2019 completed in 0:00:00.690401

 54%|█████▍    | 2331/4292 [12:21<12:47,  2.55it/s]

NC_24889_2019 completed in 0:00:00.315967

 54%|█████▍    | 2332/4292 [12:22<19:46,  1.65it/s]

ND_12090_2019 completed in 0:00:01.103268

 54%|█████▍    | 2333/4292 [12:22<16:01,  2.04it/s]

ND_12301_2019 completed in 0:00:00.221957

 54%|█████▍    | 2334/4292 [12:22<13:48,  2.36it/s]

ND_14232_2019 completed in 0:00:00.264091

 54%|█████▍    | 2335/4292 [12:23<12:20,  2.64it/s]

ND_19790_2019 completed in 0:00:00.273545

 54%|█████▍    | 2336/4292 [12:23<10:42,  3.04it/s]

ND_24949_2019 completed in 0:00:00.210950

 54%|█████▍    | 2337/4292 [12:23<10:35,  3.08it/s]

NE_4373_2019 completed in 0:00:00.315762

 54%|█████▍    | 2338/4292 [12:23<09:26,  3.45it/s]

NE_4911_2019 completed in 0:00:00.207378

 54%|█████▍    | 2339/4292 [12:24<11:00,  2.95it/s]

NE_6779_2019 completed in 0:00:00.450180
NE_11018_2019 completed in 0:00:00.200659

 55%|█████▍    | 2342/4292 [12:24<08:32,  3.81it/s]

NE_11251_2019 completed in 0:00:00.274285
NE_12539_2019 completed in 0:00:00.195938

 55%|█████▍    | 2343/4292 [12:25<08:16,  3.93it/s]

NE_13337_2019 completed in 0:00:00.235512

 55%|█████▍    | 2345/4292 [12:25<08:35,  3.78it/s]

NE_13664_2019 completed in 0:00:00.414323
NE_14127_2019 completed in 0:00:00.174770

 55%|█████▍    | 2346/4292 [12:26<09:35,  3.38it/s]

NE_17642_2019 completed in 0:00:00.367698

 55%|█████▍    | 2347/4292 [12:26<09:38,  3.36it/s]

NE_27058_2019 completed in 0:00:00.301058

 55%|█████▍    | 2348/4292 [12:26<08:57,  3.62it/s]

NE_40606_2019 completed in 0:00:00.226119

 55%|█████▍    | 2349/4292 [12:26<09:04,  3.57it/s]

NH_13441_2019 completed in 0:00:00.288332

 55%|█████▍    | 2351/4292 [12:27<08:14,  3.93it/s]

NH_15472_2019 completed in 0:00:00.270444
NH_24590_2019 completed in 0:00:00.199506

 55%|█████▍    | 2352/4292 [12:27<08:26,  3.83it/s]

NJ_963_2019 completed in 0:00:00.274814

 55%|█████▍    | 2353/4292 [12:27<08:01,  4.03it/s]

NJ_9726_2019 completed in 0:00:00.217297

 55%|█████▍    | 2354/4292 [12:28<08:19,  3.88it/s]

NJ_15477_2019 completed in 0:00:00.279547

 55%|█████▍    | 2355/4292 [12:28<08:14,  3.91it/s]

NJ_16213_2019 completed in 0:00:00.249020

 55%|█████▍    | 2357/4292 [12:28<07:01,  4.59it/s]

NM_3287_2019 completed in 0:00:00.216540
NM_5701_2019 completed in 0:00:00.156075

 55%|█████▍    | 2358/4292 [12:29<07:04,  4.56it/s]

NM_6204_2019 completed in 0:00:00.221311

 55%|█████▍    | 2359/4292 [12:29<07:23,  4.36it/s]

NM_11204_2019 completed in 0:00:00.252143

 55%|█████▍    | 2360/4292 [12:29<08:32,  3.77it/s]

NM_15473_2019 completed in 0:00:00.347798

 55%|█████▌    | 2362/4292 [12:30<09:20,  3.44it/s]

NM_17718_2019 completed in 0:00:00.496976
NV_2008_2019 completed in 0:00:00.184850

 55%|█████▌    | 2364/4292 [12:30<08:22,  3.83it/s]

NV_13073_2019 completed in 0:00:00.287669
NV_13407_2019 completed in 0:00:00.190317

 55%|█████▌    | 2365/4292 [12:30<07:48,  4.12it/s]

NV_17166_2019 completed in 0:00:00.196363

 55%|█████▌    | 2366/4292 [12:31<07:40,  4.18it/s]

NV_19840_2019 completed in 0:00:00.229441

 55%|█████▌    | 2368/4292 [12:31<08:36,  3.73it/s]

NY_3249_2019 completed in 0:00:00.458439
NY_4226_2019 completed in 0:00:00.180882

 55%|█████▌    | 2369/4292 [12:32<07:33,  4.24it/s]

NY_11171_2019 completed in 0:00:00.158569

 55%|█████▌    | 2370/4292 [12:32<08:25,  3.80it/s]

NY_13511_2019 completed in 0:00:00.326222

 55%|█████▌    | 2372/4292 [12:32<08:34,  3.73it/s]

NY_13573_2019 completed in 0:00:00.406283
NY_14154_2019 completed in 0:00:00.176901

 55%|█████▌    | 2373/4292 [12:33<07:45,  4.12it/s]

NY_14711_2019 completed in 0:00:00.182909

 55%|█████▌    | 2374/4292 [12:33<07:34,  4.22it/s]

NY_16183_2019 completed in 0:00:00.223319

 55%|█████▌    | 2375/4292 [12:33<08:01,  3.98it/s]

OH_3542_2019 completed in 0:00:00.284096

 55%|█████▌    | 2376/4292 [12:33<08:21,  3.82it/s]

OH_3755_2019 completed in 0:00:00.285550

 55%|█████▌    | 2377/4292 [12:34<08:58,  3.56it/s]

OH_4922_2019 completed in 0:00:00.325238

 55%|█████▌    | 2378/4292 [12:34<08:18,  3.84it/s]

OH_13998_2019 completed in 0:00:00.211439

 55%|█████▌    | 2379/4292 [12:34<09:01,  3.53it/s]

OH_14006_2019 completed in 0:00:00.334600

 55%|█████▌    | 2381/4292 [12:35<07:53,  4.04it/s]

OH_18997_2019 completed in 0:00:00.245905
OK_5860_2019 completed in 0:00:00.189700

 56%|█████▌    | 2383/4292 [12:35<08:33,  3.72it/s]

OK_13734_2019 completed in 0:00:00.423999
OK_14062_2019 completed in 0:00:00.193220

 56%|█████▌    | 2384/4292 [12:36<08:45,  3.63it/s]

OK_14063_2019 completed in 0:00:00.289622

 56%|█████▌    | 2385/4292 [12:36<08:51,  3.59it/s]

OK_15474_2019 completed in 0:00:00.285590

 56%|█████▌    | 2386/4292 [12:37<12:40,  2.51it/s]

OK_19785_2019 completed in 0:00:00.678286

 56%|█████▌    | 2387/4292 [12:37<11:46,  2.70it/s]

OR_6022_2019 completed in 0:00:00.304803

 56%|█████▌    | 2388/4292 [12:37<11:48,  2.69it/s]

OR_9191_2019 completed in 0:00:00.373870

 56%|█████▌    | 2389/4292 [12:38<11:02,  2.87it/s]

OR_14354_2019 completed in 0:00:00.292107

 56%|█████▌    | 2391/4292 [12:38<09:34,  3.31it/s]

OR_15248_2019 completed in 0:00:00.393551
OR_18260_2019 completed in 0:00:00.161693

 56%|█████▌    | 2392/4292 [12:38<09:09,  3.46it/s]

OR_28541_2019 completed in 0:00:00.257856

 56%|█████▌    | 2393/4292 [12:39<11:42,  2.70it/s]

OR_40437_2019 completed in 0:00:00.557615

 56%|█████▌    | 2394/4292 [12:39<10:13,  3.09it/s]

PA_3597_2019 completed in 0:00:00.212916

 56%|█████▌    | 2395/4292 [12:39<09:16,  3.41it/s]

PA_5487_2019 completed in 0:00:00.221728

 56%|█████▌    | 2396/4292 [12:40<09:05,  3.48it/s]

PA_12390_2019 completed in 0:00:00.273350

 56%|█████▌    | 2397/4292 [12:40<09:17,  3.40it/s]

PA_14711_2019 completed in 0:00:00.308217

 56%|█████▌    | 2398/4292 [12:41<11:46,  2.68it/s]

PA_14715_2019 completed in 0:00:00.557133

 56%|█████▌    | 2400/4292 [12:41<09:14,  3.41it/s]

PA_14716_2019 completed in 0:00:00.249001
PA_14940_2019 completed in 0:00:00.191399

 56%|█████▌    | 2401/4292 [12:41<08:18,  3.79it/s]

PA_15045_2019 completed in 0:00:00.194741
PA_19390_2019 completed in 0:00:00.202334

 56%|█████▌    | 2403/4292 [12:42<07:23,  4.26it/s]

PA_20334_2019 completed in 0:00:00.207347

 56%|█████▌    | 2404/4292 [12:42<08:11,  3.84it/s]

PA_20387_2019 completed in 0:00:00.319043

 56%|█████▌    | 2406/4292 [12:42<07:01,  4.48it/s]

RI_1857_2019 completed in 0:00:00.203294
RI_13214_2019 completed in 0:00:00.175133

 56%|█████▌    | 2407/4292 [12:42<06:38,  4.73it/s]

RI_14537_2019 completed in 0:00:00.182456

 56%|█████▌    | 2408/4292 [12:43<07:38,  4.11it/s]

SC_1613_2019 completed in 0:00:00.315295

 56%|█████▌    | 2409/4292 [12:43<07:30,  4.18it/s]

SC_3046_2019 completed in 0:00:00.228402

 56%|█████▌    | 2410/4292 [12:43<07:37,  4.12it/s]

SC_5416_2019 completed in 0:00:00.250320

 56%|█████▌    | 2411/4292 [12:43<07:30,  4.18it/s]

SC_14398_2019 completed in 0:00:00.228504

 56%|█████▌    | 2412/4292 [12:44<07:27,  4.20it/s]

SC_17539_2019 completed in 0:00:00.232501

 56%|█████▌    | 2414/4292 [12:44<06:27,  4.84it/s]

SC_17543_2019 completed in 0:00:00.208310
SD_1769_2019 completed in 0:00:00.150991

 56%|█████▋    | 2416/4292 [12:44<06:12,  5.04it/s]

SD_14232_2019 completed in 0:00:00.187263
SD_17267_2019 completed in 0:00:00.191299

 56%|█████▋    | 2418/4292 [12:45<06:11,  5.05it/s]

SD_19293_2019 completed in 0:00:00.207061
SD_20401_2019 completed in 0:00:00.189915

 56%|█████▋    | 2419/4292 [12:45<06:13,  5.01it/s]

TN_10331_2019 completed in 0:00:00.201340

 56%|█████▋    | 2421/4292 [12:46<08:39,  3.60it/s]

TX_5701_2019 completed in 0:00:00.569956
TX_16604_2019 completed in 0:00:00.198715

 56%|█████▋    | 2422/4292 [12:46<08:29,  3.67it/s]

TX_55937_2019 completed in 0:00:00.259167

 56%|█████▋    | 2423/4292 [12:46<08:22,  3.72it/s]

UT_2010_2019 completed in 0:00:00.259395

 57%|█████▋    | 2425/4292 [12:47<07:23,  4.21it/s]

UT_11135_2019 completed in 0:00:00.242246
UT_12866_2019 completed in 0:00:00.182122

 57%|█████▋    | 2426/4292 [12:47<07:16,  4.27it/s]

UT_14354_2019 completed in 0:00:00.225000

 57%|█████▋    | 2428/4292 [12:47<07:10,  4.33it/s]

UT_15444_2019 completed in 0:00:00.266838
UT_17845_2019 completed in 0:00:00.199670

 57%|█████▋    | 2430/4292 [12:48<06:38,  4.67it/s]

UT_17874_2019 completed in 0:00:00.220435
UT_18206_2019 completed in 0:00:00.180010

 57%|█████▋    | 2431/4292 [12:48<06:45,  4.59it/s]

VA_84_2019 completed in 0:00:00.226031

 57%|█████▋    | 2432/4292 [12:48<06:45,  4.59it/s]

VA_733_2019 completed in 0:00:00.216988

 57%|█████▋    | 2433/4292 [12:49<06:48,  4.55it/s]

VA_10171_2019 completed in 0:00:00.221342

 57%|█████▋    | 2434/4292 [12:49<06:50,  4.53it/s]

VA_17066_2019 completed in 0:00:00.222626

 57%|█████▋    | 2435/4292 [12:49<07:28,  4.14it/s]

VA_19876_2019 completed in 0:00:00.289428

 57%|█████▋    | 2436/4292 [12:49<07:25,  4.17it/s]

VA_19882_2019 completed in 0:00:00.234712

 57%|█████▋    | 2437/4292 [12:50<08:46,  3.52it/s]

VA_40228_2019 completed in 0:00:00.385300

 57%|█████▋    | 2438/4292 [12:50<08:06,  3.81it/s]

VT_2548_2019 completed in 0:00:00.211421

 57%|█████▋    | 2439/4292 [12:50<09:00,  3.43it/s]

VT_7601_2019 completed in 0:00:00.358305

 57%|█████▋    | 2441/4292 [12:51<08:01,  3.84it/s]

VT_19791_2019 completed in 0:00:00.279391
WA_3660_2019 completed in 0:00:00.194276

 57%|█████▋    | 2442/4292 [12:51<07:28,  4.12it/s]

WA_14354_2019 completed in 0:00:00.200601

 57%|█████▋    | 2443/4292 [12:51<07:25,  4.15it/s]

WA_15500_2019 completed in 0:00:00.236283

 57%|█████▋    | 2445/4292 [12:52<06:53,  4.46it/s]

WA_16868_2019 completed in 0:00:00.242847
WA_17470_2019 completed in 0:00:00.181473

 57%|█████▋    | 2446/4292 [12:52<06:30,  4.72it/s]

WA_18429_2019 completed in 0:00:00.179700

 57%|█████▋    | 2447/4292 [12:52<06:53,  4.46it/s]

WA_20169_2019 completed in 0:00:00.252382

 57%|█████▋    | 2448/4292 [12:52<07:39,  4.01it/s]

WI_4715_2019 completed in 0:00:00.306570

 57%|█████▋    | 2449/4292 [12:53<08:31,  3.61it/s]

WI_5574_2019 completed in 0:00:00.342183

 57%|█████▋    | 2450/4292 [12:53<08:31,  3.60it/s]

WI_11479_2019 completed in 0:00:00.276660

 57%|█████▋    | 2451/4292 [12:53<08:09,  3.76it/s]

WI_13697_2019 completed in 0:00:00.238825

 57%|█████▋    | 2452/4292 [12:53<07:59,  3.84it/s]

WI_13815_2019 completed in 0:00:00.245793

 57%|█████▋    | 2453/4292 [12:54<08:16,  3.70it/s]

WI_20847_2019 completed in 0:00:00.291765

 57%|█████▋    | 2454/4292 [12:54<07:42,  3.97it/s]

WI_20856_2019 completed in 0:00:00.207080

 57%|█████▋    | 2455/4292 [12:54<07:34,  4.04it/s]

WI_20860_2019 completed in 0:00:00.236318

 57%|█████▋    | 2456/4292 [12:54<07:12,  4.24it/s]

WV_733_2019 completed in 0:00:00.206211

 57%|█████▋    | 2457/4292 [12:55<07:06,  4.30it/s]

WV_12796_2019 completed in 0:00:00.223893

 57%|█████▋    | 2458/4292 [12:55<07:17,  4.19it/s]

WV_15263_2019 completed in 0:00:00.252169

 57%|█████▋    | 2459/4292 [12:55<07:16,  4.20it/s]

WV_20521_2019 completed in 0:00:00.233087

 57%|█████▋    | 2460/4292 [12:55<07:03,  4.33it/s]

WY_3461_2019 completed in 0:00:00.212616

 57%|█████▋    | 2461/4292 [12:56<06:47,  4.49it/s]

WY_7222_2019 completed in 0:00:00.201270

 57%|█████▋    | 2463/4292 [12:56<07:08,  4.27it/s]

WY_8566_2019 completed in 0:00:00.350141
WY_11273_2019 completed in 0:00:00.169971

 57%|█████▋    | 2464/4292 [12:56<07:55,  3.85it/s]

WY_14354_2019 completed in 0:00:00.317380

 57%|█████▋    | 2466/4292 [12:57<08:40,  3.51it/s]

WY_19156_2019 completed in 0:00:00.527293
WY_27058_2019 completed in 0:00:00.154385

 57%|█████▋    | 2467/4292 [12:57<10:02,  3.03it/s]

MT_12199_2019 completed in 0:00:00.435599

 58%|█████▊    | 2468/4292 [12:58<10:24,  2.92it/s]

WY_12199_2019 completed in 0:00:00.368567

 58%|█████▊    | 2470/4292 [12:59<11:16,  2.69it/s]

WI_13780_2019 completed in 0:00:00.719972
ME_11477_2019 completed in 0:00:00.173094

 58%|█████▊    | 2472/4292 [12:59<09:37,  3.15it/s]

AK_219_2020 completed in 0:00:00.433114
AK_599_2020 completed in 0:00:00.146486

 58%|█████▊    | 2474/4292 [13:00<07:50,  3.87it/s]

AK_3522_2020 completed in 0:00:00.242201
AK_7353_2020 completed in 0:00:00.172850

 58%|█████▊    | 2476/4292 [13:00<06:24,  4.72it/s]

AK_11824_2020 completed in 0:00:00.195966
AK_19558_2020 completed in 0:00:00.145406

 58%|█████▊    | 2477/4292 [13:00<06:24,  4.72it/s]

AR_814_2020 completed in 0:00:00.210651

 58%|█████▊    | 2479/4292 [13:01<06:17,  4.81it/s]

AR_817_2020 completed in 0:00:00.264781
AR_3093_2020 completed in 0:00:00.160834

 58%|█████▊    | 2481/4292 [13:01<06:17,  4.79it/s]

AR_5860_2020 completed in 0:00:00.221663
AR_6342_2020 completed in 0:00:00.198818

 58%|█████▊    | 2483/4292 [13:02<05:55,  5.09it/s]

AR_13718_2020 completed in 0:00:00.232810
AR_14063_2020 completed in 0:00:00.150321

 58%|█████▊    | 2484/4292 [13:02<05:44,  5.25it/s]

AR_17698_2020 completed in 0:00:00.175236

 58%|█████▊    | 2485/4292 [13:02<05:59,  5.02it/s]

AZ_176_2020 completed in 0:00:00.218141

 58%|█████▊    | 2486/4292 [13:02<06:15,  4.80it/s]

AZ_803_2020 completed in 0:00:00.228231

 58%|█████▊    | 2487/4292 [13:02<06:24,  4.69it/s]

AZ_12919_2020 completed in 0:00:00.223715

 58%|█████▊    | 2489/4292 [13:03<05:39,  5.31it/s]

AZ_16572_2020 completed in 0:00:00.208890
AZ_19189_2020 completed in 0:00:00.131633

 58%|█████▊    | 2491/4292 [13:03<05:34,  5.38it/s]

AZ_19728_2020 completed in 0:00:00.243499
AZ_21538_2020 completed in 0:00:00.139547

 58%|█████▊    | 2493/4292 [13:04<05:50,  5.14it/s]

AZ_24211_2020 completed in 0:00:00.210721
CA_4390_2020 completed in 0:00:00.196967

 58%|█████▊    | 2494/4292 [13:04<05:38,  5.32it/s]

CA_9216_2020 completed in 0:00:00.171609

 58%|█████▊    | 2495/4292 [13:04<06:00,  4.99it/s]

CA_11208_2020 completed in 0:00:00.228928

 58%|█████▊    | 2496/4292 [13:04<07:05,  4.23it/s]

CA_12745_2020 completed in 0:00:00.319986

 58%|█████▊    | 2497/4292 [13:05<10:31,  2.84it/s]

CA_14328_2020 completed in 0:00:00.619693

 58%|█████▊    | 2499/4292 [13:05<07:55,  3.77it/s]

CA_14354_2020 completed in 0:00:00.201577
CA_14534_2020 completed in 0:00:00.167272

 58%|█████▊    | 2501/4292 [13:06<06:59,  4.27it/s]

CA_16534_2020 completed in 0:00:00.211702
CA_16609_2020 completed in 0:00:00.197059

 58%|█████▊    | 2502/4292 [13:06<06:25,  4.65it/s]

CA_16655_2020 completed in 0:00:00.170426

 58%|█████▊    | 2503/4292 [13:06<06:48,  4.37it/s]

CA_17609_2020 completed in 0:00:00.258939

 58%|█████▊    | 2505/4292 [13:07<06:36,  4.51it/s]

CA_17612_2020 completed in 0:00:00.276209
CA_18260_2020 completed in 0:00:00.170212

 58%|█████▊    | 2507/4292 [13:07<05:46,  5.15it/s]

CA_19281_2020 completed in 0:00:00.145613
CO_3989_2020 completed in 0:00:00.180940

 58%|█████▊    | 2509/4292 [13:07<05:22,  5.53it/s]

CO_6604_2020 completed in 0:00:00.168409
CO_9336_2020 completed in 0:00:00.164899

 59%|█████▊    | 2511/4292 [13:08<05:32,  5.36it/s]

CO_12866_2020 completed in 0:00:00.203290
CO_15257_2020 completed in 0:00:00.182804

 59%|█████▊    | 2512/4292 [13:08<06:41,  4.44it/s]

CO_15466_2020 completed in 0:00:00.311867

 59%|█████▊    | 2513/4292 [13:08<07:16,  4.07it/s]

CO_16603_2020 completed in 0:00:00.286591

 59%|█████▊    | 2514/4292 [13:09<08:18,  3.57it/s]

CO_19499_2020 completed in 0:00:00.358701

 59%|█████▊    | 2515/4292 [13:09<07:51,  3.77it/s]

CO_27058_2020 completed in 0:00:00.228102

 59%|█████▊    | 2516/4292 [13:09<07:31,  3.94it/s]

CO_56146_2020 completed in 0:00:00.225877

 59%|█████▊    | 2518/4292 [13:10<08:39,  3.41it/s]

CT_4176_2020 completed in 0:00:00.521585
CT_7716_2020 completed in 0:00:00.195474

 59%|█████▊    | 2520/4292 [13:10<06:55,  4.27it/s]

CT_19497_2020 completed in 0:00:00.179089
CT_20038_2020 completed in 0:00:00.176204

 59%|█████▊    | 2521/4292 [13:10<07:45,  3.80it/s]

DC_15270_2020 completed in 0:00:00.328861

 59%|█████▉    | 2523/4292 [13:11<10:07,  2.91it/s]

DE_5027_2020 completed in 0:00:00.789515
DE_5070_2020 completed in 0:00:00.160277

 59%|█████▉    | 2525/4292 [13:12<07:47,  3.78it/s]

DE_5335_2020 completed in 0:00:00.191537
DE_13519_2020 completed in 0:00:00.186357

 59%|█████▉    | 2526/4292 [13:12<09:43,  3.02it/s]

FL_6452_2020 completed in 0:00:00.483477

 59%|█████▉    | 2527/4292 [13:13<09:52,  2.98it/s]

FL_6455_2020 completed in 0:00:00.346692

 59%|█████▉    | 2528/4292 [13:13<09:42,  3.03it/s]

FL_6457_2020 completed in 0:00:00.315911

 59%|█████▉    | 2530/4292 [13:13<07:36,  3.86it/s]

FL_7801_2020 completed in 0:00:00.222611
FL_9617_2020 completed in 0:00:00.167388

 59%|█████▉    | 2531/4292 [13:14<09:39,  3.04it/s]

FL_18454_2020 completed in 0:00:00.490485

 59%|█████▉    | 2532/4292 [13:14<09:22,  3.13it/s]

GA_3916_2020 completed in 0:00:00.296993

 59%|█████▉    | 2533/4292 [13:14<09:04,  3.23it/s]

GA_9601_2020 completed in 0:00:00.284694

 59%|█████▉    | 2535/4292 [13:15<07:28,  3.92it/s]

HI_8287_2020 completed in 0:00:00.213848
HI_10071_2020 completed in 0:00:00.194230

 59%|█████▉    | 2536/4292 [13:15<08:51,  3.30it/s]

HI_11843_2020 completed in 0:00:00.412158

 59%|█████▉    | 2537/4292 [13:16<13:07,  2.23it/s]

HI_19547_2020 completed in 0:00:00.789319

 59%|█████▉    | 2538/4292 [13:16<11:47,  2.48it/s]

IA_9417_2020 completed in 0:00:00.295809

 59%|█████▉    | 2540/4292 [13:17<09:06,  3.21it/s]

IA_12341_2020 completed in 0:00:00.314270
ID_9187_2020 completed in 0:00:00.159590

 59%|█████▉    | 2542/4292 [13:17<07:16,  4.01it/s]

ID_9191_2020 completed in 0:00:00.245341
ID_10454_2020 completed in 0:00:00.148966

 59%|█████▉    | 2544/4292 [13:18<06:24,  4.55it/s]

ID_11273_2020 completed in 0:00:00.188963
ID_14354_2020 completed in 0:00:00.191404

 59%|█████▉    | 2546/4292 [13:18<06:17,  4.62it/s]

ID_20169_2020 completed in 0:00:00.258785
IL_4110_2020 completed in 0:00:00.179198

 59%|█████▉    | 2547/4292 [13:18<07:27,  3.90it/s]

IL_12341_2020 completed in 0:00:00.350154

 59%|█████▉    | 2548/4292 [13:19<07:11,  4.04it/s]

IL_13032_2020 completed in 0:00:00.224377

 59%|█████▉    | 2550/4292 [13:19<06:31,  4.45it/s]

IL_56697_2020 completed in 0:00:00.296999
IN_9273_2020 completed in 0:00:00.135569

 59%|█████▉    | 2551/4292 [13:19<07:09,  4.06it/s]

IN_9324_2020 completed in 0:00:00.295951

 59%|█████▉    | 2552/4292 [13:19<06:52,  4.21it/s]

IN_13756_2020 completed in 0:00:00.212012

 59%|█████▉    | 2553/4292 [13:20<07:53,  3.68it/s]

IN_15470_2020 completed in 0:00:00.352304

 60%|█████▉    | 2554/4292 [13:20<07:20,  3.95it/s]

IN_17633_2020 completed in 0:00:00.204444

 60%|█████▉    | 2555/4292 [13:20<07:58,  3.63it/s]

KS_5860_2020 completed in 0:00:00.325271

 60%|█████▉    | 2556/4292 [13:21<09:04,  3.19it/s]

KS_9996_2020 completed in 0:00:00.400349

 60%|█████▉    | 2557/4292 [13:21<08:26,  3.43it/s]

KS_10000_2020 completed in 0:00:00.239627

 60%|█████▉    | 2558/4292 [13:21<07:50,  3.68it/s]

KS_10005_2020 completed in 0:00:00.222267

 60%|█████▉    | 2559/4292 [13:21<07:29,  3.85it/s]

KS_22500_2020 completed in 0:00:00.230459

 60%|█████▉    | 2560/4292 [13:22<08:01,  3.60it/s]

KY_9964_2020 completed in 0:00:00.320275

 60%|█████▉    | 2561/4292 [13:22<07:58,  3.62it/s]

KY_10171_2020 completed in 0:00:00.270807

 60%|█████▉    | 2562/4292 [13:22<08:26,  3.42it/s]

KY_11249_2020 completed in 0:00:00.330654

 60%|█████▉    | 2564/4292 [13:23<07:51,  3.66it/s]

KY_17564_2020 completed in 0:00:00.355299
KY_19446_2020 completed in 0:00:00.181615

 60%|█████▉    | 2565/4292 [13:23<08:04,  3.56it/s]

KY_22053_2020 completed in 0:00:00.297575

 60%|█████▉    | 2567/4292 [13:24<11:50,  2.43it/s]

KY_49998_2020 completed in 0:00:01.026515
LA_3265_2020 completed in 0:00:00.194074

 60%|█████▉    | 2569/4292 [13:25<09:05,  3.16it/s]

LA_11241_2020 completed in 0:00:00.300602
LA_13478_2020 completed in 0:00:00.167578

 60%|█████▉    | 2570/4292 [13:25<08:35,  3.34it/s]

LA_17698_2020 completed in 0:00:00.259255

 60%|█████▉    | 2571/4292 [13:25<08:19,  3.45it/s]

MA_6374_2020 completed in 0:00:00.266368

 60%|█████▉    | 2572/4292 [13:26<07:36,  3.77it/s]

MA_8774_2020 completed in 0:00:00.206698

 60%|█████▉    | 2573/4292 [13:26<07:27,  3.85it/s]

MA_11804_2020 completed in 0:00:00.244884

 60%|█████▉    | 2575/4292 [13:26<06:29,  4.41it/s]

MA_13206_2020 completed in 0:00:00.229977
MA_15748_2020 completed in 0:00:00.168086

 60%|██████    | 2576/4292 [13:27<06:22,  4.49it/s]

MA_54913_2020 completed in 0:00:00.212870

 60%|██████    | 2578/4292 [13:27<06:19,  4.51it/s]

MD_1167_2020 completed in 0:00:00.249255
MD_5027_2020 completed in 0:00:00.199027

 60%|██████    | 2580/4292 [13:28<07:35,  3.76it/s]

MD_15263_2020 completed in 0:00:00.480735
MD_15270_2020 completed in 0:00:00.187580

 60%|██████    | 2582/4292 [13:28<06:56,  4.10it/s]

MD_17637_2020 completed in 0:00:00.251544
ME_1179_2020 completed in 0:00:00.200073

 60%|██████    | 2584/4292 [13:29<06:16,  4.53it/s]

ME_3266_2020 completed in 0:00:00.196819
ME_5609_2020 completed in 0:00:00.197709

 60%|██████    | 2586/4292 [13:29<06:13,  4.57it/s]

MI_392_2020 completed in 0:00:00.266586
MI_3828_2020 completed in 0:00:00.181555

 60%|██████    | 2587/4292 [13:29<06:16,  4.52it/s]

MI_4254_2020 completed in 0:00:00.224673
MI_5109_2020 completed in 0:00:00.200463

 60%|██████    | 2589/4292 [13:30<06:24,  4.42it/s]

MI_9324_2020 completed in 0:00:00.250506

 60%|██████    | 2591/4292 [13:30<06:50,  4.14it/s]

MI_10704_2020 completed in 0:00:00.342178
MI_19578_2020 completed in 0:00:00.194784

 60%|██████    | 2592/4292 [13:30<06:15,  4.53it/s]

MN_689_2020 completed in 0:00:00.171357

 60%|██████    | 2594/4292 [13:31<06:16,  4.51it/s]

MN_5574_2020 completed in 0:00:00.318877
MN_10596_2020 completed in 0:00:00.153606

 60%|██████    | 2595/4292 [13:31<07:19,  3.86it/s]

MN_12647_2020 completed in 0:00:00.344938

 60%|██████    | 2596/4292 [13:31<07:21,  3.84it/s]

MN_13781_2020 completed in 0:00:00.262177

 61%|██████    | 2597/4292 [13:32<09:52,  2.86it/s]

MN_14232_2020 completed in 0:00:00.556977

 61%|██████    | 2599/4292 [13:32<07:49,  3.60it/s]

MN_16181_2020 completed in 0:00:00.223423
MN_17267_2020 completed in 0:00:00.193619

 61%|██████    | 2601/4292 [13:33<06:38,  4.24it/s]

MN_20996_2020 completed in 0:00:00.236343
MN_25177_2020 completed in 0:00:00.165623

 61%|██████    | 2602/4292 [13:33<06:17,  4.48it/s]

MO_4675_2020 completed in 0:00:00.192225

 61%|██████    | 2604/4292 [13:33<06:07,  4.60it/s]

MO_5860_2020 completed in 0:00:00.289022
MO_9231_2020 completed in 0:00:00.156477

 61%|██████    | 2606/4292 [13:34<06:57,  4.04it/s]

MO_10000_2020 completed in 0:00:00.394690
MO_12698_2020 completed in 0:00:00.190714

 61%|██████    | 2607/4292 [13:34<06:28,  4.34it/s]

MO_17833_2020 completed in 0:00:00.188672

 61%|██████    | 2608/4292 [13:34<06:37,  4.24it/s]

MO_19436_2020 completed in 0:00:00.247471

 61%|██████    | 2609/4292 [13:35<06:37,  4.24it/s]

MS_3841_2020 completed in 0:00:00.235850

 61%|██████    | 2610/4292 [13:35<06:37,  4.23it/s]

MS_12685_2020 completed in 0:00:00.236482

 61%|██████    | 2611/4292 [13:35<06:51,  4.09it/s]

MS_12686_2020 completed in 0:00:00.262559

 61%|██████    | 2613/4292 [13:36<07:37,  3.67it/s]

MS_17647_2020 completed in 0:00:00.461869
MT_6395_2020 completed in 0:00:00.183737

 61%|██████    | 2615/4292 [13:36<06:23,  4.38it/s]

MT_12199_2020 completed in 0:00:00.194519
MT_12692_2020 completed in 0:00:00.178810

 61%|██████    | 2616/4292 [13:36<06:03,  4.61it/s]

MT_12825_2020 completed in 0:00:00.189910

 61%|██████    | 2618/4292 [13:37<05:57,  4.69it/s]

MT_19603_2020 completed in 0:00:00.283566
MT_20997_2020 completed in 0:00:00.156540

 61%|██████    | 2619/4292 [13:37<06:05,  4.57it/s]

NC_3046_2020 completed in 0:00:00.230194

 61%|██████    | 2621/4292 [13:38<05:53,  4.73it/s]

NC_5416_2020 completed in 0:00:00.264533
NC_9837_2020 completed in 0:00:00.160689

 61%|██████    | 2622/4292 [13:38<05:44,  4.85it/s]

NC_16496_2020 completed in 0:00:00.194102

 61%|██████    | 2624/4292 [13:38<05:27,  5.10it/s]

NC_19876_2020 completed in 0:00:00.222095
NC_24889_2020 completed in 0:00:00.159803

 61%|██████    | 2625/4292 [13:38<05:30,  5.05it/s]

ND_12090_2020 completed in 0:00:00.201531

 61%|██████    | 2627/4292 [13:39<05:19,  5.21it/s]

ND_12301_2020 completed in 0:00:00.207574
ND_14232_2020 completed in 0:00:00.168648

 61%|██████    | 2628/4292 [13:39<05:22,  5.16it/s]

ND_19790_2020 completed in 0:00:00.197174

 61%|██████▏   | 2630/4292 [13:39<05:46,  4.80it/s]

ND_24949_2020 completed in 0:00:00.290830
NE_4373_2020 completed in 0:00:00.173216

 61%|██████▏   | 2632/4292 [13:40<05:24,  5.11it/s]

NE_4911_2020 completed in 0:00:00.163993
NE_6779_2020 completed in 0:00:00.196160

 61%|██████▏   | 2634/4292 [13:40<05:05,  5.43it/s]

NE_11018_2020 completed in 0:00:00.193544
NE_11251_2020 completed in 0:00:00.157568

 61%|██████▏   | 2636/4292 [13:40<05:10,  5.33it/s]

NE_12539_2020 completed in 0:00:00.192289
NE_13337_2020 completed in 0:00:00.188648

 61%|██████▏   | 2638/4292 [13:41<06:14,  4.42it/s]

NE_13664_2020 completed in 0:00:00.379448
NE_14127_2020 completed in 0:00:00.180971

 62%|██████▏   | 2640/4292 [13:41<05:36,  4.91it/s]

NE_17642_2020 completed in 0:00:00.210059
NE_27058_2020 completed in 0:00:00.160264

 62%|██████▏   | 2642/4292 [13:42<05:04,  5.42it/s]

NE_40606_2020 completed in 0:00:00.173787
NH_13441_2020 completed in 0:00:00.159567

 62%|██████▏   | 2643/4292 [13:42<06:12,  4.43it/s]

NH_15472_2020 completed in 0:00:00.320906

 62%|██████▏   | 2645/4292 [13:42<05:43,  4.79it/s]

NJ_963_2020 completed in 0:00:00.228236
NJ_9726_2020 completed in 0:00:00.165928

 62%|██████▏   | 2646/4292 [13:43<05:14,  5.24it/s]

NJ_15477_2020 completed in 0:00:00.148676

 62%|██████▏   | 2647/4292 [13:43<05:33,  4.93it/s]

NJ_16213_2020 completed in 0:00:00.229208

 62%|██████▏   | 2648/4292 [13:43<05:36,  4.89it/s]

NM_3287_2020 completed in 0:00:00.207002

 62%|██████▏   | 2650/4292 [13:43<05:17,  5.18it/s]

NM_5701_2020 completed in 0:00:00.229453
NM_6204_2020 completed in 0:00:00.146646

 62%|██████▏   | 2651/4292 [13:44<07:32,  3.63it/s]

NM_11204_2020 completed in 0:00:00.467275

 62%|██████▏   | 2653/4292 [13:45<07:41,  3.55it/s]

NM_15473_2020 completed in 0:00:00.449456
NM_17718_2020 completed in 0:00:00.171275

 62%|██████▏   | 2654/4292 [13:45<07:08,  3.82it/s]

NV_2008_2020 completed in 0:00:00.213581

 62%|██████▏   | 2656/4292 [13:45<06:21,  4.29it/s]

NV_13073_2020 completed in 0:00:00.227942
NV_13407_2020 completed in 0:00:00.188309

 62%|██████▏   | 2658/4292 [13:46<05:46,  4.72it/s]

NV_17166_2020 completed in 0:00:00.234095
NV_19840_2020 completed in 0:00:00.159260

 62%|██████▏   | 2659/4292 [13:46<05:45,  4.73it/s]

NY_3249_2020 completed in 0:00:00.209455

 62%|██████▏   | 2660/4292 [13:46<05:48,  4.68it/s]

NY_4226_2020 completed in 0:00:00.217802

 62%|██████▏   | 2661/4292 [13:46<05:46,  4.70it/s]

NY_11171_2020 completed in 0:00:00.208632

 62%|██████▏   | 2662/4292 [13:46<05:57,  4.56it/s]

NY_13511_2020 completed in 0:00:00.229306

 62%|██████▏   | 2663/4292 [13:47<07:43,  3.52it/s]

NY_13573_2020 completed in 0:00:00.434331

 62%|██████▏   | 2664/4292 [13:47<09:29,  2.86it/s]

NY_14154_2020 completed in 0:00:00.501776

 62%|██████▏   | 2665/4292 [13:48<09:03,  2.99it/s]

NY_14711_2020 completed in 0:00:00.295776

 62%|██████▏   | 2666/4292 [13:48<08:03,  3.36it/s]

NY_16183_2020 completed in 0:00:00.210278

 62%|██████▏   | 2667/4292 [13:48<08:10,  3.31it/s]

OH_3542_2020 completed in 0:00:00.311878

 62%|██████▏   | 2668/4292 [13:48<07:35,  3.56it/s]

OH_3755_2020 completed in 0:00:00.230164

 62%|██████▏   | 2669/4292 [13:49<07:02,  3.84it/s]

OH_4922_2020 completed in 0:00:00.212066

 62%|██████▏   | 2670/4292 [13:49<06:42,  4.03it/s]

OH_13998_2020 completed in 0:00:00.216239

 62%|██████▏   | 2671/4292 [13:50<12:06,  2.23it/s]

OH_14006_2020 completed in 0:00:00.914792

 62%|██████▏   | 2672/4292 [13:50<11:00,  2.45it/s]

OH_18997_2020 completed in 0:00:00.312868

 62%|██████▏   | 2674/4292 [13:51<08:27,  3.19it/s]

OK_5860_2020 completed in 0:00:00.327808
OK_13734_2020 completed in 0:00:00.148772

 62%|██████▏   | 2675/4292 [13:51<08:21,  3.23it/s]

OK_14062_2020 completed in 0:00:00.300274

 62%|██████▏   | 2676/4292 [13:51<08:00,  3.36it/s]

OK_14063_2020 completed in 0:00:00.266910

 62%|██████▏   | 2677/4292 [13:51<08:40,  3.10it/s]

OK_15474_2020 completed in 0:00:00.379677

 62%|██████▏   | 2678/4292 [13:52<08:04,  3.33it/s]

OK_19785_2020 completed in 0:00:00.247102

 62%|██████▏   | 2679/4292 [13:52<08:34,  3.14it/s]

OR_6022_2020 completed in 0:00:00.361490
OR_9191_2020 completed in 0:00:00.203557

 62%|██████▏   | 2682/4292 [13:53<06:48,  3.94it/s]

OR_14354_2020 completed in 0:00:00.312036
OR_15248_2020 completed in 0:00:00.160735

 63%|██████▎   | 2683/4292 [13:54<12:29,  2.15it/s]

OR_18260_2020 completed in 0:00:00.959391

 63%|██████▎   | 2684/4292 [13:54<10:44,  2.50it/s]

OR_28541_2020 completed in 0:00:00.248714
OR_40437_2020 completed in 0:00:00.200592

 63%|██████▎   | 2686/4292 [13:54<08:38,  3.10it/s]

PA_3597_2020 completed in 0:00:00.278228

 63%|██████▎   | 2687/4292 [13:55<13:00,  2.06it/s]

PA_5487_2020 completed in 0:00:00.868533

 63%|██████▎   | 2688/4292 [13:56<12:05,  2.21it/s]

PA_12390_2020 completed in 0:00:00.371694

 63%|██████▎   | 2689/4292 [13:56<10:51,  2.46it/s]

PA_14711_2020 completed in 0:00:00.297778

 63%|██████▎   | 2690/4292 [13:56<10:50,  2.46it/s]

PA_14715_2020 completed in 0:00:00.404835

 63%|██████▎   | 2691/4292 [13:57<09:13,  2.89it/s]

PA_14716_2020 completed in 0:00:00.204079

 63%|██████▎   | 2693/4292 [13:57<08:35,  3.10it/s]

PA_14940_2020 completed in 0:00:00.459013
PA_15045_2020 completed in 0:00:00.184006

 63%|██████▎   | 2694/4292 [13:57<07:37,  3.49it/s]

PA_19390_2020 completed in 0:00:00.200279

 63%|██████▎   | 2695/4292 [13:58<06:59,  3.81it/s]

PA_20334_2020 completed in 0:00:00.205724

 63%|██████▎   | 2697/4292 [13:58<06:14,  4.26it/s]

PA_20387_2020 completed in 0:00:00.266029
RI_1857_2020 completed in 0:00:00.163633

 63%|██████▎   | 2699/4292 [13:58<05:30,  4.82it/s]

RI_13214_2020 completed in 0:00:00.170598
RI_14537_2020 completed in 0:00:00.184783

 63%|██████▎   | 2700/4292 [13:59<05:51,  4.53it/s]

SC_1613_2020 completed in 0:00:00.249493

 63%|██████▎   | 2701/4292 [13:59<05:54,  4.48it/s]

SC_3046_2020 completed in 0:00:00.223667

 63%|██████▎   | 2702/4292 [13:59<06:30,  4.07it/s]

SC_5416_2020 completed in 0:00:00.297772

 63%|██████▎   | 2703/4292 [13:59<06:28,  4.09it/s]

SC_14398_2020 completed in 0:00:00.241000

 63%|██████▎   | 2704/4292 [14:00<06:50,  3.87it/s]

SC_17539_2020 completed in 0:00:00.289640

 63%|██████▎   | 2706/4292 [14:00<05:55,  4.46it/s]

SC_17543_2020 completed in 0:00:00.276328
SD_1769_2020 completed in 0:00:00.129450

 63%|██████▎   | 2708/4292 [14:01<05:27,  4.84it/s]

SD_14232_2020 completed in 0:00:00.207578
SD_17267_2020 completed in 0:00:00.174751

 63%|██████▎   | 2709/4292 [14:01<05:09,  5.12it/s]

SD_19293_2020 completed in 0:00:00.168014

 63%|██████▎   | 2710/4292 [14:01<05:23,  4.89it/s]

SD_20401_2020 completed in 0:00:00.224353

 63%|██████▎   | 2711/4292 [14:01<05:34,  4.73it/s]

TN_10331_2020 completed in 0:00:00.226810

 63%|██████▎   | 2713/4292 [14:02<06:22,  4.13it/s]

TX_5701_2020 completed in 0:00:00.428755
TX_16604_2020 completed in 0:00:00.160907

 63%|██████▎   | 2715/4292 [14:02<05:40,  4.64it/s]

TX_55937_2020 completed in 0:00:00.206300
UT_2010_2020 completed in 0:00:00.177237

 63%|██████▎   | 2717/4292 [14:03<05:02,  5.21it/s]

UT_11135_2020 completed in 0:00:00.200017
UT_12866_2020 completed in 0:00:00.145456

 63%|██████▎   | 2719/4292 [14:03<05:25,  4.83it/s]

UT_14354_2020 completed in 0:00:00.299877
UT_15444_2020 completed in 0:00:00.165841

 63%|██████▎   | 2721/4292 [14:03<05:08,  5.09it/s]

UT_17845_2020 completed in 0:00:00.193670
UT_17874_2020 completed in 0:00:00.178918

 63%|██████▎   | 2722/4292 [14:04<05:06,  5.12it/s]

UT_18206_2020 completed in 0:00:00.192342

 63%|██████▎   | 2724/4292 [14:04<05:12,  5.02it/s]

VA_84_2020 completed in 0:00:00.249991
VA_733_2020 completed in 0:00:00.168631

 64%|██████▎   | 2726/4292 [14:04<05:45,  4.53it/s]

VA_10171_2020 completed in 0:00:00.337402
VA_17066_2020 completed in 0:00:00.171967

 64%|██████▎   | 2727/4292 [14:05<06:49,  3.82it/s]

VA_19876_2020 completed in 0:00:00.356276

 64%|██████▎   | 2729/4292 [14:05<06:22,  4.09it/s]

VA_19882_2020 completed in 0:00:00.316125
VA_40228_2020 completed in 0:00:00.165173

 64%|██████▎   | 2730/4292 [14:06<06:03,  4.29it/s]

VT_2548_2020 completed in 0:00:00.204924

 64%|██████▎   | 2731/4292 [14:06<06:56,  3.75it/s]

VT_7601_2020 completed in 0:00:00.345533

 64%|██████▎   | 2733/4292 [14:06<06:04,  4.27it/s]

VT_19791_2020 completed in 0:00:00.207189
WA_3660_2020 completed in 0:00:00.196730

 64%|██████▎   | 2734/4292 [14:06<05:40,  4.57it/s]

WA_14354_2020 completed in 0:00:00.182288
WA_15500_2020 completed in 0:00:00.202071

 64%|██████▍   | 2737/4292 [14:07<04:47,  5.41it/s]

WA_16868_2020 completed in 0:00:00.162004
WA_17470_2020 completed in 0:00:00.150975

 64%|██████▍   | 2738/4292 [14:07<04:44,  5.46it/s]

WA_18429_2020 completed in 0:00:00.177965

 64%|██████▍   | 2740/4292 [14:08<04:56,  5.23it/s]

WA_20169_2020 completed in 0:00:00.247264
WI_4715_2020 completed in 0:00:00.164079

 64%|██████▍   | 2741/4292 [14:08<04:51,  5.32it/s]

WI_5574_2020 completed in 0:00:00.179606

 64%|██████▍   | 2743/4292 [14:08<05:01,  5.14it/s]

WI_11479_2020 completed in 0:00:00.213989
WI_13697_2020 completed in 0:00:00.190037

 64%|██████▍   | 2745/4292 [14:09<04:41,  5.49it/s]

WI_13780_2020 completed in 0:00:00.190609
WI_13815_2020 completed in 0:00:00.153867

 64%|██████▍   | 2747/4292 [14:09<04:40,  5.50it/s]

WI_20847_2020 completed in 0:00:00.198131
WI_20856_2020 completed in 0:00:00.168081

 64%|██████▍   | 2748/4292 [14:09<04:56,  5.21it/s]

WI_20860_2020 completed in 0:00:00.214706
WV_733_2020 completed in 0:00:00.201990

 64%|██████▍   | 2751/4292 [14:10<05:06,  5.03it/s]

WV_12796_2020 completed in 0:00:00.231824
WV_15263_2020 completed in 0:00:00.179827

 64%|██████▍   | 2753/4292 [14:10<04:36,  5.57it/s]

WV_20521_2020 completed in 0:00:00.149913
WY_3461_2020 completed in 0:00:00.167039

 64%|██████▍   | 2755/4292 [14:10<04:45,  5.38it/s]

WY_7222_2020 completed in 0:00:00.204686
WY_8566_2020 completed in 0:00:00.182339

 64%|██████▍   | 2756/4292 [14:11<04:44,  5.40it/s]

WY_11273_2020 completed in 0:00:00.181936
WY_12199_2020 completed in 0:00:00.201567

 64%|██████▍   | 2759/4292 [14:11<05:30,  4.64it/s]

WY_14354_2020 completed in 0:00:00.292636
WY_19156_2020 completed in 0:00:00.197634

 64%|██████▍   | 2761/4292 [14:12<04:37,  5.53it/s]

WY_27058_2020 completed in 0:00:00.153294
NH_24590_2020 completed in 0:00:00.141970

 64%|██████▍   | 2763/4292 [14:12<03:55,  6.50it/s]

Failed for utility AK_219_2021: 'properties'
Failed for utility AK_3522_2021: 'properties'

 64%|██████▍   | 2765/4292 [14:12<03:47,  6.71it/s]

Failed for utility AK_7353_2021: 'properties'
Failed for utility AK_11824_2021: 'properties'

 64%|██████▍   | 2767/4292 [14:12<03:43,  6.83it/s]

Failed for utility AK_19558_2021: 'properties'
Failed for utility AR_814_2021: 'properties'

 65%|██████▍   | 2769/4292 [14:13<03:41,  6.88it/s]

Failed for utility AR_817_2021: 'properties'
Failed for utility AR_3093_2021: 'properties'

 65%|██████▍   | 2771/4292 [14:13<03:33,  7.14it/s]

Failed for utility AR_5860_2021: 'properties'
Failed for utility AR_6342_2021: 'properties'

 65%|██████▍   | 2773/4292 [14:13<03:07,  8.09it/s]

Failed for utility AR_13718_2021: 'properties'
Failed for utility AR_14063_2021: 'properties'

 65%|██████▍   | 2775/4292 [14:13<03:01,  8.36it/s]

Failed for utility AR_17698_2021: 'properties'
Failed for utility AZ_176_2021: 'properties'

 65%|██████▍   | 2776/4292 [14:14<03:16,  7.70it/s]

Failed for utility AZ_803_2021: 'properties'
Failed for utility AZ_12919_2021: 'properties'

 65%|██████▍   | 2779/4292 [14:14<03:00,  8.39it/s]

Failed for utility AZ_16572_2021: 'properties'
Failed for utility AZ_19189_2021: 'properties'

 65%|██████▍   | 2781/4292 [14:14<03:06,  8.12it/s]

Failed for utility AZ_19728_2021: 'properties'
Failed for utility AZ_21538_2021: 'properties'

 65%|██████▍   | 2783/4292 [14:14<03:05,  8.14it/s]

Failed for utility AZ_24211_2021: 'properties'
Failed for utility CA_4390_2021: 'properties'

 65%|██████▍   | 2785/4292 [14:15<03:31,  7.11it/s]

Failed for utility CA_9216_2021: 'properties'
Failed for utility CA_11208_2021: 'properties'

 65%|██████▍   | 2786/4292 [14:15<03:30,  7.14it/s]

Failed for utility CA_12745_2021: 'properties'

 65%|██████▍   | 2788/4292 [14:15<03:53,  6.44it/s]

Failed for utility CA_14328_2021: 'properties'
Failed for utility CA_14354_2021: 'properties'

 65%|██████▌   | 2790/4292 [14:16<03:42,  6.74it/s]

Failed for utility CA_14534_2021: 'properties'
Failed for utility CA_16534_2021: 'properties'

 65%|██████▌   | 2792/4292 [14:16<03:23,  7.38it/s]

Failed for utility CA_16609_2021: 'properties'
Failed for utility CA_16655_2021: 'properties'

 65%|██████▌   | 2793/4292 [14:16<04:00,  6.23it/s]

Failed for utility CA_17609_2021: 'properties'
Failed for utility CA_17612_2021: 'properties'

 65%|██████▌   | 2796/4292 [14:16<03:43,  6.70it/s]

Failed for utility CA_18260_2021: 'properties'
Failed for utility CA_19281_2021: 'properties'

 65%|██████▌   | 2798/4292 [14:17<03:23,  7.34it/s]

Failed for utility CO_3989_2021: 'properties'
Failed for utility CO_6604_2021: 'properties'

 65%|██████▌   | 2799/4292 [14:17<03:22,  7.37it/s]

Failed for utility CO_9336_2021: 'properties'
Failed for utility CO_12866_2021: 'properties'

 65%|██████▌   | 2802/4292 [14:17<03:12,  7.74it/s]

Failed for utility CO_15257_2021: 'properties'
Failed for utility CO_15466_2021: 'properties'

 65%|██████▌   | 2804/4292 [14:17<03:18,  7.51it/s]

Failed for utility CO_16603_2021: 'properties'
Failed for utility CO_19499_2021: 'properties'

 65%|██████▌   | 2806/4292 [14:18<03:15,  7.60it/s]

Failed for utility CO_27058_2021: 'properties'
Failed for utility CO_56146_2021: 'properties'

 65%|██████▌   | 2808/4292 [14:18<03:25,  7.24it/s]

Failed for utility CT_4176_2021: 'properties'
Failed for utility CT_7716_2021: 'properties'

 65%|██████▌   | 2810/4292 [14:18<03:22,  7.33it/s]

Failed for utility CT_19497_2021: 'properties'
Failed for utility CT_20038_2021: 'properties'

 66%|██████▌   | 2812/4292 [14:19<03:02,  8.13it/s]

Failed for utility DC_15270_2021: 'properties'
Failed for utility DE_5027_2021: 'properties'

 66%|██████▌   | 2814/4292 [14:19<03:26,  7.15it/s]

Failed for utility DE_5070_2021: 'properties'
Failed for utility DE_5335_2021: 'properties'

 66%|██████▌   | 2816/4292 [14:19<03:24,  7.22it/s]

Failed for utility DE_13519_2021: 'properties'
Failed for utility FL_6452_2021: 'properties'

 66%|██████▌   | 2818/4292 [14:19<03:23,  7.26it/s]

Failed for utility FL_6455_2021: 'properties'
Failed for utility FL_6457_2021: 'properties'

 66%|██████▌   | 2820/4292 [14:20<03:23,  7.25it/s]

Failed for utility FL_7801_2021: 'properties'
Failed for utility FL_9617_2021: 'properties'

 66%|██████▌   | 2822/4292 [14:20<03:18,  7.41it/s]

Failed for utility FL_18454_2021: 'properties'
Failed for utility GA_3916_2021: 'properties'

 66%|██████▌   | 2824/4292 [14:20<03:04,  7.97it/s]

Failed for utility GA_9601_2021: 'properties'
Failed for utility HI_8287_2021: 'properties'

 66%|██████▌   | 2826/4292 [14:20<02:55,  8.33it/s]

Failed for utility HI_10071_2021: 'properties'
Failed for utility HI_11843_2021: 'properties'

 66%|██████▌   | 2828/4292 [14:21<03:18,  7.39it/s]

Failed for utility HI_19547_2021: 'properties'
Failed for utility IA_9417_2021: 'properties'

 66%|██████▌   | 2830/4292 [14:21<03:21,  7.27it/s]

Failed for utility IA_12341_2021: 'properties'
Failed for utility ID_9187_2021: 'properties'

 66%|██████▌   | 2832/4292 [14:21<03:33,  6.84it/s]

Failed for utility ID_9191_2021: 'properties'
Failed for utility ID_10454_2021: 'properties'

 66%|██████▌   | 2833/4292 [14:21<03:21,  7.23it/s]

Failed for utility ID_11273_2021: 'properties'

 66%|██████▌   | 2835/4292 [14:22<04:08,  5.87it/s]

Failed for utility ID_14354_2021: 'properties'
Failed for utility ID_20169_2021: 'properties'

 66%|██████▌   | 2837/4292 [14:22<03:34,  6.80it/s]

Failed for utility IL_4110_2021: 'properties'
Failed for utility IL_12341_2021: 'properties'

 66%|██████▌   | 2839/4292 [14:22<03:32,  6.82it/s]

Failed for utility IL_13032_2021: 'properties'
Failed for utility IL_56697_2021: 'properties'

 66%|██████▌   | 2841/4292 [14:23<03:14,  7.48it/s]

Failed for utility IN_9273_2021: 'properties'
Failed for utility IN_9324_2021: 'properties'

 66%|██████▌   | 2843/4292 [14:23<03:36,  6.69it/s]

Failed for utility IN_13756_2021: 'properties'
Failed for utility IN_15470_2021: 'properties'

 66%|██████▋   | 2845/4292 [14:23<03:32,  6.80it/s]

Failed for utility IN_17633_2021: 'properties'
Failed for utility KS_5860_2021: 'properties'

 66%|██████▋   | 2847/4292 [14:23<03:11,  7.54it/s]

Failed for utility KS_9996_2021: 'properties'
Failed for utility KS_10000_2021: 'properties'

 66%|██████▋   | 2849/4292 [14:24<03:29,  6.90it/s]

Failed for utility KS_10005_2021: 'properties'
Failed for utility KS_22500_2021: 'properties'

 66%|██████▋   | 2851/4292 [14:24<03:35,  6.69it/s]

Failed for utility KY_9964_2021: 'properties'
Failed for utility KY_10171_2021: 'properties'

 66%|██████▋   | 2853/4292 [14:24<03:09,  7.61it/s]

Failed for utility KY_11249_2021: 'properties'
Failed for utility KY_17564_2021: 'properties'

 67%|██████▋   | 2855/4292 [14:24<03:02,  7.89it/s]

Failed for utility KY_19446_2021: 'properties'
Failed for utility KY_22053_2021: 'properties'

 67%|██████▋   | 2857/4292 [14:25<02:56,  8.11it/s]

Failed for utility KY_49998_2021: 'properties'
Failed for utility LA_3265_2021: 'properties'

 67%|██████▋   | 2859/4292 [14:25<03:07,  7.66it/s]

Failed for utility LA_11241_2021: 'properties'
Failed for utility LA_13478_2021: 'properties'

 67%|██████▋   | 2861/4292 [14:25<03:22,  7.05it/s]

Failed for utility LA_17698_2021: 'properties'
Failed for utility MA_6374_2021: 'properties'

 67%|██████▋   | 2863/4292 [14:26<02:56,  8.08it/s]

Failed for utility MA_8774_2021: 'properties'
Failed for utility MA_11804_2021: 'properties'

 67%|██████▋   | 2865/4292 [14:26<02:55,  8.11it/s]

Failed for utility MA_13206_2021: 'properties'
Failed for utility MA_15748_2021: 'properties'

 67%|██████▋   | 2867/4292 [14:26<02:48,  8.47it/s]

Failed for utility MA_54913_2021: 'properties'
Failed for utility MD_1167_2021: 'properties'

 67%|██████▋   | 2869/4292 [14:26<02:44,  8.64it/s]

Failed for utility MD_5027_2021: 'properties'
Failed for utility MD_15263_2021: 'properties'

 67%|██████▋   | 2871/4292 [14:26<02:57,  8.00it/s]

Failed for utility MD_15270_2021: 'properties'
Failed for utility MD_17637_2021: 'properties'

 67%|██████▋   | 2874/4292 [14:27<02:40,  8.81it/s]

Failed for utility ME_1179_2021: 'properties'
Failed for utility ME_3266_2021: 'properties'
Failed for utility ME_5609_2021: 'properties'

 67%|██████▋   | 2876/4292 [14:27<02:44,  8.60it/s]

Failed for utility MI_392_2021: 'properties'
Failed for utility MI_3828_2021: 'properties'

 67%|██████▋   | 2878/4292 [14:27<03:17,  7.15it/s]

Failed for utility MI_4254_2021: 'properties'
Failed for utility MI_5109_2021: 'properties'

 67%|██████▋   | 2879/4292 [14:28<03:19,  7.10it/s]

Failed for utility MI_9324_2021: 'properties'
Failed for utility MI_10704_2021: 'properties'

 67%|██████▋   | 2881/4292 [14:28<02:58,  7.92it/s]

Failed for utility MI_19578_2021: 'properties'
Failed for utility MN_689_2021: 'properties'

 67%|██████▋   | 2884/4292 [14:28<02:53,  8.11it/s]

Failed for utility MN_5574_2021: 'properties'
Failed for utility MN_10596_2021: 'properties'

 67%|██████▋   | 2886/4292 [14:28<02:53,  8.08it/s]

Failed for utility MN_12647_2021: 'properties'
Failed for utility MN_13781_2021: 'properties'

 67%|██████▋   | 2888/4292 [14:29<03:19,  7.03it/s]

Failed for utility MN_14232_2021: 'properties'
Failed for utility MN_16181_2021: 'properties'

 67%|██████▋   | 2890/4292 [14:29<02:59,  7.79it/s]

Failed for utility MN_17267_2021: 'properties'
Failed for utility MN_20996_2021: 'properties'

 67%|██████▋   | 2892/4292 [14:29<03:08,  7.42it/s]

Failed for utility MN_25177_2021: 'properties'
Failed for utility MO_4675_2021: 'properties'

 67%|██████▋   | 2894/4292 [14:30<03:29,  6.68it/s]

Failed for utility MO_5860_2021: 'properties'
Failed for utility MO_9231_2021: 'properties'

 67%|██████▋   | 2896/4292 [14:30<03:10,  7.34it/s]

Failed for utility MO_10000_2021: 'properties'
Failed for utility MO_12698_2021: 'properties'

 68%|██████▊   | 2898/4292 [14:30<03:07,  7.43it/s]

Failed for utility MO_17833_2021: 'properties'
Failed for utility MO_19436_2021: 'properties'

 68%|██████▊   | 2900/4292 [14:30<03:00,  7.69it/s]

Failed for utility MS_3841_2021: 'properties'
Failed for utility MS_12685_2021: 'properties'

 68%|██████▊   | 2902/4292 [14:31<03:02,  7.61it/s]

Failed for utility MS_12686_2021: 'properties'
Failed for utility MS_17647_2021: 'properties'

 68%|██████▊   | 2904/4292 [14:31<02:48,  8.23it/s]

Failed for utility MT_6395_2021: 'properties'
Failed for utility MT_12199_2021: 'properties'

 68%|██████▊   | 2906/4292 [14:31<03:11,  7.24it/s]

Failed for utility MT_12692_2021: 'properties'
Failed for utility MT_12825_2021: 'properties'

 68%|██████▊   | 2908/4292 [14:31<03:14,  7.11it/s]

Failed for utility MT_19603_2021: 'properties'
Failed for utility MT_20997_2021: 'properties'

 68%|██████▊   | 2910/4292 [14:32<03:25,  6.73it/s]

Failed for utility NC_3046_2021: 'properties'
Failed for utility NC_5416_2021: 'properties'

 68%|██████▊   | 2912/4292 [14:32<03:22,  6.81it/s]

Failed for utility NC_9837_2021: 'properties'
Failed for utility NC_16496_2021: 'properties'

 68%|██████▊   | 2914/4292 [14:32<03:28,  6.60it/s]

Failed for utility NC_19876_2021: 'properties'
Failed for utility NC_24889_2021: 'properties'

 68%|██████▊   | 2916/4292 [14:32<02:56,  7.77it/s]

Failed for utility ND_12090_2021: 'properties'
Failed for utility ND_12301_2021: 'properties'

 68%|██████▊   | 2918/4292 [14:33<03:17,  6.95it/s]

Failed for utility ND_14232_2021: 'properties'
Failed for utility ND_19790_2021: 'properties'

 68%|██████▊   | 2920/4292 [14:33<03:07,  7.31it/s]

Failed for utility ND_24949_2021: 'properties'
Failed for utility NE_4373_2021: 'properties'

 68%|██████▊   | 2921/4292 [14:33<02:53,  7.89it/s]

Failed for utility NE_4911_2021: 'properties'
Failed for utility NE_6779_2021: 'properties'

 68%|██████▊   | 2924/4292 [14:34<02:49,  8.09it/s]

Failed for utility NE_11018_2021: 'properties'
Failed for utility NE_11251_2021: 'properties'

 68%|██████▊   | 2926/4292 [14:34<02:44,  8.31it/s]

Failed for utility NE_12539_2021: 'properties'
Failed for utility NE_13337_2021: 'properties'

 68%|██████▊   | 2928/4292 [14:34<02:28,  9.18it/s]

Failed for utility NE_13664_2021: 'properties'
Failed for utility NE_14127_2021: 'properties'

 68%|██████▊   | 2931/4292 [14:34<02:25,  9.37it/s]

Failed for utility NE_17642_2021: 'properties'
Failed for utility NE_27058_2021: 'properties'
Failed for utility NE_40606_2021: 'properties'

 68%|██████▊   | 2933/4292 [14:35<02:32,  8.93it/s]

Failed for utility NH_13441_2021: 'properties'
Failed for utility NH_15472_2021: 'properties'

 68%|██████▊   | 2935/4292 [14:35<02:26,  9.28it/s]

Failed for utility NH_24590_2021: 'properties'
Failed for utility NJ_963_2021: 'properties'

 68%|██████▊   | 2937/4292 [14:35<02:48,  8.06it/s]

Failed for utility NJ_9726_2021: 'properties'
Failed for utility NJ_15477_2021: 'properties'

 68%|██████▊   | 2939/4292 [14:35<03:00,  7.52it/s]

Failed for utility NJ_16213_2021: 'properties'
Failed for utility NM_3287_2021: 'properties'

 69%|██████▊   | 2941/4292 [14:36<02:50,  7.91it/s]

Failed for utility NM_5701_2021: 'properties'
Failed for utility NM_6204_2021: 'properties'

 69%|██████▊   | 2943/4292 [14:36<02:49,  7.96it/s]

Failed for utility NM_11204_2021: 'properties'
Failed for utility NM_15473_2021: 'properties'

 69%|██████▊   | 2945/4292 [14:36<02:40,  8.40it/s]

Failed for utility NM_17718_2021: 'properties'
Failed for utility NV_2008_2021: 'properties'

 69%|██████▊   | 2947/4292 [14:36<02:48,  7.97it/s]

Failed for utility NV_13073_2021: 'properties'
Failed for utility NV_13407_2021: 'properties'

 69%|██████▊   | 2949/4292 [14:37<02:51,  7.81it/s]

Failed for utility NV_17166_2021: 'properties'
Failed for utility NV_19840_2021: 'properties'

 69%|██████▉   | 2951/4292 [14:37<02:44,  8.14it/s]

Failed for utility NY_3249_2021: 'properties'
Failed for utility NY_4226_2021: 'properties'

 69%|██████▉   | 2953/4292 [14:37<03:16,  6.83it/s]

Failed for utility NY_11171_2021: 'properties'
Failed for utility NY_13511_2021: 'properties'

 69%|██████▉   | 2955/4292 [14:37<03:30,  6.35it/s]

Failed for utility NY_13573_2021: 'properties'
Failed for utility NY_14154_2021: 'properties'

 69%|██████▉   | 2957/4292 [14:38<03:30,  6.34it/s]

Failed for utility NY_14711_2021: 'properties'
Failed for utility NY_16183_2021: 'properties'

 69%|██████▉   | 2959/4292 [14:38<03:14,  6.85it/s]

Failed for utility OH_3542_2021: 'properties'
Failed for utility OH_3755_2021: 'properties'

 69%|██████▉   | 2961/4292 [14:38<03:10,  7.00it/s]

Failed for utility OH_4922_2021: 'properties'
Failed for utility OH_13998_2021: 'properties'

 69%|██████▉   | 2963/4292 [14:39<03:06,  7.14it/s]

Failed for utility OH_14006_2021: 'properties'
Failed for utility OH_18997_2021: 'properties'

 69%|██████▉   | 2965/4292 [14:39<03:06,  7.13it/s]

Failed for utility OK_5860_2021: 'properties'
Failed for utility OK_13734_2021: 'properties'

 69%|██████▉   | 2967/4292 [14:39<03:10,  6.95it/s]

Failed for utility OK_14062_2021: 'properties'
Failed for utility OK_14063_2021: 'properties'

 69%|██████▉   | 2969/4292 [14:39<03:27,  6.38it/s]

Failed for utility OK_15474_2021: 'properties'
Failed for utility OK_19785_2021: 'properties'

 69%|██████▉   | 2971/4292 [14:40<02:59,  7.35it/s]

Failed for utility OR_6022_2021: 'properties'
Failed for utility OR_9191_2021: 'properties'

 69%|██████▉   | 2973/4292 [14:40<03:05,  7.10it/s]

Failed for utility OR_14354_2021: 'properties'
Failed for utility OR_15248_2021: 'properties'

 69%|██████▉   | 2975/4292 [14:40<02:54,  7.55it/s]

Failed for utility OR_18260_2021: 'properties'
Failed for utility OR_28541_2021: 'properties'

 69%|██████▉   | 2977/4292 [14:40<02:46,  7.92it/s]

Failed for utility OR_40437_2021: 'properties'
Failed for utility PA_3597_2021: 'properties'

 69%|██████▉   | 2979/4292 [14:41<03:16,  6.68it/s]

Failed for utility PA_5487_2021: 'properties'
Failed for utility PA_12390_2021: 'properties'

 69%|██████▉   | 2981/4292 [14:41<03:26,  6.34it/s]

Failed for utility PA_14711_2021: 'properties'
Failed for utility PA_14715_2021: 'properties'

 70%|██████▉   | 2983/4292 [14:41<03:16,  6.68it/s]

Failed for utility PA_14716_2021: 'properties'
Failed for utility PA_14940_2021: 'properties'

 70%|██████▉   | 2985/4292 [14:42<02:52,  7.56it/s]

Failed for utility PA_15045_2021: 'properties'
Failed for utility PA_19390_2021: 'properties'

 70%|██████▉   | 2987/4292 [14:42<03:01,  7.21it/s]

Failed for utility PA_20334_2021: 'properties'
Failed for utility PA_20387_2021: 'properties'

 70%|██████▉   | 2989/4292 [14:42<02:47,  7.76it/s]

Failed for utility RI_1857_2021: 'properties'
Failed for utility RI_13214_2021: 'properties'

 70%|██████▉   | 2991/4292 [14:42<02:56,  7.35it/s]

Failed for utility RI_14537_2021: 'properties'
Failed for utility SC_1613_2021: 'properties'

 70%|██████▉   | 2993/4292 [14:43<02:37,  8.25it/s]

Failed for utility SC_3046_2021: 'properties'
Failed for utility SC_5416_2021: 'properties'

 70%|██████▉   | 2995/4292 [14:43<02:37,  8.25it/s]

Failed for utility SC_14398_2021: 'properties'
Failed for utility SC_17539_2021: 'properties'

 70%|██████▉   | 2997/4292 [14:43<02:33,  8.44it/s]

Failed for utility SC_17543_2021: 'properties'
Failed for utility SD_1769_2021: 'properties'

 70%|██████▉   | 2999/4292 [14:43<02:53,  7.44it/s]

Failed for utility SD_14232_2021: 'properties'
Failed for utility SD_17267_2021: 'properties'

 70%|██████▉   | 3001/4292 [14:44<02:52,  7.51it/s]

Failed for utility SD_19293_2021: 'properties'
Failed for utility SD_20401_2021: 'properties'

 70%|██████▉   | 3003/4292 [14:44<02:32,  8.44it/s]

Failed for utility TN_10331_2021: 'properties'
Failed for utility TX_5701_2021: 'properties'

 70%|███████   | 3005/4292 [14:44<02:40,  8.04it/s]

Failed for utility TX_16604_2021: 'properties'
Failed for utility TX_55937_2021: 'properties'

 70%|███████   | 3007/4292 [14:44<02:36,  8.20it/s]

Failed for utility UT_2010_2021: 'properties'
Failed for utility UT_11135_2021: 'properties'

 70%|███████   | 3009/4292 [14:45<02:46,  7.73it/s]

Failed for utility UT_12866_2021: 'properties'
Failed for utility UT_14354_2021: 'properties'

 70%|███████   | 3012/4292 [14:45<02:18,  9.27it/s]

Failed for utility UT_15444_2021: 'properties'
Failed for utility UT_17845_2021: 'properties'
Failed for utility UT_17874_2021: 'properties'

 70%|███████   | 3014/4292 [14:45<02:21,  9.02it/s]

Failed for utility UT_18206_2021: 'properties'
Failed for utility VA_84_2021: 'properties'

 70%|███████   | 3016/4292 [14:45<02:28,  8.57it/s]

Failed for utility VA_733_2021: 'properties'
Failed for utility VA_10171_2021: 'properties'

 70%|███████   | 3018/4292 [14:46<02:58,  7.14it/s]

Failed for utility VA_17066_2021: 'properties'
Failed for utility VA_19876_2021: 'properties'

 70%|███████   | 3019/4292 [14:46<02:54,  7.28it/s]

Failed for utility VA_19882_2021: 'properties'
Failed for utility VA_40228_2021: 'properties'

 70%|███████   | 3021/4292 [14:46<02:34,  8.22it/s]

Failed for utility VT_2548_2021: 'properties'

 70%|███████   | 3023/4292 [14:47<03:25,  6.18it/s]

Failed for utility VT_7601_2021: 'properties'
Failed for utility VT_19791_2021: 'properties'

 70%|███████   | 3025/4292 [14:47<02:59,  7.06it/s]

Failed for utility WA_3660_2021: 'properties'
Failed for utility WA_14354_2021: 'properties'

 71%|███████   | 3027/4292 [14:47<02:53,  7.29it/s]

Failed for utility WA_15500_2021: 'properties'
Failed for utility WA_16868_2021: 'properties'

 71%|███████   | 3029/4292 [14:47<02:33,  8.22it/s]

Failed for utility WA_17470_2021: 'properties'
Failed for utility WA_18429_2021: 'properties'

 71%|███████   | 3031/4292 [14:48<02:34,  8.17it/s]

Failed for utility WA_20169_2021: 'properties'
Failed for utility WI_4715_2021: 'properties'

 71%|███████   | 3032/4292 [14:48<02:26,  8.58it/s]

Failed for utility WI_5574_2021: 'properties'
Failed for utility WI_11479_2021: 'properties'

 71%|███████   | 3035/4292 [14:48<02:22,  8.81it/s]

Failed for utility WI_13697_2021: 'properties'
Failed for utility WI_13780_2021: 'properties'

 71%|███████   | 3037/4292 [14:48<02:21,  8.88it/s]

Failed for utility WI_13815_2021: 'properties'
Failed for utility WI_20847_2021: 'properties'

 71%|███████   | 3038/4292 [14:48<02:37,  7.94it/s]

Failed for utility WI_20856_2021: 'properties'

 71%|███████   | 3040/4292 [14:49<03:29,  5.97it/s]

Failed for utility WI_20860_2021: 'properties'
Failed for utility WV_733_2021: 'properties'

 71%|███████   | 3041/4292 [14:49<03:21,  6.22it/s]

Failed for utility WV_12796_2021: 'properties'
Failed for utility WV_15263_2021: 'properties'

 71%|███████   | 3044/4292 [14:49<02:40,  7.80it/s]

Failed for utility WV_20521_2021: 'properties'
Failed for utility WY_3461_2021: 'properties'

 71%|███████   | 3046/4292 [14:50<02:44,  7.57it/s]

Failed for utility WY_7222_2021: 'properties'
Failed for utility WY_8566_2021: 'properties'

 71%|███████   | 3047/4292 [14:50<02:49,  7.33it/s]

Failed for utility WY_11273_2021: 'properties'

 71%|███████   | 3049/4292 [14:50<03:20,  6.21it/s]

Failed for utility WY_12199_2021: 'properties'
Failed for utility WY_14354_2021: 'properties'

 71%|███████   | 3051/4292 [14:50<02:51,  7.23it/s]

Failed for utility WY_19156_2021: 'properties'
Failed for utility WY_27058_2021: 'properties'

 71%|███████   | 3053/4292 [14:51<02:36,  7.92it/s]

Failed for utility CA_16612_2021: 'properties'
Failed for utility CO_10066_2021: 'properties'

 71%|███████   | 3055/4292 [14:51<02:45,  7.49it/s]

Failed for utility MA_20310_2021: 'properties'
Failed for utility AK_219_2022: 'properties'

 71%|███████   | 3057/4292 [14:51<02:27,  8.36it/s]

Failed for utility AK_3522_2022: 'properties'
Failed for utility AK_7353_2022: 'properties'

 71%|███████▏  | 3059/4292 [14:51<02:24,  8.55it/s]

Failed for utility AK_11824_2022: 'properties'
Failed for utility AK_19558_2022: 'properties'

 71%|███████▏  | 3061/4292 [14:52<02:30,  8.19it/s]

Failed for utility AR_814_2022: 'properties'
Failed for utility AR_817_2022: 'properties'

 71%|███████▏  | 3063/4292 [14:52<02:24,  8.48it/s]

Failed for utility AR_3093_2022: 'properties'
Failed for utility AR_5860_2022: 'properties'

 71%|███████▏  | 3065/4292 [14:52<02:44,  7.44it/s]

Failed for utility AR_6342_2022: 'properties'
Failed for utility AR_13718_2022: 'properties'

 71%|███████▏  | 3067/4292 [14:52<02:41,  7.61it/s]

Failed for utility AR_14063_2022: 'properties'
Failed for utility AR_17698_2022: 'properties'

 72%|███████▏  | 3069/4292 [14:53<02:34,  7.90it/s]

Failed for utility AZ_176_2022: 'properties'
Failed for utility AZ_803_2022: 'properties'

 72%|███████▏  | 3071/4292 [14:53<02:39,  7.67it/s]

Failed for utility AZ_12919_2022: 'properties'
Failed for utility AZ_16572_2022: 'properties'

 72%|███████▏  | 3073/4292 [14:53<02:50,  7.14it/s]

Failed for utility AZ_19189_2022: 'properties'
Failed for utility AZ_19728_2022: 'properties'

 72%|███████▏  | 3075/4292 [14:53<02:34,  7.85it/s]

Failed for utility AZ_21538_2022: 'properties'
Failed for utility AZ_24211_2022: 'properties'

 72%|███████▏  | 3077/4292 [14:54<02:19,  8.68it/s]

Failed for utility CA_4390_2022: 'properties'
Failed for utility CA_9216_2022: 'properties'

 72%|███████▏  | 3079/4292 [14:54<02:37,  7.71it/s]

Failed for utility CA_11208_2022: 'properties'
Failed for utility CA_12745_2022: 'properties'

 72%|███████▏  | 3081/4292 [14:54<03:03,  6.60it/s]

Failed for utility CA_14328_2022: 'properties'
Failed for utility CA_14354_2022: 'properties'

 72%|███████▏  | 3083/4292 [14:54<02:47,  7.22it/s]

Failed for utility CA_14534_2022: 'properties'
Failed for utility CA_16534_2022: 'properties'

 72%|███████▏  | 3085/4292 [14:55<02:53,  6.95it/s]

Failed for utility CA_16609_2022: 'properties'
Failed for utility CA_16655_2022: 'properties'

 72%|███████▏  | 3088/4292 [14:55<02:29,  8.03it/s]

Failed for utility CA_17609_2022: 'properties'
Failed for utility CA_17612_2022: 'properties'
Failed for utility CA_18260_2022: 'properties'

 72%|███████▏  | 3090/4292 [14:55<02:25,  8.29it/s]

Failed for utility CA_19281_2022: 'properties'
Failed for utility CO_3989_2022: 'properties'

 72%|███████▏  | 3092/4292 [14:56<02:20,  8.52it/s]

Failed for utility CO_6604_2022: 'properties'
Failed for utility CO_9336_2022: 'properties'

 72%|███████▏  | 3094/4292 [14:56<02:37,  7.63it/s]

Failed for utility CO_12866_2022: 'properties'
Failed for utility CO_15257_2022: 'properties'

 72%|███████▏  | 3096/4292 [14:56<02:20,  8.50it/s]

Failed for utility CO_15466_2022: 'properties'
Failed for utility CO_16603_2022: 'properties'

 72%|███████▏  | 3098/4292 [14:56<02:22,  8.37it/s]

Failed for utility CO_19499_2022: 'properties'
Failed for utility CO_27058_2022: 'properties'

 72%|███████▏  | 3100/4292 [14:57<02:15,  8.79it/s]

Failed for utility CO_56146_2022: 'properties'
Failed for utility CT_4176_2022: 'properties'

 72%|███████▏  | 3102/4292 [14:57<02:12,  8.98it/s]

Failed for utility CT_7716_2022: 'properties'
Failed for utility CT_19497_2022: 'properties'

 72%|███████▏  | 3104/4292 [14:57<02:24,  8.21it/s]

Failed for utility CT_20038_2022: 'properties'
Failed for utility DC_15270_2022: 'properties'

 72%|███████▏  | 3106/4292 [14:57<02:28,  7.97it/s]

Failed for utility DE_5027_2022: 'properties'
Failed for utility DE_5070_2022: 'properties'

 72%|███████▏  | 3108/4292 [14:58<02:17,  8.61it/s]

Failed for utility DE_5335_2022: 'properties'
Failed for utility DE_13519_2022: 'properties'

 72%|███████▏  | 3110/4292 [14:58<02:39,  7.41it/s]

Failed for utility FL_6452_2022: 'properties'
Failed for utility FL_6455_2022: 'properties'

 73%|███████▎  | 3113/4292 [14:58<02:22,  8.26it/s]

Failed for utility FL_6457_2022: 'properties'
Failed for utility FL_9617_2022: 'properties'
Failed for utility FL_18454_2022: 'properties'

 73%|███████▎  | 3115/4292 [14:58<02:36,  7.51it/s]

Failed for utility GA_3916_2022: 'properties'
Failed for utility GA_9601_2022: 'properties'

 73%|███████▎  | 3117/4292 [14:59<02:25,  8.05it/s]

Failed for utility HI_8287_2022: 'properties'
Failed for utility HI_10071_2022: 'properties'

 73%|███████▎  | 3119/4292 [14:59<02:29,  7.87it/s]

Failed for utility HI_11843_2022: 'properties'
Failed for utility HI_19547_2022: 'properties'

 73%|███████▎  | 3121/4292 [14:59<02:27,  7.96it/s]

Failed for utility IA_9417_2022: 'properties'
Failed for utility IA_12341_2022: 'properties'

 73%|███████▎  | 3123/4292 [14:59<02:34,  7.55it/s]

Failed for utility ID_9187_2022: 'properties'
Failed for utility ID_9191_2022: 'properties'

 73%|███████▎  | 3125/4292 [15:00<02:28,  7.88it/s]

Failed for utility ID_10454_2022: 'properties'
Failed for utility ID_11273_2022: 'properties'

 73%|███████▎  | 3127/4292 [15:00<02:19,  8.34it/s]

Failed for utility ID_14354_2022: 'properties'
Failed for utility ID_20169_2022: 'properties'

 73%|███████▎  | 3129/4292 [15:00<02:21,  8.19it/s]

Failed for utility IL_4110_2022: 'properties'
Failed for utility IL_12341_2022: 'properties'

 73%|███████▎  | 3130/4292 [15:00<02:35,  7.49it/s]

Failed for utility IL_13032_2022: 'properties'

 73%|███████▎  | 3132/4292 [15:01<03:20,  5.80it/s]

Failed for utility IL_56697_2022: 'properties'
Failed for utility IN_9273_2022: 'properties'

 73%|███████▎  | 3134/4292 [15:01<02:46,  6.96it/s]

Failed for utility IN_9324_2022: 'properties'
Failed for utility IN_13756_2022: 'properties'

 73%|███████▎  | 3136/4292 [15:01<02:43,  7.09it/s]

Failed for utility IN_15470_2022: 'properties'
Failed for utility IN_17633_2022: 'properties'

 73%|███████▎  | 3139/4292 [15:02<02:18,  8.35it/s]

Failed for utility KS_5860_2022: 'properties'
Failed for utility KS_9996_2022: 'properties'
Failed for utility KS_10000_2022: 'properties'

 73%|███████▎  | 3141/4292 [15:02<02:18,  8.29it/s]

Failed for utility KS_10005_2022: 'properties'
Failed for utility KS_22500_2022: 'properties'

 73%|███████▎  | 3143/4292 [15:02<02:32,  7.51it/s]

Failed for utility KY_9964_2022: 'properties'
Failed for utility KY_10171_2022: 'properties'

 73%|███████▎  | 3145/4292 [15:02<02:38,  7.25it/s]

Failed for utility KY_11249_2022: 'properties'
Failed for utility KY_17564_2022: 'properties'

 73%|███████▎  | 3147/4292 [15:03<02:30,  7.63it/s]

Failed for utility KY_19446_2022: 'properties'
Failed for utility KY_22053_2022: 'properties'
Failed for utility KY_49998_2022: 'properties'
Failed for utility LA_3265_2022: 'properties'

 73%|███████▎  | 3150/4292 [15:03<02:37,  7.26it/s]

Failed for utility LA_11241_2022: 'properties'
Failed for utility LA_13478_2022: 'properties'

 73%|███████▎  | 3153/4292 [15:03<02:21,  8.08it/s]

Failed for utility LA_17698_2022: 'properties'
Failed for utility MA_6374_2022: 'properties'

 74%|███████▎  | 3155/4292 [15:04<02:30,  7.55it/s]

Failed for utility MA_8774_2022: 'properties'
Failed for utility MA_11804_2022: 'properties'

 74%|███████▎  | 3157/4292 [15:04<02:21,  8.01it/s]

Failed for utility MA_13206_2022: 'properties'
Failed for utility MA_15748_2022: 'properties'

 74%|███████▎  | 3159/4292 [15:04<02:32,  7.43it/s]

Failed for utility MA_54913_2022: 'properties'
Failed for utility MD_1167_2022: 'properties'

 74%|███████▎  | 3161/4292 [15:04<02:25,  7.80it/s]

Failed for utility MD_5027_2022: 'properties'
Failed for utility MD_15263_2022: 'properties'

 74%|███████▎  | 3162/4292 [15:05<02:20,  8.03it/s]

Failed for utility MD_15270_2022: 'properties'
Failed for utility MD_17637_2022: 'properties'

 74%|███████▎  | 3165/4292 [15:05<02:17,  8.20it/s]

Failed for utility ME_1179_2022: 'properties'
Failed for utility ME_3266_2022: 'properties'

 74%|███████▍  | 3167/4292 [15:05<02:24,  7.76it/s]

Failed for utility ME_5609_2022: 'properties'
Failed for utility MI_392_2022: 'properties'

 74%|███████▍  | 3169/4292 [15:05<02:12,  8.47it/s]

Failed for utility MI_3828_2022: 'properties'
Failed for utility MI_4254_2022: 'properties'

 74%|███████▍  | 3171/4292 [15:06<02:11,  8.50it/s]

Failed for utility MI_5109_2022: 'properties'
Failed for utility MI_9324_2022: 'properties'

 74%|███████▍  | 3173/4292 [15:06<02:08,  8.68it/s]

Failed for utility MI_10704_2022: 'properties'
Failed for utility MI_19578_2022: 'properties'

 74%|███████▍  | 3175/4292 [15:06<02:11,  8.50it/s]

Failed for utility MN_689_2022: 'properties'
Failed for utility MN_5574_2022: 'properties'

 74%|███████▍  | 3177/4292 [15:06<02:17,  8.10it/s]

Failed for utility MN_10596_2022: 'properties'
Failed for utility MN_12647_2022: 'properties'

 74%|███████▍  | 3179/4292 [15:07<02:25,  7.66it/s]

Failed for utility MN_13781_2022: 'properties'
Failed for utility MN_14232_2022: 'properties'

 74%|███████▍  | 3181/4292 [15:07<02:32,  7.27it/s]

Failed for utility MN_16181_2022: 'properties'
Failed for utility MN_17267_2022: 'properties'

 74%|███████▍  | 3183/4292 [15:07<02:13,  8.31it/s]

Failed for utility MN_20996_2022: 'properties'
Failed for utility MN_25177_2022: 'properties'

 74%|███████▍  | 3185/4292 [15:07<02:29,  7.42it/s]

Failed for utility MO_4675_2022: 'properties'
Failed for utility MO_5860_2022: 'properties'

 74%|███████▍  | 3187/4292 [15:08<02:23,  7.69it/s]

Failed for utility MO_9231_2022: 'properties'
Failed for utility MO_10000_2022: 'properties'

 74%|███████▍  | 3189/4292 [15:08<02:22,  7.73it/s]

Failed for utility MO_12698_2022: 'properties'
Failed for utility MO_17833_2022: 'properties'

 74%|███████▍  | 3191/4292 [15:08<02:25,  7.58it/s]

Failed for utility MO_19436_2022: 'properties'
Failed for utility MS_3841_2022: 'properties'

 74%|███████▍  | 3193/4292 [15:08<02:22,  7.71it/s]

Failed for utility MS_12685_2022: 'properties'
Failed for utility MS_12686_2022: 'properties'

 74%|███████▍  | 3195/4292 [15:09<02:23,  7.65it/s]

Failed for utility MS_17647_2022: 'properties'
Failed for utility MT_6395_2022: 'properties'

 74%|███████▍  | 3197/4292 [15:09<02:34,  7.08it/s]

Failed for utility MT_12199_2022: 'properties'
Failed for utility MT_12692_2022: 'properties'

 75%|███████▍  | 3199/4292 [15:09<02:32,  7.15it/s]

Failed for utility MT_12825_2022: 'properties'
Failed for utility MT_19603_2022: 'properties'

 75%|███████▍  | 3201/4292 [15:10<02:42,  6.73it/s]

Failed for utility MT_20997_2022: 'properties'
Failed for utility NC_3046_2022: 'properties'

 75%|███████▍  | 3203/4292 [15:10<02:25,  7.51it/s]

Failed for utility NC_5416_2022: 'properties'
Failed for utility NC_9837_2022: 'properties'

 75%|███████▍  | 3205/4292 [15:10<02:19,  7.82it/s]

Failed for utility NC_16496_2022: 'properties'
Failed for utility NC_19876_2022: 'properties'

 75%|███████▍  | 3207/4292 [15:10<02:18,  7.86it/s]

Failed for utility NC_24889_2022: 'properties'
Failed for utility ND_12090_2022: 'properties'

 75%|███████▍  | 3208/4292 [15:10<02:14,  8.06it/s]

Failed for utility ND_12301_2022: 'properties'

 75%|███████▍  | 3210/4292 [15:11<03:01,  5.95it/s]

Failed for utility ND_14232_2022: 'properties'
Failed for utility ND_19790_2022: 'properties'

 75%|███████▍  | 3211/4292 [15:11<02:45,  6.55it/s]

Failed for utility ND_20413_2022: 'properties'
Failed for utility ND_24949_2022: 'properties'

 75%|███████▍  | 3214/4292 [15:11<02:17,  7.83it/s]

Failed for utility NE_4373_2022: 'properties'
Failed for utility NE_4911_2022: 'properties'

 75%|███████▍  | 3216/4292 [15:12<02:12,  8.10it/s]

Failed for utility NE_6779_2022: 'properties'
Failed for utility NE_11018_2022: 'properties'
Failed for utility NE_11251_2022: 'properties'

 75%|███████▍  | 3218/4292 [15:12<01:58,  9.10it/s]

Failed for utility NE_12539_2022: 'properties'
Failed for utility NE_13337_2022: 'properties'

 75%|███████▌  | 3221/4292 [15:12<01:56,  9.21it/s]

Failed for utility NE_13664_2022: 'properties'
Failed for utility NE_14127_2022: 'properties'

 75%|███████▌  | 3223/4292 [15:12<02:03,  8.68it/s]

Failed for utility NE_17642_2022: 'properties'
Failed for utility NE_27058_2022: 'properties'

 75%|███████▌  | 3225/4292 [15:13<02:04,  8.57it/s]

Failed for utility NE_40606_2022: 'properties'
Failed for utility NH_13441_2022: 'properties'

 75%|███████▌  | 3227/4292 [15:13<02:05,  8.50it/s]

Failed for utility NH_15472_2022: 'properties'
Failed for utility NH_24590_2022: 'properties'

 75%|███████▌  | 3229/4292 [15:13<02:04,  8.51it/s]

Failed for utility NJ_963_2022: 'properties'
Failed for utility NJ_9726_2022: 'properties'

 75%|███████▌  | 3231/4292 [15:13<01:58,  8.97it/s]

Failed for utility NJ_15477_2022: 'properties'
Failed for utility NJ_16213_2022: 'properties'

 75%|███████▌  | 3233/4292 [15:14<01:58,  8.95it/s]

Failed for utility NM_3287_2022: 'properties'
Failed for utility NM_5701_2022: 'properties'

 75%|███████▌  | 3235/4292 [15:14<01:55,  9.13it/s]

Failed for utility NM_6204_2022: 'properties'
Failed for utility NM_11204_2022: 'properties'

 75%|███████▌  | 3237/4292 [15:14<02:23,  7.37it/s]

Failed for utility NM_15473_2022: 'properties'
Failed for utility NM_17718_2022: 'properties'

 75%|███████▌  | 3239/4292 [15:14<02:17,  7.63it/s]

Failed for utility NV_2008_2022: 'properties'
Failed for utility NV_13073_2022: 'properties'

 76%|███████▌  | 3241/4292 [15:15<02:29,  7.02it/s]

Failed for utility NV_13407_2022: 'properties'
Failed for utility NV_17166_2022: 'properties'

 76%|███████▌  | 3243/4292 [15:15<02:17,  7.63it/s]

Failed for utility NV_19840_2022: 'properties'
Failed for utility NY_3249_2022: 'properties'

 76%|███████▌  | 3244/4292 [15:15<02:15,  7.75it/s]

Failed for utility NY_4226_2022: 'properties'
Failed for utility NY_11171_2022: 'properties'

 76%|███████▌  | 3247/4292 [15:15<02:28,  7.05it/s]

Failed for utility NY_13511_2022: 'properties'
Failed for utility NY_13573_2022: 'properties'

 76%|███████▌  | 3248/4292 [15:16<02:22,  7.32it/s]

Failed for utility NY_14154_2022: 'properties'

 76%|███████▌  | 3250/4292 [15:16<02:57,  5.88it/s]

Failed for utility NY_14711_2022: 'properties'
Failed for utility NY_16183_2022: 'properties'

 76%|███████▌  | 3252/4292 [15:16<02:35,  6.68it/s]

Failed for utility OH_3542_2022: 'properties'
Failed for utility OH_3755_2022: 'properties'

 76%|███████▌  | 3254/4292 [15:17<02:36,  6.61it/s]

Failed for utility OH_4922_2022: 'properties'
Failed for utility OH_13998_2022: 'properties'

 76%|███████▌  | 3256/4292 [15:17<02:29,  6.93it/s]

Failed for utility OH_14006_2022: 'properties'
Failed for utility OH_18997_2022: 'properties'

 76%|███████▌  | 3258/4292 [15:17<02:18,  7.49it/s]

Failed for utility OK_5860_2022: 'properties'
Failed for utility OK_13734_2022: 'properties'

 76%|███████▌  | 3260/4292 [15:18<03:10,  5.42it/s]

Failed for utility OK_14062_2022: 'properties'
Failed for utility OK_14063_2022: 'properties'

 76%|███████▌  | 3263/4292 [15:18<02:18,  7.45it/s]

Failed for utility OK_15474_2022: 'properties'
Failed for utility OK_19785_2022: 'properties'
Failed for utility OR_6022_2022: 'properties'

 76%|███████▌  | 3265/4292 [15:18<02:21,  7.25it/s]

Failed for utility OR_9191_2022: 'properties'
Failed for utility OR_14354_2022: 'properties'

 76%|███████▌  | 3266/4292 [15:18<02:24,  7.09it/s]

Failed for utility OR_15248_2022: 'properties'
Failed for utility OR_18260_2022: 'properties'
Failed for utility OR_28541_2022: 'properties'

 76%|███████▌  | 3270/4292 [15:19<01:57,  8.68it/s]

Failed for utility OR_40437_2022: 'properties'
Failed for utility PA_3597_2022: 'properties'

 76%|███████▌  | 3272/4292 [15:19<02:17,  7.42it/s]

Failed for utility PA_5487_2022: 'properties'
Failed for utility PA_12390_2022: 'properties'

 76%|███████▋  | 3274/4292 [15:19<02:32,  6.69it/s]

Failed for utility PA_14711_2022: 'properties'
Failed for utility PA_14715_2022: 'properties'

 76%|███████▋  | 3276/4292 [15:20<02:20,  7.22it/s]

Failed for utility PA_14716_2022: 'properties'
Failed for utility PA_14940_2022: 'properties'

 76%|███████▋  | 3278/4292 [15:20<02:11,  7.69it/s]

Failed for utility PA_15045_2022: 'properties'
Failed for utility PA_19390_2022: 'properties'

 76%|███████▋  | 3280/4292 [15:20<02:52,  5.86it/s]

Failed for utility PA_20334_2022: 'properties'
Failed for utility PA_20387_2022: 'properties'

 76%|███████▋  | 3282/4292 [15:21<02:25,  6.95it/s]

Failed for utility RI_1857_2022: 'properties'
Failed for utility RI_13214_2022: 'properties'

 76%|███████▋  | 3283/4292 [15:21<02:24,  6.97it/s]

Failed for utility RI_14537_2022: 'properties'
Failed for utility SC_1613_2022: 'properties'

 77%|███████▋  | 3286/4292 [15:21<02:16,  7.36it/s]

Failed for utility SC_3046_2022: 'properties'
Failed for utility SC_5416_2022: 'properties'

 77%|███████▋  | 3288/4292 [15:21<02:08,  7.84it/s]

Failed for utility SC_14398_2022: 'properties'
Failed for utility SC_17539_2022: 'properties'

 77%|███████▋  | 3289/4292 [15:21<02:04,  8.08it/s]

Failed for utility SC_17543_2022: 'properties'
Failed for utility SD_1769_2022: 'properties'

 77%|███████▋  | 3292/4292 [15:22<01:58,  8.46it/s]

Failed for utility SD_14232_2022: 'properties'
Failed for utility SD_17267_2022: 'properties'

 77%|███████▋  | 3294/4292 [15:22<02:16,  7.32it/s]

Failed for utility SD_19293_2022: 'properties'
Failed for utility SD_20401_2022: 'properties'

 77%|███████▋  | 3295/4292 [15:22<02:10,  7.65it/s]

Failed for utility TN_10331_2022: 'properties'

 77%|███████▋  | 3297/4292 [15:23<02:18,  7.16it/s]

Failed for utility TX_5701_2022: 'properties'
Failed for utility TX_16604_2022: 'properties'

 77%|███████▋  | 3299/4292 [15:23<02:12,  7.50it/s]

Failed for utility TX_55937_2022: 'properties'
Failed for utility UT_2010_2022: 'properties'

 77%|███████▋  | 3300/4292 [15:23<02:07,  7.77it/s]

Failed for utility UT_11135_2022: 'properties'

 77%|███████▋  | 3301/4292 [15:23<02:31,  6.55it/s]

Failed for utility UT_12866_2022: 'properties'

 77%|███████▋  | 3303/4292 [15:24<03:06,  5.30it/s]

Failed for utility UT_14354_2022: 'properties'
Failed for utility UT_15444_2022: 'properties'

 77%|███████▋  | 3305/4292 [15:24<02:31,  6.50it/s]

Failed for utility UT_17845_2022: 'properties'
Failed for utility UT_17874_2022: 'properties'

 77%|███████▋  | 3307/4292 [15:24<02:15,  7.24it/s]

Failed for utility UT_18206_2022: 'properties'
Failed for utility VA_84_2022: 'properties'

 77%|███████▋  | 3309/4292 [15:24<02:00,  8.14it/s]

Failed for utility VA_733_2022: 'properties'
Failed for utility VA_10171_2022: 'properties'

 77%|███████▋  | 3311/4292 [15:25<02:07,  7.70it/s]

Failed for utility VA_17066_2022: 'properties'
Failed for utility VA_19876_2022: 'properties'

 77%|███████▋  | 3313/4292 [15:25<02:02,  7.98it/s]

Failed for utility VA_19882_2022: 'properties'
Failed for utility VA_40228_2022: 'properties'

 77%|███████▋  | 3315/4292 [15:25<01:55,  8.45it/s]

Failed for utility VT_2548_2022: 'properties'
Failed for utility VT_7601_2022: 'properties'

 77%|███████▋  | 3317/4292 [15:25<01:54,  8.51it/s]

Failed for utility VT_19791_2022: 'properties'
Failed for utility WA_3660_2022: 'properties'

 77%|███████▋  | 3319/4292 [15:26<02:10,  7.47it/s]

Failed for utility WA_14354_2022: 'properties'
Failed for utility WA_15500_2022: 'properties'

 77%|███████▋  | 3321/4292 [15:26<02:02,  7.90it/s]

Failed for utility WA_16868_2022: 'properties'
Failed for utility WA_17470_2022: 'properties'

 77%|███████▋  | 3322/4292 [15:26<01:59,  8.09it/s]

Failed for utility WA_18429_2022: 'properties'

 77%|███████▋  | 3325/4292 [15:26<02:08,  7.54it/s]

Failed for utility WA_20169_2022: 'properties'
Failed for utility WI_4715_2022: 'properties'
Failed for utility WI_5574_2022: 'properties'

 78%|███████▊  | 3327/4292 [15:27<02:09,  7.44it/s]

Failed for utility WI_11479_2022: 'properties'
Failed for utility WI_13697_2022: 'properties'

 78%|███████▊  | 3328/4292 [15:27<02:09,  7.43it/s]

Failed for utility WI_13780_2022: 'properties'
Failed for utility WI_13815_2022: 'properties'

 78%|███████▊  | 3331/4292 [15:27<02:05,  7.64it/s]

Failed for utility WI_20847_2022: 'properties'
Failed for utility WI_20856_2022: 'properties'

 78%|███████▊  | 3333/4292 [15:27<01:59,  8.03it/s]

Failed for utility WI_20860_2022: 'properties'
Failed for utility WV_733_2022: 'properties'

 78%|███████▊  | 3335/4292 [15:28<01:54,  8.33it/s]

Failed for utility WV_12796_2022: 'properties'
Failed for utility WV_15263_2022: 'properties'

 78%|███████▊  | 3337/4292 [15:28<01:53,  8.39it/s]

Failed for utility WV_20521_2022: 'properties'
Failed for utility WY_3461_2022: 'properties'

 78%|███████▊  | 3339/4292 [15:28<01:57,  8.14it/s]

Failed for utility WY_7222_2022: 'properties'
Failed for utility WY_8566_2022: 'properties'

 78%|███████▊  | 3341/4292 [15:28<01:50,  8.60it/s]

Failed for utility WY_11273_2022: 'properties'
Failed for utility WY_12199_2022: 'properties'

 78%|███████▊  | 3343/4292 [15:29<02:10,  7.29it/s]

Failed for utility WY_14354_2022: 'properties'
Failed for utility WY_19156_2022: 'properties'

 78%|███████▊  | 3345/4292 [15:29<02:14,  7.04it/s]

Failed for utility WY_27058_2022: 'properties'
Failed for utility OK_817_2022: 'properties'

 78%|███████▊  | 3347/4292 [15:29<02:05,  7.56it/s]

Failed for utility CO_10066_2022: 'properties'
Failed for utility AR_12681_2022: 'properties'

 78%|███████▊  | 3349/4292 [15:29<01:59,  7.89it/s]

Failed for utility CA_16612_2022: 'properties'
Failed for utility MA_20310_2022: 'properties'

 78%|███████▊  | 3351/4292 [15:30<02:00,  7.83it/s]

Failed for utility NE_8245_2022: 'properties'
Failed for utility AK_219_2023: 'properties'

 78%|███████▊  | 3353/4292 [15:30<02:01,  7.74it/s]

Failed for utility AK_3522_2023: 'properties'
Failed for utility AK_7353_2023: 'properties'

 78%|███████▊  | 3355/4292 [15:30<01:55,  8.14it/s]

Failed for utility AK_11824_2023: 'properties'
Failed for utility AK_19558_2023: 'properties'

 78%|███████▊  | 3357/4292 [15:31<02:00,  7.78it/s]

Failed for utility AL_3222_2023: 'properties'
Failed for utility AL_4327_2023: 'properties'

 78%|███████▊  | 3359/4292 [15:31<02:00,  7.74it/s]

Failed for utility AL_4430_2023: 'properties'
Failed for utility AL_6491_2023: 'properties'

 78%|███████▊  | 3361/4292 [15:31<02:00,  7.70it/s]

Failed for utility AL_17646_2023: 'properties'
Failed for utility AR_814_2023: 'properties'

 78%|███████▊  | 3363/4292 [15:31<02:05,  7.42it/s]

Failed for utility AR_817_2023: 'properties'
Failed for utility AR_1586_2023: 'properties'

 78%|███████▊  | 3365/4292 [15:32<02:02,  7.59it/s]

Failed for utility AR_2678_2023: 'properties'
Failed for utility AR_3093_2023: 'properties'

 78%|███████▊  | 3367/4292 [15:32<02:03,  7.49it/s]

Failed for utility AR_3712_2023: 'properties'
Failed for utility AR_4280_2023: 'properties'

 78%|███████▊  | 3369/4292 [15:32<01:57,  7.82it/s]

Failed for utility AR_4509_2023: 'properties'
Failed for utility AR_5860_2023: 'properties'

 79%|███████▊  | 3371/4292 [15:32<02:04,  7.39it/s]

Failed for utility AR_6342_2023: 'properties'
Failed for utility AR_8840_2023: 'properties'

 79%|███████▊  | 3374/4292 [15:33<01:40,  9.11it/s]

Failed for utility AR_9879_2023: 'properties'
Failed for utility AR_12681_2023: 'properties'
Failed for utility AR_13676_2023: 'properties'

 79%|███████▊  | 3376/4292 [15:33<01:45,  8.68it/s]

Failed for utility AR_13718_2023: 'properties'
Failed for utility AR_14063_2023: 'properties'

 79%|███████▊  | 3378/4292 [15:33<01:44,  8.74it/s]

Failed for utility AR_14289_2023: 'properties'
Failed for utility AR_14446_2023: 'properties'

 79%|███████▉  | 3380/4292 [15:33<01:49,  8.30it/s]

Failed for utility AR_14864_2023: 'properties'
Failed for utility AR_17184_2023: 'properties'

 79%|███████▉  | 3382/4292 [15:34<01:43,  8.77it/s]

Failed for utility AR_17671_2023: 'properties'
Failed for utility AR_17698_2023: 'properties'

 79%|███████▉  | 3384/4292 [15:34<01:43,  8.78it/s]

Failed for utility AR_20963_2023: 'properties'
Failed for utility AZ_176_2023: 'properties'

 79%|███████▉  | 3386/4292 [15:34<01:49,  8.29it/s]

Failed for utility AZ_803_2023: 'properties'
Failed for utility AZ_6957_2023: 'properties'
Failed for utility AZ_12351_2023: 'properties'

 79%|███████▉  | 3389/4292 [15:34<01:41,  8.91it/s]

Failed for utility AZ_12919_2023: 'properties'
Failed for utility AZ_13318_2023: 'properties'

 79%|███████▉  | 3391/4292 [15:35<01:42,  8.76it/s]

Failed for utility AZ_16572_2023: 'properties'
Failed for utility AZ_18280_2023: 'properties'

 79%|███████▉  | 3393/4292 [15:35<01:39,  9.05it/s]

Failed for utility AZ_19189_2023: 'properties'
Failed for utility AZ_19728_2023: 'properties'

 79%|███████▉  | 3395/4292 [15:35<01:49,  8.15it/s]

Failed for utility AZ_21538_2023: 'properties'
Failed for utility AZ_24211_2023: 'properties'

 79%|███████▉  | 3396/4292 [15:35<01:59,  7.51it/s]

Failed for utility AZ_30518_2023: 'properties'
Failed for utility AZ_40165_2023: 'properties'

 79%|███████▉  | 3399/4292 [15:36<01:50,  8.05it/s]

Failed for utility CA_207_2023: 'properties'
Failed for utility CA_590_2023: 'properties'

 79%|███████▉  | 3401/4292 [15:36<01:55,  7.72it/s]

Failed for utility CA_1050_2023: 'properties'
Failed for utility CA_2507_2023: 'properties'

 79%|███████▉  | 3403/4292 [15:36<01:53,  7.85it/s]

Failed for utility CA_4003_2023: 'properties'
Failed for utility CA_4390_2023: 'properties'

 79%|███████▉  | 3406/4292 [15:36<01:39,  8.89it/s]

Failed for utility CA_7294_2023: 'properties'
Failed for utility CA_9216_2023: 'properties'
Failed for utility CA_11124_2023: 'properties'

 79%|███████▉  | 3409/4292 [15:37<01:38,  8.95it/s]

Failed for utility CA_11208_2023: 'properties'
Failed for utility CA_12312_2023: 'properties'
Failed for utility CA_12745_2023: 'properties'

 79%|███████▉  | 3411/4292 [15:37<02:02,  7.17it/s]

Failed for utility CA_14328_2023: 'properties'
Failed for utility CA_14354_2023: 'properties'

 80%|███████▉  | 3413/4292 [15:37<01:50,  7.96it/s]

Failed for utility CA_14401_2023: 'properties'
Failed for utility CA_14534_2023: 'properties'
Failed for utility CA_15783_2023: 'properties'

 80%|███████▉  | 3416/4292 [15:38<01:39,  8.84it/s]

Failed for utility CA_16088_2023: 'properties'
Failed for utility CA_16295_2023: 'properties'

 80%|███████▉  | 3418/4292 [15:38<01:35,  9.15it/s]

Failed for utility CA_16534_2023: 'properties'
Failed for utility CA_16609_2023: 'properties'

 80%|███████▉  | 3420/4292 [15:38<01:49,  7.95it/s]

Failed for utility CA_16612_2023: 'properties'
Failed for utility CA_16655_2023: 'properties'

 80%|███████▉  | 3422/4292 [15:39<01:57,  7.42it/s]

Failed for utility CA_17609_2023: 'properties'
Failed for utility CA_17612_2023: 'properties'

 80%|███████▉  | 3424/4292 [15:39<01:53,  7.66it/s]

Failed for utility CA_17896_2023: 'properties'
Failed for utility CA_18260_2023: 'properties'

 80%|███████▉  | 3426/4292 [15:39<01:56,  7.42it/s]

Failed for utility CA_19281_2023: 'properties'
Failed for utility CA_19798_2023: 'properties'

 80%|███████▉  | 3428/4292 [15:39<01:50,  7.82it/s]

Failed for utility CA_55787_2023: 'properties'
Failed for utility CA_57483_2023: 'properties'

 80%|███████▉  | 3430/4292 [15:39<01:38,  8.79it/s]

Failed for utility CO_3989_2023: 'properties'
Failed for utility CO_5086_2023: 'properties'

 80%|███████▉  | 3432/4292 [15:40<01:46,  8.10it/s]

Failed for utility CO_5862_2023: 'properties'
Failed for utility CO_6604_2023: 'properties'

 80%|████████  | 3434/4292 [15:40<01:39,  8.65it/s]

Failed for utility CO_6638_2023: 'properties'
Failed for utility CO_7563_2023: 'properties'

 80%|████████  | 3436/4292 [15:40<02:06,  6.77it/s]

Failed for utility CO_8570_2023: 'properties'
Failed for utility CO_8773_2023: 'properties'

 80%|████████  | 3438/4292 [15:41<01:52,  7.62it/s]

Failed for utility CO_9336_2023: 'properties'
Failed for utility CO_10066_2023: 'properties'

 80%|████████  | 3440/4292 [15:41<01:52,  7.54it/s]

Failed for utility CO_10539_2023: 'properties'
Failed for utility CO_11187_2023: 'properties'

 80%|████████  | 3442/4292 [15:41<01:43,  8.23it/s]

Failed for utility CO_11256_2023: 'properties'
Failed for utility CO_12860_2023: 'properties'

 80%|████████  | 3445/4292 [15:41<01:29,  9.45it/s]

Failed for utility CO_12866_2023: 'properties'
Failed for utility CO_13050_2023: 'properties'
Failed for utility CO_13058_2023: 'properties'

 80%|████████  | 3447/4292 [15:42<01:46,  7.97it/s]

Failed for utility CO_15257_2023: 'properties'
Failed for utility CO_15466_2023: 'properties'

 80%|████████  | 3449/4292 [15:42<01:54,  7.37it/s]

Failed for utility CO_16603_2023: 'properties'
Failed for utility CO_16616_2023: 'properties'

 80%|████████  | 3451/4292 [15:42<01:59,  7.02it/s]

Failed for utility CO_16622_2023: 'properties'
Failed for utility CO_17592_2023: 'properties'

 80%|████████  | 3453/4292 [15:43<01:52,  7.45it/s]

Failed for utility CO_19499_2023: 'properties'
Failed for utility CO_20576_2023: 'properties'

 81%|████████  | 3456/4292 [15:43<01:44,  8.01it/s]

Failed for utility CO_21075_2023: 'properties'
Failed for utility CO_21081_2023: 'properties'
Failed for utility CO_27058_2023: 'properties'

 81%|████████  | 3458/4292 [15:43<01:45,  7.89it/s]

Failed for utility CO_56146_2023: 'properties'
Failed for utility CT_4176_2023: 'properties'

 81%|████████  | 3460/4292 [15:43<01:53,  7.31it/s]

Failed for utility CT_7716_2023: 'properties'
Failed for utility CT_13831_2023: 'properties'

 81%|████████  | 3462/4292 [15:44<01:36,  8.57it/s]

Failed for utility CT_19497_2023: 'properties'
Failed for utility CT_20038_2023: 'properties'
Failed for utility DC_15270_2023: 'properties'

 81%|████████  | 3465/4292 [15:44<01:28,  9.37it/s]

Failed for utility DE_5027_2023: 'properties'
Failed for utility DE_5070_2023: 'properties'

 81%|████████  | 3467/4292 [15:44<01:35,  8.62it/s]

Failed for utility DE_5335_2023: 'properties'
Failed for utility DE_12478_2023: 'properties'

 81%|████████  | 3469/4292 [15:44<01:39,  8.26it/s]

Failed for utility DE_12540_2023: 'properties'
Failed for utility DE_13519_2023: 'properties'

 81%|████████  | 3471/4292 [15:45<01:36,  8.53it/s]

Failed for utility FL_1300_2023: 'properties'
Failed for utility FL_3245_2023: 'properties'

 81%|████████  | 3473/4292 [15:45<01:47,  7.61it/s]

Failed for utility FL_3502_2023: 'properties'
Failed for utility FL_3757_2023: 'properties'

 81%|████████  | 3475/4292 [15:45<01:47,  7.58it/s]

Failed for utility FL_6443_2023: 'properties'
Failed for utility FL_6452_2023: 'properties'

 81%|████████  | 3477/4292 [15:46<02:14,  6.04it/s]

Failed for utility FL_6455_2023: 'properties'
Failed for utility FL_6457_2023: 'properties'

 81%|████████  | 3480/4292 [15:46<01:42,  7.90it/s]

Failed for utility FL_6616_2023: 'properties'
Failed for utility FL_6909_2023: 'properties'
Failed for utility FL_7264_2023: 'properties'

 81%|████████  | 3482/4292 [15:46<01:36,  8.36it/s]

Failed for utility FL_7785_2023: 'properties'
Failed for utility FL_8795_2023: 'properties'

 81%|████████  | 3483/4292 [15:46<01:38,  8.19it/s]

Failed for utility FL_9616_2023: 'properties'
Failed for utility FL_9617_2023: 'properties'

 81%|████████  | 3486/4292 [15:47<01:35,  8.42it/s]

Failed for utility FL_10226_2023: 'properties'
Failed for utility FL_10376_2023: 'properties'

 81%|████████  | 3487/4292 [15:47<01:33,  8.59it/s]

Failed for utility FL_10620_2023: 'properties'

 81%|████████▏ | 3489/4292 [15:47<02:03,  6.52it/s]

Failed for utility FL_10623_2023: 'properties'
Failed for utility FL_10857_2023: 'properties'

 81%|████████▏ | 3491/4292 [15:47<01:46,  7.50it/s]

Failed for utility FL_10868_2023: 'properties'
Failed for utility FL_13485_2023: 'properties'

 81%|████████▏ | 3493/4292 [15:48<01:41,  7.89it/s]

Failed for utility FL_13955_2023: 'properties'
Failed for utility FL_14606_2023: 'properties'

 81%|████████▏ | 3495/4292 [15:48<01:43,  7.73it/s]

Failed for utility FL_14610_2023: 'properties'
Failed for utility FL_15776_2023: 'properties'

 81%|████████▏ | 3497/4292 [15:48<01:46,  7.44it/s]

Failed for utility FL_18304_2023: 'properties'
Failed for utility FL_18360_2023: 'properties'

 82%|████████▏ | 3499/4292 [15:48<01:40,  7.92it/s]

Failed for utility FL_18445_2023: 'properties'
Failed for utility FL_18449_2023: 'properties'

 82%|████████▏ | 3501/4292 [15:49<01:33,  8.42it/s]

Failed for utility FL_18454_2023: 'properties'
Failed for utility FL_19161_2023: 'properties'

 82%|████████▏ | 3503/4292 [15:49<01:39,  7.95it/s]

Failed for utility FL_20371_2023: 'properties'
Failed for utility FL_20885_2023: 'properties'

 82%|████████▏ | 3506/4292 [15:49<01:21,  9.60it/s]

Failed for utility FL_31833_2023: 'properties'
Failed for utility GA_230_2023: 'properties'
Failed for utility GA_407_2023: 'properties'

 82%|████████▏ | 3508/4292 [15:49<01:27,  8.91it/s]

Failed for utility GA_562_2023: 'properties'
Failed for utility GA_2487_2023: 'properties'

 82%|████████▏ | 3510/4292 [15:50<01:32,  8.50it/s]

Failed for utility GA_2812_2023: 'properties'
Failed for utility GA_2903_2023: 'properties'

 82%|████████▏ | 3511/4292 [15:50<01:31,  8.52it/s]

Failed for utility GA_3081_2023: 'properties'
Failed for utility GA_3108_2023: 'properties'

 82%|████████▏ | 3514/4292 [15:50<01:26,  8.97it/s]

Failed for utility GA_3248_2023: 'properties'
Failed for utility GA_3843_2023: 'properties'

 82%|████████▏ | 3516/4292 [15:50<01:33,  8.29it/s]

Failed for utility GA_3916_2023: 'properties'
Failed for utility GA_4432_2023: 'properties'

 82%|████████▏ | 3518/4292 [15:51<01:30,  8.53it/s]

Failed for utility GA_4433_2023: 'properties'
Failed for utility GA_4538_2023: 'properties'

 82%|████████▏ | 3520/4292 [15:51<01:32,  8.34it/s]

Failed for utility GA_5905_2023: 'properties'
Failed for utility GA_6411_2023: 'properties'

 82%|████████▏ | 3522/4292 [15:51<01:43,  7.47it/s]

Failed for utility GA_7090_2023: 'properties'
Failed for utility GA_7140_2023: 'properties'

 82%|████████▏ | 3524/4292 [15:52<02:07,  6.00it/s]

Failed for utility GA_7450_2023: 'properties'
Failed for utility GA_7887_2023: 'properties'

 82%|████████▏ | 3526/4292 [15:52<01:52,  6.79it/s]

Failed for utility GA_8210_2023: 'properties'
Failed for utility GA_9431_2023: 'properties'

 82%|████████▏ | 3528/4292 [15:52<02:00,  6.36it/s]

Failed for utility GA_9601_2023: 'properties'
Failed for utility GA_9689_2023: 'properties'

 82%|████████▏ | 3530/4292 [15:52<01:40,  7.55it/s]

Failed for utility GA_10624_2023: 'properties'
Failed for utility GA_10800_2023: 'properties'

 82%|████████▏ | 3531/4292 [15:53<01:46,  7.16it/s]

Failed for utility GA_11646_2023: 'properties'
Failed for utility GA_12706_2023: 'properties'

 82%|████████▏ | 3534/4292 [15:53<01:39,  7.60it/s]

Failed for utility GA_13962_2023: 'properties'
Failed for utility GA_15700_2023: 'properties'

 82%|████████▏ | 3536/4292 [15:53<01:33,  8.07it/s]

Failed for utility GA_16674_2023: 'properties'
Failed for utility GA_16865_2023: 'properties'

 82%|████████▏ | 3537/4292 [15:53<01:31,  8.29it/s]

Failed for utility GA_18305_2023: 'properties'

 82%|████████▏ | 3539/4292 [15:54<01:53,  6.64it/s]

Failed for utility GA_18499_2023: 'properties'
Failed for utility GA_18848_2023: 'properties'

 83%|████████▎ | 3541/4292 [15:54<01:37,  7.74it/s]

Failed for utility GA_18956_2023: 'properties'
Failed for utility GA_19219_2023: 'properties'

 83%|████████▎ | 3543/4292 [15:54<01:34,  7.92it/s]

Failed for utility GA_20065_2023: 'properties'
Failed for utility GA_20146_2023: 'properties'

 83%|████████▎ | 3545/4292 [15:54<01:35,  7.81it/s]

Failed for utility GA_31833_2023: 'properties'
Failed for utility GA_40212_2023: 'properties'

 83%|████████▎ | 3547/4292 [15:55<01:37,  7.61it/s]

Failed for utility HI_8287_2023: 'properties'
Failed for utility HI_10071_2023: 'properties'

 83%|████████▎ | 3549/4292 [15:55<01:30,  8.19it/s]

Failed for utility HI_11843_2023: 'properties'
Failed for utility HI_19547_2023: 'properties'
Failed for utility IA_554_2023: 'properties'

 83%|████████▎ | 3552/4292 [15:55<01:35,  7.76it/s]

Failed for utility IA_2652_2023: 'properties'
Failed for utility IA_3203_2023: 'properties'

 83%|████████▎ | 3554/4292 [15:56<01:33,  7.92it/s]

Failed for utility IA_5588_2023: 'properties'
Failed for utility IA_5605_2023: 'properties'
Failed for utility IA_8319_2023: 'properties'

 83%|████████▎ | 3557/4292 [15:56<01:28,  8.32it/s]

Failed for utility IA_9230_2023: 'properties'
Failed for utility IA_9417_2023: 'properties'

 83%|████████▎ | 3559/4292 [15:56<01:24,  8.69it/s]

Failed for utility IA_9425_2023: 'properties'
Failed for utility IA_11053_2023: 'properties'

 83%|████████▎ | 3561/4292 [15:56<01:33,  7.83it/s]

Failed for utility IA_11611_2023: 'properties'
Failed for utility IA_11788_2023: 'properties'

 83%|████████▎ | 3563/4292 [15:57<01:36,  7.57it/s]

Failed for utility IA_12341_2023: 'properties'
Failed for utility IA_12450_2023: 'properties'

 83%|████████▎ | 3565/4292 [15:57<01:34,  7.70it/s]

Failed for utility IA_13143_2023: 'properties'
Failed for utility IA_15291_2023: 'properties'

 83%|████████▎ | 3567/4292 [15:57<01:34,  7.70it/s]

Failed for utility IA_15349_2023: 'properties'
Failed for utility IA_17260_2023: 'properties'

 83%|████████▎ | 3569/4292 [15:57<01:28,  8.14it/s]

Failed for utility IA_19157_2023: 'properties'
Failed for utility ID_6169_2023: 'properties'

 83%|████████▎ | 3571/4292 [15:58<01:27,  8.24it/s]

Failed for utility ID_8699_2023: 'properties'
Failed for utility ID_9187_2023: 'properties'

 83%|████████▎ | 3573/4292 [15:58<01:33,  7.65it/s]

Failed for utility ID_9191_2023: 'properties'
Failed for utility ID_10454_2023: 'properties'

 83%|████████▎ | 3575/4292 [15:58<01:44,  6.87it/s]

Failed for utility ID_11273_2023: 'properties'
Failed for utility ID_14354_2023: 'properties'

 83%|████████▎ | 3577/4292 [15:58<01:39,  7.15it/s]

Failed for utility ID_19502_2023: 'properties'
Failed for utility ID_20169_2023: 'properties'

 83%|████████▎ | 3579/4292 [15:59<01:38,  7.20it/s]

Failed for utility IL_3931_2023: 'properties'
Failed for utility IL_4110_2023: 'properties'

 83%|████████▎ | 3581/4292 [15:59<01:51,  6.37it/s]

Failed for utility IL_4362_2023: 'properties'
Failed for utility IL_5535_2023: 'properties'

 83%|████████▎ | 3583/4292 [15:59<01:36,  7.35it/s]

Failed for utility IL_5585_2023: 'properties'
Failed for utility IL_7096_2023: 'properties'

 84%|████████▎ | 3585/4292 [16:00<01:26,  8.19it/s]

Failed for utility IL_9750_2023: 'properties'
Failed for utility IL_12341_2023: 'properties'

 84%|████████▎ | 3587/4292 [16:00<01:23,  8.41it/s]

Failed for utility IL_12395_2023: 'properties'
Failed for utility IL_13032_2023: 'properties'

 84%|████████▎ | 3588/4292 [16:00<01:23,  8.38it/s]

Failed for utility IL_13208_2023: 'properties'
Failed for utility IL_13292_2023: 'properties'

 84%|████████▎ | 3591/4292 [16:00<01:19,  8.83it/s]

Failed for utility IL_14840_2023: 'properties'
Failed for utility IL_16179_2023: 'properties'

 84%|████████▎ | 3594/4292 [16:01<01:27,  8.00it/s]

Failed for utility IL_16196_2023: 'properties'
Failed for utility IL_16740_2023: 'properties'
Failed for utility IL_17040_2023: 'properties'

 84%|████████▍ | 3596/4292 [16:01<01:25,  8.18it/s]

Failed for utility IL_17585_2023: 'properties'
Failed for utility IL_17828_2023: 'properties'

 84%|████████▍ | 3598/4292 [16:01<01:27,  7.92it/s]

Failed for utility IL_17860_2023: 'properties'
Failed for utility IL_18955_2023: 'properties'

 84%|████████▍ | 3600/4292 [16:01<01:27,  7.89it/s]

Failed for utility IL_20222_2023: 'properties'
Failed for utility IL_56697_2023: 'properties'

 84%|████████▍ | 3602/4292 [16:02<01:24,  8.13it/s]

Failed for utility IN_636_2023: 'properties'
Failed for utility IN_1283_2023: 'properties'

 84%|████████▍ | 3604/4292 [16:02<01:21,  8.48it/s]

Failed for utility IN_4508_2023: 'properties'
Failed for utility IN_4848_2023: 'properties'

 84%|████████▍ | 3606/4292 [16:02<01:15,  9.06it/s]

Failed for utility IN_4960_2023: 'properties'
Failed for utility IN_5394_2023: 'properties'

 84%|████████▍ | 3608/4292 [16:02<01:13,  9.37it/s]

Failed for utility IN_8000_2023: 'properties'
Failed for utility IN_8179_2023: 'properties'

 84%|████████▍ | 3610/4292 [16:03<01:23,  8.17it/s]

Failed for utility IN_8447_2023: 'properties'
Failed for utility IN_9273_2023: 'properties'

 84%|████████▍ | 3612/4292 [16:03<01:25,  7.93it/s]

Failed for utility IN_9324_2023: 'properties'
Failed for utility IN_9576_2023: 'properties'

 84%|████████▍ | 3614/4292 [16:03<01:23,  8.09it/s]

Failed for utility IN_9665_2023: 'properties'
Failed for utility IN_9667_2023: 'properties'

 84%|████████▍ | 3616/4292 [16:03<01:28,  7.67it/s]

Failed for utility IN_9778_2023: 'properties'
Failed for utility IN_10448_2023: 'properties'

 84%|████████▍ | 3618/4292 [16:04<01:34,  7.10it/s]

Failed for utility IN_12377_2023: 'properties'
Failed for utility IN_12929_2023: 'properties'

 84%|████████▍ | 3620/4292 [16:04<01:31,  7.34it/s]

Failed for utility IN_13647_2023: 'properties'
Failed for utility IN_13756_2023: 'properties'

 84%|████████▍ | 3622/4292 [16:04<01:35,  7.04it/s]

Failed for utility IN_14839_2023: 'properties'
Failed for utility IN_15470_2023: 'properties'

 84%|████████▍ | 3624/4292 [16:04<01:20,  8.35it/s]

Failed for utility IN_15989_2023: 'properties'
Failed for utility IN_17038_2023: 'properties'

 84%|████████▍ | 3626/4292 [16:05<01:20,  8.25it/s]

Failed for utility IN_17599_2023: 'properties'
Failed for utility IN_17633_2023: 'properties'

 85%|████████▍ | 3628/4292 [16:05<01:17,  8.53it/s]

Failed for utility IN_18940_2023: 'properties'
Failed for utility IN_19445_2023: 'properties'

 85%|████████▍ | 3630/4292 [16:05<01:19,  8.36it/s]

Failed for utility IN_19667_2023: 'properties'
Failed for utility IN_20216_2023: 'properties'

 85%|████████▍ | 3632/4292 [16:05<01:19,  8.27it/s]

Failed for utility IN_20603_2023: 'properties'
Failed for utility IN_22822_2023: 'properties'

 85%|████████▍ | 3634/4292 [16:06<01:26,  7.65it/s]

Failed for utility IN_24753_2023: 'properties'
Failed for utility IN_25295_2023: 'properties'

 85%|████████▍ | 3636/4292 [16:06<01:15,  8.70it/s]

Failed for utility IN_27599_2023: 'properties'
Failed for utility KS_5860_2023: 'properties'

 85%|████████▍ | 3638/4292 [16:06<01:14,  8.81it/s]

Failed for utility KS_9996_2023: 'properties'
Failed for utility KS_10000_2023: 'properties'

 85%|████████▍ | 3640/4292 [16:06<01:19,  8.24it/s]

Failed for utility KS_10005_2023: 'properties'
Failed for utility KS_10019_2023: 'properties'

 85%|████████▍ | 3643/4292 [16:07<01:08,  9.41it/s]

Failed for utility KS_12208_2023: 'properties'
Failed for utility KS_13799_2023: 'properties'
Failed for utility KS_15073_2023: 'properties'

 85%|████████▍ | 3645/4292 [16:07<01:16,  8.43it/s]

Failed for utility KS_19160_2023: 'properties'
Failed for utility KS_19820_2023: 'properties'

 85%|████████▍ | 3647/4292 [16:07<01:16,  8.43it/s]

Failed for utility KS_20476_2023: 'properties'
Failed for utility KS_20510_2023: 'properties'

 85%|████████▌ | 3649/4292 [16:07<01:17,  8.34it/s]

Failed for utility KS_22500_2023: 'properties'
Failed for utility KY_690_2023: 'properties'

 85%|████████▌ | 3651/4292 [16:08<01:26,  7.40it/s]

Failed for utility KY_1708_2023: 'properties'
Failed for utility KY_1886_2023: 'properties'

 85%|████████▌ | 3653/4292 [16:08<01:28,  7.25it/s]

Failed for utility KY_3687_2023: 'properties'
Failed for utility KY_4622_2023: 'properties'

 85%|████████▌ | 3655/4292 [16:08<01:24,  7.58it/s]

Failed for utility KY_6194_2023: 'properties'
Failed for utility KY_6442_2023: 'properties'

 85%|████████▌ | 3657/4292 [16:08<01:15,  8.42it/s]

Failed for utility KY_6708_2023: 'properties'
Failed for utility KY_7558_2023: 'properties'

 85%|████████▌ | 3659/4292 [16:09<01:19,  7.98it/s]

Failed for utility KY_8449_2023: 'properties'
Failed for utility KY_9292_2023: 'properties'

 85%|████████▌ | 3661/4292 [16:09<01:30,  6.96it/s]

Failed for utility KY_9575_2023: 'properties'
Failed for utility KY_9605_2023: 'properties'

 85%|████████▌ | 3662/4292 [16:09<01:25,  7.35it/s]

Failed for utility KY_9964_2023: 'properties'

 85%|████████▌ | 3664/4292 [16:09<01:36,  6.47it/s]

Failed for utility KY_10171_2023: 'properties'
Failed for utility KY_11249_2023: 'properties'

 85%|████████▌ | 3666/4292 [16:10<01:30,  6.88it/s]

Failed for utility KY_12243_2023: 'properties'
Failed for utility KY_13651_2023: 'properties'

 85%|████████▌ | 3668/4292 [16:10<01:20,  7.75it/s]

Failed for utility KY_14251_2023: 'properties'
Failed for utility KY_14268_2023: 'properties'

 86%|████████▌ | 3670/4292 [16:10<01:21,  7.65it/s]

Failed for utility KY_16587_2023: 'properties'
Failed for utility KY_17044_2023: 'properties'

 86%|████████▌ | 3672/4292 [16:10<01:18,  7.85it/s]

Failed for utility KY_17564_2023: 'properties'
Failed for utility KY_18498_2023: 'properties'

 86%|████████▌ | 3674/4292 [16:11<01:14,  8.25it/s]

Failed for utility KY_19446_2023: 'properties'
Failed for utility KY_22053_2023: 'properties'

 86%|████████▌ | 3676/4292 [16:11<01:17,  7.93it/s]

Failed for utility KY_49998_2023: 'properties'
Failed for utility LA_298_2023: 'properties'

 86%|████████▌ | 3678/4292 [16:11<01:21,  7.54it/s]

Failed for utility LA_1458_2023: 'properties'
Failed for utility LA_3265_2023: 'properties'

 86%|████████▌ | 3680/4292 [16:11<01:21,  7.48it/s]

Failed for utility LA_3641_2023: 'properties'
Failed for utility LA_4153_2023: 'properties'

 86%|████████▌ | 3683/4292 [16:12<01:07,  9.01it/s]

Failed for utility LA_5202_2023: 'properties'
Failed for utility LA_9096_2023: 'properties'
Failed for utility LA_9682_2023: 'properties'

 86%|████████▌ | 3684/4292 [16:12<01:13,  8.30it/s]

Failed for utility LA_11241_2023: 'properties'
Failed for utility LA_13228_2023: 'properties'

 86%|████████▌ | 3687/4292 [16:12<01:14,  8.13it/s]

Failed for utility LA_13478_2023: 'properties'
Failed for utility LA_13783_2023: 'properties'

 86%|████████▌ | 3689/4292 [16:12<01:09,  8.74it/s]

Failed for utility LA_14424_2023: 'properties'
Failed for utility LA_15175_2023: 'properties'

 86%|████████▌ | 3691/4292 [16:13<01:09,  8.62it/s]

Failed for utility LA_16463_2023: 'properties'
Failed for utility LA_17565_2023: 'properties'

 86%|████████▌ | 3693/4292 [16:13<01:14,  8.06it/s]

Failed for utility LA_17684_2023: 'properties'
Failed for utility LA_17698_2023: 'properties'

 86%|████████▌ | 3695/4292 [16:13<01:14,  8.02it/s]

Failed for utility LA_21567_2023: 'properties'
Failed for utility MA_2144_2023: 'properties'

 86%|████████▌ | 3697/4292 [16:13<01:06,  8.94it/s]

Failed for utility MA_3477_2023: 'properties'
Failed for utility MA_5480_2023: 'properties'
Failed for utility MA_6374_2023: 'properties'

 86%|████████▌ | 3700/4292 [16:14<01:05,  9.10it/s]

Failed for utility MA_8774_2023: 'properties'
Failed for utility MA_11085_2023: 'properties'

 86%|████████▋ | 3702/4292 [16:14<01:06,  8.87it/s]

Failed for utility MA_11586_2023: 'properties'
Failed for utility MA_11804_2023: 'properties'

 86%|████████▋ | 3704/4292 [16:14<01:05,  9.02it/s]

Failed for utility MA_12473_2023: 'properties'
Failed for utility MA_13206_2023: 'properties'

 86%|████████▋ | 3706/4292 [16:14<01:06,  8.87it/s]

Failed for utility MA_13679_2023: 'properties'
Failed for utility MA_14605_2023: 'properties'

 86%|████████▋ | 3707/4292 [16:15<01:10,  8.28it/s]

Failed for utility MA_15748_2023: 'properties'
Failed for utility MA_17127_2023: 'properties'

 86%|████████▋ | 3710/4292 [16:15<01:11,  8.08it/s]

Failed for utility MA_18087_2023: 'properties'
Failed for utility MA_18488_2023: 'properties'

 87%|████████▋ | 3713/4292 [16:15<01:04,  9.01it/s]

Failed for utility MA_20310_2023: 'properties'
Failed for utility MA_54913_2023: 'properties'
Failed for utility MD_1167_2023: 'properties'

 87%|████████▋ | 3715/4292 [16:15<01:03,  9.14it/s]

Failed for utility MD_3503_2023: 'properties'
Failed for utility MD_5027_2023: 'properties'

 87%|████████▋ | 3717/4292 [16:16<01:03,  9.13it/s]

Failed for utility MD_5625_2023: 'properties'
Failed for utility MD_7908_2023: 'properties'

 87%|████████▋ | 3719/4292 [16:16<01:03,  8.99it/s]

Failed for utility MD_15263_2023: 'properties'
Failed for utility MD_15270_2023: 'properties'

 87%|████████▋ | 3721/4292 [16:16<01:07,  8.44it/s]

Failed for utility MD_17637_2023: 'properties'
Failed for utility ME_1179_2023: 'properties'

 87%|████████▋ | 3723/4292 [16:16<01:09,  8.19it/s]

Failed for utility ME_3266_2023: 'properties'
Failed for utility ME_5609_2023: 'properties'

 87%|████████▋ | 3725/4292 [16:17<01:06,  8.56it/s]

Failed for utility MI_305_2023: 'properties'
Failed for utility MI_392_2023: 'properties'

 87%|████████▋ | 3727/4292 [16:17<01:14,  7.60it/s]

Failed for utility MI_1196_2023: 'properties'
Failed for utility MI_1366_2023: 'properties'

 87%|████████▋ | 3730/4292 [16:17<01:07,  8.32it/s]

Failed for utility MI_3436_2023: 'properties'
Failed for utility MI_3828_2023: 'properties'
Failed for utility MI_4254_2023: 'properties'

 87%|████████▋ | 3732/4292 [16:18<01:04,  8.65it/s]

Failed for utility MI_4604_2023: 'properties'
Failed for utility MI_5109_2023: 'properties'

 87%|████████▋ | 3734/4292 [16:18<01:06,  8.45it/s]

Failed for utility MI_7265_2023: 'properties'
Failed for utility MI_7483_2023: 'properties'

 87%|████████▋ | 3736/4292 [16:18<01:05,  8.54it/s]

Failed for utility MI_8723_2023: 'properties'
Failed for utility MI_9324_2023: 'properties'

 87%|████████▋ | 3738/4292 [16:18<01:02,  8.87it/s]

Failed for utility MI_10508_2023: 'properties'
Failed for utility MI_10704_2023: 'properties'

 87%|████████▋ | 3741/4292 [16:19<00:58,  9.35it/s]

Failed for utility MI_11701_2023: 'properties'
Failed for utility MI_12377_2023: 'properties'
Failed for utility MI_13352_2023: 'properties'

 87%|████████▋ | 3743/4292 [16:19<00:59,  9.25it/s]

Failed for utility MI_13826_2023: 'properties'
Failed for utility MI_15340_2023: 'properties'

 87%|████████▋ | 3745/4292 [16:19<01:03,  8.63it/s]

Failed for utility MI_18252_2023: 'properties'
Failed for utility MI_19125_2023: 'properties'

 87%|████████▋ | 3748/4292 [16:19<00:57,  9.43it/s]

Failed for utility MI_19396_2023: 'properties'
Failed for utility MI_19578_2023: 'properties'
Failed for utility MI_21048_2023: 'properties'

 87%|████████▋ | 3750/4292 [16:20<00:56,  9.52it/s]

Failed for utility MI_21158_2023: 'properties'
Failed for utility MI_38084_2023: 'properties'

 87%|████████▋ | 3752/4292 [16:20<00:58,  9.17it/s]

Failed for utility MN_155_2023: 'properties'
Failed for utility MN_295_2023: 'properties'

 87%|████████▋ | 3754/4292 [16:20<01:06,  8.13it/s]

Failed for utility MN_689_2023: 'properties'
Failed for utility MN_691_2023: 'properties'

 88%|████████▊ | 3756/4292 [16:20<01:07,  7.91it/s]

Failed for utility MN_1009_2023: 'properties'
Failed for utility MN_1529_2023: 'properties'

 88%|████████▊ | 3758/4292 [16:21<01:06,  8.07it/s]

Failed for utility MN_1884_2023: 'properties'
Failed for utility MN_3400_2023: 'properties'

 88%|████████▊ | 3760/4292 [16:21<01:08,  7.74it/s]

Failed for utility MN_4577_2023: 'properties'
Failed for utility MN_5574_2023: 'properties'

 88%|████████▊ | 3762/4292 [16:21<01:07,  7.81it/s]

Failed for utility MN_5773_2023: 'properties'
Failed for utility MN_6258_2023: 'properties'

 88%|████████▊ | 3764/4292 [16:21<01:06,  7.98it/s]

Failed for utility MN_6782_2023: 'properties'
Failed for utility MN_8319_2023: 'properties'

 88%|████████▊ | 3766/4292 [16:22<01:06,  7.92it/s]

Failed for utility MN_9475_2023: 'properties'
Failed for utility MN_10596_2023: 'properties'

 88%|████████▊ | 3768/4292 [16:22<01:02,  8.38it/s]

Failed for utility MN_10618_2023: 'properties'
Failed for utility MN_10697_2023: 'properties'

 88%|████████▊ | 3769/4292 [16:22<01:04,  8.13it/s]

Failed for utility MN_11731_2023: 'properties'

 88%|████████▊ | 3771/4292 [16:22<01:13,  7.14it/s]

Failed for utility MN_12227_2023: 'properties'
Failed for utility MN_12546_2023: 'properties'

 88%|████████▊ | 3773/4292 [16:23<01:17,  6.71it/s]

Failed for utility MN_12647_2023: 'properties'
Failed for utility MN_12651_2023: 'properties'

 88%|████████▊ | 3775/4292 [16:23<01:13,  7.06it/s]

Failed for utility MN_12894_2023: 'properties'
Failed for utility MN_13781_2023: 'properties'

 88%|████████▊ | 3778/4292 [16:23<00:59,  8.58it/s]

Failed for utility MN_14232_2023: 'properties'
Failed for utility MN_14246_2023: 'properties'
Failed for utility MN_14468_2023: 'properties'

 88%|████████▊ | 3779/4292 [16:23<01:00,  8.44it/s]

Failed for utility MN_16181_2023: 'properties'
Failed for utility MN_16368_2023: 'properties'

 88%|████████▊ | 3781/4292 [16:23<00:58,  8.69it/s]

Failed for utility MN_16971_2023: 'properties'
Failed for utility MN_17267_2023: 'properties'

 88%|████████▊ | 3784/4292 [16:24<01:03,  7.96it/s]

Failed for utility MN_17550_2023: 'properties'
Failed for utility MN_18019_2023: 'properties'

 88%|████████▊ | 3786/4292 [16:24<00:56,  8.97it/s]

Failed for utility MN_18047_2023: 'properties'
Failed for utility MN_19157_2023: 'properties'

 88%|████████▊ | 3788/4292 [16:24<01:06,  7.54it/s]

Failed for utility MN_20639_2023: 'properties'
Failed for utility MN_20737_2023: 'properties'

 88%|████████▊ | 3789/4292 [16:25<01:05,  7.66it/s]

Failed for utility MN_20996_2023: 'properties'
Failed for utility MN_21013_2023: 'properties'

 88%|████████▊ | 3792/4292 [16:25<01:01,  8.19it/s]

Failed for utility MN_25177_2023: 'properties'
Failed for utility MN_40304_2023: 'properties'

 88%|████████▊ | 3794/4292 [16:25<01:06,  7.49it/s]

Failed for utility MO_1775_2023: 'properties'
Failed for utility MO_2001_2023: 'properties'

 88%|████████▊ | 3796/4292 [16:25<01:00,  8.17it/s]

Failed for utility MO_3113_2023: 'properties'
Failed for utility MO_3268_2023: 'properties'

 88%|████████▊ | 3798/4292 [16:26<00:58,  8.51it/s]

Failed for utility MO_3600_2023: 'properties'
Failed for utility MO_4045_2023: 'properties'

 89%|████████▊ | 3801/4292 [16:26<00:59,  8.30it/s]

Failed for utility MO_4063_2023: 'properties'
Failed for utility MO_4160_2023: 'properties'
Failed for utility MO_4237_2023: 'properties'

 89%|████████▊ | 3803/4292 [16:26<00:58,  8.30it/s]

Failed for utility MO_4524_2023: 'properties'
Failed for utility MO_4675_2023: 'properties'

 89%|████████▊ | 3805/4292 [16:26<00:57,  8.50it/s]

Failed for utility MO_5860_2023: 'properties'
Failed for utility MO_6181_2023: 'properties'

 89%|████████▊ | 3807/4292 [16:27<01:00,  8.07it/s]

Failed for utility MO_6205_2023: 'properties'
Failed for utility MO_7024_2023: 'properties'

 89%|████████▊ | 3809/4292 [16:27<00:57,  8.41it/s]

Failed for utility MO_8055_2023: 'properties'
Failed for utility MO_8934_2023: 'properties'

 89%|████████▉ | 3810/4292 [16:27<01:02,  7.77it/s]

Failed for utility MO_9231_2023: 'properties'
Failed for utility MO_9331_2023: 'properties'

 89%|████████▉ | 3813/4292 [16:27<01:00,  7.96it/s]

Failed for utility MO_10000_2023: 'properties'
Failed for utility MO_10370_2023: 'properties'

 89%|████████▉ | 3815/4292 [16:28<00:55,  8.58it/s]

Failed for utility MO_10603_2023: 'properties'
Failed for utility MO_10832_2023: 'properties'

 89%|████████▉ | 3817/4292 [16:28<00:53,  8.84it/s]

Failed for utility MO_11463_2023: 'properties'
Failed for utility MO_12698_2023: 'properties'

 89%|████████▉ | 3819/4292 [16:28<00:57,  8.19it/s]

Failed for utility MO_12700_2023: 'properties'
Failed for utility MO_12782_2023: 'properties'

 89%|████████▉ | 3821/4292 [16:28<00:58,  8.11it/s]

Failed for utility MO_13520_2023: 'properties'
Failed for utility MO_14192_2023: 'properties'

 89%|████████▉ | 3823/4292 [16:29<00:56,  8.32it/s]

Failed for utility MO_14285_2023: 'properties'
Failed for utility MO_14288_2023: 'properties'

 89%|████████▉ | 3825/4292 [16:29<01:00,  7.72it/s]

Failed for utility MO_15138_2023: 'properties'
Failed for utility MO_15229_2023: 'properties'

 89%|████████▉ | 3827/4292 [16:29<00:57,  8.07it/s]

Failed for utility MO_16259_2023: 'properties'
Failed for utility MO_16751_2023: 'properties'

 89%|████████▉ | 3829/4292 [16:29<00:57,  8.11it/s]

Failed for utility MO_16805_2023: 'properties'
Failed for utility MO_17177_2023: 'properties'

 89%|████████▉ | 3831/4292 [16:30<01:03,  7.31it/s]

Failed for utility MO_17833_2023: 'properties'
Failed for utility MO_19436_2023: 'properties'

 89%|████████▉ | 3833/4292 [16:30<01:05,  7.01it/s]

Failed for utility MO_20318_2023: 'properties'
Failed for utility MO_20363_2023: 'properties'

 89%|████████▉ | 3835/4292 [16:30<00:59,  7.63it/s]

Failed for utility MO_20574_2023: 'properties'
Failed for utility MO_27238_2023: 'properties'

 89%|████████▉ | 3837/4292 [16:30<00:55,  8.19it/s]

Failed for utility MS_3841_2023: 'properties'
Failed for utility MS_5175_2023: 'properties'

 89%|████████▉ | 3839/4292 [16:31<01:02,  7.26it/s]

Failed for utility MS_11519_2023: 'properties'
Failed for utility MS_12685_2023: 'properties'

 89%|████████▉ | 3841/4292 [16:31<00:57,  7.81it/s]

Failed for utility MS_12686_2023: 'properties'
Failed for utility MS_14563_2023: 'properties'

 90%|████████▉ | 3843/4292 [16:31<00:57,  7.79it/s]

Failed for utility MS_17647_2023: 'properties'
Failed for utility MS_22815_2023: 'properties'

 90%|████████▉ | 3845/4292 [16:31<00:52,  8.56it/s]

Failed for utility MT_6169_2023: 'properties'
Failed for utility MT_6395_2023: 'properties'

 90%|████████▉ | 3847/4292 [16:32<00:51,  8.66it/s]

Failed for utility MT_11272_2023: 'properties'
Failed for utility MT_12199_2023: 'properties'

 90%|████████▉ | 3849/4292 [16:32<00:51,  8.59it/s]

Failed for utility MT_12692_2023: 'properties'
Failed for utility MT_12825_2023: 'properties'

 90%|████████▉ | 3851/4292 [16:32<00:57,  7.65it/s]

Failed for utility MT_19603_2023: 'properties'
Failed for utility MT_20997_2023: 'properties'

 90%|████████▉ | 3853/4292 [16:32<00:56,  7.76it/s]

Failed for utility MT_21513_2023: 'properties'
Failed for utility NC_240_2023: 'properties'

 90%|████████▉ | 3855/4292 [16:33<00:54,  7.98it/s]

Failed for utility NC_719_2023: 'properties'
Failed for utility NC_1889_2023: 'properties'

 90%|████████▉ | 3857/4292 [16:33<01:00,  7.21it/s]

Failed for utility NC_3046_2023: 'properties'
Failed for utility NC_5416_2023: 'properties'

 90%|████████▉ | 3859/4292 [16:33<01:02,  6.90it/s]

Failed for utility NC_6640_2023: 'properties'
Failed for utility NC_6784_2023: 'properties'

 90%|████████▉ | 3861/4292 [16:33<00:54,  7.87it/s]

Failed for utility NC_7639_2023: 'properties'
Failed for utility NC_8333_2023: 'properties'

 90%|█████████ | 3863/4292 [16:34<00:51,  8.35it/s]

Failed for utility NC_9837_2023: 'properties'
Failed for utility NC_14717_2023: 'properties'

 90%|█████████ | 3865/4292 [16:34<00:49,  8.56it/s]

Failed for utility NC_15023_2023: 'properties'
Failed for utility NC_16101_2023: 'properties'

 90%|█████████ | 3868/4292 [16:34<00:47,  8.94it/s]

Failed for utility NC_16496_2023: 'properties'
Failed for utility NC_17572_2023: 'properties'
Failed for utility NC_18957_2023: 'properties'

 90%|█████████ | 3870/4292 [16:35<00:49,  8.55it/s]

Failed for utility NC_19435_2023: 'properties'
Failed for utility NC_19876_2023: 'properties'

 90%|█████████ | 3872/4292 [16:35<00:55,  7.56it/s]

Failed for utility NC_19981_2023: 'properties'
Failed for utility NC_21632_2023: 'properties'

 90%|█████████ | 3873/4292 [16:35<00:56,  7.43it/s]

Failed for utility NC_24889_2023: 'properties'
Failed for utility ND_2394_2023: 'properties'

 90%|█████████ | 3876/4292 [16:35<00:50,  8.16it/s]

Failed for utility ND_12090_2023: 'properties'
Failed for utility ND_12301_2023: 'properties'

 90%|█████████ | 3878/4292 [16:36<00:51,  8.04it/s]

Failed for utility ND_14232_2023: 'properties'
Failed for utility ND_19790_2023: 'properties'

 90%|█████████ | 3880/4292 [16:36<00:47,  8.64it/s]

Failed for utility ND_20413_2023: 'properties'
Failed for utility ND_24949_2023: 'properties'

 90%|█████████ | 3882/4292 [16:36<00:52,  7.79it/s]

Failed for utility NE_2643_2023: 'properties'
Failed for utility NE_3205_2023: 'properties'

 90%|█████████ | 3884/4292 [16:36<00:51,  7.95it/s]

Failed for utility NE_4373_2023: 'properties'
Failed for utility NE_4671_2023: 'properties'

 91%|█████████ | 3885/4292 [16:36<00:49,  8.18it/s]

Failed for utility NE_4911_2023: 'properties'
Failed for utility NE_5780_2023: 'properties'

 91%|█████████ | 3889/4292 [16:37<00:42,  9.50it/s]

Failed for utility NE_6779_2023: 'properties'
Failed for utility NE_8245_2023: 'properties'
Failed for utility NE_8570_2023: 'properties'

 91%|█████████ | 3891/4292 [16:37<00:44,  8.99it/s]

Failed for utility NE_10967_2023: 'properties'
Failed for utility NE_11018_2023: 'properties'

 91%|█████████ | 3893/4292 [16:37<00:50,  7.90it/s]

Failed for utility NE_11251_2023: 'properties'
Failed for utility NE_12539_2023: 'properties'

 91%|█████████ | 3895/4292 [16:38<00:53,  7.47it/s]

Failed for utility NE_13337_2023: 'properties'
Failed for utility NE_13664_2023: 'properties'

 91%|█████████ | 3897/4292 [16:38<01:02,  6.29it/s]

Failed for utility NE_13725_2023: 'properties'
Failed for utility NE_13739_2023: 'properties'

 91%|█████████ | 3899/4292 [16:38<00:59,  6.61it/s]

Failed for utility NE_14127_2023: 'properties'
Failed for utility NE_17577_2023: 'properties'

 91%|█████████ | 3901/4292 [16:39<00:58,  6.70it/s]

Failed for utility NE_17642_2023: 'properties'
Failed for utility NE_17692_2023: 'properties'

 91%|█████████ | 3903/4292 [16:39<00:51,  7.56it/s]

Failed for utility NE_21111_2023: 'properties'
Failed for utility NE_27058_2023: 'properties'

 91%|█████████ | 3905/4292 [16:39<00:46,  8.25it/s]

Failed for utility NE_40606_2023: 'properties'
Failed for utility NH_13441_2023: 'properties'

 91%|█████████ | 3907/4292 [16:39<00:44,  8.66it/s]

Failed for utility NH_15472_2023: 'properties'
Failed for utility NH_24590_2023: 'properties'

 91%|█████████ | 3908/4292 [16:39<00:45,  8.42it/s]

Failed for utility NJ_963_2023: 'properties'

 91%|█████████ | 3910/4292 [16:40<00:52,  7.29it/s]

Failed for utility NJ_9726_2023: 'properties'
Failed for utility NJ_15477_2023: 'properties'

 91%|█████████ | 3913/4292 [16:40<00:43,  8.72it/s]

Failed for utility NJ_16213_2023: 'properties'
Failed for utility NJ_19856_2023: 'properties'
Failed for utility NM_3273_2023: 'properties'

 91%|█████████ | 3915/4292 [16:40<00:45,  8.32it/s]

Failed for utility NM_3287_2023: 'properties'
Failed for utility NM_4265_2023: 'properties'

 91%|█████████▏| 3917/4292 [16:41<00:45,  8.20it/s]

Failed for utility NM_5701_2023: 'properties'
Failed for utility NM_6198_2023: 'properties'

 91%|█████████▏| 3919/4292 [16:41<00:44,  8.33it/s]

Failed for utility NM_6204_2023: 'properties'
Failed for utility NM_9699_2023: 'properties'

 91%|█████████▏| 3921/4292 [16:41<00:43,  8.61it/s]

Failed for utility NM_10378_2023: 'properties'
Failed for utility NM_11204_2023: 'properties'

 91%|█████████▏| 3923/4292 [16:41<00:46,  7.99it/s]

Failed for utility NM_13318_2023: 'properties'
Failed for utility NM_14224_2023: 'properties'

 91%|█████████▏| 3925/4292 [16:41<00:43,  8.44it/s]

Failed for utility NM_15473_2023: 'properties'
Failed for utility NM_17715_2023: 'properties'

 91%|█████████▏| 3927/4292 [16:42<00:47,  7.76it/s]

Failed for utility NM_17718_2023: 'properties'
Failed for utility NM_17826_2023: 'properties'

 92%|█████████▏| 3929/4292 [16:42<00:43,  8.30it/s]

Failed for utility NV_2008_2023: 'properties'
Failed for utility NV_13073_2023: 'properties'

 92%|█████████▏| 3931/4292 [16:42<00:45,  7.87it/s]

Failed for utility NV_13407_2023: 'properties'
Failed for utility NV_14245_2023: 'properties'

 92%|█████████▏| 3933/4292 [16:42<00:44,  8.09it/s]

Failed for utility NV_17166_2023: 'properties'
Failed for utility NV_19840_2023: 'properties'

 92%|█████████▏| 3934/4292 [16:43<00:46,  7.72it/s]

Failed for utility NY_3249_2023: 'properties'

 92%|█████████▏| 3935/4292 [16:43<00:54,  6.49it/s]

Failed for utility NY_4226_2023: 'properties'

 92%|█████████▏| 3937/4292 [16:43<00:58,  6.11it/s]

Failed for utility NY_11171_2023: 'properties'
Failed for utility NY_11811_2023: 'properties'

 92%|█████████▏| 3938/4292 [16:43<00:56,  6.30it/s]

Failed for utility NY_13511_2023: 'properties'

 92%|█████████▏| 3940/4292 [16:44<00:57,  6.16it/s]

Failed for utility NY_13573_2023: 'properties'
Failed for utility NY_14154_2023: 'properties'

 92%|█████████▏| 3943/4292 [16:44<00:45,  7.63it/s]

Failed for utility NY_14711_2023: 'properties'
Failed for utility NY_16183_2023: 'properties'
Failed for utility OH_2651_2023: 'properties'

 92%|█████████▏| 3945/4292 [16:44<00:50,  6.94it/s]

Failed for utility OH_3542_2023: 'properties'
Failed for utility OH_3755_2023: 'properties'

 92%|█████████▏| 3947/4292 [16:45<00:41,  8.28it/s]

Failed for utility OH_3762_2023: 'properties'
Failed for utility OH_4683_2023: 'properties'

 92%|█████████▏| 3949/4292 [16:45<00:44,  7.74it/s]

Failed for utility OH_4922_2023: 'properties'
Failed for utility OH_7891_2023: 'properties'

 92%|█████████▏| 3951/4292 [16:45<00:42,  8.02it/s]

Failed for utility OH_8761_2023: 'properties'
Failed for utility OH_10830_2023: 'properties'

 92%|█████████▏| 3953/4292 [16:45<00:41,  8.26it/s]

Failed for utility OH_12377_2023: 'properties'
Failed for utility OH_12990_2023: 'properties'

 92%|█████████▏| 3955/4292 [16:46<00:49,  6.85it/s]

Failed for utility OH_13998_2023: 'properties'
Failed for utility OH_14006_2023: 'properties'

 92%|█████████▏| 3957/4292 [16:46<00:47,  7.03it/s]

Failed for utility OH_18997_2023: 'properties'
Failed for utility OH_19951_2023: 'properties'

 92%|█████████▏| 3959/4292 [16:46<00:48,  6.83it/s]

Failed for utility OH_20477_2023: 'properties'
Failed for utility OK_296_2023: 'properties'

 92%|█████████▏| 3960/4292 [16:46<00:44,  7.51it/s]

Failed for utility OK_817_2023: 'properties'

 92%|█████████▏| 3962/4292 [16:47<00:48,  6.79it/s]

Failed for utility OK_3226_2023: 'properties'
Failed for utility OK_3478_2023: 'properties'

 92%|█████████▏| 3964/4292 [16:47<00:45,  7.19it/s]

Failed for utility OK_3527_2023: 'properties'
Failed for utility OK_3647_2023: 'properties'

 92%|█████████▏| 3966/4292 [16:47<00:42,  7.76it/s]

Failed for utility OK_4296_2023: 'properties'
Failed for utility OK_4401_2023: 'properties'

 92%|█████████▏| 3967/4292 [16:47<00:39,  8.21it/s]

Failed for utility OK_5598_2023: 'properties'
Failed for utility OK_5661_2023: 'properties'

 92%|█████████▏| 3970/4292 [16:48<00:39,  8.12it/s]

Failed for utility OK_5860_2023: 'properties'
Failed for utility OK_9246_2023: 'properties'

 93%|█████████▎| 3972/4292 [16:48<00:39,  8.02it/s]

Failed for utility OK_10170_2023: 'properties'
Failed for utility OK_10599_2023: 'properties'

 93%|█████████▎| 3974/4292 [16:48<00:40,  7.92it/s]

Failed for utility OK_13734_2023: 'properties'
Failed for utility OK_14062_2023: 'properties'

 93%|█████████▎| 3976/4292 [16:48<00:44,  7.15it/s]

Failed for utility OK_14063_2023: 'properties'
Failed for utility OK_14289_2023: 'properties'

 93%|█████████▎| 3978/4292 [16:49<00:45,  6.92it/s]

Failed for utility OK_14775_2023: 'properties'
Failed for utility OK_15474_2023: 'properties'

 93%|█████████▎| 3980/4292 [16:49<00:46,  6.73it/s]

Failed for utility OK_16382_2023: 'properties'
Failed for utility OK_17671_2023: 'properties'

 93%|█████████▎| 3981/4292 [16:49<00:45,  6.87it/s]

Failed for utility OK_18125_2023: 'properties'
Failed for utility OK_19160_2023: 'properties'

 93%|█████████▎| 3984/4292 [16:50<00:41,  7.48it/s]

Failed for utility OK_19785_2023: 'properties'
Failed for utility OR_3240_2023: 'properties'

 93%|█████████▎| 3986/4292 [16:50<00:39,  7.75it/s]

Failed for utility OR_3264_2023: 'properties'
Failed for utility OR_4317_2023: 'properties'

 93%|█████████▎| 3988/4292 [16:50<00:37,  8.08it/s]

Failed for utility OR_4743_2023: 'properties'
Failed for utility OR_6022_2023: 'properties'

 93%|█████████▎| 3990/4292 [16:50<00:36,  8.19it/s]

Failed for utility OR_6582_2023: 'properties'
Failed for utility OR_9191_2023: 'properties'

 93%|█████████▎| 3992/4292 [16:51<00:35,  8.35it/s]

Failed for utility OR_10681_2023: 'properties'
Failed for utility OR_12187_2023: 'properties'

 93%|█████████▎| 3994/4292 [16:51<00:35,  8.36it/s]

Failed for utility OR_12439_2023: 'properties'
Failed for utility OR_13788_2023: 'properties'

 93%|█████████▎| 3996/4292 [16:51<00:37,  7.97it/s]

Failed for utility OR_14109_2023: 'properties'
Failed for utility OR_14354_2023: 'properties'

 93%|█████████▎| 3998/4292 [16:51<00:33,  8.71it/s]

Failed for utility OR_15248_2023: 'properties'
Failed for utility OR_16555_2023: 'properties'
Failed for utility OR_17839_2023: 'properties'

 93%|█████████▎| 4000/4292 [16:51<00:33,  8.67it/s]

Failed for utility OR_18260_2023: 'properties'

 93%|█████████▎| 4002/4292 [16:52<00:40,  7.13it/s]

Failed for utility OR_18917_2023: 'properties'
Failed for utility OR_19325_2023: 'properties'

 93%|█████████▎| 4004/4292 [16:52<00:36,  7.90it/s]

Failed for utility OR_28541_2023: 'properties'
Failed for utility OR_40437_2023: 'properties'

 93%|█████████▎| 4007/4292 [16:52<00:32,  8.86it/s]

Failed for utility OR_40438_2023: 'properties'
Failed for utility PA_3329_2023: 'properties'
Failed for utility PA_3597_2023: 'properties'

 93%|█████████▎| 4009/4292 [16:53<00:35,  7.87it/s]

Failed for utility PA_5487_2023: 'properties'
Failed for utility PA_12390_2023: 'properties'

 93%|█████████▎| 4011/4292 [16:53<00:40,  6.97it/s]

Failed for utility PA_14711_2023: 'properties'
Failed for utility PA_14715_2023: 'properties'

 93%|█████████▎| 4013/4292 [16:53<00:36,  7.58it/s]

Failed for utility PA_14716_2023: 'properties'
Failed for utility PA_14940_2023: 'properties'

 94%|█████████▎| 4015/4292 [16:53<00:33,  8.17it/s]

Failed for utility PA_15045_2023: 'properties'
Failed for utility PA_19390_2023: 'properties'

 94%|█████████▎| 4017/4292 [16:54<00:34,  8.09it/s]

Failed for utility PA_20334_2023: 'properties'
Failed for utility PA_20387_2023: 'properties'

 94%|█████████▎| 4019/4292 [16:54<00:38,  7.08it/s]

Failed for utility PA_40167_2023: 'properties'
Failed for utility PA_40220_2023: 'properties'

 94%|█████████▎| 4021/4292 [16:54<00:34,  7.76it/s]

Failed for utility PA_40221_2023: 'properties'
Failed for utility PA_40222_2023: 'properties'

 94%|█████████▎| 4023/4292 [16:55<00:36,  7.41it/s]

Failed for utility PA_40224_2023: 'properties'
Failed for utility PA_40289_2023: 'properties'

 94%|█████████▍| 4025/4292 [16:55<00:38,  6.99it/s]

Failed for utility PA_40290_2023: 'properties'
Failed for utility PA_40292_2023: 'properties'

 94%|█████████▍| 4027/4292 [16:55<00:34,  7.58it/s]

Failed for utility PA_40293_2023: 'properties'
Failed for utility RI_1857_2023: 'properties'
Failed for utility RI_13214_2023: 'properties'

 94%|█████████▍| 4030/4292 [16:55<00:33,  7.77it/s]

Failed for utility RI_14537_2023: 'properties'
Failed for utility SC_162_2023: 'properties'

 94%|█████████▍| 4032/4292 [16:56<00:31,  8.34it/s]

Failed for utility SC_1613_2023: 'properties'
Failed for utility SC_1763_2023: 'properties'
Failed for utility SC_1890_2023: 'properties'

 94%|█████████▍| 4035/4292 [16:56<00:29,  8.75it/s]

Failed for utility SC_2212_2023: 'properties'
Failed for utility SC_3046_2023: 'properties'

 94%|█████████▍| 4037/4292 [16:56<00:29,  8.60it/s]

Failed for utility SC_5416_2023: 'properties'
Failed for utility SC_5644_2023: 'properties'

 94%|█████████▍| 4039/4292 [16:56<00:29,  8.71it/s]

Failed for utility SC_6709_2023: 'properties'
Failed for utility SC_6894_2023: 'properties'

 94%|█████████▍| 4041/4292 [16:57<00:29,  8.47it/s]

Failed for utility SC_7654_2023: 'properties'
Failed for utility SC_8786_2023: 'properties'

 94%|█████████▍| 4043/4292 [16:57<00:29,  8.58it/s]

Failed for utility SC_10768_2023: 'properties'
Failed for utility SC_11355_2023: 'properties'

 94%|█████████▍| 4045/4292 [16:57<00:32,  7.57it/s]

Failed for utility SC_12462_2023: 'properties'
Failed for utility SC_13523_2023: 'properties'

 94%|█████████▍| 4047/4292 [16:57<00:28,  8.57it/s]

Failed for utility SC_13524_2023: 'properties'
Failed for utility SC_14164_2023: 'properties'
Failed for utility SC_14175_2023: 'properties'

 94%|█████████▍| 4050/4292 [16:58<00:26,  8.99it/s]

Failed for utility SC_14398_2023: 'properties'
Failed for utility SC_16195_2023: 'properties'

 94%|█████████▍| 4052/4292 [16:58<00:26,  8.92it/s]

Failed for utility SC_16606_2023: 'properties'
Failed for utility SC_17539_2023: 'properties'

 94%|█████████▍| 4054/4292 [16:58<00:27,  8.74it/s]

Failed for utility SC_17543_2023: 'properties'
Failed for utility SC_21002_2023: 'properties'

 95%|█████████▍| 4056/4292 [16:58<00:27,  8.54it/s]

Failed for utility SD_1769_2023: 'properties'
Failed for utility SD_14232_2023: 'properties'

 95%|█████████▍| 4058/4292 [16:59<00:27,  8.45it/s]

Failed for utility SD_17267_2023: 'properties'
Failed for utility SD_19293_2023: 'properties'

 95%|█████████▍| 4060/4292 [16:59<00:27,  8.34it/s]

Failed for utility SD_19545_2023: 'properties'
Failed for utility SD_20401_2023: 'properties'

 95%|█████████▍| 4061/4292 [16:59<00:26,  8.70it/s]

Failed for utility TN_10331_2023: 'properties'
Failed for utility TX_1169_2023: 'properties'

 95%|█████████▍| 4064/4292 [16:59<00:26,  8.63it/s]

Failed for utility TX_1175_2023: 'properties'
Failed for utility TX_1273_2023: 'properties'

 95%|█████████▍| 4066/4292 [17:00<00:26,  8.64it/s]

Failed for utility TX_1591_2023: 'properties'
Failed for utility TX_1892_2023: 'properties'

 95%|█████████▍| 4068/4292 [17:00<00:27,  8.05it/s]

Failed for utility TX_2049_2023: 'properties'
Failed for utility TX_2194_2023: 'properties'

 95%|█████████▍| 4070/4292 [17:00<00:28,  7.86it/s]

Failed for utility TX_2409_2023: 'properties'
Failed for utility TX_2442_2023: 'properties'

 95%|█████████▍| 4072/4292 [17:00<00:28,  7.77it/s]

Failed for utility TX_3282_2023: 'properties'
Failed for utility TX_3470_2023: 'properties'

 95%|█████████▍| 4073/4292 [17:00<00:26,  8.31it/s]

Failed for utility TX_4146_2023: 'properties'
Failed for utility TX_4262_2023: 'properties'

 95%|█████████▍| 4076/4292 [17:01<00:25,  8.44it/s]

Failed for utility TX_4295_2023: 'properties'
Failed for utility TX_4939_2023: 'properties'

 95%|█████████▌| 4078/4292 [17:01<00:24,  8.67it/s]

Failed for utility TX_4975_2023: 'properties'
Failed for utility TX_5063_2023: 'properties'

 95%|█████████▌| 4080/4292 [17:01<00:26,  8.08it/s]

Failed for utility TX_5078_2023: 'properties'
Failed for utility TX_5701_2023: 'properties'

 95%|█████████▌| 4082/4292 [17:02<00:24,  8.70it/s]

Failed for utility TX_6182_2023: 'properties'
Failed for utility TX_6183_2023: 'properties'

 95%|█████████▌| 4083/4292 [17:02<00:23,  8.71it/s]

Failed for utility TX_6427_2023: 'properties'
Failed for utility TX_7129_2023: 'properties'

 95%|█████████▌| 4086/4292 [17:02<00:24,  8.53it/s]

Failed for utility TX_7559_2023: 'properties'
Failed for utility TX_7752_2023: 'properties'
Failed for utility TX_7979_2023: 'properties'

 95%|█████████▌| 4090/4292 [17:02<00:20,  9.96it/s]

Failed for utility TX_8620_2023: 'properties'
Failed for utility TX_9590_2023: 'properties'
Failed for utility TX_9668_2023: 'properties'

 95%|█████████▌| 4092/4292 [17:03<00:20,  9.95it/s]

Failed for utility TX_10009_2023: 'properties'
Failed for utility TX_11014_2023: 'properties'

 95%|█████████▌| 4094/4292 [17:03<00:21,  9.27it/s]

Failed for utility TX_11292_2023: 'properties'
Failed for utility TX_11501_2023: 'properties'

 95%|█████████▌| 4097/4292 [17:03<00:20,  9.58it/s]

Failed for utility TX_12268_2023: 'properties'
Failed for utility TX_12452_2023: 'properties'
Failed for utility TX_13332_2023: 'properties'

 96%|█████████▌| 4099/4292 [17:03<00:19,  9.90it/s]

Failed for utility TX_13418_2023: 'properties'
Failed for utility TX_13757_2023: 'properties'

 96%|█████████▌| 4101/4292 [17:04<00:20,  9.12it/s]

Failed for utility TX_14626_2023: 'properties'
Failed for utility TX_16057_2023: 'properties'

 96%|█████████▌| 4103/4292 [17:04<00:21,  8.72it/s]

Failed for utility TX_16063_2023: 'properties'
Failed for utility TX_16146_2023: 'properties'

 96%|█████████▌| 4105/4292 [17:04<00:22,  8.19it/s]

Failed for utility TX_16461_2023: 'properties'
Failed for utility TX_16604_2023: 'properties'

 96%|█████████▌| 4106/4292 [17:04<00:22,  8.36it/s]

Failed for utility TX_16627_2023: 'properties'
Failed for utility TX_16638_2023: 'properties'

 96%|█████████▌| 4109/4292 [17:05<00:20,  9.04it/s]

Failed for utility TX_17561_2023: 'properties'
Failed for utility TX_17671_2023: 'properties'
Failed for utility TX_18976_2023: 'properties'

 96%|█████████▌| 4112/4292 [17:05<00:19,  9.14it/s]

Failed for utility TX_19159_2023: 'properties'
Failed for utility TX_19160_2023: 'properties'

 96%|█████████▌| 4114/4292 [17:05<00:20,  8.68it/s]

Failed for utility TX_19490_2023: 'properties'
Failed for utility TX_19579_2023: 'properties'

 96%|█████████▌| 4116/4292 [17:05<00:20,  8.72it/s]

Failed for utility TX_19806_2023: 'properties'
Failed for utility TX_20230_2023: 'properties'

 96%|█████████▌| 4118/4292 [17:06<00:19,  9.14it/s]

Failed for utility TX_20948_2023: 'properties'
Failed for utility TX_28604_2023: 'properties'

 96%|█████████▌| 4120/4292 [17:06<00:21,  7.89it/s]

Failed for utility TX_28978_2023: 'properties'
Failed for utility TX_55937_2023: 'properties'

 96%|█████████▌| 4122/4292 [17:06<00:21,  7.96it/s]

Failed for utility TX_55982_2023: 'properties'
Failed for utility UT_2010_2023: 'properties'

 96%|█████████▌| 4124/4292 [17:06<00:20,  8.06it/s]

Failed for utility UT_5862_2023: 'properties'
Failed for utility UT_6957_2023: 'properties'

 96%|█████████▌| 4125/4292 [17:06<00:20,  8.20it/s]

Failed for utility UT_10879_2023: 'properties'
Failed for utility UT_11135_2023: 'properties'

 96%|█████████▌| 4128/4292 [17:07<00:19,  8.38it/s]

Failed for utility UT_12866_2023: 'properties'
Failed for utility UT_13137_2023: 'properties'

 96%|█████████▌| 4131/4292 [17:07<00:17,  9.07it/s]

Failed for utility UT_14354_2023: 'properties'
Failed for utility UT_15444_2023: 'properties'
Failed for utility UT_17732_2023: 'properties'

 96%|█████████▋| 4133/4292 [17:07<00:17,  9.35it/s]

Failed for utility UT_17845_2023: 'properties'
Failed for utility UT_17874_2023: 'properties'

 96%|█████████▋| 4135/4292 [17:08<00:18,  8.31it/s]

Failed for utility UT_18206_2023: 'properties'
Failed for utility UT_40165_2023: 'properties'

 96%|█████████▋| 4137/4292 [17:08<00:16,  9.21it/s]

Failed for utility VA_84_2023: 'properties'
Failed for utility VA_733_2023: 'properties'

 96%|█████████▋| 4138/4292 [17:08<00:17,  9.03it/s]

Failed for utility VA_3291_2023: 'properties'
Failed for utility VA_4794_2023: 'properties'

 97%|█████████▋| 4142/4292 [17:08<00:15,  9.97it/s]

Failed for utility VA_8198_2023: 'properties'
Failed for utility VA_10171_2023: 'properties'
Failed for utility VA_12260_2023: 'properties'

 97%|█████████▋| 4144/4292 [17:09<00:18,  8.18it/s]

Failed for utility VA_13640_2023: 'properties'
Failed for utility VA_13762_2023: 'properties'

 97%|█████████▋| 4146/4292 [17:09<00:18,  7.94it/s]

Failed for utility VA_15410_2023: 'properties'
Failed for utility VA_16558_2023: 'properties'

 97%|█████████▋| 4148/4292 [17:09<00:19,  7.30it/s]

Failed for utility VA_17066_2023: 'properties'
Failed for utility VA_19876_2023: 'properties'

 97%|█████████▋| 4151/4292 [17:10<00:18,  7.81it/s]

Failed for utility VA_19882_2023: 'properties'
Failed for utility VA_21244_2023: 'properties'
Failed for utility VA_40228_2023: 'properties'

 97%|█████████▋| 4153/4292 [17:10<00:16,  8.50it/s]

Failed for utility VT_2548_2023: 'properties'
Failed for utility VT_7601_2023: 'properties'

 97%|█████████▋| 4155/4292 [17:10<00:16,  8.46it/s]

Failed for utility VT_19791_2023: 'properties'
Failed for utility VT_20151_2023: 'properties'

 97%|█████████▋| 4156/4292 [17:10<00:16,  8.16it/s]

Failed for utility WA_1579_2023: 'properties'
Failed for utility WA_1625_2023: 'properties'

 97%|█████████▋| 4158/4292 [17:10<00:16,  8.21it/s]

Failed for utility WA_1723_2023: 'properties'
Failed for utility WA_3295_2023: 'properties'

 97%|█████████▋| 4161/4292 [17:11<00:17,  7.46it/s]

Failed for utility WA_3413_2023: 'properties'
Failed for utility WA_3644_2023: 'properties'

 97%|█████████▋| 4163/4292 [17:11<00:15,  8.14it/s]

Failed for utility WA_3660_2023: 'properties'
Failed for utility WA_4041_2023: 'properties'
Failed for utility WA_4442_2023: 'properties'

 97%|█████████▋| 4166/4292 [17:11<00:14,  8.77it/s]

Failed for utility WA_5326_2023: 'properties'
Failed for utility WA_5832_2023: 'properties'

 97%|█████████▋| 4168/4292 [17:12<00:14,  8.56it/s]

Failed for utility WA_6149_2023: 'properties'
Failed for utility WA_6716_2023: 'properties'

 97%|█████████▋| 4170/4292 [17:12<00:14,  8.63it/s]

Failed for utility WA_7548_2023: 'properties'
Failed for utility WA_8699_2023: 'properties'

 97%|█████████▋| 4173/4292 [17:12<00:12,  9.50it/s]

Failed for utility WA_10393_2023: 'properties'
Failed for utility WA_10627_2023: 'properties'
Failed for utility WA_10944_2023: 'properties'

 97%|█████████▋| 4176/4292 [17:12<00:11,  9.70it/s]

Failed for utility WA_12744_2023: 'properties'
Failed for utility WA_14055_2023: 'properties'
Failed for utility WA_14170_2023: 'properties'

 97%|█████████▋| 4178/4292 [17:13<00:12,  9.06it/s]

Failed for utility WA_14324_2023: 'properties'
Failed for utility WA_14354_2023: 'properties'

 97%|█████████▋| 4179/4292 [17:13<00:12,  8.98it/s]

Failed for utility WA_14624_2023: 'properties'
Failed for utility WA_14653_2023: 'properties'

 97%|█████████▋| 4182/4292 [17:13<00:12,  8.86it/s]

Failed for utility WA_14668_2023: 'properties'
Failed for utility WA_15231_2023: 'properties'

 97%|█████████▋| 4184/4292 [17:13<00:12,  8.93it/s]

Failed for utility WA_15419_2023: 'properties'
Failed for utility WA_15500_2023: 'properties'

 98%|█████████▊| 4186/4292 [17:13<00:11,  9.18it/s]

Failed for utility WA_15979_2023: 'properties'
Failed for utility WA_16868_2023: 'properties'

 98%|█████████▊| 4188/4292 [17:14<00:11,  8.86it/s]

Failed for utility WA_17470_2023: 'properties'
Failed for utility WA_18429_2023: 'properties'

 98%|█████████▊| 4190/4292 [17:14<00:11,  8.79it/s]

Failed for utility WA_19784_2023: 'properties'
Failed for utility WA_20169_2023: 'properties'

 98%|█████████▊| 4192/4292 [17:14<00:11,  9.05it/s]

Failed for utility WI_108_2023: 'properties'
Failed for utility WI_307_2023: 'properties'

 98%|█████████▊| 4194/4292 [17:14<00:11,  8.75it/s]

Failed for utility WI_1251_2023: 'properties'
Failed for utility WI_1776_2023: 'properties'

 98%|█████████▊| 4196/4292 [17:15<00:10,  9.04it/s]

Failed for utility WI_1997_2023: 'properties'
Failed for utility WI_2273_2023: 'properties'

 98%|█████████▊| 4197/4292 [17:15<00:11,  8.38it/s]

Failed for utility WI_3208_2023: 'properties'
Failed for utility WI_4073_2023: 'properties'

 98%|█████████▊| 4200/4292 [17:15<00:10,  8.64it/s]

Failed for utility WI_4607_2023: 'properties'
Failed for utility WI_4715_2023: 'properties'

 98%|█████████▊| 4202/4292 [17:15<00:10,  8.38it/s]

Failed for utility WI_5417_2023: 'properties'
Failed for utility WI_5551_2023: 'properties'

 98%|█████████▊| 4204/4292 [17:16<00:10,  8.59it/s]

Failed for utility WI_5574_2023: 'properties'
Failed for utility WI_6043_2023: 'properties'

 98%|█████████▊| 4206/4292 [17:16<00:09,  8.65it/s]

Failed for utility WI_6424_2023: 'properties'
Failed for utility WI_8212_2023: 'properties'

 98%|█████████▊| 4208/4292 [17:16<00:10,  8.17it/s]

Failed for utility WI_9124_2023: 'properties'
Failed for utility WI_9690_2023: 'properties'

 98%|█████████▊| 4210/4292 [17:16<00:08,  9.18it/s]

Failed for utility WI_9936_2023: 'properties'
Failed for utility WI_10056_2023: 'properties'
Failed for utility WI_10605_2023: 'properties'

 98%|█████████▊| 4214/4292 [17:17<00:07, 10.18it/s]

Failed for utility WI_11125_2023: 'properties'
Failed for utility WI_11479_2023: 'properties'
Failed for utility WI_11571_2023: 'properties'

 98%|█████████▊| 4216/4292 [17:17<00:07, 10.02it/s]

Failed for utility WI_11740_2023: 'properties'
Failed for utility WI_12298_2023: 'properties'

 98%|█████████▊| 4218/4292 [17:17<00:08,  8.81it/s]

Failed for utility WI_13036_2023: 'properties'
Failed for utility WI_13145_2023: 'properties'

 98%|█████████▊| 4220/4292 [17:17<00:08,  8.41it/s]

Failed for utility WI_13438_2023: 'properties'
Failed for utility WI_13448_2023: 'properties'

 98%|█████████▊| 4222/4292 [17:18<00:09,  7.70it/s]

Failed for utility WI_13467_2023: 'properties'
Failed for utility WI_13481_2023: 'properties'

 98%|█████████▊| 4224/4292 [17:18<00:09,  7.48it/s]

Failed for utility WI_13697_2023: 'properties'
Failed for utility WI_13780_2023: 'properties'

 98%|█████████▊| 4226/4292 [17:18<00:07,  8.60it/s]

Failed for utility WI_13815_2023: 'properties'
Failed for utility WI_13936_2023: 'properties'

 99%|█████████▊| 4228/4292 [17:18<00:08,  7.86it/s]

Failed for utility WI_13963_2023: 'properties'
Failed for utility WI_15159_2023: 'properties'

 99%|█████████▊| 4230/4292 [17:19<00:07,  7.98it/s]

Failed for utility WI_15312_2023: 'properties'
Failed for utility WI_15344_2023: 'properties'

 99%|█████████▊| 4232/4292 [17:19<00:06,  8.59it/s]

Failed for utility WI_15804_2023: 'properties'
Failed for utility WI_15978_2023: 'properties'

 99%|█████████▊| 4234/4292 [17:19<00:06,  8.34it/s]

Failed for utility WI_16082_2023: 'properties'
Failed for utility WI_16196_2023: 'properties'

 99%|█████████▊| 4236/4292 [17:19<00:06,  8.34it/s]

Failed for utility WI_16740_2023: 'properties'
Failed for utility WI_17324_2023: 'properties'

 99%|█████████▊| 4238/4292 [17:20<00:06,  8.10it/s]

Failed for utility WI_18181_2023: 'properties'
Failed for utility WI_18249_2023: 'properties'

 99%|█████████▉| 4240/4292 [17:20<00:06,  7.93it/s]

Failed for utility WI_18312_2023: 'properties'
Failed for utility WI_19324_2023: 'properties'

 99%|█████████▉| 4242/4292 [17:20<00:05,  8.34it/s]

Failed for utility WI_20182_2023: 'properties'
Failed for utility WI_20211_2023: 'properties'

 99%|█████████▉| 4244/4292 [17:20<00:05,  9.01it/s]

Failed for utility WI_20213_2023: 'properties'
Failed for utility WI_20434_2023: 'properties'

 99%|█████████▉| 4246/4292 [17:21<00:05,  8.99it/s]

Failed for utility WI_20583_2023: 'properties'
Failed for utility WI_20847_2023: 'properties'

 99%|█████████▉| 4248/4292 [17:21<00:05,  8.57it/s]

Failed for utility WI_20856_2023: 'properties'
Failed for utility WI_20860_2023: 'properties'

 99%|█████████▉| 4250/4292 [17:21<00:05,  8.28it/s]

Failed for utility WI_20862_2023: 'properties'
Failed for utility WV_733_2023: 'properties'

 99%|█████████▉| 4252/4292 [17:21<00:05,  7.62it/s]

Failed for utility WV_12796_2023: 'properties'
Failed for utility WV_15263_2023: 'properties'
Failed for utility WV_20521_2023: 'properties'

 99%|█████████▉| 4255/4292 [17:22<00:04,  8.65it/s]

Failed for utility WY_3461_2023: 'properties'
Failed for utility WY_6169_2023: 'properties'

 99%|█████████▉| 4257/4292 [17:22<00:04,  7.77it/s]

Failed for utility WY_7222_2023: 'properties'
Failed for utility WY_8566_2023: 'properties'

 99%|█████████▉| 4259/4292 [17:22<00:04,  7.89it/s]

Failed for utility WY_11273_2023: 'properties'
Failed for utility WY_12199_2023: 'properties'

 99%|█████████▉| 4261/4292 [17:22<00:04,  7.65it/s]

Failed for utility WY_14354_2023: 'properties'
Failed for utility WY_19156_2023: 'properties'

 99%|█████████▉| 4262/4292 [17:23<00:04,  7.35it/s]

Failed for utility WY_27058_2023: 'properties'

 99%|█████████▉| 4263/4292 [17:23<00:04,  6.38it/s]

AL_4958_2012 completed in 0:00:00.205349

 99%|█████████▉| 4264/4292 [17:23<00:04,  5.61it/s]

AL_4958_2013 completed in 0:00:00.227545

 99%|█████████▉| 4265/4292 [17:23<00:05,  4.83it/s]

ID_9187_2011 completed in 0:00:00.272289

 99%|█████████▉| 4267/4292 [17:24<00:05,  4.86it/s]

ID_9187_2012 completed in 0:00:00.217810
ID_9187_2013 completed in 0:00:00.192717

 99%|█████████▉| 4268/4292 [17:24<00:04,  5.39it/s]

MN_16181_2011 completed in 0:00:00.136642

 99%|█████████▉| 4269/4292 [17:24<00:04,  5.06it/s]

MN_16181_2012 completed in 0:00:00.225462

 99%|█████████▉| 4270/4292 [17:24<00:04,  4.91it/s]

MN_16181_2013 completed in 0:00:00.216974

100%|█████████▉| 4271/4292 [17:25<00:05,  3.94it/s]

MS_19273_2012 completed in 0:00:00.369507

100%|█████████▉| 4273/4292 [17:25<00:05,  3.64it/s]

MS_19273_2013 completed in 0:00:00.456885
NH_26510_2014 completed in 0:00:00.179532

100%|█████████▉| 4275/4292 [17:26<00:04,  4.23it/s]

NH_26510_2015 completed in 0:00:00.217549
NH_26510_2016 completed in 0:00:00.184785

100%|█████████▉| 4276/4292 [17:26<00:04,  3.96it/s]

NH_26510_2017 completed in 0:00:00.288813

100%|█████████▉| 4277/4292 [17:26<00:04,  3.74it/s]

NH_26510_2018 completed in 0:00:00.301169

100%|█████████▉| 4278/4292 [17:27<00:03,  3.91it/s]

NH_26510_2019 completed in 0:00:00.227100

100%|█████████▉| 4280/4292 [17:27<00:02,  4.40it/s]

NH_26510_2020 completed in 0:00:00.290144
Failed for utility NH_26510_2021: 'properties'

100%|█████████▉| 4282/4292 [17:27<00:01,  5.95it/s]

Failed for utility NH_26510_2022: 'properties'
Failed for utility NH_26510_2023: 'properties'
Skipping utility TN_3704_2012 due to empty or invalid geometry.
Skipping utility TN_3704_2013 due to empty or invalid geometry.
Skipping utility TN_3758_2012 due to empty or invalid geometry.
Skipping utility TN_3758_2013 due to empty or invalid geometry.

100%|█████████▉| 4287/4292 [17:27<00:00, 13.21it/s]

UT_11135_2011 completed in 0:00:00.149858
UT_11135_2012 completed in 0:00:00.191067

100%|█████████▉| 4289/4292 [17:28<00:00,  9.40it/s]

UT_11135_2013 completed in 0:00:00.178164

100%|█████████▉| 4291/4292 [17:28<00:00,  6.93it/s]

VA_19882_2011 completed in 0:00:00.295016
VA_19882_2012 completed in 0:00:00.182138

100%|██████████| 4292/4292 [17:28<00:00,  4.09it/s]

VA_19882_2013 completed in 0:00:00.180826

/tmp/ipython-input-2731846361.py:70: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(utility_monthly_temp, ignore_index=True)

In [86]:
# read in the dataset
result_df = pd.read_csv('data files/monthly_air_temp_utilities_kelvin.csv')

In [87]:
# check out the data
result_df.head()

       id        date    avg_temp  median_temp     full_id_y  year  month
0  201101  2011-01-01  262.901527   262.708801  AK_1651_2011  2011      1
1  201102  2011-02-01  262.651882   262.448761  AK_1651_2011  2011      2
2  201103  2011-03-01  263.460223   263.237762  AK_1651_2011  2011      3
3  201104  2011-04-01  269.190750   269.344147  AK_1651_2011  2011      4
4  201105  2011-05-01  279.746675   280.305023  AK_1651_2011  2011      5

In [88]:
# see the values that were failed or not in the u_sf
failed_utilities = [u for u in ulist if u not in result_df['full_id_y'].unique().tolist()]
print(failed_utilities)

['AK_219_2021', 'AK_3522_2021', 'AK_7353_2021', 'AK_11824_2021', 'AK_19558_2021', 'AR_814_2021', 'AR_817_2021', 'AR_3093_2021', 'AR_5860_2021', 'AR_6342_2021', 'AR_13718_2021', 'AR_14063_2021', 'AR_17698_2021', 'AZ_176_2021', 'AZ_803_2021', 'AZ_12919_2021', 'AZ_16572_2021', 'AZ_19189_2021', 'AZ_19728_2021', 'AZ_21538_2021', 'AZ_24211_2021', 'CA_4390_2021', 'CA_9216_2021', 'CA_11208_2021', 'CA_12745_2021', 'CA_14328_2021', 'CA_14354_2021', 'CA_14534_2021', 'CA_16534_2021', 'CA_16609_2021', 'CA_16655_2021', 'CA_17609_2021', 'CA_17612_2021', 'CA_18260_2021', 'CA_19281_2021', 'CO_3989_2021', 'CO_6604_2021', 'CO_9336_2021', 'CO_12866_2021', 'CO_15257_2021', 'CO_15466_2021', 'CO_16603_2021', 'CO_19499_2021', 'CO_27058_2021', 'CO_56146_2021', 'CT_4176_2021', 'CT_7716_2021', 'CT_19497_2021', 'CT_20038_2021', 'DC_15270_2021', 'DE_5027_2021', 'DE_5070_2021', 'DE_5335_2021', 'DE_13519_2021', 'FL_6452_2021', 'FL_6455_2021', 'FL_6457_2021', 'FL_7801_2021', 'FL_9617_2021', 'FL_18454_2021', 'GA_3916_2021', 'GA_9601_2021', 'HI_8287_2021', 'HI_10071_2021', 'HI_11843_2021', 'HI_19547_2021', 'IA_9417_2021', 'IA_12341_2021', 'ID_9187_2021', 'ID_9191_2021', 'ID_10454_2021', 'ID_11273_2021', 'ID_14354_2021', 'ID_20169_2021', 'IL_4110_2021', 'IL_12341_2021', 'IL_13032_2021', 'IL_56697_2021', 'IN_9273_2021', 'IN_9324_2021', 'IN_13756_2021', 'IN_15470_2021', 'IN_17633_2021', 'KS_5860_2021', 'KS_9996_2021', 'KS_10000_2021', 'KS_10005_2021', 'KS_22500_2021', 'KY_9964_2021', 'KY_10171_2021', 'KY_11249_2021', 'KY_17564_2021', 'KY_19446_2021', 'KY_22053_2021', 'KY_49998_2021', 'LA_3265_2021', 'LA_11241_2021', 'LA_13478_2021', 'LA_17698_2021', 'MA_6374_2021', 'MA_8774_2021', 'MA_11804_2021', 'MA_13206_2021', 'MA_15748_2021', 'MA_54913_2021', 'MD_1167_2021', 'MD_5027_2021', 'MD_15263_2021', 'MD_15270_2021', 'MD_17637_2021', 'ME_1179_2021', 'ME_3266_2021', 'ME_5609_2021', 'MI_392_2021', 'MI_3828_2021', 'MI_4254_2021', 'MI_5109_2021', 'MI_9324_2021', 'MI_10704_2021', 'MI_19578_2021', 'MN_689_2021', 'MN_5574_2021', 'MN_10596_2021', 'MN_12647_2021', 'MN_13781_2021', 'MN_14232_2021', 'MN_16181_2021', 'MN_17267_2021', 'MN_20996_2021', 'MN_25177_2021', 'MO_4675_2021', 'MO_5860_2021', 'MO_9231_2021', 'MO_10000_2021', 'MO_12698_2021', 'MO_17833_2021', 'MO_19436_2021', 'MS_3841_2021', 'MS_12685_2021', 'MS_12686_2021', 'MS_17647_2021', 'MT_6395_2021', 'MT_12199_2021', 'MT_12692_2021', 'MT_12825_2021', 'MT_19603_2021', 'MT_20997_2021', 'NC_3046_2021', 'NC_5416_2021', 'NC_9837_2021', 'NC_16496_2021', 'NC_19876_2021', 'NC_24889_2021', 'ND_12090_2021', 'ND_12301_2021', 'ND_14232_2021', 'ND_19790_2021', 'ND_24949_2021', 'NE_4373_2021', 'NE_4911_2021', 'NE_6779_2021', 'NE_11018_2021', 'NE_11251_2021', 'NE_12539_2021', 'NE_13337_2021', 'NE_13664_2021', 'NE_14127_2021', 'NE_17642_2021', 'NE_27058_2021', 'NE_40606_2021', 'NH_13441_2021', 'NH_15472_2021', 'NH_24590_2021', 'NJ_963_2021', 'NJ_9726_2021', 'NJ_15477_2021', 'NJ_16213_2021', 'NM_3287_2021', 'NM_5701_2021', 'NM_6204_2021', 'NM_11204_2021', 'NM_15473_2021', 'NM_17718_2021', 'NV_2008_2021', 'NV_13073_2021', 'NV_13407_2021', 'NV_17166_2021', 'NV_19840_2021', 'NY_3249_2021', 'NY_4226_2021', 'NY_11171_2021', 'NY_13511_2021', 'NY_13573_2021', 'NY_14154_2021', 'NY_14711_2021', 'NY_16183_2021', 'OH_3542_2021', 'OH_3755_2021', 'OH_4922_2021', 'OH_13998_2021', 'OH_14006_2021', 'OH_18997_2021', 'OK_5860_2021', 'OK_13734_2021', 'OK_14062_2021', 'OK_14063_2021', 'OK_15474_2021', 'OK_19785_2021', 'OR_6022_2021', 'OR_9191_2021', 'OR_14354_2021', 'OR_15248_2021', 'OR_18260_2021', 'OR_28541_2021', 'OR_40437_2021', 'PA_3597_2021', 'PA_5487_2021', 'PA_12390_2021', 'PA_14711_2021', 'PA_14715_2021', 'PA_14716_2021', 'PA_14940_2021', 'PA_15045_2021', 'PA_19390_2021', 'PA_20334_2021', 'PA_20387_2021', 'RI_1857_2021', 'RI_13214_2021', 'RI_14537_2021', 'SC_1613_2021', 'SC_3046_2021', 'SC_5416_2021', 'SC_14398_2021', 'SC_17539_2021', 'SC_17543_2021', 'SD_1769_2021', 'SD_14232_2021', 'SD_17267_2021', 'SD_19293_2021', 'SD_20401_2021', 'TN_10331_2021', 'TX_5701_2021', 'TX_16604_2021', 'TX_55937_2021', 'UT_2010_2021', 'UT_11135_2021', 'UT_12866_2021', 'UT_14354_2021', 'UT_15444_2021', 'UT_17845_2021', 'UT_17874_2021', 'UT_18206_2021', 'VA_84_2021', 'VA_733_2021', 'VA_10171_2021', 'VA_17066_2021', 'VA_19876_2021', 'VA_19882_2021', 'VA_40228_2021', 'VT_2548_2021', 'VT_7601_2021', 'VT_19791_2021', 'WA_3660_2021', 'WA_14354_2021', 'WA_15500_2021', 'WA_16868_2021', 'WA_17470_2021', 'WA_18429_2021', 'WA_20169_2021', 'WI_4715_2021', 'WI_5574_2021', 'WI_11479_2021', 'WI_13697_2021', 'WI_13780_2021', 'WI_13815_2021', 'WI_20847_2021', 'WI_20856_2021', 'WI_20860_2021', 'WV_733_2021', 'WV_12796_2021', 'WV_15263_2021', 'WV_20521_2021', 'WY_3461_2021', 'WY_7222_2021', 'WY_8566_2021', 'WY_11273_2021', 'WY_12199_2021', 'WY_14354_2021', 'WY_19156_2021', 'WY_27058_2021', 'CA_16612_2021', 'CO_10066_2021', 'MA_20310_2021', 'AK_219_2022', 'AK_3522_2022', 'AK_7353_2022', 'AK_11824_2022', 'AK_19558_2022', 'AR_814_2022', 'AR_817_2022', 'AR_3093_2022', 'AR_5860_2022', 'AR_6342_2022', 'AR_13718_2022', 'AR_14063_2022', 'AR_17698_2022', 'AZ_176_2022', 'AZ_803_2022', 'AZ_12919_2022', 'AZ_16572_2022', 'AZ_19189_2022', 'AZ_19728_2022', 'AZ_21538_2022', 'AZ_24211_2022', 'CA_4390_2022', 'CA_9216_2022', 'CA_11208_2022', 'CA_12745_2022', 'CA_14328_2022', 'CA_14354_2022', 'CA_14534_2022', 'CA_16534_2022', 'CA_16609_2022', 'CA_16655_2022', 'CA_17609_2022', 'CA_17612_2022', 'CA_18260_2022', 'CA_19281_2022', 'CO_3989_2022', 'CO_6604_2022', 'CO_9336_2022', 'CO_12866_2022', 'CO_15257_2022', 'CO_15466_2022', 'CO_16603_2022', 'CO_19499_2022', 'CO_27058_2022', 'CO_56146_2022', 'CT_4176_2022', 'CT_7716_2022', 'CT_19497_2022', 'CT_20038_2022', 'DC_15270_2022', 'DE_5027_2022', 'DE_5070_2022', 'DE_5335_2022', 'DE_13519_2022', 'FL_6452_2022', 'FL_6455_2022', 'FL_6457_2022', 'FL_9617_2022', 'FL_18454_2022', 'GA_3916_2022', 'GA_9601_2022', 'HI_8287_2022', 'HI_10071_2022', 'HI_11843_2022', 'HI_19547_2022', 'IA_9417_2022', 'IA_12341_2022', 'ID_9187_2022', 'ID_9191_2022', 'ID_10454_2022', 'ID_11273_2022', 'ID_14354_2022', 'ID_20169_2022', 'IL_4110_2022', 'IL_12341_2022', 'IL_13032_2022', 'IL_56697_2022', 'IN_9273_2022', 'IN_9324_2022', 'IN_13756_2022', 'IN_15470_2022', 'IN_17633_2022', 'KS_5860_2022', 'KS_9996_2022', 'KS_10000_2022', 'KS_10005_2022', 'KS_22500_2022', 'KY_9964_2022', 'KY_10171_2022', 'KY_11249_2022', 'KY_17564_2022', 'KY_19446_2022', 'KY_22053_2022', 'KY_49998_2022', 'LA_3265_2022', 'LA_11241_2022', 'LA_13478_2022', 'LA_17698_2022', 'MA_6374_2022', 'MA_8774_2022', 'MA_11804_2022', 'MA_13206_2022', 'MA_15748_2022', 'MA_54913_2022', 'MD_1167_2022', 'MD_5027_2022', 'MD_15263_2022', 'MD_15270_2022', 'MD_17637_2022', 'ME_1179_2022', 'ME_3266_2022', 'ME_5609_2022', 'MI_392_2022', 'MI_3828_2022', 'MI_4254_2022', 'MI_5109_2022', 'MI_9324_2022', 'MI_10704_2022', 'MI_19578_2022', 'MN_689_2022', 'MN_5574_2022', 'MN_10596_2022', 'MN_12647_2022', 'MN_13781_2022', 'MN_14232_2022', 'MN_16181_2022', 'MN_17267_2022', 'MN_20996_2022', 'MN_25177_2022', 'MO_4675_2022', 'MO_5860_2022', 'MO_9231_2022', 'MO_10000_2022', 'MO_12698_2022', 'MO_17833_2022', 'MO_19436_2022', 'MS_3841_2022', 'MS_12685_2022', 'MS_12686_2022', 'MS_17647_2022', 'MT_6395_2022', 'MT_12199_2022', 'MT_12692_2022', 'MT_12825_2022', 'MT_19603_2022', 'MT_20997_2022', 'NC_3046_2022', 'NC_5416_2022', 'NC_9837_2022', 'NC_16496_2022', 'NC_19876_2022', 'NC_24889_2022', 'ND_12090_2022', 'ND_12301_2022', 'ND_14232_2022', 'ND_19790_2022', 'ND_20413_2022', 'ND_24949_2022', 'NE_4373_2022', 'NE_4911_2022', 'NE_6779_2022', 'NE_11018_2022', 'NE_11251_2022', 'NE_12539_2022', 'NE_13337_2022', 'NE_13664_2022', 'NE_14127_2022', 'NE_17642_2022', 'NE_27058_2022', 'NE_40606_2022', 'NH_13441_2022', 'NH_15472_2022', 'NH_24590_2022', 'NJ_963_2022', 'NJ_9726_2022', 'NJ_15477_2022', 'NJ_16213_2022', 'NM_3287_2022', 'NM_5701_2022', 'NM_6204_2022', 'NM_11204_2022', 'NM_15473_2022', 'NM_17718_2022', 'NV_2008_2022', 'NV_13073_2022', 'NV_13407_2022', 'NV_17166_2022', 'NV_19840_2022', 'NY_3249_2022', 'NY_4226_2022', 'NY_11171_2022', 'NY_13511_2022', 'NY_13573_2022', 'NY_14154_2022', 'NY_14711_2022', 'NY_16183_2022', 'OH_3542_2022', 'OH_3755_2022', 'OH_4922_2022', 'OH_13998_2022', 'OH_14006_2022', 'OH_18997_2022', 'OK_5860_2022', 'OK_13734_2022', 'OK_14062_2022', 'OK_14063_2022', 'OK_15474_2022', 'OK_19785_2022', 'OR_6022_2022', 'OR_9191_2022', 'OR_14354_2022', 'OR_15248_2022', 'OR_18260_2022', 'OR_28541_2022', 'OR_40437_2022', 'PA_3597_2022', 'PA_5487_2022', 'PA_12390_2022', 'PA_14711_2022', 'PA_14715_2022', 'PA_14716_2022', 'PA_14940_2022', 'PA_15045_2022', 'PA_19390_2022', 'PA_20334_2022', 'PA_20387_2022', 'RI_1857_2022', 'RI_13214_2022', 'RI_14537_2022', 'SC_1613_2022', 'SC_3046_2022', 'SC_5416_2022', 'SC_14398_2022', 'SC_17539_2022', 'SC_17543_2022', 'SD_1769_2022', 'SD_14232_2022', 'SD_17267_2022', 'SD_19293_2022', 'SD_20401_2022', 'TN_10331_2022', 'TX_5701_2022', 'TX_16604_2022', 'TX_55937_2022', 'UT_2010_2022', 'UT_11135_2022', 'UT_12866_2022', 'UT_14354_2022', 'UT_15444_2022', 'UT_17845_2022', 'UT_17874_2022', 'UT_18206_2022', 'VA_84_2022', 'VA_733_2022', 'VA_10171_2022', 'VA_17066_2022', 'VA_19876_2022', 'VA_19882_2022', 'VA_40228_2022', 'VT_2548_2022', 'VT_7601_2022', 'VT_19791_2022', 'WA_3660_2022', 'WA_14354_2022', 'WA_15500_2022', 'WA_16868_2022', 'WA_17470_2022', 'WA_18429_2022', 'WA_20169_2022', 'WI_4715_2022', 'WI_5574_2022', 'WI_11479_2022', 'WI_13697_2022', 'WI_13780_2022', 'WI_13815_2022', 'WI_20847_2022', 'WI_20856_2022', 'WI_20860_2022', 'WV_733_2022', 'WV_12796_2022', 'WV_15263_2022', 'WV_20521_2022', 'WY_3461_2022', 'WY_7222_2022', 'WY_8566_2022', 'WY_11273_2022', 'WY_12199_2022', 'WY_14354_2022', 'WY_19156_2022', 'WY_27058_2022', 'OK_817_2022', 'CO_10066_2022', 'AR_12681_2022', 'CA_16612_2022', 'MA_20310_2022', 'NE_8245_2022', 'AK_219_2023', 'AK_3522_2023', 'AK_7353_2023', 'AK_11824_2023', 'AK_19558_2023', 'AL_3222_2023', 'AL_4327_2023', 'AL_4430_2023', 'AL_6491_2023', 'AL_17646_2023', 'AR_814_2023', 'AR_817_2023', 'AR_1586_2023', 'AR_2678_2023', 'AR_3093_2023', 'AR_3712_2023', 'AR_4280_2023', 'AR_4509_2023', 'AR_5860_2023', 'AR_6342_2023', 'AR_8840_2023', 'AR_9879_2023', 'AR_12681_2023', 'AR_13676_2023', 'AR_13718_2023', 'AR_14063_2023', 'AR_14289_2023', 'AR_14446_2023', 'AR_14864_2023', 'AR_17184_2023', 'AR_17671_2023', 'AR_17698_2023', 'AR_20963_2023', 'AZ_176_2023', 'AZ_803_2023', 'AZ_6957_2023', 'AZ_12351_2023', 'AZ_12919_2023', 'AZ_13318_2023', 'AZ_16572_2023', 'AZ_18280_2023', 'AZ_19189_2023', 'AZ_19728_2023', 'AZ_21538_2023', 'AZ_24211_2023', 'AZ_30518_2023', 'AZ_40165_2023', 'CA_207_2023', 'CA_590_2023', 'CA_1050_2023', 'CA_2507_2023', 'CA_4003_2023', 'CA_4390_2023', 'CA_7294_2023', 'CA_9216_2023', 'CA_11124_2023', 'CA_11208_2023', 'CA_12312_2023', 'CA_12745_2023', 'CA_14328_2023', 'CA_14354_2023', 'CA_14401_2023', 'CA_14534_2023', 'CA_15783_2023', 'CA_16088_2023', 'CA_16295_2023', 'CA_16534_2023', 'CA_16609_2023', 'CA_16612_2023', 'CA_16655_2023', 'CA_17609_2023', 'CA_17612_2023', 'CA_17896_2023', 'CA_18260_2023', 'CA_19281_2023', 'CA_19798_2023', 'CA_55787_2023', 'CA_57483_2023', 'CO_3989_2023', 'CO_5086_2023', 'CO_5862_2023', 'CO_6604_2023', 'CO_6638_2023', 'CO_7563_2023', 'CO_8570_2023', 'CO_8773_2023', 'CO_9336_2023', 'CO_10066_2023', 'CO_10539_2023', 'CO_11187_2023', 'CO_11256_2023', 'CO_12860_2023', 'CO_12866_2023', 'CO_13050_2023', 'CO_13058_2023', 'CO_15257_2023', 'CO_15466_2023', 'CO_16603_2023', 'CO_16616_2023', 'CO_16622_2023', 'CO_17592_2023', 'CO_19499_2023', 'CO_20576_2023', 'CO_21075_2023', 'CO_21081_2023', 'CO_27058_2023', 'CO_56146_2023', 'CT_4176_2023', 'CT_7716_2023', 'CT_13831_2023', 'CT_19497_2023', 'CT_20038_2023', 'DC_15270_2023', 'DE_5027_2023', 'DE_5070_2023', 'DE_5335_2023', 'DE_12478_2023', 'DE_12540_2023', 'DE_13519_2023', 'FL_1300_2023', 'FL_3245_2023', 'FL_3502_2023', 'FL_3757_2023', 'FL_6443_2023', 'FL_6452_2023', 'FL_6455_2023', 'FL_6457_2023', 'FL_6616_2023', 'FL_6909_2023', 'FL_7264_2023', 'FL_7785_2023', 'FL_8795_2023', 'FL_9616_2023', 'FL_9617_2023', 'FL_10226_2023', 'FL_10376_2023', 'FL_10620_2023', 'FL_10623_2023', 'FL_10857_2023', 'FL_10868_2023', 'FL_13485_2023', 'FL_13955_2023', 'FL_14606_2023', 'FL_14610_2023', 'FL_15776_2023', 'FL_18304_2023', 'FL_18360_2023', 'FL_18445_2023', 'FL_18449_2023', 'FL_18454_2023', 'FL_19161_2023', 'FL_20371_2023', 'FL_20885_2023', 'FL_31833_2023', 'GA_230_2023', 'GA_407_2023', 'GA_562_2023', 'GA_2487_2023', 'GA_2812_2023', 'GA_2903_2023', 'GA_3081_2023', 'GA_3108_2023', 'GA_3248_2023', 'GA_3843_2023', 'GA_3916_2023', 'GA_4432_2023', 'GA_4433_2023', 'GA_4538_2023', 'GA_5905_2023', 'GA_6411_2023', 'GA_7090_2023', 'GA_7140_2023', 'GA_7450_2023', 'GA_7887_2023', 'GA_8210_2023', 'GA_9431_2023', 'GA_9601_2023', 'GA_9689_2023', 'GA_10624_2023', 'GA_10800_2023', 'GA_11646_2023', 'GA_12706_2023', 'GA_13962_2023', 'GA_15700_2023', 'GA_16674_2023', 'GA_16865_2023', 'GA_18305_2023', 'GA_18499_2023', 'GA_18848_2023', 'GA_18956_2023', 'GA_19219_2023', 'GA_20065_2023', 'GA_20146_2023', 'GA_31833_2023', 'GA_40212_2023', 'HI_8287_2023', 'HI_10071_2023', 'HI_11843_2023', 'HI_19547_2023', 'IA_554_2023', 'IA_2652_2023', 'IA_3203_2023', 'IA_5588_2023', 'IA_5605_2023', 'IA_8319_2023', 'IA_9230_2023', 'IA_9417_2023', 'IA_9425_2023', 'IA_11053_2023', 'IA_11611_2023', 'IA_11788_2023', 'IA_12341_2023', 'IA_12450_2023', 'IA_13143_2023', 'IA_15291_2023', 'IA_15349_2023', 'IA_17260_2023', 'IA_19157_2023', 'ID_6169_2023', 'ID_8699_2023', 'ID_9187_2023', 'ID_9191_2023', 'ID_10454_2023', 'ID_11273_2023', 'ID_14354_2023', 'ID_19502_2023', 'ID_20169_2023', 'IL_3931_2023', 'IL_4110_2023', 'IL_4362_2023', 'IL_5535_2023', 'IL_5585_2023', 'IL_7096_2023', 'IL_9750_2023', 'IL_12341_2023', 'IL_12395_2023', 'IL_13032_2023', 'IL_13208_2023', 'IL_13292_2023', 'IL_14840_2023', 'IL_16179_2023', 'IL_16196_2023', 'IL_16740_2023', 'IL_17040_2023', 'IL_17585_2023', 'IL_17828_2023', 'IL_17860_2023', 'IL_18955_2023', 'IL_20222_2023', 'IL_56697_2023', 'IN_636_2023', 'IN_1283_2023', 'IN_4508_2023', 'IN_4848_2023', 'IN_4960_2023', 'IN_5394_2023', 'IN_8000_2023', 'IN_8179_2023', 'IN_8447_2023', 'IN_9273_2023', 'IN_9324_2023', 'IN_9576_2023', 'IN_9665_2023', 'IN_9667_2023', 'IN_9778_2023', 'IN_10448_2023', 'IN_12377_2023', 'IN_12929_2023', 'IN_13647_2023', 'IN_13756_2023', 'IN_14839_2023', 'IN_15470_2023', 'IN_15989_2023', 'IN_17038_2023', 'IN_17599_2023', 'IN_17633_2023', 'IN_18940_2023', 'IN_19445_2023', 'IN_19667_2023', 'IN_20216_2023', 'IN_20603_2023', 'IN_22822_2023', 'IN_24753_2023', 'IN_25295_2023', 'IN_27599_2023', 'KS_5860_2023', 'KS_9996_2023', 'KS_10000_2023', 'KS_10005_2023', 'KS_10019_2023', 'KS_12208_2023', 'KS_13799_2023', 'KS_15073_2023', 'KS_19160_2023', 'KS_19820_2023', 'KS_20476_2023', 'KS_20510_2023', 'KS_22500_2023', 'KY_690_2023', 'KY_1708_2023', 'KY_1886_2023', 'KY_3687_2023', 'KY_4622_2023', 'KY_6194_2023', 'KY_6442_2023', 'KY_6708_2023', 'KY_7558_2023', 'KY_8449_2023', 'KY_9292_2023', 'KY_9575_2023', 'KY_9605_2023', 'KY_9964_2023', 'KY_10171_2023', 'KY_11249_2023', 'KY_12243_2023', 'KY_13651_2023', 'KY_14251_2023', 'KY_14268_2023', 'KY_16587_2023', 'KY_17044_2023', 'KY_17564_2023', 'KY_18498_2023', 'KY_19446_2023', 'KY_22053_2023', 'KY_49998_2023', 'LA_298_2023', 'LA_1458_2023', 'LA_3265_2023', 'LA_3641_2023', 'LA_4153_2023', 'LA_5202_2023', 'LA_9096_2023', 'LA_9682_2023', 'LA_11241_2023', 'LA_13228_2023', 'LA_13478_2023', 'LA_13783_2023', 'LA_14424_2023', 'LA_15175_2023', 'LA_16463_2023', 'LA_17565_2023', 'LA_17684_2023', 'LA_17698_2023', 'LA_21567_2023', 'MA_2144_2023', 'MA_3477_2023', 'MA_5480_2023', 'MA_6374_2023', 'MA_8774_2023', 'MA_11085_2023', 'MA_11586_2023', 'MA_11804_2023', 'MA_12473_2023', 'MA_13206_2023', 'MA_13679_2023', 'MA_14605_2023', 'MA_15748_2023', 'MA_17127_2023', 'MA_18087_2023', 'MA_18488_2023', 'MA_20310_2023', 'MA_54913_2023', 'MD_1167_2023', 'MD_3503_2023', 'MD_5027_2023', 'MD_5625_2023', 'MD_7908_2023', 'MD_15263_2023', 'MD_15270_2023', 'MD_17637_2023', 'ME_1179_2023', 'ME_3266_2023', 'ME_5609_2023', 'MI_305_2023', 'MI_392_2023', 'MI_1196_2023', 'MI_1366_2023', 'MI_3436_2023', 'MI_3828_2023', 'MI_4254_2023', 'MI_4604_2023', 'MI_5109_2023', 'MI_7265_2023', 'MI_7483_2023', 'MI_8723_2023', 'MI_9324_2023', 'MI_10508_2023', 'MI_10704_2023', 'MI_11701_2023', 'MI_12377_2023', 'MI_13352_2023', 'MI_13826_2023', 'MI_15340_2023', 'MI_18252_2023', 'MI_19125_2023', 'MI_19396_2023', 'MI_19578_2023', 'MI_21048_2023', 'MI_21158_2023', 'MI_38084_2023', 'MN_155_2023', 'MN_295_2023', 'MN_689_2023', 'MN_691_2023', 'MN_1009_2023', 'MN_1529_2023', 'MN_1884_2023', 'MN_3400_2023', 'MN_4577_2023', 'MN_5574_2023', 'MN_5773_2023', 'MN_6258_2023', 'MN_6782_2023', 'MN_8319_2023', 'MN_9475_2023', 'MN_10596_2023', 'MN_10618_2023', 'MN_10697_2023', 'MN_11731_2023', 'MN_12227_2023', 'MN_12546_2023', 'MN_12647_2023', 'MN_12651_2023', 'MN_12894_2023', 'MN_13781_2023', 'MN_14232_2023', 'MN_14246_2023', 'MN_14468_2023', 'MN_16181_2023', 'MN_16368_2023', 'MN_16971_2023', 'MN_17267_2023', 'MN_17550_2023', 'MN_18019_2023', 'MN_18047_2023', 'MN_19157_2023', 'MN_20639_2023', 'MN_20737_2023', 'MN_20996_2023', 'MN_21013_2023', 'MN_25177_2023', 'MN_40304_2023', 'MO_1775_2023', 'MO_2001_2023', 'MO_3113_2023', 'MO_3268_2023', 'MO_3600_2023', 'MO_4045_2023', 'MO_4063_2023', 'MO_4160_2023', 'MO_4237_2023', 'MO_4524_2023', 'MO_4675_2023', 'MO_5860_2023', 'MO_6181_2023', 'MO_6205_2023', 'MO_7024_2023', 'MO_8055_2023', 'MO_8934_2023', 'MO_9231_2023', 'MO_9331_2023', 'MO_10000_2023', 'MO_10370_2023', 'MO_10603_2023', 'MO_10832_2023', 'MO_11463_2023', 'MO_12698_2023', 'MO_12700_2023', 'MO_12782_2023', 'MO_13520_2023', 'MO_14192_2023', 'MO_14285_2023', 'MO_14288_2023', 'MO_15138_2023', 'MO_15229_2023', 'MO_16259_2023', 'MO_16751_2023', 'MO_16805_2023', 'MO_17177_2023', 'MO_17833_2023', 'MO_19436_2023', 'MO_20318_2023', 'MO_20363_2023', 'MO_20574_2023', 'MO_27238_2023', 'MS_3841_2023', 'MS_5175_2023', 'MS_11519_2023', 'MS_12685_2023', 'MS_12686_2023', 'MS_14563_2023', 'MS_17647_2023', 'MS_22815_2023', 'MT_6169_2023', 'MT_6395_2023', 'MT_11272_2023', 'MT_12199_2023', 'MT_12692_2023', 'MT_12825_2023', 'MT_19603_2023', 'MT_20997_2023', 'MT_21513_2023', 'NC_240_2023', 'NC_719_2023', 'NC_1889_2023', 'NC_3046_2023', 'NC_5416_2023', 'NC_6640_2023', 'NC_6784_2023', 'NC_7639_2023', 'NC_8333_2023', 'NC_9837_2023', 'NC_14717_2023', 'NC_15023_2023', 'NC_16101_2023', 'NC_16496_2023', 'NC_17572_2023', 'NC_18957_2023', 'NC_19435_2023', 'NC_19876_2023', 'NC_19981_2023', 'NC_21632_2023', 'NC_24889_2023', 'ND_2394_2023', 'ND_12090_2023', 'ND_12301_2023', 'ND_14232_2023', 'ND_19790_2023', 'ND_20413_2023', 'ND_24949_2023', 'NE_2643_2023', 'NE_3205_2023', 'NE_4373_2023', 'NE_4671_2023', 'NE_4911_2023', 'NE_5780_2023', 'NE_6779_2023', 'NE_8245_2023', 'NE_8570_2023', 'NE_10967_2023', 'NE_11018_2023', 'NE_11251_2023', 'NE_12539_2023', 'NE_13337_2023', 'NE_13664_2023', 'NE_13725_2023', 'NE_13739_2023', 'NE_14127_2023', 'NE_17577_2023', 'NE_17642_2023', 'NE_17692_2023', 'NE_21111_2023', 'NE_27058_2023', 'NE_40606_2023', 'NH_13441_2023', 'NH_15472_2023', 'NH_24590_2023', 'NJ_963_2023', 'NJ_9726_2023', 'NJ_15477_2023', 'NJ_16213_2023', 'NJ_19856_2023', 'NM_3273_2023', 'NM_3287_2023', 'NM_4265_2023', 'NM_5701_2023', 'NM_6198_2023', 'NM_6204_2023', 'NM_9699_2023', 'NM_10378_2023', 'NM_11204_2023', 'NM_13318_2023', 'NM_14224_2023', 'NM_15473_2023', 'NM_17715_2023', 'NM_17718_2023', 'NM_17826_2023', 'NV_2008_2023', 'NV_13073_2023', 'NV_13407_2023', 'NV_14245_2023', 'NV_17166_2023', 'NV_19840_2023', 'NY_3249_2023', 'NY_4226_2023', 'NY_11171_2023', 'NY_11811_2023', 'NY_13511_2023', 'NY_13573_2023', 'NY_14154_2023', 'NY_14711_2023', 'NY_16183_2023', 'OH_2651_2023', 'OH_3542_2023', 'OH_3755_2023', 'OH_3762_2023', 'OH_4683_2023', 'OH_4922_2023', 'OH_7891_2023', 'OH_8761_2023', 'OH_10830_2023', 'OH_12377_2023', 'OH_12990_2023', 'OH_13998_2023', 'OH_14006_2023', 'OH_18997_2023', 'OH_19951_2023', 'OH_20477_2023', 'OK_296_2023', 'OK_817_2023', 'OK_3226_2023', 'OK_3478_2023', 'OK_3527_2023', 'OK_3647_2023', 'OK_4296_2023', 'OK_4401_2023', 'OK_5598_2023'

In [89]:
# find these in the all_sf
failed_df = all_sf[all_sf['full_id_y'].isin(failed_utilities)]
failed_df.head()

,year,full_id,full_id_y,geometry
3404,2021.0,AK_219,AK_219_2021,"MULTIPOLYGON (((-152.84 66.52844, -152.54921 6..."
3405,2021.0,AK_3522,AK_3522_2021,"MULTIPOLYGON (((-149.92786 61.26033, -150.1725..."
3406,2021.0,AK_7353,AK_7353_2021,"MULTIPOLYGON (((-148.99777 61.68576, -149.0274..."
3407,2021.0,AK_11824,AK_11824_2021,"MULTIPOLYGON (((-147.70998 61.25606, -144.8711..."
3408,2021.0,AK_19558,AK_19558_2021,"MULTIPOLYGON (((-150.2314 60.93248, -149.79817..."

In [92]:
# use the geometry from results that worked by the same full_id
# start with the unique full_id in failed_df
fi_ulist = failed_df['full_id'].unique().tolist()

# make the full_id in results by removing everything after first number  from full_id_y
result_df['full_id'] = result_df['full_id_y'].apply(lambda x: x.rsplit('_', 1)[0])
result_df.head()

,id,date,avg_temp,median_temp,full_id_y,year,month,full_id
0,201101,2011-01-01,262.901527,262.708801,AK_1651_2011,2011,1,AK_1651
1,201102,2011-02-01,262.651882,262.448761,AK_1651_2011,2011,2,AK_1651
2,201103,2011-03-01,263.460223,263.237762,AK_1651_2011,2011,3,AK_1651
3,201104,2011-04-01,269.190750,269.344147,AK_1651_2011,2011,4,AK_1651
4,201105,2011-05-01,279.746675,280.305023,AK_1651_2011,2011,5,AK_1651

In [93]:
# find the full_id's from fi_ulist in result_df
good_fi_df = result_df[result_df['full_id'].isin(fi_ulist)]
good_fi_df.head()

,id,date,avg_temp,median_temp,full_id_y,year,month,full_id
12,201101,2011-01-01,253.831641,254.329533,AK_7353_2011,2011,1,AK_7353
13,201102,2011-02-01,253.333961,254.224711,AK_7353_2011,2011,2,AK_7353
14,201103,2011-03-01,258.729929,259.534265,AK_7353_2011,2011,3,AK_7353
15,201104,2011-04-01,270.226517,271.338089,AK_7353_2011,2011,4,AK_7353
16,201105,2011-05-01,281.966434,282.717443,AK_7353_2011,2011,5,AK_7353

In [96]:
# use the geometries from all_sf that match what is in good_fi_df as an sf
# object
good_fi_sf = all_sf[all_sf['full_id_y'].isin(good_fi_df['full_id_y'])]
good_fi_sf

,year,full_id,full_id_y,geometry
1,2011.0,AK_7353,AK_7353_2011,"MULTIPOLYGON (((-145.49744 62.8097, -145.94969..."
2,2011.0,AK_19558,AK_19558_2011,"MULTIPOLYGON (((-151.41011 60.72023, -150.5924..."
3,2011.0,AR_814,AR_814_2011,"MULTIPOLYGON (((-89.92713 35.80674, -89.97135 ..."
4,2011.0,AR_817,AR_817_2011,"MULTIPOLYGON (((-94.4324 35.36433, -94.42681 3..."
5,2011.0,AR_6342,AR_6342_2011,"MULTIPOLYGON (((-91.90864 34.25538, -91.55306 ..."
...,...,...,...,...
5148,2012.0,UT_11135,UT_11135_2012,"POLYGON ((-111.99107 41.83314, -111.64558 41.7..."
5149,2013.0,UT_11135,UT_11135_2013,"POLYGON ((-111.99107 41.83314, -111.64558 41.7..."
5150,2011.0,VA_19882,VA_19882_2011,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."
5151,2012.0,VA_19882,VA_19882_2012,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."
5152,2013.0,VA_19882,VA_19882_2013,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."

In [98]:
# select the latest observation for full_id in good_fi_sf
good_fi_sf = good_fi_sf.sort_values('year', ascending=False).drop_duplicates('full_id')

# drop the year and full_id_y
good_fi_sf = good_fi_sf.drop(columns=['year', 'full_id_y'])
good_fi_sf

       full_id                                           geometry
3400  WY_19156  POLYGON ((-104.24224 42.53926, -105.52642 42.2...
5136  NH_26510  MULTIPOLYGON (((-72.30138 43.53117, -72.2327 4...
3384  WI_13697  POLYGON ((-90.23122 46.08239, -90.0437 45.6686...
3056  AR_13718  MULTIPOLYGON (((-92.39016 34.76831, -92.42712 ...
3055   AR_6342  MULTIPOLYGON (((-90.84715 34.20613, -90.9498 3...
...        ...                                                ...
3387  WI_20847  MULTIPOLYGON (((-87.89778 43.93541, -87.79727 ...
3386  WI_13815  POLYGON ((-92.70405 45.35366, -92.293 46.33216...
982    GA_7140  MULTIPOLYGON (((-84.97732 32.29543, -84.98883 ...
207   SD_19545  MULTIPOLYGON (((-104.05604 44.58166, -102.9641...
142    NM_9699  MULTIPOLYGON (((-107.30831 36.56714, -107.6979...

[294 rows x 2 columns]

In [100]:
# replace the geometry in failed_df and attach the good geometry from good_fi_sf by full_id
failed_df['geometry'] = failed_df['full_id'].map(good_fi_sf.set_index('full_id')['geometry'])

# see the top 20 values
failed_df.head(20)

/usr/local/lib/python3.11/dist-packages/geopandas/geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

,year,full_id,full_id_y,geometry
3404,2021.0,AK_219,AK_219_2021,"MULTIPOLYGON (((-152.84 66.52844, -152.54921 6..."
3405,2021.0,AK_3522,AK_3522_2021,"MULTIPOLYGON (((-149.92786 61.26033, -150.1725..."
3406,2021.0,AK_7353,AK_7353_2021,"MULTIPOLYGON (((-148.99777 61.68576, -149.0274..."
3407,2021.0,AK_11824,AK_11824_2021,"MULTIPOLYGON (((-147.70998 61.25606, -144.8711..."
3408,2021.0,AK_19558,AK_19558_2021,"MULTIPOLYGON (((-150.2314 60.93248, -149.79817..."
3409,2021.0,AR_814,AR_814_2021,"MULTIPOLYGON (((-93.61086 33.01907, -94.5706 3..."
3410,2021.0,AR_817,AR_817_2021,"POLYGON ((-93.86355 34.71236, -94.5706 34.6813..."
3411,2021.0,AR_3093,AR_3093_2021,"MULTIPOLYGON (((-93.96879 36.00338, -93.96002 ..."
3412,2021.0,AR_5860,AR_5860_2021,"POLYGON ((-94.14034 36.45877, -94.56561 36.223..."
3413,2021.0,AR_6342,AR_6342_2021,"MULTIPOLYGON (((-90.84715 34.20613, -90.9498 3..."
3414,2021.0,AR_13718,AR_13718_2021,"MULTIPOLYGON (((-92.39016 34.76831, -92.42712 ..."
3415,2021.0,AR_14063,AR_14063_2021,"POLYGON ((-94.45109 34.8307, -94.12889 35.9930..."
3416,2021.0,AR_17698,AR_17698_2021,"MULTIPOLYGON (((-93.44203 33.25828, -93.41124 ..."
3417,2021.0,AZ_176,AZ_176_2021,"POLYGON ((-112.81746 31.88002, -112.88103 32.5..."
3418,2021.0,AZ_803,AZ_803_2021,"MULTIPOLYGON (((-112.60776 31.81576, -112.8810..."
3419,2021.0,AZ_12919,AZ_12919_2021,"POLYGON ((-109.04755 33.10739, -109.66786 33.2..."
3420,2021.0,AZ_16572,AZ_16572_2021,"POLYGON ((-112.04921 32.87501, -112.25403 34.4..."
3421,2021.0,AZ_19189,AZ_19189_2021,"POLYGON ((-111.05387 31.38547, -111.686 32.833..."
3422,2021.0,AZ_19728,AZ_19728_2021,"MULTIPOLYGON (((-111.69622 34.34275, -111.9398..."
3423,2021.0,AZ_21538,AZ_21538_2021,"MULTIPOLYGON (((-112.20504 34.97397, -112.4417..."

In [102]:
# make the failed_df into an sf object
failed_df = gpd.GeoDataFrame(failed_df, geometry='geometry')
failed_df.head()

,year,full_id,full_id_y,geometry
3404,2021.0,AK_219,AK_219_2021,"MULTIPOLYGON (((-152.84 66.52844, -152.54921 6..."
3405,2021.0,AK_3522,AK_3522_2021,"MULTIPOLYGON (((-149.92786 61.26033, -150.1725..."
3406,2021.0,AK_7353,AK_7353_2021,"MULTIPOLYGON (((-148.99777 61.68576, -149.0274..."
3407,2021.0,AK_11824,AK_11824_2021,"MULTIPOLYGON (((-147.70998 61.25606, -144.8711..."
3408,2021.0,AK_19558,AK_19558_2021,"MULTIPOLYGON (((-150.2314 60.93248, -149.79817..."

In [105]:
# this requires a new image collection
#https://developers.google.com/earth-engine/datasets/catalog/NCEP_RE_surface_temp#bands

temp_collection = ee.ImageCollection("NCEP_RE/surface_temp").select('air')

In [ ]:

# create an empty df to collect data for loop
utility_monthly_temp = []

# Loop over each utility
for u in tqdm(failed_utilities):  # u = "WY_14354_2023"
    start_time = datetime.now()

    u_sf = failed_df[failed_df['full_id_y'] == u]

    # Add an explicit check for None geometry before attempting to access its attributes
    if u_sf.empty or u_sf.geometry.is_empty.any() or u_sf.geometry.values[0] is None:
        print(f"Skipping utility {u} due to empty or invalid geometry.")
        continue

    # Convert geometry to EE
    geom_json = u_sf.geometry.values[0].__geo_interface__
    boundary = ee.Geometry(geom_json)

    # Extract year
    year = int(u_sf['year'].values[0])
    d1 = datetime(year, 1, 1)
    d2 = d1 + relativedelta(months=12)

    # Filter image collection
    monthly_image = temp_collection.filterDate(d1.strftime('%Y-%m-%d'), d2.strftime('%Y-%m-%d'))

    # Function to extract average temp for each image
    def extract_temp(image):
        date = ee.Date(image.get('system:time_start')).format('YYYY-MM-dd HH:mm')

        med_temp = image.reduceRegion(
            reducer=ee.Reducer.median(),
            geometry=boundary,
            scale=5000,
            maxPixels=1e13
        ).get('air')

        mean_temp = image.reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=boundary,
            scale=5000,
            maxPixels=1e13
        ).get('air')
        return ee.Feature(None, {'date': date, 'avg_temp': mean_temp, 'median_temp': med_temp})
    # Map over collection and get features
    temp_features = monthly_image.map(extract_temp)
    temp_table = ee.FeatureCollection(temp_features)

    # Export to client
    try:
        temp_dicts = geemap.ee_to_geojson(temp_table)
        temp_df = pd.DataFrame(temp_dicts['features'])
        temp_df['date'] = pd.to_datetime(temp_df['properties'].apply(lambda x: x['date']))
        temp_df['avg_temp'] = temp_df['properties'].apply(lambda x: x['avg_temp'])
        temp_df['median_temp'] = temp_df['properties'].apply(lambda x: x['median_temp'])
        temp_df.drop(columns=['properties', 'type', 'geometry'], inplace=True)

        # Add utility info
        temp_df['full_id_y'] = u
        temp_df['year'] = year
        temp_df['month'] = temp_df['date'].dt.month

        # save
        utility_monthly_temp.append(temp_df)

    except Exception as e:
        print(f"Failed for utility {u}: {e}")
        continue

    print(f"{u} completed in {datetime.now() - start_time}")

# Combine all data and write to CSV
missing_df = pd.concat(utility_monthly_temp, ignore_index=True)

# Save to CSV
missing_df.to_csv("data files/missing_monthly_air_temp_utilities_kelvin.csv", index=False)

  0%|          | 1/1508 [00:03<1:23:40,  3.33s/it]

AK_219_2021 completed in 0:00:03.330988

  0%|          | 2/1508 [00:05<1:01:22,  2.44s/it]

AK_3522_2021 completed in 0:00:01.821312

  0%|          | 3/1508 [00:12<1:59:34,  4.77s/it]

AK_7353_2021 completed in 0:00:07.530128

  0%|          | 4/1508 [00:22<2:50:38,  6.81s/it]

AK_11824_2021 completed in 0:00:09.934255

  0%|          | 5/1508 [00:31<3:09:23,  7.56s/it]

AK_19558_2021 completed in 0:00:08.893753

  0%|          | 6/1508 [00:37<2:51:35,  6.85s/it]

AR_814_2021 completed in 0:00:05.483779

  0%|          | 7/1508 [00:41<2:32:38,  6.10s/it]

AR_817_2021 completed in 0:00:04.550012

  1%|          | 8/1508 [00:47<2:32:15,  6.09s/it]

AR_3093_2021 completed in 0:00:06.065547

  1%|          | 9/1508 [00:53<2:28:58,  5.96s/it]

AR_5860_2021 completed in 0:00:05.677731

  1%|          | 10/1508 [01:30<6:29:56, 15.62s/it]

AR_6342_2021 completed in 0:00:37.234293

  1%|          | 11/1508 [01:34<5:01:17, 12.08s/it]

AR_13718_2021 completed in 0:00:04.043340

  1%|          | 12/1508 [01:39<4:09:32, 10.01s/it]

AR_14063_2021 completed in 0:00:05.278562

  1%|          | 13/1508 [01:44<3:32:29,  8.53s/it]

AR_17698_2021 completed in 0:00:05.121463

  1%|          | 14/1508 [01:49<3:00:35,  7.25s/it]

AZ_176_2021 completed in 0:00:04.303134

  1%|          | 15/1508 [01:57<3:08:31,  7.58s/it]

AZ_803_2021 completed in 0:00:08.327221

  1%|          | 16/1508 [02:01<2:42:16,  6.53s/it]

AZ_12919_2021 completed in 0:00:04.085599

  1%|          | 17/1508 [02:06<2:29:04,  6.00s/it]

AZ_16572_2021 completed in 0:00:04.772754

  1%|          | 18/1508 [02:40<5:58:09, 14.42s/it]

AZ_19189_2021 completed in 0:00:34.026697

  1%|▏         | 19/1508 [02:45<4:47:15, 11.58s/it]

AZ_19728_2021 completed in 0:00:04.941955

  1%|▏         | 20/1508 [02:50<3:57:52,  9.59s/it]

AZ_21538_2021 completed in 0:00:04.967724

  1%|▏         | 21/1508 [02:55<3:24:14,  8.24s/it]

AZ_24211_2021 completed in 0:00:05.090087

  1%|▏         | 22/1508 [03:01<3:07:31,  7.57s/it]

CA_4390_2021 completed in 0:00:06.006644

  2%|▏         | 23/1508 [03:06<2:46:40,  6.73s/it]

CA_9216_2021 completed in 0:00:04.780329

  2%|▏         | 24/1508 [03:12<2:41:54,  6.55s/it]

CA_11208_2021 completed in 0:00:06.107282

  2%|▏         | 25/1508 [03:16<2:24:18,  5.84s/it]

CA_12745_2021 completed in 0:00:04.186481

  2%|▏         | 26/1508 [03:29<3:16:30,  7.96s/it]

CA_14328_2021 completed in 0:00:12.894886

  2%|▏         | 27/1508 [03:36<3:12:13,  7.79s/it]

CA_14354_2021 completed in 0:00:07.393261

  2%|▏         | 28/1508 [03:41<2:51:37,  6.96s/it]

CA_14534_2021 completed in 0:00:05.020729

  2%|▏         | 29/1508 [03:47<2:39:28,  6.47s/it]

CA_16534_2021 completed in 0:00:05.329078

  2%|▏         | 30/1508 [03:52<2:27:42,  6.00s/it]

CA_16609_2021 completed in 0:00:04.892529

  2%|▏         | 31/1508 [03:56<2:18:49,  5.64s/it]

CA_16655_2021 completed in 0:00:04.806012

  2%|▏         | 32/1508 [04:05<2:38:17,  6.43s/it]

CA_17609_2021 completed in 0:00:08.285482

  2%|▏         | 33/1508 [04:10<2:28:23,  6.04s/it]

CA_17612_2021 completed in 0:00:05.107406

  2%|▏         | 34/1508 [04:15<2:24:52,  5.90s/it]

CA_18260_2021 completed in 0:00:05.570364

  2%|▏         | 35/1508 [04:21<2:22:56,  5.82s/it]

CA_19281_2021 completed in 0:00:05.648297

  2%|▏         | 36/1508 [04:26<2:15:14,  5.51s/it]

CO_3989_2021 completed in 0:00:04.784639

  2%|▏         | 37/1508 [04:29<1:59:24,  4.87s/it]

CO_6604_2021 completed in 0:00:03.371403

  3%|▎         | 38/1508 [04:34<1:57:40,  4.80s/it]

CO_9336_2021 completed in 0:00:04.644227

  3%|▎         | 39/1508 [04:39<2:00:43,  4.93s/it]

CO_12866_2021 completed in 0:00:05.226843

  3%|▎         | 40/1508 [04:44<1:57:53,  4.82s/it]

CO_15257_2021 completed in 0:00:04.554305

  3%|▎         | 41/1508 [04:51<2:13:47,  5.47s/it]

CO_15466_2021 completed in 0:00:06.997745

  3%|▎         | 42/1508 [04:56<2:12:20,  5.42s/it]

CO_16603_2021 completed in 0:00:05.284120

  3%|▎         | 43/1508 [05:01<2:12:33,  5.43s/it]

CO_19499_2021 completed in 0:00:05.457063

  3%|▎         | 44/1508 [05:07<2:11:03,  5.37s/it]

CO_27058_2021 completed in 0:00:05.235303

  3%|▎         | 45/1508 [05:12<2:08:28,  5.27s/it]

CO_56146_2021 completed in 0:00:05.029303

  3%|▎         | 46/1508 [05:16<2:04:40,  5.12s/it]

CT_4176_2021 completed in 0:00:04.761564

  3%|▎         | 47/1508 [05:32<3:23:59,  8.38s/it]

CT_7716_2021 completed in 0:00:15.984389

  3%|▎         | 48/1508 [05:37<2:56:46,  7.26s/it]

CT_19497_2021 completed in 0:00:04.667221

  3%|▎         | 49/1508 [05:44<2:51:16,  7.04s/it]

CT_20038_2021 completed in 0:00:06.525086

  3%|▎         | 50/1508 [05:54<3:14:01,  7.98s/it]

DC_15270_2021 completed in 0:00:10.177913

  3%|▎         | 51/1508 [06:03<3:25:17,  8.45s/it]

DE_5027_2021 completed in 0:00:09.550177

  3%|▎         | 52/1508 [06:12<3:27:58,  8.57s/it]

DE_5070_2021 completed in 0:00:08.840523

  4%|▎         | 53/1508 [06:22<3:40:14,  9.08s/it]

DE_5335_2021 completed in 0:00:10.274338

  4%|▎         | 54/1508 [06:28<3:16:32,  8.11s/it]

DE_13519_2021 completed in 0:00:05.842448

  4%|▎         | 55/1508 [06:34<3:00:39,  7.46s/it]

FL_6452_2021 completed in 0:00:05.941742

  4%|▎         | 56/1508 [06:43<3:10:55,  7.89s/it]

FL_6455_2021 completed in 0:00:08.889257

  4%|▍         | 57/1508 [06:50<3:01:31,  7.51s/it]

FL_6457_2021 completed in 0:00:06.611714

  4%|▍         | 58/1508 [06:58<3:06:13,  7.71s/it]

FL_7801_2021 completed in 0:00:08.171652

  4%|▍         | 59/1508 [07:06<3:07:41,  7.77s/it]

FL_9617_2021 completed in 0:00:07.924167

  4%|▍         | 60/1508 [07:11<2:48:29,  6.98s/it]

FL_18454_2021 completed in 0:00:05.138188

  4%|▍         | 61/1508 [07:18<2:51:10,  7.10s/it]

GA_3916_2021 completed in 0:00:07.368150

  4%|▍         | 62/1508 [07:26<2:52:06,  7.14s/it]

GA_9601_2021 completed in 0:00:07.240542

  4%|▍         | 63/1508 [07:33<2:51:29,  7.12s/it]

HI_8287_2021 completed in 0:00:07.068987

  4%|▍         | 64/1508 [07:39<2:45:16,  6.87s/it]

HI_10071_2021 completed in 0:00:06.275902

  4%|▍         | 65/1508 [07:45<2:41:23,  6.71s/it]

HI_11843_2021 completed in 0:00:06.343061

  4%|▍         | 66/1508 [07:49<2:19:52,  5.82s/it]

HI_19547_2021 completed in 0:00:03.740289

  4%|▍         | 67/1508 [07:56<2:25:56,  6.08s/it]

IA_9417_2021 completed in 0:00:06.674768

  5%|▍         | 68/1508 [08:02<2:24:34,  6.02s/it]

IA_12341_2021 completed in 0:00:05.900711

  5%|▍         | 69/1508 [08:10<2:43:56,  6.84s/it]

ID_9187_2021 completed in 0:00:08.724334

  5%|▍         | 70/1508 [08:18<2:50:38,  7.12s/it]

ID_9191_2021 completed in 0:00:07.783624

  5%|▍         | 71/1508 [08:23<2:36:41,  6.54s/it]

ID_10454_2021 completed in 0:00:05.193476

  5%|▍         | 72/1508 [08:29<2:28:56,  6.22s/it]

ID_11273_2021 completed in 0:00:05.478174

  5%|▍         | 73/1508 [08:36<2:39:11,  6.66s/it]

ID_14354_2021 completed in 0:00:07.664564

  5%|▍         | 74/1508 [08:42<2:31:14,  6.33s/it]

ID_20169_2021 completed in 0:00:05.561465

  5%|▍         | 75/1508 [08:48<2:30:02,  6.28s/it]

IL_4110_2021 completed in 0:00:06.175180

  5%|▌         | 76/1508 [08:55<2:37:14,  6.59s/it]

IL_12341_2021 completed in 0:00:07.300502

  5%|▌         | 77/1508 [09:01<2:30:29,  6.31s/it]

IL_13032_2021 completed in 0:00:05.659645

  5%|▌         | 78/1508 [09:10<2:49:04,  7.09s/it]

IL_56697_2021 completed in 0:00:08.920481

  5%|▌         | 79/1508 [09:16<2:39:40,  6.70s/it]

IN_9273_2021 completed in 0:00:05.793477

  5%|▌         | 80/1508 [09:23<2:41:47,  6.80s/it]

IN_9324_2021 completed in 0:00:07.012025

  5%|▌         | 81/1508 [09:30<2:41:27,  6.79s/it]

IN_13756_2021 completed in 0:00:06.764958

  5%|▌         | 82/1508 [09:39<3:02:34,  7.68s/it]

IN_15470_2021 completed in 0:00:09.765260

  6%|▌         | 83/1508 [09:46<2:55:50,  7.40s/it]

IN_17633_2021 completed in 0:00:06.751846

  6%|▌         | 84/1508 [09:52<2:43:30,  6.89s/it]

KS_5860_2021 completed in 0:00:05.687448

  6%|▌         | 85/1508 [09:56<2:24:06,  6.08s/it]

KS_9996_2021 completed in 0:00:04.174754

  6%|▌         | 86/1508 [10:03<2:30:24,  6.35s/it]

KS_10000_2021 completed in 0:00:06.976998

  6%|▌         | 87/1508 [10:08<2:20:59,  5.95s/it]

KS_10005_2021 completed in 0:00:05.034157

  6%|▌         | 88/1508 [10:12<2:10:05,  5.50s/it]

KS_22500_2021 completed in 0:00:04.430135

  6%|▌         | 89/1508 [10:17<2:01:19,  5.13s/it]

KY_9964_2021 completed in 0:00:04.273755

  6%|▌         | 90/1508 [10:22<2:03:13,  5.21s/it]

KY_10171_2021 completed in 0:00:05.405043

  6%|▌         | 91/1508 [10:28<2:05:11,  5.30s/it]

KY_11249_2021 completed in 0:00:05.503142

  6%|▌         | 92/1508 [10:34<2:09:22,  5.48s/it]

KY_17564_2021 completed in 0:00:05.903138

  6%|▌         | 93/1508 [10:38<2:03:11,  5.22s/it]

KY_19446_2021 completed in 0:00:04.620393

  6%|▌         | 94/1508 [10:44<2:07:27,  5.41s/it]

KY_22053_2021 completed in 0:00:05.838675

  6%|▋         | 95/1508 [10:50<2:09:06,  5.48s/it]

KY_49998_2021 completed in 0:00:05.653833

  6%|▋         | 96/1508 [10:56<2:12:16,  5.62s/it]

LA_3265_2021 completed in 0:00:05.943844

  6%|▋         | 97/1508 [11:02<2:14:25,  5.72s/it]

LA_11241_2021 completed in 0:00:05.936947

  6%|▋         | 98/1508 [11:08<2:19:18,  5.93s/it]

LA_13478_2021 completed in 0:00:06.422686

  7%|▋         | 99/1508 [11:15<2:26:37,  6.24s/it]

LA_17698_2021 completed in 0:00:06.978286

  7%|▋         | 100/1508 [11:20<2:16:49,  5.83s/it]

MA_6374_2021 completed in 0:00:04.866790

  7%|▋         | 101/1508 [11:25<2:12:46,  5.66s/it]

MA_8774_2021 completed in 0:00:05.262618

  7%|▋         | 102/1508 [11:31<2:13:47,  5.71s/it]

MA_11804_2021 completed in 0:00:05.820414

  7%|▋         | 103/1508 [11:35<2:04:55,  5.34s/it]

MA_13206_2021 completed in 0:00:04.457016

  7%|▋         | 104/1508 [11:41<2:03:26,  5.28s/it]

MA_15748_2021 completed in 0:00:05.135454

  7%|▋         | 105/1508 [11:48<2:20:59,  6.03s/it]

MA_54913_2021 completed in 0:00:07.788737

  7%|▋         | 106/1508 [11:53<2:09:25,  5.54s/it]

MD_1167_2021 completed in 0:00:04.391893

  7%|▋         | 107/1508 [11:57<2:02:36,  5.25s/it]

MD_5027_2021 completed in 0:00:04.578507

  7%|▋         | 108/1508 [12:04<2:12:00,  5.66s/it]

MD_15263_2021 completed in 0:00:06.605340

  7%|▋         | 109/1508 [12:08<2:01:00,  5.19s/it]

MD_15270_2021 completed in 0:00:04.096288

  7%|▋         | 110/1508 [12:14<2:03:11,  5.29s/it]

MD_17637_2021 completed in 0:00:05.509944

  7%|▋         | 111/1508 [12:20<2:14:07,  5.76s/it]

ME_1179_2021 completed in 0:00:06.865096

  7%|▋         | 112/1508 [12:26<2:10:42,  5.62s/it]

ME_3266_2021 completed in 0:00:05.281234

  7%|▋         | 113/1508 [12:31<2:11:29,  5.66s/it]

ME_5609_2021 completed in 0:00:05.741349

  8%|▊         | 114/1508 [12:37<2:08:00,  5.51s/it]

MI_392_2021 completed in 0:00:05.166720

  8%|▊         | 115/1508 [12:40<1:55:52,  4.99s/it]

MI_3828_2021 completed in 0:00:03.780226

  8%|▊         | 116/1508 [12:46<1:59:20,  5.14s/it]

MI_4254_2021 completed in 0:00:05.499913

  8%|▊         | 117/1508 [12:50<1:50:12,  4.75s/it]

MI_5109_2021 completed in 0:00:03.841132

  8%|▊         | 118/1508 [12:53<1:39:05,  4.28s/it]

MI_9324_2021 completed in 0:00:03.165568

  8%|▊         | 119/1508 [12:57<1:36:28,  4.17s/it]

MI_10704_2021 completed in 0:00:03.910568

  8%|▊         | 120/1508 [13:00<1:33:13,  4.03s/it]

MI_19578_2021 completed in 0:00:03.704029

  8%|▊         | 121/1508 [13:06<1:40:46,  4.36s/it]

MN_689_2021 completed in 0:00:05.127668

  8%|▊         | 122/1508 [13:09<1:34:01,  4.07s/it]

MN_5574_2021 completed in 0:00:03.394379

  8%|▊         | 123/1508 [13:14<1:42:35,  4.44s/it]

MN_10596_2021 completed in 0:00:05.313282

  8%|▊         | 124/1508 [13:20<1:48:06,  4.69s/it]

MN_12647_2021 completed in 0:00:05.251214

  8%|▊         | 125/1508 [13:25<1:50:11,  4.78s/it]

MN_13781_2021 completed in 0:00:04.998458

  8%|▊         | 126/1508 [13:30<1:55:08,  5.00s/it]

MN_14232_2021 completed in 0:00:05.508887

  8%|▊         | 127/1508 [13:35<1:53:55,  4.95s/it]

MN_16181_2021 completed in 0:00:04.834083

  8%|▊         | 128/1508 [13:40<1:53:04,  4.92s/it]

MN_17267_2021 completed in 0:00:04.834290

  9%|▊         | 129/1508 [13:45<1:58:11,  5.14s/it]

MN_20996_2021 completed in 0:00:05.668826

  9%|▊         | 130/1508 [13:50<1:52:45,  4.91s/it]

MN_25177_2021 completed in 0:00:04.364804

  9%|▊         | 131/1508 [13:55<1:51:36,  4.86s/it]

MO_4675_2021 completed in 0:00:04.753665

  9%|▉         | 132/1508 [13:59<1:47:56,  4.71s/it]

MO_5860_2021 completed in 0:00:04.340287

  9%|▉         | 133/1508 [14:03<1:43:42,  4.53s/it]

MO_9231_2021 completed in 0:00:04.097749

  9%|▉         | 134/1508 [14:07<1:40:35,  4.39s/it]

MO_10000_2021 completed in 0:00:04.081599

  9%|▉         | 135/1508 [14:12<1:44:24,  4.56s/it]

MO_12698_2021 completed in 0:00:04.959583

  9%|▉         | 136/1508 [14:17<1:47:24,  4.70s/it]

MO_17833_2021 completed in 0:00:05.006407

  9%|▉         | 137/1508 [14:23<1:54:05,  4.99s/it]

MO_19436_2021 completed in 0:00:05.684161

  9%|▉         | 138/1508 [14:27<1:50:52,  4.86s/it]

MS_3841_2021 completed in 0:00:04.530933

  9%|▉         | 139/1508 [14:33<1:57:21,  5.14s/it]

MS_12685_2021 completed in 0:00:05.814122

  9%|▉         | 140/1508 [14:40<2:07:55,  5.61s/it]

MS_12686_2021 completed in 0:00:06.699857

  9%|▉         | 141/1508 [14:45<2:01:42,  5.34s/it]

MS_17647_2021 completed in 0:00:04.714432

  9%|▉         | 142/1508 [14:51<2:07:28,  5.60s/it]

MT_6395_2021 completed in 0:00:06.197946

  9%|▉         | 143/1508 [14:56<2:06:34,  5.56s/it]

MT_12199_2021 completed in 0:00:05.481219

 10%|▉         | 144/1508 [15:03<2:13:07,  5.86s/it]

MT_12692_2021 completed in 0:00:06.537073

 10%|▉         | 145/1508 [15:09<2:13:51,  5.89s/it]

MT_12825_2021 completed in 0:00:05.976691

 10%|▉         | 146/1508 [15:14<2:10:28,  5.75s/it]

MT_19603_2021 completed in 0:00:05.409393

 10%|▉         | 147/1508 [15:20<2:10:40,  5.76s/it]

MT_20997_2021 completed in 0:00:05.790947

 10%|▉         | 148/1508 [15:26<2:11:57,  5.82s/it]

NC_3046_2021 completed in 0:00:05.963213

 10%|▉         | 149/1508 [15:30<2:03:28,  5.45s/it]

NC_5416_2021 completed in 0:00:04.584852

 10%|▉         | 150/1508 [15:34<1:49:12,  4.83s/it]

NC_9837_2021 completed in 0:00:03.358730

 10%|█         | 151/1508 [15:39<1:49:09,  4.83s/it]

NC_16496_2021 completed in 0:00:04.827361

 10%|█         | 152/1508 [15:44<1:51:32,  4.94s/it]

NC_19876_2021 completed in 0:00:05.190372

 10%|█         | 153/1508 [15:48<1:43:42,  4.59s/it]

NC_24889_2021 completed in 0:00:03.788684

 10%|█         | 154/1508 [15:53<1:47:55,  4.78s/it]

ND_12090_2021 completed in 0:00:05.226084

 10%|█         | 155/1508 [15:59<1:55:24,  5.12s/it]

ND_12301_2021 completed in 0:00:05.898833

 10%|█         | 156/1508 [16:04<1:58:36,  5.26s/it]

ND_14232_2021 completed in 0:00:05.603938

 10%|█         | 157/1508 [16:09<1:55:39,  5.14s/it]

ND_19790_2021 completed in 0:00:04.838988

 10%|█         | 158/1508 [16:14<1:52:23,  5.00s/it]

ND_24949_2021 completed in 0:00:04.665128

 11%|█         | 159/1508 [16:19<1:51:00,  4.94s/it]

NE_4373_2021 completed in 0:00:04.799720

 11%|█         | 160/1508 [16:25<2:03:13,  5.48s/it]

NE_4911_2021 completed in 0:00:06.760202

 11%|█         | 161/1508 [16:30<1:54:22,  5.09s/it]

NE_6779_2021 completed in 0:00:04.183512

 11%|█         | 162/1508 [16:34<1:51:58,  4.99s/it]

NE_11018_2021 completed in 0:00:04.748985

 11%|█         | 163/1508 [16:40<1:57:49,  5.26s/it]

NE_11251_2021 completed in 0:00:05.872998

 11%|█         | 164/1508 [16:45<1:54:05,  5.09s/it]

NE_12539_2021 completed in 0:00:04.712240

 11%|█         | 165/1508 [16:53<2:13:29,  5.96s/it]

NE_13337_2021 completed in 0:00:07.991628

 11%|█         | 166/1508 [16:58<2:07:07,  5.68s/it]

NE_13664_2021 completed in 0:00:05.029081

 11%|█         | 167/1508 [17:03<2:05:04,  5.60s/it]

NE_14127_2021 completed in 0:00:05.391319

 11%|█         | 168/1508 [17:10<2:09:08,  5.78s/it]

NE_17642_2021 completed in 0:00:06.215646

 11%|█         | 169/1508 [17:17<2:17:54,  6.18s/it]

NE_27058_2021 completed in 0:00:07.103245

 11%|█▏        | 170/1508 [17:23<2:20:55,  6.32s/it]

NE_40606_2021 completed in 0:00:06.644511

 11%|█▏        | 171/1508 [17:28<2:08:10,  5.75s/it]

NH_13441_2021 completed in 0:00:04.427019

 11%|█▏        | 172/1508 [17:34<2:11:53,  5.92s/it]

NH_15472_2021 completed in 0:00:06.317013

 11%|█▏        | 173/1508 [17:40<2:09:33,  5.82s/it]

NH_24590_2021 completed in 0:00:05.587793

 12%|█▏        | 174/1508 [17:44<1:59:19,  5.37s/it]

NJ_963_2021 completed in 0:00:04.298471

 12%|█▏        | 175/1508 [17:49<1:56:41,  5.25s/it]

NJ_9726_2021 completed in 0:00:04.984379

 12%|█▏        | 176/1508 [17:53<1:51:10,  5.01s/it]

NJ_15477_2021 completed in 0:00:04.436157

 12%|█▏        | 177/1508 [17:59<1:52:51,  5.09s/it]

NJ_16213_2021 completed in 0:00:05.273102

 12%|█▏        | 178/1508 [18:04<1:54:27,  5.16s/it]

NM_3287_2021 completed in 0:00:05.338073

 12%|█▏        | 179/1508 [18:08<1:49:07,  4.93s/it]

NM_5701_2021 completed in 0:00:04.372432

 12%|█▏        | 180/1508 [18:15<1:59:33,  5.40s/it]

NM_6204_2021 completed in 0:00:06.510658

 12%|█▏        | 181/1508 [18:19<1:53:24,  5.13s/it]

NM_11204_2021 completed in 0:00:04.487359

 12%|█▏        | 182/1508 [18:24<1:52:17,  5.08s/it]

NM_15473_2021 completed in 0:00:04.969984

 12%|█▏        | 183/1508 [18:29<1:50:49,  5.02s/it]

NM_17718_2021 completed in 0:00:04.871607

 12%|█▏        | 184/1508 [18:36<1:59:49,  5.43s/it]

NV_2008_2021 completed in 0:00:06.390774

 12%|█▏        | 185/1508 [18:41<2:00:26,  5.46s/it]

NV_13073_2021 completed in 0:00:05.535125

 12%|█▏        | 186/1508 [18:48<2:11:02,  5.95s/it]

NV_13407_2021 completed in 0:00:07.078491

 12%|█▏        | 187/1508 [18:54<2:11:23,  5.97s/it]

NV_17166_2021 completed in 0:00:06.015297

 12%|█▏        | 188/1508 [18:59<2:02:52,  5.59s/it]

NV_19840_2021 completed in 0:00:04.691804

 13%|█▎        | 189/1508 [19:04<2:01:11,  5.51s/it]

NY_3249_2021 completed in 0:00:05.342140

 13%|█▎        | 190/1508 [19:08<1:51:46,  5.09s/it]

NY_4226_2021 completed in 0:00:04.097281

 13%|█▎        | 191/1508 [19:13<1:51:35,  5.08s/it]

NY_11171_2021 completed in 0:00:05.073312

 13%|█▎        | 192/1508 [19:22<2:14:38,  6.14s/it]

NY_13511_2021 completed in 0:00:08.598907

 13%|█▎        | 193/1508 [19:29<2:19:18,  6.36s/it]

NY_13573_2021 completed in 0:00:06.862553

 13%|█▎        | 194/1508 [19:37<2:28:19,  6.77s/it]

NY_14154_2021 completed in 0:00:07.743696

 13%|█▎        | 195/1508 [19:41<2:15:20,  6.19s/it]

NY_14711_2021 completed in 0:00:04.812748

 13%|█▎        | 196/1508 [19:46<2:06:06,  5.77s/it]

NY_16183_2021 completed in 0:00:04.790448

 13%|█▎        | 197/1508 [20:04<3:22:51,  9.28s/it]

OH_3542_2021 completed in 0:00:17.486729

 13%|█▎        | 198/1508 [20:11<3:07:23,  8.58s/it]

OH_3755_2021 completed in 0:00:06.941840

 13%|█▎        | 199/1508 [20:18<2:55:44,  8.06s/it]

OH_4922_2021 completed in 0:00:06.822272

 13%|█▎        | 200/1508 [20:25<2:51:04,  7.85s/it]

OH_13998_2021 completed in 0:00:07.361379

 13%|█▎        | 201/1508 [20:33<2:55:46,  8.07s/it]

OH_14006_2021 completed in 0:00:08.586241

 13%|█▎        | 202/1508 [20:39<2:38:39,  7.29s/it]

OH_18997_2021 completed in 0:00:05.463326

 13%|█▎        | 203/1508 [20:44<2:23:15,  6.59s/it]

OK_5860_2021 completed in 0:00:04.946703

 14%|█▎        | 204/1508 [20:49<2:16:08,  6.26s/it]

OK_13734_2021 completed in 0:00:05.510493

 14%|█▎        | 205/1508 [20:54<2:04:32,  5.74s/it]

OK_14062_2021 completed in 0:00:04.500469

 14%|█▎        | 206/1508 [21:01<2:10:35,  6.02s/it]

OK_14063_2021 completed in 0:00:06.677653

 14%|█▎        | 207/1508 [21:09<2:29:04,  6.88s/it]

OK_15474_2021 completed in 0:00:08.873792

 14%|█▍        | 208/1508 [21:15<2:22:40,  6.58s/it]

OK_19785_2021 completed in 0:00:05.901302

 14%|█▍        | 209/1508 [21:20<2:07:48,  5.90s/it]

OR_6022_2021 completed in 0:00:04.313670

 14%|█▍        | 210/1508 [21:25<2:02:06,  5.64s/it]

OR_9191_2021 completed in 0:00:05.038321

 14%|█▍        | 211/1508 [21:30<2:00:52,  5.59s/it]

OR_14354_2021 completed in 0:00:05.466765

 14%|█▍        | 212/1508 [21:35<1:57:47,  5.45s/it]

OR_15248_2021 completed in 0:00:05.128865

 14%|█▍        | 213/1508 [21:40<1:50:48,  5.13s/it]

OR_18260_2021 completed in 0:00:04.383440

 14%|█▍        | 214/1508 [21:44<1:43:40,  4.81s/it]

OR_28541_2021 completed in 0:00:04.043811

 14%|█▍        | 215/1508 [21:50<1:53:28,  5.27s/it]

OR_40437_2021 completed in 0:00:06.334465

 14%|█▍        | 216/1508 [21:55<1:49:57,  5.11s/it]

PA_3597_2021 completed in 0:00:04.734744

 14%|█▍        | 217/1508 [22:00<1:53:16,  5.26s/it]

PA_5487_2021 completed in 0:00:05.630814

 14%|█▍        | 218/1508 [22:07<1:58:21,  5.50s/it]

PA_12390_2021 completed in 0:00:06.066022

 15%|█▍        | 219/1508 [22:15<2:15:28,  6.31s/it]

PA_14711_2021 completed in 0:00:08.174062

 15%|█▍        | 220/1508 [22:23<2:29:55,  6.98s/it]

PA_14715_2021 completed in 0:00:08.564965

 15%|█▍        | 221/1508 [22:30<2:28:15,  6.91s/it]

PA_14716_2021 completed in 0:00:06.738830

 15%|█▍        | 222/1508 [22:36<2:19:18,  6.50s/it]

PA_14940_2021 completed in 0:00:05.537287

 15%|█▍        | 223/1508 [22:41<2:14:05,  6.26s/it]

PA_15045_2021 completed in 0:00:05.699381

 15%|█▍        | 224/1508 [22:46<2:02:54,  5.74s/it]

PA_19390_2021 completed in 0:00:04.533954

 15%|█▍        | 225/1508 [22:51<1:59:33,  5.59s/it]

PA_20334_2021 completed in 0:00:05.236053

 15%|█▍        | 226/1508 [22:58<2:09:42,  6.07s/it]

PA_20387_2021 completed in 0:00:07.189504

 15%|█▌        | 227/1508 [23:04<2:05:01,  5.86s/it]

RI_1857_2021 completed in 0:00:05.354593

 15%|█▌        | 228/1508 [23:08<1:54:48,  5.38s/it]

RI_13214_2021 completed in 0:00:04.274230

 15%|█▌        | 229/1508 [23:13<1:54:37,  5.38s/it]

RI_14537_2021 completed in 0:00:05.364227

 15%|█▌        | 230/1508 [23:19<1:57:30,  5.52s/it]

SC_1613_2021 completed in 0:00:05.841148

 15%|█▌        | 231/1508 [23:25<2:02:07,  5.74s/it]

SC_3046_2021 completed in 0:00:06.251856

 15%|█▌        | 232/1508 [23:34<2:20:32,  6.61s/it]

SC_5416_2021 completed in 0:00:08.639646

 15%|█▌        | 233/1508 [23:39<2:08:52,  6.06s/it]

SC_14398_2021 completed in 0:00:04.794584

 16%|█▌        | 234/1508 [23:44<2:02:01,  5.75s/it]

SC_17539_2021 completed in 0:00:05.004204

 16%|█▌        | 235/1508 [23:49<1:56:18,  5.48s/it]

SC_17543_2021 completed in 0:00:04.862719

 16%|█▌        | 236/1508 [23:55<2:00:42,  5.69s/it]

SD_1769_2021 completed in 0:00:06.186490

 16%|█▌        | 237/1508 [24:03<2:16:46,  6.46s/it]

SD_14232_2021 completed in 0:00:08.235578

 16%|█▌        | 238/1508 [24:08<2:05:17,  5.92s/it]

SD_17267_2021 completed in 0:00:04.661774

 16%|█▌        | 239/1508 [24:13<2:01:42,  5.75s/it]

SD_19293_2021 completed in 0:00:05.368879

 16%|█▌        | 240/1508 [24:20<2:10:45,  6.19s/it]

SD_20401_2021 completed in 0:00:07.196549

 16%|█▌        | 241/1508 [24:27<2:16:17,  6.45s/it]

TN_10331_2021 completed in 0:00:07.072130

 16%|█▌        | 242/1508 [24:34<2:18:43,  6.57s/it]

TX_5701_2021 completed in 0:00:06.854061

 16%|█▌        | 243/1508 [24:41<2:18:20,  6.56s/it]

TX_16604_2021 completed in 0:00:06.529497

 16%|█▌        | 244/1508 [24:47<2:16:30,  6.48s/it]

TX_55937_2021 completed in 0:00:06.287894

 16%|█▌        | 245/1508 [24:53<2:13:22,  6.34s/it]

UT_2010_2021 completed in 0:00:06.000843

 16%|█▋        | 246/1508 [24:58<2:03:08,  5.85s/it]

UT_11135_2021 completed in 0:00:04.730269

 16%|█▋        | 247/1508 [25:19<3:38:44, 10.41s/it]

UT_12866_2021 completed in 0:00:21.030824

 16%|█▋        | 248/1508 [25:30<3:44:05, 10.67s/it]

UT_14354_2021 completed in 0:00:11.284071

 17%|█▋        | 249/1508 [25:37<3:20:00,  9.53s/it]

UT_15444_2021 completed in 0:00:06.873361

 17%|█▋        | 250/1508 [25:44<3:06:11,  8.88s/it]

UT_17845_2021 completed in 0:00:07.359180

 17%|█▋        | 251/1508 [25:52<2:56:13,  8.41s/it]

UT_17874_2021 completed in 0:00:07.315799

 17%|█▋        | 252/1508 [25:59<2:46:39,  7.96s/it]

UT_18206_2021 completed in 0:00:06.911090

 17%|█▋        | 253/1508 [26:05<2:37:27,  7.53s/it]

VA_84_2021 completed in 0:00:06.514683

 17%|█▋        | 254/1508 [26:35<4:57:08, 14.22s/it]

VA_733_2021 completed in 0:00:29.818560

 17%|█▋        | 255/1508 [26:41<4:05:05, 11.74s/it]

VA_10171_2021 completed in 0:00:05.947710

 17%|█▋        | 256/1508 [26:47<3:31:04, 10.12s/it]

VA_17066_2021 completed in 0:00:06.330483

 17%|█▋        | 257/1508 [26:56<3:21:46,  9.68s/it]

VA_19876_2021 completed in 0:00:08.654363

 17%|█▋        | 258/1508 [27:01<2:54:42,  8.39s/it]

VA_19882_2021 completed in 0:00:05.372546

 17%|█▋        | 259/1508 [27:09<2:48:01,  8.07s/it]

VA_40228_2021 completed in 0:00:07.337344

 17%|█▋        | 260/1508 [27:16<2:45:30,  7.96s/it]

VT_2548_2021 completed in 0:00:07.687258

 17%|█▋        | 261/1508 [27:23<2:35:39,  7.49s/it]

VT_7601_2021 completed in 0:00:06.396949

 17%|█▋        | 262/1508 [27:28<2:24:33,  6.96s/it]

VT_19791_2021 completed in 0:00:05.726123

 17%|█▋        | 263/1508 [27:34<2:17:11,  6.61s/it]

WA_3660_2021 completed in 0:00:05.794482

 18%|█▊        | 264/1508 [27:41<2:17:32,  6.63s/it]

WA_14354_2021 completed in 0:00:06.685375

 18%|█▊        | 265/1508 [27:48<2:22:10,  6.86s/it]

WA_15500_2021 completed in 0:00:07.395464

 18%|█▊        | 266/1508 [27:55<2:24:23,  6.98s/it]

WA_16868_2021 completed in 0:00:07.236902

 18%|█▊        | 267/1508 [28:01<2:13:31,  6.46s/it]

WA_17470_2021 completed in 0:00:05.240946

 18%|█▊        | 268/1508 [28:17<3:11:51,  9.28s/it]

WA_18429_2021 completed in 0:00:15.879628

 18%|█▊        | 269/1508 [28:23<2:51:09,  8.29s/it]

WA_20169_2021 completed in 0:00:05.965546

 18%|█▊        | 270/1508 [28:29<2:40:54,  7.80s/it]

WI_4715_2021 completed in 0:00:06.655214

 18%|█▊        | 271/1508 [28:34<2:20:33,  6.82s/it]

WI_5574_2021 completed in 0:00:04.529369

 18%|█▊        | 272/1508 [28:39<2:13:11,  6.47s/it]

WI_11479_2021 completed in 0:00:05.642204

 18%|█▊        | 273/1508 [28:45<2:07:55,  6.21s/it]

WI_13697_2021 completed in 0:00:05.628683

 18%|█▊        | 274/1508 [28:52<2:09:31,  6.30s/it]

WI_13780_2021 completed in 0:00:06.483962

 18%|█▊        | 275/1508 [28:57<2:04:33,  6.06s/it]

WI_13815_2021 completed in 0:00:05.509953

 18%|█▊        | 276/1508 [29:03<2:06:29,  6.16s/it]

WI_20847_2021 completed in 0:00:06.387228

 18%|█▊        | 277/1508 [29:09<2:00:40,  5.88s/it]

WI_20856_2021 completed in 0:00:05.229664

 18%|█▊        | 278/1508 [29:15<2:05:45,  6.13s/it]

WI_20860_2021 completed in 0:00:06.721397

 19%|█▊        | 279/1508 [29:22<2:08:23,  6.27s/it]

WV_733_2021 completed in 0:00:06.579838

 19%|█▊        | 280/1508 [29:28<2:06:11,  6.17s/it]

WV_12796_2021 completed in 0:00:05.925185

 19%|█▊        | 281/1508 [29:34<2:03:05,  6.02s/it]

WV_15263_2021 completed in 0:00:05.675066

 19%|█▊        | 282/1508 [29:39<1:57:54,  5.77s/it]

WV_20521_2021 completed in 0:00:05.188463

 19%|█▉        | 283/1508 [29:44<1:57:36,  5.76s/it]

WY_3461_2021 completed in 0:00:05.735587

 19%|█▉        | 284/1508 [29:50<1:58:06,  5.79s/it]

WY_7222_2021 completed in 0:00:05.856646

 19%|█▉        | 285/1508 [29:58<2:09:30,  6.35s/it]

WY_8566_2021 completed in 0:00:07.669277

 19%|█▉        | 286/1508 [30:07<2:25:45,  7.16s/it]

WY_11273_2021 completed in 0:00:09.025125

 19%|█▉        | 287/1508 [30:13<2:15:23,  6.65s/it]

WY_12199_2021 completed in 0:00:05.477717

 19%|█▉        | 288/1508 [30:21<2:28:08,  7.29s/it]

WY_14354_2021 completed in 0:00:08.759355

 19%|█▉        | 289/1508 [30:28<2:23:21,  7.06s/it]

WY_19156_2021 completed in 0:00:06.521393

 19%|█▉        | 290/1508 [30:34<2:16:07,  6.71s/it]

WY_27058_2021 completed in 0:00:05.887079
Skipping utility CA_16612_2021 due to empty or invalid geometry.
Skipping utility CO_10066_2021 due to empty or invalid geometry.
Skipping utility MA_20310_2021 due to empty or invalid geometry.

 19%|█▉        | 294/1508 [30:45<1:24:43,  4.19s/it]

AK_219_2022 completed in 0:00:10.864944

 20%|█▉        | 295/1508 [30:54<1:44:12,  5.15s/it]

AK_3522_2022 completed in 0:00:09.441786

 20%|█▉        | 296/1508 [31:01<1:53:04,  5.60s/it]

AK_7353_2022 completed in 0:00:07.282503

 20%|█▉        | 297/1508 [31:08<1:57:11,  5.81s/it]

AK_11824_2022 completed in 0:00:06.508703

 20%|█▉        | 298/1508 [31:14<1:59:08,  5.91s/it]

AK_19558_2022 completed in 0:00:06.215056

 20%|█▉        | 299/1508 [31:20<2:01:31,  6.03s/it]

AR_814_2022 completed in 0:00:06.380338

 20%|█▉        | 300/1508 [31:27<2:04:01,  6.16s/it]

AR_817_2022 completed in 0:00:06.505737

 20%|█▉        | 301/1508 [31:33<2:04:12,  6.17s/it]

AR_3093_2022 completed in 0:00:06.211473

 20%|██        | 302/1508 [31:38<1:58:33,  5.90s/it]

AR_5860_2022 completed in 0:00:05.205884

 20%|██        | 303/1508 [31:48<2:17:52,  6.87s/it]

AR_6342_2022 completed in 0:00:09.237022

 20%|██        | 304/1508 [31:53<2:12:00,  6.58s/it]

AR_13718_2022 completed in 0:00:05.883735

 20%|██        | 305/1508 [32:03<2:26:43,  7.32s/it]

AR_14063_2022 completed in 0:00:09.086693

 20%|██        | 306/1508 [32:10<2:26:04,  7.29s/it]

AR_17698_2022 completed in 0:00:07.229461

 20%|██        | 307/1508 [32:24<3:07:22,  9.36s/it]

AZ_176_2022 completed in 0:00:14.246617

 20%|██        | 308/1508 [32:36<3:25:27, 10.27s/it]

AZ_803_2022 completed in 0:00:12.420060

 20%|██        | 309/1508 [32:58<4:31:00, 13.56s/it]

AZ_12919_2022 completed in 0:00:21.275517

 21%|██        | 310/1508 [33:06<3:59:31, 12.00s/it]

AZ_16572_2022 completed in 0:00:08.329070

 21%|██        | 311/1508 [33:13<3:30:58, 10.58s/it]

AZ_19189_2022 completed in 0:00:07.248261

 21%|██        | 312/1508 [33:20<3:10:32,  9.56s/it]

AZ_19728_2022 completed in 0:00:07.180849

 21%|██        | 313/1508 [33:28<2:59:05,  8.99s/it]

AZ_21538_2022 completed in 0:00:07.667473

 21%|██        | 314/1508 [33:35<2:46:55,  8.39s/it]

AZ_24211_2022 completed in 0:00:06.971097

 21%|██        | 315/1508 [33:42<2:39:10,  8.01s/it]

CA_4390_2022 completed in 0:00:07.110920

 21%|██        | 316/1508 [33:52<2:50:20,  8.57s/it]

CA_9216_2022 completed in 0:00:09.901791

 21%|██        | 317/1508 [33:59<2:37:13,  7.92s/it]

CA_11208_2022 completed in 0:00:06.392320

 21%|██        | 318/1508 [34:04<2:24:15,  7.27s/it]

CA_12745_2022 completed in 0:00:05.763829

 21%|██        | 319/1508 [34:20<3:12:50,  9.73s/it]

CA_14328_2022 completed in 0:00:15.460985

 21%|██        | 320/1508 [34:26<2:54:53,  8.83s/it]

CA_14354_2022 completed in 0:00:06.736127

 21%|██▏       | 321/1508 [34:35<2:50:50,  8.64s/it]

CA_14534_2022 completed in 0:00:08.174135

 21%|██▏       | 322/1508 [34:41<2:34:53,  7.84s/it]

CA_16534_2022 completed in 0:00:05.968239

 21%|██▏       | 323/1508 [34:48<2:30:02,  7.60s/it]

CA_16609_2022 completed in 0:00:07.035676

 21%|██▏       | 324/1508 [34:53<2:17:41,  6.98s/it]

CA_16655_2022 completed in 0:00:05.532239

 22%|██▏       | 325/1508 [35:03<2:35:30,  7.89s/it]

CA_17609_2022 completed in 0:00:10.008645

 22%|██▏       | 326/1508 [35:12<2:41:40,  8.21s/it]

CA_17612_2022 completed in 0:00:08.950930

 22%|██▏       | 327/1508 [35:20<2:36:53,  7.97s/it]

CA_18260_2022 completed in 0:00:07.418629

 22%|██▏       | 328/1508 [35:26<2:25:47,  7.41s/it]

CA_19281_2022 completed in 0:00:06.111677

 22%|██▏       | 329/1508 [35:32<2:20:58,  7.17s/it]

CO_3989_2022 completed in 0:00:06.617099

 22%|██▏       | 330/1508 [35:38<2:10:08,  6.63s/it]

CO_6604_2022 completed in 0:00:05.354266

 22%|██▏       | 331/1508 [35:44<2:09:42,  6.61s/it]

CO_9336_2022 completed in 0:00:06.572718

 22%|██▏       | 332/1508 [35:51<2:10:54,  6.68s/it]

CO_12866_2022 completed in 0:00:06.834608

 22%|██▏       | 333/1508 [36:01<2:28:38,  7.59s/it]

CO_15257_2022 completed in 0:00:09.714158

 22%|██▏       | 334/1508 [36:08<2:25:04,  7.41s/it]

CO_15466_2022 completed in 0:00:07.004534

 22%|██▏       | 335/1508 [36:14<2:19:33,  7.14s/it]

CO_16603_2022 completed in 0:00:06.488234

 22%|██▏       | 336/1508 [36:22<2:20:40,  7.20s/it]

CO_19499_2022 completed in 0:00:07.347300

 22%|██▏       | 337/1508 [36:27<2:08:26,  6.58s/it]

CO_27058_2022 completed in 0:00:05.132499

 22%|██▏       | 338/1508 [36:32<1:58:22,  6.07s/it]

CO_56146_2022 completed in 0:00:04.877024

 22%|██▏       | 339/1508 [36:36<1:50:13,  5.66s/it]

CT_4176_2022 completed in 0:00:04.688233

 23%|██▎       | 340/1508 [36:42<1:52:24,  5.77s/it]

CT_7716_2022 completed in 0:00:06.046931

 23%|██▎       | 341/1508 [36:48<1:51:10,  5.72s/it]

CT_19497_2022 completed in 0:00:05.576738

 23%|██▎       | 342/1508 [36:54<1:51:44,  5.75s/it]

CT_20038_2022 completed in 0:00:05.830150

 23%|██▎       | 343/1508 [36:59<1:49:26,  5.64s/it]

DC_15270_2022 completed in 0:00:05.368881

 23%|██▎       | 344/1508 [37:06<1:57:44,  6.07s/it]

DE_5027_2022 completed in 0:00:07.078210

 23%|██▎       | 345/1508 [37:13<1:59:06,  6.14s/it]

DE_5070_2022 completed in 0:00:06.320413

 23%|██▎       | 346/1508 [37:20<2:08:36,  6.64s/it]

DE_5335_2022 completed in 0:00:07.795950

 23%|██▎       | 347/1508 [37:28<2:16:14,  7.04s/it]

DE_13519_2022 completed in 0:00:07.975827

 23%|██▎       | 348/1508 [37:36<2:19:55,  7.24s/it]

FL_6452_2022 completed in 0:00:07.695124

 23%|██▎       | 349/1508 [37:46<2:32:51,  7.91s/it]

FL_6455_2022 completed in 0:00:09.485361

 23%|██▎       | 350/1508 [37:52<2:25:50,  7.56s/it]

FL_6457_2022 completed in 0:00:06.719266

 23%|██▎       | 351/1508 [37:59<2:22:20,  7.38s/it]

FL_9617_2022 completed in 0:00:06.971429

 23%|██▎       | 352/1508 [38:06<2:21:25,  7.34s/it]

FL_18454_2022 completed in 0:00:07.242828

 23%|██▎       | 353/1508 [38:15<2:25:27,  7.56s/it]

GA_3916_2022 completed in 0:00:08.059624

 23%|██▎       | 354/1508 [38:21<2:19:33,  7.26s/it]

GA_9601_2022 completed in 0:00:06.554929

 24%|██▎       | 355/1508 [38:26<2:04:40,  6.49s/it]

HI_8287_2022 completed in 0:00:04.693242

 24%|██▎       | 356/1508 [38:32<2:03:30,  6.43s/it]

HI_10071_2022 completed in 0:00:06.302895

 24%|██▎       | 357/1508 [38:38<2:01:43,  6.35s/it]

HI_11843_2022 completed in 0:00:06.142544

 24%|██▎       | 358/1508 [38:44<1:59:47,  6.25s/it]

HI_19547_2022 completed in 0:00:06.025124

 24%|██▍       | 359/1508 [38:53<2:14:45,  7.04s/it]

IA_9417_2022 completed in 0:00:08.872195

 24%|██▍       | 360/1508 [39:00<2:13:38,  6.99s/it]

IA_12341_2022 completed in 0:00:06.862765

 24%|██▍       | 361/1508 [39:06<2:09:35,  6.78s/it]

ID_9187_2022 completed in 0:00:06.293574

 24%|██▍       | 362/1508 [39:14<2:13:55,  7.01s/it]

ID_9191_2022 completed in 0:00:07.555019

 24%|██▍       | 363/1508 [39:21<2:12:51,  6.96s/it]

ID_10454_2022 completed in 0:00:06.843884

 24%|██▍       | 364/1508 [39:27<2:07:59,  6.71s/it]

ID_11273_2022 completed in 0:00:06.130624

 24%|██▍       | 365/1508 [39:37<2:29:57,  7.87s/it]

ID_14354_2022 completed in 0:00:10.575487

 24%|██▍       | 366/1508 [39:44<2:24:09,  7.57s/it]

ID_20169_2022 completed in 0:00:06.875619

 24%|██▍       | 367/1508 [39:52<2:25:58,  7.68s/it]

IL_4110_2022 completed in 0:00:07.912871

 24%|██▍       | 368/1508 [39:59<2:20:17,  7.38s/it]

IL_12341_2022 completed in 0:00:06.701412

 24%|██▍       | 369/1508 [40:06<2:15:55,  7.16s/it]

IL_13032_2022 completed in 0:00:06.637831

 25%|██▍       | 370/1508 [40:15<2:31:37,  7.99s/it]

IL_56697_2022 completed in 0:00:09.940733

 25%|██▍       | 371/1508 [40:22<2:21:43,  7.48s/it]

IN_9273_2022 completed in 0:00:06.274980

 25%|██▍       | 372/1508 [40:29<2:22:14,  7.51s/it]

IN_9324_2022 completed in 0:00:07.591486

 25%|██▍       | 373/1508 [40:37<2:21:54,  7.50s/it]

IN_13756_2022 completed in 0:00:07.474835

 25%|██▍       | 374/1508 [40:47<2:38:24,  8.38s/it]

IN_15470_2022 completed in 0:00:10.433799

 25%|██▍       | 375/1508 [40:54<2:27:21,  7.80s/it]

IN_17633_2022 completed in 0:00:06.455014

 25%|██▍       | 376/1508 [41:00<2:19:53,  7.41s/it]

KS_5860_2022 completed in 0:00:06.504622

 25%|██▌       | 377/1508 [41:06<2:08:42,  6.83s/it]

KS_9996_2022 completed in 0:00:05.457495

 25%|██▌       | 378/1508 [41:12<2:04:44,  6.62s/it]

KS_10000_2022 completed in 0:00:06.145483

 25%|██▌       | 379/1508 [41:17<1:58:47,  6.31s/it]

KS_10005_2022 completed in 0:00:05.589889

 25%|██▌       | 380/1508 [41:24<2:00:14,  6.40s/it]

KS_22500_2022 completed in 0:00:06.585872

 25%|██▌       | 381/1508 [41:31<2:01:00,  6.44s/it]

KY_9964_2022 completed in 0:00:06.552265

 25%|██▌       | 382/1508 [41:40<2:17:56,  7.35s/it]

KY_10171_2022 completed in 0:00:09.461365

 25%|██▌       | 383/1508 [41:46<2:11:59,  7.04s/it]

KY_11249_2022 completed in 0:00:06.314356

 25%|██▌       | 384/1508 [41:53<2:09:11,  6.90s/it]

KY_17564_2022 completed in 0:00:06.561335

 26%|██▌       | 385/1508 [41:58<2:00:34,  6.44s/it]

KY_19446_2022 completed in 0:00:05.375261

 26%|██▌       | 386/1508 [42:05<1:59:31,  6.39s/it]

KY_22053_2022 completed in 0:00:06.275407

 26%|██▌       | 387/1508 [42:11<1:58:22,  6.34s/it]

KY_49998_2022 completed in 0:00:06.204096

 26%|██▌       | 388/1508 [42:20<2:15:16,  7.25s/it]

LA_3265_2022 completed in 0:00:09.370791

 26%|██▌       | 389/1508 [42:27<2:12:56,  7.13s/it]

LA_11241_2022 completed in 0:00:06.851025

 26%|██▌       | 390/1508 [42:33<2:07:23,  6.84s/it]

LA_13478_2022 completed in 0:00:06.155227

 26%|██▌       | 391/1508 [42:41<2:11:20,  7.05s/it]

LA_17698_2022 completed in 0:00:07.563585

 26%|██▌       | 392/1508 [42:47<2:05:54,  6.77s/it]

MA_6374_2022 completed in 0:00:06.100921

 26%|██▌       | 393/1508 [42:54<2:09:32,  6.97s/it]

MA_8774_2022 completed in 0:00:07.439823

 26%|██▌       | 394/1508 [43:01<2:06:35,  6.82s/it]

MA_11804_2022 completed in 0:00:06.460490

 26%|██▌       | 395/1508 [43:07<2:04:23,  6.71s/it]

MA_13206_2022 completed in 0:00:06.444658

 26%|██▋       | 396/1508 [43:13<1:59:34,  6.45s/it]

MA_15748_2022 completed in 0:00:05.857092

 26%|██▋       | 397/1508 [43:19<1:59:19,  6.44s/it]

MA_54913_2022 completed in 0:00:06.426527

 26%|██▋       | 398/1508 [43:26<1:58:19,  6.40s/it]

MD_1167_2022 completed in 0:00:06.274818

 26%|██▋       | 399/1508 [43:35<2:11:39,  7.12s/it]

MD_5027_2022 completed in 0:00:08.818484

 27%|██▋       | 400/1508 [43:40<2:02:35,  6.64s/it]

MD_15263_2022 completed in 0:00:05.505500

 27%|██▋       | 401/1508 [43:45<1:53:18,  6.14s/it]

MD_15270_2022 completed in 0:00:04.980319

 27%|██▋       | 402/1508 [43:51<1:52:59,  6.13s/it]

MD_17637_2022 completed in 0:00:06.100724

 27%|██▋       | 403/1508 [43:58<1:58:29,  6.43s/it]

ME_1179_2022 completed in 0:00:07.143066

 27%|██▋       | 404/1508 [44:05<1:57:48,  6.40s/it]

ME_3266_2022 completed in 0:00:06.327723

 27%|██▋       | 405/1508 [44:11<2:00:24,  6.55s/it]

ME_5609_2022 completed in 0:00:06.894551

 27%|██▋       | 406/1508 [44:17<1:54:41,  6.24s/it]

MI_392_2022 completed in 0:00:05.530690

 27%|██▋       | 407/1508 [44:23<1:51:20,  6.07s/it]

MI_3828_2022 completed in 0:00:05.655347

 27%|██▋       | 408/1508 [44:30<1:56:18,  6.34s/it]

MI_4254_2022 completed in 0:00:06.988206

 27%|██▋       | 409/1508 [44:36<1:56:09,  6.34s/it]

MI_5109_2022 completed in 0:00:06.330014

 27%|██▋       | 410/1508 [44:44<2:02:23,  6.69s/it]

MI_9324_2022 completed in 0:00:07.494693

 27%|██▋       | 411/1508 [44:49<1:56:28,  6.37s/it]

MI_10704_2022 completed in 0:00:05.628971

 27%|██▋       | 412/1508 [45:02<2:29:38,  8.19s/it]

MI_19578_2022 completed in 0:00:12.442330

 27%|██▋       | 413/1508 [45:07<2:12:08,  7.24s/it]

MN_689_2022 completed in 0:00:05.020266

 27%|██▋       | 414/1508 [45:13<2:06:33,  6.94s/it]

MN_5574_2022 completed in 0:00:06.240051

 28%|██▊       | 415/1508 [45:18<1:55:33,  6.34s/it]

MN_10596_2022 completed in 0:00:04.947699

 28%|██▊       | 416/1508 [45:24<1:52:48,  6.20s/it]

MN_12647_2022 completed in 0:00:05.859946

 28%|██▊       | 417/1508 [45:31<2:01:24,  6.68s/it]

MN_13781_2022 completed in 0:00:07.793794

 28%|██▊       | 418/1508 [45:37<1:54:54,  6.33s/it]

MN_14232_2022 completed in 0:00:05.503283

 28%|██▊       | 419/1508 [45:43<1:52:37,  6.20s/it]

MN_16181_2022 completed in 0:00:05.923222

 28%|██▊       | 420/1508 [45:47<1:41:23,  5.59s/it]

MN_17267_2022 completed in 0:00:04.158301

 28%|██▊       | 421/1508 [45:54<1:48:33,  5.99s/it]

MN_20996_2022 completed in 0:00:06.925394

 28%|██▊       | 422/1508 [46:00<1:49:28,  6.05s/it]

MN_25177_2022 completed in 0:00:06.177279

 28%|██▊       | 423/1508 [46:07<1:52:55,  6.24s/it]

MO_4675_2022 completed in 0:00:06.700785

 28%|██▊       | 424/1508 [46:13<1:51:03,  6.15s/it]

MO_5860_2022 completed in 0:00:05.920865

 28%|██▊       | 425/1508 [46:18<1:47:25,  5.95s/it]

MO_9231_2022 completed in 0:00:05.493642

 28%|██▊       | 426/1508 [46:24<1:48:00,  5.99s/it]

MO_10000_2022 completed in 0:00:06.077803

 28%|██▊       | 427/1508 [46:29<1:42:05,  5.67s/it]

MO_12698_2022 completed in 0:00:04.912501

 28%|██▊       | 428/1508 [46:35<1:40:06,  5.56s/it]

MO_17833_2022 completed in 0:00:05.315959

 28%|██▊       | 429/1508 [46:41<1:42:49,  5.72s/it]

MO_19436_2022 completed in 0:00:06.077300

 29%|██▊       | 430/1508 [46:47<1:48:38,  6.05s/it]

MS_3841_2022 completed in 0:00:06.814904

 29%|██▊       | 431/1508 [46:55<1:57:04,  6.52s/it]

MS_12685_2022 completed in 0:00:07.626727

 29%|██▊       | 432/1508 [47:02<1:58:34,  6.61s/it]

MS_12686_2022 completed in 0:00:06.820264

 29%|██▊       | 433/1508 [47:08<1:56:42,  6.51s/it]

MS_17647_2022 completed in 0:00:06.283715

 29%|██▉       | 434/1508 [47:14<1:50:32,  6.18s/it]

MT_6395_2022 completed in 0:00:05.386433

 29%|██▉       | 435/1508 [47:20<1:52:30,  6.29s/it]

MT_12199_2022 completed in 0:00:06.559269

 29%|██▉       | 436/1508 [47:25<1:44:27,  5.85s/it]

MT_12692_2022 completed in 0:00:04.801398

 29%|██▉       | 437/1508 [47:32<1:49:10,  6.12s/it]

MT_12825_2022 completed in 0:00:06.746222

 29%|██▉       | 438/1508 [47:36<1:41:53,  5.71s/it]

MT_19603_2022 completed in 0:00:04.772754

 29%|██▉       | 439/1508 [47:41<1:34:47,  5.32s/it]

MT_20997_2022 completed in 0:00:04.399350

 29%|██▉       | 440/1508 [47:49<1:47:26,  6.04s/it]

NC_3046_2022 completed in 0:00:07.705021

 29%|██▉       | 441/1508 [47:56<1:54:17,  6.43s/it]

NC_5416_2022 completed in 0:00:07.337437

 29%|██▉       | 442/1508 [48:01<1:47:03,  6.03s/it]

NC_9837_2022 completed in 0:00:05.089215

 29%|██▉       | 443/1508 [48:08<1:51:51,  6.30s/it]

NC_16496_2022 completed in 0:00:06.942306

 29%|██▉       | 444/1508 [48:16<1:58:25,  6.68s/it]

NC_19876_2022 completed in 0:00:07.553372

 30%|██▉       | 445/1508 [48:21<1:54:23,  6.46s/it]

NC_24889_2022 completed in 0:00:05.940106

 30%|██▉       | 446/1508 [48:27<1:49:58,  6.21s/it]

ND_12090_2022 completed in 0:00:05.643649

 30%|██▉       | 447/1508 [48:33<1:47:24,  6.07s/it]

ND_12301_2022 completed in 0:00:05.749973

 30%|██▉       | 448/1508 [48:40<1:52:58,  6.39s/it]

ND_14232_2022 completed in 0:00:07.141284

 30%|██▉       | 449/1508 [48:46<1:50:13,  6.24s/it]

ND_19790_2022 completed in 0:00:05.894477
Skipping utility ND_20413_2022 due to empty or invalid geometry.

 30%|██▉       | 451/1508 [48:52<1:24:39,  4.81s/it]

ND_24949_2022 completed in 0:00:06.250410

 30%|██▉       | 452/1508 [48:58<1:30:24,  5.14s/it]

NE_4373_2022 completed in 0:00:06.141224

 30%|███       | 453/1508 [49:04<1:31:56,  5.23s/it]

NE_4911_2022 completed in 0:00:05.487298

 30%|███       | 454/1508 [49:09<1:32:11,  5.25s/it]

NE_6779_2022 completed in 0:00:05.297223

 30%|███       | 455/1508 [49:15<1:33:14,  5.31s/it]

NE_11018_2022 completed in 0:00:05.479853

 30%|███       | 456/1508 [49:26<2:04:46,  7.12s/it]

NE_11251_2022 completed in 0:00:11.622929

 30%|███       | 457/1508 [49:32<1:56:17,  6.64s/it]

NE_12539_2022 completed in 0:00:05.463505

 30%|███       | 458/1508 [49:39<1:59:41,  6.84s/it]

NE_13337_2022 completed in 0:00:07.323140

 30%|███       | 459/1508 [49:46<1:58:57,  6.80s/it]

NE_13664_2022 completed in 0:00:06.714350

 31%|███       | 460/1508 [49:52<1:57:05,  6.70s/it]

NE_14127_2022 completed in 0:00:06.465470

 31%|███       | 461/1508 [50:02<2:11:43,  7.55s/it]

NE_17642_2022 completed in 0:00:09.541958

 31%|███       | 462/1508 [50:10<2:13:02,  7.63s/it]

NE_27058_2022 completed in 0:00:07.824068

 31%|███       | 463/1508 [50:16<2:06:09,  7.24s/it]

NE_40606_2022 completed in 0:00:06.331123

 31%|███       | 464/1508 [50:25<2:17:06,  7.88s/it]

NH_13441_2022 completed in 0:00:09.362428

 31%|███       | 465/1508 [50:34<2:19:43,  8.04s/it]

NH_15472_2022 completed in 0:00:08.407154

 31%|███       | 466/1508 [50:40<2:08:41,  7.41s/it]

NH_24590_2022 completed in 0:00:05.943328

 31%|███       | 467/1508 [50:49<2:18:03,  7.96s/it]

NJ_963_2022 completed in 0:00:09.229676

 31%|███       | 468/1508 [50:56<2:14:27,  7.76s/it]

NJ_9726_2022 completed in 0:00:07.289731

 31%|███       | 469/1508 [51:03<2:08:49,  7.44s/it]

NJ_15477_2022 completed in 0:00:06.695713

 31%|███       | 470/1508 [51:09<2:04:39,  7.21s/it]

NJ_16213_2022 completed in 0:00:06.659087

 31%|███       | 471/1508 [51:16<2:01:41,  7.04s/it]

NM_3287_2022 completed in 0:00:06.657200

 31%|███▏      | 472/1508 [51:24<2:07:34,  7.39s/it]

NM_5701_2022 completed in 0:00:08.197078

 31%|███▏      | 473/1508 [51:31<2:01:14,  7.03s/it]

NM_6204_2022 completed in 0:00:06.187434

 31%|███▏      | 474/1508 [51:37<1:58:31,  6.88s/it]

NM_11204_2022 completed in 0:00:06.522502

 31%|███▏      | 475/1508 [51:43<1:55:34,  6.71s/it]

NM_15473_2022 completed in 0:00:06.328307

 32%|███▏      | 476/1508 [51:51<1:59:36,  6.95s/it]

NM_17718_2022 completed in 0:00:07.513179

 32%|███▏      | 477/1508 [51:56<1:52:15,  6.53s/it]

NV_2008_2022 completed in 0:00:05.552379

 32%|███▏      | 478/1508 [52:03<1:50:03,  6.41s/it]

NV_13073_2022 completed in 0:00:06.124593

 32%|███▏      | 479/1508 [52:09<1:52:10,  6.54s/it]

NV_13407_2022 completed in 0:00:06.841778

 32%|███▏      | 480/1508 [52:15<1:49:33,  6.39s/it]

NV_17166_2022 completed in 0:00:06.053218

 32%|███▏      | 481/1508 [52:23<1:54:59,  6.72s/it]

NV_19840_2022 completed in 0:00:07.473567

 32%|███▏      | 482/1508 [52:32<2:07:59,  7.48s/it]

NY_3249_2022 completed in 0:00:09.271324

 32%|███▏      | 483/1508 [52:40<2:08:37,  7.53s/it]

NY_4226_2022 completed in 0:00:07.633884

 32%|███▏      | 484/1508 [52:45<1:57:24,  6.88s/it]

NY_11171_2022 completed in 0:00:05.362616

 32%|███▏      | 485/1508 [52:55<2:12:24,  7.77s/it]

NY_13511_2022 completed in 0:00:09.831863

 32%|███▏      | 486/1508 [53:04<2:19:16,  8.18s/it]

NY_13573_2022 completed in 0:00:09.133093

 32%|███▏      | 487/1508 [53:11<2:10:33,  7.67s/it]

NY_14154_2022 completed in 0:00:06.493225

 32%|███▏      | 488/1508 [53:20<2:19:52,  8.23s/it]

NY_14711_2022 completed in 0:00:09.523075

 32%|███▏      | 489/1508 [53:30<2:28:50,  8.76s/it]

NY_16183_2022 completed in 0:00:10.010257

 32%|███▏      | 490/1508 [53:38<2:23:41,  8.47s/it]

OH_3542_2022 completed in 0:00:07.780017

 33%|███▎      | 491/1508 [53:46<2:18:49,  8.19s/it]

OH_3755_2022 completed in 0:00:07.537878

 33%|███▎      | 492/1508 [53:53<2:17:08,  8.10s/it]

OH_4922_2022 completed in 0:00:07.883701

 33%|███▎      | 493/1508 [54:04<2:31:02,  8.93s/it]

OH_13998_2022 completed in 0:00:10.864092

 33%|███▎      | 494/1508 [54:18<2:53:01, 10.24s/it]

OH_14006_2022 completed in 0:00:13.294930

 33%|███▎      | 495/1508 [54:26<2:43:37,  9.69s/it]

OH_18997_2022 completed in 0:00:08.412451

 33%|███▎      | 496/1508 [54:34<2:33:10,  9.08s/it]

OK_5860_2022 completed in 0:00:07.657014

 33%|███▎      | 497/1508 [54:42<2:29:54,  8.90s/it]

OK_13734_2022 completed in 0:00:08.463858

 33%|███▎      | 498/1508 [54:50<2:25:26,  8.64s/it]

OK_14062_2022 completed in 0:00:08.040688

 33%|███▎      | 499/1508 [55:01<2:34:22,  9.18s/it]

OK_14063_2022 completed in 0:00:10.439728

 33%|███▎      | 500/1508 [55:09<2:30:55,  8.98s/it]

OK_15474_2022 completed in 0:00:08.523124

 33%|███▎      | 501/1508 [55:17<2:27:27,  8.79s/it]

OK_19785_2022 completed in 0:00:08.325825

 33%|███▎      | 502/1508 [55:26<2:26:08,  8.72s/it]

OR_6022_2022 completed in 0:00:08.552705

 33%|███▎      | 503/1508 [55:39<2:45:41,  9.89s/it]

OR_9191_2022 completed in 0:00:12.634811

 33%|███▎      | 504/1508 [55:47<2:39:23,  9.53s/it]

OR_14354_2022 completed in 0:00:08.668097

 33%|███▎      | 505/1508 [55:56<2:34:58,  9.27s/it]

OR_15248_2022 completed in 0:00:08.676687

 34%|███▎      | 506/1508 [56:03<2:23:35,  8.60s/it]

OR_18260_2022 completed in 0:00:07.027565

 34%|███▎      | 507/1508 [56:10<2:14:18,  8.05s/it]

OR_28541_2022 completed in 0:00:06.770093

 34%|███▎      | 508/1508 [56:17<2:08:37,  7.72s/it]

OR_40437_2022 completed in 0:00:06.941541

 34%|███▍      | 509/1508 [56:24<2:07:09,  7.64s/it]

PA_3597_2022 completed in 0:00:07.448065

 34%|███▍      | 510/1508 [56:33<2:11:40,  7.92s/it]

PA_5487_2022 completed in 0:00:08.563252

 34%|███▍      | 511/1508 [56:44<2:27:40,  8.89s/it]

PA_12390_2022 completed in 0:00:11.152933

 34%|███▍      | 512/1508 [56:57<2:47:19, 10.08s/it]

PA_14711_2022 completed in 0:00:12.860471

 34%|███▍      | 513/1508 [57:07<2:49:04, 10.20s/it]

PA_14715_2022 completed in 0:00:10.464638

 34%|███▍      | 514/1508 [57:15<2:38:30,  9.57s/it]

PA_14716_2022 completed in 0:00:08.104242

 34%|███▍      | 515/1508 [57:23<2:28:19,  8.96s/it]

PA_14940_2022 completed in 0:00:07.545887

 34%|███▍      | 516/1508 [57:30<2:19:44,  8.45s/it]

PA_15045_2022 completed in 0:00:07.262344

 34%|███▍      | 517/1508 [57:37<2:14:10,  8.12s/it]

PA_19390_2022 completed in 0:00:07.357312

 34%|███▍      | 518/1508 [57:44<2:07:24,  7.72s/it]

PA_20334_2022 completed in 0:00:06.779365

 34%|███▍      | 519/1508 [57:54<2:19:16,  8.45s/it]

PA_20387_2022 completed in 0:00:10.145736

 34%|███▍      | 520/1508 [58:03<2:17:31,  8.35s/it]

RI_1857_2022 completed in 0:00:08.124835

 35%|███▍      | 521/1508 [58:10<2:12:28,  8.05s/it]

RI_13214_2022 completed in 0:00:07.351407

 35%|███▍      | 522/1508 [58:18<2:10:23,  7.93s/it]

RI_14537_2022 completed in 0:00:07.657115

 35%|███▍      | 523/1508 [58:24<2:04:49,  7.60s/it]

SC_1613_2022 completed in 0:00:06.828453

 35%|███▍      | 524/1508 [58:31<2:01:56,  7.44s/it]

SC_3046_2022 completed in 0:00:07.044216

 35%|███▍      | 525/1508 [58:39<2:02:01,  7.45s/it]

SC_5416_2022 completed in 0:00:07.472195

 35%|███▍      | 526/1508 [58:46<2:00:19,  7.35s/it]

SC_14398_2022 completed in 0:00:07.122246

 35%|███▍      | 527/1508 [58:53<1:59:45,  7.32s/it]

SC_17539_2022 completed in 0:00:07.258167

 35%|███▌      | 528/1508 [59:01<2:00:45,  7.39s/it]

SC_17543_2022 completed in 0:00:07.552616

 35%|███▌      | 529/1508 [59:08<1:58:41,  7.27s/it]

SD_1769_2022 completed in 0:00:06.995762

 35%|███▌      | 530/1508 [59:16<2:01:46,  7.47s/it]

SD_14232_2022 completed in 0:00:07.927837

 35%|███▌      | 531/1508 [59:23<2:01:53,  7.49s/it]

SD_17267_2022 completed in 0:00:07.520781

 35%|███▌      | 532/1508 [59:31<2:02:26,  7.53s/it]

SD_19293_2022 completed in 0:00:07.621305

 35%|███▌      | 533/1508 [59:38<2:01:26,  7.47s/it]

SD_20401_2022 completed in 0:00:07.346664

 35%|███▌      | 534/1508 [59:46<2:01:51,  7.51s/it]

TN_10331_2022 completed in 0:00:07.583707

 35%|███▌      | 535/1508 [59:53<2:01:17,  7.48s/it]

TX_5701_2022 completed in 0:00:07.414960

 36%|███▌      | 536/1508 [1:00:01<2:04:06,  7.66s/it]

TX_16604_2022 completed in 0:00:08.082772

 36%|███▌      | 537/1508 [1:00:11<2:13:28,  8.25s/it]

TX_55937_2022 completed in 0:00:09.617731

 36%|███▌      | 538/1508 [1:00:20<2:16:59,  8.47s/it]

UT_2010_2022 completed in 0:00:08.999203

 36%|███▌      | 539/1508 [1:00:28<2:15:42,  8.40s/it]

UT_11135_2022 completed in 0:00:08.237229

 36%|███▌      | 540/1508 [1:00:36<2:13:36,  8.28s/it]

UT_12866_2022 completed in 0:00:07.998250

 36%|███▌      | 541/1508 [1:00:47<2:23:16,  8.89s/it]

UT_14354_2022 completed in 0:00:10.306523

 36%|███▌      | 542/1508 [1:00:54<2:17:11,  8.52s/it]

UT_15444_2022 completed in 0:00:07.659800

 36%|███▌      | 543/1508 [1:01:01<2:09:41,  8.06s/it]

UT_17845_2022 completed in 0:00:06.995638

 36%|███▌      | 544/1508 [1:01:11<2:15:47,  8.45s/it]

UT_17874_2022 completed in 0:00:09.356522

 36%|███▌      | 545/1508 [1:01:19<2:18:03,  8.60s/it]

UT_18206_2022 completed in 0:00:08.951721

 36%|███▌      | 546/1508 [1:01:28<2:16:44,  8.53s/it]

VA_84_2022 completed in 0:00:08.350984

 36%|███▋      | 547/1508 [1:01:38<2:24:46,  9.04s/it]

VA_733_2022 completed in 0:00:10.228298

 36%|███▋      | 548/1508 [1:01:46<2:18:10,  8.64s/it]

VA_10171_2022 completed in 0:00:07.693138

 36%|███▋      | 549/1508 [1:01:58<2:37:27,  9.85s/it]

VA_17066_2022 completed in 0:00:12.688771

 36%|███▋      | 550/1508 [1:02:11<2:51:29, 10.74s/it]

VA_19876_2022 completed in 0:00:12.809105

 37%|███▋      | 551/1508 [1:02:19<2:38:23,  9.93s/it]

VA_19882_2022 completed in 0:00:08.037020

 37%|███▋      | 552/1508 [1:02:28<2:31:14,  9.49s/it]

VA_40228_2022 completed in 0:00:08.464250

 37%|███▋      | 553/1508 [1:02:36<2:25:04,  9.11s/it]

VT_2548_2022 completed in 0:00:08.233121

 37%|███▋      | 554/1508 [1:02:47<2:33:21,  9.65s/it]

VT_7601_2022 completed in 0:00:10.884391

 37%|███▋      | 555/1508 [1:02:55<2:26:17,  9.21s/it]

VT_19791_2022 completed in 0:00:08.194227

 37%|███▋      | 556/1508 [1:03:08<2:44:36, 10.37s/it]

WA_3660_2022 completed in 0:00:13.089104

 37%|███▋      | 557/1508 [1:03:22<2:59:50, 11.35s/it]

WA_14354_2022 completed in 0:00:13.607725

 37%|███▋      | 558/1508 [1:03:32<2:56:07, 11.12s/it]

WA_15500_2022 completed in 0:00:10.601531

 37%|███▋      | 559/1508 [1:03:41<2:41:50, 10.23s/it]

WA_16868_2022 completed in 0:00:08.141362

 37%|███▋      | 560/1508 [1:03:53<2:50:11, 10.77s/it]

WA_17470_2022 completed in 0:00:12.029372

 37%|███▋      | 561/1508 [1:04:01<2:37:41,  9.99s/it]

WA_18429_2022 completed in 0:00:08.170786

 37%|███▋      | 562/1508 [1:04:12<2:44:09, 10.41s/it]

WA_20169_2022 completed in 0:00:11.392521

 37%|███▋      | 563/1508 [1:04:22<2:41:23, 10.25s/it]

WI_4715_2022 completed in 0:00:09.861597

 37%|███▋      | 564/1508 [1:04:31<2:36:49,  9.97s/it]

WI_5574_2022 completed in 0:00:09.311565

 37%|███▋      | 565/1508 [1:04:41<2:35:08,  9.87s/it]

WI_11479_2022 completed in 0:00:09.645614

 38%|███▊      | 566/1508 [1:04:50<2:31:22,  9.64s/it]

WI_13697_2022 completed in 0:00:09.106434

 38%|███▊      | 567/1508 [1:05:04<2:50:10, 10.85s/it]

WI_13780_2022 completed in 0:00:13.669992

 38%|███▊      | 568/1508 [1:05:13<2:44:30, 10.50s/it]

WI_13815_2022 completed in 0:00:09.681355

 38%|███▊      | 569/1508 [1:05:23<2:40:30, 10.26s/it]

WI_20847_2022 completed in 0:00:09.684849

 38%|███▊      | 570/1508 [1:05:33<2:40:02, 10.24s/it]

WI_20856_2022 completed in 0:00:10.188140

 38%|███▊      | 571/1508 [1:05:42<2:34:33,  9.90s/it]

WI_20860_2022 completed in 0:00:09.103398

 38%|███▊      | 572/1508 [1:05:53<2:38:51, 10.18s/it]

WV_733_2022 completed in 0:00:10.848219

 38%|███▊      | 573/1508 [1:06:03<2:35:51, 10.00s/it]

WV_12796_2022 completed in 0:00:09.578695

 38%|███▊      | 574/1508 [1:06:13<2:34:19,  9.91s/it]

WV_15263_2022 completed in 0:00:09.706993

 38%|███▊      | 575/1508 [1:06:23<2:34:46,  9.95s/it]

WV_20521_2022 completed in 0:00:10.046069

 38%|███▊      | 576/1508 [1:06:32<2:32:56,  9.85s/it]

WY_3461_2022 completed in 0:00:09.595489

 38%|███▊      | 577/1508 [1:06:43<2:35:22, 10.01s/it]

WY_7222_2022 completed in 0:00:10.401930

 38%|███▊      | 578/1508 [1:06:56<2:50:41, 11.01s/it]

WY_8566_2022 completed in 0:00:13.341867

 38%|███▊      | 579/1508 [1:07:06<2:45:16, 10.67s/it]

WY_11273_2022 completed in 0:00:09.883632

 38%|███▊      | 580/1508 [1:07:15<2:37:06, 10.16s/it]

WY_12199_2022 completed in 0:00:08.952437

 39%|███▊      | 581/1508 [1:07:27<2:46:25, 10.77s/it]

WY_14354_2022 completed in 0:00:12.200570

 39%|███▊      | 582/1508 [1:07:38<2:45:22, 10.72s/it]

WY_19156_2022 completed in 0:00:10.579986

 39%|███▊      | 583/1508 [1:07:46<2:36:28, 10.15s/it]

WY_27058_2022 completed in 0:00:08.822307
Skipping utility OK_817_2022 due to empty or invalid geometry.
Skipping utility CO_10066_2022 due to empty or invalid geometry.
Skipping utility AR_12681_2022 due to empty or invalid geometry.
Skipping utility CA_16612_2022 due to empty or invalid geometry.
Skipping utility MA_20310_2022 due to empty or invalid geometry.
Skipping utility NE_8245_2022 due to empty or invalid geometry.

 39%|███▉      | 590/1508 [1:08:00<1:01:16,  4.00s/it]

AK_219_2023 completed in 0:00:13.686797

 39%|███▉      | 591/1508 [1:08:10<1:12:37,  4.75s/it]

AK_3522_2023 completed in 0:00:09.637415

 39%|███▉      | 592/1508 [1:08:23<1:32:46,  6.08s/it]

AK_7353_2023 completed in 0:00:13.063623

 39%|███▉      | 593/1508 [1:08:32<1:42:14,  6.70s/it]

AK_11824_2023 completed in 0:00:09.455797

 39%|███▉      | 594/1508 [1:08:41<1:47:12,  7.04s/it]

AK_19558_2023 completed in 0:00:08.296224
Skipping utility AL_3222_2023 due to empty or invalid geometry.
Skipping utility AL_4327_2023 due to empty or invalid geometry.
Skipping utility AL_4430_2023 due to empty or invalid geometry.
Skipping utility AL_6491_2023 due to empty or invalid geometry.
Skipping utility AL_17646_2023 due to empty or invalid geometry.

 40%|███▉      | 600/1508 [1:08:50<52:51,  3.49s/it]

AR_814_2023 completed in 0:00:09.098076

 40%|███▉      | 601/1508 [1:08:57<1:01:18,  4.06s/it]

AR_817_2023 completed in 0:00:07.735445
Skipping utility AR_1586_2023 due to empty or invalid geometry.
Skipping utility AR_2678_2023 due to empty or invalid geometry.

 40%|████      | 604/1508 [1:09:05<53:05,  3.52s/it]

AR_3093_2023 completed in 0:00:07.761905
Skipping utility AR_3712_2023 due to empty or invalid geometry.
Skipping utility AR_4280_2023 due to empty or invalid geometry.
Skipping utility AR_4509_2023 due to empty or invalid geometry.

 40%|████      | 608/1508 [1:09:15<45:45,  3.05s/it]

AR_5860_2023 completed in 0:00:09.458306

 40%|████      | 609/1508 [1:09:24<58:23,  3.90s/it]

AR_6342_2023 completed in 0:00:09.699386
Skipping utility AR_8840_2023 due to empty or invalid geometry.
Skipping utility AR_9879_2023 due to empty or invalid geometry.
Skipping utility AR_12681_2023 due to empty or invalid geometry.
Skipping utility AR_13676_2023 due to empty or invalid geometry.

 41%|████      | 614/1508 [1:09:33<42:31,  2.85s/it]

AR_13718_2023 completed in 0:00:08.527270

 41%|████      | 615/1508 [1:09:41<51:38,  3.47s/it]

AR_14063_2023 completed in 0:00:07.987289
Skipping utility AR_14289_2023 due to empty or invalid geometry.
Skipping utility AR_14446_2023 due to empty or invalid geometry.
Skipping utility AR_14864_2023 due to empty or invalid geometry.
Skipping utility AR_17184_2023 due to empty or invalid geometry.
Skipping utility AR_17671_2023 due to empty or invalid geometry.

 41%|████      | 621/1508 [1:09:51<37:23,  2.53s/it]

AR_17698_2023 completed in 0:00:09.674633
Skipping utility AR_20963_2023 due to empty or invalid geometry.

 41%|████▏     | 623/1508 [1:09:58<41:01,  2.78s/it]

AZ_176_2023 completed in 0:00:07.645504

 41%|████▏     | 624/1508 [1:10:09<55:34,  3.77s/it]

AZ_803_2023 completed in 0:00:10.911109
Skipping utility AZ_6957_2023 due to empty or invalid geometry.
Skipping utility AZ_12351_2023 due to empty or invalid geometry.

 42%|████▏     | 627/1508 [1:10:17<49:17,  3.36s/it]

AZ_12919_2023 completed in 0:00:07.683630
Skipping utility AZ_13318_2023 due to empty or invalid geometry.

 42%|████▏     | 629/1508 [1:10:25<51:05,  3.49s/it]

AZ_16572_2023 completed in 0:00:07.769663
Skipping utility AZ_18280_2023 due to empty or invalid geometry.

 42%|████▏     | 631/1508 [1:10:32<52:32,  3.59s/it]

AZ_19189_2023 completed in 0:00:07.796207

 42%|████▏     | 632/1508 [1:10:40<1:02:45,  4.30s/it]

AZ_19728_2023 completed in 0:00:08.082294

 42%|████▏     | 633/1508 [1:10:47<1:08:18,  4.68s/it]

AZ_21538_2023 completed in 0:00:06.406667

 42%|████▏     | 634/1508 [1:10:54<1:16:54,  5.28s/it]

AZ_24211_2023 completed in 0:00:07.554692
Skipping utility AZ_30518_2023 due to empty or invalid geometry.
Skipping utility AZ_40165_2023 due to empty or invalid geometry.
Skipping utility CA_207_2023 due to empty or invalid geometry.
Skipping utility CA_590_2023 due to empty or invalid geometry.
Skipping utility CA_1050_2023 due to empty or invalid geometry.
Skipping utility CA_2507_2023 due to empty or invalid geometry.
Skipping utility CA_4003_2023 due to empty or invalid geometry.

 43%|████▎     | 642/1508 [1:11:00<30:19,  2.10s/it]

CA_4390_2023 completed in 0:00:06.056078
Skipping utility CA_7294_2023 due to empty or invalid geometry.

 43%|████▎     | 644/1508 [1:11:08<35:13,  2.45s/it]

CA_9216_2023 completed in 0:00:07.628484
Skipping utility CA_11124_2023 due to empty or invalid geometry.

 43%|████▎     | 646/1508 [1:11:17<41:19,  2.88s/it]

CA_11208_2023 completed in 0:00:08.755963
Skipping utility CA_12312_2023 due to empty or invalid geometry.

 43%|████▎     | 648/1508 [1:11:24<43:21,  3.02s/it]

CA_12745_2023 completed in 0:00:06.974681

 43%|████▎     | 649/1508 [1:11:42<1:14:29,  5.20s/it]

CA_14328_2023 completed in 0:00:17.829643

 43%|████▎     | 650/1508 [1:11:49<1:18:51,  5.51s/it]

CA_14354_2023 completed in 0:00:06.999185
Skipping utility CA_14401_2023 due to empty or invalid geometry.

 43%|████▎     | 652/1508 [1:11:55<1:07:25,  4.73s/it]

CA_14534_2023 completed in 0:00:06.271063
Skipping utility CA_15783_2023 due to empty or invalid geometry.
Skipping utility CA_16088_2023 due to empty or invalid geometry.
Skipping utility CA_16295_2023 due to empty or invalid geometry.

 44%|████▎     | 656/1508 [1:12:03<48:26,  3.41s/it]

CA_16534_2023 completed in 0:00:08.089046

 44%|████▎     | 657/1508 [1:12:11<57:44,  4.07s/it]

CA_16609_2023 completed in 0:00:07.868318
Skipping utility CA_16612_2023 due to empty or invalid geometry.

 44%|████▎     | 659/1508 [1:12:18<54:46,  3.87s/it]

CA_16655_2023 completed in 0:00:06.789003

 44%|████▍     | 660/1508 [1:12:30<1:15:07,  5.32s/it]

CA_17609_2023 completed in 0:00:12.121462

 44%|████▍     | 661/1508 [1:12:37<1:19:13,  5.61s/it]

CA_17612_2023 completed in 0:00:06.796759
Skipping utility CA_17896_2023 due to empty or invalid geometry.

 44%|████▍     | 663/1508 [1:12:43<1:07:09,  4.77s/it]

CA_18260_2023 completed in 0:00:06.582840

 44%|████▍     | 664/1508 [1:12:50<1:12:59,  5.19s/it]

CA_19281_2023 completed in 0:00:06.807980
Skipping utility CA_19798_2023 due to empty or invalid geometry.
Skipping utility CA_55787_2023 due to empty or invalid geometry.
Skipping utility CA_57483_2023 due to empty or invalid geometry.

 44%|████▍     | 668/1508 [1:12:58<48:08,  3.44s/it]

CO_3989_2023 completed in 0:00:07.811382
Skipping utility CO_5086_2023 due to empty or invalid geometry.
Skipping utility CO_5862_2023 due to empty or invalid geometry.

 44%|████▍     | 671/1508 [1:13:05<42:19,  3.03s/it]

CO_6604_2023 completed in 0:00:06.993421
Skipping utility CO_6638_2023 due to empty or invalid geometry.
Skipping utility CO_7563_2023 due to empty or invalid geometry.
Skipping utility CO_8570_2023 due to empty or invalid geometry.
Skipping utility CO_8773_2023 due to empty or invalid geometry.

 45%|████▍     | 676/1508 [1:13:12<31:51,  2.30s/it]

CO_9336_2023 completed in 0:00:07.263304
Skipping utility CO_10066_2023 due to empty or invalid geometry.
Skipping utility CO_10539_2023 due to empty or invalid geometry.
Skipping utility CO_11187_2023 due to empty or invalid geometry.
Skipping utility CO_11256_2023 due to empty or invalid geometry.
Skipping utility CO_12860_2023 due to empty or invalid geometry.

 45%|████▌     | 682/1508 [1:13:19<24:53,  1.81s/it]

CO_12866_2023 completed in 0:00:07.172772
Skipping utility CO_13050_2023 due to empty or invalid geometry.
Skipping utility CO_13058_2023 due to empty or invalid geometry.

 45%|████▌     | 685/1508 [1:13:26<26:31,  1.93s/it]

CO_15257_2023 completed in 0:00:06.978076

 45%|████▌     | 686/1508 [1:13:36<37:04,  2.71s/it]

CO_15466_2023 completed in 0:00:09.442961

 46%|████▌     | 687/1508 [1:13:44<46:45,  3.42s/it]

CO_16603_2023 completed in 0:00:08.249163
Skipping utility CO_16616_2023 due to empty or invalid geometry.
Skipping utility CO_16622_2023 due to empty or invalid geometry.
Skipping utility CO_17592_2023 due to empty or invalid geometry.

 46%|████▌     | 691/1508 [1:13:53<39:09,  2.88s/it]

CO_19499_2023 completed in 0:00:08.543730
Skipping utility CO_20576_2023 due to empty or invalid geometry.
Skipping utility CO_21075_2023 due to empty or invalid geometry.
Skipping utility CO_21081_2023 due to empty or invalid geometry.

 46%|████▌     | 695/1508 [1:14:00<33:20,  2.46s/it]

CO_27058_2023 completed in 0:00:07.085723

 46%|████▌     | 696/1508 [1:14:07<40:30,  2.99s/it]

CO_56146_2023 completed in 0:00:06.949071

 46%|████▌     | 697/1508 [1:14:21<1:02:31,  4.63s/it]

CT_4176_2023 completed in 0:00:14.268661

 46%|████▋     | 698/1508 [1:14:27<1:07:11,  4.98s/it]

CT_7716_2023 completed in 0:00:06.670656
Skipping utility CT_13831_2023 due to empty or invalid geometry.

 46%|████▋     | 700/1508 [1:14:40<1:12:10,  5.36s/it]

CT_19497_2023 completed in 0:00:12.279282

 46%|████▋     | 701/1508 [1:14:51<1:26:33,  6.44s/it]

CT_20038_2023 completed in 0:00:11.019368

 47%|████▋     | 702/1508 [1:15:09<1:59:09,  8.87s/it]

DC_15270_2023 completed in 0:00:17.830561

 47%|████▋     | 703/1508 [1:15:22<2:12:40,  9.89s/it]

DE_5027_2023 completed in 0:00:13.224136

 47%|████▋     | 704/1508 [1:15:34<2:20:46, 10.51s/it]

DE_5070_2023 completed in 0:00:12.349755

 47%|████▋     | 705/1508 [1:15:46<2:24:20, 10.78s/it]

DE_5335_2023 completed in 0:00:11.564890
Skipping utility DE_12478_2023 due to empty or invalid geometry.
Skipping utility DE_12540_2023 due to empty or invalid geometry.

 47%|████▋     | 708/1508 [1:15:56<1:30:33,  6.79s/it]

DE_13519_2023 completed in 0:00:09.760183
Skipping utility FL_1300_2023 due to empty or invalid geometry.
Skipping utility FL_3245_2023 due to empty or invalid geometry.
Skipping utility FL_3502_2023 due to empty or invalid geometry.
Skipping utility FL_3757_2023 due to empty or invalid geometry.
Skipping utility FL_6443_2023 due to empty or invalid geometry.

 47%|████▋     | 714/1508 [1:16:06<49:26,  3.74s/it]

FL_6452_2023 completed in 0:00:10.310194

 47%|████▋     | 715/1508 [1:16:18<1:03:47,  4.83s/it]

FL_6455_2023 completed in 0:00:12.425730

 47%|████▋     | 716/1508 [1:16:30<1:16:57,  5.83s/it]

FL_6457_2023 completed in 0:00:11.433085
Skipping utility FL_6616_2023 due to empty or invalid geometry.
Skipping utility FL_6909_2023 due to empty or invalid geometry.
Skipping utility FL_7264_2023 due to empty or invalid geometry.
Skipping utility FL_7785_2023 due to empty or invalid geometry.
Skipping utility FL_8795_2023 due to empty or invalid geometry.
Skipping utility FL_9616_2023 due to empty or invalid geometry.

 48%|████▊     | 723/1508 [1:16:40<41:54,  3.20s/it]

FL_9617_2023 completed in 0:00:10.314754
Skipping utility FL_10226_2023 due to empty or invalid geometry.
Skipping utility FL_10376_2023 due to empty or invalid geometry.
Skipping utility FL_10620_2023 due to empty or invalid geometry.
Skipping utility FL_10623_2023 due to empty or invalid geometry.
Skipping utility FL_10857_2023 due to empty or invalid geometry.
Skipping utility FL_10868_2023 due to empty or invalid geometry.
Skipping utility FL_13485_2023 due to empty or invalid geometry.
Skipping utility FL_13955_2023 due to empty or invalid geometry.
Skipping utility FL_14606_2023 due to empty or invalid geometry.
Skipping utility FL_14610_2023 due to empty or invalid geometry.
Skipping utility FL_15776_2023 due to empty or invalid geometry.
Skipping utility FL_18304_2023 due to empty or invalid geometry.
Skipping utility FL_18360_2023 due to empty or invalid geometry.
Skipping utility FL_18445_2023 due to empty or invalid geometry.
Skipping utility FL_18449_2023 due to empty or invalid geometry.

 49%|████▉     | 739/1508 [1:16:51<19:43,  1.54s/it]

FL_18454_2023 completed in 0:00:11.086652
Skipping utility FL_19161_2023 due to empty or invalid geometry.
Skipping utility FL_20371_2023 due to empty or invalid geometry.
Skipping utility FL_20885_2023 due to empty or invalid geometry.
Skipping utility FL_31833_2023 due to empty or invalid geometry.
Skipping utility GA_230_2023 due to empty or invalid geometry.
Skipping utility GA_407_2023 due to empty or invalid geometry.
Skipping utility GA_562_2023 due to empty or invalid geometry.
Skipping utility GA_2487_2023 due to empty or invalid geometry.
Skipping utility GA_2812_2023 due to empty or invalid geometry.
Skipping utility GA_2903_2023 due to empty or invalid geometry.
Skipping utility GA_3081_2023 due to empty or invalid geometry.
Skipping utility GA_3108_2023 due to empty or invalid geometry.
Skipping utility GA_3248_2023 due to empty or invalid geometry.
Skipping utility GA_3843_2023 due to empty or invalid geometry.

 50%|█████     | 754/1508 [1:17:01<14:00,  1.11s/it]

GA_3916_2023 completed in 0:00:09.515523
Skipping utility GA_4432_2023 due to empty or invalid geometry.
Skipping utility GA_4433_2023 due to empty or invalid geometry.
Skipping utility GA_4538_2023 due to empty or invalid geometry.
Skipping utility GA_5905_2023 due to empty or invalid geometry.
Skipping utility GA_6411_2023 due to empty or invalid geometry.
Skipping utility GA_7090_2023 due to empty or invalid geometry.

 50%|█████     | 761/1508 [1:17:13<15:59,  1.28s/it]

GA_7140_2023 completed in 0:00:12.791036
Skipping utility GA_7450_2023 due to empty or invalid geometry.
Skipping utility GA_7887_2023 due to empty or invalid geometry.
Skipping utility GA_8210_2023 due to empty or invalid geometry.
Skipping utility GA_9431_2023 due to empty or invalid geometry.

 51%|█████     | 766/1508 [1:17:24<18:06,  1.46s/it]

GA_9601_2023 completed in 0:00:10.985651
Skipping utility GA_9689_2023 due to empty or invalid geometry.
Skipping utility GA_10624_2023 due to empty or invalid geometry.
Skipping utility GA_10800_2023 due to empty or invalid geometry.
Skipping utility GA_11646_2023 due to empty or invalid geometry.
Skipping utility GA_12706_2023 due to empty or invalid geometry.
Skipping utility GA_13962_2023 due to empty or invalid geometry.
Skipping utility GA_15700_2023 due to empty or invalid geometry.
Skipping utility GA_16674_2023 due to empty or invalid geometry.
Skipping utility GA_16865_2023 due to empty or invalid geometry.
Skipping utility GA_18305_2023 due to empty or invalid geometry.
Skipping utility GA_18499_2023 due to empty or invalid geometry.
Skipping utility GA_18848_2023 due to empty or invalid geometry.
Skipping utility GA_18956_2023 due to empty or invalid geometry.
Skipping utility GA_19219_2023 due to empty or invalid geometry.
Skipping utility GA_20065_2023 due to empty or invalid geometry.
Skipping utility GA_20146_2023 due to empty or invalid geometry.
Skipping utility GA_31833_2023 due to empty or invalid geometry.
Skipping utility GA_40212_2023 due to empty or invalid geometry.

 52%|█████▏    | 785/1508 [1:17:32<10:58,  1.10it/s]

HI_8287_2023 completed in 0:00:07.378502

 52%|█████▏    | 786/1508 [1:17:39<13:54,  1.16s/it]

HI_10071_2023 completed in 0:00:07.513468

 52%|█████▏    | 787/1508 [1:17:47<18:05,  1.51s/it]

HI_11843_2023 completed in 0:00:08.060097

 52%|█████▏    | 788/1508 [1:18:05<31:12,  2.60s/it]

HI_19547_2023 completed in 0:00:17.755526
Skipping utility IA_554_2023 due to empty or invalid geometry.
Skipping utility IA_2652_2023 due to empty or invalid geometry.
Skipping utility IA_3203_2023 due to empty or invalid geometry.
Skipping utility IA_5588_2023 due to empty or invalid geometry.
Skipping utility IA_5605_2023 due to empty or invalid geometry.
Skipping utility IA_8319_2023 due to empty or invalid geometry.
Skipping utility IA_9230_2023 due to empty or invalid geometry.

 53%|█████▎    | 796/1508 [1:18:17<24:53,  2.10s/it]

IA_9417_2023 completed in 0:00:11.534004
Skipping utility IA_9425_2023 due to empty or invalid geometry.
Skipping utility IA_11053_2023 due to empty or invalid geometry.
Skipping utility IA_11611_2023 due to empty or invalid geometry.
Skipping utility IA_11788_2023 due to empty or invalid geometry.

 53%|█████▎    | 801/1508 [1:18:29<26:04,  2.21s/it]

IA_12341_2023 completed in 0:00:12.544922
Skipping utility IA_12450_2023 due to empty or invalid geometry.
Skipping utility IA_13143_2023 due to empty or invalid geometry.
Skipping utility IA_15291_2023 due to empty or invalid geometry.
Skipping utility IA_15349_2023 due to empty or invalid geometry.
Skipping utility IA_17260_2023 due to empty or invalid geometry.
Skipping utility IA_19157_2023 due to empty or invalid geometry.
Skipping utility ID_6169_2023 due to empty or invalid geometry.
Skipping utility ID_8699_2023 due to empty or invalid geometry.

 54%|█████▎    | 810/1508 [1:18:38<19:24,  1.67s/it]

ID_9187_2023 completed in 0:00:08.195149

 54%|█████▍    | 811/1508 [1:18:49<26:13,  2.26s/it]

ID_9191_2023 completed in 0:00:11.117798

 54%|█████▍    | 812/1508 [1:18:57<31:48,  2.74s/it]

ID_10454_2023 completed in 0:00:08.180789

 54%|█████▍    | 813/1508 [1:19:07<40:50,  3.53s/it]

ID_11273_2023 completed in 0:00:10.240760

 54%|█████▍    | 814/1508 [1:19:16<48:34,  4.20s/it]

ID_14354_2023 completed in 0:00:08.717882
Skipping utility ID_19502_2023 due to empty or invalid geometry.

 54%|█████▍    | 816/1508 [1:19:24<48:00,  4.16s/it]

ID_20169_2023 completed in 0:00:08.120427
Skipping utility IL_3931_2023 due to empty or invalid geometry.

 54%|█████▍    | 818/1508 [1:19:46<1:10:39,  6.14s/it]

IL_4110_2023 completed in 0:00:22.530443
Skipping utility IL_4362_2023 due to empty or invalid geometry.
Skipping utility IL_5535_2023 due to empty or invalid geometry.
Skipping utility IL_5585_2023 due to empty or invalid geometry.
Skipping utility IL_7096_2023 due to empty or invalid geometry.
Skipping utility IL_9750_2023 due to empty or invalid geometry.

 55%|█████▍    | 824/1508 [1:19:55<40:31,  3.56s/it]

IL_12341_2023 completed in 0:00:08.326958
Skipping utility IL_12395_2023 due to empty or invalid geometry.

 55%|█████▍    | 826/1508 [1:20:05<43:53,  3.86s/it]

IL_13032_2023 completed in 0:00:10.070170
Skipping utility IL_13208_2023 due to empty or invalid geometry.
Skipping utility IL_13292_2023 due to empty or invalid geometry.
Skipping utility IL_14840_2023 due to empty or invalid geometry.
Skipping utility IL_16179_2023 due to empty or invalid geometry.
Skipping utility IL_16196_2023 due to empty or invalid geometry.
Skipping utility IL_16740_2023 due to empty or invalid geometry.
Skipping utility IL_17040_2023 due to empty or invalid geometry.
Skipping utility IL_17585_2023 due to empty or invalid geometry.
Skipping utility IL_17828_2023 due to empty or invalid geometry.
Skipping utility IL_17860_2023 due to empty or invalid geometry.
Skipping utility IL_18955_2023 due to empty or invalid geometry.
Skipping utility IL_20222_2023 due to empty or invalid geometry.

 56%|█████▌    | 839/1508 [1:20:20<23:24,  2.10s/it]

IL_56697_2023 completed in 0:00:15.308402
Skipping utility IN_636_2023 due to empty or invalid geometry.
Skipping utility IN_1283_2023 due to empty or invalid geometry.
Skipping utility IN_4508_2023 due to empty or invalid geometry.
Skipping utility IN_4848_2023 due to empty or invalid geometry.
Skipping utility IN_4960_2023 due to empty or invalid geometry.
Skipping utility IN_5394_2023 due to empty or invalid geometry.
Skipping utility IN_8000_2023 due to empty or invalid geometry.
Skipping utility IN_8179_2023 due to empty or invalid geometry.
Skipping utility IN_8447_2023 due to empty or invalid geometry.

 56%|█████▋    | 849/1508 [1:20:28<17:00,  1.55s/it]

IN_9273_2023 completed in 0:00:07.819668

 56%|█████▋    | 850/1508 [1:20:41<24:06,  2.20s/it]

IN_9324_2023 completed in 0:00:13.048370
Skipping utility IN_9576_2023 due to empty or invalid geometry.
Skipping utility IN_9665_2023 due to empty or invalid geometry.
Skipping utility IN_9667_2023 due to empty or invalid geometry.
Skipping utility IN_9778_2023 due to empty or invalid geometry.
Skipping utility IN_10448_2023 due to empty or invalid geometry.
Skipping utility IN_12377_2023 due to empty or invalid geometry.
Skipping utility IN_12929_2023 due to empty or invalid geometry.
Skipping utility IN_13647_2023 due to empty or invalid geometry.

 57%|█████▋    | 859/1508 [1:20:56<21:07,  1.95s/it]

IN_13756_2023 completed in 0:00:14.519507
Skipping utility IN_14839_2023 due to empty or invalid geometry.

 57%|█████▋    | 861/1508 [1:21:10<27:48,  2.58s/it]

IN_15470_2023 completed in 0:00:14.534774
Skipping utility IN_15989_2023 due to empty or invalid geometry.
Skipping utility IN_17038_2023 due to empty or invalid geometry.
Skipping utility IN_17599_2023 due to empty or invalid geometry.

 57%|█████▋    | 865/1508 [1:21:21<28:13,  2.63s/it]

IN_17633_2023 completed in 0:00:11.168944
Skipping utility IN_18940_2023 due to empty or invalid geometry.
Skipping utility IN_19445_2023 due to empty or invalid geometry.
Skipping utility IN_19667_2023 due to empty or invalid geometry.
Skipping utility IN_20216_2023 due to empty or invalid geometry.
Skipping utility IN_20603_2023 due to empty or invalid geometry.
Skipping utility IN_22822_2023 due to empty or invalid geometry.
Skipping utility IN_24753_2023 due to empty or invalid geometry.
Skipping utility IN_25295_2023 due to empty or invalid geometry.
Skipping utility IN_27599_2023 due to empty or invalid geometry.

 58%|█████▊    | 875/1508 [1:21:33<20:32,  1.95s/it]

KS_5860_2023 completed in 0:00:11.840577

 58%|█████▊    | 876/1508 [1:21:44<26:16,  2.49s/it]

KS_9996_2023 completed in 0:00:10.571131

 58%|█████▊    | 877/1508 [1:21:52<31:26,  2.99s/it]

KS_10000_2023 completed in 0:00:08.463519

 58%|█████▊    | 878/1508 [1:22:03<40:19,  3.84s/it]

KS_10005_2023 completed in 0:00:11.011061
Skipping utility KS_10019_2023 due to empty or invalid geometry.
Skipping utility KS_12208_2023 due to empty or invalid geometry.
Skipping utility KS_13799_2023 due to empty or invalid geometry.
Skipping utility KS_15073_2023 due to empty or invalid geometry.
Skipping utility KS_19160_2023 due to empty or invalid geometry.
Skipping utility KS_19820_2023 due to empty or invalid geometry.
Skipping utility KS_20476_2023 due to empty or invalid geometry.
Skipping utility KS_20510_2023 due to empty or invalid geometry.

 59%|█████▉    | 887/1508 [1:22:17<26:09,  2.53s/it]

KS_22500_2023 completed in 0:00:14.053760
Skipping utility KY_690_2023 due to empty or invalid geometry.
Skipping utility KY_1708_2023 due to empty or invalid geometry.
Skipping utility KY_1886_2023 due to empty or invalid geometry.
Skipping utility KY_3687_2023 due to empty or invalid geometry.
Skipping utility KY_4622_2023 due to empty or invalid geometry.
Skipping utility KY_6194_2023 due to empty or invalid geometry.
Skipping utility KY_6442_2023 due to empty or invalid geometry.
Skipping utility KY_6708_2023 due to empty or invalid geometry.
Skipping utility KY_7558_2023 due to empty or invalid geometry.
Skipping utility KY_8449_2023 due to empty or invalid geometry.
Skipping utility KY_9292_2023 due to empty or invalid geometry.
Skipping utility KY_9575_2023 due to empty or invalid geometry.
Skipping utility KY_9605_2023 due to empty or invalid geometry.

 60%|█████▉    | 901/1508 [1:22:26<14:42,  1.45s/it]

KY_9964_2023 completed in 0:00:08.599988

 60%|█████▉    | 902/1508 [1:22:39<21:07,  2.09s/it]

KY_10171_2023 completed in 0:00:13.225756

 60%|█████▉    | 903/1508 [1:22:51<28:25,  2.82s/it]

KY_11249_2023 completed in 0:00:12.212602
Skipping utility KY_12243_2023 due to empty or invalid geometry.
Skipping utility KY_13651_2023 due to empty or invalid geometry.
Skipping utility KY_14251_2023 due to empty or invalid geometry.
Skipping utility KY_14268_2023 due to empty or invalid geometry.
Skipping utility KY_16587_2023 due to empty or invalid geometry.
Skipping utility KY_17044_2023 due to empty or invalid geometry.

 60%|██████    | 910/1508 [1:23:01<21:55,  2.20s/it]

KY_17564_2023 completed in 0:00:09.346031
Skipping utility KY_18498_2023 due to empty or invalid geometry.

 60%|██████    | 912/1508 [1:23:09<24:54,  2.51s/it]

KY_19446_2023 completed in 0:00:08.634016

 61%|██████    | 913/1508 [1:23:41<52:06,  5.25s/it]

KY_22053_2023 completed in 0:00:31.619133

 61%|██████    | 914/1508 [1:23:51<57:42,  5.83s/it]

KY_49998_2023 completed in 0:00:10.101623
Skipping utility LA_298_2023 due to empty or invalid geometry.
Skipping utility LA_1458_2023 due to empty or invalid geometry.

 61%|██████    | 917/1508 [1:24:01<49:03,  4.98s/it]

LA_3265_2023 completed in 0:00:09.931819
Skipping utility LA_3641_2023 due to empty or invalid geometry.
Skipping utility LA_4153_2023 due to empty or invalid geometry.
Skipping utility LA_5202_2023 due to empty or invalid geometry.
Skipping utility LA_9096_2023 due to empty or invalid geometry.
Skipping utility LA_9682_2023 due to empty or invalid geometry.

 61%|██████    | 923/1508 [1:24:09<31:06,  3.19s/it]

LA_11241_2023 completed in 0:00:07.980986
Skipping utility LA_13228_2023 due to empty or invalid geometry.

 61%|██████▏   | 925/1508 [1:24:20<35:42,  3.67s/it]

LA_13478_2023 completed in 0:00:11.488581
Skipping utility LA_13783_2023 due to empty or invalid geometry.
Skipping utility LA_14424_2023 due to empty or invalid geometry.
Skipping utility LA_15175_2023 due to empty or invalid geometry.
Skipping utility LA_16463_2023 due to empty or invalid geometry.
Skipping utility LA_17565_2023 due to empty or invalid geometry.
Skipping utility LA_17684_2023 due to empty or invalid geometry.

 62%|██████▏   | 932/1508 [1:24:31<25:16,  2.63s/it]

LA_17698_2023 completed in 0:00:10.735908
Skipping utility LA_21567_2023 due to empty or invalid geometry.
Skipping utility MA_2144_2023 due to empty or invalid geometry.
Skipping utility MA_3477_2023 due to empty or invalid geometry.
Skipping utility MA_5480_2023 due to empty or invalid geometry.

 62%|██████▏   | 937/1508 [1:24:40<22:24,  2.35s/it]

MA_6374_2023 completed in 0:00:08.943446

 62%|██████▏   | 938/1508 [1:24:50<28:28,  3.00s/it]

MA_8774_2023 completed in 0:00:09.789113
Skipping utility MA_11085_2023 due to empty or invalid geometry.
Skipping utility MA_11586_2023 due to empty or invalid geometry.

 62%|██████▏   | 941/1508 [1:25:00<29:03,  3.08s/it]

MA_11804_2023 completed in 0:00:09.842483
Skipping utility MA_12473_2023 due to empty or invalid geometry.

 63%|██████▎   | 943/1508 [1:25:11<33:55,  3.60s/it]

MA_13206_2023 completed in 0:00:11.299688
Skipping utility MA_13679_2023 due to empty or invalid geometry.
Skipping utility MA_14605_2023 due to empty or invalid geometry.

 63%|██████▎   | 946/1508 [1:25:21<32:43,  3.49s/it]

MA_15748_2023 completed in 0:00:09.737927
Skipping utility MA_17127_2023 due to empty or invalid geometry.
Skipping utility MA_18087_2023 due to empty or invalid geometry.
Skipping utility MA_18488_2023 due to empty or invalid geometry.
Skipping utility MA_20310_2023 due to empty or invalid geometry.

 63%|██████▎   | 951/1508 [1:25:30<26:10,  2.82s/it]

MA_54913_2023 completed in 0:00:09.454942

 63%|██████▎   | 952/1508 [1:25:38<30:46,  3.32s/it]

MD_1167_2023 completed in 0:00:07.481417
Skipping utility MD_3503_2023 due to empty or invalid geometry.

 63%|██████▎   | 954/1508 [1:25:45<31:30,  3.41s/it]

MD_5027_2023 completed in 0:00:07.418411
Skipping utility MD_5625_2023 due to empty or invalid geometry.
Skipping utility MD_7908_2023 due to empty or invalid geometry.

 63%|██████▎   | 957/1508 [1:25:54<29:37,  3.23s/it]

MD_15263_2023 completed in 0:00:08.558764

 64%|██████▎   | 958/1508 [1:26:02<36:20,  3.96s/it]

MD_15270_2023 completed in 0:00:08.595585

 64%|██████▎   | 959/1508 [1:26:11<42:56,  4.69s/it]

MD_17637_2023 completed in 0:00:08.404441

 64%|██████▎   | 960/1508 [1:26:19<48:47,  5.34s/it]

ME_1179_2023 completed in 0:00:08.111139

 64%|██████▎   | 961/1508 [1:26:27<53:32,  5.87s/it]

ME_3266_2023 completed in 0:00:07.826783

 64%|██████▍   | 962/1508 [1:26:35<57:39,  6.34s/it]

ME_5609_2023 completed in 0:00:07.853719
Skipping utility MI_305_2023 due to empty or invalid geometry.

 64%|██████▍   | 964/1508 [1:26:46<55:01,  6.07s/it]

MI_392_2023 completed in 0:00:11.335876
Skipping utility MI_1196_2023 due to empty or invalid geometry.
Skipping utility MI_1366_2023 due to empty or invalid geometry.
Skipping utility MI_3436_2023 due to empty or invalid geometry.

 64%|██████▍   | 968/1508 [1:26:54<35:03,  3.89s/it]

MI_3828_2023 completed in 0:00:07.968918

 64%|██████▍   | 969/1508 [1:27:04<44:27,  4.95s/it]

MI_4254_2023 completed in 0:00:10.474584
Skipping utility MI_4604_2023 due to empty or invalid geometry.

 64%|██████▍   | 971/1508 [1:27:14<44:27,  4.97s/it]

MI_5109_2023 completed in 0:00:10.010550
Skipping utility MI_7265_2023 due to empty or invalid geometry.
Skipping utility MI_7483_2023 due to empty or invalid geometry.
Skipping utility MI_8723_2023 due to empty or invalid geometry.

 65%|██████▍   | 975/1508 [1:27:22<31:08,  3.50s/it]

MI_9324_2023 completed in 0:00:07.490234
Skipping utility MI_10508_2023 due to empty or invalid geometry.

 65%|██████▍   | 977/1508 [1:27:31<33:39,  3.80s/it]

MI_10704_2023 completed in 0:00:09.376422
Skipping utility MI_11701_2023 due to empty or invalid geometry.
Skipping utility MI_12377_2023 due to empty or invalid geometry.
Skipping utility MI_13352_2023 due to empty or invalid geometry.
Skipping utility MI_13826_2023 due to empty or invalid geometry.
Skipping utility MI_15340_2023 due to empty or invalid geometry.
Skipping utility MI_18252_2023 due to empty or invalid geometry.
Skipping utility MI_19125_2023 due to empty or invalid geometry.
Skipping utility MI_19396_2023 due to empty or invalid geometry.

 65%|██████▌   | 986/1508 [1:27:38<16:36,  1.91s/it]

MI_19578_2023 completed in 0:00:06.664168
Skipping utility MI_21048_2023 due to empty or invalid geometry.
Skipping utility MI_21158_2023 due to empty or invalid geometry.
Skipping utility MI_38084_2023 due to empty or invalid geometry.
Skipping utility MN_155_2023 due to empty or invalid geometry.
Skipping utility MN_295_2023 due to empty or invalid geometry.

 66%|██████▌   | 992/1508 [1:27:44<13:35,  1.58s/it]

MN_689_2023 completed in 0:00:06.114430
Skipping utility MN_691_2023 due to empty or invalid geometry.
Skipping utility MN_1009_2023 due to empty or invalid geometry.
Skipping utility MN_1529_2023 due to empty or invalid geometry.
Skipping utility MN_1884_2023 due to empty or invalid geometry.
Skipping utility MN_3400_2023 due to empty or invalid geometry.
Skipping utility MN_4577_2023 due to empty or invalid geometry.

 66%|██████▌   | 999/1508 [1:27:52<12:07,  1.43s/it]

MN_5574_2023 completed in 0:00:08.300976
Skipping utility MN_5773_2023 due to empty or invalid geometry.
Skipping utility MN_6258_2023 due to empty or invalid geometry.
Skipping utility MN_6782_2023 due to empty or invalid geometry.
Skipping utility MN_8319_2023 due to empty or invalid geometry.
Skipping utility MN_9475_2023 due to empty or invalid geometry.

 67%|██████▋   | 1005/1508 [1:28:00<11:41,  1.40s/it]

MN_10596_2023 completed in 0:00:07.916899
Skipping utility MN_10618_2023 due to empty or invalid geometry.
Skipping utility MN_10697_2023 due to empty or invalid geometry.
Skipping utility MN_11731_2023 due to empty or invalid geometry.
Skipping utility MN_12227_2023 due to empty or invalid geometry.
Skipping utility MN_12546_2023 due to empty or invalid geometry.

 67%|██████▋   | 1011/1508 [1:28:10<12:05,  1.46s/it]

MN_12647_2023 completed in 0:00:09.591636
Skipping utility MN_12651_2023 due to empty or invalid geometry.
Skipping utility MN_12894_2023 due to empty or invalid geometry.

 67%|██████▋   | 1014/1508 [1:28:18<14:00,  1.70s/it]

MN_13781_2023 completed in 0:00:08.353299

 67%|██████▋   | 1015/1508 [1:28:28<19:34,  2.38s/it]

MN_14232_2023 completed in 0:00:10.202943
Skipping utility MN_14246_2023 due to empty or invalid geometry.
Skipping utility MN_14468_2023 due to empty or invalid geometry.

 68%|██████▊   | 1018/1508 [1:28:36<19:26,  2.38s/it]

MN_16181_2023 completed in 0:00:07.123173
Skipping utility MN_16368_2023 due to empty or invalid geometry.
Skipping utility MN_16971_2023 due to empty or invalid geometry.

 68%|██████▊   | 1021/1508 [1:28:44<20:12,  2.49s/it]

MN_17267_2023 completed in 0:00:08.357757
Skipping utility MN_17550_2023 due to empty or invalid geometry.
Skipping utility MN_18019_2023 due to empty or invalid geometry.
Skipping utility MN_18047_2023 due to empty or invalid geometry.
Skipping utility MN_19157_2023 due to empty or invalid geometry.
Skipping utility MN_20639_2023 due to empty or invalid geometry.
Skipping utility MN_20737_2023 due to empty or invalid geometry.

 68%|██████▊   | 1028/1508 [1:28:53<15:09,  1.90s/it]

MN_20996_2023 completed in 0:00:08.589515
Skipping utility MN_21013_2023 due to empty or invalid geometry.

 68%|██████▊   | 1030/1508 [1:29:01<18:09,  2.28s/it]

MN_25177_2023 completed in 0:00:08.541813
Skipping utility MN_40304_2023 due to empty or invalid geometry.
Skipping utility MO_1775_2023 due to empty or invalid geometry.
Skipping utility MO_2001_2023 due to empty or invalid geometry.
Skipping utility MO_3113_2023 due to empty or invalid geometry.
Skipping utility MO_3268_2023 due to empty or invalid geometry.
Skipping utility MO_3600_2023 due to empty or invalid geometry.
Skipping utility MO_4045_2023 due to empty or invalid geometry.
Skipping utility MO_4063_2023 due to empty or invalid geometry.
Skipping utility MO_4160_2023 due to empty or invalid geometry.
Skipping utility MO_4237_2023 due to empty or invalid geometry.
Skipping utility MO_4524_2023 due to empty or invalid geometry.

 69%|██████▉   | 1042/1508 [1:29:10<10:45,  1.39s/it]

MO_4675_2023 completed in 0:00:08.869241

 69%|██████▉   | 1043/1508 [1:29:20<14:48,  1.91s/it]

MO_5860_2023 completed in 0:00:09.507196
Skipping utility MO_6181_2023 due to empty or invalid geometry.
Skipping utility MO_6205_2023 due to empty or invalid geometry.
Skipping utility MO_7024_2023 due to empty or invalid geometry.
Skipping utility MO_8055_2023 due to empty or invalid geometry.
Skipping utility MO_8934_2023 due to empty or invalid geometry.

 70%|██████▉   | 1049/1508 [1:29:28<13:26,  1.76s/it]

MO_9231_2023 completed in 0:00:08.856450
Skipping utility MO_9331_2023 due to empty or invalid geometry.

 70%|██████▉   | 1051/1508 [1:29:37<16:27,  2.16s/it]

MO_10000_2023 completed in 0:00:09.072263
Skipping utility MO_10370_2023 due to empty or invalid geometry.
Skipping utility MO_10603_2023 due to empty or invalid geometry.
Skipping utility MO_10832_2023 due to empty or invalid geometry.
Skipping utility MO_11463_2023 due to empty or invalid geometry.

 70%|███████   | 1056/1508 [1:29:46<15:08,  2.01s/it]

MO_12698_2023 completed in 0:00:08.608658
Skipping utility MO_12700_2023 due to empty or invalid geometry.
Skipping utility MO_12782_2023 due to empty or invalid geometry.
Skipping utility MO_13520_2023 due to empty or invalid geometry.
Skipping utility MO_14192_2023 due to empty or invalid geometry.
Skipping utility MO_14285_2023 due to empty or invalid geometry.
Skipping utility MO_14288_2023 due to empty or invalid geometry.
Skipping utility MO_15138_2023 due to empty or invalid geometry.
Skipping utility MO_15229_2023 due to empty or invalid geometry.
Skipping utility MO_16259_2023 due to empty or invalid geometry.
Skipping utility MO_16751_2023 due to empty or invalid geometry.
Skipping utility MO_16805_2023 due to empty or invalid geometry.
Skipping utility MO_17177_2023 due to empty or invalid geometry.

 71%|███████   | 1069/1508 [1:29:54<09:03,  1.24s/it]

MO_17833_2023 completed in 0:00:08.124853

 71%|███████   | 1070/1508 [1:30:06<13:20,  1.83s/it]

MO_19436_2023 completed in 0:00:11.429471
Skipping utility MO_20318_2023 due to empty or invalid geometry.
Skipping utility MO_20363_2023 due to empty or invalid geometry.
Skipping utility MO_20574_2023 due to empty or invalid geometry.
Skipping utility MO_27238_2023 due to empty or invalid geometry.

 71%|███████▏  | 1075/1508 [1:30:14<12:50,  1.78s/it]

MS_3841_2023 completed in 0:00:08.299846
Skipping utility MS_5175_2023 due to empty or invalid geometry.
Skipping utility MS_11519_2023 due to empty or invalid geometry.

 71%|███████▏  | 1078/1508 [1:30:25<15:20,  2.14s/it]

MS_12685_2023 completed in 0:00:10.750419

 72%|███████▏  | 1079/1508 [1:30:34<19:32,  2.73s/it]

MS_12686_2023 completed in 0:00:08.941053
Skipping utility MS_14563_2023 due to empty or invalid geometry.

 72%|███████▏  | 1081/1508 [1:30:43<22:21,  3.14s/it]

MS_17647_2023 completed in 0:00:09.566426
Skipping utility MS_22815_2023 due to empty or invalid geometry.
Skipping utility MT_6169_2023 due to empty or invalid geometry.

 72%|███████▏  | 1084/1508 [1:30:54<22:55,  3.24s/it]

MT_6395_2023 completed in 0:00:10.433907
Skipping utility MT_11272_2023 due to empty or invalid geometry.

 72%|███████▏  | 1086/1508 [1:31:04<25:27,  3.62s/it]

MT_12199_2023 completed in 0:00:09.881109

 72%|███████▏  | 1087/1508 [1:31:12<30:26,  4.34s/it]

MT_12692_2023 completed in 0:00:08.864407

 72%|███████▏  | 1088/1508 [1:31:21<35:20,  5.05s/it]

MT_12825_2023 completed in 0:00:08.690178

 72%|███████▏  | 1089/1508 [1:31:28<38:02,  5.45s/it]

MT_19603_2023 completed in 0:00:07.156311

 72%|███████▏  | 1090/1508 [1:31:35<40:26,  5.80s/it]

MT_20997_2023 completed in 0:00:07.120787
Skipping utility MT_21513_2023 due to empty or invalid geometry.
Skipping utility NC_240_2023 due to empty or invalid geometry.
Skipping utility NC_719_2023 due to empty or invalid geometry.
Skipping utility NC_1889_2023 due to empty or invalid geometry.

 73%|███████▎  | 1095/1508 [1:31:49<27:18,  3.97s/it]

NC_3046_2023 completed in 0:00:13.769690

 73%|███████▎  | 1096/1508 [1:31:58<32:01,  4.66s/it]

NC_5416_2023 completed in 0:00:08.701077
Skipping utility NC_6640_2023 due to empty or invalid geometry.
Skipping utility NC_6784_2023 due to empty or invalid geometry.
Skipping utility NC_7639_2023 due to empty or invalid geometry.
Skipping utility NC_8333_2023 due to empty or invalid geometry.

 73%|███████▎  | 1101/1508 [1:32:06<21:04,  3.11s/it]

NC_9837_2023 completed in 0:00:08.129715
Skipping utility NC_14717_2023 due to empty or invalid geometry.
Skipping utility NC_15023_2023 due to empty or invalid geometry.
Skipping utility NC_16101_2023 due to empty or invalid geometry.

 73%|███████▎  | 1105/1508 [1:32:17<20:05,  2.99s/it]

NC_16496_2023 completed in 0:00:11.169901
Skipping utility NC_17572_2023 due to empty or invalid geometry.
Skipping utility NC_18957_2023 due to empty or invalid geometry.
Skipping utility NC_19435_2023 due to empty or invalid geometry.

 74%|███████▎  | 1109/1508 [1:32:26<18:14,  2.74s/it]

NC_19876_2023 completed in 0:00:09.075431
Skipping utility NC_19981_2023 due to empty or invalid geometry.
Skipping utility NC_21632_2023 due to empty or invalid geometry.

 74%|███████▎  | 1112/1508 [1:32:37<19:33,  2.96s/it]

NC_24889_2023 completed in 0:00:10.681148
Skipping utility ND_2394_2023 due to empty or invalid geometry.

 74%|███████▍  | 1114/1508 [1:32:45<20:44,  3.16s/it]

ND_12090_2023 completed in 0:00:07.817954

 74%|███████▍  | 1115/1508 [1:32:54<25:31,  3.90s/it]

ND_12301_2023 completed in 0:00:08.941779

 74%|███████▍  | 1116/1508 [1:33:03<30:26,  4.66s/it]

ND_14232_2023 completed in 0:00:08.843684

 74%|███████▍  | 1117/1508 [1:33:13<36:57,  5.67s/it]

ND_19790_2023 completed in 0:00:10.263335
Skipping utility ND_20413_2023 due to empty or invalid geometry.

 74%|███████▍  | 1119/1508 [1:33:20<32:09,  4.96s/it]

ND_24949_2023 completed in 0:00:07.157992
Skipping utility NE_2643_2023 due to empty or invalid geometry.
Skipping utility NE_3205_2023 due to empty or invalid geometry.

 74%|███████▍  | 1122/1508 [1:33:27<25:05,  3.90s/it]

NE_4373_2023 completed in 0:00:07.339623
Skipping utility NE_4671_2023 due to empty or invalid geometry.

 75%|███████▍  | 1124/1508 [1:33:34<23:43,  3.71s/it]

NE_4911_2023 completed in 0:00:06.446039
Skipping utility NE_5780_2023 due to empty or invalid geometry.

 75%|███████▍  | 1126/1508 [1:33:44<26:07,  4.10s/it]

NE_6779_2023 completed in 0:00:10.132330
Skipping utility NE_8245_2023 due to empty or invalid geometry.
Skipping utility NE_8570_2023 due to empty or invalid geometry.
Skipping utility NE_10967_2023 due to empty or invalid geometry.

 75%|███████▍  | 1130/1508 [1:34:13<35:08,  5.58s/it]

NE_11018_2023 completed in 0:00:29.411546

 75%|███████▌  | 1131/1508 [1:34:21<36:34,  5.82s/it]

NE_11251_2023 completed in 0:00:07.330739

 75%|███████▌  | 1132/1508 [1:34:30<39:54,  6.37s/it]

NE_12539_2023 completed in 0:00:09.110471

 75%|███████▌  | 1133/1508 [1:34:38<42:20,  6.78s/it]

NE_13337_2023 completed in 0:00:08.495333

 75%|███████▌  | 1134/1508 [1:34:46<43:55,  7.05s/it]

NE_13664_2023 completed in 0:00:08.031107
Skipping utility NE_13725_2023 due to empty or invalid geometry.
Skipping utility NE_13739_2023 due to empty or invalid geometry.

 75%|███████▌  | 1137/1508 [1:34:56<31:50,  5.15s/it]

NE_14127_2023 completed in 0:00:09.263107
Skipping utility NE_17577_2023 due to empty or invalid geometry.

 76%|███████▌  | 1139/1508 [1:35:12<37:42,  6.13s/it]

NE_17642_2023 completed in 0:00:16.570971
Skipping utility NE_17692_2023 due to empty or invalid geometry.
Skipping utility NE_21111_2023 due to empty or invalid geometry.

 76%|███████▌  | 1142/1508 [1:35:26<34:01,  5.58s/it]

NE_27058_2023 completed in 0:00:14.250358

 76%|███████▌  | 1143/1508 [1:35:35<36:26,  5.99s/it]

NE_40606_2023 completed in 0:00:08.143843

 76%|███████▌  | 1144/1508 [1:35:44<40:02,  6.60s/it]

NH_13441_2023 completed in 0:00:09.254186

 76%|███████▌  | 1145/1508 [1:36:03<55:38,  9.20s/it]

NH_15472_2023 completed in 0:00:18.942220

 76%|███████▌  | 1146/1508 [1:36:14<58:08,  9.64s/it]

NH_24590_2023 completed in 0:00:11.090461

 76%|███████▌  | 1147/1508 [1:36:25<1:00:14, 10.01s/it]

NJ_963_2023 completed in 0:00:11.156447

 76%|███████▌  | 1148/1508 [1:36:48<1:20:23, 13.40s/it]

NJ_9726_2023 completed in 0:00:22.947637

 76%|███████▌  | 1149/1508 [1:37:01<1:20:05, 13.39s/it]

NJ_15477_2023 completed in 0:00:13.352101

 76%|███████▋  | 1150/1508 [1:37:11<1:14:31, 12.49s/it]

NJ_16213_2023 completed in 0:00:10.186057
Skipping utility NJ_19856_2023 due to empty or invalid geometry.
Skipping utility NM_3273_2023 due to empty or invalid geometry.

 76%|███████▋  | 1153/1508 [1:37:23<46:21,  7.83s/it]

NM_3287_2023 completed in 0:00:11.860774
Skipping utility NM_4265_2023 due to empty or invalid geometry.

 77%|███████▋  | 1155/1508 [1:37:35<41:57,  7.13s/it]

NM_5701_2023 completed in 0:00:11.555875
Skipping utility NM_6198_2023 due to empty or invalid geometry.

 77%|███████▋  | 1157/1508 [1:37:46<38:18,  6.55s/it]

NM_6204_2023 completed in 0:00:10.706607

 77%|███████▋  | 1158/1508 [1:37:56<42:26,  7.27s/it]

NM_9699_2023 completed in 0:00:10.370110
Skipping utility NM_10378_2023 due to empty or invalid geometry.

 77%|███████▋  | 1160/1508 [1:38:08<39:20,  6.78s/it]

NM_11204_2023 completed in 0:00:11.745100
Skipping utility NM_13318_2023 due to empty or invalid geometry.
Skipping utility NM_14224_2023 due to empty or invalid geometry.

 77%|███████▋  | 1163/1508 [1:38:23<34:36,  6.02s/it]

NM_15473_2023 completed in 0:00:14.995787
Skipping utility NM_17715_2023 due to empty or invalid geometry.

 77%|███████▋  | 1165/1508 [1:38:38<37:00,  6.47s/it]

NM_17718_2023 completed in 0:00:15.172796
Skipping utility NM_17826_2023 due to empty or invalid geometry.

 77%|███████▋  | 1167/1508 [1:38:49<35:28,  6.24s/it]

NV_2008_2023 completed in 0:00:11.356405

 77%|███████▋  | 1168/1508 [1:39:01<41:02,  7.24s/it]

NV_13073_2023 completed in 0:00:12.026186

 78%|███████▊  | 1169/1508 [1:39:18<51:30,  9.12s/it]

NV_13407_2023 completed in 0:00:16.686668
Skipping utility NV_14245_2023 due to empty or invalid geometry.

 78%|███████▊  | 1171/1508 [1:39:32<47:16,  8.42s/it]

NV_17166_2023 completed in 0:00:14.368564

 78%|███████▊  | 1172/1508 [1:39:45<52:16,  9.33s/it]

NV_19840_2023 completed in 0:00:12.883388

 78%|███████▊  | 1173/1508 [1:39:57<54:36,  9.78s/it]

NY_3249_2023 completed in 0:00:11.298184

 78%|███████▊  | 1174/1508 [1:40:12<1:02:18, 11.19s/it]

NY_4226_2023 completed in 0:00:15.555405

 78%|███████▊  | 1175/1508 [1:40:22<1:00:41, 10.94s/it]

NY_11171_2023 completed in 0:00:10.200253
Skipping utility NY_11811_2023 due to empty or invalid geometry.

 78%|███████▊  | 1177/1508 [1:40:38<52:48,  9.57s/it]

NY_13511_2023 completed in 0:00:15.454352

 78%|███████▊  | 1178/1508 [1:40:53<59:24, 10.80s/it]

NY_13573_2023 completed in 0:00:14.839675

 78%|███████▊  | 1179/1508 [1:41:03<58:38, 10.69s/it]

NY_14154_2023 completed in 0:00:10.369991

 78%|███████▊  | 1180/1508 [1:41:12<56:25, 10.32s/it]

NY_14711_2023 completed in 0:00:09.282004

 78%|███████▊  | 1181/1508 [1:41:23<56:41, 10.40s/it]

NY_16183_2023 completed in 0:00:10.612653
Skipping utility OH_2651_2023 due to empty or invalid geometry.

 78%|███████▊  | 1183/1508 [1:41:31<41:24,  7.64s/it]

OH_3542_2023 completed in 0:00:08.213560

 79%|███████▊  | 1184/1508 [1:41:39<41:39,  7.71s/it]

OH_3755_2023 completed in 0:00:07.937083
Skipping utility OH_3762_2023 due to empty or invalid geometry.
Skipping utility OH_4683_2023 due to empty or invalid geometry.

 79%|███████▊  | 1187/1508 [1:41:51<31:00,  5.80s/it]

OH_4922_2023 completed in 0:00:11.745367
Skipping utility OH_7891_2023 due to empty or invalid geometry.
Skipping utility OH_8761_2023 due to empty or invalid geometry.
Skipping utility OH_10830_2023 due to empty or invalid geometry.
Skipping utility OH_12377_2023 due to empty or invalid geometry.
Skipping utility OH_12990_2023 due to empty or invalid geometry.

 79%|███████▉  | 1193/1508 [1:42:03<18:41,  3.56s/it]

OH_13998_2023 completed in 0:00:12.080234

 79%|███████▉  | 1194/1508 [1:42:17<25:37,  4.90s/it]

OH_14006_2023 completed in 0:00:14.379902

 79%|███████▉  | 1195/1508 [1:42:29<30:43,  5.89s/it]

OH_18997_2023 completed in 0:00:11.530448
Skipping utility OH_19951_2023 due to empty or invalid geometry.
Skipping utility OH_20477_2023 due to empty or invalid geometry.
Skipping utility OK_296_2023 due to empty or invalid geometry.
Skipping utility OK_817_2023 due to empty or invalid geometry.
Skipping utility OK_3226_2023 due to empty or invalid geometry.
Skipping utility OK_3478_2023 due to empty or invalid geometry.
Skipping utility OK_3527_2023 due to empty or invalid geometry.
Skipping utility OK_3647_2023 due to empty or invalid geometry.
Skipping utility OK_4296_2023 due to empty or invalid geometry.
Skipping utility OK_4401_2023 due to empty or invalid geometry.
Skipping utility OK_5598_2023 due to empty or invalid geometry.
Skipping utility OK_5661_2023 due to empty or invalid geometry.

 80%|████████  | 1208/1508 [1:42:37<10:01,  2.00s/it]

OK_5860_2023 completed in 0:00:07.869773
Skipping utility OK_9246_2023 due to empty or invalid geometry.
Skipping utility OK_10170_2023 due to empty or invalid geometry.
Skipping utility OK_10599_2023 due to empty or invalid geometry.

 80%|████████  | 1212/1508 [1:42:47<10:43,  2.17s/it]

OK_13734_2023 completed in 0:00:10.774295

 80%|████████  | 1213/1508 [1:42:54<12:24,  2.52s/it]

OK_14062_2023 completed in 0:00:06.558684

 81%|████████  | 1214/1508 [1:43:02<15:01,  3.07s/it]

OK_14063_2023 completed in 0:00:07.787730
Skipping utility OK_14289_2023 due to empty or invalid geometry.
Skipping utility OK_14775_2023 due to empty or invalid geometry.

 81%|████████  | 1217/1508 [1:43:12<15:24,  3.18s/it]

OK_15474_2023 completed in 0:00:10.276481
Skipping utility OK_16382_2023 due to empty or invalid geometry.
Skipping utility OK_17671_2023 due to empty or invalid geometry.
Skipping utility OK_18125_2023 due to empty or invalid geometry.
Skipping utility OK_19160_2023 due to empty or invalid geometry.

 81%|████████  | 1222/1508 [1:43:19<11:21,  2.38s/it]

OK_19785_2023 completed in 0:00:06.473785
Skipping utility OR_3240_2023 due to empty or invalid geometry.
Skipping utility OR_3264_2023 due to empty or invalid geometry.
Skipping utility OR_4317_2023 due to empty or invalid geometry.
Skipping utility OR_4743_2023 due to empty or invalid geometry.

 81%|████████▏ | 1227/1508 [1:43:25<09:13,  1.97s/it]

OR_6022_2023 completed in 0:00:06.385211
Skipping utility OR_6582_2023 due to empty or invalid geometry.

 81%|████████▏ | 1229/1508 [1:43:32<10:22,  2.23s/it]

OR_9191_2023 completed in 0:00:06.898574
Skipping utility OR_10681_2023 due to empty or invalid geometry.
Skipping utility OR_12187_2023 due to empty or invalid geometry.
Skipping utility OR_12439_2023 due to empty or invalid geometry.
Skipping utility OR_13788_2023 due to empty or invalid geometry.
Skipping utility OR_14109_2023 due to empty or invalid geometry.

 82%|████████▏ | 1235/1508 [1:43:39<08:09,  1.79s/it]

OR_14354_2023 completed in 0:00:07.271134

 82%|████████▏ | 1236/1508 [1:43:46<10:09,  2.24s/it]

OR_15248_2023 completed in 0:00:06.618147
Skipping utility OR_16555_2023 due to empty or invalid geometry.
Skipping utility OR_17839_2023 due to empty or invalid geometry.

 82%|████████▏ | 1239/1508 [1:43:53<10:25,  2.33s/it]

OR_18260_2023 completed in 0:00:07.604383
Skipping utility OR_18917_2023 due to empty or invalid geometry.
Skipping utility OR_19325_2023 due to empty or invalid geometry.

 82%|████████▏ | 1242/1508 [1:43:59<09:48,  2.21s/it]

OR_28541_2023 completed in 0:00:05.788243

 82%|████████▏ | 1243/1508 [1:44:05<11:47,  2.67s/it]

OR_40437_2023 completed in 0:00:05.988825
Skipping utility OR_40438_2023 due to empty or invalid geometry.
Skipping utility PA_3329_2023 due to empty or invalid geometry.

 83%|████████▎ | 1246/1508 [1:44:12<10:54,  2.50s/it]

PA_3597_2023 completed in 0:00:06.483858

 83%|████████▎ | 1247/1508 [1:44:20<14:15,  3.28s/it]

PA_5487_2023 completed in 0:00:08.086717

 83%|████████▎ | 1248/1508 [1:44:27<17:13,  3.98s/it]

PA_12390_2023 completed in 0:00:07.463621

 83%|████████▎ | 1249/1508 [1:44:42<25:49,  5.98s/it]

PA_14711_2023 completed in 0:00:14.406215

 83%|████████▎ | 1250/1508 [1:44:51<28:45,  6.69s/it]

PA_14715_2023 completed in 0:00:09.265104

 83%|████████▎ | 1251/1508 [1:45:02<32:48,  7.66s/it]

PA_14716_2023 completed in 0:00:10.806459

 83%|████████▎ | 1252/1508 [1:45:08<31:38,  7.41s/it]

PA_14940_2023 completed in 0:00:06.687105

 83%|████████▎ | 1253/1508 [1:45:15<31:10,  7.33s/it]

PA_15045_2023 completed in 0:00:07.112143

 83%|████████▎ | 1254/1508 [1:45:23<31:09,  7.36s/it]

PA_19390_2023 completed in 0:00:07.429113

 83%|████████▎ | 1255/1508 [1:45:30<30:11,  7.16s/it]

PA_20334_2023 completed in 0:00:06.647606

 83%|████████▎ | 1256/1508 [1:45:39<32:36,  7.76s/it]

PA_20387_2023 completed in 0:00:09.257149
Skipping utility PA_40167_2023 due to empty or invalid geometry.
Skipping utility PA_40220_2023 due to empty or invalid geometry.
Skipping utility PA_40221_2023 due to empty or invalid geometry.
Skipping utility PA_40222_2023 due to empty or invalid geometry.
Skipping utility PA_40224_2023 due to empty or invalid geometry.
Skipping utility PA_40289_2023 due to empty or invalid geometry.
Skipping utility PA_40290_2023 due to empty or invalid geometry.
Skipping utility PA_40292_2023 due to empty or invalid geometry.
Skipping utility PA_40293_2023 due to empty or invalid geometry.

 84%|████████▍ | 1266/1508 [1:45:48<09:01,  2.24s/it]

RI_1857_2023 completed in 0:00:08.887821

 84%|████████▍ | 1267/1508 [1:45:55<11:00,  2.74s/it]

RI_13214_2023 completed in 0:00:07.119382

 84%|████████▍ | 1268/1508 [1:46:02<13:23,  3.35s/it]

RI_14537_2023 completed in 0:00:07.459000
Skipping utility SC_162_2023 due to empty or invalid geometry.

 84%|████████▍ | 1270/1508 [1:46:08<12:51,  3.24s/it]

SC_1613_2023 completed in 0:00:05.914149
Skipping utility SC_1763_2023 due to empty or invalid geometry.
Skipping utility SC_1890_2023 due to empty or invalid geometry.
Skipping utility SC_2212_2023 due to empty or invalid geometry.

 84%|████████▍ | 1274/1508 [1:46:15<09:59,  2.56s/it]

SC_3046_2023 completed in 0:00:06.704370

 85%|████████▍ | 1275/1508 [1:46:22<12:03,  3.11s/it]

SC_5416_2023 completed in 0:00:06.605962
Skipping utility SC_5644_2023 due to empty or invalid geometry.
Skipping utility SC_6709_2023 due to empty or invalid geometry.
Skipping utility SC_6894_2023 due to empty or invalid geometry.
Skipping utility SC_7654_2023 due to empty or invalid geometry.
Skipping utility SC_8786_2023 due to empty or invalid geometry.
Skipping utility SC_10768_2023 due to empty or invalid geometry.
Skipping utility SC_11355_2023 due to empty or invalid geometry.
Skipping utility SC_12462_2023 due to empty or invalid geometry.
Skipping utility SC_13523_2023 due to empty or invalid geometry.
Skipping utility SC_13524_2023 due to empty or invalid geometry.
Skipping utility SC_14164_2023 due to empty or invalid geometry.
Skipping utility SC_14175_2023 due to empty or invalid geometry.

 85%|████████▌ | 1288/1508 [1:46:30<04:59,  1.36s/it]

SC_14398_2023 completed in 0:00:08.570096
Skipping utility SC_16195_2023 due to empty or invalid geometry.
Skipping utility SC_16606_2023 due to empty or invalid geometry.

 86%|████████▌ | 1291/1508 [1:46:37<05:29,  1.52s/it]

SC_17539_2023 completed in 0:00:06.544121

 86%|████████▌ | 1292/1508 [1:46:44<07:06,  1.97s/it]

SC_17543_2023 completed in 0:00:07.010059
Skipping utility SC_21002_2023 due to empty or invalid geometry.

 86%|████████▌ | 1294/1508 [1:46:49<07:31,  2.11s/it]

SD_1769_2023 completed in 0:00:05.338126

 86%|████████▌ | 1295/1508 [1:46:55<09:19,  2.63s/it]

SD_14232_2023 completed in 0:00:06.412008

 86%|████████▌ | 1296/1508 [1:47:01<10:49,  3.06s/it]

SD_17267_2023 completed in 0:00:05.597108

 86%|████████▌ | 1297/1508 [1:47:07<12:22,  3.52s/it]

SD_19293_2023 completed in 0:00:05.672987

 86%|████████▌ | 1298/1508 [1:47:13<14:09,  4.04s/it]

SD_19545_2023 completed in 0:00:06.171814

 86%|████████▌ | 1299/1508 [1:47:18<15:11,  4.36s/it]

SD_20401_2023 completed in 0:00:05.470702

 86%|████████▌ | 1300/1508 [1:47:23<15:41,  4.53s/it]

TN_10331_2023 completed in 0:00:05.059064
Skipping utility TX_1169_2023 due to empty or invalid geometry.
Skipping utility TX_1175_2023 due to empty or invalid geometry.
Skipping utility TX_1273_2023 due to empty or invalid geometry.
Skipping utility TX_1591_2023 due to empty or invalid geometry.
Skipping utility TX_1892_2023 due to empty or invalid geometry.
Skipping utility TX_2049_2023 due to empty or invalid geometry.
Skipping utility TX_2194_2023 due to empty or invalid geometry.
Skipping utility TX_2409_2023 due to empty or invalid geometry.
Skipping utility TX_2442_2023 due to empty or invalid geometry.
Skipping utility TX_3282_2023 due to empty or invalid geometry.
Skipping utility TX_3470_2023 due to empty or invalid geometry.
Skipping utility TX_4146_2023 due to empty or invalid geometry.
Skipping utility TX_4262_2023 due to empty or invalid geometry.
Skipping utility TX_4295_2023 due to empty or invalid geometry.
Skipping utility TX_4939_2023 due to empty or invalid geometry.
Skipping utility TX_4975_2023 due to empty or invalid geometry.
Skipping utility TX_5063_2023 due to empty or invalid geometry.
Skipping utility TX_5078_2023 due to empty or invalid geometry.

 87%|████████▋ | 1319/1508 [1:47:28<02:37,  1.20it/s]

TX_5701_2023 completed in 0:00:05.050774
Skipping utility TX_6182_2023 due to empty or invalid geometry.
Skipping utility TX_6183_2023 due to empty or invalid geometry.
Skipping utility TX_6427_2023 due to empty or invalid geometry.
Skipping utility TX_7129_2023 due to empty or invalid geometry.
Skipping utility TX_7559_2023 due to empty or invalid geometry.
Skipping utility TX_7752_2023 due to empty or invalid geometry.
Skipping utility TX_7979_2023 due to empty or invalid geometry.
Skipping utility TX_8620_2023 due to empty or invalid geometry.
Skipping utility TX_9590_2023 due to empty or invalid geometry.
Skipping utility TX_9668_2023 due to empty or invalid geometry.
Skipping utility TX_10009_2023 due to empty or invalid geometry.
Skipping utility TX_11014_2023 due to empty or invalid geometry.
Skipping utility TX_11292_2023 due to empty or invalid geometry.
Skipping utility TX_11501_2023 due to empty or invalid geometry.
Skipping utility TX_12268_2023 due to empty or invalid geometry.
Skipping utility TX_12452_2023 due to empty or invalid geometry.
Skipping utility TX_13332_2023 due to empty or invalid geometry.
Skipping utility TX_13418_2023 due to empty or invalid geometry.
Skipping utility TX_13757_2023 due to empty or invalid geometry.
Skipping utility TX_14626_2023 due to empty or invalid geometry.
Skipping utility TX_16057_2023 due to empty or invalid geometry.
Skipping utility TX_16063_2023 due to empty or invalid geometry.
Skipping utility TX_16146_2023 due to empty or invalid geometry.
Skipping utility TX_16461_2023 due to empty or invalid geometry.

 89%|████████▉ | 1344/1508 [1:47:36<01:21,  2.02it/s]

TX_16604_2023 completed in 0:00:07.170101
Skipping utility TX_16627_2023 due to empty or invalid geometry.
Skipping utility TX_16638_2023 due to empty or invalid geometry.
Skipping utility TX_17561_2023 due to empty or invalid geometry.
Skipping utility TX_17671_2023 due to empty or invalid geometry.
Skipping utility TX_18976_2023 due to empty or invalid geometry.
Skipping utility TX_19159_2023 due to empty or invalid geometry.
Skipping utility TX_19160_2023 due to empty or invalid geometry.
Skipping utility TX_19490_2023 due to empty or invalid geometry.
Skipping utility TX_19579_2023 due to empty or invalid geometry.
Skipping utility TX_19806_2023 due to empty or invalid geometry.
Skipping utility TX_20230_2023 due to empty or invalid geometry.
Skipping utility TX_20948_2023 due to empty or invalid geometry.
Skipping utility TX_28604_2023 due to empty or invalid geometry.
Skipping utility TX_28978_2023 due to empty or invalid geometry.

 90%|█████████ | 1359/1508 [1:47:43<01:11,  2.07it/s]

TX_55937_2023 completed in 0:00:06.853839
Skipping utility TX_55982_2023 due to empty or invalid geometry.

 90%|█████████ | 1361/1508 [1:47:48<01:31,  1.60it/s]

UT_2010_2023 completed in 0:00:05.518304
Skipping utility UT_5862_2023 due to empty or invalid geometry.
Skipping utility UT_6957_2023 due to empty or invalid geometry.
Skipping utility UT_10879_2023 due to empty or invalid geometry.

 91%|█████████ | 1365/1508 [1:47:54<01:45,  1.36it/s]

UT_11135_2023 completed in 0:00:05.431168

 91%|█████████ | 1366/1508 [1:47:59<02:21,  1.00it/s]

UT_12866_2023 completed in 0:00:05.921916
Skipping utility UT_13137_2023 due to empty or invalid geometry.

 91%|█████████ | 1368/1508 [1:48:08<03:22,  1.44s/it]

UT_14354_2023 completed in 0:00:09.008823

 91%|█████████ | 1369/1508 [1:48:15<04:15,  1.84s/it]

UT_15444_2023 completed in 0:00:06.131659
Skipping utility UT_17732_2023 due to empty or invalid geometry.

 91%|█████████ | 1371/1508 [1:48:23<05:07,  2.25s/it]

UT_17845_2023 completed in 0:00:07.957417

 91%|█████████ | 1372/1508 [1:48:28<05:52,  2.59s/it]

UT_17874_2023 completed in 0:00:05.067888

 91%|█████████ | 1373/1508 [1:48:34<07:08,  3.17s/it]

UT_18206_2023 completed in 0:00:06.568137
Skipping utility UT_40165_2023 due to empty or invalid geometry.

 91%|█████████ | 1375/1508 [1:48:41<07:10,  3.24s/it]

VA_84_2023 completed in 0:00:06.759601

 91%|█████████ | 1376/1508 [1:48:47<08:18,  3.78s/it]

VA_733_2023 completed in 0:00:06.329377
Skipping utility VA_3291_2023 due to empty or invalid geometry.
Skipping utility VA_4794_2023 due to empty or invalid geometry.
Skipping utility VA_8198_2023 due to empty or invalid geometry.

 92%|█████████▏| 1380/1508 [1:48:53<05:38,  2.65s/it]

VA_10171_2023 completed in 0:00:06.046148
Skipping utility VA_12260_2023 due to empty or invalid geometry.
Skipping utility VA_13640_2023 due to empty or invalid geometry.
Skipping utility VA_13762_2023 due to empty or invalid geometry.
Skipping utility VA_15410_2023 due to empty or invalid geometry.
Skipping utility VA_16558_2023 due to empty or invalid geometry.

 92%|█████████▏| 1386/1508 [1:49:02<04:03,  1.99s/it]

VA_17066_2023 completed in 0:00:08.297973

 92%|█████████▏| 1387/1508 [1:49:12<05:57,  2.96s/it]

VA_19876_2023 completed in 0:00:10.774227

 92%|█████████▏| 1388/1508 [1:49:21<07:21,  3.68s/it]

VA_19882_2023 completed in 0:00:08.265126
Skipping utility VA_21244_2023 due to empty or invalid geometry.

 92%|█████████▏| 1390/1508 [1:49:30<07:46,  3.95s/it]

VA_40228_2023 completed in 0:00:09.327851

 92%|█████████▏| 1391/1508 [1:49:38<08:54,  4.56s/it]

VT_2548_2023 completed in 0:00:07.642753

 92%|█████████▏| 1392/1508 [1:49:46<10:23,  5.37s/it]

VT_7601_2023 completed in 0:00:08.786036

 92%|█████████▏| 1393/1508 [1:49:53<10:48,  5.64s/it]

VT_19791_2023 completed in 0:00:06.586124
Skipping utility VT_20151_2023 due to empty or invalid geometry.
Skipping utility WA_1579_2023 due to empty or invalid geometry.
Skipping utility WA_1625_2023 due to empty or invalid geometry.
Skipping utility WA_1723_2023 due to empty or invalid geometry.
Skipping utility WA_3295_2023 due to empty or invalid geometry.
Skipping utility WA_3413_2023 due to empty or invalid geometry.
Skipping utility WA_3644_2023 due to empty or invalid geometry.

 93%|█████████▎| 1401/1508 [1:50:00<04:04,  2.29s/it]

WA_3660_2023 completed in 0:00:07.389828
Skipping utility WA_4041_2023 due to empty or invalid geometry.
Skipping utility WA_4442_2023 due to empty or invalid geometry.
Skipping utility WA_5326_2023 due to empty or invalid geometry.
Skipping utility WA_5832_2023 due to empty or invalid geometry.
Skipping utility WA_6149_2023 due to empty or invalid geometry.
Skipping utility WA_6716_2023 due to empty or invalid geometry.
Skipping utility WA_7548_2023 due to empty or invalid geometry.
Skipping utility WA_8699_2023 due to empty or invalid geometry.
Skipping utility WA_10393_2023 due to empty or invalid geometry.
Skipping utility WA_10627_2023 due to empty or invalid geometry.
Skipping utility WA_10944_2023 due to empty or invalid geometry.
Skipping utility WA_12744_2023 due to empty or invalid geometry.
Skipping utility WA_14055_2023 due to empty or invalid geometry.
Skipping utility WA_14170_2023 due to empty or invalid geometry.
Skipping utility WA_14324_2023 due to empty or invalid geometry.

 94%|█████████▍| 1417/1508 [1:50:08<01:37,  1.08s/it]

WA_14354_2023 completed in 0:00:07.625552
Skipping utility WA_14624_2023 due to empty or invalid geometry.
Skipping utility WA_14653_2023 due to empty or invalid geometry.
Skipping utility WA_14668_2023 due to empty or invalid geometry.
Skipping utility WA_15231_2023 due to empty or invalid geometry.
Skipping utility WA_15419_2023 due to empty or invalid geometry.

 94%|█████████▍| 1423/1508 [1:50:17<01:41,  1.19s/it]

WA_15500_2023 completed in 0:00:09.020088
Skipping utility WA_15979_2023 due to empty or invalid geometry.

 94%|█████████▍| 1425/1508 [1:50:24<02:01,  1.46s/it]

WA_16868_2023 completed in 0:00:07.235928

 95%|█████████▍| 1426/1508 [1:50:31<02:32,  1.86s/it]

WA_17470_2023 completed in 0:00:06.902616

 95%|█████████▍| 1427/1508 [1:50:39<03:17,  2.44s/it]

WA_18429_2023 completed in 0:00:07.894998
Skipping utility WA_19784_2023 due to empty or invalid geometry.

 95%|█████████▍| 1429/1508 [1:50:48<03:46,  2.86s/it]

WA_20169_2023 completed in 0:00:08.827378
Skipping utility WI_108_2023 due to empty or invalid geometry.
Skipping utility WI_307_2023 due to empty or invalid geometry.
Skipping utility WI_1251_2023 due to empty or invalid geometry.
Skipping utility WI_1776_2023 due to empty or invalid geometry.
Skipping utility WI_1997_2023 due to empty or invalid geometry.
Skipping utility WI_2273_2023 due to empty or invalid geometry.
Skipping utility WI_3208_2023 due to empty or invalid geometry.
Skipping utility WI_4073_2023 due to empty or invalid geometry.
Skipping utility WI_4607_2023 due to empty or invalid geometry.

 95%|█████████▌| 1439/1508 [1:50:55<01:46,  1.55s/it]

WI_4715_2023 completed in 0:00:06.890183
Skipping utility WI_5417_2023 due to empty or invalid geometry.
Skipping utility WI_5551_2023 due to empty or invalid geometry.

 96%|█████████▌| 1442/1508 [1:51:02<01:53,  1.73s/it]

WI_5574_2023 completed in 0:00:07.239835
Skipping utility WI_6043_2023 due to empty or invalid geometry.
Skipping utility WI_6424_2023 due to empty or invalid geometry.
Skipping utility WI_8212_2023 due to empty or invalid geometry.
Skipping utility WI_9124_2023 due to empty or invalid geometry.
Skipping utility WI_9690_2023 due to empty or invalid geometry.
Skipping utility WI_9936_2023 due to empty or invalid geometry.
Skipping utility WI_10056_2023 due to empty or invalid geometry.
Skipping utility WI_10605_2023 due to empty or invalid geometry.
Skipping utility WI_11125_2023 due to empty or invalid geometry.

 96%|█████████▋| 1452/1508 [1:51:10<01:09,  1.24s/it]

WI_11479_2023 completed in 0:00:07.470599
Skipping utility WI_11571_2023 due to empty or invalid geometry.
Skipping utility WI_11740_2023 due to empty or invalid geometry.
Skipping utility WI_12298_2023 due to empty or invalid geometry.
Skipping utility WI_13036_2023 due to empty or invalid geometry.
Skipping utility WI_13145_2023 due to empty or invalid geometry.
Skipping utility WI_13438_2023 due to empty or invalid geometry.
Skipping utility WI_13448_2023 due to empty or invalid geometry.
Skipping utility WI_13467_2023 due to empty or invalid geometry.
Skipping utility WI_13481_2023 due to empty or invalid geometry.

 97%|█████████▋| 1462/1508 [1:51:16<00:46,  1.01s/it]

WI_13697_2023 completed in 0:00:06.703746

 97%|█████████▋| 1463/1508 [1:51:25<01:04,  1.44s/it]

WI_13780_2023 completed in 0:00:08.807776

 97%|█████████▋| 1464/1508 [1:51:33<01:25,  1.93s/it]

WI_13815_2023 completed in 0:00:08.071388
Skipping utility WI_13936_2023 due to empty or invalid geometry.
Skipping utility WI_13963_2023 due to empty or invalid geometry.
Skipping utility WI_15159_2023 due to empty or invalid geometry.
Skipping utility WI_15312_2023 due to empty or invalid geometry.
Skipping utility WI_15344_2023 due to empty or invalid geometry.
Skipping utility WI_15804_2023 due to empty or invalid geometry.
Skipping utility WI_15978_2023 due to empty or invalid geometry.
Skipping utility WI_16082_2023 due to empty or invalid geometry.
Skipping utility WI_16196_2023 due to empty or invalid geometry.
Skipping utility WI_16740_2023 due to empty or invalid geometry.
Skipping utility WI_17324_2023 due to empty or invalid geometry.
Skipping utility WI_18181_2023 due to empty or invalid geometry.
Skipping utility WI_18249_2023 due to empty or invalid geometry.
Skipping utility WI_18312_2023 due to empty or invalid geometry.
Skipping utility WI_19324_2023 due to empty or invalid geometry.
Skipping utility WI_20182_2023 due to empty or invalid geometry.
Skipping utility WI_20211_2023 due to empty or invalid geometry.
Skipping utility WI_20213_2023 due to empty or invalid geometry.
Skipping utility WI_20434_2023 due to empty or invalid geometry.
Skipping utility WI_20583_2023 due to empty or invalid geometry.

 98%|█████████▊| 1485/1508 [1:51:41<00:19,  1.15it/s]

WI_20847_2023 completed in 0:00:08.060986

 99%|█████████▊| 1486/1508 [1:51:49<00:26,  1.19s/it]

WI_20856_2023 completed in 0:00:08.113143

 99%|█████████▊| 1487/1508 [1:51:59<00:35,  1.67s/it]

WI_20860_2023 completed in 0:00:09.237661
Skipping utility WI_20862_2023 due to empty or invalid geometry.

 99%|█████████▊| 1489/1508 [1:52:07<00:38,  2.04s/it]

WV_733_2023 completed in 0:00:08.340770

 99%|█████████▉| 1490/1508 [1:52:15<00:47,  2.62s/it]

WV_12796_2023 completed in 0:00:08.125966

 99%|█████████▉| 1491/1508 [1:52:23<00:55,  3.26s/it]

WV_15263_2023 completed in 0:00:07.983023

 99%|█████████▉| 1492/1508 [1:52:35<01:12,  4.52s/it]

WV_20521_2023 completed in 0:00:11.936876

 99%|█████████▉| 1493/1508 [1:52:42<01:13,  4.92s/it]

WY_3461_2023 completed in 0:00:06.813081
Skipping utility WY_6169_2023 due to empty or invalid geometry.

 99%|█████████▉| 1495/1508 [1:52:49<00:57,  4.45s/it]

WY_7222_2023 completed in 0:00:06.997898

 99%|█████████▉| 1496/1508 [1:52:57<01:02,  5.18s/it]

WY_8566_2023 completed in 0:00:08.273428

 99%|█████████▉| 1497/1508 [1:53:02<00:57,  5.18s/it]

WY_11273_2023 completed in 0:00:05.197825

 99%|█████████▉| 1498/1508 [1:53:10<00:58,  5.81s/it]

WY_12199_2023 completed in 0:00:07.850885

 99%|█████████▉| 1499/1508 [1:53:17<00:55,  6.11s/it]

WY_14354_2023 completed in 0:00:07.027522

 99%|█████████▉| 1500/1508 [1:53:24<00:51,  6.38s/it]

WY_19156_2023 completed in 0:00:07.134599

100%|█████████▉| 1501/1508 [1:53:31<00:44,  6.31s/it]

WY_27058_2023 completed in 0:00:06.109129

100%|█████████▉| 1502/1508 [1:53:40<00:43,  7.20s/it]

NH_26510_2021 completed in 0:00:09.459221

100%|█████████▉| 1503/1508 [1:53:49<00:38,  7.61s/it]

NH_26510_2022 completed in 0:00:08.647707

100%|██████████| 1508/1508 [1:53:57<00:00,  4.53s/it]

NH_26510_2023 completed in 0:00:08.148567
Skipping utility TN_3704_2012 due to empty or invalid geometry.
Skipping utility TN_3704_2013 due to empty or invalid geometry.
Skipping utility TN_3758_2012 due to empty or invalid geometry.
Skipping utility TN_3758_2013 due to empty or invalid geometry.

Download URL: https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/tables/f40b05a0d96e6057fab1acba04670ab7-511aaa63de20224b7ede2284d8f4565a:getFeatures