Collect Cloud coverage for various zip codes

In [1]:
# import library
import ee
import os
import geemap
import geopandas as gpd
import pandas as pd
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from tqdm import tqdm

In [2]:
# authenticate & initilialize earth engine
ee.Authenticate()
ee.Initialize(project='ee-jfelix-netmetering')

In [3]:
# set working directory/mount drive
from google.colab import drive
drive.mount('/content/drive')

#  Set working directory inside Google Drive
drive_path = '/content/drive/My Drive/net_metering'
os.makedirs(drive_path, exist_ok=True)
os.chdir(drive_path)

print("Current working directory:", os.getcwd())

# to keep console from disconnecting ctr+shift+i to inspector and go to the console
# function ClickConnect(){
#    console.log("Working");
#    document.querySelector("colab-toolbar-button#connect").click()
#}
#setInterval(ClickConnect,60000)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Current working directory: /content/drive/My Drive/net_metering

In [ ]:
# use dataset = ee.ImageCollection('NOAA/NCEP_DOE_RE2/total_cloud_coverage')
# band = "tcdc" (total cloud coverage in percentage: 0 to 100)
# filter dates :2011 to 2020

In [4]:
# get the boundary for all the offices
# you have to mount the google drive
# load the shapefile for all the utility boundaries (This was simplified in R)
all_sf = gpd.read_file('shapefiles/utility_boundaries_simplified_annual_v2.shp')

/usr/local/lib/python3.11/dist-packages/pyogrio/raw.py:198: RuntimeWarning: shapefiles/utility_boundaries_simplified_annual_v2.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

In [5]:
# view the boundary shapefile
all_sf.head()
all_sf.tail()

,year,full_id,full_id_y,geometry
5148,2012.0,UT_11135,UT_11135_2012,"POLYGON ((-111.99107 41.83314, -111.64558 41.7..."
5149,2013.0,UT_11135,UT_11135_2013,"POLYGON ((-111.99107 41.83314, -111.64558 41.7..."
5150,2011.0,VA_19882,VA_19882_2011,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."
5151,2012.0,VA_19882,VA_19882_2012,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."
5152,2013.0,VA_19882,VA_19882_2013,"POLYGON ((-80.61584 37.22951, -80.35152 37.349..."

In [ ]:

# This is the information for the google earth engine data that has cloud coverage
# https://developers.google.com/earth-engine/datasets/catalog/NOAA_NCEP_DOE_RE2_total_cloud_coverage

# description: NCEP-DOE Reanalysis 2 project is using a state-of-the-art analysis/forecast system to perform data assimilation using past data from 1979 through the previous year.

# citation: NCEP-DOE AMIP-II Reanalysis (R-2): M. Kanamitsu, W. Ebisuzaki, J. Woollen, S-K Yang, J.J. Hnilo, M. Fiorino, and G. L. Potter. 1631-1643, Nov 2002, Bulletin of the American Meteorological Society..

# availability: 1979 to 2025

# provider: NOAA

# Cadence: 6 hrs
# Pixel size: 278300 meters
# bands: tcdc , units: %, min: 0*, max: 100*, description: Total Cloud Cover
# ee snippet: ee.ImageCollection("NOAA/NCEP_DOE_RE2/total_cloud_coverage")

In [6]:
# bring the data from ee and select the band
tcc_collection = ee.ImageCollection('NOAA/NCEP_DOE_RE2/total_cloud_coverage').select('tcdc')

In [7]:
# List of unique utility IDs
ulist = all_sf['full_id_y'].unique().tolist()

In [8]:
# create an empty df to collect data for loop
utility_monthly_tcc = []

In [ ]:
# Loop over each utility
for u in tqdm(ulist):  # u = "AZ_24211_2011"
    start_time = datetime.now()

    u_sf = all_sf[all_sf['full_id_y'] == u]

    # Add an explicit check for None geometry before attempting to access its attributes
    if u_sf.empty or u_sf.geometry.is_empty.any() or u_sf.geometry.values[0] is None:
        print(f"Skipping utility {u} due to empty or invalid geometry.")
        continue

    # Convert geometry to EE
    geom_json = u_sf.geometry.values[0].__geo_interface__
    boundary = ee.Geometry(geom_json)

    # Extract year
    year = int(u_sf['year'].values[0])
    d1 = datetime(year, 1, 1)
    d2 = d1 + relativedelta(months=12)

    # Filter image collection
    monthly_image = tcc_collection.filterDate(d1.strftime('%Y-%m-%d'), d2.strftime('%Y-%m-%d'))

    # Function to extract average TCC for each image
    def extract_tcc(image):
        date = ee.Date(image.get('system:time_start')).format('YYYY-MM-dd HH:mm')

        med_tcc = image.reduceRegion(
            reducer=ee.Reducer.median(),
            geometry=boundary,
            scale=5000,
            maxPixels=1e13
        ).get('tcdc')

        mean_tcc = image.reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=boundary,
            scale=5000,
            maxPixels=1e13
        ).get('tcdc')
        return ee.Feature(None, {'date': date, 'avg_tcc': mean_tcc, 'median_tcc': med_tcc})

    # Map over collection and get features
    tcc_features = monthly_image.map(extract_tcc)
    tcc_table = ee.FeatureCollection(tcc_features)

    # Export to client
    try:
        tcc_dicts = geemap.ee_to_geojson(tcc_table)
        tcc_df = pd.DataFrame(tcc_dicts['features'])
        tcc_df['date'] = pd.to_datetime(tcc_df['properties'].apply(lambda x: x['date']))
        tcc_df['avg_tcc'] = tcc_df['properties'].apply(lambda x: x['avg_tcc'])
        tcc_df['median_tcc'] = tcc_df['properties'].apply(lambda x: x['median_tcc'])
        tcc_df.drop(columns=['properties', 'type', 'geometry'], inplace=True)

        # create the hour and month and year for tcc_df
        tcc_df['hour'] = tcc_df['date'].dt.hour
        tcc_df['day'] = tcc_df['date'].dt.day
        tcc_df['month'] = tcc_df['date'].dt.month
        tcc_df['year'] = tcc_df['date'].dt.year

        # filter out midnitght, so that we only count from 6 am to 6 pm
        tcc_df = tcc_df[tcc_df['hour'] != 0 ]

        # aggregate cloud coverage at the daily level
        tcc_df = tcc_df.groupby(['year', 'month', 'day']).agg({'avg_tcc': 'mean', 'median_tcc': 'median'}).reset_index()

        # count the number of cloudy days by those with coverage over 75% on average
        tcc_df['cloudy_days'] = tcc_df['avg_tcc'] > 75

        # now aggreagate to the monthly level, number of cloudy days, avg_tcc and median_tcc
        tcc_df = tcc_df.groupby(['year', 'month']).agg({'cloudy_days': 'sum', 'avg_tcc': 'mean', 'median_tcc': 'median'}).reset_index()

        # Add utility info
        for col in u_sf.columns:
            if col != 'geometry':
                tcc_df[col] = u_sf.iloc[0][col]

        utility_monthly_tcc.append(tcc_df)

    except Exception as e:
        print(f"Failed for utility {u}: {e}")
        continue

    print(f"{u} completed in {datetime.now() - start_time}")

# Combine all data and write to CSV
result_df = pd.concat(utility_monthly_tcc, ignore_index=True)

# Save to CSV
result_df.to_csv("data files/monthly_cloudy_days_utility_all_75pcnt_cov.csv", index=False)

  0%|          | 1/4292 [00:15<17:54:05, 15.02s/it]

AK_1651_2011 completed in 0:00:15.018733

  0%|          | 2/4292 [00:26<15:30:46, 13.02s/it]

AK_7353_2011 completed in 0:00:11.616342

  0%|          | 3/4292 [00:37<14:19:31, 12.02s/it]

AK_19558_2011 completed in 0:00:10.840762

  0%|          | 4/4292 [00:48<14:03:19, 11.80s/it]

AR_814_2011 completed in 0:00:11.455905

  0%|          | 5/4292 [00:58<13:02:05, 10.95s/it]

AR_817_2011 completed in 0:00:09.427998

  0%|          | 6/4292 [01:04<11:10:31,  9.39s/it]

AR_6342_2011 completed in 0:00:06.358187

  0%|          | 7/4292 [01:09<9:27:15,  7.94s/it]

AR_14063_2011 completed in 0:00:04.969069

  0%|          | 8/4292 [01:16<9:11:59,  7.73s/it]

AR_17698_2011 completed in 0:00:07.276047

  0%|          | 9/4292 [01:24<8:59:23,  7.56s/it]

AZ_16572_2011 completed in 0:00:07.168770

  0%|          | 10/4292 [01:32<9:23:15,  7.89s/it]

AZ_19728_2011 completed in 0:00:08.644069

  0%|          | 11/4292 [01:39<8:58:33,  7.55s/it]

AZ_21538_2011 completed in 0:00:06.766191

  0%|          | 12/4292 [01:44<7:57:35,  6.70s/it]

AZ_24211_2011 completed in 0:00:04.744117

  0%|          | 13/4292 [01:49<7:14:30,  6.09s/it]

CA_11208_2011 completed in 0:00:04.704773

  0%|          | 14/4292 [02:07<11:39:52,  9.82s/it]

CA_14328_2011 completed in 0:00:18.417023

  0%|          | 15/4292 [02:15<11:09:51,  9.40s/it]

CA_14354_2011 completed in 0:00:08.426062

  0%|          | 16/4292 [02:25<11:12:44,  9.44s/it]

CA_14534_2011 completed in 0:00:09.533997

  0%|          | 17/4292 [02:33<10:49:50,  9.12s/it]

CA_16534_2011 completed in 0:00:08.377071

  0%|          | 18/4292 [02:40<10:06:18,  8.51s/it]

CA_16609_2011 completed in 0:00:07.093348

  0%|          | 19/4292 [02:49<10:04:14,  8.48s/it]

CA_17609_2011 completed in 0:00:08.420551

  0%|          | 20/4292 [02:54<9:03:38,  7.64s/it]

CA_19281_2011 completed in 0:00:05.655593

  0%|          | 21/4292 [03:01<8:31:55,  7.19s/it]

CO_3989_2011 completed in 0:00:06.156139

  1%|          | 22/4292 [03:06<8:02:47,  6.78s/it]

CO_6604_2011 completed in 0:00:05.832246

  1%|          | 23/4292 [03:13<8:05:26,  6.82s/it]

CO_9336_2011 completed in 0:00:06.912152

  1%|          | 24/4292 [03:26<10:03:09,  8.48s/it]

CO_15257_2011 completed in 0:00:12.342934

  1%|          | 25/4292 [03:33<9:31:45,  8.04s/it]

CO_15466_2011 completed in 0:00:07.013498

  1%|          | 26/4292 [03:42<10:01:14,  8.46s/it]

CO_16603_2011 completed in 0:00:09.426683

  1%|          | 27/4292 [03:52<10:24:16,  8.78s/it]

CO_19499_2011 completed in 0:00:09.542348

  1%|          | 28/4292 [03:58<9:37:46,  8.13s/it]

CT_19497_2011 completed in 0:00:06.607420

  1%|          | 29/4292 [04:07<9:57:26,  8.41s/it]

DC_15270_2011 completed in 0:00:09.058168

  1%|          | 30/4292 [04:14<9:28:23,  8.00s/it]

DE_5027_2011 completed in 0:00:07.051081

  1%|          | 31/4292 [04:20<8:31:54,  7.21s/it]

DE_5070_2011 completed in 0:00:05.355940

  1%|          | 32/4292 [04:26<8:07:38,  6.87s/it]

DE_5335_2011 completed in 0:00:06.073254

  1%|          | 33/4292 [04:38<10:08:22,  8.57s/it]

FL_6452_2011 completed in 0:00:12.542575

  1%|          | 34/4292 [04:47<10:03:05,  8.50s/it]

FL_6455_2011 completed in 0:00:08.327956

  1%|          | 35/4292 [04:56<10:17:43,  8.71s/it]

FL_7801_2011 completed in 0:00:09.191638

  1%|          | 36/4292 [05:04<10:03:27,  8.51s/it]

FL_9617_2011 completed in 0:00:08.042142

  1%|          | 37/4292 [05:11<9:26:09,  7.98s/it]

FL_18454_2011 completed in 0:00:06.759763

  1%|          | 38/4292 [05:17<8:56:52,  7.57s/it]

GA_3916_2011 completed in 0:00:06.612303

  1%|          | 39/4292 [05:27<9:42:25,  8.22s/it]

GA_7140_2011 completed in 0:00:09.718556

  1%|          | 40/4292 [05:36<9:59:23,  8.46s/it]

HI_8287_2011 completed in 0:00:09.020684

  1%|          | 41/4292 [05:44<9:39:02,  8.17s/it]

HI_10071_2011 completed in 0:00:07.505621

  1%|          | 42/4292 [05:50<8:58:51,  7.61s/it]

HI_11843_2011 completed in 0:00:06.287312

  1%|          | 43/4292 [05:57<8:47:37,  7.45s/it]

HI_19547_2011 completed in 0:00:07.083962

  1%|          | 44/4292 [06:04<8:40:55,  7.36s/it]

IA_9417_2011 completed in 0:00:07.137182

  1%|          | 45/4292 [06:15<9:53:47,  8.39s/it]

IA_12341_2011 completed in 0:00:10.793766

  1%|          | 46/4292 [06:28<11:42:11,  9.92s/it]

ID_9191_2011 completed in 0:00:13.500499

  1%|          | 47/4292 [06:36<10:51:53,  9.21s/it]

ID_14354_2011 completed in 0:00:07.559387

  1%|          | 48/4292 [06:45<10:42:55,  9.09s/it]

ID_20169_2011 completed in 0:00:08.797377

  1%|          | 49/4292 [06:52<10:07:08,  8.59s/it]

IL_4110_2011 completed in 0:00:07.406404

  1%|          | 50/4292 [06:58<9:18:08,  7.89s/it]

IL_12341_2011 completed in 0:00:06.280679

  1%|          | 51/4292 [07:05<9:00:27,  7.65s/it]

IN_9273_2011 completed in 0:00:07.065427

  1%|          | 52/4292 [07:14<9:19:11,  7.91s/it]

IN_9324_2011 completed in 0:00:08.535096

  1%|          | 53/4292 [07:27<11:10:46,  9.49s/it]

IN_15470_2011 completed in 0:00:13.182893

  1%|▏         | 54/4292 [07:40<12:25:44, 10.56s/it]

IN_17633_2011 completed in 0:00:13.038406

  1%|▏         | 55/4292 [07:47<11:14:20,  9.55s/it]

KS_10005_2011 completed in 0:00:07.194924

  1%|▏         | 56/4292 [07:56<10:46:39,  9.16s/it]

KS_22500_2011 completed in 0:00:08.247507

  1%|▏         | 57/4292 [08:10<12:34:20, 10.69s/it]

KY_10171_2011 completed in 0:00:14.251321

  1%|▏         | 58/4292 [08:20<12:26:47, 10.58s/it]

KY_11249_2011 completed in 0:00:10.338250

  1%|▏         | 59/4292 [08:28<11:29:05,  9.77s/it]

KY_19446_2011 completed in 0:00:07.864093

  1%|▏         | 60/4292 [08:39<12:01:23, 10.23s/it]

KY_49998_2011 completed in 0:00:11.300253

  1%|▏         | 61/4292 [08:49<11:47:44, 10.04s/it]

LA_11241_2011 completed in 0:00:09.589402

  1%|▏         | 62/4292 [08:57<11:09:35,  9.50s/it]

LA_13478_2011 completed in 0:00:08.236415

  1%|▏         | 63/4292 [09:06<10:59:06,  9.35s/it]

LA_17698_2011 completed in 0:00:09.008504

  1%|▏         | 64/4292 [09:17<11:18:47,  9.63s/it]

LA_55936_2011 completed in 0:00:10.288841

  2%|▏         | 65/4292 [09:24<10:32:14,  8.97s/it]

MA_6374_2011 completed in 0:00:07.436879

  2%|▏         | 66/4292 [09:32<10:13:13,  8.71s/it]

MA_8774_2011 completed in 0:00:08.080209

  2%|▏         | 67/4292 [09:41<10:19:39,  8.80s/it]

MA_11804_2011 completed in 0:00:09.016742

  2%|▏         | 68/4292 [09:48<9:45:26,  8.32s/it]

MA_13206_2011 completed in 0:00:07.186165

  2%|▏         | 69/4292 [09:59<10:27:34,  8.92s/it]

MD_1167_2011 completed in 0:00:10.316779

  2%|▏         | 70/4292 [10:10<11:13:44,  9.57s/it]

MD_5027_2011 completed in 0:00:11.110132

  2%|▏         | 71/4292 [10:39<18:14:47, 15.56s/it]

MD_15263_2011 completed in 0:00:29.531313

  2%|▏         | 72/4292 [10:49<16:05:25, 13.73s/it]

MD_15270_2011 completed in 0:00:09.439683

  2%|▏         | 73/4292 [10:58<14:37:16, 12.48s/it]

ME_3266_2011 completed in 0:00:09.558010

  2%|▏         | 74/4292 [11:05<12:31:49, 10.69s/it]

MI_392_2011 completed in 0:00:06.536338

  2%|▏         | 75/4292 [11:15<12:27:55, 10.64s/it]

MI_3828_2011 completed in 0:00:10.514250

  2%|▏         | 76/4292 [11:27<12:42:43, 10.85s/it]

MI_4254_2011 completed in 0:00:11.351238

  2%|▏         | 77/4292 [11:37<12:30:25, 10.68s/it]

MI_5109_2011 completed in 0:00:10.278427

  2%|▏         | 78/4292 [11:47<12:22:06, 10.57s/it]

MI_9324_2011 completed in 0:00:10.294942

  2%|▏         | 79/4292 [11:56<11:53:25, 10.16s/it]

MI_19578_2011 completed in 0:00:09.212162

  2%|▏         | 80/4292 [12:11<13:26:51, 11.49s/it]

MI_20847_2011 completed in 0:00:14.603950

  2%|▏         | 81/4292 [12:48<22:32:21, 19.27s/it]

MI_20860_2011 completed in 0:00:37.410639

  2%|▏         | 82/4292 [13:09<22:52:36, 19.56s/it]

MN_5574_2011 completed in 0:00:20.244628

  2%|▏         | 83/4292 [13:17<18:55:42, 16.19s/it]

MN_12647_2011 completed in 0:00:08.316356

  2%|▏         | 84/4292 [13:31<17:58:40, 15.38s/it]

MN_14232_2011 completed in 0:00:13.491435

  2%|▏         | 85/4292 [13:39<15:35:20, 13.34s/it]

MN_17267_2011 completed in 0:00:08.577455

  2%|▏         | 86/4292 [13:46<13:19:13, 11.40s/it]

MN_25177_2011 completed in 0:00:06.876876

  2%|▏         | 87/4292 [13:53<11:54:21, 10.19s/it]

MO_4675_2011 completed in 0:00:07.372248

  2%|▏         | 88/4292 [14:07<13:12:56, 11.32s/it]

MO_5860_2011 completed in 0:00:13.938996

  2%|▏         | 89/4292 [14:17<12:39:06, 10.84s/it]

MO_10000_2011 completed in 0:00:09.714511

  2%|▏         | 90/4292 [14:30<13:13:52, 11.34s/it]

MO_12698_2011 completed in 0:00:12.498836

  2%|▏         | 91/4292 [14:41<13:20:40, 11.44s/it]

MO_17833_2011 completed in 0:00:11.667721

WARNING:googleapiclient.http:Sleeping 1.52 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/value:compute?prettyPrint=false&alt=json, after 503
  2%|▏         | 92/4292 [14:59<15:43:34, 13.48s/it]

MO_19436_2011 completed in 0:00:18.248307

  2%|▏         | 93/4292 [15:09<14:16:28, 12.24s/it]

MT_6395_2011 completed in 0:00:09.337773

  2%|▏         | 94/4292 [15:17<13:01:14, 11.17s/it]

MT_12692_2011 completed in 0:00:08.662705

  2%|▏         | 95/4292 [15:31<13:47:10, 11.83s/it]

MT_12825_2011 completed in 0:00:13.362530

  2%|▏         | 96/4292 [15:38<12:15:16, 10.51s/it]

MT_20997_2011 completed in 0:00:07.453878

  2%|▏         | 97/4292 [15:54<14:05:02, 12.09s/it]

NC_3046_2011 completed in 0:00:15.754053

  2%|▏         | 98/4292 [16:36<24:31:01, 21.04s/it]

NC_5416_2011 completed in 0:00:41.947044

  2%|▏         | 99/4292 [16:45<20:17:39, 17.42s/it]

NC_9837_2011 completed in 0:00:08.975044

  2%|▏         | 100/4292 [17:05<21:10:39, 18.19s/it]

NC_16496_2011 completed in 0:00:19.965635

  2%|▏         | 101/4292 [17:14<17:52:28, 15.35s/it]

NC_19876_2011 completed in 0:00:08.742731

  2%|▏         | 102/4292 [17:27<17:16:51, 14.85s/it]

ND_12087_2011 completed in 0:00:13.664738

  2%|▏         | 103/4292 [17:40<16:33:55, 14.24s/it]

ND_14232_2011 completed in 0:00:12.805296

  2%|▏         | 104/4292 [17:50<14:56:31, 12.84s/it]

ND_24949_2011 completed in 0:00:09.592279

  2%|▏         | 105/4292 [17:57<13:00:50, 11.19s/it]

NE_11018_2011 completed in 0:00:07.327648

  2%|▏         | 106/4292 [18:04<11:25:56,  9.83s/it]

NE_17642_2011 completed in 0:00:06.663366

  2%|▏         | 107/4292 [18:22<14:15:13, 12.26s/it]

NH_13441_2011 completed in 0:00:17.923351

  3%|▎         | 108/4292 [18:31<13:14:25, 11.39s/it]

NH_15472_2011 completed in 0:00:09.363967

  3%|▎         | 109/4292 [18:42<13:04:33, 11.25s/it]

NH_24590_2011 completed in 0:00:10.928619

  3%|▎         | 110/4292 [18:54<13:22:32, 11.51s/it]

NH_26510_2011 completed in 0:00:12.120756

  3%|▎         | 111/4292 [19:17<17:26:15, 15.01s/it]

NJ_963_2011 completed in 0:00:23.178409

  3%|▎         | 112/4292 [19:25<14:56:33, 12.87s/it]

NJ_9726_2011 completed in 0:00:07.860822

  3%|▎         | 113/4292 [19:38<14:54:14, 12.84s/it]

NJ_16213_2011 completed in 0:00:12.767394

  3%|▎         | 114/4292 [19:52<15:27:07, 13.31s/it]

NM_5701_2011 completed in 0:00:14.422894

  3%|▎         | 115/4292 [20:06<15:40:48, 13.51s/it]

NM_6204_2011 completed in 0:00:13.979047

  3%|▎         | 116/4292 [20:22<16:19:13, 14.07s/it]

NM_9699_2011 completed in 0:00:15.363654

  3%|▎         | 117/4292 [20:34<15:38:01, 13.48s/it]

NM_11204_2011 completed in 0:00:12.106097

  3%|▎         | 118/4292 [20:45<14:57:13, 12.90s/it]

NV_2008_2011 completed in 0:00:11.535295

  3%|▎         | 119/4292 [20:57<14:40:54, 12.67s/it]

NV_13407_2011 completed in 0:00:12.122316

  3%|▎         | 120/4292 [21:11<14:57:35, 12.91s/it]

NV_17166_2011 completed in 0:00:13.474498

WARNING:googleapiclient.http:Sleeping 0.27 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/value:compute?prettyPrint=false&alt=json, after 503
  3%|▎         | 121/4292 [21:41<20:46:12, 17.93s/it]

NV_19840_2011 completed in 0:00:29.634350

  3%|▎         | 122/4292 [22:02<22:06:31, 19.09s/it]

NY_3249_2011 completed in 0:00:21.792350

  3%|▎         | 123/4292 [22:25<23:18:04, 20.12s/it]

NY_13511_2011 completed in 0:00:22.533648

  3%|▎         | 124/4292 [22:34<19:35:01, 16.91s/it]

NY_14154_2011 completed in 0:00:09.432710

  3%|▎         | 125/4292 [22:46<17:36:06, 15.21s/it]

OH_3542_2011 completed in 0:00:11.219440

  3%|▎         | 126/4292 [23:05<19:04:25, 16.48s/it]

OH_3755_2011 completed in 0:00:19.458009

  3%|▎         | 127/4292 [23:16<17:15:31, 14.92s/it]

OH_4922_2011 completed in 0:00:11.265538

  3%|▎         | 128/4292 [23:33<17:51:21, 15.44s/it]

OH_13998_2011 completed in 0:00:16.649301

  3%|▎         | 129/4292 [24:08<24:37:11, 21.29s/it]

OH_14006_2011 completed in 0:00:34.946376

  3%|▎         | 130/4292 [24:17<20:31:27, 17.75s/it]

OH_18997_2011 completed in 0:00:09.498022

  3%|▎         | 131/4292 [24:29<18:26:55, 15.96s/it]

OK_13734_2011 completed in 0:00:11.780394

  3%|▎         | 132/4292 [24:51<20:34:00, 17.80s/it]

OK_14063_2011 completed in 0:00:22.082873

  3%|▎         | 133/4292 [25:07<19:59:11, 17.30s/it]

OK_15474_2011 completed in 0:00:16.134808

  3%|▎         | 134/4292 [25:24<19:50:50, 17.18s/it]

OR_6022_2011 completed in 0:00:16.911417

  3%|▎         | 135/4292 [25:34<17:07:29, 14.83s/it]

OR_9191_2011 completed in 0:00:09.337469

  3%|▎         | 136/4292 [25:50<17:45:25, 15.38s/it]

OR_14354_2011 completed in 0:00:16.666458

  3%|▎         | 137/4292 [26:04<17:14:03, 14.93s/it]

OR_15248_2011 completed in 0:00:13.883095

  3%|▎         | 138/4292 [26:21<17:55:06, 15.53s/it]

OR_40437_2011 completed in 0:00:16.919273

  3%|▎         | 139/4292 [26:45<20:46:32, 18.01s/it]

PA_3597_2011 completed in 0:00:23.796200

  3%|▎         | 140/4292 [27:11<23:44:06, 20.58s/it]

PA_5487_2011 completed in 0:00:26.575800

  3%|▎         | 141/4292 [27:20<19:38:34, 17.04s/it]

PA_12390_2011 completed in 0:00:08.764891

  3%|▎         | 142/4292 [27:51<24:18:00, 21.08s/it]

PA_14711_2011 completed in 0:00:30.515404

  3%|▎         | 143/4292 [28:04<21:45:24, 18.88s/it]

PA_14715_2011 completed in 0:00:13.739631

  3%|▎         | 144/4292 [28:16<19:16:15, 16.72s/it]

PA_14716_2011 completed in 0:00:11.700367

  3%|▎         | 145/4292 [28:36<20:23:11, 17.70s/it]

PA_14940_2011 completed in 0:00:19.965697

  3%|▎         | 146/4292 [28:46<17:35:46, 15.28s/it]

PA_15045_2011 completed in 0:00:09.634890

  3%|▎         | 147/4292 [29:02<18:03:38, 15.69s/it]

PA_19390_2011 completed in 0:00:16.627811

  3%|▎         | 148/4292 [29:13<16:25:19, 14.27s/it]

PA_20334_2011 completed in 0:00:10.953226

  3%|▎         | 149/4292 [29:26<15:49:42, 13.75s/it]

PA_20387_2011 completed in 0:00:12.557122

  3%|▎         | 150/4292 [29:50<19:13:27, 16.71s/it]

RI_1857_2011 completed in 0:00:23.602150

  4%|▎         | 151/4292 [29:57<16:02:31, 13.95s/it]

RI_13214_2011 completed in 0:00:07.499664

  4%|▎         | 152/4292 [30:07<14:30:57, 12.62s/it]

SC_3046_2011 completed in 0:00:09.533100

  4%|▎         | 153/4292 [30:14<12:51:49, 11.19s/it]

SC_5416_2011 completed in 0:00:07.842036

  4%|▎         | 154/4292 [30:25<12:48:06, 11.14s/it]

SC_17539_2011 completed in 0:00:11.016454

  4%|▎         | 155/4292 [30:40<13:56:50, 12.14s/it]

SC_17543_2011 completed in 0:00:14.468889

  4%|▎         | 156/4292 [30:52<13:58:17, 12.16s/it]

SD_14232_2011 completed in 0:00:12.215462

  4%|▎         | 157/4292 [31:06<14:33:06, 12.67s/it]

SD_19545_2011 completed in 0:00:13.853765

  4%|▎         | 158/4292 [31:15<13:26:55, 11.71s/it]

SD_20401_2011 completed in 0:00:09.476045

  4%|▎         | 159/4292 [31:22<11:47:16, 10.27s/it]

TX_5701_2011 completed in 0:00:06.897693

  4%|▎         | 160/4292 [31:34<12:06:33, 10.55s/it]

TX_17698_2011 completed in 0:00:11.208655

  4%|▍         | 161/4292 [31:41<11:06:18,  9.68s/it]

TX_55937_2011 completed in 0:00:07.640934

  4%|▍         | 162/4292 [31:51<11:08:55,  9.72s/it]

UT_2010_2011 completed in 0:00:09.810830

  4%|▍         | 163/4292 [31:59<10:28:20,  9.13s/it]

UT_12866_2011 completed in 0:00:07.755601

  4%|▍         | 164/4292 [32:08<10:35:18,  9.23s/it]

UT_14354_2011 completed in 0:00:09.474977

  4%|▍         | 165/4292 [32:18<10:41:09,  9.32s/it]

UT_15444_2011 completed in 0:00:09.524207

  4%|▍         | 166/4292 [32:26<10:15:48,  8.96s/it]

UT_17845_2011 completed in 0:00:08.099238

  4%|▍         | 167/4292 [32:34<10:01:52,  8.75s/it]

UT_17874_2011 completed in 0:00:08.283962

  4%|▍         | 168/4292 [32:57<15:00:59, 13.11s/it]

VA_733_2011 completed in 0:00:23.267016

  4%|▍         | 169/4292 [33:15<16:34:48, 14.48s/it]

VA_17066_2011 completed in 0:00:17.669142

  4%|▍         | 170/4292 [33:29<16:19:25, 14.26s/it]

VA_19876_2011 completed in 0:00:13.736940

  4%|▍         | 171/4292 [33:48<17:59:20, 15.71s/it]

VA_40228_2011 completed in 0:00:19.111256

  4%|▍         | 172/4292 [34:06<18:57:46, 16.57s/it]

VT_2548_2011 completed in 0:00:18.562998

  4%|▍         | 173/4292 [34:15<16:06:53, 14.08s/it]

VT_7601_2011 completed in 0:00:08.285032

  4%|▍         | 174/4292 [34:40<19:59:38, 17.48s/it]

VT_19791_2011 completed in 0:00:25.398612

  4%|▍         | 175/4292 [34:48<16:49:53, 14.72s/it]

WA_3660_2011 completed in 0:00:08.274364

  4%|▍         | 176/4292 [35:12<19:50:13, 17.35s/it]

WA_15500_2011 completed in 0:00:23.491567

  4%|▍         | 177/4292 [35:23<17:32:15, 15.34s/it]

WA_17470_2011 completed in 0:00:10.657499

  4%|▍         | 178/4292 [35:33<16:00:02, 14.00s/it]

WA_18429_2011 completed in 0:00:10.871598

  4%|▍         | 179/4292 [35:43<14:21:01, 12.56s/it]

WA_20169_2011 completed in 0:00:09.197380

  4%|▍         | 180/4292 [35:50<12:37:13, 11.05s/it]

WI_11479_2011 completed in 0:00:07.520608

  4%|▍         | 181/4292 [35:59<11:52:11, 10.39s/it]

WI_13697_2011 completed in 0:00:08.866499

  4%|▍         | 182/4292 [36:06<10:37:50,  9.31s/it]

WI_13815_2011 completed in 0:00:06.784224

  4%|▍         | 183/4292 [36:17<11:16:47,  9.88s/it]

WI_20847_2011 completed in 0:00:11.213824

  4%|▍         | 184/4292 [36:26<10:55:31,  9.57s/it]

WI_20856_2011 completed in 0:00:08.854331

  4%|▍         | 185/4292 [36:42<13:08:51, 11.52s/it]

WI_20860_2011 completed in 0:00:16.074522

  4%|▍         | 186/4292 [36:52<12:32:34, 11.00s/it]

WV_733_2011 completed in 0:00:09.765872

  4%|▍         | 187/4292 [37:01<11:58:39, 10.50s/it]

WV_12796_2011 completed in 0:00:09.352278

  4%|▍         | 188/4292 [37:11<11:51:52, 10.41s/it]

WV_20521_2011 completed in 0:00:10.181625

  4%|▍         | 189/4292 [37:18<10:34:57,  9.29s/it]

WY_3461_2011 completed in 0:00:06.665819

  4%|▍         | 190/4292 [37:28<10:41:06,  9.38s/it]

WY_8566_2011 completed in 0:00:09.591389

  4%|▍         | 191/4292 [37:35<9:59:57,  8.78s/it]

WY_14354_2011 completed in 0:00:07.377803

  4%|▍         | 192/4292 [37:43<9:51:26,  8.66s/it]

WY_19156_2011 completed in 0:00:08.364849

  4%|▍         | 193/4292 [37:50<9:17:03,  8.15s/it]

WY_27058_2011 completed in 0:00:06.983289

  5%|▍         | 194/4292 [38:00<9:58:15,  8.76s/it]

AK_3522_2011 completed in 0:00:10.171129

  5%|▍         | 195/4292 [38:08<9:32:19,  8.38s/it]

AR_3093_2011 completed in 0:00:07.499628

  5%|▍         | 196/4292 [38:16<9:28:55,  8.33s/it]

FL_6457_2011 completed in 0:00:08.221706

  5%|▍         | 197/4292 [38:23<9:06:33,  8.01s/it]

MN_9417_2011 completed in 0:00:07.246819

  5%|▍         | 198/4292 [38:30<8:36:05,  7.56s/it]

NM_22690_2011 completed in 0:00:06.521919

  5%|▍         | 199/4292 [38:37<8:29:17,  7.47s/it]

TN_10331_2011 completed in 0:00:07.236654

  5%|▍         | 200/4292 [38:46<9:00:54,  7.93s/it]

TX_17008_2011 completed in 0:00:09.016465

  5%|▍         | 201/4292 [38:54<8:56:17,  7.87s/it]

WA_14354_2011 completed in 0:00:07.710611

  5%|▍         | 202/4292 [39:11<12:05:16, 10.64s/it]

WI_4715_2011 completed in 0:00:17.112445

  5%|▍         | 203/4292 [39:18<10:56:27,  9.63s/it]

AZ_19189_2011 completed in 0:00:07.281321

  5%|▍         | 204/4292 [39:34<12:56:30, 11.40s/it]

CT_4176_2011 completed in 0:00:15.512864

  5%|▍         | 205/4292 [39:45<12:44:26, 11.22s/it]

KY_22053_2011 completed in 0:00:10.814792

  5%|▍         | 206/4292 [39:52<11:20:28,  9.99s/it]

MA_20455_2011 completed in 0:00:07.118342

  5%|▍         | 207/4292 [39:59<10:14:24,  9.02s/it]

NJ_15477_2011 completed in 0:00:06.765477

  5%|▍         | 208/4292 [40:25<16:01:55, 14.13s/it]

NV_13073_2011 completed in 0:00:26.049363

  5%|▍         | 209/4292 [40:35<14:38:45, 12.91s/it]

SD_1769_2011 completed in 0:00:10.069181

  5%|▍         | 210/4292 [40:41<12:27:35, 10.99s/it]

CA_12745_2011 completed in 0:00:06.496660

  5%|▍         | 211/4292 [40:48<10:58:36,  9.68s/it]

MO_9231_2011 completed in 0:00:06.635713

  5%|▍         | 212/4292 [40:55<10:06:27,  8.92s/it]

IN_13756_2011 completed in 0:00:07.133871

  5%|▍         | 213/4292 [41:03<9:44:06,  8.59s/it]

TN_12293_2011 completed in 0:00:07.828520

  5%|▍         | 214/4292 [41:10<9:15:19,  8.17s/it]

KS_10000_2011 completed in 0:00:07.183883

  5%|▌         | 215/4292 [41:18<9:20:46,  8.25s/it]

NC_24889_2011 completed in 0:00:08.444143

  5%|▌         | 216/4292 [41:25<8:45:55,  7.74s/it]

CO_27058_2011 completed in 0:00:06.548268

  5%|▌         | 217/4292 [41:33<8:56:46,  7.90s/it]

ID_10454_2011 completed in 0:00:08.280254

  5%|▌         | 218/4292 [41:41<9:00:44,  7.96s/it]

IL_13032_2011 completed in 0:00:08.101807

  5%|▌         | 219/4292 [41:52<9:46:10,  8.64s/it]

AK_3522_2012 completed in 0:00:10.196326

  5%|▌         | 220/4292 [41:59<9:31:43,  8.42s/it]

AK_7353_2012 completed in 0:00:07.931503

  5%|▌         | 221/4292 [42:08<9:39:10,  8.54s/it]

AK_19558_2012 completed in 0:00:08.795923

  5%|▌         | 222/4292 [42:16<9:26:55,  8.36s/it]

AR_814_2012 completed in 0:00:07.940716

  5%|▌         | 223/4292 [42:23<8:48:12,  7.79s/it]

AR_817_2012 completed in 0:00:06.460877

  5%|▌         | 224/4292 [42:33<9:46:37,  8.65s/it]

AR_3093_2012 completed in 0:00:10.666123

  5%|▌         | 225/4292 [42:39<8:54:38,  7.89s/it]

AR_6342_2012 completed in 0:00:06.101779

  5%|▌         | 226/4292 [42:48<9:07:01,  8.07s/it]

AR_14063_2012 completed in 0:00:08.501772

WARNING:googleapiclient.http:Sleeping 0.96 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/value:compute?prettyPrint=false&alt=json, after 503
  5%|▌         | 227/4292 [43:01<10:48:13,  9.57s/it]

AR_17698_2012 completed in 0:00:13.057366

  5%|▌         | 228/4292 [43:07<9:41:46,  8.59s/it]

AZ_16572_2012 completed in 0:00:06.304580

  5%|▌         | 229/4292 [43:15<9:25:15,  8.35s/it]

AZ_19189_2012 completed in 0:00:07.781921

  5%|▌         | 230/4292 [43:22<9:04:28,  8.04s/it]

AZ_19728_2012 completed in 0:00:07.330432

  5%|▌         | 231/4292 [43:29<8:39:15,  7.67s/it]

AZ_21538_2012 completed in 0:00:06.805808

  5%|▌         | 232/4292 [43:36<8:13:14,  7.29s/it]

AZ_24211_2012 completed in 0:00:06.395780

  5%|▌         | 233/4292 [43:42<7:56:40,  7.05s/it]

CA_11208_2012 completed in 0:00:06.477807

  5%|▌         | 234/4292 [43:48<7:33:18,  6.70s/it]

CA_12745_2012 completed in 0:00:05.899896

  5%|▌         | 235/4292 [44:04<10:47:45,  9.58s/it]

CA_14328_2012 completed in 0:00:16.292812

  5%|▌         | 236/4292 [44:11<9:55:08,  8.80s/it]

CA_14354_2012 completed in 0:00:06.992090

  6%|▌         | 237/4292 [44:18<9:15:14,  8.22s/it]

CA_14534_2012 completed in 0:00:06.842335

  6%|▌         | 238/4292 [44:25<8:49:38,  7.84s/it]

CA_16534_2012 completed in 0:00:06.958364

  6%|▌         | 239/4292 [44:34<9:17:07,  8.25s/it]

CA_16609_2012 completed in 0:00:09.200765

  6%|▌         | 240/4292 [44:45<10:09:43,  9.03s/it]

CA_17609_2012 completed in 0:00:10.849579

  6%|▌         | 241/4292 [44:53<9:37:08,  8.55s/it]

CA_19281_2012 completed in 0:00:07.423021

  6%|▌         | 242/4292 [45:00<9:21:54,  8.32s/it]

CO_3989_2012 completed in 0:00:07.801724

  6%|▌         | 243/4292 [45:07<8:45:02,  7.78s/it]

CO_6604_2012 completed in 0:00:06.509404

  6%|▌         | 244/4292 [45:17<9:30:04,  8.45s/it]

CO_9336_2012 completed in 0:00:10.010965

  6%|▌         | 245/4292 [45:24<9:02:58,  8.05s/it]

CO_15257_2012 completed in 0:00:07.115930

  6%|▌         | 246/4292 [45:30<8:23:39,  7.47s/it]

CO_15466_2012 completed in 0:00:06.112503

  6%|▌         | 247/4292 [45:42<9:42:58,  8.65s/it]

CO_16603_2012 completed in 0:00:11.396257

  6%|▌         | 248/4292 [45:50<9:42:01,  8.64s/it]

CO_19499_2012 completed in 0:00:08.606687

  6%|▌         | 249/4292 [45:59<9:41:40,  8.63s/it]

CO_27058_2012 completed in 0:00:08.623581

  6%|▌         | 250/4292 [46:06<9:23:23,  8.36s/it]

CT_4176_2012 completed in 0:00:07.729617

  6%|▌         | 251/4292 [46:14<9:15:35,  8.25s/it]

CT_19497_2012 completed in 0:00:07.983036

  6%|▌         | 252/4292 [46:23<9:15:06,  8.24s/it]

DC_15270_2012 completed in 0:00:08.230795

  6%|▌         | 253/4292 [46:30<8:47:52,  7.84s/it]

DE_5027_2012 completed in 0:00:06.901340

  6%|▌         | 254/4292 [46:41<10:05:16,  8.99s/it]

DE_5070_2012 completed in 0:00:11.680731

  6%|▌         | 255/4292 [46:49<9:35:58,  8.56s/it]

DE_5335_2012 completed in 0:00:07.548580

  6%|▌         | 256/4292 [46:57<9:36:38,  8.57s/it]

FL_6452_2012 completed in 0:00:08.599227

  6%|▌         | 257/4292 [47:07<10:00:19,  8.93s/it]

FL_6455_2012 completed in 0:00:09.752417

  6%|▌         | 258/4292 [47:14<9:15:03,  8.26s/it]

FL_6457_2012 completed in 0:00:06.689202

  6%|▌         | 259/4292 [47:22<9:19:00,  8.32s/it]

FL_7801_2012 completed in 0:00:08.452883

  6%|▌         | 260/4292 [47:29<8:46:58,  7.84s/it]

FL_9617_2012 completed in 0:00:06.733348

  6%|▌         | 261/4292 [47:35<8:16:46,  7.39s/it]

FL_18454_2012 completed in 0:00:06.349554

  6%|▌         | 262/4292 [47:43<8:16:32,  7.39s/it]

GA_3916_2012 completed in 0:00:07.387741

  6%|▌         | 263/4292 [47:52<8:53:01,  7.94s/it]

GA_7140_2012 completed in 0:00:09.208782

  6%|▌         | 264/4292 [47:59<8:24:32,  7.52s/it]

HI_8287_2012 completed in 0:00:06.529563

  6%|▌         | 265/4292 [48:06<8:24:06,  7.51s/it]

HI_10071_2012 completed in 0:00:07.498610

  6%|▌         | 266/4292 [48:13<8:14:31,  7.37s/it]

HI_11843_2012 completed in 0:00:07.040057

  6%|▌         | 267/4292 [48:19<7:50:47,  7.02s/it]

HI_19547_2012 completed in 0:00:06.196293

  6%|▌         | 268/4292 [48:27<8:06:38,  7.26s/it]

IA_9417_2012 completed in 0:00:07.810648

  6%|▋         | 269/4292 [48:34<8:00:14,  7.16s/it]

IA_12341_2012 completed in 0:00:06.938491

  6%|▋         | 270/4292 [48:42<8:17:45,  7.43s/it]

ID_9191_2012 completed in 0:00:08.038309

  6%|▋         | 271/4292 [48:49<8:17:28,  7.42s/it]

ID_10454_2012 completed in 0:00:07.412804

  6%|▋         | 272/4292 [48:56<8:04:27,  7.23s/it]

ID_14354_2012 completed in 0:00:06.780987

  6%|▋         | 273/4292 [49:02<7:38:24,  6.84s/it]

ID_20169_2012 completed in 0:00:05.939574

  6%|▋         | 274/4292 [49:10<8:00:25,  7.17s/it]

IL_4110_2012 completed in 0:00:07.943777

  6%|▋         | 275/4292 [49:17<7:45:40,  6.96s/it]

IL_12341_2012 completed in 0:00:06.444537

  6%|▋         | 276/4292 [49:23<7:30:51,  6.74s/it]

IL_13032_2012 completed in 0:00:06.218413

  6%|▋         | 277/4292 [49:28<7:07:17,  6.39s/it]

IN_9273_2012 completed in 0:00:05.566171

  6%|▋         | 278/4292 [49:35<7:18:24,  6.55s/it]

IN_9324_2012 completed in 0:00:06.939401

  7%|▋         | 279/4292 [49:43<7:35:57,  6.82s/it]

IN_13756_2012 completed in 0:00:07.432887

  7%|▋         | 280/4292 [49:50<7:48:53,  7.01s/it]

IN_15470_2012 completed in 0:00:07.466902

  7%|▋         | 281/4292 [49:55<7:11:45,  6.46s/it]

IN_17633_2012 completed in 0:00:05.165079

  7%|▋         | 282/4292 [50:01<6:46:07,  6.08s/it]

KS_10000_2012 completed in 0:00:05.184995

  7%|▋         | 283/4292 [50:06<6:32:51,  5.88s/it]

KS_10005_2012 completed in 0:00:05.419174

  7%|▋         | 284/4292 [50:14<7:23:38,  6.64s/it]

KS_22500_2012 completed in 0:00:08.414838

  7%|▋         | 285/4292 [50:24<8:29:14,  7.63s/it]

KY_10171_2012 completed in 0:00:09.920597

  7%|▋         | 286/4292 [50:33<8:40:01,  7.79s/it]

KY_11249_2012 completed in 0:00:08.168784

  7%|▋         | 287/4292 [50:38<8:02:04,  7.22s/it]

KY_19446_2012 completed in 0:00:05.899689

  7%|▋         | 288/4292 [50:46<8:02:24,  7.23s/it]

KY_22053_2012 completed in 0:00:07.243606

  7%|▋         | 289/4292 [50:51<7:27:41,  6.71s/it]

KY_49998_2012 completed in 0:00:05.499655

  7%|▋         | 290/4292 [51:05<9:56:49,  8.95s/it]

LA_11241_2012 completed in 0:00:14.168084

  7%|▋         | 291/4292 [51:11<8:41:25,  7.82s/it]

LA_13478_2012 completed in 0:00:05.184786

  7%|▋         | 292/4292 [51:18<8:30:12,  7.65s/it]

LA_17698_2012 completed in 0:00:07.264682

  7%|▋         | 293/4292 [51:25<8:16:51,  7.45s/it]

LA_55936_2012 completed in 0:00:06.990379

  7%|▋         | 294/4292 [51:30<7:32:53,  6.80s/it]

MA_6374_2012 completed in 0:00:05.261157

  7%|▋         | 295/4292 [51:38<7:53:50,  7.11s/it]

MA_11804_2012 completed in 0:00:07.849707

  7%|▋         | 296/4292 [51:44<7:38:37,  6.89s/it]

MA_13206_2012 completed in 0:00:06.355964

  7%|▋         | 297/4292 [51:52<7:54:18,  7.12s/it]

MA_20455_2012 completed in 0:00:07.671749

  7%|▋         | 298/4292 [51:58<7:40:40,  6.92s/it]

MD_1167_2012 completed in 0:00:06.446011

  7%|▋         | 299/4292 [52:05<7:32:50,  6.80s/it]

MD_5027_2012 completed in 0:00:06.532733

  7%|▋         | 300/4292 [52:12<7:34:21,  6.83s/it]

MD_15263_2012 completed in 0:00:06.885157

  7%|▋         | 301/4292 [52:19<7:48:42,  7.05s/it]

MD_15270_2012 completed in 0:00:07.553565

  7%|▋         | 302/4292 [52:27<7:50:45,  7.08s/it]

ME_3266_2012 completed in 0:00:07.154024

  7%|▋         | 303/4292 [52:33<7:36:27,  6.87s/it]

MI_392_2012 completed in 0:00:06.367085

  7%|▋         | 304/4292 [52:39<7:23:29,  6.67s/it]

MI_3828_2012 completed in 0:00:06.220163

  7%|▋         | 305/4292 [52:48<8:15:17,  7.45s/it]

MI_4254_2012 completed in 0:00:09.273572

  7%|▋         | 306/4292 [52:56<8:17:16,  7.49s/it]

MI_5109_2012 completed in 0:00:07.558176

  7%|▋         | 307/4292 [53:02<7:49:45,  7.07s/it]

MI_9324_2012 completed in 0:00:06.110115

  7%|▋         | 308/4292 [53:08<7:33:39,  6.83s/it]

MI_19578_2012 completed in 0:00:06.269581

  7%|▋         | 309/4292 [53:16<7:43:49,  6.99s/it]

MI_20847_2012 completed in 0:00:07.347729

  7%|▋         | 310/4292 [53:21<7:04:28,  6.40s/it]

MI_20860_2012 completed in 0:00:05.015853

  7%|▋         | 311/4292 [53:28<7:27:54,  6.75s/it]

MN_5574_2012 completed in 0:00:07.577751

  7%|▋         | 312/4292 [53:35<7:26:30,  6.73s/it]

MN_9417_2012 completed in 0:00:06.684374

  7%|▋         | 313/4292 [53:42<7:40:33,  6.94s/it]

MN_12647_2012 completed in 0:00:07.437480

  7%|▋         | 314/4292 [53:52<8:25:46,  7.63s/it]

MN_13781_2012 completed in 0:00:09.223331

  7%|▋         | 315/4292 [54:00<8:50:17,  8.00s/it]

MN_14232_2012 completed in 0:00:08.866664

  7%|▋         | 316/4292 [54:10<9:17:21,  8.41s/it]

MN_17267_2012 completed in 0:00:09.368279

  7%|▋         | 317/4292 [54:17<8:51:38,  8.02s/it]

MN_25177_2012 completed in 0:00:07.122873

  7%|▋         | 318/4292 [54:26<9:13:36,  8.36s/it]

MO_4675_2012 completed in 0:00:09.135609

  7%|▋         | 319/4292 [54:35<9:30:58,  8.62s/it]

MO_5860_2012 completed in 0:00:09.238524

  7%|▋         | 320/4292 [54:44<9:26:27,  8.56s/it]

MO_9231_2012 completed in 0:00:08.397152

  7%|▋         | 321/4292 [54:52<9:23:00,  8.51s/it]

MO_10000_2012 completed in 0:00:08.385376

  8%|▊         | 322/4292 [55:00<9:14:39,  8.38s/it]

MO_12698_2012 completed in 0:00:08.092636

  8%|▊         | 323/4292 [55:08<9:03:16,  8.21s/it]

MO_17833_2012 completed in 0:00:07.810140

  8%|▊         | 324/4292 [55:17<9:22:18,  8.50s/it]

MO_19436_2012 completed in 0:00:09.177894

  8%|▊         | 325/4292 [55:24<8:52:01,  8.05s/it]

MT_6395_2012 completed in 0:00:06.982063

  8%|▊         | 326/4292 [55:34<9:19:11,  8.46s/it]

MT_12692_2012 completed in 0:00:09.422476

  8%|▊         | 327/4292 [55:42<9:19:43,  8.47s/it]

MT_12825_2012 completed in 0:00:08.492332

  8%|▊         | 328/4292 [55:50<9:14:38,  8.40s/it]

MT_20997_2012 completed in 0:00:08.219368

  8%|▊         | 329/4292 [55:58<8:56:28,  8.12s/it]

NC_3046_2012 completed in 0:00:07.480578

  8%|▊         | 330/4292 [56:04<8:09:33,  7.41s/it]

NC_5416_2012 completed in 0:00:05.759555

  8%|▊         | 331/4292 [56:12<8:31:27,  7.75s/it]

NC_9837_2012 completed in 0:00:08.525312

  8%|▊         | 332/4292 [56:20<8:32:46,  7.77s/it]

NC_16496_2012 completed in 0:00:07.819351

  8%|▊         | 333/4292 [56:29<9:03:36,  8.24s/it]

NC_19876_2012 completed in 0:00:09.332311

  8%|▊         | 334/4292 [56:36<8:28:20,  7.71s/it]

NC_24889_2012 completed in 0:00:06.463189

  8%|▊         | 335/4292 [56:46<9:21:17,  8.51s/it]

ND_12087_2012 completed in 0:00:10.387732

  8%|▊         | 336/4292 [56:54<9:14:24,  8.41s/it]

ND_14232_2012 completed in 0:00:08.168937

  8%|▊         | 337/4292 [57:02<9:09:33,  8.34s/it]

ND_24949_2012 completed in 0:00:08.169509

  8%|▊         | 338/4292 [57:10<8:49:41,  8.04s/it]

NE_11018_2012 completed in 0:00:07.338358

  8%|▊         | 339/4292 [57:16<8:22:01,  7.62s/it]

NE_17642_2012 completed in 0:00:06.643065

  8%|▊         | 340/4292 [57:23<7:52:43,  7.18s/it]

NH_13441_2012 completed in 0:00:06.138188

  8%|▊         | 341/4292 [57:30<7:48:45,  7.12s/it]

NH_15472_2012 completed in 0:00:06.981142

  8%|▊         | 342/4292 [57:37<8:04:14,  7.36s/it]

NH_24590_2012 completed in 0:00:07.907728

  8%|▊         | 343/4292 [57:44<7:41:35,  7.01s/it]

NH_26510_2012 completed in 0:00:06.213375

  8%|▊         | 344/4292 [57:54<8:39:59,  7.90s/it]

NJ_963_2012 completed in 0:00:09.977240

  8%|▊         | 345/4292 [58:04<9:20:12,  8.52s/it]

NJ_9726_2012 completed in 0:00:09.945816

  8%|▊         | 346/4292 [58:16<10:36:57,  9.69s/it]

NJ_15477_2012 completed in 0:00:12.412439

  8%|▊         | 347/4292 [58:23<9:43:35,  8.88s/it]

NJ_16213_2012 completed in 0:00:06.986405

  8%|▊         | 348/4292 [58:30<9:11:37,  8.39s/it]

NM_5701_2012 completed in 0:00:07.261711

  8%|▊         | 349/4292 [58:40<9:28:03,  8.64s/it]

NM_6204_2012 completed in 0:00:09.227420

  8%|▊         | 350/4292 [58:52<10:40:10,  9.74s/it]

NM_11204_2012 completed in 0:00:12.309348

  8%|▊         | 351/4292 [59:03<11:03:42, 10.10s/it]

NM_17718_2012 completed in 0:00:10.945906

  8%|▊         | 352/4292 [59:12<10:55:25,  9.98s/it]

NM_22690_2012 completed in 0:00:09.691782

  8%|▊         | 353/4292 [59:23<11:09:31, 10.20s/it]

NV_2008_2012 completed in 0:00:10.704489

  8%|▊         | 354/4292 [59:32<10:45:56,  9.84s/it]

NV_13073_2012 completed in 0:00:09.008601

  8%|▊         | 355/4292 [59:43<10:55:42,  9.99s/it]

NV_13407_2012 completed in 0:00:10.344925

  8%|▊         | 356/4292 [59:54<11:18:32, 10.34s/it]

NV_17166_2012 completed in 0:00:11.160753

  8%|▊         | 357/4292 [1:00:04<11:15:46, 10.30s/it]

NV_19840_2012 completed in 0:00:10.211049

  8%|▊         | 358/4292 [1:00:13<10:57:58, 10.04s/it]

NY_3249_2012 completed in 0:00:09.406548

  8%|▊         | 359/4292 [1:00:27<12:08:58, 11.12s/it]

NY_13511_2012 completed in 0:00:13.653493

  8%|▊         | 360/4292 [1:00:35<11:17:11, 10.33s/it]

NY_14154_2012 completed in 0:00:08.495179

  8%|▊         | 361/4292 [1:00:48<11:51:26, 10.86s/it]

OH_3542_2012 completed in 0:00:12.084565

  8%|▊         | 362/4292 [1:00:58<11:42:49, 10.73s/it]

OH_3755_2012 completed in 0:00:10.428322

  8%|▊         | 363/4292 [1:01:08<11:21:01, 10.40s/it]

OH_4922_2012 completed in 0:00:09.624881

  8%|▊         | 364/4292 [1:01:18<11:29:50, 10.54s/it]

OH_13998_2012 completed in 0:00:10.857128

  9%|▊         | 365/4292 [1:01:30<11:49:41, 10.84s/it]

OH_14006_2012 completed in 0:00:11.555933

  9%|▊         | 366/4292 [1:01:39<11:17:22, 10.35s/it]

OH_18997_2012 completed in 0:00:09.205808

  9%|▊         | 367/4292 [1:01:48<10:41:04,  9.80s/it]

OK_13734_2012 completed in 0:00:08.510291

  9%|▊         | 368/4292 [1:01:59<11:05:34, 10.18s/it]

OK_14063_2012 completed in 0:00:11.050895

  9%|▊         | 369/4292 [1:02:08<10:48:25,  9.92s/it]

OK_15474_2012 completed in 0:00:09.310522

  9%|▊         | 370/4292 [1:02:15<9:55:49,  9.12s/it]

OR_6022_2012 completed in 0:00:07.242598

  9%|▊         | 371/4292 [1:02:26<10:27:34,  9.60s/it]

OR_9191_2012 completed in 0:00:10.741148

  9%|▊         | 372/4292 [1:02:40<11:48:44, 10.85s/it]

OR_14354_2012 completed in 0:00:13.752081

  9%|▊         | 373/4292 [1:02:51<11:45:39, 10.80s/it]

OR_15248_2012 completed in 0:00:10.698917

  9%|▊         | 374/4292 [1:03:01<11:40:40, 10.73s/it]

OR_40437_2012 completed in 0:00:10.557056

  9%|▊         | 375/4292 [1:03:13<12:13:04, 11.23s/it]

PA_3597_2012 completed in 0:00:12.387869

  9%|▉         | 376/4292 [1:03:23<11:30:43, 10.58s/it]

PA_5487_2012 completed in 0:00:09.070317

  9%|▉         | 377/4292 [1:03:36<12:29:14, 11.48s/it]

PA_12390_2012 completed in 0:00:13.580211

  9%|▉         | 378/4292 [1:03:45<11:37:31, 10.69s/it]

PA_14711_2012 completed in 0:00:08.848922

  9%|▉         | 379/4292 [1:03:57<12:07:28, 11.15s/it]

PA_14715_2012 completed in 0:00:12.231723

  9%|▉         | 380/4292 [1:04:05<11:10:26, 10.28s/it]

PA_14716_2012 completed in 0:00:08.246928

  9%|▉         | 381/4292 [1:04:15<10:59:18, 10.11s/it]

PA_14940_2012 completed in 0:00:09.718682

  9%|▉         | 382/4292 [1:04:26<11:13:05, 10.33s/it]

PA_15045_2012 completed in 0:00:10.827458

  9%|▉         | 383/4292 [1:04:34<10:19:31,  9.51s/it]

PA_19390_2012 completed in 0:00:07.595469

  9%|▉         | 384/4292 [1:04:43<10:18:27,  9.50s/it]

PA_20334_2012 completed in 0:00:09.461829

  9%|▉         | 385/4292 [1:04:52<10:12:17,  9.40s/it]

PA_20387_2012 completed in 0:00:09.186317

  9%|▉         | 386/4292 [1:05:00<9:42:11,  8.94s/it]

RI_1857_2012 completed in 0:00:07.865609

  9%|▉         | 387/4292 [1:05:09<9:40:45,  8.92s/it]

RI_13214_2012 completed in 0:00:08.876423

  9%|▉         | 388/4292 [1:05:21<10:30:24,  9.69s/it]

SC_3046_2012 completed in 0:00:11.473880

  9%|▉         | 389/4292 [1:05:31<10:37:12,  9.80s/it]

SC_5416_2012 completed in 0:00:10.044376

  9%|▉         | 390/4292 [1:05:42<11:11:01, 10.32s/it]

SC_17539_2012 completed in 0:00:11.536870

  9%|▉         | 391/4292 [1:05:51<10:34:07,  9.75s/it]

SC_17543_2012 completed in 0:00:08.432546

  9%|▉         | 392/4292 [1:06:01<10:43:21,  9.90s/it]

SD_1769_2012 completed in 0:00:10.233711

  9%|▉         | 393/4292 [1:06:09<10:11:07,  9.40s/it]

SD_14232_2012 completed in 0:00:08.252403

  9%|▉         | 394/4292 [1:06:23<11:35:12, 10.70s/it]

SD_20401_2012 completed in 0:00:13.725840

  9%|▉         | 395/4292 [1:06:33<11:35:22, 10.71s/it]

TN_10331_2012 completed in 0:00:10.717965

  9%|▉         | 396/4292 [1:06:43<11:14:34, 10.39s/it]

TX_5701_2012 completed in 0:00:09.646500

  9%|▉         | 397/4292 [1:06:56<12:04:20, 11.16s/it]

TX_16604_2012 completed in 0:00:12.952139

  9%|▉         | 398/4292 [1:07:06<11:33:49, 10.69s/it]

TX_17008_2012 completed in 0:00:09.594546

  9%|▉         | 399/4292 [1:07:18<11:59:06, 11.08s/it]

TX_17698_2012 completed in 0:00:11.998198

  9%|▉         | 400/4292 [1:07:28<11:47:05, 10.90s/it]

TX_55937_2012 completed in 0:00:10.474179

  9%|▉         | 401/4292 [1:07:39<11:45:29, 10.88s/it]

UT_2010_2012 completed in 0:00:10.827321

  9%|▉         | 402/4292 [1:07:51<12:04:27, 11.17s/it]

UT_14354_2012 completed in 0:00:11.862060

  9%|▉         | 403/4292 [1:08:01<11:36:29, 10.75s/it]

UT_15444_2012 completed in 0:00:09.744547

  9%|▉         | 404/4292 [1:08:12<11:47:21, 10.92s/it]

UT_17845_2012 completed in 0:00:11.313035

  9%|▉         | 405/4292 [1:08:25<12:35:57, 11.67s/it]

UT_17874_2012 completed in 0:00:13.424861

  9%|▉         | 406/4292 [1:08:44<14:54:43, 13.81s/it]

VA_733_2012 completed in 0:00:18.820236

  9%|▉         | 407/4292 [1:09:01<15:49:53, 14.67s/it]

VA_17066_2012 completed in 0:00:16.665553

 10%|▉         | 408/4292 [1:09:18<16:36:15, 15.39s/it]

VA_19876_2012 completed in 0:00:17.069807

 10%|▉         | 409/4292 [1:09:29<15:08:47, 14.04s/it]

VA_40228_2012 completed in 0:00:10.897111

 10%|▉         | 410/4292 [1:09:40<14:14:02, 13.20s/it]

VT_2548_2012 completed in 0:00:11.233314

 10%|▉         | 411/4292 [1:09:50<13:04:27, 12.13s/it]

VT_7601_2012 completed in 0:00:09.624465

 10%|▉         | 412/4292 [1:09:59<12:14:50, 11.36s/it]

VT_19791_2012 completed in 0:00:09.579843

 10%|▉         | 413/4292 [1:10:08<11:27:46, 10.64s/it]

WA_3660_2012 completed in 0:00:08.945537

 10%|▉         | 414/4292 [1:10:18<11:09:08, 10.35s/it]

WA_14354_2012 completed in 0:00:09.685559

 10%|▉         | 415/4292 [1:10:28<11:04:20, 10.28s/it]

WA_15500_2012 completed in 0:00:10.113212

 10%|▉         | 416/4292 [1:10:37<10:41:49,  9.94s/it]

WA_17470_2012 completed in 0:00:09.127353

 10%|▉         | 417/4292 [1:10:45<10:01:47,  9.32s/it]

WA_18429_2012 completed in 0:00:07.876558

 10%|▉         | 418/4292 [1:10:53<9:27:20,  8.79s/it]

WA_20169_2012 completed in 0:00:07.547193

 10%|▉         | 419/4292 [1:11:02<9:36:11,  8.93s/it]

WI_4715_2012 completed in 0:00:09.249753

 10%|▉         | 420/4292 [1:11:11<9:50:04,  9.14s/it]

WI_11479_2012 completed in 0:00:09.649888

 10%|▉         | 421/4292 [1:11:20<9:39:45,  8.99s/it]

WI_13697_2012 completed in 0:00:08.617932

 10%|▉         | 422/4292 [1:11:28<9:21:29,  8.71s/it]

WI_13815_2012 completed in 0:00:08.048756

 10%|▉         | 423/4292 [1:11:34<8:35:51,  8.00s/it]

WI_20847_2012 completed in 0:00:06.353420

 10%|▉         | 424/4292 [1:11:43<8:48:53,  8.20s/it]

WI_20856_2012 completed in 0:00:08.679205

 10%|▉         | 425/4292 [1:11:54<9:32:33,  8.88s/it]

WI_20860_2012 completed in 0:00:10.468902

 10%|▉         | 426/4292 [1:11:59<8:30:58,  7.93s/it]

WV_733_2012 completed in 0:00:05.704484

 10%|▉         | 427/4292 [1:12:08<8:44:17,  8.14s/it]

WV_12796_2012 completed in 0:00:08.625852

 10%|▉         | 428/4292 [1:12:13<7:40:32,  7.15s/it]

WV_20521_2012 completed in 0:00:04.845565

 10%|▉         | 429/4292 [1:12:17<6:52:52,  6.41s/it]

WY_3461_2012 completed in 0:00:04.688538

 10%|█         | 430/4292 [1:12:23<6:28:49,  6.04s/it]

WY_8566_2012 completed in 0:00:05.171850

 10%|█         | 431/4292 [1:12:30<6:56:16,  6.47s/it]

WY_14354_2012 completed in 0:00:07.467113

 10%|█         | 432/4292 [1:12:41<8:19:49,  7.77s/it]

WY_19156_2012 completed in 0:00:10.802488

 10%|█         | 433/4292 [1:12:46<7:22:12,  6.88s/it]

WY_27058_2012 completed in 0:00:04.788834

 10%|█         | 434/4292 [1:12:55<8:02:34,  7.51s/it]

AK_11824_2012 completed in 0:00:08.973770

 10%|█         | 435/4292 [1:13:00<7:30:25,  7.01s/it]

NY_16183_2012 completed in 0:00:05.843165

 10%|█         | 436/4292 [1:13:09<7:58:28,  7.45s/it]

AL_9094_2012 completed in 0:00:08.467417

 10%|█         | 437/4292 [1:13:20<9:09:27,  8.55s/it]

AL_9739_2012 completed in 0:00:11.133085

 10%|█         | 438/4292 [1:13:27<8:43:21,  8.15s/it]

GA_3408_2012 completed in 0:00:07.202011

 10%|█         | 439/4292 [1:13:33<7:53:28,  7.37s/it]

KY_14724_2012 completed in 0:00:05.564667

 10%|█         | 440/4292 [1:13:43<8:46:19,  8.20s/it]

KY_20130_2012 completed in 0:00:10.122583

 10%|█         | 441/4292 [1:13:52<8:57:27,  8.37s/it]

MS_6641_2012 completed in 0:00:08.783021

 10%|█         | 442/4292 [1:14:00<8:47:20,  8.22s/it]

TN_727_2012 completed in 0:00:07.854731

 10%|█         | 443/4292 [1:14:09<9:10:41,  8.58s/it]

TN_2247_2012 completed in 0:00:09.437124

 10%|█         | 444/4292 [1:14:19<9:36:12,  8.98s/it]

TN_3408_2012 completed in 0:00:09.917399

 10%|█         | 445/4292 [1:14:28<9:36:10,  8.99s/it]

TN_3812_2012 completed in 0:00:08.984786

 10%|█         | 446/4292 [1:14:36<9:11:12,  8.60s/it]

TN_4624_2012 completed in 0:00:07.694808

 10%|█         | 447/4292 [1:14:43<8:43:08,  8.16s/it]

TN_5399_2012 completed in 0:00:07.146028

 10%|█         | 448/4292 [1:14:51<8:48:49,  8.25s/it]

TN_7174_2012 completed in 0:00:08.459875

 10%|█         | 449/4292 [1:15:00<9:02:30,  8.47s/it]

TN_7625_2012 completed in 0:00:08.972981

 10%|█         | 450/4292 [1:15:10<9:28:03,  8.87s/it]

TN_9777_2012 completed in 0:00:09.806929

 11%|█         | 451/4292 [1:15:19<9:28:49,  8.89s/it]

TN_12470_2012 completed in 0:00:08.917811

 11%|█         | 452/4292 [1:15:28<9:30:43,  8.92s/it]

TN_13216_2012 completed in 0:00:08.986721

 11%|█         | 453/4292 [1:15:36<9:20:05,  8.75s/it]

TN_17694_2012 completed in 0:00:08.370054

 11%|█         | 454/4292 [1:15:45<9:11:14,  8.62s/it]

TN_19574_2012 completed in 0:00:08.299146

 11%|█         | 455/4292 [1:15:52<8:40:16,  8.14s/it]

TN_19898_2012 completed in 0:00:07.009682

 11%|█         | 456/4292 [1:16:00<8:47:14,  8.25s/it]

CT_20038_2012 completed in 0:00:08.505319

 11%|█         | 457/4292 [1:16:12<9:56:47,  9.34s/it]

AK_599_2013 completed in 0:00:11.880148

 11%|█         | 458/4292 [1:16:19<9:09:47,  8.60s/it]

AK_3522_2013 completed in 0:00:06.892637

 11%|█         | 459/4292 [1:16:27<8:59:05,  8.44s/it]

AK_7353_2013 completed in 0:00:08.051838

 11%|█         | 460/4292 [1:16:37<9:34:47,  9.00s/it]

AK_11824_2013 completed in 0:00:10.308903

 11%|█         | 461/4292 [1:16:43<8:34:54,  8.06s/it]

AK_19558_2013 completed in 0:00:05.880298

 11%|█         | 462/4292 [1:16:53<9:17:07,  8.73s/it]

AL_195_2013 completed in 0:00:10.274935

 11%|█         | 463/4292 [1:17:02<9:12:09,  8.65s/it]

AL_9094_2013 completed in 0:00:08.475525

 11%|█         | 464/4292 [1:17:10<8:58:49,  8.45s/it]

AL_9739_2013 completed in 0:00:07.961539

 11%|█         | 465/4292 [1:17:22<10:11:04,  9.58s/it]

AR_814_2013 completed in 0:00:12.222889

 11%|█         | 466/4292 [1:17:31<9:56:07,  9.35s/it]

AR_817_2013 completed in 0:00:08.806199

 11%|█         | 467/4292 [1:17:37<8:51:38,  8.34s/it]

AR_3093_2013 completed in 0:00:05.983919

 11%|█         | 468/4292 [1:17:43<8:02:25,  7.57s/it]

AR_6342_2013 completed in 0:00:05.771934

 11%|█         | 469/4292 [1:17:49<7:29:45,  7.06s/it]

AR_14063_2013 completed in 0:00:05.866197

 11%|█         | 470/4292 [1:18:02<9:26:38,  8.90s/it]

AR_17698_2013 completed in 0:00:13.180337

 11%|█         | 471/4292 [1:18:10<9:11:49,  8.67s/it]

AZ_803_2013 completed in 0:00:08.126641

 11%|█         | 472/4292 [1:18:20<9:31:17,  8.97s/it]

AZ_16572_2013 completed in 0:00:09.691381

 11%|█         | 473/4292 [1:18:34<11:13:59, 10.59s/it]

AZ_19189_2013 completed in 0:00:14.357982

 11%|█         | 474/4292 [1:18:41<9:59:26,  9.42s/it]

AZ_19728_2013 completed in 0:00:06.692449

 11%|█         | 475/4292 [1:18:50<9:49:00,  9.26s/it]

AZ_21538_2013 completed in 0:00:08.881176

 11%|█         | 476/4292 [1:18:58<9:31:23,  8.98s/it]

AZ_24211_2013 completed in 0:00:08.342336

 11%|█         | 477/4292 [1:19:07<9:39:05,  9.11s/it]

CA_9216_2013 completed in 0:00:09.393968

 11%|█         | 478/4292 [1:19:16<9:38:21,  9.10s/it]

CA_11208_2013 completed in 0:00:09.076643

 11%|█         | 479/4292 [1:19:23<8:50:43,  8.35s/it]

CA_12745_2013 completed in 0:00:06.606606

 11%|█         | 480/4292 [1:19:41<12:02:59, 11.38s/it]

CA_14328_2013 completed in 0:00:18.445189

 11%|█         | 481/4292 [1:19:49<10:49:01, 10.22s/it]

CA_14354_2013 completed in 0:00:07.507257

 11%|█         | 482/4292 [1:19:56<9:48:22,  9.27s/it]

CA_14534_2013 completed in 0:00:07.042280

 11%|█▏        | 483/4292 [1:20:02<8:46:19,  8.29s/it]

CA_16534_2013 completed in 0:00:06.015051

 11%|█▏        | 484/4292 [1:20:11<9:01:48,  8.54s/it]

CA_16609_2013 completed in 0:00:09.105920

 11%|█▏        | 485/4292 [1:20:26<11:02:47, 10.45s/it]

CA_17609_2013 completed in 0:00:14.898835

 11%|█▏        | 486/4292 [1:20:38<11:32:45, 10.92s/it]

CA_18260_2013 completed in 0:00:12.029507

 11%|█▏        | 487/4292 [1:20:54<13:16:46, 12.56s/it]

CA_19281_2013 completed in 0:00:16.396955

 11%|█▏        | 488/4292 [1:21:11<14:39:31, 13.87s/it]

CO_3989_2013 completed in 0:00:16.924760

 11%|█▏        | 489/4292 [1:21:18<12:21:31, 11.70s/it]

CO_6604_2013 completed in 0:00:06.626370

 11%|█▏        | 490/4292 [1:21:24<10:35:38, 10.03s/it]

CO_9336_2013 completed in 0:00:06.134518

 11%|█▏        | 491/4292 [1:21:36<11:17:10, 10.69s/it]

CO_12866_2013 completed in 0:00:12.224748

 11%|█▏        | 492/4292 [1:21:46<11:03:08, 10.47s/it]

CO_15257_2013 completed in 0:00:09.959087

 11%|█▏        | 493/4292 [1:21:56<10:58:13, 10.40s/it]

CO_15466_2013 completed in 0:00:10.219959

 12%|█▏        | 494/4292 [1:22:04<10:00:14,  9.48s/it]

CO_16603_2013 completed in 0:00:07.350412

 12%|█▏        | 495/4292 [1:22:15<10:30:17,  9.96s/it]

CO_19499_2013 completed in 0:00:11.072690

 12%|█▏        | 496/4292 [1:22:23<9:46:40,  9.27s/it]

CO_27058_2013 completed in 0:00:07.669743

 12%|█▏        | 497/4292 [1:22:32<9:54:15,  9.40s/it]

CT_4176_2013 completed in 0:00:09.680062

 12%|█▏        | 498/4292 [1:22:45<11:01:17, 10.46s/it]

CT_19497_2013 completed in 0:00:12.935963

 12%|█▏        | 499/4292 [1:22:55<10:56:04, 10.38s/it]

CT_20038_2013 completed in 0:00:10.191513

 12%|█▏        | 500/4292 [1:23:08<11:43:52, 11.14s/it]

DC_15270_2013 completed in 0:00:12.906994

 12%|█▏        | 501/4292 [1:23:22<12:36:06, 11.97s/it]

DE_5027_2013 completed in 0:00:13.899241

 12%|█▏        | 502/4292 [1:23:32<11:53:36, 11.30s/it]

DE_5070_2013 completed in 0:00:09.730184

 12%|█▏        | 503/4292 [1:23:42<11:37:59, 11.05s/it]

DE_5335_2013 completed in 0:00:10.481104

/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_nanfunctions_impl.py:1231: RuntimeWarning: Mean of empty slice

DE_13519_2013 completed in 0:00:09.531026

 12%|█▏        | 505/4292 [1:24:04<11:43:03, 11.14s/it]

FL_6452_2013 completed in 0:00:12.402949

 12%|█▏        | 506/4292 [1:24:16<11:51:59, 11.28s/it]

FL_6455_2013 completed in 0:00:11.619805

 12%|█▏        | 507/4292 [1:24:25<11:05:51, 10.56s/it]

FL_6457_2013 completed in 0:00:08.855485

 12%|█▏        | 508/4292 [1:24:34<10:46:55, 10.26s/it]

FL_7801_2013 completed in 0:00:09.562598

 12%|█▏        | 509/4292 [1:24:44<10:28:16,  9.96s/it]

FL_9617_2013 completed in 0:00:09.275670

 12%|█▏        | 510/4292 [1:24:52<10:03:53,  9.58s/it]

FL_18454_2013 completed in 0:00:08.683208

 12%|█▏        | 511/4292 [1:25:01<9:41:47,  9.23s/it]

GA_3408_2013 completed in 0:00:08.419046

 12%|█▏        | 512/4292 [1:25:09<9:26:49,  9.00s/it]

GA_3916_2013 completed in 0:00:08.447249

 12%|█▏        | 513/4292 [1:25:20<9:51:00,  9.38s/it]

GA_7140_2013 completed in 0:00:10.280609

 12%|█▏        | 514/4292 [1:25:27<9:13:37,  8.79s/it]

HI_8287_2013 completed in 0:00:07.411006

 12%|█▏        | 515/4292 [1:25:36<9:27:35,  9.02s/it]

HI_10071_2013 completed in 0:00:09.539173

 12%|█▏        | 516/4292 [1:25:45<9:12:31,  8.78s/it]

HI_11843_2013 completed in 0:00:08.225477

 12%|█▏        | 517/4292 [1:25:55<9:44:42,  9.29s/it]

HI_19547_2013 completed in 0:00:10.491159

 12%|█▏        | 518/4292 [1:26:03<9:16:09,  8.84s/it]

IA_9417_2013 completed in 0:00:07.787909

 12%|█▏        | 519/4292 [1:26:16<10:35:28, 10.11s/it]

IA_12341_2013 completed in 0:00:13.053468

 12%|█▏        | 520/4292 [1:26:25<10:20:25,  9.87s/it]

ID_9191_2013 completed in 0:00:09.315309

 12%|█▏        | 521/4292 [1:26:40<11:49:24, 11.29s/it]

ID_10454_2013 completed in 0:00:14.596052

 12%|█▏        | 522/4292 [1:26:47<10:20:52,  9.88s/it]

ID_11273_2013 completed in 0:00:06.599834

 12%|█▏        | 523/4292 [1:26:55<10:02:45,  9.60s/it]

ID_14354_2013 completed in 0:00:08.927660

 12%|█▏        | 524/4292 [1:27:01<8:54:24,  8.51s/it]

ID_20169_2013 completed in 0:00:05.975464

 12%|█▏        | 525/4292 [1:27:09<8:38:36,  8.26s/it]

IL_4110_2013 completed in 0:00:07.677297

 12%|█▏        | 526/4292 [1:27:15<7:48:07,  7.46s/it]

IL_12341_2013 completed in 0:00:05.585680

 12%|█▏        | 527/4292 [1:27:21<7:34:35,  7.24s/it]

IL_13032_2013 completed in 0:00:06.740675

 12%|█▏        | 528/4292 [1:27:27<7:01:06,  6.71s/it]

IN_9273_2013 completed in 0:00:05.470701

 12%|█▏        | 529/4292 [1:27:33<6:57:21,  6.65s/it]

IN_9324_2013 completed in 0:00:06.513777

 12%|█▏        | 530/4292 [1:27:41<7:07:32,  6.82s/it]

IN_13756_2013 completed in 0:00:07.201099

 12%|█▏        | 531/4292 [1:27:51<8:06:18,  7.76s/it]

IN_15470_2013 completed in 0:00:09.949134

 12%|█▏        | 532/4292 [1:27:57<7:50:09,  7.50s/it]

IN_17633_2013 completed in 0:00:06.903804

 12%|█▏        | 533/4292 [1:28:06<8:11:10,  7.84s/it]

KS_9996_2013 completed in 0:00:08.624902

 12%|█▏        | 534/4292 [1:28:16<8:49:38,  8.46s/it]

KS_10000_2013 completed in 0:00:09.892959

 12%|█▏        | 535/4292 [1:28:23<8:28:07,  8.11s/it]

KS_10005_2013 completed in 0:00:07.312695

 12%|█▏        | 536/4292 [1:28:34<9:15:48,  8.88s/it]

KS_22500_2013 completed in 0:00:10.660617

 13%|█▎        | 537/4292 [1:28:41<8:43:26,  8.36s/it]

KY_9964_2013 completed in 0:00:07.160606

 13%|█▎        | 538/4292 [1:28:51<9:14:34,  8.86s/it]

KY_10171_2013 completed in 0:00:10.029365

 13%|█▎        | 539/4292 [1:29:00<9:06:58,  8.74s/it]

KY_11249_2013 completed in 0:00:08.464794

 13%|█▎        | 540/4292 [1:29:13<10:27:57, 10.04s/it]

KY_14724_2013 completed in 0:00:13.068635

 13%|█▎        | 541/4292 [1:29:21<9:59:28,  9.59s/it]

KY_19446_2013 completed in 0:00:08.531633

 13%|█▎        | 542/4292 [1:29:29<9:25:07,  9.04s/it]

KY_20130_2013 completed in 0:00:07.764335

 13%|█▎        | 543/4292 [1:29:36<8:53:35,  8.54s/it]

KY_22053_2013 completed in 0:00:07.366525

 13%|█▎        | 544/4292 [1:29:46<9:04:35,  8.72s/it]

KY_49998_2013 completed in 0:00:09.133076

 13%|█▎        | 545/4292 [1:29:54<8:52:44,  8.53s/it]

LA_3265_2013 completed in 0:00:08.092395

 13%|█▎        | 546/4292 [1:30:04<9:26:42,  9.08s/it]

LA_11241_2013 completed in 0:00:10.350523

 13%|█▎        | 547/4292 [1:30:11<8:57:06,  8.61s/it]

LA_13478_2013 completed in 0:00:07.503531

 13%|█▎        | 548/4292 [1:30:23<9:45:22,  9.38s/it]

LA_17698_2013 completed in 0:00:11.190113

 13%|█▎        | 549/4292 [1:30:30<9:02:10,  8.69s/it]

LA_55936_2013 completed in 0:00:07.080023

 13%|█▎        | 550/4292 [1:30:38<9:01:58,  8.69s/it]

MA_6374_2013 completed in 0:00:08.687390

 13%|█▎        | 551/4292 [1:30:47<9:00:33,  8.67s/it]

MA_8774_2013 completed in 0:00:08.620898

 13%|█▎        | 552/4292 [1:30:57<9:28:54,  9.13s/it]

MA_11804_2013 completed in 0:00:10.192439

 13%|█▎        | 553/4292 [1:31:04<8:51:33,  8.53s/it]

MA_13206_2013 completed in 0:00:07.136755

 13%|█▎        | 554/4292 [1:31:13<8:56:56,  8.62s/it]

MA_15748_2013 completed in 0:00:08.824522

 13%|█▎        | 555/4292 [1:31:22<8:59:12,  8.66s/it]

MA_20455_2013 completed in 0:00:08.747048

 13%|█▎        | 556/4292 [1:31:30<8:48:18,  8.48s/it]

MA_54913_2013 completed in 0:00:08.080511

 13%|█▎        | 557/4292 [1:31:38<8:30:09,  8.20s/it]

MD_84_2013 completed in 0:00:07.519614

 13%|█▎        | 558/4292 [1:31:45<8:11:01,  7.89s/it]

MD_1167_2013 completed in 0:00:07.177021

 13%|█▎        | 559/4292 [1:31:52<8:04:56,  7.79s/it]

MD_5027_2013 completed in 0:00:07.565618

 13%|█▎        | 560/4292 [1:31:59<7:41:25,  7.42s/it]

MD_15263_2013 completed in 0:00:06.539930

 13%|█▎        | 561/4292 [1:32:06<7:32:39,  7.28s/it]

MD_15270_2013 completed in 0:00:06.953878

 13%|█▎        | 562/4292 [1:32:14<7:40:36,  7.41s/it]

ME_1179_2013 completed in 0:00:07.711554

 13%|█▎        | 563/4292 [1:32:20<7:19:47,  7.08s/it]

ME_3266_2013 completed in 0:00:06.299005

 13%|█▎        | 564/4292 [1:32:32<8:51:56,  8.56s/it]

ME_11522_2013 completed in 0:00:12.025313

 13%|█▎        | 565/4292 [1:32:38<8:03:25,  7.78s/it]

MI_392_2013 completed in 0:00:05.963582

 13%|█▎        | 566/4292 [1:32:45<7:57:57,  7.70s/it]

MI_3828_2013 completed in 0:00:07.494845

 13%|█▎        | 567/4292 [1:32:56<8:49:30,  8.53s/it]

MI_4254_2013 completed in 0:00:10.467318

 13%|█▎        | 568/4292 [1:33:03<8:21:36,  8.08s/it]

MI_5109_2013 completed in 0:00:07.037194

 13%|█▎        | 569/4292 [1:33:10<8:05:46,  7.83s/it]

MI_9324_2013 completed in 0:00:07.237812

 13%|█▎        | 570/4292 [1:33:20<8:43:44,  8.44s/it]

MI_19578_2013 completed in 0:00:09.870663

 13%|█▎        | 571/4292 [1:33:27<8:10:16,  7.91s/it]

MI_20847_2013 completed in 0:00:06.651057

 13%|█▎        | 572/4292 [1:33:34<8:04:07,  7.81s/it]

MI_20860_2013 completed in 0:00:07.577772

 13%|█▎        | 573/4292 [1:33:42<7:56:50,  7.69s/it]

MN_689_2013 completed in 0:00:07.422474

 13%|█▎        | 574/4292 [1:34:05<12:47:03, 12.38s/it]

MN_5574_2013 completed in 0:00:23.310431

 13%|█▎        | 575/4292 [1:34:13<11:29:46, 11.13s/it]

MN_9417_2013 completed in 0:00:08.230029

 13%|█▎        | 576/4292 [1:34:21<10:29:21, 10.16s/it]

MN_12647_2013 completed in 0:00:07.892020

 13%|█▎        | 577/4292 [1:34:29<9:57:24,  9.65s/it]

MN_13781_2013 completed in 0:00:08.449581

 13%|█▎        | 578/4292 [1:34:37<9:25:04,  9.13s/it]

MN_14232_2013 completed in 0:00:07.915633

 13%|█▎        | 579/4292 [1:34:46<9:21:49,  9.08s/it]

MN_17267_2013 completed in 0:00:08.961078

 14%|█▎        | 580/4292 [1:34:55<9:15:23,  8.98s/it]

MN_20996_2013 completed in 0:00:08.739617

 14%|█▎        | 581/4292 [1:35:04<9:12:25,  8.93s/it]

MN_25177_2013 completed in 0:00:08.824427

 14%|█▎        | 582/4292 [1:35:13<9:15:51,  8.99s/it]

MO_4675_2013 completed in 0:00:09.123275

 14%|█▎        | 583/4292 [1:35:20<8:43:33,  8.47s/it]

MO_5860_2013 completed in 0:00:07.252462

 14%|█▎        | 584/4292 [1:35:28<8:34:24,  8.32s/it]

MO_9231_2013 completed in 0:00:07.982899

 14%|█▎        | 585/4292 [1:35:37<8:37:24,  8.37s/it]

MO_10000_2013 completed in 0:00:08.492106

 14%|█▎        | 586/4292 [1:35:45<8:36:47,  8.37s/it]

MO_12698_2013 completed in 0:00:08.348488

 14%|█▎        | 587/4292 [1:35:53<8:35:50,  8.35s/it]

MO_17833_2013 completed in 0:00:08.321699

 14%|█▎        | 588/4292 [1:36:03<8:52:22,  8.62s/it]

MO_19436_2013 completed in 0:00:09.252967

 14%|█▎        | 589/4292 [1:36:09<8:09:28,  7.93s/it]

MS_6641_2013 completed in 0:00:06.309712

 14%|█▎        | 590/4292 [1:36:18<8:32:35,  8.31s/it]

MS_17647_2013 completed in 0:00:09.186088

 14%|█▍        | 591/4292 [1:36:25<8:03:47,  7.84s/it]

MT_6395_2013 completed in 0:00:06.757535

 14%|█▍        | 592/4292 [1:36:35<8:40:45,  8.44s/it]

MT_12692_2013 completed in 0:00:09.848108

 14%|█▍        | 593/4292 [1:36:42<8:15:13,  8.03s/it]

MT_12825_2013 completed in 0:00:07.071150

 14%|█▍        | 594/4292 [1:36:53<9:18:25,  9.06s/it]

MT_19603_2013 completed in 0:00:11.456949

 14%|█▍        | 595/4292 [1:36:59<8:14:00,  8.02s/it]

MT_20997_2013 completed in 0:00:05.582246

 14%|█▍        | 596/4292 [1:37:07<8:22:43,  8.16s/it]

NC_3046_2013 completed in 0:00:08.495949

 14%|█▍        | 597/4292 [1:37:14<7:58:16,  7.77s/it]

NC_5416_2013 completed in 0:00:06.843559

 14%|█▍        | 598/4292 [1:37:20<7:22:27,  7.19s/it]

NC_9837_2013 completed in 0:00:05.832706

 14%|█▍        | 599/4292 [1:37:28<7:28:20,  7.28s/it]

NC_16496_2013 completed in 0:00:07.511284

 14%|█▍        | 600/4292 [1:37:33<6:46:37,  6.61s/it]

NC_19876_2013 completed in 0:00:05.029821

 14%|█▍        | 601/4292 [1:37:39<6:49:50,  6.66s/it]

NC_24889_2013 completed in 0:00:06.787509

 14%|█▍        | 602/4292 [1:37:46<6:50:50,  6.68s/it]

ND_12087_2013 completed in 0:00:06.721759

 14%|█▍        | 603/4292 [1:37:53<6:48:01,  6.64s/it]

ND_12301_2013 completed in 0:00:06.532362

 14%|█▍        | 604/4292 [1:37:58<6:29:57,  6.34s/it]

ND_14232_2013 completed in 0:00:05.662069

 14%|█▍        | 605/4292 [1:38:05<6:40:12,  6.51s/it]

ND_19790_2013 completed in 0:00:06.905204

 14%|█▍        | 606/4292 [1:38:13<7:03:38,  6.90s/it]

ND_24949_2013 completed in 0:00:07.788541

 14%|█▍        | 607/4292 [1:38:20<7:10:40,  7.01s/it]

NE_4373_2013 completed in 0:00:07.282809

 14%|█▍        | 608/4292 [1:38:27<7:03:12,  6.89s/it]

NE_11018_2013 completed in 0:00:06.612473

 14%|█▍        | 609/4292 [1:38:34<7:11:21,  7.03s/it]

NE_11251_2013 completed in 0:00:07.340144

 14%|█▍        | 610/4292 [1:38:40<6:43:10,  6.57s/it]

NE_13337_2013 completed in 0:00:05.502538

 14%|█▍        | 611/4292 [1:38:47<6:59:07,  6.83s/it]

NE_13664_2013 completed in 0:00:07.441356

 14%|█▍        | 612/4292 [1:38:54<7:03:57,  6.91s/it]

NE_14127_2013 completed in 0:00:07.099290

 14%|█▍        | 613/4292 [1:39:02<7:13:17,  7.07s/it]

NE_17642_2013 completed in 0:00:07.424186

 14%|█▍        | 614/4292 [1:39:10<7:36:25,  7.45s/it]

NH_13441_2013 completed in 0:00:08.330020

 14%|█▍        | 615/4292 [1:39:17<7:30:44,  7.36s/it]

NH_15472_2013 completed in 0:00:07.142650

 14%|█▍        | 616/4292 [1:39:25<7:41:44,  7.54s/it]

NH_24590_2013 completed in 0:00:07.959695

 14%|█▍        | 617/4292 [1:39:32<7:22:39,  7.23s/it]

NH_26510_2013 completed in 0:00:06.503101

 14%|█▍        | 618/4292 [1:39:39<7:32:36,  7.39s/it]

NJ_963_2013 completed in 0:00:07.769344

 14%|█▍        | 619/4292 [1:39:47<7:35:57,  7.45s/it]

NJ_9726_2013 completed in 0:00:07.580132

 14%|█▍        | 620/4292 [1:39:54<7:33:22,  7.41s/it]

NJ_15477_2013 completed in 0:00:07.313523

 14%|█▍        | 621/4292 [1:40:02<7:42:59,  7.57s/it]

NJ_16213_2013 completed in 0:00:07.937373

 14%|█▍        | 622/4292 [1:40:11<8:08:46,  7.99s/it]

NM_3287_2013 completed in 0:00:08.978965

 15%|█▍        | 623/4292 [1:40:20<8:19:48,  8.17s/it]

NM_5701_2013 completed in 0:00:08.597900

 15%|█▍        | 624/4292 [1:40:29<8:28:49,  8.32s/it]

NM_6204_2013 completed in 0:00:08.671681

 15%|█▍        | 625/4292 [1:40:37<8:32:12,  8.38s/it]

NM_11204_2013 completed in 0:00:08.514283

 15%|█▍        | 626/4292 [1:40:46<8:45:41,  8.60s/it]

NM_15473_2013 completed in 0:00:09.123067

 15%|█▍        | 627/4292 [1:40:54<8:37:48,  8.48s/it]

NM_17718_2013 completed in 0:00:08.176657

 15%|█▍        | 628/4292 [1:41:03<8:42:24,  8.55s/it]

NM_22690_2013 completed in 0:00:08.735000

 15%|█▍        | 629/4292 [1:41:12<8:56:57,  8.80s/it]

NV_2008_2013 completed in 0:00:09.356264

 15%|█▍        | 630/4292 [1:41:21<8:51:38,  8.71s/it]

NV_13073_2013 completed in 0:00:08.511956

 15%|█▍        | 631/4292 [1:41:30<8:49:44,  8.68s/it]

NV_13407_2013 completed in 0:00:08.614182

 15%|█▍        | 632/4292 [1:41:39<9:10:12,  9.02s/it]

NV_17166_2013 completed in 0:00:09.807459

 15%|█▍        | 633/4292 [1:41:48<9:04:21,  8.93s/it]

NV_19840_2013 completed in 0:00:08.707039

 15%|█▍        | 634/4292 [1:42:00<10:05:31,  9.93s/it]

NY_3249_2013 completed in 0:00:12.272930

 15%|█▍        | 635/4292 [1:42:09<9:46:12,  9.62s/it]

NY_4226_2013 completed in 0:00:08.879387

 15%|█▍        | 636/4292 [1:42:21<10:20:02, 10.18s/it]

NY_11171_2013 completed in 0:00:11.475714

 15%|█▍        | 637/4292 [1:42:30<10:04:50,  9.93s/it]

NY_13511_2013 completed in 0:00:09.351972

 15%|█▍        | 638/4292 [1:42:48<12:34:12, 12.38s/it]

NY_13573_2013 completed in 0:00:18.112792

 15%|█▍        | 639/4292 [1:42:57<11:24:47, 11.25s/it]

NY_14154_2013 completed in 0:00:08.588975

 15%|█▍        | 640/4292 [1:43:06<10:39:22, 10.50s/it]

NY_16183_2013 completed in 0:00:08.769334

 15%|█▍        | 641/4292 [1:43:13<9:41:40,  9.56s/it]

OH_3542_2013 completed in 0:00:07.352237

 15%|█▍        | 642/4292 [1:43:22<9:25:15,  9.29s/it]

OH_3755_2013 completed in 0:00:08.666819

 15%|█▍        | 643/4292 [1:43:32<9:47:37,  9.66s/it]

OH_4922_2013 completed in 0:00:10.525846

 15%|█▌        | 644/4292 [1:43:38<8:35:39,  8.48s/it]

OH_13998_2013 completed in 0:00:05.724281

 15%|█▌        | 645/4292 [1:43:45<8:13:58,  8.13s/it]

OH_14006_2013 completed in 0:00:07.294018

 15%|█▌        | 646/4292 [1:43:50<7:21:26,  7.26s/it]

OH_18997_2013 completed in 0:00:05.251474

 15%|█▌        | 647/4292 [1:43:58<7:30:10,  7.41s/it]

OK_13734_2013 completed in 0:00:07.745821

 15%|█▌        | 648/4292 [1:44:04<6:58:11,  6.89s/it]

OK_14062_2013 completed in 0:00:05.660102

 15%|█▌        | 649/4292 [1:44:12<7:15:38,  7.17s/it]

OK_14063_2013 completed in 0:00:07.843963

 15%|█▌        | 650/4292 [1:44:19<7:19:35,  7.24s/it]

OK_15474_2013 completed in 0:00:07.397414

 15%|█▌        | 651/4292 [1:44:26<7:18:13,  7.22s/it]

OK_19785_2013 completed in 0:00:07.173412

 15%|█▌        | 652/4292 [1:44:34<7:28:06,  7.39s/it]

OR_6022_2013 completed in 0:00:07.769876

 15%|█▌        | 653/4292 [1:44:40<7:10:32,  7.10s/it]

OR_9191_2013 completed in 0:00:06.426873

 15%|█▌        | 654/4292 [1:44:48<7:14:39,  7.17s/it]

OR_14354_2013 completed in 0:00:07.330373

 15%|█▌        | 655/4292 [1:44:54<7:05:59,  7.03s/it]

OR_15248_2013 completed in 0:00:06.697877

 15%|█▌        | 656/4292 [1:45:02<7:22:27,  7.30s/it]

OR_18260_2013 completed in 0:00:07.938594

 15%|█▌        | 657/4292 [1:45:10<7:23:58,  7.33s/it]

OR_40437_2013 completed in 0:00:07.390968

 15%|█▌        | 658/4292 [1:45:20<8:08:45,  8.07s/it]

PA_3597_2013 completed in 0:00:09.798540

 15%|█▌        | 659/4292 [1:45:27<8:00:08,  7.93s/it]

PA_5487_2013 completed in 0:00:07.602152

 15%|█▌        | 660/4292 [1:45:35<7:55:15,  7.85s/it]

PA_12390_2013 completed in 0:00:07.666956

 15%|█▌        | 661/4292 [1:45:43<7:54:59,  7.85s/it]

PA_14711_2013 completed in 0:00:07.842844

 15%|█▌        | 662/4292 [1:45:52<8:20:30,  8.27s/it]

PA_14715_2013 completed in 0:00:09.260990

 15%|█▌        | 663/4292 [1:46:00<8:21:51,  8.30s/it]

PA_14716_2013 completed in 0:00:08.354096

 15%|█▌        | 664/4292 [1:46:08<8:11:13,  8.12s/it]

PA_14940_2013 completed in 0:00:07.718141

 15%|█▌        | 665/4292 [1:46:15<7:45:03,  7.69s/it]

PA_15045_2013 completed in 0:00:06.687489

 16%|█▌        | 666/4292 [1:46:23<7:54:22,  7.85s/it]

PA_19390_2013 completed in 0:00:08.213000

 16%|█▌        | 667/4292 [1:46:31<7:59:27,  7.94s/it]

PA_20334_2013 completed in 0:00:08.136401

 16%|█▌        | 668/4292 [1:46:42<8:47:29,  8.73s/it]

PA_20387_2013 completed in 0:00:10.592515

 16%|█▌        | 669/4292 [1:46:48<7:58:12,  7.92s/it]

RI_1857_2013 completed in 0:00:06.020416

 16%|█▌        | 670/4292 [1:46:54<7:29:17,  7.44s/it]

RI_13214_2013 completed in 0:00:06.328554

 16%|█▌        | 671/4292 [1:47:01<7:23:00,  7.34s/it]

SC_1613_2013 completed in 0:00:07.101420

 16%|█▌        | 672/4292 [1:47:11<8:01:16,  7.98s/it]

SC_3046_2013 completed in 0:00:09.461092

 16%|█▌        | 673/4292 [1:47:23<9:22:02,  9.32s/it]

SC_5416_2013 completed in 0:00:12.447316

 16%|█▌        | 674/4292 [1:47:32<9:21:12,  9.31s/it]

SC_14398_2013 completed in 0:00:09.279512

 16%|█▌        | 675/4292 [1:47:40<8:45:40,  8.72s/it]

SC_17539_2013 completed in 0:00:07.345354

 16%|█▌        | 676/4292 [1:47:46<7:56:15,  7.90s/it]

SC_17543_2013 completed in 0:00:05.993299

 16%|█▌        | 677/4292 [1:47:51<7:15:10,  7.22s/it]

SD_1769_2013 completed in 0:00:05.636246

 16%|█▌        | 678/4292 [1:47:58<7:13:44,  7.20s/it]

SD_13337_2013 completed in 0:00:07.148960

 16%|█▌        | 679/4292 [1:48:05<6:58:31,  6.95s/it]

SD_14232_2013 completed in 0:00:06.364493

 16%|█▌        | 680/4292 [1:48:11<6:45:57,  6.74s/it]

SD_19293_2013 completed in 0:00:06.260383

 16%|█▌        | 681/4292 [1:48:19<7:01:32,  7.00s/it]

SD_20401_2013 completed in 0:00:07.611976

 16%|█▌        | 682/4292 [1:48:26<6:57:59,  6.95s/it]

TN_727_2013 completed in 0:00:06.812654

 16%|█▌        | 683/4292 [1:48:35<7:36:45,  7.59s/it]

TN_2247_2013 completed in 0:00:09.101330

 16%|█▌        | 684/4292 [1:48:42<7:40:33,  7.66s/it]

TN_3408_2013 completed in 0:00:07.805499

 16%|█▌        | 685/4292 [1:48:48<7:03:32,  7.05s/it]

TN_3812_2013 completed in 0:00:05.612885

 16%|█▌        | 686/4292 [1:48:55<6:56:27,  6.93s/it]

TN_4624_2013 completed in 0:00:06.658044

 16%|█▌        | 687/4292 [1:49:03<7:13:45,  7.22s/it]

TN_5399_2013 completed in 0:00:07.894567

 16%|█▌        | 688/4292 [1:49:09<6:53:27,  6.88s/it]

TN_7174_2013 completed in 0:00:06.098552

 16%|█▌        | 689/4292 [1:49:15<6:37:20,  6.62s/it]

TN_7625_2013 completed in 0:00:05.994665

 16%|█▌        | 690/4292 [1:49:20<6:18:07,  6.30s/it]

TN_9777_2013 completed in 0:00:05.554815

 16%|█▌        | 691/4292 [1:49:26<6:02:56,  6.05s/it]

TN_10331_2013 completed in 0:00:05.459882

 16%|█▌        | 692/4292 [1:49:33<6:19:58,  6.33s/it]

TN_12470_2013 completed in 0:00:06.998439

 16%|█▌        | 693/4292 [1:49:42<7:08:50,  7.15s/it]

TN_13216_2013 completed in 0:00:09.053953

 16%|█▌        | 694/4292 [1:49:51<7:43:03,  7.72s/it]

TN_17694_2013 completed in 0:00:09.056638

 16%|█▌        | 695/4292 [1:49:58<7:39:07,  7.66s/it]

TN_19574_2013 completed in 0:00:07.510083

 16%|█▌        | 696/4292 [1:50:05<7:23:39,  7.40s/it]

TN_19898_2013 completed in 0:00:06.803806

 16%|█▌        | 697/4292 [1:50:11<6:57:21,  6.97s/it]

TX_5701_2013 completed in 0:00:05.945427

 16%|█▋        | 698/4292 [1:50:18<7:04:57,  7.09s/it]

TX_16604_2013 completed in 0:00:07.392026

 16%|█▋        | 699/4292 [1:50:25<6:52:57,  6.90s/it]

TX_17008_2013 completed in 0:00:06.432390

 16%|█▋        | 700/4292 [1:50:33<7:07:12,  7.14s/it]

TX_17698_2013 completed in 0:00:07.691073

 16%|█▋        | 701/4292 [1:50:39<6:58:48,  7.00s/it]

TX_55937_2013 completed in 0:00:06.673550

 16%|█▋        | 702/4292 [1:50:46<6:48:08,  6.82s/it]

UT_2010_2013 completed in 0:00:06.408739

 16%|█▋        | 703/4292 [1:50:52<6:30:40,  6.53s/it]

UT_12866_2013 completed in 0:00:05.853572

 16%|█▋        | 704/4292 [1:50:59<6:39:08,  6.67s/it]

UT_14354_2013 completed in 0:00:07.008668

 16%|█▋        | 705/4292 [1:51:05<6:38:33,  6.67s/it]

UT_15444_2013 completed in 0:00:06.647224

 16%|█▋        | 706/4292 [1:51:12<6:48:49,  6.84s/it]

UT_17845_2013 completed in 0:00:07.244139

 16%|█▋        | 707/4292 [1:51:22<7:40:15,  7.70s/it]

UT_17874_2013 completed in 0:00:09.715014

 16%|█▋        | 708/4292 [1:51:32<8:13:03,  8.25s/it]

UT_18206_2013 completed in 0:00:09.539957

 17%|█▋        | 709/4292 [1:51:43<8:59:33,  9.04s/it]

VA_84_2013 completed in 0:00:10.856314

 17%|█▋        | 710/4292 [1:51:54<9:34:33,  9.62s/it]

VA_733_2013 completed in 0:00:10.997043

 17%|█▋        | 711/4292 [1:52:08<11:01:59, 11.09s/it]

VA_17066_2013 completed in 0:00:14.515218

 17%|█▋        | 712/4292 [1:52:25<12:53:24, 12.96s/it]

VA_19876_2013 completed in 0:00:17.325585

 17%|█▋        | 713/4292 [1:52:37<12:26:21, 12.51s/it]

VA_40228_2013 completed in 0:00:11.461651

 17%|█▋        | 714/4292 [1:52:46<11:17:30, 11.36s/it]

VT_2548_2013 completed in 0:00:08.675046

 17%|█▋        | 715/4292 [1:52:54<10:19:49, 10.40s/it]

VT_7601_2013 completed in 0:00:08.145148

 17%|█▋        | 716/4292 [1:53:02<9:34:29,  9.64s/it]

VT_19791_2013 completed in 0:00:07.870258

 17%|█▋        | 717/4292 [1:53:13<9:59:42, 10.07s/it]

WA_3660_2013 completed in 0:00:11.058382

 17%|█▋        | 718/4292 [1:53:23<10:11:10, 10.26s/it]

WA_14354_2013 completed in 0:00:10.714840

 17%|█▋        | 719/4292 [1:53:34<10:21:00, 10.43s/it]

WA_15500_2013 completed in 0:00:10.819259

 17%|█▋        | 720/4292 [1:53:43<9:49:25,  9.90s/it]

WA_16868_2013 completed in 0:00:08.668855

 17%|█▋        | 721/4292 [1:53:53<9:49:54,  9.91s/it]

WA_17470_2013 completed in 0:00:09.936124

 17%|█▋        | 722/4292 [1:54:03<9:47:27,  9.87s/it]

WA_18429_2013 completed in 0:00:09.777120

 17%|█▋        | 723/4292 [1:54:12<9:44:35,  9.83s/it]

WA_20169_2013 completed in 0:00:09.721591

 17%|█▋        | 724/4292 [1:54:20<9:14:16,  9.32s/it]

WI_4715_2013 completed in 0:00:08.136944

 17%|█▋        | 725/4292 [1:54:33<10:12:02, 10.30s/it]

WI_11479_2013 completed in 0:00:12.567485

 17%|█▋        | 726/4292 [1:54:42<9:48:41,  9.90s/it]

WI_13697_2013 completed in 0:00:08.993596

 17%|█▋        | 727/4292 [1:54:50<9:13:59,  9.32s/it]

WI_13815_2013 completed in 0:00:07.966921

 17%|█▋        | 728/4292 [1:54:57<8:37:02,  8.70s/it]

WI_20847_2013 completed in 0:00:07.257594

 17%|█▋        | 729/4292 [1:55:07<8:50:00,  8.93s/it]

WI_20856_2013 completed in 0:00:09.439380

 17%|█▋        | 730/4292 [1:55:20<10:08:52, 10.26s/it]

WI_20860_2013 completed in 0:00:13.360179

 17%|█▋        | 731/4292 [1:55:29<9:47:34,  9.90s/it]

WV_733_2013 completed in 0:00:09.066762

 17%|█▋        | 732/4292 [1:55:41<10:22:22, 10.49s/it]

WV_12796_2013 completed in 0:00:11.864135

 17%|█▋        | 733/4292 [1:55:51<10:18:20, 10.42s/it]

WV_20521_2013 completed in 0:00:10.272000

 17%|█▋        | 734/4292 [1:56:00<9:42:49,  9.83s/it]

WY_3461_2013 completed in 0:00:08.436228

 17%|█▋        | 735/4292 [1:56:10<9:52:36, 10.00s/it]

WY_8566_2013 completed in 0:00:10.387023

 17%|█▋        | 736/4292 [1:56:18<9:24:16,  9.52s/it]

WY_11273_2013 completed in 0:00:08.407104

 17%|█▋        | 737/4292 [1:56:27<9:01:59,  9.15s/it]

WY_14354_2013 completed in 0:00:08.275703

 17%|█▋        | 738/4292 [1:56:35<8:49:06,  8.93s/it]

WY_19156_2013 completed in 0:00:08.430265

 17%|█▋        | 739/4292 [1:56:45<9:01:57,  9.15s/it]

WY_27058_2013 completed in 0:00:09.662944

 17%|█▋        | 740/4292 [1:56:53<8:46:11,  8.89s/it]

MI_10704_2013 completed in 0:00:08.272591

 17%|█▋        | 741/4292 [1:57:00<8:03:34,  8.17s/it]

NE_12539_2013 completed in 0:00:06.495672

 17%|█▋        | 742/4292 [1:57:09<8:17:09,  8.40s/it]

AR_5860_2013 completed in 0:00:08.942410

 17%|█▋        | 743/4292 [1:57:17<8:19:12,  8.44s/it]

OK_5860_2013 completed in 0:00:08.525178

 17%|█▋        | 744/4292 [1:57:29<9:24:03,  9.54s/it]

AK_599_2014 completed in 0:00:12.102051

 17%|█▋        | 745/4292 [1:57:37<8:55:43,  9.06s/it]

AK_3522_2014 completed in 0:00:07.949850

 17%|█▋        | 746/4292 [1:57:49<9:49:03,  9.97s/it]

AK_7353_2014 completed in 0:00:12.078010

 17%|█▋        | 747/4292 [1:57:58<9:26:15,  9.58s/it]

AK_11824_2014 completed in 0:00:08.688913

 17%|█▋        | 748/4292 [1:58:06<8:57:23,  9.10s/it]

AK_19558_2014 completed in 0:00:07.963093

 17%|█▋        | 749/4292 [1:58:18<9:46:40,  9.94s/it]

AL_195_2014 completed in 0:00:11.887143

 17%|█▋        | 750/4292 [1:58:25<8:54:58,  9.06s/it]

AL_4958_2014 completed in 0:00:07.024504

 17%|█▋        | 751/4292 [1:58:34<8:51:41,  9.01s/it]

AL_9739_2014 completed in 0:00:08.880319

 18%|█▊        | 752/4292 [1:58:45<9:41:37,  9.86s/it]

AR_814_2014 completed in 0:00:11.837543

 18%|█▊        | 753/4292 [1:58:55<9:39:10,  9.82s/it]

AR_817_2014 completed in 0:00:09.728366

 18%|█▊        | 754/4292 [1:59:06<10:03:17, 10.23s/it]

AR_3093_2014 completed in 0:00:11.190952

 18%|█▊        | 755/4292 [1:59:13<9:05:59,  9.26s/it]

AR_5860_2014 completed in 0:00:06.999520

 18%|█▊        | 756/4292 [1:59:23<9:14:40,  9.41s/it]

AR_6342_2014 completed in 0:00:09.756133

 18%|█▊        | 757/4292 [1:59:32<9:11:39,  9.36s/it]

AR_14063_2014 completed in 0:00:09.248886

 18%|█▊        | 758/4292 [1:59:42<9:19:40,  9.50s/it]

AR_17698_2014 completed in 0:00:09.825048

 18%|█▊        | 759/4292 [1:59:50<8:54:20,  9.07s/it]

AZ_176_2014 completed in 0:00:08.076176

 18%|█▊        | 760/4292 [2:00:03<10:05:00, 10.28s/it]

AZ_803_2014 completed in 0:00:13.078809

 18%|█▊        | 761/4292 [2:00:13<10:01:02, 10.21s/it]

AZ_12919_2014 completed in 0:00:10.055827

 18%|█▊        | 762/4292 [2:00:21<9:12:23,  9.39s/it]

AZ_16572_2014 completed in 0:00:07.465367

 18%|█▊        | 763/4292 [2:00:32<9:37:42,  9.82s/it]

AZ_19189_2014 completed in 0:00:10.831940

 18%|█▊        | 764/4292 [2:00:39<8:45:54,  8.94s/it]

AZ_19728_2014 completed in 0:00:06.893743

 18%|█▊        | 765/4292 [2:00:47<8:29:46,  8.67s/it]

AZ_21538_2014 completed in 0:00:08.034698

 18%|█▊        | 766/4292 [2:00:55<8:18:02,  8.48s/it]

AZ_24211_2014 completed in 0:00:08.014320

 18%|█▊        | 767/4292 [2:01:02<7:52:32,  8.04s/it]

CA_9216_2014 completed in 0:00:07.035463

 18%|█▊        | 768/4292 [2:01:09<7:41:09,  7.85s/it]

CA_11208_2014 completed in 0:00:07.403892

 18%|█▊        | 769/4292 [2:01:17<7:47:41,  7.97s/it]

CA_12745_2014 completed in 0:00:08.228616

 18%|█▊        | 770/4292 [2:01:35<10:31:05, 10.75s/it]

CA_14328_2014 completed in 0:00:17.250629

 18%|█▊        | 771/4292 [2:01:41<9:15:20,  9.46s/it]

CA_14354_2014 completed in 0:00:06.457063

 18%|█▊        | 772/4292 [2:01:46<8:01:32,  8.21s/it]

CA_14534_2014 completed in 0:00:05.274050

 18%|█▊        | 773/4292 [2:01:52<7:16:34,  7.44s/it]

CA_16534_2014 completed in 0:00:05.659176

 18%|█▊        | 774/4292 [2:02:00<7:26:55,  7.62s/it]

CA_16609_2014 completed in 0:00:08.038062

 18%|█▊        | 775/4292 [2:02:10<8:06:42,  8.30s/it]

CA_17609_2014 completed in 0:00:09.891388

 18%|█▊        | 776/4292 [2:02:16<7:34:58,  7.76s/it]

CA_17612_2014 completed in 0:00:06.504470

 18%|█▊        | 777/4292 [2:02:28<8:41:18,  8.90s/it]

CA_19281_2014 completed in 0:00:11.545483

 18%|█▊        | 778/4292 [2:02:34<7:44:28,  7.93s/it]

CO_3989_2014 completed in 0:00:05.671499

 18%|█▊        | 779/4292 [2:02:41<7:25:12,  7.60s/it]

CO_6604_2014 completed in 0:00:06.840255

 18%|█▊        | 780/4292 [2:02:49<7:48:52,  8.01s/it]

CO_9336_2014 completed in 0:00:08.957921

 18%|█▊        | 781/4292 [2:03:03<9:19:08,  9.56s/it]

CO_12866_2014 completed in 0:00:13.158790

 18%|█▊        | 782/4292 [2:03:10<8:48:43,  9.04s/it]

CO_15257_2014 completed in 0:00:07.830411

 18%|█▊        | 783/4292 [2:03:30<11:46:30, 12.08s/it]

CO_15466_2014 completed in 0:00:19.179239

 18%|█▊        | 784/4292 [2:03:37<10:22:34, 10.65s/it]

CO_16603_2014 completed in 0:00:07.305938

 18%|█▊        | 785/4292 [2:03:44<9:27:29,  9.71s/it]

CO_19499_2014 completed in 0:00:07.516197

 18%|█▊        | 786/4292 [2:03:53<9:14:08,  9.48s/it]

CO_27058_2014 completed in 0:00:08.950860

 18%|█▊        | 787/4292 [2:04:03<9:06:58,  9.36s/it]

CO_56146_2014 completed in 0:00:09.082336

 18%|█▊        | 788/4292 [2:04:11<8:50:23,  9.08s/it]

CT_4176_2014 completed in 0:00:08.420186

 18%|█▊        | 789/4292 [2:04:17<7:59:35,  8.21s/it]

CT_19497_2014 completed in 0:00:06.189904

 18%|█▊        | 790/4292 [2:04:24<7:28:19,  7.68s/it]

CT_20038_2014 completed in 0:00:06.435817

 18%|█▊        | 791/4292 [2:04:31<7:18:23,  7.51s/it]

DC_15270_2014 completed in 0:00:07.119618

 18%|█▊        | 792/4292 [2:04:38<7:08:49,  7.35s/it]

DE_5027_2014 completed in 0:00:06.973405

 18%|█▊        | 793/4292 [2:04:46<7:33:16,  7.77s/it]

DE_5070_2014 completed in 0:00:08.754395

 18%|█▊        | 794/4292 [2:04:53<7:19:26,  7.54s/it]

DE_5335_2014 completed in 0:00:06.983897

 19%|█▊        | 795/4292 [2:05:02<7:29:03,  7.70s/it]

DE_13519_2014 completed in 0:00:08.093516

 19%|█▊        | 796/4292 [2:05:12<8:11:40,  8.44s/it]

FL_6452_2014 completed in 0:00:10.148973

 19%|█▊        | 797/4292 [2:05:24<9:14:40,  9.52s/it]

FL_6455_2014 completed in 0:00:12.051080

 19%|█▊        | 798/4292 [2:05:31<8:42:02,  8.96s/it]

FL_6457_2014 completed in 0:00:07.662081

 19%|█▊        | 799/4292 [2:05:38<8:03:24,  8.30s/it]

FL_7801_2014 completed in 0:00:06.760419

 19%|█▊        | 800/4292 [2:05:46<7:59:42,  8.24s/it]

FL_9617_2014 completed in 0:00:08.098415

 19%|█▊        | 801/4292 [2:05:55<8:00:07,  8.25s/it]

FL_18454_2014 completed in 0:00:08.267974

 19%|█▊        | 802/4292 [2:06:02<7:39:29,  7.90s/it]

GA_3916_2014 completed in 0:00:07.077207

 19%|█▊        | 803/4292 [2:06:13<8:41:27,  8.97s/it]

GA_7140_2014 completed in 0:00:11.458488

 19%|█▊        | 804/4292 [2:06:20<8:11:22,  8.45s/it]

HI_8287_2014 completed in 0:00:07.250352

 19%|█▉        | 805/4292 [2:06:30<8:30:47,  8.79s/it]

HI_10071_2014 completed in 0:00:09.573520

 19%|█▉        | 806/4292 [2:06:37<8:06:34,  8.37s/it]

HI_11843_2014 completed in 0:00:07.407418

 19%|█▉        | 807/4292 [2:06:47<8:21:10,  8.63s/it]

HI_19547_2014 completed in 0:00:09.219253

 19%|█▉        | 808/4292 [2:06:57<8:50:52,  9.14s/it]

IA_9417_2014 completed in 0:00:10.340870

 19%|█▉        | 809/4292 [2:07:07<9:08:03,  9.44s/it]

IA_12341_2014 completed in 0:00:10.137703

 19%|█▉        | 810/4292 [2:07:17<9:25:25,  9.74s/it]

ID_9187_2014 completed in 0:00:10.446533

 19%|█▉        | 811/4292 [2:07:29<10:00:43, 10.35s/it]

ID_9191_2014 completed in 0:00:11.779460

 19%|█▉        | 812/4292 [2:07:36<9:04:43,  9.39s/it]

ID_10454_2014 completed in 0:00:07.144649

 19%|█▉        | 813/4292 [2:07:46<9:16:28,  9.60s/it]

ID_11273_2014 completed in 0:00:10.075525

 19%|█▉        | 814/4292 [2:07:55<9:00:25,  9.32s/it]

ID_14354_2014 completed in 0:00:08.680626

 19%|█▉        | 815/4292 [2:08:03<8:26:39,  8.74s/it]

ID_20169_2014 completed in 0:00:07.388517

 19%|█▉        | 816/4292 [2:08:10<8:05:21,  8.38s/it]

IL_4110_2014 completed in 0:00:07.524552

 19%|█▉        | 817/4292 [2:08:17<7:48:10,  8.08s/it]

IL_12341_2014 completed in 0:00:07.395748

 19%|█▉        | 818/4292 [2:08:24<7:25:50,  7.70s/it]

IL_13032_2014 completed in 0:00:06.804641

 19%|█▉        | 819/4292 [2:08:37<8:57:15,  9.28s/it]

IL_56697_2014 completed in 0:00:12.971380

 19%|█▉        | 820/4292 [2:08:44<8:22:21,  8.68s/it]

IN_9273_2014 completed in 0:00:07.279131

 19%|█▉        | 821/4292 [2:08:55<8:52:54,  9.21s/it]

IN_9324_2014 completed in 0:00:10.448992

 19%|█▉        | 822/4292 [2:09:02<8:21:51,  8.68s/it]

IN_13756_2014 completed in 0:00:07.430242

 19%|█▉        | 823/4292 [2:09:13<8:58:30,  9.31s/it]

IN_15470_2014 completed in 0:00:10.798286

 19%|█▉        | 824/4292 [2:09:21<8:37:32,  8.95s/it]

IN_17633_2014 completed in 0:00:08.113316

 19%|█▉        | 825/4292 [2:09:27<7:48:24,  8.11s/it]

KS_9996_2014 completed in 0:00:06.126438

 19%|█▉        | 826/4292 [2:09:35<7:46:02,  8.07s/it]

KS_10000_2014 completed in 0:00:07.975746

 19%|█▉        | 827/4292 [2:09:44<8:02:35,  8.36s/it]

KS_10005_2014 completed in 0:00:09.029803

 19%|█▉        | 828/4292 [2:09:52<7:53:37,  8.20s/it]

KS_22500_2014 completed in 0:00:07.845205

 19%|█▉        | 829/4292 [2:10:02<8:12:47,  8.54s/it]

KY_9964_2014 completed in 0:00:09.315077

 19%|█▉        | 830/4292 [2:10:12<8:52:06,  9.22s/it]

KY_10171_2014 completed in 0:00:10.816813

 19%|█▉        | 831/4292 [2:10:20<8:26:54,  8.79s/it]

KY_11249_2014 completed in 0:00:07.772869

 19%|█▉        | 832/4292 [2:10:28<8:16:36,  8.61s/it]

KY_14724_2014 completed in 0:00:08.199944

 19%|█▉        | 833/4292 [2:10:36<7:50:56,  8.17s/it]

KY_19446_2014 completed in 0:00:07.135642

 19%|█▉        | 834/4292 [2:10:45<8:19:28,  8.67s/it]

KY_20130_2014 completed in 0:00:09.825931

 19%|█▉        | 835/4292 [2:10:54<8:24:33,  8.76s/it]

KY_22053_2014 completed in 0:00:08.967861

 19%|█▉        | 836/4292 [2:11:02<7:58:58,  8.32s/it]

KY_49998_2014 completed in 0:00:07.281768

 20%|█▉        | 837/4292 [2:11:09<7:47:26,  8.12s/it]

LA_3265_2014 completed in 0:00:07.655027

 20%|█▉        | 838/4292 [2:11:17<7:40:49,  8.01s/it]

LA_11241_2014 completed in 0:00:07.740411

 20%|█▉        | 839/4292 [2:11:25<7:44:58,  8.08s/it]

LA_13478_2014 completed in 0:00:08.252144

 20%|█▉        | 840/4292 [2:11:31<7:12:36,  7.52s/it]

LA_17698_2014 completed in 0:00:06.211261

 20%|█▉        | 841/4292 [2:11:37<6:30:28,  6.79s/it]

LA_55936_2014 completed in 0:00:05.080272

 20%|█▉        | 842/4292 [2:11:46<7:14:31,  7.56s/it]

MA_6374_2014 completed in 0:00:09.348542

 20%|█▉        | 843/4292 [2:11:54<7:22:05,  7.69s/it]

MA_8774_2014 completed in 0:00:08.001911

 20%|█▉        | 844/4292 [2:12:03<7:52:42,  8.23s/it]

MA_11804_2014 completed in 0:00:09.473143

 20%|█▉        | 845/4292 [2:12:12<7:55:43,  8.28s/it]

MA_13206_2014 completed in 0:00:08.407621

 20%|█▉        | 846/4292 [2:12:20<7:52:22,  8.22s/it]

MA_15748_2014 completed in 0:00:08.093244

 20%|█▉        | 847/4292 [2:12:29<8:01:03,  8.38s/it]

MA_20455_2014 completed in 0:00:08.733916

 20%|█▉        | 848/4292 [2:12:37<7:59:48,  8.36s/it]

MA_54913_2014 completed in 0:00:08.313063

 20%|█▉        | 849/4292 [2:12:45<7:47:30,  8.15s/it]

MD_1167_2014 completed in 0:00:07.652064

 20%|█▉        | 850/4292 [2:12:52<7:42:24,  8.06s/it]

MD_5027_2014 completed in 0:00:07.857363

 20%|█▉        | 851/4292 [2:13:00<7:31:25,  7.87s/it]

MD_15263_2014 completed in 0:00:07.428438

 20%|█▉        | 852/4292 [2:13:07<7:24:54,  7.76s/it]

MD_15270_2014 completed in 0:00:07.499418

 20%|█▉        | 853/4292 [2:13:16<7:47:02,  8.15s/it]

ME_1179_2014 completed in 0:00:09.053687

 20%|█▉        | 854/4292 [2:13:25<8:00:52,  8.39s/it]

ME_3266_2014 completed in 0:00:08.960069

 20%|█▉        | 855/4292 [2:13:33<7:46:21,  8.14s/it]

MI_392_2014 completed in 0:00:07.554768

 20%|█▉        | 856/4292 [2:13:40<7:28:56,  7.84s/it]

MI_3828_2014 completed in 0:00:07.134496

 20%|█▉        | 857/4292 [2:13:49<7:43:06,  8.09s/it]

MI_4254_2014 completed in 0:00:08.670747

 20%|█▉        | 858/4292 [2:13:57<7:46:19,  8.15s/it]

MI_5109_2014 completed in 0:00:08.284183

 20%|██        | 859/4292 [2:14:06<7:58:13,  8.36s/it]

MI_9324_2014 completed in 0:00:08.848181

 20%|██        | 860/4292 [2:14:14<7:56:12,  8.33s/it]

MI_10704_2014 completed in 0:00:08.248106

 20%|██        | 861/4292 [2:14:22<7:42:31,  8.09s/it]

MI_19578_2014 completed in 0:00:07.534515

 20%|██        | 862/4292 [2:14:32<8:25:30,  8.84s/it]

MI_20847_2014 completed in 0:00:10.602075

 20%|██        | 863/4292 [2:14:39<7:43:34,  8.11s/it]

MI_20860_2014 completed in 0:00:06.404549

 20%|██        | 864/4292 [2:14:47<7:44:35,  8.13s/it]

MN_689_2014 completed in 0:00:08.178179

 20%|██        | 865/4292 [2:14:56<8:02:56,  8.46s/it]

MN_5574_2014 completed in 0:00:09.209085

 20%|██        | 866/4292 [2:15:04<7:54:42,  8.31s/it]

MN_9417_2014 completed in 0:00:07.981951

 20%|██        | 867/4292 [2:15:14<8:22:08,  8.80s/it]

MN_12647_2014 completed in 0:00:09.922746

 20%|██        | 868/4292 [2:15:21<7:59:49,  8.41s/it]

MN_13781_2014 completed in 0:00:07.499305

 20%|██        | 869/4292 [2:15:32<8:27:34,  8.90s/it]

MN_14232_2014 completed in 0:00:10.036924

 20%|██        | 870/4292 [2:15:40<8:16:28,  8.70s/it]

MN_16181_2014 completed in 0:00:08.255807

 20%|██        | 871/4292 [2:15:45<7:21:34,  7.74s/it]

MN_17267_2014 completed in 0:00:05.502881

 20%|██        | 872/4292 [2:15:53<7:25:04,  7.81s/it]

MN_20996_2014 completed in 0:00:07.956424

 20%|██        | 873/4292 [2:15:59<6:50:49,  7.21s/it]

MN_25177_2014 completed in 0:00:05.811547

 20%|██        | 874/4292 [2:16:05<6:30:30,  6.85s/it]

MO_4675_2014 completed in 0:00:06.026508

 20%|██        | 875/4292 [2:16:14<7:05:15,  7.47s/it]

MO_5860_2014 completed in 0:00:08.895457

 20%|██        | 876/4292 [2:16:19<6:29:59,  6.85s/it]

MO_9231_2014 completed in 0:00:05.408143

 20%|██        | 877/4292 [2:16:26<6:26:17,  6.79s/it]

MO_10000_2014 completed in 0:00:06.639207

 20%|██        | 878/4292 [2:16:34<6:38:34,  7.00s/it]

MO_12698_2014 completed in 0:00:07.511945

 20%|██        | 879/4292 [2:16:40<6:38:03,  7.00s/it]

MO_17833_2014 completed in 0:00:06.980068

 21%|██        | 880/4292 [2:16:48<6:45:08,  7.12s/it]

MO_19436_2014 completed in 0:00:07.418074

 21%|██        | 881/4292 [2:16:54<6:28:50,  6.84s/it]

MS_3841_2014 completed in 0:00:06.174931

 21%|██        | 882/4292 [2:17:02<6:46:35,  7.15s/it]

MS_6641_2014 completed in 0:00:07.887109

 21%|██        | 883/4292 [2:17:08<6:29:27,  6.85s/it]

MS_17647_2014 completed in 0:00:06.154390

 21%|██        | 884/4292 [2:17:14<6:06:06,  6.45s/it]

MS_19273_2014 completed in 0:00:05.490668

 21%|██        | 885/4292 [2:17:25<7:34:45,  8.01s/it]

MT_6395_2014 completed in 0:00:11.654501

 21%|██        | 886/4292 [2:17:32<7:04:15,  7.47s/it]

MT_12692_2014 completed in 0:00:06.225320

 21%|██        | 887/4292 [2:17:38<6:42:20,  7.09s/it]

MT_12825_2014 completed in 0:00:06.192736

 21%|██        | 888/4292 [2:17:43<6:11:54,  6.56s/it]

MT_19603_2014 completed in 0:00:05.306928

 21%|██        | 889/4292 [2:17:49<6:07:40,  6.48s/it]

MT_20997_2014 completed in 0:00:06.312833

 21%|██        | 890/4292 [2:17:57<6:33:16,  6.94s/it]

NC_3046_2014 completed in 0:00:07.992744

 21%|██        | 891/4292 [2:18:04<6:32:26,  6.92s/it]

NC_5416_2014 completed in 0:00:06.892440

 21%|██        | 892/4292 [2:18:11<6:22:26,  6.75s/it]

NC_9837_2014 completed in 0:00:06.338859

 21%|██        | 893/4292 [2:18:18<6:35:21,  6.98s/it]

NC_16496_2014 completed in 0:00:07.514688

 21%|██        | 894/4292 [2:18:25<6:41:41,  7.09s/it]

NC_19876_2014 completed in 0:00:07.357783

 21%|██        | 895/4292 [2:18:33<6:51:19,  7.27s/it]

NC_24889_2014 completed in 0:00:07.665746

 21%|██        | 896/4292 [2:18:39<6:31:05,  6.91s/it]

ND_12087_2014 completed in 0:00:06.079367

 21%|██        | 897/4292 [2:18:45<6:20:01,  6.72s/it]

ND_12301_2014 completed in 0:00:06.264099

 21%|██        | 898/4292 [2:18:53<6:33:03,  6.95s/it]

ND_14232_2014 completed in 0:00:07.487189

 21%|██        | 899/4292 [2:19:01<6:48:08,  7.22s/it]

ND_19790_2014 completed in 0:00:07.843859

 21%|██        | 900/4292 [2:19:09<7:12:08,  7.64s/it]

ND_24949_2014 completed in 0:00:08.638493

 21%|██        | 901/4292 [2:19:15<6:43:54,  7.15s/it]

NE_4373_2014 completed in 0:00:05.985322

 21%|██        | 902/4292 [2:19:21<6:22:24,  6.77s/it]

NE_11018_2014 completed in 0:00:05.884754

 21%|██        | 903/4292 [2:19:26<5:48:37,  6.17s/it]

NE_11251_2014 completed in 0:00:04.780404

 21%|██        | 904/4292 [2:19:33<6:06:59,  6.50s/it]

NE_12539_2014 completed in 0:00:07.261079

 21%|██        | 905/4292 [2:19:41<6:23:06,  6.79s/it]

NE_13337_2014 completed in 0:00:07.457068

 21%|██        | 906/4292 [2:19:47<6:21:09,  6.75s/it]

NE_13664_2014 completed in 0:00:06.677423

 21%|██        | 907/4292 [2:19:55<6:41:24,  7.12s/it]

NE_14127_2014 completed in 0:00:07.956193

 21%|██        | 908/4292 [2:20:04<7:08:43,  7.60s/it]

NE_17642_2014 completed in 0:00:08.731401

 21%|██        | 909/4292 [2:20:13<7:26:29,  7.92s/it]

NH_13441_2014 completed in 0:00:08.658138

 21%|██        | 910/4292 [2:20:23<8:11:01,  8.71s/it]

NH_15472_2014 completed in 0:00:10.559162

 21%|██        | 911/4292 [2:20:31<7:51:54,  8.37s/it]

NH_24590_2014 completed in 0:00:07.588873

 21%|██        | 912/4292 [2:20:40<8:01:32,  8.55s/it]

NJ_963_2014 completed in 0:00:08.951632

 21%|██▏       | 913/4292 [2:20:48<8:00:57,  8.54s/it]

NJ_9726_2014 completed in 0:00:08.521022

 21%|██▏       | 914/4292 [2:20:56<7:41:35,  8.20s/it]

NJ_15477_2014 completed in 0:00:07.401331

 21%|██▏       | 915/4292 [2:21:03<7:18:03,  7.78s/it]

NJ_16213_2014 completed in 0:00:06.811871

 21%|██▏       | 916/4292 [2:21:09<7:00:34,  7.47s/it]

NM_3287_2014 completed in 0:00:06.753860

 21%|██▏       | 917/4292 [2:21:17<6:54:27,  7.37s/it]

NM_5701_2014 completed in 0:00:07.118950

 21%|██▏       | 918/4292 [2:21:23<6:38:51,  7.09s/it]

NM_6204_2014 completed in 0:00:06.449428

 21%|██▏       | 919/4292 [2:21:30<6:30:12,  6.94s/it]

NM_11204_2014 completed in 0:00:06.584805

 21%|██▏       | 920/4292 [2:21:43<8:13:45,  8.79s/it]

NM_15473_2014 completed in 0:00:13.088701

 21%|██▏       | 921/4292 [2:21:48<7:23:16,  7.89s/it]

NM_17718_2014 completed in 0:00:05.797925

 21%|██▏       | 922/4292 [2:21:54<6:46:37,  7.24s/it]

NM_22690_2014 completed in 0:00:05.721462

 22%|██▏       | 923/4292 [2:21:59<6:10:25,  6.60s/it]

NV_2008_2014 completed in 0:00:05.096888

 22%|██▏       | 924/4292 [2:22:05<5:59:17,  6.40s/it]

NV_13073_2014 completed in 0:00:05.941645

 22%|██▏       | 925/4292 [2:22:11<5:52:51,  6.29s/it]

NV_13407_2014 completed in 0:00:06.022999

 22%|██▏       | 926/4292 [2:22:19<6:13:20,  6.65s/it]

NV_17166_2014 completed in 0:00:07.505780

 22%|██▏       | 927/4292 [2:22:25<6:05:03,  6.51s/it]

NV_19840_2014 completed in 0:00:06.168201

 22%|██▏       | 928/4292 [2:22:32<6:11:45,  6.63s/it]

NY_3249_2014 completed in 0:00:06.909737

 22%|██▏       | 929/4292 [2:22:45<7:59:19,  8.55s/it]

NY_4226_2014 completed in 0:00:13.032813

 22%|██▏       | 930/4292 [2:22:52<7:43:07,  8.27s/it]

NY_11171_2014 completed in 0:00:07.595593

 22%|██▏       | 931/4292 [2:23:04<8:44:25,  9.36s/it]

NY_13511_2014 completed in 0:00:11.920209

 22%|██▏       | 932/4292 [2:23:24<11:34:18, 12.40s/it]

NY_13573_2014 completed in 0:00:19.482223

 22%|██▏       | 933/4292 [2:23:31<10:07:28, 10.85s/it]

NY_14154_2014 completed in 0:00:07.240360

 22%|██▏       | 934/4292 [2:23:40<9:30:27, 10.19s/it]

NY_16183_2014 completed in 0:00:08.655913

 22%|██▏       | 935/4292 [2:23:45<8:13:23,  8.82s/it]

OH_3542_2014 completed in 0:00:05.610856

 22%|██▏       | 936/4292 [2:23:53<8:01:20,  8.61s/it]

OH_3755_2014 completed in 0:00:08.108367

 22%|██▏       | 937/4292 [2:24:05<8:55:50,  9.58s/it]

OH_4922_2014 completed in 0:00:11.862113

 22%|██▏       | 938/4292 [2:24:13<8:28:43,  9.10s/it]

OH_13998_2014 completed in 0:00:07.974931

 22%|██▏       | 939/4292 [2:24:25<9:16:16,  9.95s/it]

OH_14006_2014 completed in 0:00:11.944469

 22%|██▏       | 940/4292 [2:24:31<8:02:48,  8.64s/it]

OH_18997_2014 completed in 0:00:05.580422

 22%|██▏       | 941/4292 [2:24:38<7:45:22,  8.33s/it]

OK_5860_2014 completed in 0:00:07.608194

 22%|██▏       | 942/4292 [2:24:44<7:06:04,  7.63s/it]

OK_13734_2014 completed in 0:00:05.993516

 22%|██▏       | 943/4292 [2:24:51<6:54:17,  7.42s/it]

OK_14062_2014 completed in 0:00:06.934663

 22%|██▏       | 944/4292 [2:25:01<7:26:49,  8.01s/it]

OK_14063_2014 completed in 0:00:09.372092

 22%|██▏       | 945/4292 [2:25:08<7:14:39,  7.79s/it]

OK_15474_2014 completed in 0:00:07.287156

 22%|██▏       | 946/4292 [2:25:14<6:39:30,  7.16s/it]

OK_19785_2014 completed in 0:00:05.698427

 22%|██▏       | 947/4292 [2:25:20<6:16:49,  6.76s/it]

OR_6022_2014 completed in 0:00:05.813761

 22%|██▏       | 948/4292 [2:25:26<6:07:18,  6.59s/it]

OR_9191_2014 completed in 0:00:06.196038

 22%|██▏       | 949/4292 [2:25:37<7:18:31,  7.87s/it]

OR_14354_2014 completed in 0:00:10.856415

 22%|██▏       | 950/4292 [2:25:44<7:18:04,  7.86s/it]

OR_15248_2014 completed in 0:00:07.850929

 22%|██▏       | 951/4292 [2:25:51<6:51:42,  7.39s/it]

OR_18260_2014 completed in 0:00:06.293355

 22%|██▏       | 952/4292 [2:25:58<6:46:13,  7.30s/it]

OR_40437_2014 completed in 0:00:07.072069

 22%|██▏       | 953/4292 [2:26:05<6:41:21,  7.21s/it]

PA_3597_2014 completed in 0:00:07.011705

 22%|██▏       | 954/4292 [2:26:12<6:44:09,  7.26s/it]

PA_5487_2014 completed in 0:00:07.384809

 22%|██▏       | 955/4292 [2:26:25<8:13:10,  8.87s/it]

PA_12390_2014 completed in 0:00:12.606473

 22%|██▏       | 956/4292 [2:26:40<9:55:13, 10.71s/it]

PA_14711_2014 completed in 0:00:14.992747

 22%|██▏       | 957/4292 [2:26:53<10:39:40, 11.51s/it]

PA_14715_2014 completed in 0:00:13.380810

 22%|██▏       | 958/4292 [2:27:03<10:12:52, 11.03s/it]

PA_14716_2014 completed in 0:00:09.911574

WARNING:googleapiclient.http:Sleeping 1.52 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/value:compute?prettyPrint=false&alt=json, after 503
 22%|██▏       | 959/4292 [2:27:19<11:31:20, 12.45s/it]

PA_14940_2014 completed in 0:00:15.747315

 22%|██▏       | 960/4292 [2:27:29<10:43:56, 11.60s/it]

PA_15045_2014 completed in 0:00:09.612449

 22%|██▏       | 961/4292 [2:27:37<9:49:21, 10.62s/it]

PA_19390_2014 completed in 0:00:08.328350

 22%|██▏       | 962/4292 [2:27:46<9:27:09, 10.22s/it]

PA_20334_2014 completed in 0:00:09.292238

 22%|██▏       | 963/4292 [2:27:59<10:18:06, 11.14s/it]

PA_20387_2014 completed in 0:00:13.289330

 22%|██▏       | 964/4292 [2:28:08<9:31:44, 10.31s/it]

RI_1857_2014 completed in 0:00:08.364252

 22%|██▏       | 965/4292 [2:28:16<9:02:39,  9.79s/it]

RI_13214_2014 completed in 0:00:08.563413

 23%|██▎       | 966/4292 [2:28:26<9:04:49,  9.83s/it]

SC_1613_2014 completed in 0:00:09.924963

 23%|██▎       | 967/4292 [2:28:36<9:02:16,  9.79s/it]

SC_3046_2014 completed in 0:00:09.684624

 23%|██▎       | 968/4292 [2:28:47<9:21:33, 10.14s/it]

SC_5416_2014 completed in 0:00:10.954034

 23%|██▎       | 969/4292 [2:28:57<9:17:40, 10.07s/it]

SC_14398_2014 completed in 0:00:09.912397

 23%|██▎       | 970/4292 [2:29:07<9:11:23,  9.96s/it]

SC_17539_2014 completed in 0:00:09.699917

 23%|██▎       | 971/4292 [2:29:15<8:43:58,  9.47s/it]

SC_17543_2014 completed in 0:00:08.316733

 23%|██▎       | 972/4292 [2:29:27<9:35:03, 10.39s/it]

SD_1769_2014 completed in 0:00:12.551300

 23%|██▎       | 973/4292 [2:29:35<8:48:09,  9.55s/it]

SD_13337_2014 completed in 0:00:07.576681

 23%|██▎       | 974/4292 [2:29:43<8:18:05,  9.01s/it]

SD_14232_2014 completed in 0:00:07.739682

 23%|██▎       | 975/4292 [2:29:50<7:50:05,  8.50s/it]

SD_17267_2014 completed in 0:00:07.326809

 23%|██▎       | 976/4292 [2:29:58<7:43:25,  8.39s/it]

SD_19293_2014 completed in 0:00:08.108462

 23%|██▎       | 977/4292 [2:30:04<6:54:34,  7.50s/it]

SD_20401_2014 completed in 0:00:05.445595

 23%|██▎       | 978/4292 [2:30:10<6:39:47,  7.24s/it]

TN_727_2014 completed in 0:00:06.617534

 23%|██▎       | 979/4292 [2:30:19<7:01:04,  7.63s/it]

TN_4624_2014 completed in 0:00:08.529533

 23%|██▎       | 980/4292 [2:30:27<7:03:06,  7.67s/it]

TN_5399_2014 completed in 0:00:07.755801

 23%|██▎       | 981/4292 [2:30:33<6:49:35,  7.42s/it]

TN_7174_2014 completed in 0:00:06.855414

 23%|██▎       | 982/4292 [2:30:41<6:45:04,  7.34s/it]

TN_10331_2014 completed in 0:00:07.156402

 23%|██▎       | 983/4292 [2:30:49<6:55:53,  7.54s/it]

TN_12470_2014 completed in 0:00:08.002509

 23%|██▎       | 984/4292 [2:30:55<6:38:37,  7.23s/it]

TN_17694_2014 completed in 0:00:06.503938

 23%|██▎       | 985/4292 [2:31:01<6:14:34,  6.80s/it]

TN_19574_2014 completed in 0:00:05.782237

 23%|██▎       | 986/4292 [2:31:08<6:19:34,  6.89s/it]

TN_19898_2014 completed in 0:00:07.099689

 23%|██▎       | 987/4292 [2:31:16<6:35:07,  7.17s/it]

TX_5701_2014 completed in 0:00:07.836416

 23%|██▎       | 988/4292 [2:31:24<6:59:12,  7.61s/it]

TX_16604_2014 completed in 0:00:08.637567

 23%|██▎       | 989/4292 [2:31:37<8:17:51,  9.04s/it]

TX_17008_2014 completed in 0:00:12.381879

 23%|██▎       | 990/4292 [2:31:50<9:20:17, 10.18s/it]

TX_17698_2014 completed in 0:00:12.829255

 23%|██▎       | 991/4292 [2:31:59<8:59:41,  9.81s/it]

TX_55937_2014 completed in 0:00:08.935990

 23%|██▎       | 992/4292 [2:32:07<8:34:28,  9.35s/it]

UT_2010_2014 completed in 0:00:08.290558

 23%|██▎       | 993/4292 [2:32:13<7:48:02,  8.51s/it]

UT_11135_2014 completed in 0:00:06.547160

 23%|██▎       | 994/4292 [2:32:22<7:45:11,  8.46s/it]

UT_12866_2014 completed in 0:00:08.347715

 23%|██▎       | 995/4292 [2:32:31<8:00:52,  8.75s/it]

UT_14354_2014 completed in 0:00:09.422311

 23%|██▎       | 996/4292 [2:32:38<7:24:25,  8.09s/it]

UT_15444_2014 completed in 0:00:06.547335

 23%|██▎       | 997/4292 [2:32:47<7:37:41,  8.33s/it]

UT_17845_2014 completed in 0:00:08.902859

 23%|██▎       | 998/4292 [2:32:55<7:31:42,  8.23s/it]

UT_17874_2014 completed in 0:00:07.978159

 23%|██▎       | 999/4292 [2:33:00<6:50:16,  7.48s/it]

UT_18206_2014 completed in 0:00:05.718785

 23%|██▎       | 1000/4292 [2:33:08<6:45:44,  7.40s/it]

VA_84_2014 completed in 0:00:07.207292

 23%|██▎       | 1001/4292 [2:33:14<6:36:34,  7.23s/it]

VA_733_2014 completed in 0:00:06.844385

 23%|██▎       | 1002/4292 [2:33:26<7:52:25,  8.62s/it]

VA_17066_2014 completed in 0:00:11.848031

 23%|██▎       | 1003/4292 [2:33:36<8:09:24,  8.93s/it]

VA_19876_2014 completed in 0:00:09.656395

 23%|██▎       | 1004/4292 [2:33:43<7:41:59,  8.43s/it]

VA_19882_2014 completed in 0:00:07.267955

 23%|██▎       | 1005/4292 [2:33:51<7:29:12,  8.20s/it]

VA_40228_2014 completed in 0:00:07.660253

 23%|██▎       | 1006/4292 [2:33:58<7:19:40,  8.03s/it]

VT_2548_2014 completed in 0:00:07.626704

 23%|██▎       | 1007/4292 [2:34:06<7:08:08,  7.82s/it]

VT_7601_2014 completed in 0:00:07.332914

 23%|██▎       | 1008/4292 [2:34:12<6:47:08,  7.44s/it]

VT_19791_2014 completed in 0:00:06.543968

 24%|██▎       | 1009/4292 [2:34:22<7:25:27,  8.14s/it]

WA_3660_2014 completed in 0:00:09.779583

 24%|██▎       | 1010/4292 [2:34:28<6:54:48,  7.58s/it]

WA_14354_2014 completed in 0:00:06.281173

 24%|██▎       | 1011/4292 [2:34:36<6:52:21,  7.54s/it]

WA_15500_2014 completed in 0:00:07.440965

 24%|██▎       | 1012/4292 [2:34:43<6:41:45,  7.35s/it]

WA_16868_2014 completed in 0:00:06.900586

 24%|██▎       | 1013/4292 [2:34:49<6:19:06,  6.94s/it]

WA_17470_2014 completed in 0:00:05.969588

 24%|██▎       | 1014/4292 [2:34:54<5:56:00,  6.52s/it]

WA_18429_2014 completed in 0:00:05.533201

 24%|██▎       | 1015/4292 [2:35:01<5:56:45,  6.53s/it]

WA_20169_2014 completed in 0:00:06.563374

 24%|██▎       | 1016/4292 [2:35:08<6:03:16,  6.65s/it]

WI_4715_2014 completed in 0:00:06.935239

 24%|██▎       | 1017/4292 [2:35:14<5:56:37,  6.53s/it]

WI_5574_2014 completed in 0:00:06.253141

 24%|██▎       | 1018/4292 [2:35:21<6:05:07,  6.69s/it]

WI_11479_2014 completed in 0:00:07.058669

 24%|██▎       | 1019/4292 [2:35:28<6:10:41,  6.80s/it]

WI_13697_2014 completed in 0:00:07.036940

 24%|██▍       | 1020/4292 [2:35:35<6:14:32,  6.87s/it]

WI_13815_2014 completed in 0:00:07.037401

 24%|██▍       | 1021/4292 [2:35:44<6:50:16,  7.53s/it]

WI_20847_2014 completed in 0:00:09.059075

 24%|██▍       | 1022/4292 [2:35:54<7:32:55,  8.31s/it]

WI_20856_2014 completed in 0:00:10.136430

 24%|██▍       | 1023/4292 [2:36:04<7:47:01,  8.57s/it]

WI_20860_2014 completed in 0:00:09.181345

 24%|██▍       | 1024/4292 [2:36:11<7:31:24,  8.29s/it]

WV_733_2014 completed in 0:00:07.623727

 24%|██▍       | 1025/4292 [2:36:19<7:29:41,  8.26s/it]

WV_12796_2014 completed in 0:00:08.189929

 24%|██▍       | 1026/4292 [2:36:27<7:13:47,  7.97s/it]

WV_15263_2014 completed in 0:00:07.292774

 24%|██▍       | 1027/4292 [2:36:33<6:48:49,  7.51s/it]

WV_20521_2014 completed in 0:00:06.447326

 24%|██▍       | 1028/4292 [2:36:39<6:27:37,  7.13s/it]

WY_3461_2014 completed in 0:00:06.216978

 24%|██▍       | 1029/4292 [2:36:48<6:54:27,  7.62s/it]

WY_8566_2014 completed in 0:00:08.776372

 24%|██▍       | 1030/4292 [2:36:54<6:27:16,  7.12s/it]

WY_11273_2014 completed in 0:00:05.960827

 24%|██▍       | 1031/4292 [2:37:01<6:31:44,  7.21s/it]

WY_14354_2014 completed in 0:00:07.403750

 24%|██▍       | 1032/4292 [2:37:11<7:04:52,  7.82s/it]

WY_19156_2014 completed in 0:00:09.247008

 24%|██▍       | 1033/4292 [2:37:17<6:33:28,  7.24s/it]

WY_27058_2014 completed in 0:00:05.899624

 24%|██▍       | 1034/4292 [2:37:22<6:06:46,  6.75s/it]

NE_6779_2014 completed in 0:00:05.611799

 24%|██▍       | 1035/4292 [2:37:31<6:33:46,  7.25s/it]

AK_219_2014 completed in 0:00:08.413907

 24%|██▍       | 1036/4292 [2:37:39<6:56:03,  7.67s/it]

CT_7716_2014 completed in 0:00:08.629092

 24%|██▍       | 1037/4292 [2:37:48<7:07:02,  7.87s/it]

AR_13718_2014 completed in 0:00:08.348935

 24%|██▍       | 1038/4292 [2:37:55<7:03:18,  7.81s/it]

KY_17564_2014 completed in 0:00:07.644804

 24%|██▍       | 1039/4292 [2:38:02<6:42:52,  7.43s/it]

NC_6235_2014 completed in 0:00:06.556636

 24%|██▍       | 1040/4292 [2:38:09<6:39:59,  7.38s/it]

WY_7222_2014 completed in 0:00:07.259612

 24%|██▍       | 1041/4292 [2:38:20<7:39:50,  8.49s/it]

AK_219_2015 completed in 0:00:11.069141

 24%|██▍       | 1042/4292 [2:38:33<8:48:27,  9.76s/it]

AK_599_2015 completed in 0:00:12.716850

 24%|██▍       | 1043/4292 [2:38:41<8:24:34,  9.32s/it]

AK_3522_2015 completed in 0:00:08.294466

 24%|██▍       | 1044/4292 [2:38:53<9:07:11, 10.11s/it]

AK_7353_2015 completed in 0:00:11.950862

 24%|██▍       | 1045/4292 [2:39:01<8:38:46,  9.59s/it]

AK_11824_2015 completed in 0:00:08.367363

 24%|██▍       | 1046/4292 [2:39:09<8:08:08,  9.02s/it]

AK_19558_2015 completed in 0:00:07.706342

 24%|██▍       | 1047/4292 [2:39:22<9:13:39, 10.24s/it]

AL_195_2015 completed in 0:00:13.069391

 24%|██▍       | 1048/4292 [2:39:33<9:14:45, 10.26s/it]

AR_814_2015 completed in 0:00:10.314227

 24%|██▍       | 1049/4292 [2:39:48<10:31:20, 11.68s/it]

AR_817_2015 completed in 0:00:14.993539

 24%|██▍       | 1050/4292 [2:39:55<9:29:49, 10.55s/it]

AR_3093_2015 completed in 0:00:07.896348

 24%|██▍       | 1051/4292 [2:40:07<9:45:27, 10.84s/it]

AR_5860_2015 completed in 0:00:11.520869

 25%|██▍       | 1052/4292 [2:40:18<9:44:46, 10.83s/it]

AR_6342_2015 completed in 0:00:10.806098

 25%|██▍       | 1053/4292 [2:40:26<8:56:36,  9.94s/it]

AR_13718_2015 completed in 0:00:07.865650

 25%|██▍       | 1054/4292 [2:40:34<8:24:59,  9.36s/it]

AR_14063_2015 completed in 0:00:07.996220

 25%|██▍       | 1055/4292 [2:40:42<8:07:57,  9.04s/it]

AR_17698_2015 completed in 0:00:08.314498

 25%|██▍       | 1056/4292 [2:40:49<7:31:28,  8.37s/it]

AZ_176_2015 completed in 0:00:06.798157

 25%|██▍       | 1057/4292 [2:40:59<8:03:43,  8.97s/it]

AZ_803_2015 completed in 0:00:10.372187

 25%|██▍       | 1058/4292 [2:41:08<8:09:11,  9.08s/it]

AZ_12919_2015 completed in 0:00:09.318475

 25%|██▍       | 1059/4292 [2:41:15<7:22:38,  8.21s/it]

AZ_16572_2015 completed in 0:00:06.205001

 25%|██▍       | 1060/4292 [2:41:21<6:54:41,  7.70s/it]

AZ_19189_2015 completed in 0:00:06.492990

 25%|██▍       | 1061/4292 [2:41:32<7:45:52,  8.65s/it]

AZ_19728_2015 completed in 0:00:10.872997

 25%|██▍       | 1062/4292 [2:41:42<8:04:41,  9.00s/it]

AZ_21538_2015 completed in 0:00:09.824738

 25%|██▍       | 1063/4292 [2:41:48<7:22:38,  8.23s/it]

AZ_24211_2015 completed in 0:00:06.407613

 25%|██▍       | 1064/4292 [2:42:00<8:23:57,  9.37s/it]

CA_9216_2015 completed in 0:00:12.031960

 25%|██▍       | 1065/4292 [2:42:08<7:58:35,  8.90s/it]

CA_11208_2015 completed in 0:00:07.803440

 25%|██▍       | 1066/4292 [2:42:16<7:38:37,  8.53s/it]

CA_12745_2015 completed in 0:00:07.669310

 25%|██▍       | 1067/4292 [2:42:33<9:57:29, 11.12s/it]

CA_14328_2015 completed in 0:00:17.150020

 25%|██▍       | 1068/4292 [2:42:40<8:59:41, 10.04s/it]

CA_14354_2015 completed in 0:00:07.541128

 25%|██▍       | 1069/4292 [2:42:51<9:07:21, 10.19s/it]

CA_14534_2015 completed in 0:00:10.528897

 25%|██▍       | 1070/4292 [2:42:57<8:07:29,  9.08s/it]

CA_16534_2015 completed in 0:00:06.483835

 25%|██▍       | 1071/4292 [2:43:07<8:13:30,  9.19s/it]

CA_16609_2015 completed in 0:00:09.459143

 25%|██▍       | 1072/4292 [2:43:22<9:43:56, 10.88s/it]

CA_17609_2015 completed in 0:00:14.814155

 25%|██▌       | 1073/4292 [2:43:38<11:02:17, 12.34s/it]

CA_17612_2015 completed in 0:00:15.758650

 25%|██▌       | 1074/4292 [2:43:46<10:01:13, 11.21s/it]

CA_19281_2015 completed in 0:00:08.561891

 25%|██▌       | 1075/4292 [2:43:55<9:24:29, 10.53s/it]

CO_3989_2015 completed in 0:00:08.936404

 25%|██▌       | 1076/4292 [2:44:04<8:57:49, 10.03s/it]

CO_6604_2015 completed in 0:00:08.879845

 25%|██▌       | 1077/4292 [2:44:11<8:14:08,  9.22s/it]

CO_9336_2015 completed in 0:00:07.326191

 25%|██▌       | 1078/4292 [2:44:18<7:38:22,  8.56s/it]

CO_12866_2015 completed in 0:00:07.004545

 25%|██▌       | 1079/4292 [2:44:25<7:08:04,  7.99s/it]

CO_15257_2015 completed in 0:00:06.679674

 25%|██▌       | 1080/4292 [2:44:36<7:50:47,  8.79s/it]

CO_15466_2015 completed in 0:00:10.660503

 25%|██▌       | 1081/4292 [2:44:45<8:07:54,  9.12s/it]

CO_16603_2015 completed in 0:00:09.868500

 25%|██▌       | 1082/4292 [2:44:54<8:04:28,  9.06s/it]

CO_19499_2015 completed in 0:00:08.907034

 25%|██▌       | 1083/4292 [2:45:02<7:47:12,  8.74s/it]

CO_27058_2015 completed in 0:00:07.987822

 25%|██▌       | 1084/4292 [2:45:12<8:06:32,  9.10s/it]

CO_56146_2015 completed in 0:00:09.949806

 25%|██▌       | 1085/4292 [2:45:22<8:20:18,  9.36s/it]

CT_4176_2015 completed in 0:00:09.966258

 25%|██▌       | 1086/4292 [2:45:29<7:37:37,  8.56s/it]

CT_7716_2015 completed in 0:00:06.702366

 25%|██▌       | 1087/4292 [2:45:36<7:16:37,  8.17s/it]

CT_19497_2015 completed in 0:00:07.262209

 25%|██▌       | 1088/4292 [2:45:42<6:45:20,  7.59s/it]

CT_20038_2015 completed in 0:00:06.228770

 25%|██▌       | 1089/4292 [2:45:49<6:30:21,  7.31s/it]

DC_15270_2015 completed in 0:00:06.657576

 25%|██▌       | 1090/4292 [2:45:56<6:30:05,  7.31s/it]

DE_5027_2015 completed in 0:00:07.302242

 25%|██▌       | 1091/4292 [2:46:06<7:02:35,  7.92s/it]

DE_5070_2015 completed in 0:00:09.347068

 25%|██▌       | 1092/4292 [2:46:12<6:40:52,  7.52s/it]

DE_5335_2015 completed in 0:00:06.571213

 25%|██▌       | 1093/4292 [2:46:19<6:23:44,  7.20s/it]

DE_13519_2015 completed in 0:00:06.451426

 25%|██▌       | 1094/4292 [2:46:27<6:36:08,  7.43s/it]

FL_6452_2015 completed in 0:00:07.980084

 26%|██▌       | 1095/4292 [2:46:38<7:34:01,  8.52s/it]

FL_6455_2015 completed in 0:00:11.060078

 26%|██▌       | 1096/4292 [2:46:49<8:23:26,  9.45s/it]

FL_6457_2015 completed in 0:00:11.620324

 26%|██▌       | 1097/4292 [2:46:55<7:19:00,  8.24s/it]

FL_7801_2015 completed in 0:00:05.424054

 26%|██▌       | 1098/4292 [2:47:01<6:38:49,  7.49s/it]

FL_9617_2015 completed in 0:00:05.736222

 26%|██▌       | 1099/4292 [2:47:06<6:10:43,  6.97s/it]

FL_18454_2015 completed in 0:00:05.735419

 26%|██▌       | 1100/4292 [2:47:12<5:42:24,  6.44s/it]

GA_3916_2015 completed in 0:00:05.199094

 26%|██▌       | 1101/4292 [2:47:18<5:35:54,  6.32s/it]

HI_8287_2015 completed in 0:00:06.034918

 26%|██▌       | 1102/4292 [2:47:25<5:47:42,  6.54s/it]

HI_10071_2015 completed in 0:00:07.060818

 26%|██▌       | 1103/4292 [2:47:30<5:35:51,  6.32s/it]

HI_11843_2015 completed in 0:00:05.800337

 26%|██▌       | 1104/4292 [2:47:38<5:47:30,  6.54s/it]

HI_19547_2015 completed in 0:00:07.055823

 26%|██▌       | 1105/4292 [2:47:44<5:48:08,  6.55s/it]

IA_9417_2015 completed in 0:00:06.586227

 26%|██▌       | 1106/4292 [2:47:50<5:39:02,  6.39s/it]

IA_12341_2015 completed in 0:00:05.988889

 26%|██▌       | 1107/4292 [2:47:57<5:41:43,  6.44s/it]

ID_9187_2015 completed in 0:00:06.554646

 26%|██▌       | 1108/4292 [2:48:03<5:40:48,  6.42s/it]

ID_9191_2015 completed in 0:00:06.385456

 26%|██▌       | 1109/4292 [2:48:09<5:25:06,  6.13s/it]

ID_10454_2015 completed in 0:00:05.438340

 26%|██▌       | 1110/4292 [2:48:15<5:35:04,  6.32s/it]

ID_11273_2015 completed in 0:00:06.758904

 26%|██▌       | 1111/4292 [2:48:24<6:12:53,  7.03s/it]

ID_14354_2015 completed in 0:00:08.701104

 26%|██▌       | 1112/4292 [2:48:29<5:48:51,  6.58s/it]

ID_20169_2015 completed in 0:00:05.528989

 26%|██▌       | 1113/4292 [2:48:36<5:47:48,  6.56s/it]

IL_4110_2015 completed in 0:00:06.522287

 26%|██▌       | 1114/4292 [2:48:42<5:46:17,  6.54s/it]

IL_12341_2015 completed in 0:00:06.474913

 26%|██▌       | 1115/4292 [2:48:49<5:48:30,  6.58s/it]

IL_13032_2015 completed in 0:00:06.682832

 26%|██▌       | 1116/4292 [2:49:06<8:32:43,  9.69s/it]

IL_56697_2015 completed in 0:00:16.928959

 26%|██▌       | 1117/4292 [2:49:13<7:50:26,  8.89s/it]

IN_9273_2015 completed in 0:00:07.032423

 26%|██▌       | 1118/4292 [2:49:32<10:24:52, 11.81s/it]

IN_9324_2015 completed in 0:00:18.629472

 26%|██▌       | 1119/4292 [2:49:47<11:25:54, 12.97s/it]

IN_13756_2015 completed in 0:00:15.670687

 26%|██▌       | 1120/4292 [2:49:57<10:36:01, 12.03s/it]

IN_15470_2015 completed in 0:00:09.837895

 26%|██▌       | 1121/4292 [2:50:03<8:56:22, 10.15s/it]

IN_17633_2015 completed in 0:00:05.757774

 26%|██▌       | 1122/4292 [2:50:09<7:46:44,  8.83s/it]

KS_9996_2015 completed in 0:00:05.765671

 26%|██▌       | 1123/4292 [2:50:18<7:54:48,  8.99s/it]

KS_10000_2015 completed in 0:00:09.351707

 26%|██▌       | 1124/4292 [2:50:24<7:12:36,  8.19s/it]

KS_10005_2015 completed in 0:00:06.332785

 26%|██▌       | 1125/4292 [2:50:31<6:44:14,  7.66s/it]

KS_22500_2015 completed in 0:00:06.409562

 26%|██▌       | 1126/4292 [2:50:39<6:54:10,  7.85s/it]

KY_9964_2015 completed in 0:00:08.289094

 26%|██▋       | 1127/4292 [2:50:59<10:07:54, 11.52s/it]

KY_10171_2015 completed in 0:00:20.098848

 26%|██▋       | 1128/4292 [2:51:06<8:58:25, 10.21s/it]

KY_11249_2015 completed in 0:00:07.142839

 26%|██▋       | 1129/4292 [2:51:13<7:56:54,  9.05s/it]

KY_17564_2015 completed in 0:00:06.330829

 26%|██▋       | 1130/4292 [2:51:21<7:42:44,  8.78s/it]

KY_19446_2015 completed in 0:00:08.159269

 26%|██▋       | 1131/4292 [2:51:29<7:23:58,  8.43s/it]

KY_22053_2015 completed in 0:00:07.601366

 26%|██▋       | 1132/4292 [2:51:36<7:01:50,  8.01s/it]

KY_49998_2015 completed in 0:00:07.035087

 26%|██▋       | 1133/4292 [2:51:44<7:11:15,  8.19s/it]

LA_3265_2015 completed in 0:00:08.613077

 26%|██▋       | 1134/4292 [2:51:54<7:39:47,  8.74s/it]

LA_11241_2015 completed in 0:00:10.000626

 26%|██▋       | 1135/4292 [2:52:02<7:27:01,  8.50s/it]

LA_13478_2015 completed in 0:00:07.935045

 26%|██▋       | 1136/4292 [2:52:08<6:51:48,  7.83s/it]

LA_17698_2015 completed in 0:00:06.272805

 26%|██▋       | 1137/4292 [2:52:17<7:07:48,  8.14s/it]

LA_55936_2015 completed in 0:00:08.850846

 27%|██▋       | 1138/4292 [2:52:25<6:57:56,  7.95s/it]

MA_6374_2015 completed in 0:00:07.517067

 27%|██▋       | 1139/4292 [2:52:37<7:57:36,  9.09s/it]

MA_8774_2015 completed in 0:00:11.742662

 27%|██▋       | 1140/4292 [2:52:45<7:43:07,  8.82s/it]

MA_11804_2015 completed in 0:00:08.178758

 27%|██▋       | 1141/4292 [2:52:52<7:22:15,  8.42s/it]

MA_13206_2015 completed in 0:00:07.494731

 27%|██▋       | 1142/4292 [2:52:59<6:57:04,  7.94s/it]

MA_15748_2015 completed in 0:00:06.830540

 27%|██▋       | 1143/4292 [2:53:06<6:43:14,  7.68s/it]

MA_20455_2015 completed in 0:00:07.073306

 27%|██▋       | 1144/4292 [2:53:14<6:52:57,  7.87s/it]

MA_54913_2015 completed in 0:00:08.308423

 27%|██▋       | 1145/4292 [2:53:27<8:10:06,  9.34s/it]

MD_1167_2015 completed in 0:00:12.780672

 27%|██▋       | 1146/4292 [2:53:38<8:25:13,  9.64s/it]

MD_5027_2015 completed in 0:00:10.314107

 27%|██▋       | 1147/4292 [2:53:46<8:08:36,  9.32s/it]

MD_15263_2015 completed in 0:00:08.588833

 27%|██▋       | 1148/4292 [2:53:56<8:14:28,  9.44s/it]

MD_15270_2015 completed in 0:00:09.698687

 27%|██▋       | 1149/4292 [2:54:03<7:34:53,  8.68s/it]

ME_1179_2015 completed in 0:00:06.926973

 27%|██▋       | 1150/4292 [2:54:12<7:40:25,  8.79s/it]

ME_3266_2015 completed in 0:00:09.044347

 27%|██▋       | 1151/4292 [2:54:20<7:38:20,  8.76s/it]

MI_392_2015 completed in 0:00:08.663287

 27%|██▋       | 1152/4292 [2:54:27<7:09:19,  8.20s/it]

MI_3828_2015 completed in 0:00:06.915423

 27%|██▋       | 1153/4292 [2:54:38<7:48:05,  8.95s/it]

MI_4254_2015 completed in 0:00:10.681658

 27%|██▋       | 1154/4292 [2:54:48<8:05:06,  9.28s/it]

MI_5109_2015 completed in 0:00:10.040669

 27%|██▋       | 1155/4292 [2:54:55<7:30:41,  8.62s/it]

MI_9324_2015 completed in 0:00:07.088410

 27%|██▋       | 1156/4292 [2:55:04<7:33:36,  8.68s/it]

MI_10704_2015 completed in 0:00:08.814355

 27%|██▋       | 1157/4292 [2:55:13<7:42:33,  8.85s/it]

MI_19578_2015 completed in 0:00:09.257626

 27%|██▋       | 1158/4292 [2:55:20<7:15:02,  8.33s/it]

MI_20847_2015 completed in 0:00:07.100150

 27%|██▋       | 1159/4292 [2:55:27<6:52:14,  7.89s/it]

MI_20860_2015 completed in 0:00:06.877396

 27%|██▋       | 1160/4292 [2:55:35<6:57:45,  8.00s/it]

MN_689_2015 completed in 0:00:08.254818

 27%|██▋       | 1161/4292 [2:55:45<7:18:39,  8.41s/it]

MN_5574_2015 completed in 0:00:09.345658

 27%|██▋       | 1162/4292 [2:55:54<7:27:34,  8.58s/it]

MN_9417_2015 completed in 0:00:08.983952

 27%|██▋       | 1163/4292 [2:56:04<7:59:42,  9.20s/it]

MN_12647_2015 completed in 0:00:10.642025

 27%|██▋       | 1164/4292 [2:56:13<7:47:55,  8.98s/it]

MN_13781_2015 completed in 0:00:08.453828

 27%|██▋       | 1165/4292 [2:56:24<8:22:04,  9.63s/it]

MN_14232_2015 completed in 0:00:11.168134

 27%|██▋       | 1166/4292 [2:56:34<8:20:13,  9.60s/it]

MN_16181_2015 completed in 0:00:09.525436

 27%|██▋       | 1167/4292 [2:56:42<7:57:23,  9.17s/it]

MN_17267_2015 completed in 0:00:08.148541

 27%|██▋       | 1168/4292 [2:56:49<7:31:16,  8.67s/it]

MN_20996_2015 completed in 0:00:07.502828

 27%|██▋       | 1169/4292 [2:56:57<7:22:23,  8.50s/it]

MN_25177_2015 completed in 0:00:08.106741

 27%|██▋       | 1170/4292 [2:57:04<6:52:23,  7.93s/it]

MO_4675_2015 completed in 0:00:06.585736

 27%|██▋       | 1171/4292 [2:57:11<6:44:59,  7.79s/it]

MO_5860_2015 completed in 0:00:07.458896

 27%|██▋       | 1172/4292 [2:57:19<6:33:55,  7.58s/it]

MO_9231_2015 completed in 0:00:07.083922

 27%|██▋       | 1173/4292 [2:57:27<6:43:25,  7.76s/it]

MO_10000_2015 completed in 0:00:08.191480

 27%|██▋       | 1174/4292 [2:57:43<8:55:36, 10.31s/it]

MO_12698_2015 completed in 0:00:16.246731

 27%|██▋       | 1175/4292 [2:57:50<8:11:17,  9.46s/it]

MO_17833_2015 completed in 0:00:07.473770

 27%|██▋       | 1176/4292 [2:57:59<8:02:44,  9.30s/it]

MO_19436_2015 completed in 0:00:08.917073

 27%|██▋       | 1177/4292 [2:58:07<7:39:30,  8.85s/it]

MS_3841_2015 completed in 0:00:07.813459

 27%|██▋       | 1178/4292 [2:58:13<6:57:21,  8.04s/it]

MS_17647_2015 completed in 0:00:06.152037

 27%|██▋       | 1179/4292 [2:58:18<6:08:11,  7.10s/it]

MT_6395_2015 completed in 0:00:04.890054

 27%|██▋       | 1180/4292 [2:58:26<6:15:00,  7.23s/it]

MT_12692_2015 completed in 0:00:07.536202

 28%|██▊       | 1181/4292 [2:58:32<6:01:09,  6.97s/it]

MT_12825_2015 completed in 0:00:06.347180

 28%|██▊       | 1182/4292 [2:58:39<6:03:54,  7.02s/it]

MT_19603_2015 completed in 0:00:07.148504

 28%|██▊       | 1183/4292 [2:58:46<5:55:12,  6.85s/it]

MT_20997_2015 completed in 0:00:06.467606

 28%|██▊       | 1184/4292 [2:58:55<6:39:37,  7.71s/it]

NC_3046_2015 completed in 0:00:09.719764

 28%|██▊       | 1185/4292 [2:59:03<6:42:20,  7.77s/it]

NC_5416_2015 completed in 0:00:07.896045

 28%|██▊       | 1186/4292 [2:59:10<6:22:30,  7.39s/it]

NC_9837_2015 completed in 0:00:06.500603

 28%|██▊       | 1187/4292 [2:59:16<6:08:47,  7.13s/it]

NC_16496_2015 completed in 0:00:06.512685

 28%|██▊       | 1188/4292 [2:59:33<8:32:26,  9.91s/it]

NC_19876_2015 completed in 0:00:16.388343

 28%|██▊       | 1189/4292 [2:59:38<7:27:01,  8.64s/it]

NC_24889_2015 completed in 0:00:05.698657

 28%|██▊       | 1190/4292 [2:59:46<7:05:40,  8.23s/it]

ND_12301_2015 completed in 0:00:07.276244

 28%|██▊       | 1191/4292 [2:59:53<6:44:30,  7.83s/it]

ND_14232_2015 completed in 0:00:06.876512

 28%|██▊       | 1192/4292 [2:59:59<6:18:40,  7.33s/it]

ND_19790_2015 completed in 0:00:06.166821

 28%|██▊       | 1193/4292 [3:00:05<6:01:38,  7.00s/it]

ND_24949_2015 completed in 0:00:06.236954

 28%|██▊       | 1194/4292 [3:00:16<6:56:20,  8.06s/it]

NE_4373_2015 completed in 0:00:10.539225

 28%|██▊       | 1195/4292 [3:00:23<6:53:46,  8.02s/it]

NE_6779_2015 completed in 0:00:07.905731

 28%|██▊       | 1196/4292 [3:00:30<6:37:46,  7.71s/it]

NE_11018_2015 completed in 0:00:06.990669

 28%|██▊       | 1197/4292 [3:00:38<6:39:54,  7.75s/it]

NE_11251_2015 completed in 0:00:07.853734

 28%|██▊       | 1198/4292 [3:00:46<6:36:56,  7.70s/it]

NE_12539_2015 completed in 0:00:07.568498

 28%|██▊       | 1199/4292 [3:00:52<6:08:49,  7.15s/it]

NE_13337_2015 completed in 0:00:05.882070

 28%|██▊       | 1200/4292 [3:01:00<6:18:21,  7.34s/it]

NE_13664_2015 completed in 0:00:07.778753

 28%|██▊       | 1201/4292 [3:01:06<6:10:42,  7.20s/it]

NE_14127_2015 completed in 0:00:06.853640

 28%|██▊       | 1202/4292 [3:01:14<6:11:05,  7.21s/it]

NE_17642_2015 completed in 0:00:07.227613

 28%|██▊       | 1203/4292 [3:01:21<6:20:35,  7.39s/it]

NH_13441_2015 completed in 0:00:07.827803

 28%|██▊       | 1204/4292 [3:01:30<6:34:44,  7.67s/it]

NH_15472_2015 completed in 0:00:08.314382

 28%|██▊       | 1205/4292 [3:01:38<6:38:14,  7.74s/it]

NH_24590_2015 completed in 0:00:07.903991

 28%|██▊       | 1206/4292 [3:01:46<6:55:03,  8.07s/it]

NJ_963_2015 completed in 0:00:08.837081

 28%|██▊       | 1207/4292 [3:01:54<6:48:19,  7.94s/it]

NJ_9726_2015 completed in 0:00:07.639812

 28%|██▊       | 1208/4292 [3:02:01<6:35:29,  7.69s/it]

NJ_15477_2015 completed in 0:00:07.116694

 28%|██▊       | 1209/4292 [3:02:09<6:32:20,  7.64s/it]

NJ_16213_2015 completed in 0:00:07.497888

 28%|██▊       | 1210/4292 [3:02:17<6:46:07,  7.91s/it]

NM_3287_2015 completed in 0:00:08.537180

 28%|██▊       | 1211/4292 [3:02:25<6:39:27,  7.78s/it]

NM_5701_2015 completed in 0:00:07.481303

 28%|██▊       | 1212/4292 [3:02:33<6:40:18,  7.80s/it]

NM_6204_2015 completed in 0:00:07.841642

 28%|██▊       | 1213/4292 [3:02:40<6:37:43,  7.75s/it]

NM_11204_2015 completed in 0:00:07.637672

 28%|██▊       | 1214/4292 [3:02:50<7:04:29,  8.27s/it]

NM_15473_2015 completed in 0:00:09.492759

 28%|██▊       | 1215/4292 [3:02:57<6:41:55,  7.84s/it]

NM_17718_2015 completed in 0:00:06.816087

 28%|██▊       | 1216/4292 [3:03:03<6:19:44,  7.41s/it]

NV_2008_2015 completed in 0:00:06.402446

 28%|██▊       | 1217/4292 [3:03:10<6:10:31,  7.23s/it]

NV_13073_2015 completed in 0:00:06.810366

 28%|██▊       | 1218/4292 [3:03:18<6:23:59,  7.49s/it]

NV_13407_2015 completed in 0:00:08.112939

 28%|██▊       | 1219/4292 [3:03:26<6:26:42,  7.55s/it]

NV_17166_2015 completed in 0:00:07.679118

 28%|██▊       | 1220/4292 [3:03:36<7:16:51,  8.53s/it]

NV_19840_2015 completed in 0:00:10.818408

 28%|██▊       | 1221/4292 [3:03:43<6:52:12,  8.05s/it]

NY_3249_2015 completed in 0:00:06.935276

 28%|██▊       | 1222/4292 [3:03:49<6:22:57,  7.48s/it]

NY_4226_2015 completed in 0:00:06.155458

 28%|██▊       | 1223/4292 [3:03:56<6:11:00,  7.25s/it]

NY_11171_2015 completed in 0:00:06.709130

 29%|██▊       | 1224/4292 [3:04:07<7:09:08,  8.39s/it]

NY_13511_2015 completed in 0:00:11.049717

 29%|██▊       | 1225/4292 [3:04:18<7:49:18,  9.18s/it]

NY_13573_2015 completed in 0:00:11.020590

 29%|██▊       | 1226/4292 [3:04:27<7:36:23,  8.93s/it]

NY_14154_2015 completed in 0:00:08.347301

 29%|██▊       | 1227/4292 [3:04:33<6:58:33,  8.19s/it]

NY_16183_2015 completed in 0:00:06.467600

 29%|██▊       | 1228/4292 [3:04:40<6:43:11,  7.90s/it]

OH_3542_2015 completed in 0:00:07.198795

 29%|██▊       | 1229/4292 [3:04:46<6:14:42,  7.34s/it]

OH_3755_2015 completed in 0:00:06.037979

 29%|██▊       | 1230/4292 [3:04:56<6:50:57,  8.05s/it]

OH_4922_2015 completed in 0:00:09.715586

 29%|██▊       | 1231/4292 [3:05:04<6:45:12,  7.94s/it]

OH_13998_2015 completed in 0:00:07.684309

 29%|██▊       | 1232/4292 [3:05:13<7:10:28,  8.44s/it]

OH_14006_2015 completed in 0:00:09.602012

 29%|██▊       | 1233/4292 [3:05:23<7:28:26,  8.80s/it]

OH_18997_2015 completed in 0:00:09.622817

 29%|██▉       | 1234/4292 [3:05:30<6:54:25,  8.13s/it]

OK_5860_2015 completed in 0:00:06.575828

 29%|██▉       | 1235/4292 [3:05:35<6:17:50,  7.42s/it]

OK_13734_2015 completed in 0:00:05.741864

 29%|██▉       | 1236/4292 [3:05:42<6:12:29,  7.31s/it]

OK_14062_2015 completed in 0:00:07.072704

 29%|██▉       | 1237/4292 [3:05:56<7:46:58,  9.17s/it]

OK_14063_2015 completed in 0:00:13.505605

 29%|██▉       | 1238/4292 [3:06:03<7:21:59,  8.68s/it]

OK_15474_2015 completed in 0:00:07.544605

 29%|██▉       | 1239/4292 [3:06:10<6:52:31,  8.11s/it]

OK_19785_2015 completed in 0:00:06.762111

 29%|██▉       | 1240/4292 [3:06:18<6:51:32,  8.09s/it]

OR_6022_2015 completed in 0:00:08.051199

 29%|██▉       | 1241/4292 [3:06:25<6:28:53,  7.65s/it]

OR_9191_2015 completed in 0:00:06.611723

 29%|██▉       | 1242/4292 [3:06:34<6:47:32,  8.02s/it]

OR_14354_2015 completed in 0:00:08.877820

 29%|██▉       | 1243/4292 [3:06:40<6:19:22,  7.47s/it]

OR_15248_2015 completed in 0:00:06.177178

 29%|██▉       | 1244/4292 [3:06:46<6:00:21,  7.09s/it]

OR_18260_2015 completed in 0:00:06.225007

 29%|██▉       | 1245/4292 [3:06:53<6:00:05,  7.09s/it]

OR_40437_2015 completed in 0:00:07.082896

 29%|██▉       | 1246/4292 [3:06:58<5:29:38,  6.49s/it]

PA_3597_2015 completed in 0:00:05.098590

 29%|██▉       | 1247/4292 [3:07:05<5:28:28,  6.47s/it]

PA_5487_2015 completed in 0:00:06.422744

 29%|██▉       | 1248/4292 [3:07:13<5:55:14,  7.00s/it]

PA_12390_2015 completed in 0:00:08.237768

 29%|██▉       | 1249/4292 [3:07:21<6:14:12,  7.38s/it]

PA_14711_2015 completed in 0:00:08.255731

 29%|██▉       | 1250/4292 [3:07:31<6:50:46,  8.10s/it]

PA_14715_2015 completed in 0:00:09.789249

 29%|██▉       | 1251/4292 [3:07:37<6:11:12,  7.32s/it]

PA_14716_2015 completed in 0:00:05.503355

 29%|██▉       | 1252/4292 [3:07:43<5:59:00,  7.09s/it]

PA_14940_2015 completed in 0:00:06.527870

 29%|██▉       | 1253/4292 [3:07:50<5:51:16,  6.94s/it]

PA_15045_2015 completed in 0:00:06.583356

 29%|██▉       | 1254/4292 [3:07:55<5:25:09,  6.42s/it]

PA_19390_2015 completed in 0:00:05.222766

 29%|██▉       | 1255/4292 [3:08:00<5:05:14,  6.03s/it]

PA_20334_2015 completed in 0:00:05.116739

 29%|██▉       | 1256/4292 [3:08:09<5:44:32,  6.81s/it]

PA_20387_2015 completed in 0:00:08.625248

 29%|██▉       | 1257/4292 [3:08:14<5:23:31,  6.40s/it]

RI_1857_2015 completed in 0:00:05.428519

 29%|██▉       | 1258/4292 [3:08:20<5:09:37,  6.12s/it]

RI_13214_2015 completed in 0:00:05.486360

 29%|██▉       | 1259/4292 [3:08:33<6:59:39,  8.30s/it]

SC_1613_2015 completed in 0:00:13.383945

 29%|██▉       | 1260/4292 [3:08:43<7:21:15,  8.73s/it]

SC_3046_2015 completed in 0:00:09.734861

 29%|██▉       | 1261/4292 [3:08:52<7:32:27,  8.96s/it]

SC_5416_2015 completed in 0:00:09.479327

 29%|██▉       | 1262/4292 [3:08:58<6:51:48,  8.15s/it]

SC_14398_2015 completed in 0:00:06.282002

 29%|██▉       | 1263/4292 [3:09:05<6:34:13,  7.81s/it]

SC_17539_2015 completed in 0:00:06.997504

 29%|██▉       | 1264/4292 [3:09:13<6:29:44,  7.72s/it]

SC_17543_2015 completed in 0:00:07.515829

 29%|██▉       | 1265/4292 [3:09:19<6:04:59,  7.23s/it]

SD_1769_2015 completed in 0:00:06.094768

 29%|██▉       | 1266/4292 [3:09:25<5:44:21,  6.83s/it]

SD_13337_2015 completed in 0:00:05.878764

 30%|██▉       | 1267/4292 [3:09:33<6:07:13,  7.28s/it]

SD_14232_2015 completed in 0:00:08.346644

 30%|██▉       | 1268/4292 [3:09:40<5:58:12,  7.11s/it]

SD_17267_2015 completed in 0:00:06.693544

 30%|██▉       | 1269/4292 [3:09:47<5:53:10,  7.01s/it]

SD_19293_2015 completed in 0:00:06.781658

 30%|██▉       | 1270/4292 [3:09:53<5:34:15,  6.64s/it]

SD_20401_2015 completed in 0:00:05.764623

 30%|██▉       | 1271/4292 [3:09:57<4:59:45,  5.95s/it]

TN_10331_2015 completed in 0:00:04.358414

 30%|██▉       | 1272/4292 [3:10:04<5:22:10,  6.40s/it]

TX_5701_2015 completed in 0:00:07.444368

 30%|██▉       | 1273/4292 [3:10:10<5:17:12,  6.30s/it]

TX_16604_2015 completed in 0:00:06.077938

 30%|██▉       | 1274/4292 [3:10:20<6:04:19,  7.24s/it]

TX_17698_2015 completed in 0:00:09.432556

 30%|██▉       | 1275/4292 [3:10:29<6:29:45,  7.75s/it]

TX_55937_2015 completed in 0:00:08.936591

 30%|██▉       | 1276/4292 [3:10:38<6:51:14,  8.18s/it]

UT_2010_2015 completed in 0:00:09.182793

 30%|██▉       | 1277/4292 [3:10:46<6:50:41,  8.17s/it]

UT_11135_2015 completed in 0:00:08.152902

 30%|██▉       | 1278/4292 [3:10:52<6:13:37,  7.44s/it]

UT_12866_2015 completed in 0:00:05.721757

 30%|██▉       | 1279/4292 [3:11:00<6:29:46,  7.76s/it]

UT_14354_2015 completed in 0:00:08.516834

 30%|██▉       | 1280/4292 [3:11:07<6:12:37,  7.42s/it]

UT_15444_2015 completed in 0:00:06.625694

 30%|██▉       | 1281/4292 [3:11:16<6:33:47,  7.85s/it]

UT_17845_2015 completed in 0:00:08.836793

 30%|██▉       | 1282/4292 [3:11:22<6:03:21,  7.24s/it]

UT_17874_2015 completed in 0:00:05.833010

 30%|██▉       | 1283/4292 [3:11:28<5:52:04,  7.02s/it]

UT_18206_2015 completed in 0:00:06.499419

 30%|██▉       | 1284/4292 [3:11:35<5:56:17,  7.11s/it]

VA_84_2015 completed in 0:00:07.307859

 30%|██▉       | 1285/4292 [3:11:48<7:24:48,  8.88s/it]

VA_733_2015 completed in 0:00:13.001960

 30%|██▉       | 1286/4292 [3:11:58<7:35:02,  9.08s/it]

VA_17066_2015 completed in 0:00:09.564657

 30%|██▉       | 1287/4292 [3:12:13<8:58:24, 10.75s/it]

VA_19876_2015 completed in 0:00:14.640999

 30%|███       | 1288/4292 [3:12:23<8:48:04, 10.55s/it]

VA_19882_2015 completed in 0:00:10.073039

 30%|███       | 1289/4292 [3:12:30<7:58:28,  9.56s/it]

VA_40228_2015 completed in 0:00:07.255286

 30%|███       | 1290/4292 [3:12:41<8:25:04, 10.09s/it]

VT_2548_2015 completed in 0:00:11.341836

 30%|███       | 1291/4292 [3:12:55<9:16:40, 11.13s/it]

VT_7601_2015 completed in 0:00:13.543793

 30%|███       | 1292/4292 [3:13:07<9:26:23, 11.33s/it]

VT_19791_2015 completed in 0:00:11.789496

 30%|███       | 1293/4292 [3:13:19<9:41:22, 11.63s/it]

WA_3660_2015 completed in 0:00:12.338660

 30%|███       | 1294/4292 [3:13:27<8:46:01, 10.53s/it]

WA_14354_2015 completed in 0:00:07.950991

 30%|███       | 1295/4292 [3:13:43<10:01:49, 12.05s/it]

WA_15500_2015 completed in 0:00:15.596817

 30%|███       | 1296/4292 [3:13:57<10:32:46, 12.67s/it]

WA_16868_2015 completed in 0:00:14.126536

 30%|███       | 1297/4292 [3:14:11<10:56:40, 13.16s/it]

WA_17470_2015 completed in 0:00:14.282222

 30%|███       | 1298/4292 [3:14:24<10:49:40, 13.02s/it]

WA_18429_2015 completed in 0:00:12.701353

 30%|███       | 1299/4292 [3:14:34<10:04:17, 12.11s/it]

WA_20169_2015 completed in 0:00:09.996442

 30%|███       | 1300/4292 [3:14:44<9:43:10, 11.69s/it]

WI_4715_2015 completed in 0:00:10.715079

 30%|███       | 1301/4292 [3:14:56<9:35:36, 11.55s/it]

WI_5574_2015 completed in 0:00:11.201282

 30%|███       | 1302/4292 [3:15:06<9:17:59, 11.20s/it]

WI_11479_2015 completed in 0:00:10.379849

 30%|███       | 1303/4292 [3:15:17<9:19:20, 11.23s/it]

WI_13697_2015 completed in 0:00:11.297935

 30%|███       | 1304/4292 [3:15:27<9:03:53, 10.92s/it]

WI_13815_2015 completed in 0:00:10.205650

 30%|███       | 1305/4292 [3:15:39<9:08:10, 11.01s/it]

WI_20847_2015 completed in 0:00:11.219589

 30%|███       | 1306/4292 [3:15:48<8:37:16, 10.39s/it]

WI_20856_2015 completed in 0:00:08.952761

 30%|███       | 1307/4292 [3:15:59<8:52:33, 10.70s/it]

WI_20860_2015 completed in 0:00:11.428933

 30%|███       | 1308/4292 [3:16:13<9:40:00, 11.66s/it]

WV_733_2015 completed in 0:00:13.895891

 30%|███       | 1309/4292 [3:16:30<11:06:05, 13.40s/it]

WV_12796_2015 completed in 0:00:17.445973

 31%|███       | 1310/4292 [3:16:40<10:14:24, 12.36s/it]

WV_15263_2015 completed in 0:00:09.945962

 31%|███       | 1311/4292 [3:16:47<8:44:38, 10.56s/it]

WV_20521_2015 completed in 0:00:06.352002

 31%|███       | 1312/4292 [3:16:54<7:53:52,  9.54s/it]

WY_3461_2015 completed in 0:00:07.163421

 31%|███       | 1313/4292 [3:17:05<8:11:06,  9.89s/it]

WY_7222_2015 completed in 0:00:10.707699

 31%|███       | 1314/4292 [3:17:13<7:53:46,  9.55s/it]

WY_8566_2015 completed in 0:00:08.737900

 31%|███       | 1315/4292 [3:17:27<8:56:08, 10.81s/it]

WY_11273_2015 completed in 0:00:13.745594

 31%|███       | 1316/4292 [3:17:36<8:30:28, 10.29s/it]

WY_14354_2015 completed in 0:00:09.090845

 31%|███       | 1317/4292 [3:17:48<8:58:49, 10.87s/it]

WY_19156_2015 completed in 0:00:12.208680

 31%|███       | 1318/4292 [3:17:58<8:45:14, 10.60s/it]

WY_27058_2015 completed in 0:00:09.964268

 31%|███       | 1319/4292 [3:18:08<8:30:31, 10.30s/it]

OR_28541_2015 completed in 0:00:09.613808

 31%|███       | 1320/4292 [3:18:20<8:54:05, 10.78s/it]

AK_219_2016 completed in 0:00:11.899253

 31%|███       | 1321/4292 [3:18:30<8:44:26, 10.59s/it]

AK_599_2016 completed in 0:00:10.144338

 31%|███       | 1322/4292 [3:18:44<9:41:25, 11.75s/it]

AK_3522_2016 completed in 0:00:14.439912

 31%|███       | 1323/4292 [3:18:57<9:46:09, 11.85s/it]

AK_7353_2016 completed in 0:00:12.077245

 31%|███       | 1324/4292 [3:19:08<9:36:03, 11.65s/it]

AK_11824_2016 completed in 0:00:11.176968

 31%|███       | 1325/4292 [3:19:18<9:21:23, 11.35s/it]

AK_19558_2016 completed in 0:00:10.669580

 31%|███       | 1326/4292 [3:19:33<10:12:43, 12.40s/it]

AL_195_2016 completed in 0:00:14.826098

 31%|███       | 1327/4292 [3:19:43<9:31:26, 11.56s/it]

AR_814_2016 completed in 0:00:09.623452

 31%|███       | 1328/4292 [3:19:51<8:41:11, 10.55s/it]

AR_817_2016 completed in 0:00:08.184759

 31%|███       | 1329/4292 [3:20:00<8:23:50, 10.20s/it]

AR_3093_2016 completed in 0:00:09.390702

 31%|███       | 1330/4292 [3:20:07<7:36:15,  9.24s/it]

AR_5860_2016 completed in 0:00:07.000362

 31%|███       | 1331/4292 [3:20:16<7:30:48,  9.13s/it]

AR_6342_2016 completed in 0:00:08.883342

 31%|███       | 1332/4292 [3:20:25<7:16:58,  8.86s/it]

AR_13718_2016 completed in 0:00:08.209724

 31%|███       | 1333/4292 [3:20:32<6:51:00,  8.33s/it]

AR_14063_2016 completed in 0:00:07.111921

 31%|███       | 1334/4292 [3:20:39<6:33:34,  7.98s/it]

AR_17698_2016 completed in 0:00:07.163347

 31%|███       | 1335/4292 [3:20:44<5:50:23,  7.11s/it]

AZ_176_2016 completed in 0:00:05.066690

 31%|███       | 1336/4292 [3:20:53<6:14:39,  7.60s/it]

AZ_803_2016 completed in 0:00:08.759021

 31%|███       | 1337/4292 [3:21:02<6:45:39,  8.24s/it]

AZ_12919_2016 completed in 0:00:09.709938

 31%|███       | 1338/4292 [3:21:08<6:10:47,  7.53s/it]

AZ_16572_2016 completed in 0:00:05.883664

 31%|███       | 1339/4292 [3:21:13<5:29:45,  6.70s/it]

AZ_19189_2016 completed in 0:00:04.759889

 31%|███       | 1340/4292 [3:21:22<6:01:01,  7.34s/it]

AZ_19728_2016 completed in 0:00:08.825361

 31%|███       | 1341/4292 [3:21:28<5:42:42,  6.97s/it]

AZ_21538_2016 completed in 0:00:06.103526

 31%|███▏      | 1342/4292 [3:21:37<6:14:07,  7.61s/it]

AZ_24211_2016 completed in 0:00:09.105109

 31%|███▏      | 1343/4292 [3:21:43<5:45:41,  7.03s/it]

CA_9216_2016 completed in 0:00:05.689132

 31%|███▏      | 1344/4292 [3:21:48<5:16:38,  6.44s/it]

CA_11208_2016 completed in 0:00:05.068796

 31%|███▏      | 1345/4292 [3:21:54<5:08:57,  6.29s/it]

CA_12745_2016 completed in 0:00:05.930195

 31%|███▏      | 1346/4292 [3:22:10<7:32:41,  9.22s/it]

CA_14328_2016 completed in 0:00:16.053847

 31%|███▏      | 1347/4292 [3:22:16<6:42:18,  8.20s/it]

CA_14354_2016 completed in 0:00:05.808389

 31%|███▏      | 1348/4292 [3:22:21<5:59:10,  7.32s/it]

CA_14534_2016 completed in 0:00:05.274295

 31%|███▏      | 1349/4292 [3:22:27<5:42:19,  6.98s/it]

CA_16534_2016 completed in 0:00:06.182715

 31%|███▏      | 1350/4292 [3:22:34<5:45:18,  7.04s/it]

CA_16609_2016 completed in 0:00:07.188367

 31%|███▏      | 1351/4292 [3:22:40<5:24:55,  6.63s/it]

CA_16655_2016 completed in 0:00:05.663507

 32%|███▏      | 1352/4292 [3:22:49<6:04:26,  7.44s/it]

CA_17609_2016 completed in 0:00:09.323021

 32%|███▏      | 1353/4292 [3:22:54<5:32:08,  6.78s/it]

CA_17612_2016 completed in 0:00:05.246895

 32%|███▏      | 1354/4292 [3:23:01<5:28:47,  6.71s/it]

CA_19281_2016 completed in 0:00:06.554492

 32%|███▏      | 1355/4292 [3:23:08<5:30:25,  6.75s/it]

CO_3989_2016 completed in 0:00:06.832306

 32%|███▏      | 1356/4292 [3:23:14<5:16:30,  6.47s/it]

CO_6604_2016 completed in 0:00:05.809729

 32%|███▏      | 1357/4292 [3:23:21<5:22:58,  6.60s/it]

CO_9336_2016 completed in 0:00:06.914571

 32%|███▏      | 1358/4292 [3:23:27<5:18:17,  6.51s/it]

CO_12866_2016 completed in 0:00:06.289689

 32%|███▏      | 1359/4292 [3:23:34<5:25:08,  6.65s/it]

CO_15257_2016 completed in 0:00:06.983456

 32%|███▏      | 1360/4292 [3:23:42<5:45:46,  7.08s/it]

CO_15466_2016 completed in 0:00:08.064785

 32%|███▏      | 1361/4292 [3:23:49<5:44:04,  7.04s/it]

CO_16603_2016 completed in 0:00:06.967326

 32%|███▏      | 1362/4292 [3:23:56<5:39:09,  6.95s/it]

CO_19499_2016 completed in 0:00:06.714589

 32%|███▏      | 1363/4292 [3:24:01<5:22:21,  6.60s/it]

CO_27058_2016 completed in 0:00:05.805076

 32%|███▏      | 1364/4292 [3:24:07<5:11:23,  6.38s/it]

CO_56146_2016 completed in 0:00:05.860112

 32%|███▏      | 1365/4292 [3:24:13<5:03:48,  6.23s/it]

CT_4176_2016 completed in 0:00:05.864714

 32%|███▏      | 1366/4292 [3:24:20<5:06:05,  6.28s/it]

CT_7716_2016 completed in 0:00:06.389222

 32%|███▏      | 1367/4292 [3:24:26<5:11:18,  6.39s/it]

CT_19497_2016 completed in 0:00:06.637989

 32%|███▏      | 1368/4292 [3:24:33<5:17:31,  6.52s/it]

CT_20038_2016 completed in 0:00:06.816991

 32%|███▏      | 1369/4292 [3:24:39<5:02:59,  6.22s/it]

DC_15270_2016 completed in 0:00:05.524110

 32%|███▏      | 1370/4292 [3:24:45<4:59:32,  6.15s/it]

DE_5027_2016 completed in 0:00:05.989501

 32%|███▏      | 1371/4292 [3:24:51<5:03:20,  6.23s/it]

DE_5070_2016 completed in 0:00:06.416480

 32%|███▏      | 1372/4292 [3:24:56<4:44:57,  5.86s/it]

DE_5335_2016 completed in 0:00:04.977484

 32%|███▏      | 1373/4292 [3:25:02<4:49:24,  5.95s/it]

DE_13519_2016 completed in 0:00:06.166421

 32%|███▏      | 1374/4292 [3:25:10<5:21:21,  6.61s/it]

FL_6452_2016 completed in 0:00:08.144450

 32%|███▏      | 1375/4292 [3:25:18<5:40:08,  7.00s/it]

FL_6455_2016 completed in 0:00:07.901223

 32%|███▏      | 1376/4292 [3:25:24<5:20:15,  6.59s/it]

FL_6457_2016 completed in 0:00:05.639930

 32%|███▏      | 1377/4292 [3:25:29<5:00:56,  6.19s/it]

FL_7801_2016 completed in 0:00:05.270940

 32%|███▏      | 1378/4292 [3:25:36<5:15:01,  6.49s/it]

FL_9617_2016 completed in 0:00:07.167637

 32%|███▏      | 1379/4292 [3:25:42<4:59:46,  6.17s/it]

FL_18454_2016 completed in 0:00:05.445581

 32%|███▏      | 1380/4292 [3:25:49<5:21:08,  6.62s/it]

GA_3916_2016 completed in 0:00:07.648133

 32%|███▏      | 1381/4292 [3:25:56<5:22:19,  6.64s/it]

HI_8287_2016 completed in 0:00:06.704570

 32%|███▏      | 1382/4292 [3:26:03<5:31:20,  6.83s/it]

HI_10071_2016 completed in 0:00:07.270803

 32%|███▏      | 1383/4292 [3:26:11<5:47:31,  7.17s/it]

HI_11843_2016 completed in 0:00:07.950496

 32%|███▏      | 1384/4292 [3:26:16<5:18:46,  6.58s/it]

HI_19547_2016 completed in 0:00:05.193339

 32%|███▏      | 1385/4292 [3:26:24<5:34:48,  6.91s/it]

IA_9417_2016 completed in 0:00:07.687143

 32%|███▏      | 1386/4292 [3:26:30<5:18:11,  6.57s/it]

IA_12341_2016 completed in 0:00:05.768228

 32%|███▏      | 1387/4292 [3:26:35<4:50:15,  6.00s/it]

ID_9187_2016 completed in 0:00:04.653030

 32%|███▏      | 1388/4292 [3:26:42<5:11:12,  6.43s/it]

ID_9191_2016 completed in 0:00:07.439175

 32%|███▏      | 1389/4292 [3:26:48<5:11:46,  6.44s/it]

ID_10454_2016 completed in 0:00:06.475381

 32%|███▏      | 1390/4292 [3:26:57<5:47:17,  7.18s/it]

ID_11273_2016 completed in 0:00:08.897443

 32%|███▏      | 1391/4292 [3:27:06<6:09:11,  7.64s/it]

ID_14354_2016 completed in 0:00:08.697714

 32%|███▏      | 1392/4292 [3:27:13<5:56:45,  7.38s/it]

ID_20169_2016 completed in 0:00:06.786241

 32%|███▏      | 1393/4292 [3:27:20<5:52:34,  7.30s/it]

IL_4110_2016 completed in 0:00:07.095340

 32%|███▏      | 1394/4292 [3:27:26<5:37:20,  6.98s/it]

IL_12341_2016 completed in 0:00:06.253932

 33%|███▎      | 1395/4292 [3:27:33<5:27:57,  6.79s/it]

IL_13032_2016 completed in 0:00:06.343219

 33%|███▎      | 1396/4292 [3:27:44<6:29:38,  8.07s/it]

IL_56697_2016 completed in 0:00:11.059053

 33%|███▎      | 1397/4292 [3:27:51<6:17:51,  7.83s/it]

IN_9273_2016 completed in 0:00:07.267561

 33%|███▎      | 1398/4292 [3:27:57<5:54:56,  7.36s/it]

IN_9324_2016 completed in 0:00:06.255406

 33%|███▎      | 1399/4292 [3:28:03<5:29:57,  6.84s/it]

IN_13756_2016 completed in 0:00:05.639530

 33%|███▎      | 1400/4292 [3:28:12<6:06:04,  7.59s/it]

IN_15470_2016 completed in 0:00:09.347546

 33%|███▎      | 1401/4292 [3:28:17<5:27:18,  6.79s/it]

IN_17633_2016 completed in 0:00:04.920826

 33%|███▎      | 1402/4292 [3:28:24<5:25:08,  6.75s/it]

KS_5860_2016 completed in 0:00:06.649795

 33%|███▎      | 1403/4292 [3:28:29<5:09:31,  6.43s/it]

KS_9996_2016 completed in 0:00:05.676501

 33%|███▎      | 1404/4292 [3:28:38<5:48:17,  7.24s/it]

KS_10000_2016 completed in 0:00:09.119126

 33%|███▎      | 1405/4292 [3:28:47<6:02:50,  7.54s/it]

KS_10005_2016 completed in 0:00:08.246980

 33%|███▎      | 1406/4292 [3:28:54<6:02:14,  7.53s/it]

KS_22500_2016 completed in 0:00:07.507083

 33%|███▎      | 1407/4292 [3:29:04<6:36:05,  8.24s/it]

KY_9964_2016 completed in 0:00:09.885449

 33%|███▎      | 1408/4292 [3:29:14<6:57:03,  8.68s/it]

KY_10171_2016 completed in 0:00:09.700605

 33%|███▎      | 1409/4292 [3:29:21<6:31:59,  8.16s/it]

KY_11249_2016 completed in 0:00:06.946856

 33%|███▎      | 1410/4292 [3:29:28<6:12:52,  7.76s/it]

KY_17564_2016 completed in 0:00:06.839474

 33%|███▎      | 1411/4292 [3:29:34<5:53:15,  7.36s/it]

KY_19446_2016 completed in 0:00:06.404340

 33%|███▎      | 1412/4292 [3:29:42<6:02:59,  7.56s/it]

KY_22053_2016 completed in 0:00:08.041064

 33%|███▎      | 1413/4292 [3:29:49<5:56:43,  7.43s/it]

KY_49998_2016 completed in 0:00:07.134174

 33%|███▎      | 1414/4292 [3:29:59<6:25:39,  8.04s/it]

LA_3265_2016 completed in 0:00:09.452499

 33%|███▎      | 1415/4292 [3:30:09<6:59:56,  8.76s/it]

LA_11241_2016 completed in 0:00:10.431514

 33%|███▎      | 1416/4292 [3:30:16<6:36:46,  8.28s/it]

LA_13478_2016 completed in 0:00:07.156681

 33%|███▎      | 1417/4292 [3:30:23<6:13:15,  7.79s/it]

LA_17698_2016 completed in 0:00:06.646527

 33%|███▎      | 1418/4292 [3:30:31<6:16:07,  7.85s/it]

MA_6374_2016 completed in 0:00:07.996660

 33%|███▎      | 1419/4292 [3:30:37<5:53:37,  7.39s/it]

MA_8774_2016 completed in 0:00:06.294398

 33%|███▎      | 1420/4292 [3:30:46<6:10:12,  7.73s/it]

MA_11804_2016 completed in 0:00:08.547318

 33%|███▎      | 1421/4292 [3:30:53<5:57:14,  7.47s/it]

MA_13206_2016 completed in 0:00:06.839039

 33%|███▎      | 1422/4292 [3:31:02<6:19:38,  7.94s/it]

MA_15748_2016 completed in 0:00:09.030997

 33%|███▎      | 1423/4292 [3:31:10<6:26:19,  8.08s/it]

MA_20455_2016 completed in 0:00:08.410867

 33%|███▎      | 1424/4292 [3:31:17<6:14:44,  7.84s/it]

MA_54913_2016 completed in 0:00:07.275116

 33%|███▎      | 1425/4292 [3:31:24<6:03:26,  7.61s/it]

MD_1167_2016 completed in 0:00:07.054344

 33%|███▎      | 1426/4292 [3:31:31<5:48:25,  7.29s/it]

MD_5027_2016 completed in 0:00:06.565874

 33%|███▎      | 1427/4292 [3:31:37<5:28:40,  6.88s/it]

MD_15263_2016 completed in 0:00:05.919694

 33%|███▎      | 1428/4292 [3:31:44<5:30:30,  6.92s/it]

MD_15270_2016 completed in 0:00:07.017483

 33%|███▎      | 1429/4292 [3:31:50<5:14:19,  6.59s/it]

MD_17637_2016 completed in 0:00:05.800494

 33%|███▎      | 1430/4292 [3:31:56<5:07:43,  6.45s/it]

ME_1179_2016 completed in 0:00:06.132645

 33%|███▎      | 1431/4292 [3:32:03<5:17:47,  6.66s/it]

ME_3266_2016 completed in 0:00:07.157105

 33%|███▎      | 1432/4292 [3:32:10<5:26:18,  6.85s/it]

MI_392_2016 completed in 0:00:07.267729

 33%|███▎      | 1433/4292 [3:32:22<6:36:37,  8.32s/it]

MI_3828_2016 completed in 0:00:11.771465

 33%|███▎      | 1434/4292 [3:32:32<7:00:10,  8.82s/it]

MI_4254_2016 completed in 0:00:09.980080

 33%|███▎      | 1435/4292 [3:32:40<6:51:12,  8.64s/it]

MI_5109_2016 completed in 0:00:08.198185

 33%|███▎      | 1436/4292 [3:32:47<6:25:48,  8.11s/it]

MI_9324_2016 completed in 0:00:06.866461

 33%|███▎      | 1437/4292 [3:32:54<6:08:12,  7.74s/it]

MI_10704_2016 completed in 0:00:06.880465

 34%|███▎      | 1438/4292 [3:33:03<6:21:52,  8.03s/it]

MI_19578_2016 completed in 0:00:08.704431

 34%|███▎      | 1439/4292 [3:33:10<6:11:16,  7.81s/it]

MI_20847_2016 completed in 0:00:07.293174

 34%|███▎      | 1440/4292 [3:33:17<6:01:19,  7.60s/it]

MI_20860_2016 completed in 0:00:07.119056

 34%|███▎      | 1441/4292 [3:33:24<5:49:20,  7.35s/it]

MN_689_2016 completed in 0:00:06.769198

 34%|███▎      | 1442/4292 [3:33:32<5:58:40,  7.55s/it]

MN_5574_2016 completed in 0:00:08.014395

 34%|███▎      | 1443/4292 [3:33:50<8:28:53, 10.72s/it]

MN_12647_2016 completed in 0:00:18.103512

 34%|███▎      | 1444/4292 [3:33:59<8:02:02, 10.16s/it]

MN_13781_2016 completed in 0:00:08.843583

 34%|███▎      | 1445/4292 [3:34:06<7:20:16,  9.28s/it]

MN_14232_2016 completed in 0:00:07.228693

 34%|███▎      | 1446/4292 [3:34:12<6:36:35,  8.36s/it]

MN_16181_2016 completed in 0:00:06.218249

 34%|███▎      | 1447/4292 [3:34:21<6:34:42,  8.32s/it]

MN_17267_2016 completed in 0:00:08.237511

 34%|███▎      | 1448/4292 [3:34:29<6:40:40,  8.45s/it]

MN_20996_2016 completed in 0:00:08.753116

 34%|███▍      | 1449/4292 [3:34:39<7:01:15,  8.89s/it]

MN_25177_2016 completed in 0:00:09.909666

 34%|███▍      | 1450/4292 [3:34:47<6:47:31,  8.60s/it]

MO_4675_2016 completed in 0:00:07.934197

 34%|███▍      | 1451/4292 [3:34:53<6:10:15,  7.82s/it]

MO_5860_2016 completed in 0:00:05.988896

 34%|███▍      | 1452/4292 [3:34:59<5:38:07,  7.14s/it]

MO_9231_2016 completed in 0:00:05.561127

 34%|███▍      | 1453/4292 [3:35:05<5:27:05,  6.91s/it]

MO_10000_2016 completed in 0:00:06.373524

 34%|███▍      | 1454/4292 [3:35:12<5:34:10,  7.07s/it]

MO_12698_2016 completed in 0:00:07.419444

 34%|███▍      | 1455/4292 [3:35:19<5:28:37,  6.95s/it]

MO_17833_2016 completed in 0:00:06.676168

 34%|███▍      | 1456/4292 [3:35:26<5:27:38,  6.93s/it]

MO_19436_2016 completed in 0:00:06.888401

 34%|███▍      | 1457/4292 [3:35:32<5:19:09,  6.75s/it]

MS_3841_2016 completed in 0:00:06.340581

 34%|███▍      | 1458/4292 [3:35:37<4:50:53,  6.16s/it]

MS_17647_2016 completed in 0:00:04.766517

 34%|███▍      | 1459/4292 [3:35:47<5:38:24,  7.17s/it]

MT_6395_2016 completed in 0:00:09.515869

 34%|███▍      | 1460/4292 [3:35:54<5:40:33,  7.22s/it]

MT_12692_2016 completed in 0:00:07.325964

 34%|███▍      | 1461/4292 [3:36:01<5:42:08,  7.25s/it]

MT_12825_2016 completed in 0:00:07.334849

 34%|███▍      | 1462/4292 [3:36:35<11:51:53, 15.09s/it]

MT_19603_2016 completed in 0:00:33.385688

 34%|███▍      | 1463/4292 [3:36:44<10:23:35, 13.23s/it]

MT_20997_2016 completed in 0:00:08.867914

 34%|███▍      | 1464/4292 [3:36:57<10:23:03, 13.22s/it]

NC_3046_2016 completed in 0:00:13.202422

 34%|███▍      | 1465/4292 [3:37:07<9:39:23, 12.30s/it]

NC_5416_2016 completed in 0:00:10.144287

 34%|███▍      | 1466/4292 [3:37:16<8:50:29, 11.26s/it]

NC_9837_2016 completed in 0:00:08.849934

 34%|███▍      | 1467/4292 [3:37:24<8:09:37, 10.40s/it]

NC_16496_2016 completed in 0:00:08.382422

 34%|███▍      | 1468/4292 [3:37:33<7:43:35,  9.85s/it]

NC_19876_2016 completed in 0:00:08.566827

 34%|███▍      | 1469/4292 [3:37:42<7:31:03,  9.59s/it]

NC_24889_2016 completed in 0:00:08.971826

 34%|███▍      | 1470/4292 [3:37:50<7:15:19,  9.26s/it]

ND_12301_2016 completed in 0:00:08.482409

 34%|███▍      | 1471/4292 [3:38:01<7:33:45,  9.65s/it]

ND_14232_2016 completed in 0:00:10.572023

 34%|███▍      | 1472/4292 [3:38:11<7:42:05,  9.83s/it]

ND_19790_2016 completed in 0:00:10.253154

 34%|███▍      | 1473/4292 [3:38:22<8:04:30, 10.31s/it]

ND_24949_2016 completed in 0:00:11.432315

 34%|███▍      | 1474/4292 [3:38:38<9:22:55, 11.99s/it]

NE_4373_2016 completed in 0:00:15.888835

 34%|███▍      | 1475/4292 [3:38:52<9:48:34, 12.54s/it]

NE_6779_2016 completed in 0:00:13.820402

 34%|███▍      | 1476/4292 [3:39:08<10:33:17, 13.49s/it]

NE_11018_2016 completed in 0:00:15.725065

 34%|███▍      | 1477/4292 [3:39:22<10:34:51, 13.53s/it]

NE_11251_2016 completed in 0:00:13.619889

 34%|███▍      | 1478/4292 [3:39:34<10:16:53, 13.15s/it]

NE_12539_2016 completed in 0:00:12.269470

 34%|███▍      | 1479/4292 [3:39:47<10:23:46, 13.30s/it]

NE_13337_2016 completed in 0:00:13.657758

 34%|███▍      | 1480/4292 [3:40:02<10:45:07, 13.77s/it]

NE_13664_2016 completed in 0:00:14.838398

 35%|███▍      | 1481/4292 [3:40:29<13:46:01, 17.63s/it]

NE_14127_2016 completed in 0:00:26.650524

 35%|███▍      | 1482/4292 [3:40:41<12:23:33, 15.88s/it]

NE_17642_2016 completed in 0:00:11.776892

 35%|███▍      | 1483/4292 [3:40:53<11:25:55, 14.65s/it]

NH_13441_2016 completed in 0:00:11.792177

 35%|███▍      | 1484/4292 [3:41:10<11:58:55, 15.36s/it]

NH_15472_2016 completed in 0:00:17.017558

 35%|███▍      | 1485/4292 [3:41:31<13:18:36, 17.07s/it]

NH_24590_2016 completed in 0:00:21.056088

 35%|███▍      | 1486/4292 [3:41:40<11:37:22, 14.91s/it]

NJ_963_2016 completed in 0:00:09.868651

 35%|███▍      | 1487/4292 [3:41:54<11:19:00, 14.52s/it]

NJ_9726_2016 completed in 0:00:13.618512

 35%|███▍      | 1488/4292 [3:42:06<10:47:47, 13.86s/it]

NJ_15477_2016 completed in 0:00:12.309396

 35%|███▍      | 1489/4292 [3:42:20<10:37:55, 13.66s/it]

NJ_16213_2016 completed in 0:00:13.168661

 35%|███▍      | 1490/4292 [3:42:32<10:13:42, 13.14s/it]

NM_3287_2016 completed in 0:00:11.937034

 35%|███▍      | 1491/4292 [3:42:46<10:36:03, 13.63s/it]

NM_5701_2016 completed in 0:00:14.747338

 35%|███▍      | 1492/4292 [3:42:56<9:35:17, 12.33s/it]

NM_6204_2016 completed in 0:00:09.299619

 35%|███▍      | 1493/4292 [3:43:05<8:56:37, 11.50s/it]

NM_11204_2016 completed in 0:00:09.574504

 35%|███▍      | 1494/4292 [3:43:14<8:22:59, 10.79s/it]

NM_15473_2016 completed in 0:00:09.111276

 35%|███▍      | 1495/4292 [3:43:26<8:42:28, 11.21s/it]

NM_17718_2016 completed in 0:00:12.191179

 35%|███▍      | 1496/4292 [3:43:36<8:17:01, 10.67s/it]

NV_2008_2016 completed in 0:00:09.400457

 35%|███▍      | 1497/4292 [3:43:48<8:41:23, 11.19s/it]

NV_13073_2016 completed in 0:00:12.421478

 35%|███▍      | 1498/4292 [3:43:57<8:02:35, 10.36s/it]

NV_13407_2016 completed in 0:00:08.427354

 35%|███▍      | 1499/4292 [3:44:08<8:22:29, 10.79s/it]

NV_17166_2016 completed in 0:00:11.795194

 35%|███▍      | 1500/4292 [3:44:18<8:04:46, 10.42s/it]

NV_19840_2016 completed in 0:00:09.533125

 35%|███▍      | 1501/4292 [3:44:28<7:54:27, 10.20s/it]

NY_3249_2016 completed in 0:00:09.689118

 35%|███▍      | 1502/4292 [3:44:37<7:37:36,  9.84s/it]

NY_4226_2016 completed in 0:00:09.003046

 35%|███▌      | 1503/4292 [3:44:46<7:29:53,  9.68s/it]

NY_11171_2016 completed in 0:00:09.298227

 35%|███▌      | 1504/4292 [3:44:58<8:05:56, 10.46s/it]

NY_13511_2016 completed in 0:00:12.270055

 35%|███▌      | 1505/4292 [3:45:09<8:05:05, 10.44s/it]

NY_13573_2016 completed in 0:00:10.403313

 35%|███▌      | 1506/4292 [3:45:17<7:33:35,  9.77s/it]

NY_14154_2016 completed in 0:00:08.188663

 35%|███▌      | 1507/4292 [3:45:24<7:00:55,  9.07s/it]

NY_16183_2016 completed in 0:00:07.433920

 35%|███▌      | 1508/4292 [3:45:32<6:43:41,  8.70s/it]

OH_3542_2016 completed in 0:00:07.840428

 35%|███▌      | 1509/4292 [3:45:40<6:33:06,  8.48s/it]

OH_3755_2016 completed in 0:00:07.948279

 35%|███▌      | 1510/4292 [3:45:49<6:38:31,  8.60s/it]

OH_4922_2016 completed in 0:00:08.874157

 35%|███▌      | 1511/4292 [3:45:59<6:52:30,  8.90s/it]

OH_13998_2016 completed in 0:00:09.610560

 35%|███▌      | 1512/4292 [3:46:13<8:12:04, 10.62s/it]

OH_14006_2016 completed in 0:00:14.629370

 35%|███▌      | 1513/4292 [3:46:21<7:30:51,  9.73s/it]

OH_18997_2016 completed in 0:00:07.665164

 35%|███▌      | 1514/4292 [3:46:28<6:53:16,  8.93s/it]

OK_5860_2016 completed in 0:00:07.039025

 35%|███▌      | 1515/4292 [3:46:37<6:52:58,  8.92s/it]

OK_13734_2016 completed in 0:00:08.914340

 35%|███▌      | 1516/4292 [3:46:46<6:51:23,  8.89s/it]

OK_14062_2016 completed in 0:00:08.819126

 35%|███▌      | 1517/4292 [3:46:58<7:37:27,  9.89s/it]

OK_14063_2016 completed in 0:00:12.217447

 35%|███▌      | 1518/4292 [3:47:08<7:46:38, 10.09s/it]

OK_15474_2016 completed in 0:00:10.561088

 35%|███▌      | 1519/4292 [3:47:17<7:21:33,  9.55s/it]

OK_19785_2016 completed in 0:00:08.295188

 35%|███▌      | 1520/4292 [3:47:24<6:48:00,  8.83s/it]

OR_6022_2016 completed in 0:00:07.143632

 35%|███▌      | 1521/4292 [3:47:36<7:33:24,  9.82s/it]

OR_9191_2016 completed in 0:00:12.111910

 35%|███▌      | 1522/4292 [3:47:49<8:18:32, 10.80s/it]

OR_14354_2016 completed in 0:00:13.082911

 35%|███▌      | 1523/4292 [3:47:57<7:36:40,  9.90s/it]

OR_15248_2016 completed in 0:00:07.786065

 36%|███▌      | 1524/4292 [3:48:05<7:06:21,  9.24s/it]

OR_18260_2016 completed in 0:00:07.715841

 36%|███▌      | 1525/4292 [3:48:12<6:43:56,  8.76s/it]

OR_28541_2016 completed in 0:00:07.631802

 36%|███▌      | 1526/4292 [3:48:18<6:05:45,  7.93s/it]

OR_40437_2016 completed in 0:00:06.003758

 36%|███▌      | 1527/4292 [3:48:28<6:29:35,  8.45s/it]

PA_3597_2016 completed in 0:00:09.666595

 36%|███▌      | 1528/4292 [3:48:38<6:46:43,  8.83s/it]

PA_5487_2016 completed in 0:00:09.702737

 36%|███▌      | 1529/4292 [3:48:47<6:58:41,  9.09s/it]

PA_12390_2016 completed in 0:00:09.705386

 36%|███▌      | 1530/4292 [3:48:58<7:19:36,  9.55s/it]

PA_14711_2016 completed in 0:00:10.614810

 36%|███▌      | 1531/4292 [3:49:07<7:19:01,  9.54s/it]

PA_14715_2016 completed in 0:00:09.517510

 36%|███▌      | 1532/4292 [3:49:14<6:30:27,  8.49s/it]

PA_14716_2016 completed in 0:00:06.032036

 36%|███▌      | 1533/4292 [3:49:21<6:21:14,  8.29s/it]

PA_14940_2016 completed in 0:00:07.828073

 36%|███▌      | 1534/4292 [3:49:27<5:46:00,  7.53s/it]

PA_15045_2016 completed in 0:00:05.744759

 36%|███▌      | 1535/4292 [3:49:33<5:28:26,  7.15s/it]

PA_19390_2016 completed in 0:00:06.261281

 36%|███▌      | 1536/4292 [3:49:39<5:13:31,  6.83s/it]

PA_20334_2016 completed in 0:00:06.073228

 36%|███▌      | 1537/4292 [3:49:51<6:23:16,  8.35s/it]

PA_20387_2016 completed in 0:00:11.896734

 36%|███▌      | 1538/4292 [3:49:58<5:58:21,  7.81s/it]

RI_1857_2016 completed in 0:00:06.546771

 36%|███▌      | 1539/4292 [3:50:06<6:03:25,  7.92s/it]

RI_13214_2016 completed in 0:00:08.183605

 36%|███▌      | 1540/4292 [3:50:12<5:34:25,  7.29s/it]

SC_1613_2016 completed in 0:00:05.822538

 36%|███▌      | 1541/4292 [3:50:17<5:09:14,  6.74s/it]

SC_3046_2016 completed in 0:00:05.467919

 36%|███▌      | 1542/4292 [3:50:22<4:42:30,  6.16s/it]

SC_5416_2016 completed in 0:00:04.808281

 36%|███▌      | 1543/4292 [3:50:29<4:47:57,  6.29s/it]

SC_14398_2016 completed in 0:00:06.567016

 36%|███▌      | 1544/4292 [3:50:35<4:40:47,  6.13s/it]

SC_17539_2016 completed in 0:00:05.769753

 36%|███▌      | 1545/4292 [3:50:40<4:27:25,  5.84s/it]

SC_17543_2016 completed in 0:00:05.164402

 36%|███▌      | 1546/4292 [3:50:47<4:43:59,  6.21s/it]

SD_1769_2016 completed in 0:00:07.052638

 36%|███▌      | 1547/4292 [3:50:54<4:52:32,  6.39s/it]

SD_13337_2016 completed in 0:00:06.834740

 36%|███▌      | 1548/4292 [3:51:01<5:02:37,  6.62s/it]

SD_14232_2016 completed in 0:00:07.136429

 36%|███▌      | 1549/4292 [3:51:09<5:19:01,  6.98s/it]

SD_17267_2016 completed in 0:00:07.820154

 36%|███▌      | 1550/4292 [3:51:22<6:43:11,  8.82s/it]

SD_19293_2016 completed in 0:00:13.124382

 36%|███▌      | 1551/4292 [3:51:27<5:59:34,  7.87s/it]

SD_20401_2016 completed in 0:00:05.650018

 36%|███▌      | 1552/4292 [3:51:37<6:29:47,  8.54s/it]

TN_10331_2016 completed in 0:00:10.085442

 36%|███▌      | 1553/4292 [3:51:42<5:42:37,  7.51s/it]

TX_5701_2016 completed in 0:00:05.100551

 36%|███▌      | 1554/4292 [3:51:49<5:23:09,  7.08s/it]

TX_16604_2016 completed in 0:00:06.091361

 36%|███▌      | 1555/4292 [3:51:56<5:21:07,  7.04s/it]

TX_17698_2016 completed in 0:00:06.937003

 36%|███▋      | 1556/4292 [3:52:03<5:33:49,  7.32s/it]

TX_55937_2016 completed in 0:00:07.975182

 36%|███▋      | 1557/4292 [3:52:09<5:05:48,  6.71s/it]

UT_2010_2016 completed in 0:00:05.278538

 36%|███▋      | 1558/4292 [3:52:14<4:45:42,  6.27s/it]

UT_11135_2016 completed in 0:00:05.245397

 36%|███▋      | 1559/4292 [3:52:24<5:35:39,  7.37s/it]

UT_12866_2016 completed in 0:00:09.928796

 36%|███▋      | 1560/4292 [3:52:31<5:35:50,  7.38s/it]

UT_14354_2016 completed in 0:00:07.390603

 36%|███▋      | 1561/4292 [3:52:37<5:12:18,  6.86s/it]

UT_15444_2016 completed in 0:00:05.660278

 36%|███▋      | 1562/4292 [3:52:46<5:38:11,  7.43s/it]

UT_17845_2016 completed in 0:00:08.765194

 36%|███▋      | 1563/4292 [3:52:50<5:00:15,  6.60s/it]

UT_17874_2016 completed in 0:00:04.660724

 36%|███▋      | 1564/4292 [3:52:57<4:55:16,  6.49s/it]

UT_18206_2016 completed in 0:00:06.243278

 36%|███▋      | 1565/4292 [3:53:02<4:44:40,  6.26s/it]

VA_84_2016 completed in 0:00:05.724640

 36%|███▋      | 1566/4292 [3:53:07<4:25:23,  5.84s/it]

VA_733_2016 completed in 0:00:04.854793

 37%|███▋      | 1567/4292 [3:53:14<4:40:06,  6.17s/it]

VA_10171_2016 completed in 0:00:06.928090

 37%|███▋      | 1568/4292 [3:53:20<4:34:12,  6.04s/it]

VA_17066_2016 completed in 0:00:05.741575

 37%|███▋      | 1569/4292 [3:53:27<4:44:00,  6.26s/it]

VA_19876_2016 completed in 0:00:06.766275

 37%|███▋      | 1570/4292 [3:53:32<4:27:53,  5.90s/it]

VA_19882_2016 completed in 0:00:05.079725

 37%|███▋      | 1571/4292 [3:53:37<4:24:59,  5.84s/it]

VA_40228_2016 completed in 0:00:05.698297

 37%|███▋      | 1572/4292 [3:53:47<5:12:29,  6.89s/it]

VT_2548_2016 completed in 0:00:09.342271

 37%|███▋      | 1573/4292 [3:53:54<5:10:44,  6.86s/it]

VT_7601_2016 completed in 0:00:06.772540

 37%|███▋      | 1574/4292 [3:54:01<5:11:35,  6.88s/it]

VT_19791_2016 completed in 0:00:06.927097

 37%|███▋      | 1575/4292 [3:54:06<4:49:22,  6.39s/it]

WA_3660_2016 completed in 0:00:05.250786

 37%|███▋      | 1576/4292 [3:54:12<4:42:26,  6.24s/it]

WA_14354_2016 completed in 0:00:05.886067

 37%|███▋      | 1577/4292 [3:54:24<6:07:01,  8.11s/it]

WA_15500_2016 completed in 0:00:12.477745

 37%|███▋      | 1578/4292 [3:54:29<5:27:47,  7.25s/it]

WA_16868_2016 completed in 0:00:05.228326

 37%|███▋      | 1579/4292 [3:54:34<4:57:31,  6.58s/it]

WA_17470_2016 completed in 0:00:05.023154

 37%|███▋      | 1580/4292 [3:54:41<4:58:58,  6.61s/it]

WA_18429_2016 completed in 0:00:06.694503

 37%|███▋      | 1581/4292 [3:54:49<5:21:38,  7.12s/it]

WA_20169_2016 completed in 0:00:08.288584

 37%|███▋      | 1582/4292 [3:54:55<5:05:33,  6.76s/it]

WI_4715_2016 completed in 0:00:05.939040

 37%|███▋      | 1583/4292 [3:55:03<5:19:49,  7.08s/it]

WI_5574_2016 completed in 0:00:07.825675

 37%|███▋      | 1584/4292 [3:55:10<5:20:43,  7.11s/it]

WI_11479_2016 completed in 0:00:07.154188

 37%|███▋      | 1585/4292 [3:55:16<5:06:25,  6.79s/it]

WI_13697_2016 completed in 0:00:06.057232

 37%|███▋      | 1586/4292 [3:55:23<5:01:16,  6.68s/it]

WI_13815_2016 completed in 0:00:06.413809

 37%|███▋      | 1587/4292 [3:55:28<4:35:06,  6.10s/it]

WI_20847_2016 completed in 0:00:04.752711

 37%|███▋      | 1588/4292 [3:55:34<4:46:10,  6.35s/it]

WI_20856_2016 completed in 0:00:06.928059

 37%|███▋      | 1589/4292 [3:55:40<4:41:32,  6.25s/it]

WI_20860_2016 completed in 0:00:06.013619

 37%|███▋      | 1590/4292 [3:55:51<5:33:14,  7.40s/it]

WV_733_2016 completed in 0:00:10.079904

 37%|███▋      | 1591/4292 [3:55:56<5:03:47,  6.75s/it]

WV_12796_2016 completed in 0:00:05.227038

 37%|███▋      | 1592/4292 [3:56:05<5:43:03,  7.62s/it]

WV_15263_2016 completed in 0:00:09.665186

 37%|███▋      | 1593/4292 [3:56:10<5:06:00,  6.80s/it]

WV_20521_2016 completed in 0:00:04.882404

 37%|███▋      | 1594/4292 [3:56:17<4:59:57,  6.67s/it]

WY_3461_2016 completed in 0:00:06.362272

 37%|███▋      | 1595/4292 [3:56:22<4:44:29,  6.33s/it]

WY_7222_2016 completed in 0:00:05.530980

 37%|███▋      | 1596/4292 [3:56:29<4:45:30,  6.35s/it]

WY_8566_2016 completed in 0:00:06.411160

 37%|███▋      | 1597/4292 [3:56:34<4:36:49,  6.16s/it]

WY_11273_2016 completed in 0:00:05.716272

 37%|███▋      | 1598/4292 [3:56:43<5:07:40,  6.85s/it]

WY_14354_2016 completed in 0:00:08.459672

 37%|███▋      | 1599/4292 [3:56:50<5:15:30,  7.03s/it]

WY_19156_2016 completed in 0:00:07.442477

 37%|███▋      | 1600/4292 [3:56:55<4:48:19,  6.43s/it]

WY_27058_2016 completed in 0:00:05.017517

 37%|███▋      | 1601/4292 [3:57:00<4:28:02,  5.98s/it]

GA_9601_2016 completed in 0:00:04.925552

 37%|███▋      | 1602/4292 [3:57:07<4:42:01,  6.29s/it]

MS_12685_2016 completed in 0:00:07.022583

 37%|███▋      | 1603/4292 [3:57:18<5:37:20,  7.53s/it]

AK_219_2017 completed in 0:00:10.407047

 37%|███▋      | 1604/4292 [3:57:26<5:49:23,  7.80s/it]

AK_599_2017 completed in 0:00:08.432516

 37%|███▋      | 1605/4292 [3:57:34<5:47:44,  7.76s/it]

AK_3522_2017 completed in 0:00:07.684608

 37%|███▋      | 1606/4292 [3:57:39<5:17:38,  7.10s/it]

AK_7353_2017 completed in 0:00:05.532756

 37%|███▋      | 1607/4292 [3:57:47<5:19:14,  7.13s/it]

AK_11824_2017 completed in 0:00:07.222461

 37%|███▋      | 1608/4292 [3:57:52<5:00:20,  6.71s/it]

AK_19558_2017 completed in 0:00:05.734028

 37%|███▋      | 1609/4292 [3:58:00<5:08:06,  6.89s/it]

AL_195_2017 completed in 0:00:07.300700

 38%|███▊      | 1610/4292 [3:58:06<5:05:11,  6.83s/it]

AR_814_2017 completed in 0:00:06.679579

 38%|███▊      | 1611/4292 [3:58:13<5:05:09,  6.83s/it]

AR_817_2017 completed in 0:00:06.833518

 38%|███▊      | 1612/4292 [3:58:19<4:56:28,  6.64s/it]

AR_3093_2017 completed in 0:00:06.188970

 38%|███▊      | 1613/4292 [3:58:27<5:05:07,  6.83s/it]

AR_5860_2017 completed in 0:00:07.288485

 38%|███▊      | 1614/4292 [3:58:32<4:52:01,  6.54s/it]

AR_6342_2017 completed in 0:00:05.862473

 38%|███▊      | 1615/4292 [3:58:40<5:12:13,  7.00s/it]

AR_13718_2017 completed in 0:00:08.053700

 38%|███▊      | 1616/4292 [3:58:46<4:49:13,  6.48s/it]

AR_14063_2017 completed in 0:00:05.287568

 38%|███▊      | 1617/4292 [3:58:52<4:49:28,  6.49s/it]

AR_17698_2017 completed in 0:00:06.510660

 38%|███▊      | 1618/4292 [3:58:59<4:47:13,  6.44s/it]

AZ_176_2017 completed in 0:00:06.331766

 38%|███▊      | 1619/4292 [3:59:07<5:13:18,  7.03s/it]

AZ_803_2017 completed in 0:00:08.403240

 38%|███▊      | 1620/4292 [3:59:15<5:20:03,  7.19s/it]

AZ_12919_2017 completed in 0:00:07.546667

 38%|███▊      | 1621/4292 [3:59:19<4:48:01,  6.47s/it]

AZ_16572_2017 completed in 0:00:04.795655

 38%|███▊      | 1622/4292 [3:59:27<4:57:00,  6.67s/it]

AZ_19189_2017 completed in 0:00:07.149813

 38%|███▊      | 1623/4292 [3:59:33<4:59:40,  6.74s/it]

AZ_19728_2017 completed in 0:00:06.881908

 38%|███▊      | 1624/4292 [3:59:39<4:41:20,  6.33s/it]

AZ_21538_2017 completed in 0:00:05.368042

 38%|███▊      | 1625/4292 [3:59:45<4:33:31,  6.15s/it]

AZ_24211_2017 completed in 0:00:05.747715

 38%|███▊      | 1626/4292 [3:59:50<4:21:14,  5.88s/it]

CA_9216_2017 completed in 0:00:05.238788

 38%|███▊      | 1627/4292 [3:59:55<4:13:20,  5.70s/it]

CA_11208_2017 completed in 0:00:05.293334

 38%|███▊      | 1628/4292 [4:00:01<4:21:50,  5.90s/it]

CA_12745_2017 completed in 0:00:06.348334

 38%|███▊      | 1629/4292 [4:00:15<6:06:13,  8.25s/it]

CA_14328_2017 completed in 0:00:13.742831

 38%|███▊      | 1630/4292 [4:00:22<5:45:24,  7.79s/it]

CA_14354_2017 completed in 0:00:06.696811

 38%|███▊      | 1631/4292 [4:00:27<5:12:40,  7.05s/it]

CA_14534_2017 completed in 0:00:05.333269

 38%|███▊      | 1632/4292 [4:00:34<5:14:49,  7.10s/it]

CA_16534_2017 completed in 0:00:07.219721

 38%|███▊      | 1633/4292 [4:00:40<4:52:12,  6.59s/it]

CA_16609_2017 completed in 0:00:05.409209

 38%|███▊      | 1634/4292 [4:00:45<4:33:06,  6.16s/it]

CA_16655_2017 completed in 0:00:05.162818

 38%|███▊      | 1635/4292 [4:00:54<5:15:26,  7.12s/it]

CA_17609_2017 completed in 0:00:09.354276

 38%|███▊      | 1636/4292 [4:01:00<4:52:37,  6.61s/it]

CA_17612_2017 completed in 0:00:05.413155

 38%|███▊      | 1637/4292 [4:01:06<4:47:53,  6.51s/it]

CA_19281_2017 completed in 0:00:06.260381

 38%|███▊      | 1638/4292 [4:01:12<4:37:57,  6.28s/it]

CO_3989_2017 completed in 0:00:05.765404

 38%|███▊      | 1639/4292 [4:01:17<4:29:13,  6.09s/it]

CO_6604_2017 completed in 0:00:05.632666

 38%|███▊      | 1640/4292 [4:01:24<4:29:16,  6.09s/it]

CO_9336_2017 completed in 0:00:06.099661

 38%|███▊      | 1641/4292 [4:01:29<4:17:20,  5.82s/it]

CO_12866_2017 completed in 0:00:05.198602

 38%|███▊      | 1642/4292 [4:01:35<4:19:37,  5.88s/it]

CO_15257_2017 completed in 0:00:06.002655

 38%|███▊      | 1643/4292 [4:01:42<4:40:51,  6.36s/it]

CO_15466_2017 completed in 0:00:07.483104

 38%|███▊      | 1644/4292 [4:01:48<4:28:35,  6.09s/it]

CO_16603_2017 completed in 0:00:05.441409

 38%|███▊      | 1645/4292 [4:01:53<4:17:09,  5.83s/it]

CO_19499_2017 completed in 0:00:05.229189

 38%|███▊      | 1646/4292 [4:01:59<4:21:41,  5.93s/it]

CO_27058_2017 completed in 0:00:06.178050

 38%|███▊      | 1647/4292 [4:02:03<3:58:12,  5.40s/it]

CO_56146_2017 completed in 0:00:04.160250

 38%|███▊      | 1648/4292 [4:02:10<4:09:48,  5.67s/it]

CT_4176_2017 completed in 0:00:06.286365

 38%|███▊      | 1649/4292 [4:02:15<4:02:22,  5.50s/it]

CT_7716_2017 completed in 0:00:05.113134

 38%|███▊      | 1650/4292 [4:02:20<3:56:35,  5.37s/it]

CT_19497_2017 completed in 0:00:05.069887

 38%|███▊      | 1651/4292 [4:02:26<4:11:36,  5.72s/it]

CT_20038_2017 completed in 0:00:06.516895

 38%|███▊      | 1652/4292 [4:02:34<4:42:02,  6.41s/it]

DC_15270_2017 completed in 0:00:08.028313

 39%|███▊      | 1653/4292 [4:02:40<4:31:20,  6.17s/it]

DE_5027_2017 completed in 0:00:05.605745

 39%|███▊      | 1654/4292 [4:02:46<4:32:14,  6.19s/it]

DE_5070_2017 completed in 0:00:06.243497

 39%|███▊      | 1655/4292 [4:02:51<4:20:28,  5.93s/it]

DE_5335_2017 completed in 0:00:05.302806

 39%|███▊      | 1656/4292 [4:02:58<4:26:00,  6.05s/it]

DE_13519_2017 completed in 0:00:06.352460

 39%|███▊      | 1657/4292 [4:03:04<4:25:22,  6.04s/it]

FL_6452_2017 completed in 0:00:06.014003

 39%|███▊      | 1658/4292 [4:03:11<4:40:22,  6.39s/it]

FL_6455_2017 completed in 0:00:07.187923

 39%|███▊      | 1659/4292 [4:03:17<4:39:18,  6.36s/it]

FL_6457_2017 completed in 0:00:06.312178

 39%|███▊      | 1660/4292 [4:03:22<4:18:55,  5.90s/it]

FL_7801_2017 completed in 0:00:04.823019

WARNING:googleapiclient.http:Sleeping 0.69 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/value:compute?prettyPrint=false&alt=json, after 503
 39%|███▊      | 1661/4292 [4:03:38<6:27:13,  8.83s/it]

FL_9617_2017 completed in 0:00:15.662862

 39%|███▊      | 1662/4292 [4:03:44<5:47:56,  7.94s/it]

FL_18454_2017 completed in 0:00:05.853508

 39%|███▊      | 1663/4292 [4:03:50<5:24:02,  7.40s/it]

GA_3916_2017 completed in 0:00:06.128799

 39%|███▉      | 1664/4292 [4:03:55<4:54:56,  6.73s/it]

GA_9601_2017 completed in 0:00:05.189722

 39%|███▉      | 1665/4292 [4:04:00<4:30:11,  6.17s/it]

HI_8287_2017 completed in 0:00:04.856310

 39%|███▉      | 1666/4292 [4:04:04<4:09:32,  5.70s/it]

HI_10071_2017 completed in 0:00:04.600984

 39%|███▉      | 1667/4292 [4:04:16<5:25:44,  7.45s/it]

HI_11843_2017 completed in 0:00:11.513730

 39%|███▉      | 1668/4292 [4:04:21<4:48:59,  6.61s/it]

HI_19547_2017 completed in 0:00:04.652924

 39%|███▉      | 1669/4292 [4:04:27<4:49:05,  6.61s/it]

IA_9417_2017 completed in 0:00:06.623559

 39%|███▉      | 1670/4292 [4:04:37<5:35:04,  7.67s/it]

IA_12341_2017 completed in 0:00:10.123235

 39%|███▉      | 1671/4292 [4:04:43<5:07:08,  7.03s/it]

ID_9187_2017 completed in 0:00:05.540544

 39%|███▉      | 1672/4292 [4:04:52<5:31:03,  7.58s/it]

ID_9191_2017 completed in 0:00:08.864786

 39%|███▉      | 1673/4292 [4:04:57<5:03:41,  6.96s/it]

ID_10454_2017 completed in 0:00:05.500591

 39%|███▉      | 1674/4292 [4:05:02<4:32:13,  6.24s/it]

ID_11273_2017 completed in 0:00:04.561296

 39%|███▉      | 1675/4292 [4:05:07<4:24:57,  6.07s/it]

ID_14354_2017 completed in 0:00:05.690010

 39%|███▉      | 1676/4292 [4:05:15<4:49:19,  6.64s/it]

ID_20169_2017 completed in 0:00:07.944558

 39%|███▉      | 1677/4292 [4:05:21<4:37:53,  6.38s/it]

IL_4110_2017 completed in 0:00:05.768846

 39%|███▉      | 1678/4292 [4:05:30<5:02:58,  6.95s/it]

IL_12341_2017 completed in 0:00:08.302665

 39%|███▉      | 1679/4292 [4:05:35<4:46:10,  6.57s/it]

IL_13032_2017 completed in 0:00:05.676589

 39%|███▉      | 1680/4292 [4:05:46<5:46:49,  7.97s/it]

IL_56697_2017 completed in 0:00:11.222439

 39%|███▉      | 1681/4292 [4:05:55<5:52:37,  8.10s/it]

IN_9273_2017 completed in 0:00:08.421195

 39%|███▉      | 1682/4292 [4:06:01<5:21:06,  7.38s/it]

IN_9324_2017 completed in 0:00:05.697347

 39%|███▉      | 1683/4292 [4:06:11<6:04:35,  8.38s/it]

IN_13756_2017 completed in 0:00:10.723110

 39%|███▉      | 1684/4292 [4:06:20<6:08:39,  8.48s/it]

IN_15470_2017 completed in 0:00:08.706737

 39%|███▉      | 1685/4292 [4:06:25<5:26:29,  7.51s/it]

IN_17633_2017 completed in 0:00:05.256423

 39%|███▉      | 1686/4292 [4:06:31<5:00:43,  6.92s/it]

KS_5860_2017 completed in 0:00:05.542065

 39%|███▉      | 1687/4292 [4:06:39<5:13:09,  7.21s/it]

KS_9996_2017 completed in 0:00:07.886650

 39%|███▉      | 1688/4292 [4:06:47<5:24:50,  7.48s/it]

KS_10000_2017 completed in 0:00:08.116483

 39%|███▉      | 1689/4292 [4:06:53<5:06:43,  7.07s/it]

KS_10005_2017 completed in 0:00:06.101760

WARNING:googleapiclient.http:Sleeping 0.63 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/value:compute?prettyPrint=false&alt=json, after 503
 39%|███▉      | 1690/4292 [4:07:01<5:25:54,  7.52s/it]

KS_22500_2017 completed in 0:00:08.552861

WARNING:googleapiclient.http:Sleeping 0.61 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/value:compute?prettyPrint=false&alt=json, after 503
 39%|███▉      | 1691/4292 [4:07:17<7:04:51,  9.80s/it]

KY_9964_2017 completed in 0:00:15.127599

 39%|███▉      | 1692/4292 [4:07:26<6:58:55,  9.67s/it]

KY_10171_2017 completed in 0:00:09.355823

 39%|███▉      | 1693/4292 [4:07:34<6:34:28,  9.11s/it]

KY_11249_2017 completed in 0:00:07.792313

 39%|███▉      | 1694/4292 [4:07:41<6:08:08,  8.50s/it]

KY_17564_2017 completed in 0:00:07.089609

 39%|███▉      | 1695/4292 [4:07:47<5:43:07,  7.93s/it]

KY_19446_2017 completed in 0:00:06.586210

 40%|███▉      | 1696/4292 [4:07:54<5:30:38,  7.64s/it]

KY_22053_2017 completed in 0:00:06.974952

 40%|███▉      | 1697/4292 [4:08:02<5:25:11,  7.52s/it]

KY_49998_2017 completed in 0:00:07.230601

 40%|███▉      | 1698/4292 [4:08:10<5:42:48,  7.93s/it]

LA_3265_2017 completed in 0:00:08.885951

WARNING:googleapiclient.http:Sleeping 0.23 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/ee-jfelix-netmetering/value:compute?prettyPrint=false&alt=json, after 503
 40%|███▉      | 1699/4292 [4:08:20<5:59:32,  8.32s/it]

LA_11241_2017 completed in 0:00:09.229658

 40%|███▉      | 1700/4292 [4:08:31<6:42:33,  9.32s/it]

LA_13478_2017 completed in 0:00:11.648379

 40%|███▉      | 1701/4292 [4:08:39<6:16:35,  8.72s/it]

LA_17698_2017 completed in 0:00:07.324766

 40%|███▉      | 1702/4292 [4:08:47<6:11:14,  8.60s/it]

MA_6374_2017 completed in 0:00:08.318028

 40%|███▉      | 1703/4292 [4:08:53<5:35:17,  7.77s/it]

MA_8774_2017 completed in 0:00:05.832648

 40%|███▉      | 1704/4292 [4:09:00<5:22:40,  7.48s/it]

MA_11804_2017 completed in 0:00:06.805271

 40%|███▉      | 1705/4292 [4:09:08<5:28:05,  7.61s/it]

MA_13206_2017 completed in 0:00:07.908029

 40%|███▉      | 1706/4292 [4:09:16<5:38:49,  7.86s/it]

MA_15748_2017 completed in 0:00:08.448574

 40%|███▉      | 1707/4292 [4:09:23<5:32:09,  7.71s/it]

MA_20455_2017 completed in 0:00:07.351898

 40%|███▉      | 1708/4292 [4:09:31<5:24:41,  7.54s/it]

MA_54913_2017 completed in 0:00:07.141160

 40%|███▉      | 1709/4292 [4:09:41<6:07:08,  8.53s/it]

MD_1167_2017 completed in 0:00:10.834489

 40%|███▉      | 1710/4292 [4:09:50<6:08:48,  8.57s/it]

MD_5027_2017 completed in 0:00:08.667721

 40%|███▉      | 1711/4292 [4:10:00<6:26:49,  8.99s/it]

MD_15263_2017 completed in 0:00:09.976213

 40%|███▉      | 1712/4292 [4:10:08<6:10:14,  8.61s/it]

MD_15270_2017 completed in 0:00:07.717892

 40%|███▉      | 1713/4292 [4:10:16<6:07:48,  8.56s/it]

MD_17637_2017 completed in 0:00:08.432125

 40%|███▉      | 1714/4292 [4:10:26<6:23:09,  8.92s/it]

ME_1179_2017 completed in 0:00:09.753281

 40%|███▉      | 1715/4292 [4:10:36<6:35:58,  9.22s/it]

ME_3266_2017 completed in 0:00:09.923169

 40%|███▉      | 1716/4292 [4:10:43<6:12:59,  8.69s/it]

MI_392_2017 completed in 0:00:07.445256

 40%|████      | 1717/4292 [4:10:51<5:55:04,  8.27s/it]

MI_3828_2017 completed in 0:00:07.306590

 40%|████      | 1718/4292 [4:10:59<5:57:41,  8.34s/it]

MI_4254_2017 completed in 0:00:08.486856

 40%|████      | 1719/4292 [4:11:06<5:40:58,  7.95s/it]

MI_5109_2017 completed in 0:00:07.047074

 40%|████      | 1720/4292 [4:11:13<5:24:39,  7.57s/it]

MI_9324_2017 completed in 0:00:06.692579

 40%|████      | 1721/4292 [4:11:20<5:16:21,  7.38s/it]

MI_10704_2017 completed in 0:00:06.936382

 40%|████      | 1722/4292 [4:11:28<5:21:57,  7.52s/it]

MI_19578_2017 completed in 0:00:07.828161

 40%|████      | 1723/4292 [4:11:33<4:59:35,  7.00s/it]

MN_689_2017 completed in 0:00:05.783633

 40%|████      | 1724/4292 [4:11:39<4:46:17,  6.69s/it]

MN_5574_2017 completed in 0:00:05.969115

 40%|████      | 1725/4292 [4:11:48<5:17:08,  7.41s/it]

MN_12647_2017 completed in 0:00:09.100396

 40%|████      | 1726/4292 [4:11:56<5:23:01,  7.55s/it]

MN_13781_2017 completed in 0:00:07.879962

 40%|████      | 1727/4292 [4:12:02<4:56:46,  6.94s/it]

MN_14232_2017 completed in 0:00:05.515621

 40%|████      | 1728/4292 [4:12:08<4:41:59,  6.60s/it]

MN_16181_2017 completed in 0:00:05.797342

 40%|████      | 1729/4292 [4:12:13<4:26:25,  6.24s/it]

MN_17267_2017 completed in 0:00:05.391368

 40%|████      | 1730/4292 [4:12:18<4:14:43,  5.97s/it]

MN_20996_2017 completed in 0:00:05.330993

 40%|████      | 1731/4292 [4:12:24<4:05:57,  5.76s/it]

MN_25177_2017 completed in 0:00:05.287360

 40%|████      | 1732/4292 [4:12:30<4:16:23,  6.01s/it]

MO_4675_2017 completed in 0:00:06.583696

 40%|████      | 1733/4292 [4:12:38<4:34:50,  6.44s/it]

MO_5860_2017 completed in 0:00:07.457198

 40%|████      | 1734/4292 [4:12:44<4:35:23,  6.46s/it]

MO_9231_2017 completed in 0:00:06.495262

 40%|████      | 1735/4292 [4:12:52<4:57:57,  6.99s/it]

MO_10000_2017 completed in 0:00:08.231398

 40%|████      | 1736/4292 [4:12:57<4:31:57,  6.38s/it]

MO_12698_2017 completed in 0:00:04.965748

 40%|████      | 1737/4292 [4:13:03<4:16:24,  6.02s/it]

MO_17833_2017 completed in 0:00:05.174234

 40%|████      | 1738/4292 [4:13:10<4:39:28,  6.57s/it]

MO_19436_2017 completed in 0:00:07.834562

 41%|████      | 1739/4292 [4:13:16<4:29:10,  6.33s/it]

MS_3841_2017 completed in 0:00:05.766587

 41%|████      | 1740/4292 [4:13:25<4:59:10,  7.03s/it]

MS_12685_2017 completed in 0:00:08.683715

 41%|████      | 1741/4292 [4:13:30<4:39:32,  6.57s/it]

MS_17647_2017 completed in 0:00:05.502658

 41%|████      | 1742/4292 [4:13:38<4:56:20,  6.97s/it]

MT_6395_2017 completed in 0:00:07.895383

 41%|████      | 1743/4292 [4:13:43<4:33:14,  6.43s/it]

MT_12692_2017 completed in 0:00:05.168900

 41%|████      | 1744/4292 [4:13:52<4:57:06,  7.00s/it]

MT_12825_2017 completed in 0:00:08.307522

 41%|████      | 1745/4292 [4:13:57<4:36:28,  6.51s/it]

MT_19603_2017 completed in 0:00:05.383847

 41%|████      | 1746/4292 [4:14:03<4:34:10,  6.46s/it]

MT_20997_2017 completed in 0:00:06.340909

 41%|████      | 1747/4292 [4:14:11<4:42:43,  6.67s/it]

NC_3046_2017 completed in 0:00:07.140289

 41%|████      | 1748/4292 [4:14:17<4:38:20,  6.56s/it]

NC_5416_2017 completed in 0:00:06.328864

 41%|████      | 1749/4292 [4:14:23<4:25:40,  6.27s/it]

NC_9837_2017 completed in 0:00:05.576504

 41%|████      | 1750/4292 [4:14:28<4:12:06,  5.95s/it]

NC_16496_2017 completed in 0:00:05.207875

 41%|████      | 1751/4292 [4:14:35<4:24:45,  6.25s/it]

NC_19876_2017 completed in 0:00:06.953814

 41%|████      | 1752/4292 [4:14:40<4:16:58,  6.07s/it]

NC_24889_2017 completed in 0:00:05.646502

 41%|████      | 1753/4292 [4:14:48<4:37:10,  6.55s/it]

ND_12301_2017 completed in 0:00:07.668796

 41%|████      | 1754/4292 [4:14:56<5:01:07,  7.12s/it]

ND_14232_2017 completed in 0:00:08.444559

 41%|████      | 1755/4292 [4:15:02<4:40:56,  6.64s/it]

ND_19790_2017 completed in 0:00:05.531157

 41%|████      | 1756/4292 [4:15:08<4:27:19,  6.32s/it]

ND_24949_2017 completed in 0:00:05.577926

 41%|████      | 1757/4292 [4:15:15<4:41:12,  6.66s/it]

NE_4373_2017 completed in 0:00:07.427426

 41%|████      | 1758/4292 [4:15:20<4:19:33,  6.15s/it]

NE_4911_2017 completed in 0:00:04.955646

 41%|████      | 1759/4292 [4:15:26<4:22:26,  6.22s/it]

NE_6779_2017 completed in 0:00:06.380599

 41%|████      | 1760/4292 [4:15:32<4:20:58,  6.18s/it]

NE_11018_2017 completed in 0:00:06.107169

 41%|████      | 1761/4292 [4:15:38<4:16:34,  6.08s/it]

NE_11251_2017 completed in 0:00:05.839368

 41%|████      | 1762/4292 [4:15:42<3:50:40,  5.47s/it]

NE_12539_2017 completed in 0:00:04.042400

 41%|████      | 1763/4292 [4:15:49<4:02:32,  5.75s/it]

NE_13337_2017 completed in 0:00:06.414910

 41%|████      | 1764/4292 [4:15:55<4:09:42,  5.93s/it]

NE_13664_2017 completed in 0:00:06.327629

 41%|████      | 1765/4292 [4:16:02<4:25:14,  6.30s/it]

NE_14127_2017 completed in 0:00:07.162833

 41%|████      | 1766/4292 [4:16:07<4:10:32,  5.95s/it]

NE_17642_2017 completed in 0:00:05.140986

 41%|████      | 1767/4292 [4:16:11<3:46:17,  5.38s/it]

NH_13441_2017 completed in 0:00:04.037354

 41%|████      | 1768/4292 [4:16:17<3:47:31,  5.41s/it]

NH_15472_2017 completed in 0:00:05.481213

 41%|████      | 1769/4292 [4:16:22<3:49:55,  5.47s/it]

NH_24590_2017 completed in 0:00:05.604955

 41%|████      | 1770/4292 [4:16:28<3:48:51,  5.44s/it]

NJ_963_2017 completed in 0:00:05.390224

 41%|████▏     | 1771/4292 [4:16:33<3:42:27,  5.29s/it]

NJ_9726_2017 completed in 0:00:04.942871

 41%|████▏     | 1772/4292 [4:16:40<4:04:21,  5.82s/it]

NJ_15477_2017 completed in 0:00:07.034639

 41%|████▏     | 1773/4292 [4:16:46<4:03:37,  5.80s/it]

NJ_16213_2017 completed in 0:00:05.766079

 41%|████▏     | 1774/4292 [4:16:51<3:58:19,  5.68s/it]

NM_3287_2017 completed in 0:00:05.383691

 41%|████▏     | 1775/4292 [4:16:57<3:57:33,  5.66s/it]

NM_5701_2017 completed in 0:00:05.625012

 41%|████▏     | 1776/4292 [4:17:01<3:36:50,  5.17s/it]

NM_6204_2017 completed in 0:00:04.020991

 41%|████▏     | 1777/4292 [4:17:06<3:36:44,  5.17s/it]

NM_11204_2017 completed in 0:00:05.169268

 41%|████▏     | 1778/4292 [4:17:12<3:45:39,  5.39s/it]

NM_15473_2017 completed in 0:00:05.881373

 41%|████▏     | 1779/4292 [4:17:19<4:05:30,  5.86s/it]

NM_17718_2017 completed in 0:00:06.972367

 41%|████▏     | 1780/4292 [4:17:22<3:38:46,  5.23s/it]

NV_2008_2017 completed in 0:00:03.739237

 41%|████▏     | 1781/4292 [4:17:28<3:42:37,  5.32s/it]

NV_13073_2017 completed in 0:00:05.536750

 42%|████▏     | 1782/4292 [4:17:33<3:43:28,  5.34s/it]

NV_13407_2017 completed in 0:00:05.392574

 42%|████▏     | 1783/4292 [4:17:39<3:50:00,  5.50s/it]

NV_17166_2017 completed in 0:00:05.869285

 42%|████▏     | 1784/4292 [4:17:44<3:35:47,  5.16s/it]

NV_19840_2017 completed in 0:00:04.372562

 42%|████▏     | 1785/4292 [4:17:49<3:43:21,  5.35s/it]

NY_3249_2017 completed in 0:00:05.771730

 42%|████▏     | 1786/4292 [4:17:54<3:38:50,  5.24s/it]

NY_4226_2017 completed in 0:00:04.991498

 42%|████▏     | 1787/4292 [4:17:59<3:32:56,  5.10s/it]

NY_11171_2017 completed in 0:00:04.774869

 42%|████▏     | 1788/4292 [4:18:10<4:50:00,  6.95s/it]

NY_13511_2017 completed in 0:00:11.260828

 42%|████▏     | 1789/4292 [4:18:18<5:01:11,  7.22s/it]

NY_13573_2017 completed in 0:00:07.851244

 42%|████▏     | 1790/4292 [4:18:23<4:35:20,  6.60s/it]

NY_14154_2017 completed in 0:00:05.162162

 42%|████▏     | 1791/4292 [4:18:29<4:19:27,  6.22s/it]

NY_16183_2017 completed in 0:00:05.336148

 42%|████▏     | 1792/4292 [4:18:35<4:15:27,  6.13s/it]

OH_3542_2017 completed in 0:00:05.911161

 42%|████▏     | 1793/4292 [4:18:40<4:08:13,  5.96s/it]

OH_3755_2017 completed in 0:00:05.559062

 42%|████▏     | 1794/4292 [4:18:48<4:28:05,  6.44s/it]

OH_4922_2017 completed in 0:00:07.557752

 42%|████▏     | 1795/4292 [4:18:54<4:28:57,  6.46s/it]

OH_13998_2017 completed in 0:00:06.516199

 42%|████▏     | 1796/4292 [4:19:04<5:11:49,  7.50s/it]

OH_14006_2017 completed in 0:00:09.905489

 42%|████▏     | 1797/4292 [4:19:12<5:09:41,  7.45s/it]

OH_18997_2017 completed in 0:00:07.333376

 42%|████▏     | 1798/4292 [4:19:18<4:52:29,  7.04s/it]

OK_5860_2017 completed in 0:00:06.076864

 42%|████▏     | 1799/4292 [4:19:24<4:48:36,  6.95s/it]

OK_13734_2017 completed in 0:00:06.733610

 42%|████▏     | 1800/4292 [4:19:29<4:20:52,  6.28s/it]

OK_14062_2017 completed in 0:00:04.726545

 42%|████▏     | 1801/4292 [4:19:36<4:24:55,  6.38s/it]

OK_14063_2017 completed in 0:00:06.614656

 42%|████▏     | 1802/4292 [4:19:43<4:37:17,  6.68s/it]

OK_15474_2017 completed in 0:00:07.377595

 42%|████▏     | 1803/4292 [4:19:50<4:34:05,  6.61s/it]

OK_19785_2017 completed in 0:00:06.432425

 42%|████▏     | 1804/4292 [4:19:55<4:17:13,  6.20s/it]

OR_6022_2017 completed in 0:00:05.259776

 42%|████▏     | 1805/4292 [4:20:01<4:16:03,  6.18s/it]

OR_9191_2017 completed in 0:00:06.116141

 42%|████▏     | 1806/4292 [4:20:07<4:08:37,  6.00s/it]

OR_14354_2017 completed in 0:00:05.586739

 42%|████▏     | 1807/4292 [4:20:11<3:48:59,  5.53s/it]

OR_15248_2017 completed in 0:00:04.427702

 42%|████▏     | 1808/4292 [4:20:15<3:27:37,  5.02s/it]

OR_18260_2017 completed in 0:00:03.815209

 42%|████▏     | 1809/4292 [4:20:20<3:35:44,  5.21s/it]

OR_28541_2017 completed in 0:00:05.675031

 42%|████▏     | 1810/4292 [4:20:26<3:39:30,  5.31s/it]

OR_40437_2017 completed in 0:00:05.523092

 42%|████▏     | 1811/4292 [4:20:31<3:40:49,  5.34s/it]

PA_3597_2017 completed in 0:00:05.418814

 42%|████▏     | 1812/4292 [4:20:37<3:48:14,  5.52s/it]

PA_5487_2017 completed in 0:00:05.943616

 42%|████▏     | 1813/4292 [4:20:43<3:55:49,  5.71s/it]

PA_12390_2017 completed in 0:00:06.140228

 42%|████▏     | 1814/4292 [4:20:53<4:40:11,  6.78s/it]

PA_14711_2017 completed in 0:00:09.295127

 42%|████▏     | 1815/4292 [4:20:59<4:38:43,  6.75s/it]

PA_14715_2017 completed in 0:00:06.674350

 42%|████▏     | 1816/4292 [4:21:05<4:21:29,  6.34s/it]

PA_14716_2017 completed in 0:00:05.367233

 42%|████▏     | 1817/4292 [4:21:11<4:23:13,  6.38s/it]

PA_14940_2017 completed in 0:00:06.485272

 42%|████▏     | 1818/4292 [4:21:17<4:09:57,  6.06s/it]

PA_15045_2017 completed in 0:00:05.315770

 42%|████▏     | 1819/4292 [4:21:25<4:38:46,  6.76s/it]

PA_19390_2017 completed in 0:00:08.400026

 42%|████▏     | 1820/4292 [4:21:31<4:29:32,  6.54s/it]

PA_20334_2017 completed in 0:00:06.020744

 42%|████▏     | 1821/4292 [4:21:39<4:41:56,  6.85s/it]

PA_20387_2017 completed in 0:00:07.553990

 42%|████▏     | 1822/4292 [4:21:43<4:14:48,  6.19s/it]

RI_1857_2017 completed in 0:00:04.657591

 42%|████▏     | 1823/4292 [4:21:49<4:11:19,  6.11s/it]

RI_13214_2017 completed in 0:00:05.913963

 42%|████▏     | 1824/4292 [4:21:57<4:32:59,  6.64s/it]

SC_1613_2017 completed in 0:00:07.866965

 43%|████▎     | 1825/4292 [4:22:02<4:18:30,  6.29s/it]

SC_3046_2017 completed in 0:00:05.471000

 43%|████▎     | 1826/4292 [4:22:07<3:55:59,  5.74s/it]

SC_5416_2017 completed in 0:00:04.467781

 43%|████▎     | 1827/4292 [4:22:12<3:44:53,  5.47s/it]

SC_14398_2017 completed in 0:00:04.848560

 43%|████▎     | 1828/4292 [4:22:17<3:41:05,  5.38s/it]

SC_17539_2017 completed in 0:00:05.171981

 43%|████▎     | 1829/4292 [4:22:26<4:21:36,  6.37s/it]

SC_17543_2017 completed in 0:00:08.679366

 43%|████▎     | 1830/4292 [4:22:31<4:12:32,  6.15s/it]

SD_1769_2017 completed in 0:00:05.640222

 43%|████▎     | 1831/4292 [4:22:35<3:47:41,  5.55s/it]

SD_14232_2017 completed in 0:00:04.143094

 43%|████▎     | 1832/4292 [4:22:39<3:25:41,  5.02s/it]

SD_17267_2017 completed in 0:00:03.769232

 43%|████▎     | 1833/4292 [4:22:43<3:14:30,  4.75s/it]

SD_19293_2017 completed in 0:00:04.108562

 43%|████▎     | 1834/4292 [4:22:47<3:06:55,  4.56s/it]

SD_20401_2017 completed in 0:00:04.135336

 43%|████▎     | 1835/4292 [4:22:52<3:06:14,  4.55s/it]

TN_10331_2017 completed in 0:00:04.512749

 43%|████▎     | 1836/4292 [4:22:59<3:32:56,  5.20s/it]

TX_5701_2017 completed in 0:00:06.727087

 43%|████▎     | 1837/4292 [4:23:06<4:01:34,  5.90s/it]

TX_16604_2017 completed in 0:00:07.541332

 43%|████▎     | 1838/4292 [4:23:12<4:03:12,  5.95s/it]

TX_17698_2017 completed in 0:00:06.044671

 43%|████▎     | 1839/4292 [4:23:19<4:08:20,  6.07s/it]

TX_55937_2017 completed in 0:00:06.371291

 43%|████▎     | 1840/4292 [4:23:26<4:25:10,  6.49s/it]

UT_2010_2017 completed in 0:00:07.454815

 43%|████▎     | 1841/4292 [4:23:32<4:22:02,  6.41s/it]

UT_11135_2017 completed in 0:00:06.240626

 43%|████▎     | 1842/4292 [4:23:38<4:08:38,  6.09s/it]

UT_12866_2017 completed in 0:00:05.328592

 43%|████▎     | 1843/4292 [4:23:46<4:38:36,  6.83s/it]

UT_14354_2017 completed in 0:00:08.543596

 43%|████▎     | 1844/4292 [4:23:54<4:51:10,  7.14s/it]

UT_15444_2017 completed in 0:00:07.861310

 43%|████▎     | 1845/4292 [4:23:59<4:26:45,  6.54s/it]

UT_17845_2017 completed in 0:00:05.150417

 43%|████▎     | 1846/4292 [4:24:08<4:49:44,  7.11s/it]

UT_17874_2017 completed in 0:00:08.427488

 43%|████▎     | 1847/4292 [4:24:16<5:00:27,  7.37s/it]

UT_18206_2017 completed in 0:00:07.992260

 43%|████▎     | 1848/4292 [4:24:20<4:26:36,  6.55s/it]

VA_84_2017 completed in 0:00:04.611099

 43%|████▎     | 1849/4292 [4:24:26<4:13:33,  6.23s/it]

VA_733_2017 completed in 0:00:05.485371

 43%|████▎     | 1850/4292 [4:24:31<4:04:18,  6.00s/it]

VA_10171_2017 completed in 0:00:05.477575

 43%|████▎     | 1851/4292 [4:24:37<4:00:48,  5.92s/it]

VA_17066_2017 completed in 0:00:05.722862

 43%|████▎     | 1852/4292 [4:24:44<4:14:05,  6.25s/it]

VA_19876_2017 completed in 0:00:07.014641

 43%|████▎     | 1853/4292 [4:24:50<4:12:28,  6.21s/it]

VA_19882_2017 completed in 0:00:06.123338

 43%|████▎     | 1854/4292 [4:24:56<4:05:22,  6.04s/it]

VA_40228_2017 completed in 0:00:05.636166

 43%|████▎     | 1855/4292 [4:25:02<4:01:58,  5.96s/it]

VT_2548_2017 completed in 0:00:05.767023

 43%|████▎     | 1856/4292 [4:25:08<4:13:00,  6.23s/it]

VT_7601_2017 completed in 0:00:06.870466

 43%|████▎     | 1857/4292 [4:25:15<4:13:59,  6.26s/it]

VT_19791_2017 completed in 0:00:06.320643

 43%|████▎     | 1858/4292 [4:25:20<4:05:41,  6.06s/it]

WA_3660_2017 completed in 0:00:05.583829

 43%|████▎     | 1859/4292 [4:25:30<4:44:11,  7.01s/it]

WA_14354_2017 completed in 0:00:09.228796

 43%|████▎     | 1860/4292 [4:25:35<4:30:47,  6.68s/it]

WA_15500_2017 completed in 0:00:05.914873

 43%|████▎     | 1861/4292 [4:25:43<4:46:01,  7.06s/it]

WA_16868_2017 completed in 0:00:07.942154

 43%|████▎     | 1862/4292 [4:25:50<4:39:25,  6.90s/it]

WA_17470_2017 completed in 0:00:06.525626

 43%|████▎     | 1863/4292 [4:26:05<6:16:41,  9.30s/it]

WA_18429_2017 completed in 0:00:14.916799

 43%|████▎     | 1864/4292 [4:26:10<5:22:39,  7.97s/it]

WA_20169_2017 completed in 0:00:04.860873

 43%|████▎     | 1865/4292 [4:26:15<4:50:57,  7.19s/it]

WI_4715_2017 completed in 0:00:05.371014

 43%|████▎     | 1866/4292 [4:26:25<5:24:06,  8.02s/it]

WI_5574_2017 completed in 0:00:09.935451

 43%|████▎     | 1867/4292 [4:26:30<4:43:28,  7.01s/it]

WI_11479_2017 completed in 0:00:04.674121

 44%|████▎     | 1868/4292 [4:26:35<4:27:48,  6.63s/it]

WI_13697_2017 completed in 0:00:05.725183

 44%|████▎     | 1869/4292 [4:26:44<4:54:53,  7.30s/it]

WI_13815_2017 completed in 0:00:08.873062

 44%|████▎     | 1870/4292 [4:26:52<5:03:04,  7.51s/it]

WI_20847_2017 completed in 0:00:07.987337

 44%|████▎     | 1871/4292 [4:26:59<4:57:59,  7.39s/it]

WI_20856_2017 completed in 0:00:07.097473

 44%|████▎     | 1872/4292 [4:27:12<5:58:16,  8.88s/it]

WI_20860_2017 completed in 0:00:12.376853

 44%|████▎     | 1873/4292 [4:27:18<5:26:48,  8.11s/it]

WV_733_2017 completed in 0:00:06.292117

 44%|████▎     | 1874/4292 [4:27:25<5:15:01,  7.82s/it]

WV_12796_2017 completed in 0:00:07.138210

 44%|████▎     | 1875/4292 [4:27:31<4:55:18,  7.33s/it]

WV_15263_2017 completed in 0:00:06.196239

 44%|████▎     | 1876/4292 [4:27:39<4:58:39,  7.42s/it]

WV_20521_2017 completed in 0:00:07.617235

 44%|████▎     | 1877/4292 [4:27:46<4:58:19,  7.41s/it]

WY_3461_2017 completed in 0:00:07.399268

 44%|████▍     | 1878/4292 [4:27:55<5:12:56,  7.78s/it]

WY_7222_2017 completed in 0:00:08.631378

 44%|████▍     | 1879/4292 [4:28:06<5:47:46,  8.65s/it]

WY_8566_2017 completed in 0:00:10.674753

 44%|████▍     | 1880/4292 [4:28:11<5:05:44,  7.61s/it]

WY_11273_2017 completed in 0:00:05.172913

 44%|████▍     | 1881/4292 [4:28:18<4:59:23,  7.45s/it]

WY_14354_2017 completed in 0:00:07.087889

 44%|████▍     | 1882/4292 [4:28:28<5:29:15,  8.20s/it]

WY_19156_2017 completed in 0:00:09.934059

 44%|████▍     | 1883/4292 [4:28:36<5:31:32,  8.26s/it]

WY_27058_2017 completed in 0:00:08.397328

 44%|████▍     | 1884/4292 [4:28:44<5:28:31,  8.19s/it]

ME_5609_2017 completed in 0:00:08.018096

 44%|████▍     | 1885/4292 [4:28:53<5:34:41,  8.34s/it]

MS_12686_2017 completed in 0:00:08.708143

 44%|████▍     | 1886/4292 [4:29:01<5:34:24,  8.34s/it]

NE_40606_2017 completed in 0:00:08.330063

 44%|████▍     | 1887/4292 [4:29:15<6:34:03,  9.83s/it]

RI_14537_2017 completed in 0:00:13.310996

 44%|████▍     | 1888/4292 [4:29:26<6:55:24, 10.37s/it]

AK_219_2018 completed in 0:00:11.620030

 44%|████▍     | 1889/4292 [4:29:37<6:58:53, 10.46s/it]

AK_599_2018 completed in 0:00:10.671666

 44%|████▍     | 1890/4292 [4:29:45<6:27:15,  9.67s/it]

AK_3522_2018 completed in 0:00:07.838649

 44%|████▍     | 1891/4292 [4:29:52<6:00:02,  9.00s/it]

AK_7353_2018 completed in 0:00:07.419259

 44%|████▍     | 1892/4292 [4:29:58<5:26:01,  8.15s/it]

AK_11824_2018 completed in 0:00:06.173368

 44%|████▍     | 1893/4292 [4:30:06<5:24:33,  8.12s/it]

AK_19558_2018 completed in 0:00:08.039002

 44%|████▍     | 1894/4292 [4:30:15<5:31:50,  8.30s/it]

AR_814_2018 completed in 0:00:08.732911

 44%|████▍     | 1895/4292 [4:30:25<5:54:41,  8.88s/it]

AR_817_2018 completed in 0:00:10.219737

 44%|████▍     | 1896/4292 [4:30:32<5:27:31,  8.20s/it]

AR_3093_2018 completed in 0:00:06.622573

 44%|████▍     | 1897/4292 [4:30:40<5:22:44,  8.09s/it]

AR_5860_2018 completed in 0:00:07.808479

 44%|████▍     | 1898/4292 [4:30:49<5:39:09,  8.50s/it]

AR_6342_2018 completed in 0:00:09.467298

 44%|████▍     | 1899/4292 [4:30:56<5:11:32,  7.81s/it]

AR_13718_2018 completed in 0:00:06.202942

 44%|████▍     | 1900/4292 [4:31:03<5:05:43,  7.67s/it]

AR_14063_2018 completed in 0:00:07.332001

 44%|████▍     | 1901/4292 [4:31:07<4:29:14,  6.76s/it]

AR_17698_2018 completed in 0:00:04.626076

 44%|████▍     | 1902/4292 [4:31:16<4:45:43,  7.17s/it]

AZ_176_2018 completed in 0:00:08.139287

 44%|████▍     | 1903/4292 [4:31:25<5:12:38,  7.85s/it]

AZ_803_2018 completed in 0:00:09.436233

 44%|████▍     | 1904/4292 [4:31:32<5:01:29,  7.58s/it]

AZ_12919_2018 completed in 0:00:06.928201

 44%|████▍     | 1905/4292 [4:31:37<4:32:45,  6.86s/it]

AZ_16572_2018 completed in 0:00:05.172780

 44%|████▍     | 1906/4292 [4:31:43<4:18:09,  6.49s/it]

AZ_19189_2018 completed in 0:00:05.640724

 44%|████▍     | 1907/4292 [4:31:49<4:11:10,  6.32s/it]

AZ_19728_2018 completed in 0:00:05.914486

 44%|████▍     | 1908/4292 [4:31:55<4:16:21,  6.45s/it]

AZ_21538_2018 completed in 0:00:06.761969

 44%|████▍     | 1909/4292 [4:32:02<4:14:16,  6.40s/it]

AZ_24211_2018 completed in 0:00:06.285539

 45%|████▍     | 1910/4292 [4:32:08<4:16:59,  6.47s/it]

CA_9216_2018 completed in 0:00:06.637328

 45%|████▍     | 1911/4292 [4:32:14<4:05:46,  6.19s/it]

CA_11208_2018 completed in 0:00:05.535133

 45%|████▍     | 1912/4292 [4:32:18<3:45:55,  5.70s/it]

CA_12745_2018 completed in 0:00:04.532450

 45%|████▍     | 1913/4292 [4:32:31<5:08:41,  7.79s/it]

CA_14328_2018 completed in 0:00:12.661518

 45%|████▍     | 1914/4292 [4:32:38<4:54:06,  7.42s/it]

CA_14354_2018 completed in 0:00:06.568821

 45%|████▍     | 1915/4292 [4:32:42<4:20:50,  6.58s/it]

CA_14534_2018 completed in 0:00:04.631242

 45%|████▍     | 1916/4292 [4:32:52<4:55:02,  7.45s/it]

CA_16534_2018 completed in 0:00:09.471363

 45%|████▍     | 1917/4292 [4:32:56<4:19:54,  6.57s/it]

CA_16609_2018 completed in 0:00:04.501087

 45%|████▍     | 1918/4292 [4:33:00<3:50:17,  5.82s/it]

CA_16655_2018 completed in 0:00:04.080059

 45%|████▍     | 1919/4292 [4:33:08<4:11:21,  6.36s/it]

CA_17609_2018 completed in 0:00:07.602251

 45%|████▍     | 1920/4292 [4:33:15<4:20:08,  6.58s/it]

CA_17612_2018 completed in 0:00:07.104047

 45%|████▍     | 1921/4292 [4:33:23<4:30:39,  6.85s/it]

CA_19281_2018 completed in 0:00:07.476181

 45%|████▍     | 1922/4292 [4:33:29<4:30:18,  6.84s/it]

CO_3989_2018 completed in 0:00:06.828542

 45%|████▍     | 1923/4292 [4:33:34<4:07:35,  6.27s/it]

CO_6604_2018 completed in 0:00:04.933069

 45%|████▍     | 1924/4292 [4:33:39<3:42:39,  5.64s/it]

CO_9336_2018 completed in 0:00:04.168076

 45%|████▍     | 1925/4292 [4:33:43<3:27:54,  5.27s/it]

CO_12866_2018 completed in 0:00:04.403364

 45%|████▍     | 1926/4292 [4:33:48<3:25:36,  5.21s/it]

CO_15257_2018 completed in 0:00:05.082064

 45%|████▍     | 1927/4292 [4:33:55<3:42:20,  5.64s/it]

CO_15466_2018 completed in 0:00:06.635504

 45%|████▍     | 1928/4292 [4:34:01<3:54:18,  5.95s/it]

CO_16603_2018 completed in 0:00:06.659933

 45%|████▍     | 1929/4292 [4:34:09<4:08:49,  6.32s/it]

CO_19499_2018 completed in 0:00:07.183673

 45%|████▍     | 1930/4292 [4:34:13<3:49:17,  5.82s/it]

CO_27058_2018 completed in 0:00:04.672527

 45%|████▍     | 1931/4292 [4:34:19<3:50:06,  5.85s/it]

CO_56146_2018 completed in 0:00:05.900046

 45%|████▌     | 1932/4292 [4:34:24<3:44:43,  5.71s/it]

CT_4176_2018 completed in 0:00:05.398878

 45%|████▌     | 1933/4292 [4:34:30<3:41:37,  5.64s/it]

CT_7716_2018 completed in 0:00:05.458565

 45%|████▌     | 1934/4292 [4:34:35<3:33:59,  5.44s/it]

CT_19497_2018 completed in 0:00:04.995456

 45%|████▌     | 1935/4292 [4:34:41<3:45:50,  5.75s/it]

CT_20038_2018 completed in 0:00:06.455821

 45%|████▌     | 1936/4292 [4:34:46<3:37:21,  5.54s/it]

DC_15270_2018 completed in 0:00:05.036393

 45%|████▌     | 1937/4292 [4:34:52<3:36:47,  5.52s/it]

DE_5027_2018 completed in 0:00:05.489120

 45%|████▌     | 1938/4292 [4:35:01<4:18:01,  6.58s/it]

DE_5070_2018 completed in 0:00:09.034483

 45%|████▌     | 1939/4292 [4:35:07<4:16:35,  6.54s/it]

DE_5335_2018 completed in 0:00:06.462863

 45%|████▌     | 1940/4292 [4:35:13<4:06:09,  6.28s/it]

DE_13519_2018 completed in 0:00:05.664162

 45%|████▌     | 1941/4292 [4:35:22<4:38:51,  7.12s/it]

FL_6452_2018 completed in 0:00:09.069067

 45%|████▌     | 1942/4292 [4:35:32<5:05:39,  7.80s/it]

FL_6455_2018 completed in 0:00:09.407186

 45%|████▌     | 1943/4292 [4:35:36<4:31:44,  6.94s/it]

FL_6457_2018 completed in 0:00:04.926096

 45%|████▌     | 1944/4292 [4:35:43<4:26:08,  6.80s/it]

FL_7801_2018 completed in 0:00:06.472592

 45%|████▌     | 1945/4292 [4:35:47<3:58:44,  6.10s/it]

FL_9617_2018 completed in 0:00:04.474881

 45%|████▌     | 1946/4292 [4:35:54<4:08:34,  6.36s/it]

FL_18454_2018 completed in 0:00:06.945249

 45%|████▌     | 1947/4292 [4:35:59<3:51:50,  5.93s/it]

GA_3916_2018 completed in 0:00:04.937667

 45%|████▌     | 1948/4292 [4:36:04<3:34:09,  5.48s/it]

GA_9601_2018 completed in 0:00:04.430212

 45%|████▌     | 1949/4292 [4:36:10<3:39:01,  5.61s/it]

HI_8287_2018 completed in 0:00:05.905241

 45%|████▌     | 1950/4292 [4:36:16<3:46:54,  5.81s/it]

HI_10071_2018 completed in 0:00:06.289456

 45%|████▌     | 1951/4292 [4:36:21<3:32:38,  5.45s/it]

HI_11843_2018 completed in 0:00:04.600876

 45%|████▌     | 1952/4292 [4:36:26<3:31:41,  5.43s/it]

HI_19547_2018 completed in 0:00:05.376104

 46%|████▌     | 1953/4292 [4:36:32<3:43:51,  5.74s/it]

IA_9417_2018 completed in 0:00:06.474898

 46%|████▌     | 1954/4292 [4:36:38<3:41:49,  5.69s/it]

IA_12341_2018 completed in 0:00:05.576293

 46%|████▌     | 1955/4292 [4:36:44<3:42:47,  5.72s/it]

ID_9187_2018 completed in 0:00:05.782241

 46%|████▌     | 1956/4292 [4:36:52<4:11:01,  6.45s/it]

ID_9191_2018 completed in 0:00:08.144629

 46%|████▌     | 1957/4292 [4:36:58<4:03:26,  6.26s/it]

ID_10454_2018 completed in 0:00:05.806483

 46%|████▌     | 1958/4292 [4:37:04<4:04:39,  6.29s/it]

ID_11273_2018 completed in 0:00:06.367262

 46%|████▌     | 1959/4292 [4:37:10<3:57:20,  6.10s/it]

ID_14354_2018 completed in 0:00:05.670954

 46%|████▌     | 1960/4292 [4:37:16<3:56:25,  6.08s/it]

ID_20169_2018 completed in 0:00:06.033120

 46%|████▌     | 1961/4292 [4:37:21<3:51:12,  5.95s/it]

IL_4110_2018 completed in 0:00:05.643101

 46%|████▌     | 1962/4292 [4:37:27<3:41:01,  5.69s/it]

IL_12341_2018 completed in 0:00:05.084156

 46%|████▌     | 1963/4292 [4:37:31<3:26:00,  5.31s/it]

IL_13032_2018 completed in 0:00:04.409621

 46%|████▌     | 1964/4292 [4:37:38<3:44:24,  5.78s/it]

IL_56697_2018 completed in 0:00:06.894228

 46%|████▌     | 1965/4292 [4:37:44<3:48:53,  5.90s/it]

IN_9273_2018 completed in 0:00:06.172392

 46%|████▌     | 1966/4292 [4:37:50<3:48:45,  5.90s/it]

IN_9324_2018 completed in 0:00:05.898123

 46%|████▌     | 1967/4292 [4:37:56<3:52:56,  6.01s/it]

IN_13756_2018 completed in 0:00:06.263213

 46%|████▌     | 1968/4292 [4:38:05<4:30:35,  6.99s/it]

IN_15470_2018 completed in 0:00:09.259798

 46%|████▌     | 1969/4292 [4:38:14<4:44:46,  7.36s/it]

IN_17633_2018 completed in 0:00:08.216032

 46%|████▌     | 1970/4292 [4:38:20<4:35:24,  7.12s/it]

KS_5860_2018 completed in 0:00:06.557259

 46%|████▌     | 1971/4292 [4:38:26<4:19:11,  6.70s/it]

KS_9996_2018 completed in 0:00:05.729082

 46%|████▌     | 1972/4292 [4:38:31<3:55:12,  6.08s/it]

KS_10000_2018 completed in 0:00:04.637302

 46%|████▌     | 1973/4292 [4:38:37<3:54:11,  6.06s/it]

KS_10005_2018 completed in 0:00:06.002617

 46%|████▌     | 1974/4292 [4:38:43<3:58:46,  6.18s/it]

KS_22500_2018 completed in 0:00:06.463498

 46%|████▌     | 1975/4292 [4:38:50<4:09:35,  6.46s/it]

KY_9964_2018 completed in 0:00:07.121467

 46%|████▌     | 1976/4292 [4:38:57<4:14:52,  6.60s/it]

KY_10171_2018 completed in 0:00:06.925597

 46%|████▌     | 1977/4292 [4:39:03<4:08:07,  6.43s/it]

KY_11249_2018 completed in 0:00:06.028117

 46%|████▌     | 1978/4292 [4:39:07<3:39:24,  5.69s/it]

KY_17564_2018 completed in 0:00:03.953349

 46%|████▌     | 1979/4292 [4:39:12<3:26:37,  5.36s/it]

KY_19446_2018 completed in 0:00:04.591352

 46%|████▌     | 1980/4292 [4:39:17<3:28:07,  5.40s/it]

KY_22053_2018 completed in 0:00:05.496722

 46%|████▌     | 1981/4292 [4:39:22<3:19:02,  5.17s/it]

KY_49998_2018 completed in 0:00:04.621906

 46%|████▌     | 1982/4292 [4:39:27<3:23:07,  5.28s/it]

LA_3265_2018 completed in 0:00:05.527147

 46%|████▌     | 1983/4292 [4:39:35<3:46:22,  5.88s/it]

LA_11241_2018 completed in 0:00:07.292054

 46%|████▌     | 1984/4292 [4:39:40<3:44:13,  5.83s/it]

LA_13478_2018 completed in 0:00:05.703666

 46%|████▌     | 1985/4292 [4:39:47<3:56:42,  6.16s/it]

LA_17698_2018 completed in 0:00:06.919471

 46%|████▋     | 1986/4292 [4:39:54<4:06:41,  6.42s/it]

MA_6374_2018 completed in 0:00:07.029693

 46%|████▋     | 1987/4292 [4:40:00<4:01:07,  6.28s/it]

MA_8774_2018 completed in 0:00:05.943804

 46%|████▋     | 1988/4292 [4:40:12<4:59:51,  7.81s/it]

MA_11804_2018 completed in 0:00:11.383335

 46%|████▋     | 1989/4292 [4:40:17<4:30:46,  7.05s/it]

MA_13206_2018 completed in 0:00:05.293498

 46%|████▋     | 1990/4292 [4:40:24<4:30:23,  7.05s/it]

MA_15748_2018 completed in 0:00:07.030649

 46%|████▋     | 1991/4292 [4:40:32<4:43:52,  7.40s/it]

MA_54913_2018 completed in 0:00:08.229541

 46%|████▋     | 1992/4292 [4:40:39<4:35:12,  7.18s/it]

MD_1167_2018 completed in 0:00:06.658081

 46%|████▋     | 1993/4292 [4:40:47<4:41:40,  7.35s/it]

MD_5027_2018 completed in 0:00:07.749663

 46%|████▋     | 1994/4292 [4:40:55<4:58:54,  7.80s/it]

MD_15263_2018 completed in 0:00:08.861410

 46%|████▋     | 1995/4292 [4:41:04<5:02:49,  7.91s/it]

MD_15270_2018 completed in 0:00:08.154277

 47%|████▋     | 1996/4292 [4:41:10<4:45:17,  7.46s/it]

MD_17637_2018 completed in 0:00:06.389070

 47%|████▋     | 1997/4292 [4:41:18<4:49:15,  7.56s/it]

ME_1179_2018 completed in 0:00:07.810644

 47%|████▋     | 1998/4292 [4:41:25<4:40:45,  7.34s/it]

ME_3266_2018 completed in 0:00:06.832014

 47%|████▋     | 1999/4292 [4:41:32<4:35:23,  7.21s/it]

ME_5609_2018 completed in 0:00:06.884206

 47%|████▋     | 2000/4292 [4:41:40<4:45:47,  7.48s/it]

MI_392_2018 completed in 0:00:08.123278

 47%|████▋     | 2001/4292 [4:41:47<4:41:23,  7.37s/it]

MI_3828_2018 completed in 0:00:07.107808

 47%|████▋     | 2002/4292 [4:41:56<5:04:58,  7.99s/it]

MI_4254_2018 completed in 0:00:09.438380

 47%|████▋     | 2003/4292 [4:42:02<4:45:21,  7.48s/it]

MI_5109_2018 completed in 0:00:06.288031

 47%|████▋     | 2004/4292 [4:42:14<5:30:51,  8.68s/it]

MI_9324_2018 completed in 0:00:11.466325

 47%|████▋     | 2005/4292 [4:42:23<5:33:57,  8.76s/it]

MI_10704_2018 completed in 0:00:08.959832

 47%|████▋     | 2006/4292 [4:42:31<5:22:18,  8.46s/it]

MI_19578_2018 completed in 0:00:07.754709

 47%|████▋     | 2007/4292 [4:42:39<5:21:59,  8.46s/it]

MN_689_2018 completed in 0:00:08.443317

 47%|████▋     | 2008/4292 [4:42:46<4:59:30,  7.87s/it]

MN_5574_2018 completed in 0:00:06.497497

 47%|████▋     | 2009/4292 [4:43:07<7:37:11, 12.02s/it]

MN_10596_2018 completed in 0:00:21.691533

 47%|████▋     | 2010/4292 [4:43:15<6:52:02, 10.83s/it]

MN_12647_2018 completed in 0:00:08.075943

 47%|████▋     | 2011/4292 [4:43:26<6:51:17, 10.82s/it]

MN_13781_2018 completed in 0:00:10.782618

 47%|████▋     | 2012/4292 [4:43:33<6:09:48,  9.73s/it]

MN_14232_2018 completed in 0:00:07.194858

 47%|████▋     | 2013/4292 [4:43:41<5:49:13,  9.19s/it]

MN_16181_2018 completed in 0:00:07.939017

 47%|████▋     | 2014/4292 [4:43:49<5:31:38,  8.74s/it]

MN_17267_2018 completed in 0:00:07.658867

 47%|████▋     | 2015/4292 [4:44:01<6:03:50,  9.59s/it]

MN_20996_2018 completed in 0:00:11.576107

 47%|████▋     | 2016/4292 [4:44:08<5:39:50,  8.96s/it]

MN_25177_2018 completed in 0:00:07.491494

 47%|████▋     | 2017/4292 [4:44:14<5:06:34,  8.09s/it]

MO_4675_2018 completed in 0:00:06.047072

 47%|████▋     | 2018/4292 [4:44:20<4:43:31,  7.48s/it]

MO_5860_2018 completed in 0:00:06.068030

 47%|████▋     | 2019/4292 [4:44:30<5:09:58,  8.18s/it]

MO_9231_2018 completed in 0:00:09.818750

 47%|████▋     | 2020/4292 [4:44:36<4:48:13,  7.61s/it]

MO_10000_2018 completed in 0:00:06.278500

 47%|████▋     | 2021/4292 [4:44:44<4:49:31,  7.65s/it]

MO_12698_2018 completed in 0:00:07.736114

 47%|████▋     | 2022/4292 [4:44:50<4:28:13,  7.09s/it]

MO_17833_2018 completed in 0:00:05.782578

 47%|████▋     | 2023/4292 [4:44:57<4:28:58,  7.11s/it]

MO_19436_2018 completed in 0:00:07.166121

 47%|████▋     | 2024/4292 [4:45:06<4:47:09,  7.60s/it]

MS_3841_2018 completed in 0:00:08.724971

 47%|████▋     | 2025/4292 [4:45:14<4:50:40,  7.69s/it]

MS_12685_2018 completed in 0:00:07.913193

 47%|████▋     | 2026/4292 [4:45:21<4:41:54,  7.46s/it]

MS_12686_2018 completed in 0:00:06.929745

 47%|████▋     | 2027/4292 [4:45:28<4:39:29,  7.40s/it]

MS_17647_2018 completed in 0:00:07.261077

 47%|████▋     | 2028/4292 [4:45:35<4:32:02,  7.21s/it]

MT_6395_2018 completed in 0:00:06.755325

 47%|████▋     | 2029/4292 [4:45:41<4:24:51,  7.02s/it]

MT_12692_2018 completed in 0:00:06.584599

 47%|████▋     | 2030/4292 [4:45:49<4:35:41,  7.31s/it]

MT_12825_2018 completed in 0:00:07.990000

 47%|████▋     | 2031/4292 [4:45:56<4:32:17,  7.23s/it]

MT_19603_2018 completed in 0:00:07.021992

 47%|████▋     | 2032/4292 [4:46:06<4:58:28,  7.92s/it]

MT_20997_2018 completed in 0:00:09.553151

 47%|████▋     | 2033/4292 [4:46:21<6:24:49, 10.22s/it]

NC_3046_2018 completed in 0:00:15.580048

 47%|████▋     | 2034/4292 [4:46:30<6:03:58,  9.67s/it]

NC_5416_2018 completed in 0:00:08.387436

 47%|████▋     | 2035/4292 [4:46:42<6:30:46, 10.39s/it]

NC_9837_2018 completed in 0:00:12.060594

 47%|████▋     | 2036/4292 [4:46:49<5:51:10,  9.34s/it]

NC_16496_2018 completed in 0:00:06.891970

 47%|████▋     | 2037/4292 [4:46:56<5:30:35,  8.80s/it]

NC_19876_2018 completed in 0:00:07.526679

 47%|████▋     | 2038/4292 [4:47:08<6:03:24,  9.67s/it]

NC_24889_2018 completed in 0:00:11.716587

 48%|████▊     | 2039/4292 [4:47:15<5:34:39,  8.91s/it]

ND_12301_2018 completed in 0:00:07.124659

 48%|████▊     | 2040/4292 [4:47:22<5:13:03,  8.34s/it]

ND_14232_2018 completed in 0:00:07.005939

 48%|████▊     | 2041/4292 [4:47:28<4:45:00,  7.60s/it]

ND_19790_2018 completed in 0:00:05.860942

 48%|████▊     | 2042/4292 [4:47:33<4:18:42,  6.90s/it]

ND_24949_2018 completed in 0:00:05.267941

 48%|████▊     | 2043/4292 [4:47:40<4:15:48,  6.82s/it]

NE_4373_2018 completed in 0:00:06.651200

 48%|████▊     | 2044/4292 [4:47:51<5:06:02,  8.17s/it]

NE_4911_2018 completed in 0:00:11.302342

 48%|████▊     | 2045/4292 [4:47:57<4:41:23,  7.51s/it]

NE_6779_2018 completed in 0:00:05.985955

 48%|████▊     | 2046/4292 [4:48:03<4:26:56,  7.13s/it]

NE_11018_2018 completed in 0:00:06.232210

 48%|████▊     | 2047/4292 [4:48:10<4:18:30,  6.91s/it]

NE_11251_2018 completed in 0:00:06.389676

 48%|████▊     | 2048/4292 [4:48:16<4:14:13,  6.80s/it]

NE_12539_2018 completed in 0:00:06.536811

 48%|████▊     | 2049/4292 [4:48:22<4:05:04,  6.56s/it]

NE_13337_2018 completed in 0:00:05.990335

 48%|████▊     | 2050/4292 [4:48:30<4:16:40,  6.87s/it]

NE_13664_2018 completed in 0:00:07.599428

 48%|████▊     | 2051/4292 [4:48:38<4:30:43,  7.25s/it]

NE_14127_2018 completed in 0:00:08.133179

 48%|████▊     | 2052/4292 [4:48:45<4:22:37,  7.03s/it]

NE_17642_2018 completed in 0:00:06.534121

 48%|████▊     | 2053/4292 [4:48:52<4:28:01,  7.18s/it]

NE_40606_2018 completed in 0:00:07.521941

 48%|████▊     | 2054/4292 [4:48:59<4:28:55,  7.21s/it]

NH_13441_2018 completed in 0:00:07.272637

 48%|████▊     | 2055/4292 [4:49:05<4:09:41,  6.70s/it]

NH_15472_2018 completed in 0:00:05.500279

 48%|████▊     | 2056/4292 [4:49:12<4:17:21,  6.91s/it]

NH_24590_2018 completed in 0:00:07.391579

 48%|████▊     | 2057/4292 [4:49:20<4:24:21,  7.10s/it]

NJ_963_2018 completed in 0:00:07.541556

 48%|████▊     | 2058/4292 [4:49:27<4:30:41,  7.27s/it]

NJ_9726_2018 completed in 0:00:07.674521

 48%|████▊     | 2059/4292 [4:49:36<4:43:18,  7.61s/it]

NJ_15477_2018 completed in 0:00:08.409155

 48%|████▊     | 2060/4292 [4:49:43<4:34:43,  7.39s/it]

NJ_16213_2018 completed in 0:00:06.854116

 48%|████▊     | 2061/4292 [4:49:50<4:30:18,  7.27s/it]

NM_3287_2018 completed in 0:00:06.998865

 48%|████▊     | 2062/4292 [4:49:58<4:40:38,  7.55s/it]

NM_5701_2018 completed in 0:00:08.205862

 48%|████▊     | 2063/4292 [4:50:03<4:13:40,  6.83s/it]

NM_6204_2018 completed in 0:00:05.142195

 48%|████▊     | 2064/4292 [4:50:10<4:18:26,  6.96s/it]

NM_11204_2018 completed in 0:00:07.265624

 48%|████▊     | 2065/4292 [4:50:16<4:01:46,  6.51s/it]

NM_15473_2018 completed in 0:00:05.467636

 48%|████▊     | 2066/4292 [4:50:22<3:58:00,  6.42s/it]

NM_17718_2018 completed in 0:00:06.183958

 48%|████▊     | 2067/4292 [4:50:29<4:04:26,  6.59s/it]

NV_2008_2018 completed in 0:00:07.002390

 48%|████▊     | 2068/4292 [4:50:35<3:55:22,  6.35s/it]

NV_13073_2018 completed in 0:00:05.786075

 48%|████▊     | 2069/4292 [4:50:42<4:10:25,  6.76s/it]

NV_13407_2018 completed in 0:00:07.708524

 48%|████▊     | 2070/4292 [4:50:49<4:09:41,  6.74s/it]

NV_17166_2018 completed in 0:00:06.702613

 48%|████▊     | 2071/4292 [4:50:53<3:39:24,  5.93s/it]

NV_19840_2018 completed in 0:00:04.024059

 48%|████▊     | 2072/4292 [4:50:59<3:43:01,  6.03s/it]

NY_3249_2018 completed in 0:00:06.261879

 48%|████▊     | 2073/4292 [4:51:05<3:37:24,  5.88s/it]

NY_4226_2018 completed in 0:00:05.529342

 48%|████▊     | 2074/4292 [4:51:10<3:33:16,  5.77s/it]

NY_11171_2018 completed in 0:00:05.513357

 48%|████▊     | 2075/4292 [4:51:19<4:06:46,  6.68s/it]

NY_13511_2018 completed in 0:00:08.794684

 48%|████▊     | 2076/4292 [4:51:27<4:17:09,  6.96s/it]

NY_13573_2018 completed in 0:00:07.624713

 48%|████▊     | 2077/4292 [4:51:35<4:27:03,  7.23s/it]

NY_14154_2018 completed in 0:00:07.866223

 48%|████▊     | 2078/4292 [4:51:44<4:44:23,  7.71s/it]

NY_16183_2018 completed in 0:00:08.809342

 48%|████▊     | 2079/4292 [4:51:49<4:13:22,  6.87s/it]

OH_3542_2018 completed in 0:00:04.914604

 48%|████▊     | 2080/4292 [4:51:56<4:14:57,  6.92s/it]

OH_3755_2018 completed in 0:00:07.021929

 48%|████▊     | 2081/4292 [4:52:01<3:59:21,  6.50s/it]

OH_4922_2018 completed in 0:00:05.515092

 49%|████▊     | 2082/4292 [4:52:09<4:11:40,  6.83s/it]

OH_13998_2018 completed in 0:00:07.618693

 49%|████▊     | 2083/4292 [4:52:17<4:23:04,  7.15s/it]

OH_14006_2018 completed in 0:00:07.874209

 49%|████▊     | 2084/4292 [4:52:24<4:27:55,  7.28s/it]

OH_18997_2018 completed in 0:00:07.595063

 49%|████▊     | 2085/4292 [4:52:32<4:35:21,  7.49s/it]

OK_5860_2018 completed in 0:00:07.959206

 49%|████▊     | 2086/4292 [4:52:37<4:10:03,  6.80s/it]

OK_13734_2018 completed in 0:00:05.203425

 49%|████▊     | 2087/4292 [4:52:45<4:15:25,  6.95s/it]

OK_14062_2018 completed in 0:00:07.296691

 49%|████▊     | 2088/4292 [4:52:51<4:13:52,  6.91s/it]

OK_14063_2018 completed in 0:00:06.818998

 49%|████▊     | 2089/4292 [4:52:58<4:07:44,  6.75s/it]

OK_15474_2018 completed in 0:00:06.364386

 49%|████▊     | 2090/4292 [4:53:04<3:58:50,  6.51s/it]

OK_19785_2018 completed in 0:00:05.949060

 49%|████▊     | 2091/4292 [4:53:09<3:49:24,  6.25s/it]

OR_6022_2018 completed in 0:00:05.659351

 49%|████▊     | 2092/4292 [4:53:18<4:11:35,  6.86s/it]

OR_9191_2018 completed in 0:00:08.278983

 49%|████▉     | 2093/4292 [4:53:24<4:04:23,  6.67s/it]

OR_14354_2018 completed in 0:00:06.213783

 49%|████▉     | 2094/4292 [4:53:29<3:48:15,  6.23s/it]

OR_15248_2018 completed in 0:00:05.210383

 49%|████▉     | 2095/4292 [4:53:38<4:15:24,  6.98s/it]

OR_18260_2018 completed in 0:00:08.711328

 49%|████▉     | 2096/4292 [4:53:43<3:57:00,  6.48s/it]

OR_28541_2018 completed in 0:00:05.309242

 49%|████▉     | 2097/4292 [4:53:50<3:56:11,  6.46s/it]

OR_40437_2018 completed in 0:00:06.409298

 49%|████▉     | 2098/4292 [4:53:57<4:11:12,  6.87s/it]

PA_3597_2018 completed in 0:00:07.834318

 49%|████▉     | 2099/4292 [4:54:04<4:06:35,  6.75s/it]

PA_5487_2018 completed in 0:00:06.458491

 49%|████▉     | 2100/4292 [4:54:11<4:15:42,  7.00s/it]

PA_12390_2018 completed in 0:00:07.587842

 49%|████▉     | 2101/4292 [4:54:20<4:29:43,  7.39s/it]

PA_14711_2018 completed in 0:00:08.288866

 49%|████▉     | 2102/4292 [4:54:34<5:39:53,  9.31s/it]

PA_14715_2018 completed in 0:00:13.805050

 49%|████▉     | 2103/4292 [4:54:46<6:12:13, 10.20s/it]

PA_14716_2018 completed in 0:00:12.278481

 49%|████▉     | 2104/4292 [4:54:52<5:27:03,  8.97s/it]

PA_14940_2018 completed in 0:00:06.088947

 49%|████▉     | 2105/4292 [4:54:58<4:52:15,  8.02s/it]

PA_15045_2018 completed in 0:00:05.799119

 49%|████▉     | 2106/4292 [4:55:03<4:19:58,  7.14s/it]

PA_19390_2018 completed in 0:00:05.075585

 49%|████▉     | 2107/4292 [4:55:09<4:05:31,  6.74s/it]

PA_20334_2018 completed in 0:00:05.823957

 49%|████▉     | 2108/4292 [4:55:16<4:11:19,  6.90s/it]

PA_20387_2018 completed in 0:00:07.281793

 49%|████▉     | 2109/4292 [4:55:21<3:55:19,  6.47s/it]

RI_1857_2018 completed in 0:00:05.448643

 49%|████▉     | 2110/4292 [4:55:28<3:58:00,  6.54s/it]

RI_13214_2018 completed in 0:00:06.723155

 49%|████▉     | 2111/4292 [4:55:34<3:53:09,  6.41s/it]

SC_1613_2018 completed in 0:00:06.108918

 49%|████▉     | 2112/4292 [4:55:39<3:40:08,  6.06s/it]

SC_3046_2018 completed in 0:00:05.229340

 49%|████▉     | 2113/4292 [4:55:48<4:05:05,  6.75s/it]

SC_5416_2018 completed in 0:00:08.357504

 49%|████▉     | 2114/4292 [4:55:53<3:51:58,  6.39s/it]

SC_14398_2018 completed in 0:00:05.553612

 49%|████▉     | 2115/4292 [4:55:59<3:45:25,  6.21s/it]

SC_17539_2018 completed in 0:00:05.797787

 49%|████▉     | 2116/4292 [4:56:04<3:27:15,  5.72s/it]

SC_17543_2018 completed in 0:00:04.552367

 49%|████▉     | 2117/4292 [4:56:07<3:06:24,  5.14s/it]

SD_1769_2018 completed in 0:00:03.804840

 49%|████▉     | 2118/4292 [4:56:12<2:57:46,  4.91s/it]

SD_14232_2018 completed in 0:00:04.355345

 49%|████▉     | 2119/4292 [4:56:16<2:54:48,  4.83s/it]

SD_17267_2018 completed in 0:00:04.639192

 49%|████▉     | 2120/4292 [4:56:23<3:13:37,  5.35s/it]

SD_19293_2018 completed in 0:00:06.566613

 49%|████▉     | 2121/4292 [4:56:28<3:14:14,  5.37s/it]

SD_20401_2018 completed in 0:00:05.412654

 49%|████▉     | 2122/4292 [4:56:34<3:19:44,  5.52s/it]

TN_10331_2018 completed in 0:00:05.881996

 49%|████▉     | 2123/4292 [4:56:40<3:16:04,  5.42s/it]

TX_5701_2018 completed in 0:00:05.189189

 49%|████▉     | 2124/4292 [4:56:44<3:07:13,  5.18s/it]

TX_16604_2018 completed in 0:00:04.615089

 50%|████▉     | 2125/4292 [4:56:50<3:09:58,  5.26s/it]

TX_17698_2018 completed in 0:00:05.442335

 50%|████▉     | 2126/4292 [4:56:55<3:11:36,  5.31s/it]

TX_55937_2018 completed in 0:00:05.417625

 50%|████▉     | 2127/4292 [4:57:00<3:07:31,  5.20s/it]

UT_2010_2018 completed in 0:00:04.936991

 50%|████▉     | 2128/4292 [4:57:04<2:51:52,  4.77s/it]

UT_11135_2018 completed in 0:00:03.757519

 50%|████▉     | 2129/4292 [4:57:10<3:05:24,  5.14s/it]

UT_12866_2018 completed in 0:00:06.023473

 50%|████▉     | 2130/4292 [4:57:16<3:20:30,  5.56s/it]

UT_14354_2018 completed in 0:00:06.547282

 50%|████▉     | 2131/4292 [4:57:21<3:07:36,  5.21s/it]

UT_15444_2018 completed in 0:00:04.378527

 50%|████▉     | 2132/4292 [4:57:25<2:57:00,  4.92s/it]

UT_17845_2018 completed in 0:00:04.234537

 50%|████▉     | 2133/4292 [4:57:29<2:43:30,  4.54s/it]

UT_17874_2018 completed in 0:00:03.673133

 50%|████▉     | 2134/4292 [4:57:32<2:35:21,  4.32s/it]

UT_18206_2018 completed in 0:00:03.793908

 50%|████▉     | 2135/4292 [4:57:37<2:39:55,  4.45s/it]

VA_84_2018 completed in 0:00:04.748988

 50%|████▉     | 2136/4292 [4:57:42<2:44:07,  4.57s/it]

VA_733_2018 completed in 0:00:04.844727

 50%|████▉     | 2137/4292 [4:57:46<2:35:20,  4.33s/it]

VA_10171_2018 completed in 0:00:03.758770

 50%|████▉     | 2138/4292 [4:57:51<2:42:04,  4.51s/it]

VA_17066_2018 completed in 0:00:04.955987

 50%|████▉     | 2139/4292 [4:57:58<3:08:16,  5.25s/it]

VA_19876_2018 completed in 0:00:06.950482

 50%|████▉     | 2140/4292 [4:58:03<3:04:48,  5.15s/it]

VA_19882_2018 completed in 0:00:04.931413

 50%|████▉     | 2141/4292 [4:58:08<3:08:14,  5.25s/it]

VA_40228_2018 completed in 0:00:05.473681

 50%|████▉     | 2142/4292 [4:58:13<3:07:20,  5.23s/it]

VT_2548_2018 completed in 0:00:05.174236

 50%|████▉     | 2143/4292 [4:58:18<3:05:32,  5.18s/it]

VT_7601_2018 completed in 0:00:05.068188

 50%|████▉     | 2144/4292 [4:58:24<3:05:58,  5.19s/it]

VT_19791_2018 completed in 0:00:05.225242

 50%|████▉     | 2145/4292 [4:58:28<3:01:32,  5.07s/it]

WA_3660_2018 completed in 0:00:04.788816

 50%|█████     | 2146/4292 [4:58:32<2:49:33,  4.74s/it]

WA_14354_2018 completed in 0:00:03.960113

 50%|█████     | 2147/4292 [4:58:38<3:03:59,  5.15s/it]

WA_15500_2018 completed in 0:00:06.092990

 50%|█████     | 2148/4292 [4:58:44<3:06:52,  5.23s/it]

WA_16868_2018 completed in 0:00:05.423160

 50%|█████     | 2149/4292 [4:58:50<3:14:05,  5.43s/it]

WA_17470_2018 completed in 0:00:05.910527

 50%|█████     | 2150/4292 [4:58:55<3:08:19,  5.28s/it]

WA_18429_2018 completed in 0:00:04.903108

 50%|█████     | 2151/4292 [4:59:01<3:16:54,  5.52s/it]

WA_20169_2018 completed in 0:00:06.083666

 50%|█████     | 2152/4292 [4:59:06<3:14:26,  5.45s/it]

WI_4715_2018 completed in 0:00:05.296137

 50%|█████     | 2153/4292 [4:59:12<3:24:55,  5.75s/it]

WI_5574_2018 completed in 0:00:06.439877

 50%|█████     | 2154/4292 [4:59:18<3:23:58,  5.72s/it]

WI_11479_2018 completed in 0:00:05.666810

 50%|█████     | 2155/4292 [4:59:24<3:27:41,  5.83s/it]

WI_13697_2018 completed in 0:00:06.080968

 50%|█████     | 2156/4292 [4:59:30<3:28:59,  5.87s/it]

WI_13815_2018 completed in 0:00:05.961619

 50%|█████     | 2157/4292 [4:59:36<3:28:05,  5.85s/it]

WI_20847_2018 completed in 0:00:05.794730

 50%|█████     | 2158/4292 [4:59:42<3:25:23,  5.78s/it]

WI_20856_2018 completed in 0:00:05.603451

 50%|█████     | 2159/4292 [4:59:47<3:17:51,  5.57s/it]

WI_20860_2018 completed in 0:00:05.075872

 50%|█████     | 2160/4292 [4:59:51<3:07:22,  5.27s/it]

WV_733_2018 completed in 0:00:04.590086

 50%|█████     | 2161/4292 [4:59:56<2:58:25,  5.02s/it]

WV_12796_2018 completed in 0:00:04.441276

 50%|█████     | 2162/4292 [5:00:02<3:08:30,  5.31s/it]

WV_15263_2018 completed in 0:00:05.976756

 50%|█████     | 2163/4292 [5:00:07<3:13:45,  5.46s/it]

WV_20521_2018 completed in 0:00:05.811255

 50%|█████     | 2164/4292 [5:00:14<3:28:36,  5.88s/it]

WY_3461_2018 completed in 0:00:06.863144

 50%|█████     | 2165/4292 [5:00:19<3:12:03,  5.42s/it]

WY_7222_2018 completed in 0:00:04.334589

 50%|█████     | 2166/4292 [5:00:25<3:17:27,  5.57s/it]

WY_8566_2018 completed in 0:00:05.932558

 50%|█████     | 2167/4292 [5:00:30<3:16:04,  5.54s/it]

WY_11273_2018 completed in 0:00:05.451367

 51%|█████     | 2168/4292 [5:00:38<3:42:02,  6.27s/it]

WY_14354_2018 completed in 0:00:07.988702

 51%|█████     | 2169/4292 [5:00:46<4:03:40,  6.89s/it]

WY_19156_2018 completed in 0:00:08.319213

 51%|█████     | 2170/4292 [5:00:52<3:54:29,  6.63s/it]

WY_27058_2018 completed in 0:00:06.030931

 51%|█████     | 2171/4292 [5:00:57<3:34:58,  6.08s/it]

CA_4390_2018 completed in 0:00:04.796143

 51%|█████     | 2172/4292 [5:01:04<3:40:28,  6.24s/it]

NE_27058_2018 completed in 0:00:06.608955

 51%|█████     | 2173/4292 [5:01:09<3:28:40,  5.91s/it]

NY_14711_2018 completed in 0:00:05.134168

 51%|█████     | 2174/4292 [5:01:14<3:22:55,  5.75s/it]

ME_11477_2018 completed in 0:00:05.373991

 51%|█████     | 2175/4292 [5:01:20<3:21:52,  5.72s/it]

MT_12199_2018 completed in 0:00:05.656925

 51%|█████     | 2176/4292 [5:01:26<3:21:22,  5.71s/it]

ND_12090_2018 completed in 0:00:05.683442

 51%|█████     | 2177/4292 [5:01:33<3:42:45,  6.32s/it]

RI_14537_2018 completed in 0:00:07.740174

 51%|█████     | 2178/4292 [5:01:39<3:36:42,  6.15s/it]

WY_12199_2018 completed in 0:00:05.755415

 51%|█████     | 2179/4292 [5:01:49<4:18:07,  7.33s/it]

AK_219_2019 completed in 0:00:10.079319

 51%|█████     | 2180/4292 [5:01:59<4:42:58,  8.04s/it]

AK_599_2019 completed in 0:00:09.694329

 51%|█████     | 2181/4292 [5:02:04<4:16:27,  7.29s/it]

AK_3522_2019 completed in 0:00:05.538900

 51%|█████     | 2182/4292 [5:02:14<4:36:10,  7.85s/it]

AK_7353_2019 completed in 0:00:09.168648

 51%|█████     | 2183/4292 [5:02:20<4:19:24,  7.38s/it]

AK_11824_2019 completed in 0:00:06.275032

 51%|█████     | 2184/4292 [5:02:26<4:02:14,  6.89s/it]

AK_19558_2019 completed in 0:00:05.761601

 51%|█████     | 2185/4292 [5:02:33<4:07:40,  7.05s/it]

AR_814_2019 completed in 0:00:07.420999

 51%|█████     | 2186/4292 [5:02:39<3:51:03,  6.58s/it]

AR_817_2019 completed in 0:00:05.485095

 51%|█████     | 2187/4292 [5:02:45<3:46:13,  6.45s/it]

AR_3093_2019 completed in 0:00:06.133571

 51%|█████     | 2188/4292 [5:02:53<4:06:47,  7.04s/it]

AR_5860_2019 completed in 0:00:08.413058

 51%|█████     | 2189/4292 [5:03:00<4:05:24,  7.00s/it]

AR_6342_2019 completed in 0:00:06.915880

 51%|█████     | 2190/4292 [5:03:10<4:32:04,  7.77s/it]

AR_13718_2019 completed in 0:00:09.549441

 51%|█████     | 2191/4292 [5:03:16<4:20:06,  7.43s/it]

AR_14063_2019 completed in 0:00:06.639196

 51%|█████     | 2192/4292 [5:03:22<3:59:38,  6.85s/it]

AR_17698_2019 completed in 0:00:05.489380

 51%|█████     | 2193/4292 [5:03:29<4:04:01,  6.98s/it]

AZ_176_2019 completed in 0:00:07.274957

 51%|█████     | 2194/4292 [5:03:37<4:14:31,  7.28s/it]

AZ_803_2019 completed in 0:00:07.986430

 51%|█████     | 2195/4292 [5:03:44<4:15:03,  7.30s/it]

AZ_12919_2019 completed in 0:00:07.340403

 51%|█████     | 2196/4292 [5:03:51<4:11:25,  7.20s/it]

AZ_16572_2019 completed in 0:00:06.961292

 51%|█████     | 2197/4292 [5:04:00<4:24:29,  7.58s/it]

AZ_19189_2019 completed in 0:00:08.456530

 51%|█████     | 2198/4292 [5:04:05<3:56:07,  6.77s/it]

AZ_19728_2019 completed in 0:00:04.876311

 51%|█████     | 2199/4292 [5:04:16<4:42:43,  8.10s/it]

AZ_21538_2019 completed in 0:00:11.228094

 51%|█████▏    | 2200/4292 [5:04:26<5:07:00,  8.81s/it]

AZ_24211_2019 completed in 0:00:10.438982

 51%|█████▏    | 2201/4292 [5:04:37<5:22:56,  9.27s/it]

CA_4390_2019 completed in 0:00:10.341807

 51%|█████▏    | 2202/4292 [5:04:49<5:50:30, 10.06s/it]

CA_9216_2019 completed in 0:00:11.918693

 51%|█████▏    | 2203/4292 [5:04:59<5:54:59, 10.20s/it]

CA_11208_2019 completed in 0:00:10.506697

 51%|█████▏    | 2204/4292 [5:05:10<5:59:59, 10.34s/it]

CA_12745_2019 completed in 0:00:10.690064

 51%|█████▏    | 2205/4292 [5:05:40<9:29:47, 16.38s/it]

CA_14328_2019 completed in 0:00:30.465468

 51%|█████▏    | 2206/4292 [5:05:56<9:26:13, 16.29s/it]

CA_14354_2019 completed in 0:00:16.064086

 51%|█████▏    | 2207/4292 [5:06:14<9:38:14, 16.64s/it]

CA_14534_2019 completed in 0:00:17.463984

 51%|█████▏    | 2208/4292 [5:06:24<8:35:53, 14.85s/it]

CA_16534_2019 completed in 0:00:10.681907

 51%|█████▏    | 2209/4292 [5:06:38<8:21:45, 14.45s/it]

CA_16609_2019 completed in 0:00:13.518852

 51%|█████▏    | 2210/4292 [5:06:55<8:53:48, 15.38s/it]

CA_16655_2019 completed in 0:00:17.553475

 52%|█████▏    | 2211/4292 [5:07:16<9:46:37, 16.91s/it]

CA_17609_2019 completed in 0:00:20.484629

 52%|█████▏    | 2212/4292 [5:07:26<8:30:15, 14.72s/it]

CA_17612_2019 completed in 0:00:09.596134

 52%|█████▏    | 2213/4292 [5:07:40<8:25:13, 14.58s/it]

CA_18260_2019 completed in 0:00:14.257046

 52%|█████▏    | 2214/4292 [5:07:48<7:20:21, 12.71s/it]

CA_19281_2019 completed in 0:00:08.360665

 52%|█████▏    | 2215/4292 [5:08:03<7:46:47, 13.48s/it]

CO_3989_2019 completed in 0:00:15.279284

 52%|█████▏    | 2216/4292 [5:08:11<6:48:23, 11.80s/it]

CO_6604_2019 completed in 0:00:07.879308

 52%|█████▏    | 2217/4292 [5:08:26<7:14:57, 12.58s/it]

CO_9336_2019 completed in 0:00:14.381853

 52%|█████▏    | 2218/4292 [5:08:32<6:12:11, 10.77s/it]

CO_12866_2019 completed in 0:00:06.544157

 52%|█████▏    | 2219/4292 [5:08:47<6:51:58, 11.92s/it]

CO_15257_2019 completed in 0:00:14.620746

 52%|█████▏    | 2220/4292 [5:08:59<6:52:08, 11.93s/it]

CO_15466_2019 completed in 0:00:11.958682

 52%|█████▏    | 2221/4292 [5:09:09<6:29:32, 11.29s/it]

CO_16603_2019 completed in 0:00:09.764255

 52%|█████▏    | 2222/4292 [5:09:16<5:52:53, 10.23s/it]

CO_19499_2019 completed in 0:00:07.761788

 52%|█████▏    | 2223/4292 [5:09:23<5:14:27,  9.12s/it]

CO_27058_2019 completed in 0:00:06.530140

 52%|█████▏    | 2224/4292 [5:09:29<4:37:51,  8.06s/it]

CO_56146_2019 completed in 0:00:05.588460

 52%|█████▏    | 2225/4292 [5:09:35<4:21:54,  7.60s/it]

CT_4176_2019 completed in 0:00:06.530279

 52%|█████▏    | 2226/4292 [5:09:41<4:03:07,  7.06s/it]

CT_7716_2019 completed in 0:00:05.795888

 52%|█████▏    | 2227/4292 [5:09:49<4:18:55,  7.52s/it]

CT_19497_2019 completed in 0:00:08.600626

 52%|█████▏    | 2228/4292 [5:09:57<4:15:09,  7.42s/it]

CT_20038_2019 completed in 0:00:07.170146

 52%|█████▏    | 2229/4292 [5:10:02<3:52:33,  6.76s/it]

DC_15270_2019 completed in 0:00:05.238240

 52%|█████▏    | 2230/4292 [5:10:10<4:11:29,  7.32s/it]

DE_5027_2019 completed in 0:00:08.609245

 52%|█████▏    | 2231/4292 [5:10:19<4:19:30,  7.55s/it]

DE_5070_2019 completed in 0:00:08.101893

 52%|█████▏    | 2232/4292 [5:10:26<4:17:36,  7.50s/it]

DE_5335_2019 completed in 0:00:07.381871

 52%|█████▏    | 2233/4292 [5:10:33<4:13:10,  7.38s/it]

DE_13519_2019 completed in 0:00:07.083528

 52%|█████▏    | 2234/4292 [5:10:40<4:06:04,  7.17s/it]

FL_6452_2019 completed in 0:00:06.699231

 52%|█████▏    | 2235/4292 [5:10:50<4:42:28,  8.24s/it]

FL_6455_2019 completed in 0:00:10.723146

 52%|█████▏    | 2236/4292 [5:10:58<4:34:43,  8.02s/it]

FL_6457_2019 completed in 0:00:07.497830

 52%|█████▏    | 2237/4292 [5:11:07<4:40:59,  8.20s/it]

FL_7801_2019 completed in 0:00:08.640346

 52%|█████▏    | 2238/4292 [5:11:11<4:01:03,  7.04s/it]

FL_9617_2019 completed in 0:00:04.327612

 52%|█████▏    | 2239/4292 [5:11:15<3:35:05,  6.29s/it]

FL_18454_2019 completed in 0:00:04.523216

 52%|█████▏    | 2240/4292 [5:11:22<3:40:08,  6.44s/it]

GA_3916_2019 completed in 0:00:06.787565

 52%|█████▏    | 2241/4292 [5:11:26<3:14:33,  5.69s/it]

GA_9601_2019 completed in 0:00:03.952396

 52%|█████▏    | 2242/4292 [5:11:47<5:53:41, 10.35s/it]

HI_8287_2019 completed in 0:00:21.224245

 52%|█████▏    | 2243/4292 [5:11:53<5:05:47,  8.95s/it]

HI_10071_2019 completed in 0:00:05.692957

 52%|█████▏    | 2244/4292 [5:11:59<4:31:31,  7.96s/it]

HI_11843_2019 completed in 0:00:05.622020

 52%|█████▏    | 2245/4292 [5:12:06<4:22:20,  7.69s/it]

HI_19547_2019 completed in 0:00:07.064568

 52%|█████▏    | 2246/4292 [5:12:11<3:52:49,  6.83s/it]

IA_9417_2019 completed in 0:00:04.815017

 52%|█████▏    | 2247/4292 [5:12:16<3:32:59,  6.25s/it]

IA_12341_2019 completed in 0:00:04.898960

 52%|█████▏    | 2248/4292 [5:12:21<3:22:29,  5.94s/it]

ID_9187_2019 completed in 0:00:05.231389

 52%|█████▏    | 2249/4292 [5:12:27<3:23:04,  5.96s/it]

ID_9191_2019 completed in 0:00:06.009743

 52%|█████▏    | 2250/4292 [5:12:34<3:33:20,  6.27s/it]

ID_10454_2019 completed in 0:00:06.978887

 52%|█████▏    | 2251/4292 [5:12:41<3:44:19,  6.59s/it]

ID_11273_2019 completed in 0:00:07.349675

 52%|█████▏    | 2252/4292 [5:12:48<3:48:04,  6.71s/it]

ID_14354_2019 completed in 0:00:06.971782

 52%|█████▏    | 2253/4292 [5:12:55<3:51:03,  6.80s/it]

ID_20169_2019 completed in 0:00:07.011981

 53%|█████▎    | 2254/4292 [5:13:02<3:50:26,  6.78s/it]

IL_4110_2019 completed in 0:00:06.747909

 53%|█████▎    | 2255/4292 [5:13:07<3:29:34,  6.17s/it]

IL_12341_2019 completed in 0:00:04.745078

 53%|█████▎    | 2256/4292 [5:13:11<3:14:20,  5.73s/it]

IL_13032_2019 completed in 0:00:04.686437

 53%|█████▎    | 2257/4292 [5:13:22<4:03:07,  7.17s/it]

IL_56697_2019 completed in 0:00:10.530320

 53%|█████▎    | 2258/4292 [5:13:28<3:50:56,  6.81s/it]

IN_9273_2019 completed in 0:00:05.981094

 53%|█████▎    | 2259/4292 [5:13:33<3:31:56,  6.25s/it]

IN_9324_2019 completed in 0:00:04.953146

 53%|█████▎    | 2260/4292 [5:13:41<3:53:33,  6.90s/it]

IN_13756_2019 completed in 0:00:08.392779

 53%|█████▎    | 2261/4292 [5:13:51<4:21:53,  7.74s/it]

IN_15470_2019 completed in 0:00:09.695807

 53%|█████▎    | 2262/4292 [5:13:57<4:06:00,  7.27s/it]

IN_17633_2019 completed in 0:00:06.184754

 53%|█████▎    | 2263/4292 [5:14:03<3:50:18,  6.81s/it]

KS_5860_2019 completed in 0:00:05.733981

 53%|█████▎    | 2264/4292 [5:14:10<3:50:43,  6.83s/it]

KS_9996_2019 completed in 0:00:06.858158

 53%|█████▎    | 2265/4292 [5:14:22<4:43:49,  8.40s/it]

KS_10000_2019 completed in 0:00:12.075783

 53%|█████▎    | 2266/4292 [5:14:26<4:00:11,  7.11s/it]

KS_10005_2019 completed in 0:00:04.106192

 53%|█████▎    | 2267/4292 [5:14:31<3:38:38,  6.48s/it]

KS_22500_2019 completed in 0:00:04.992034

 53%|█████▎    | 2268/4292 [5:14:35<3:17:38,  5.86s/it]

KY_9964_2019 completed in 0:00:04.411730

 53%|█████▎    | 2269/4292 [5:14:41<3:18:02,  5.87s/it]

KY_10171_2019 completed in 0:00:05.908665

 53%|█████▎    | 2270/4292 [5:14:47<3:14:02,  5.76s/it]

KY_11249_2019 completed in 0:00:05.486664

 53%|█████▎    | 2271/4292 [5:14:51<2:58:17,  5.29s/it]

KY_17564_2019 completed in 0:00:04.208155

 53%|█████▎    | 2272/4292 [5:14:56<2:57:53,  5.28s/it]

KY_19446_2019 completed in 0:00:05.259408

 53%|█████▎    | 2273/4292 [5:15:00<2:47:56,  4.99s/it]

KY_22053_2019 completed in 0:00:04.305964

 53%|█████▎    | 2274/4292 [5:15:06<2:50:08,  5.06s/it]

KY_49998_2019 completed in 0:00:05.215924

 53%|█████▎    | 2275/4292 [5:15:13<3:18:28,  5.90s/it]

LA_3265_2019 completed in 0:00:07.875194

 53%|█████▎    | 2276/4292 [5:15:19<3:13:24,  5.76s/it]

LA_11241_2019 completed in 0:00:05.406250

 53%|█████▎    | 2277/4292 [5:15:24<3:08:00,  5.60s/it]

LA_13478_2019 completed in 0:00:05.229109

 53%|█████▎    | 2278/4292 [5:15:29<3:00:37,  5.38s/it]

LA_17698_2019 completed in 0:00:04.872844

 53%|█████▎    | 2279/4292 [5:15:35<3:03:34,  5.47s/it]

MA_6374_2019 completed in 0:00:05.682280

 53%|█████▎    | 2280/4292 [5:15:38<2:46:44,  4.97s/it]

MA_8774_2019 completed in 0:00:03.807399

 53%|█████▎    | 2281/4292 [5:15:45<3:01:41,  5.42s/it]

MA_11804_2019 completed in 0:00:06.466367

 53%|█████▎    | 2282/4292 [5:15:52<3:13:37,  5.78s/it]

MA_13206_2019 completed in 0:00:06.615764

 53%|█████▎    | 2283/4292 [5:15:56<3:02:31,  5.45s/it]

MA_15748_2019 completed in 0:00:04.684277

 53%|█████▎    | 2284/4292 [5:16:02<3:03:31,  5.48s/it]

MA_54913_2019 completed in 0:00:05.557923

 53%|█████▎    | 2285/4292 [5:16:07<3:02:29,  5.46s/it]

MD_1167_2019 completed in 0:00:05.389002

 53%|█████▎    | 2286/4292 [5:16:13<3:01:50,  5.44s/it]

MD_5027_2019 completed in 0:00:05.398925

 53%|█████▎    | 2287/4292 [5:16:16<2:43:50,  4.90s/it]

MD_15263_2019 completed in 0:00:03.651129

 53%|█████▎    | 2288/4292 [5:16:21<2:41:58,  4.85s/it]

MD_15270_2019 completed in 0:00:04.720244

 53%|█████▎    | 2289/4292 [5:16:29<3:14:08,  5.82s/it]

MD_17637_2019 completed in 0:00:08.068972

 53%|█████▎    | 2290/4292 [5:16:35<3:10:33,  5.71s/it]

ME_1179_2019 completed in 0:00:05.464208

 53%|█████▎    | 2291/4292 [5:16:39<3:02:08,  5.46s/it]

ME_3266_2019 completed in 0:00:04.877328

 53%|█████▎    | 2292/4292 [5:16:43<2:41:14,  4.84s/it]

ME_5609_2019 completed in 0:00:03.375046

 53%|█████▎    | 2293/4292 [5:16:48<2:47:00,  5.01s/it]

MI_392_2019 completed in 0:00:05.420766

 53%|█████▎    | 2294/4292 [5:16:55<3:06:37,  5.60s/it]

MI_3828_2019 completed in 0:00:06.984997

 53%|█████▎    | 2295/4292 [5:17:00<3:03:00,  5.50s/it]

MI_4254_2019 completed in 0:00:05.250910

 53%|█████▎    | 2296/4292 [5:17:04<2:43:17,  4.91s/it]

MI_5109_2019 completed in 0:00:03.529967

 54%|█████▎    | 2297/4292 [5:17:09<2:41:03,  4.84s/it]

MI_9324_2019 completed in 0:00:04.692021

 54%|█████▎    | 2298/4292 [5:17:13<2:37:02,  4.73s/it]

MI_10704_2019 completed in 0:00:04.448225

 54%|█████▎    | 2299/4292 [5:17:18<2:42:02,  4.88s/it]

MI_19578_2019 completed in 0:00:05.234029

 54%|█████▎    | 2300/4292 [5:17:24<2:50:59,  5.15s/it]

MN_689_2019 completed in 0:00:05.784704

 54%|█████▎    | 2301/4292 [5:17:28<2:33:22,  4.62s/it]

MN_5574_2019 completed in 0:00:03.388593

 54%|█████▎    | 2302/4292 [5:17:32<2:32:17,  4.59s/it]

MN_10596_2019 completed in 0:00:04.520389

 54%|█████▎    | 2303/4292 [5:17:36<2:30:28,  4.54s/it]

MN_12647_2019 completed in 0:00:04.415706

 54%|█████▎    | 2304/4292 [5:17:43<2:52:47,  5.21s/it]

MN_13781_2019 completed in 0:00:06.790200

 54%|█████▎    | 2305/4292 [5:17:49<2:55:42,  5.31s/it]

MN_14232_2019 completed in 0:00:05.517466

 54%|█████▎    | 2306/4292 [5:17:52<2:34:12,  4.66s/it]

MN_16181_2019 completed in 0:00:03.147953

 54%|█████▍    | 2307/4292 [5:17:59<2:56:16,  5.33s/it]

MN_17267_2019 completed in 0:00:06.890054

 54%|█████▍    | 2308/4292 [5:18:06<3:11:20,  5.79s/it]

MN_20996_2019 completed in 0:00:06.854934

 54%|█████▍    | 2309/4292 [5:18:11<3:04:16,  5.58s/it]

MN_25177_2019 completed in 0:00:05.077094

 54%|█████▍    | 2310/4292 [5:18:18<3:21:17,  6.09s/it]

MO_4675_2019 completed in 0:00:07.301580

 54%|█████▍    | 2311/4292 [5:18:24<3:23:14,  6.16s/it]

MO_5860_2019 completed in 0:00:06.300144

 54%|█████▍    | 2312/4292 [5:18:30<3:16:13,  5.95s/it]

MO_9231_2019 completed in 0:00:05.455615

 54%|█████▍    | 2313/4292 [5:18:35<3:04:01,  5.58s/it]

MO_10000_2019 completed in 0:00:04.717657

 54%|█████▍    | 2314/4292 [5:18:39<2:51:05,  5.19s/it]

MO_12698_2019 completed in 0:00:04.280124

 54%|█████▍    | 2315/4292 [5:18:47<3:24:02,  6.19s/it]

MO_17833_2019 completed in 0:00:08.531405

 54%|█████▍    | 2316/4292 [5:18:53<3:18:08,  6.02s/it]

MO_19436_2019 completed in 0:00:05.605070

 54%|█████▍    | 2317/4292 [5:19:00<3:28:13,  6.33s/it]

MS_3841_2019 completed in 0:00:07.045138

 54%|█████▍    | 2318/4292 [5:19:06<3:29:41,  6.37s/it]

MS_12685_2019 completed in 0:00:06.484863

 54%|█████▍    | 2319/4292 [5:19:12<3:20:23,  6.09s/it]

MS_12686_2019 completed in 0:00:05.434887

 54%|█████▍    | 2320/4292 [5:19:20<3:35:19,  6.55s/it]

MS_17647_2019 completed in 0:00:07.617976

 54%|█████▍    | 2321/4292 [5:19:25<3:22:23,  6.16s/it]

MT_6395_2019 completed in 0:00:05.249477

 54%|█████▍    | 2322/4292 [5:19:32<3:34:47,  6.54s/it]

MT_12692_2019 completed in 0:00:07.429795

 54%|█████▍    | 2323/4292 [5:19:37<3:20:33,  6.11s/it]

MT_12825_2019 completed in 0:00:05.106341

 54%|█████▍    | 2324/4292 [5:19:43<3:15:09,  5.95s/it]

MT_19603_2019 completed in 0:00:05.571504

 54%|█████▍    | 2325/4292 [5:19:50<3:27:37,  6.33s/it]

MT_20997_2019 completed in 0:00:07.223090

 54%|█████▍    | 2326/4292 [5:19:58<3:46:27,  6.91s/it]

NC_3046_2019 completed in 0:00:08.258211

 54%|█████▍    | 2327/4292 [5:20:04<3:31:14,  6.45s/it]

NC_5416_2019 completed in 0:00:05.372825

 54%|█████▍    | 2328/4292 [5:20:10<3:31:31,  6.46s/it]

NC_9837_2019 completed in 0:00:06.490209

 54%|█████▍    | 2329/4292 [5:20:17<3:34:01,  6.54s/it]

NC_16496_2019 completed in 0:00:06.725791

 54%|█████▍    | 2330/4292 [5:20:23<3:25:55,  6.30s/it]

NC_19876_2019 completed in 0:00:05.726797

 54%|█████▍    | 2331/4292 [5:20:28<3:19:39,  6.11s/it]

NC_24889_2019 completed in 0:00:05.668855

 54%|█████▍    | 2332/4292 [5:20:33<3:02:42,  5.59s/it]

ND_12090_2019 completed in 0:00:04.388142

 54%|█████▍    | 2333/4292 [5:20:38<3:03:08,  5.61s/it]

ND_12301_2019 completed in 0:00:05.646107

 54%|█████▍    | 2334/4292 [5:20:44<3:05:05,  5.67s/it]

ND_14232_2019 completed in 0:00:05.817482

 54%|█████▍    | 2335/4292 [5:20:49<2:53:33,  5.32s/it]

ND_19790_2019 completed in 0:00:04.497461

 54%|█████▍    | 2336/4292 [5:20:55<3:07:43,  5.76s/it]

ND_24949_2019 completed in 0:00:06.777792

 54%|█████▍    | 2337/4292 [5:21:00<2:50:45,  5.24s/it]

NE_4373_2019 completed in 0:00:04.026240

 54%|█████▍    | 2338/4292 [5:21:05<2:51:41,  5.27s/it]

NE_4911_2019 completed in 0:00:05.345642

 54%|█████▍    | 2339/4292 [5:21:11<3:03:14,  5.63s/it]

NE_6779_2019 completed in 0:00:06.462578

 55%|█████▍    | 2340/4292 [5:21:17<3:02:08,  5.60s/it]

NE_11018_2019 completed in 0:00:05.524744

 55%|█████▍    | 2341/4292 [5:21:23<3:06:02,  5.72s/it]

NE_11251_2019 completed in 0:00:06.005294

 55%|█████▍    | 2342/4292 [5:21:28<3:02:39,  5.62s/it]

NE_12539_2019 completed in 0:00:05.383325

 55%|█████▍    | 2343/4292 [5:21:34<3:00:36,  5.56s/it]

NE_13337_2019 completed in 0:00:05.417651

 55%|█████▍    | 2344/4292 [5:21:39<3:02:42,  5.63s/it]

NE_13664_2019 completed in 0:00:05.784502

 55%|█████▍    | 2345/4292 [5:21:44<2:47:13,  5.15s/it]

NE_14127_2019 completed in 0:00:04.044893

 55%|█████▍    | 2346/4292 [5:21:47<2:35:39,  4.80s/it]

NE_17642_2019 completed in 0:00:03.968566

 55%|█████▍    | 2347/4292 [5:21:55<2:57:52,  5.49s/it]

NE_27058_2019 completed in 0:00:07.091649

 55%|█████▍    | 2348/4292 [5:22:00<2:52:34,  5.33s/it]

NE_40606_2019 completed in 0:00:04.950951

 55%|█████▍    | 2349/4292 [5:22:05<2:49:14,  5.23s/it]

NH_13441_2019 completed in 0:00:04.991481

 55%|█████▍    | 2350/4292 [5:22:09<2:44:53,  5.09s/it]

NH_15472_2019 completed in 0:00:04.785490

 55%|█████▍    | 2351/4292 [5:22:13<2:30:03,  4.64s/it]

NH_24590_2019 completed in 0:00:03.570370

 55%|█████▍    | 2352/4292 [5:22:19<2:40:25,  4.96s/it]

NJ_963_2019 completed in 0:00:05.713251

 55%|█████▍    | 2353/4292 [5:22:24<2:48:33,  5.22s/it]

NJ_9726_2019 completed in 0:00:05.809066

 55%|█████▍    | 2354/4292 [5:22:29<2:38:17,  4.90s/it]

NJ_15477_2019 completed in 0:00:04.163574

 55%|█████▍    | 2355/4292 [5:22:33<2:36:30,  4.85s/it]

NJ_16213_2019 completed in 0:00:04.723443

 55%|█████▍    | 2356/4292 [5:22:38<2:37:04,  4.87s/it]

NM_3287_2019 completed in 0:00:04.911119

 55%|█████▍    | 2357/4292 [5:22:44<2:45:43,  5.14s/it]

NM_5701_2019 completed in 0:00:05.766525

 55%|█████▍    | 2358/4292 [5:22:50<2:53:16,  5.38s/it]

NM_6204_2019 completed in 0:00:05.926873

 55%|█████▍    | 2359/4292 [5:22:56<3:02:06,  5.65s/it]

NM_11204_2019 completed in 0:00:06.297951

 55%|█████▍    | 2360/4292 [5:23:01<2:56:09,  5.47s/it]

NM_15473_2019 completed in 0:00:05.044918

 55%|█████▌    | 2361/4292 [5:23:08<3:05:31,  5.76s/it]

NM_17718_2019 completed in 0:00:06.448901

 55%|█████▌    | 2362/4292 [5:23:14<3:05:55,  5.78s/it]

NV_2008_2019 completed in 0:00:05.815207

 55%|█████▌    | 2363/4292 [5:23:19<3:02:20,  5.67s/it]

NV_13073_2019 completed in 0:00:05.417799

 55%|█████▌    | 2364/4292 [5:23:24<2:58:47,  5.56s/it]

NV_13407_2019 completed in 0:00:05.312738

 55%|█████▌    | 2365/4292 [5:23:32<3:18:26,  6.18s/it]

NV_17166_2019 completed in 0:00:07.611194

 55%|█████▌    | 2366/4292 [5:23:37<3:09:05,  5.89s/it]

NV_19840_2019 completed in 0:00:05.218014

 55%|█████▌    | 2367/4292 [5:23:43<3:09:11,  5.90s/it]

NY_3249_2019 completed in 0:00:05.909846

 55%|█████▌    | 2368/4292 [5:23:48<2:59:02,  5.58s/it]

NY_4226_2019 completed in 0:00:04.850316

 55%|█████▌    | 2369/4292 [5:23:54<3:00:33,  5.63s/it]

NY_11171_2019 completed in 0:00:05.749604

 55%|█████▌    | 2370/4292 [5:24:02<3:26:19,  6.44s/it]

NY_13511_2019 completed in 0:00:08.324677

 55%|█████▌    | 2371/4292 [5:24:11<3:49:18,  7.16s/it]

NY_13573_2019 completed in 0:00:08.843451

 55%|█████▌    | 2372/4292 [5:24:17<3:45:02,  7.03s/it]

NY_14154_2019 completed in 0:00:06.726379

 55%|█████▌    | 2373/4292 [5:24:24<3:37:00,  6.79s/it]

NY_14711_2019 completed in 0:00:06.207694

 55%|█████▌    | 2374/4292 [5:24:28<3:11:57,  6.01s/it]

NY_16183_2019 completed in 0:00:04.184297

 55%|█████▌    | 2375/4292 [5:24:35<3:23:49,  6.38s/it]

OH_3542_2019 completed in 0:00:07.252411

 55%|█████▌    | 2376/4292 [5:24:40<3:10:43,  5.97s/it]

OH_3755_2019 completed in 0:00:05.021045

 55%|█████▌    | 2377/4292 [5:24:48<3:30:16,  6.59s/it]

OH_4922_2019 completed in 0:00:08.024538

 55%|█████▌    | 2378/4292 [5:24:56<3:39:39,  6.89s/it]

OH_13998_2019 completed in 0:00:07.578382

 55%|█████▌    | 2379/4292 [5:25:03<3:39:54,  6.90s/it]

OH_14006_2019 completed in 0:00:06.922931

 55%|█████▌    | 2380/4292 [5:25:09<3:31:39,  6.64s/it]

OH_18997_2019 completed in 0:00:06.046284

 55%|█████▌    | 2381/4292 [5:25:15<3:31:20,  6.64s/it]

OK_5860_2019 completed in 0:00:06.618933

 55%|█████▌    | 2382/4292 [5:25:22<3:32:56,  6.69s/it]

OK_13734_2019 completed in 0:00:06.814950

 56%|█████▌    | 2383/4292 [5:25:28<3:20:50,  6.31s/it]

OK_14062_2019 completed in 0:00:05.427295

 56%|█████▌    | 2384/4292 [5:25:35<3:29:54,  6.60s/it]

OK_14063_2019 completed in 0:00:07.272928

 56%|█████▌    | 2385/4292 [5:25:42<3:33:23,  6.71s/it]

OK_15474_2019 completed in 0:00:06.973202

 56%|█████▌    | 2386/4292 [5:25:47<3:17:38,  6.22s/it]

OK_19785_2019 completed in 0:00:05.071931

 56%|█████▌    | 2387/4292 [5:25:51<2:57:51,  5.60s/it]

OR_6022_2019 completed in 0:00:04.152790

 56%|█████▌    | 2388/4292 [5:25:59<3:16:09,  6.18s/it]

OR_9191_2019 completed in 0:00:07.531534

 56%|█████▌    | 2389/4292 [5:26:05<3:22:35,  6.39s/it]

OR_14354_2019 completed in 0:00:06.862822

 56%|█████▌    | 2390/4292 [5:26:10<3:07:44,  5.92s/it]

OR_15248_2019 completed in 0:00:04.836048

 56%|█████▌    | 2391/4292 [5:26:19<3:32:29,  6.71s/it]

OR_18260_2019 completed in 0:00:08.533472

 56%|█████▌    | 2392/4292 [5:26:25<3:22:12,  6.39s/it]

OR_28541_2019 completed in 0:00:05.633642

 56%|█████▌    | 2393/4292 [5:26:31<3:19:48,  6.31s/it]

OR_40437_2019 completed in 0:00:06.138041

 56%|█████▌    | 2394/4292 [5:26:38<3:29:42,  6.63s/it]

PA_3597_2019 completed in 0:00:07.366569

 56%|█████▌    | 2395/4292 [5:26:43<3:09:38,  6.00s/it]

PA_5487_2019 completed in 0:00:04.523986

 56%|█████▌    | 2396/4292 [5:26:49<3:11:06,  6.05s/it]

PA_12390_2019 completed in 0:00:06.163792

 56%|█████▌    | 2397/4292 [5:26:56<3:24:26,  6.47s/it]

PA_14711_2019 completed in 0:00:07.462933

 56%|█████▌    | 2398/4292 [5:27:03<3:30:54,  6.68s/it]

PA_14715_2019 completed in 0:00:07.165603

 56%|█████▌    | 2399/4292 [5:27:10<3:34:35,  6.80s/it]

PA_14716_2019 completed in 0:00:07.081069

 56%|█████▌    | 2400/4292 [5:27:17<3:33:39,  6.78s/it]

PA_14940_2019 completed in 0:00:06.714772

 56%|█████▌    | 2401/4292 [5:27:22<3:19:10,  6.32s/it]

PA_15045_2019 completed in 0:00:05.253826

 56%|█████▌    | 2402/4292 [5:27:29<3:22:24,  6.43s/it]

PA_19390_2019 completed in 0:00:06.672549

 56%|█████▌    | 2403/4292 [5:27:34<3:06:30,  5.92s/it]

PA_20334_2019 completed in 0:00:04.752304

 56%|█████▌    | 2404/4292 [5:27:43<3:35:52,  6.86s/it]

PA_20387_2019 completed in 0:00:09.044064

 56%|█████▌    | 2405/4292 [5:27:50<3:35:00,  6.84s/it]

RI_1857_2019 completed in 0:00:06.779604

 56%|█████▌    | 2406/4292 [5:27:56<3:33:29,  6.79s/it]

RI_13214_2019 completed in 0:00:06.686449

 56%|█████▌    | 2407/4292 [5:28:04<3:38:34,  6.96s/it]

RI_14537_2019 completed in 0:00:07.342610

 56%|█████▌    | 2408/4292 [5:28:09<3:27:03,  6.59s/it]

SC_1613_2019 completed in 0:00:05.745522

 56%|█████▌    | 2409/4292 [5:28:15<3:12:50,  6.14s/it]

SC_3046_2019 completed in 0:00:05.096195

 56%|█████▌    | 2410/4292 [5:28:21<3:13:14,  6.16s/it]

SC_5416_2019 completed in 0:00:06.196477

 56%|█████▌    | 2411/4292 [5:28:27<3:15:29,  6.24s/it]

SC_14398_2019 completed in 0:00:06.409335

 56%|█████▌    | 2412/4292 [5:28:33<3:15:35,  6.24s/it]

SC_17539_2019 completed in 0:00:06.257925

 56%|█████▌    | 2413/4292 [5:28:38<3:02:29,  5.83s/it]

SC_17543_2019 completed in 0:00:04.858052

 56%|█████▌    | 2414/4292 [5:28:45<3:14:23,  6.21s/it]

SD_1769_2019 completed in 0:00:07.102549

 56%|█████▋    | 2415/4292 [5:28:52<3:18:29,  6.35s/it]

SD_14232_2019 completed in 0:00:06.658280

 56%|█████▋    | 2416/4292 [5:28:57<3:08:54,  6.04s/it]

SD_17267_2019 completed in 0:00:05.334373

 56%|█████▋    | 2417/4292 [5:29:02<2:55:09,  5.60s/it]

SD_19293_2019 completed in 0:00:04.583746

 56%|█████▋    | 2418/4292 [5:29:07<2:47:19,  5.36s/it]

SD_20401_2019 completed in 0:00:04.773910

 56%|█████▋    | 2419/4292 [5:29:13<2:54:51,  5.60s/it]

TN_10331_2019 completed in 0:00:06.171106

 56%|█████▋    | 2420/4292 [5:29:18<2:53:31,  5.56s/it]

TX_5701_2019 completed in 0:00:05.466827

 56%|█████▋    | 2421/4292 [5:29:23<2:48:35,  5.41s/it]

TX_16604_2019 completed in 0:00:05.043537

 56%|█████▋    | 2422/4292 [5:29:29<2:51:13,  5.49s/it]

TX_55937_2019 completed in 0:00:05.697269

 56%|█████▋    | 2423/4292 [5:29:33<2:40:17,  5.15s/it]

UT_2010_2019 completed in 0:00:04.332100

 56%|█████▋    | 2424/4292 [5:29:40<2:58:01,  5.72s/it]

UT_11135_2019 completed in 0:00:07.052965

 57%|█████▋    | 2425/4292 [5:29:47<3:02:09,  5.85s/it]

UT_12866_2019 completed in 0:00:06.169601

 57%|█████▋    | 2426/4292 [5:29:54<3:14:33,  6.26s/it]

UT_14354_2019 completed in 0:00:07.192499

 57%|█████▋    | 2427/4292 [5:29:59<3:00:39,  5.81s/it]

UT_15444_2019 completed in 0:00:04.776189

 57%|█████▋    | 2428/4292 [5:30:04<2:52:34,  5.55s/it]

UT_17845_2019 completed in 0:00:04.953389

 57%|█████▋    | 2429/4292 [5:30:09<2:54:37,  5.62s/it]

UT_17874_2019 completed in 0:00:05.779289

 57%|█████▋    | 2430/4292 [5:30:15<2:58:04,  5.74s/it]

UT_18206_2019 completed in 0:00:06.004466

 57%|█████▋    | 2431/4292 [5:30:19<2:42:35,  5.24s/it]

VA_84_2019 completed in 0:00:04.081308

 57%|█████▋    | 2432/4292 [5:30:24<2:37:13,  5.07s/it]

VA_733_2019 completed in 0:00:04.673611

 57%|█████▋    | 2433/4292 [5:30:30<2:41:30,  5.21s/it]

VA_10171_2019 completed in 0:00:05.539932

 57%|█████▋    | 2434/4292 [5:30:36<2:55:32,  5.67s/it]

VA_17066_2019 completed in 0:00:06.731645

 57%|█████▋    | 2435/4292 [5:30:44<3:15:23,  6.31s/it]

VA_19876_2019 completed in 0:00:07.816938

 57%|█████▋    | 2436/4292 [5:30:50<3:08:58,  6.11s/it]

VA_19882_2019 completed in 0:00:05.631840

 57%|█████▋    | 2437/4292 [5:30:55<3:03:43,  5.94s/it]

VA_40228_2019 completed in 0:00:05.553944

 57%|█████▋    | 2438/4292 [5:31:01<3:03:00,  5.92s/it]

VT_2548_2019 completed in 0:00:05.873946

 57%|█████▋    | 2439/4292 [5:31:07<2:58:38,  5.78s/it]

VT_7601_2019 completed in 0:00:05.460636

 57%|█████▋    | 2440/4292 [5:31:13<2:58:59,  5.80s/it]

VT_19791_2019 completed in 0:00:05.833074

 57%|█████▋    | 2441/4292 [5:31:18<2:54:19,  5.65s/it]

WA_3660_2019 completed in 0:00:05.304554

 57%|█████▋    | 2442/4292 [5:31:24<2:57:59,  5.77s/it]

WA_14354_2019 completed in 0:00:06.055008

 57%|█████▋    | 2443/4292 [5:31:32<3:21:34,  6.54s/it]

WA_15500_2019 completed in 0:00:08.333099

 57%|█████▋    | 2444/4292 [5:31:37<3:07:03,  6.07s/it]

WA_16868_2019 completed in 0:00:04.981395

 57%|█████▋    | 2445/4292 [5:31:42<2:55:34,  5.70s/it]

WA_17470_2019 completed in 0:00:04.839769

 57%|█████▋    | 2446/4292 [5:31:48<2:55:19,  5.70s/it]

WA_18429_2019 completed in 0:00:05.685938

 57%|█████▋    | 2447/4292 [5:31:55<3:12:18,  6.25s/it]

WA_20169_2019 completed in 0:00:07.548619

 57%|█████▋    | 2448/4292 [5:32:01<3:06:06,  6.06s/it]

WI_4715_2019 completed in 0:00:05.591548

 57%|█████▋    | 2449/4292 [5:32:08<3:13:54,  6.31s/it]

WI_5574_2019 completed in 0:00:06.912648

 57%|█████▋    | 2450/4292 [5:32:15<3:25:59,  6.71s/it]

WI_11479_2019 completed in 0:00:07.635242

 57%|█████▋    | 2451/4292 [5:32:24<3:39:26,  7.15s/it]

WI_13697_2019 completed in 0:00:08.178990

 57%|█████▋    | 2452/4292 [5:32:33<3:56:15,  7.70s/it]

WI_13815_2019 completed in 0:00:08.991674

 57%|█████▋    | 2453/4292 [5:32:39<3:43:13,  7.28s/it]

WI_20847_2019 completed in 0:00:06.299530

 57%|█████▋    | 2454/4292 [5:32:45<3:28:41,  6.81s/it]

WI_20856_2019 completed in 0:00:05.715075

 57%|█████▋    | 2455/4292 [5:32:51<3:25:36,  6.72s/it]

WI_20860_2019 completed in 0:00:06.487891

 57%|█████▋    | 2456/4292 [5:33:02<4:04:12,  7.98s/it]

WV_733_2019 completed in 0:00:10.931354

 57%|█████▋    | 2457/4292 [5:33:08<3:43:51,  7.32s/it]

WV_12796_2019 completed in 0:00:05.776892

 57%|█████▋    | 2458/4292 [5:33:13<3:24:11,  6.68s/it]

WV_15263_2019 completed in 0:00:05.186085

 57%|█████▋    | 2459/4292 [5:33:19<3:20:26,  6.56s/it]

WV_20521_2019 completed in 0:00:06.282673

 57%|█████▋    | 2460/4292 [5:33:25<3:14:24,  6.37s/it]

WY_3461_2019 completed in 0:00:05.913782

 57%|█████▋    | 2461/4292 [5:33:33<3:27:57,  6.81s/it]

WY_7222_2019 completed in 0:00:07.857880

 57%|█████▋    | 2462/4292 [5:33:42<3:48:56,  7.51s/it]

WY_8566_2019 completed in 0:00:09.119070

 57%|█████▋    | 2463/4292 [5:33:52<4:08:35,  8.15s/it]

WY_11273_2019 completed in 0:00:09.667633

 57%|█████▋    | 2464/4292 [5:34:02<4:21:58,  8.60s/it]

WY_14354_2019 completed in 0:00:09.633777

 57%|█████▋    | 2465/4292 [5:34:12<4:42:31,  9.28s/it]

WY_19156_2019 completed in 0:00:10.862421

 57%|█████▋    | 2466/4292 [5:34:18<4:08:51,  8.18s/it]

WY_27058_2019 completed in 0:00:05.607662

 57%|█████▋    | 2467/4292 [5:34:27<4:13:33,  8.34s/it]

MT_12199_2019 completed in 0:00:08.700737

 58%|█████▊    | 2468/4292 [5:34:35<4:14:47,  8.38s/it]

WY_12199_2019 completed in 0:00:08.486112

 58%|█████▊    | 2469/4292 [5:34:45<4:24:24,  8.70s/it]

WI_13780_2019 completed in 0:00:09.451548

 58%|█████▊    | 2470/4292 [5:34:53<4:24:53,  8.72s/it]

ME_11477_2019 completed in 0:00:08.770318

 58%|█████▊    | 2471/4292 [5:35:06<5:01:42,  9.94s/it]

AK_219_2020 completed in 0:00:12.776970

 58%|█████▊    | 2472/4292 [5:35:16<5:00:24,  9.90s/it]

AK_599_2020 completed in 0:00:09.809851

 58%|█████▊    | 2473/4292 [5:35:23<4:29:14,  8.88s/it]

AK_3522_2020 completed in 0:00:06.493982

 58%|█████▊    | 2474/4292 [5:35:28<4:01:07,  7.96s/it]

AK_7353_2020 completed in 0:00:05.802440

 58%|█████▊    | 2475/4292 [5:35:36<4:02:43,  8.01s/it]

AK_11824_2020 completed in 0:00:08.147520

 58%|█████▊    | 2476/4292 [5:35:46<4:14:51,  8.42s/it]

AK_19558_2020 completed in 0:00:09.365372

 58%|█████▊    | 2477/4292 [5:35:55<4:20:28,  8.61s/it]

AR_814_2020 completed in 0:00:09.053533

 58%|█████▊    | 2478/4292 [5:36:00<3:47:38,  7.53s/it]

AR_817_2020 completed in 0:00:04.999925

 58%|█████▊    | 2479/4292 [5:36:06<3:35:44,  7.14s/it]

AR_3093_2020 completed in 0:00:06.228990

 58%|█████▊    | 2480/4292 [5:36:15<3:48:46,  7.58s/it]

AR_5860_2020 completed in 0:00:08.585721

 58%|█████▊    | 2481/4292 [5:36:25<4:14:10,  8.42s/it]

AR_6342_2020 completed in 0:00:10.393006

 58%|█████▊    | 2482/4292 [5:36:31<3:52:54,  7.72s/it]

AR_13718_2020 completed in 0:00:06.085262

 58%|█████▊    | 2483/4292 [5:36:36<3:29:43,  6.96s/it]

AR_14063_2020 completed in 0:00:05.166559

 58%|█████▊    | 2484/4292 [5:36:42<3:13:56,  6.44s/it]

AR_17698_2020 completed in 0:00:05.221969

 58%|█████▊    | 2485/4292 [5:36:48<3:14:25,  6.46s/it]

AZ_176_2020 completed in 0:00:06.501364

 58%|█████▊    | 2486/4292 [5:36:56<3:29:50,  6.97s/it]

AZ_803_2020 completed in 0:00:08.174037

 58%|█████▊    | 2487/4292 [5:37:03<3:26:13,  6.85s/it]

AZ_12919_2020 completed in 0:00:06.577515

 58%|█████▊    | 2488/4292 [5:37:12<3:44:46,  7.48s/it]

AZ_16572_2020 completed in 0:00:08.924349

 58%|█████▊    | 2489/4292 [5:37:20<3:55:07,  7.82s/it]

AZ_19189_2020 completed in 0:00:08.637227

 58%|█████▊    | 2490/4292 [5:37:29<4:04:29,  8.14s/it]

AZ_19728_2020 completed in 0:00:08.876427

 58%|█████▊    | 2491/4292 [5:37:36<3:47:54,  7.59s/it]

AZ_21538_2020 completed in 0:00:06.312027

 58%|█████▊    | 2492/4292 [5:37:43<3:44:30,  7.48s/it]

AZ_24211_2020 completed in 0:00:07.227959

 58%|█████▊    | 2493/4292 [5:37:50<3:39:45,  7.33s/it]

CA_4390_2020 completed in 0:00:06.968660

 58%|█████▊    | 2494/4292 [5:37:56<3:29:23,  6.99s/it]

CA_9216_2020 completed in 0:00:06.188619

 58%|█████▊    | 2495/4292 [5:38:02<3:18:09,  6.62s/it]

CA_11208_2020 completed in 0:00:05.748682

 58%|█████▊    | 2496/4292 [5:38:08<3:16:14,  6.56s/it]

CA_12745_2020 completed in 0:00:06.414529

 58%|█████▊    | 2497/4292 [5:38:24<4:37:44,  9.28s/it]

CA_14328_2020 completed in 0:00:15.643202

 58%|█████▊    | 2498/4292 [5:38:31<4:19:44,  8.69s/it]

CA_14354_2020 completed in 0:00:07.294044

 58%|█████▊    | 2499/4292 [5:38:37<3:52:25,  7.78s/it]

CA_14534_2020 completed in 0:00:05.655214

 58%|█████▊    | 2500/4292 [5:38:43<3:40:12,  7.37s/it]

CA_16534_2020 completed in 0:00:06.427287

 58%|█████▊    | 2501/4292 [5:38:50<3:32:02,  7.10s/it]

CA_16609_2020 completed in 0:00:06.475048

 58%|█████▊    | 2502/4292 [5:38:56<3:23:54,  6.84s/it]

CA_16655_2020 completed in 0:00:06.207513

 58%|█████▊    | 2503/4292 [5:39:06<3:52:27,  7.80s/it]

CA_17609_2020 completed in 0:00:10.037953

 58%|█████▊    | 2504/4292 [5:39:11<3:28:10,  6.99s/it]

CA_17612_2020 completed in 0:00:05.094191

 58%|█████▊    | 2505/4292 [5:39:18<3:25:30,  6.90s/it]

CA_18260_2020 completed in 0:00:06.698798

 58%|█████▊    | 2506/4292 [5:39:23<3:10:30,  6.40s/it]

CA_19281_2020 completed in 0:00:05.231831

 58%|█████▊    | 2507/4292 [5:39:30<3:13:39,  6.51s/it]

CO_3989_2020 completed in 0:00:06.765321

 58%|█████▊    | 2508/4292 [5:39:35<3:04:57,  6.22s/it]

CO_6604_2020 completed in 0:00:05.545771

 58%|█████▊    | 2509/4292 [5:39:41<3:01:34,  6.11s/it]

CO_9336_2020 completed in 0:00:05.850456

 58%|█████▊    | 2510/4292 [5:39:48<3:11:52,  6.46s/it]

CO_12866_2020 completed in 0:00:07.277557

 59%|█████▊    | 2511/4292 [5:39:55<3:09:24,  6.38s/it]

CO_15257_2020 completed in 0:00:06.193899

 59%|█████▊    | 2512/4292 [5:40:03<3:29:36,  7.07s/it]

CO_15466_2020 completed in 0:00:08.661627

 59%|█████▊    | 2513/4292 [5:40:10<3:29:25,  7.06s/it]

CO_16603_2020 completed in 0:00:07.057371

 59%|█████▊    | 2514/4292 [5:40:17<3:25:25,  6.93s/it]

CO_19499_2020 completed in 0:00:06.624695

 59%|█████▊    | 2515/4292 [5:40:23<3:20:56,  6.78s/it]

CO_27058_2020 completed in 0:00:06.439740

 59%|█████▊    | 2516/4292 [5:40:28<3:02:43,  6.17s/it]

CO_56146_2020 completed in 0:00:04.745818

 59%|█████▊    | 2517/4292 [5:40:33<2:53:57,  5.88s/it]

CT_4176_2020 completed in 0:00:05.196350

 59%|█████▊    | 2518/4292 [5:40:39<2:52:39,  5.84s/it]

CT_7716_2020 completed in 0:00:05.739558

 59%|█████▊    | 2519/4292 [5:40:46<3:04:26,  6.24s/it]

CT_19497_2020 completed in 0:00:07.178644

 59%|█████▊    | 2520/4292 [5:40:52<2:56:18,  5.97s/it]

CT_20038_2020 completed in 0:00:05.330637

 59%|█████▊    | 2521/4292 [5:40:58<2:59:48,  6.09s/it]

DC_15270_2020 completed in 0:00:06.376310

 59%|█████▉    | 2522/4292 [5:41:04<2:55:10,  5.94s/it]

DE_5027_2020 completed in 0:00:05.578206

 59%|█████▉    | 2523/4292 [5:41:09<2:49:57,  5.76s/it]

DE_5070_2020 completed in 0:00:05.358626

 59%|█████▉    | 2524/4292 [5:41:15<2:53:52,  5.90s/it]

DE_5335_2020 completed in 0:00:06.216952

 59%|█████▉    | 2525/4292 [5:41:19<2:40:31,  5.45s/it]

DE_13519_2020 completed in 0:00:04.401139

 59%|█████▉    | 2526/4292 [5:41:26<2:48:35,  5.73s/it]

FL_6452_2020 completed in 0:00:06.373720

 59%|█████▉    | 2527/4292 [5:41:32<2:55:34,  5.97s/it]

FL_6455_2020 completed in 0:00:06.529351

 59%|█████▉    | 2528/4292 [5:41:38<2:48:01,  5.71s/it]

FL_6457_2020 completed in 0:00:05.121881

 59%|█████▉    | 2529/4292 [5:41:43<2:46:22,  5.66s/it]

FL_7801_2020 completed in 0:00:05.537882

 59%|█████▉    | 2530/4292 [5:41:50<2:56:41,  6.02s/it]

FL_9617_2020 completed in 0:00:06.843105

 59%|█████▉    | 2531/4292 [5:41:56<2:53:34,  5.91s/it]

FL_18454_2020 completed in 0:00:05.674063

 59%|█████▉    | 2532/4292 [5:42:02<3:00:18,  6.15s/it]

GA_3916_2020 completed in 0:00:06.688562

 59%|█████▉    | 2533/4292 [5:42:09<3:06:32,  6.36s/it]

GA_9601_2020 completed in 0:00:06.867237

 59%|█████▉    | 2534/4292 [5:42:14<2:52:06,  5.87s/it]

HI_8287_2020 completed in 0:00:04.731611

 59%|█████▉    | 2535/4292 [5:42:20<2:54:32,  5.96s/it]

HI_10071_2020 completed in 0:00:06.160727

 59%|█████▉    | 2536/4292 [5:42:27<2:59:58,  6.15s/it]

HI_11843_2020 completed in 0:00:06.590865

 59%|█████▉    | 2537/4292 [5:42:32<2:49:33,  5.80s/it]

HI_19547_2020 completed in 0:00:04.972352

 59%|█████▉    | 2538/4292 [5:42:38<2:57:26,  6.07s/it]

IA_9417_2020 completed in 0:00:06.705989

 59%|█████▉    | 2539/4292 [5:42:46<3:07:54,  6.43s/it]

IA_12341_2020 completed in 0:00:07.275289

 59%|█████▉    | 2540/4292 [5:42:52<3:09:42,  6.50s/it]

ID_9187_2020 completed in 0:00:06.647763

 59%|█████▉    | 2541/4292 [5:43:00<3:22:25,  6.94s/it]

ID_9191_2020 completed in 0:00:07.960483

 59%|█████▉    | 2542/4292 [5:43:06<3:12:23,  6.60s/it]

ID_10454_2020 completed in 0:00:05.800549

 59%|█████▉    | 2543/4292 [5:43:12<3:11:09,  6.56s/it]

ID_11273_2020 completed in 0:00:06.466981

 59%|█████▉    | 2544/4292 [5:43:18<3:06:31,  6.40s/it]

ID_14354_2020 completed in 0:00:06.037557

 59%|█████▉    | 2545/4292 [5:43:26<3:13:10,  6.63s/it]

ID_20169_2020 completed in 0:00:07.174957

 59%|█████▉    | 2546/4292 [5:43:32<3:11:56,  6.60s/it]

IL_4110_2020 completed in 0:00:06.504018

 59%|█████▉    | 2547/4292 [5:43:40<3:20:10,  6.88s/it]

IL_12341_2020 completed in 0:00:07.552726

 59%|█████▉    | 2548/4292 [5:43:45<3:09:07,  6.51s/it]

IL_13032_2020 completed in 0:00:05.627311

 59%|█████▉    | 2549/4292 [5:43:55<3:33:23,  7.35s/it]

IL_56697_2020 completed in 0:00:09.303161

 59%|█████▉    | 2550/4292 [5:44:00<3:20:07,  6.89s/it]

IN_9273_2020 completed in 0:00:05.836114

 59%|█████▉    | 2551/4292 [5:44:06<3:11:35,  6.60s/it]

IN_9324_2020 completed in 0:00:05.919707

 59%|█████▉    | 2552/4292 [5:44:14<3:17:56,  6.83s/it]

IN_13756_2020 completed in 0:00:07.344106

 59%|█████▉    | 2553/4292 [5:44:23<3:39:07,  7.56s/it]

IN_15470_2020 completed in 0:00:09.274436

 60%|█████▉    | 2554/4292 [5:44:28<3:20:20,  6.92s/it]

IN_17633_2020 completed in 0:00:05.411281

 60%|█████▉    | 2555/4292 [5:44:34<3:11:06,  6.60s/it]

KS_5860_2020 completed in 0:00:05.865221

 60%|█████▉    | 2556/4292 [5:44:41<3:10:16,  6.58s/it]

KS_9996_2020 completed in 0:00:06.518021

 60%|█████▉    | 2557/4292 [5:44:47<3:08:55,  6.53s/it]

KS_10000_2020 completed in 0:00:06.432893

 60%|█████▉    | 2558/4292 [5:44:54<3:14:10,  6.72s/it]

KS_10005_2020 completed in 0:00:07.149614

 60%|█████▉    | 2559/4292 [5:45:03<3:32:25,  7.35s/it]

KS_22500_2020 completed in 0:00:08.837780

 60%|█████▉    | 2560/4292 [5:45:09<3:16:59,  6.82s/it]

KY_9964_2020 completed in 0:00:05.585511

 60%|█████▉    | 2561/4292 [5:45:18<3:36:26,  7.50s/it]

KY_10171_2020 completed in 0:00:09.082919

 60%|█████▉    | 2562/4292 [5:45:24<3:23:13,  7.05s/it]

KY_11249_2020 completed in 0:00:05.988644

 60%|█████▉    | 2563/4292 [5:45:29<3:08:22,  6.54s/it]

KY_17564_2020 completed in 0:00:05.342649

 60%|█████▉    | 2564/4292 [5:45:36<3:09:50,  6.59s/it]

KY_19446_2020 completed in 0:00:06.718099

 60%|█████▉    | 2565/4292 [5:45:42<3:04:58,  6.43s/it]

KY_22053_2020 completed in 0:00:06.041345

 60%|█████▉    | 2566/4292 [5:45:47<2:53:49,  6.04s/it]

KY_49998_2020 completed in 0:00:05.144994

 60%|█████▉    | 2567/4292 [5:45:54<2:56:51,  6.15s/it]

LA_3265_2020 completed in 0:00:06.406041

 60%|█████▉    | 2568/4292 [5:46:04<3:34:40,  7.47s/it]

LA_11241_2020 completed in 0:00:10.549206

 60%|█████▉    | 2569/4292 [5:46:10<3:23:52,  7.10s/it]

LA_13478_2020 completed in 0:00:06.231351

 60%|█████▉    | 2570/4292 [5:46:17<3:17:52,  6.89s/it]

LA_17698_2020 completed in 0:00:06.415628

 60%|█████▉    | 2571/4292 [5:46:23<3:08:40,  6.58s/it]

MA_6374_2020 completed in 0:00:05.837808

 60%|█████▉    | 2572/4292 [5:46:27<2:45:46,  5.78s/it]

MA_8774_2020 completed in 0:00:03.926231

 60%|█████▉    | 2573/4292 [5:46:34<2:56:13,  6.15s/it]

MA_11804_2020 completed in 0:00:07.004963

 60%|█████▉    | 2574/4292 [5:46:40<2:56:28,  6.16s/it]

MA_13206_2020 completed in 0:00:06.190808

 60%|█████▉    | 2575/4292 [5:46:46<2:52:58,  6.04s/it]

MA_15748_2020 completed in 0:00:05.767322

 60%|██████    | 2576/4292 [5:46:50<2:42:01,  5.67s/it]

MA_54913_2020 completed in 0:00:04.779259

 60%|██████    | 2577/4292 [5:46:56<2:40:09,  5.60s/it]

MD_1167_2020 completed in 0:00:05.457207

 60%|██████    | 2578/4292 [5:47:02<2:43:22,  5.72s/it]

MD_5027_2020 completed in 0:00:05.987948

 60%|██████    | 2579/4292 [5:47:06<2:34:10,  5.40s/it]

MD_15263_2020 completed in 0:00:04.654863

 60%|██████    | 2580/4292 [5:47:12<2:38:49,  5.57s/it]

MD_15270_2020 completed in 0:00:05.953527

 60%|██████    | 2581/4292 [5:47:17<2:33:35,  5.39s/it]

MD_17637_2020 completed in 0:00:04.964167

 60%|██████    | 2582/4292 [5:47:23<2:33:02,  5.37s/it]

ME_1179_2020 completed in 0:00:05.331230

 60%|██████    | 2583/4292 [5:47:28<2:35:20,  5.45s/it]

ME_3266_2020 completed in 0:00:05.647900

 60%|██████    | 2584/4292 [5:47:35<2:43:49,  5.75s/it]

ME_5609_2020 completed in 0:00:06.456857

 60%|██████    | 2585/4292 [5:47:41<2:44:32,  5.78s/it]

MI_392_2020 completed in 0:00:05.849315

 60%|██████    | 2586/4292 [5:47:46<2:38:27,  5.57s/it]

MI_3828_2020 completed in 0:00:05.081833

 60%|██████    | 2587/4292 [5:47:51<2:38:05,  5.56s/it]

MI_4254_2020 completed in 0:00:05.538535

 60%|██████    | 2588/4292 [5:47:56<2:28:39,  5.23s/it]

MI_5109_2020 completed in 0:00:04.462487

 60%|██████    | 2589/4292 [5:48:02<2:37:12,  5.54s/it]

MI_9324_2020 completed in 0:00:06.245162

 60%|██████    | 2590/4292 [5:48:07<2:36:42,  5.52s/it]

MI_10704_2020 completed in 0:00:05.490049

 60%|██████    | 2591/4292 [5:48:13<2:33:08,  5.40s/it]

MI_19578_2020 completed in 0:00:05.114445

 60%|██████    | 2592/4292 [5:48:21<2:55:14,  6.18s/it]

MN_689_2020 completed in 0:00:08.010813

 60%|██████    | 2593/4292 [5:48:27<2:53:59,  6.14s/it]

MN_5574_2020 completed in 0:00:06.049311

 60%|██████    | 2594/4292 [5:48:32<2:48:01,  5.94s/it]

MN_10596_2020 completed in 0:00:05.453290

 60%|██████    | 2595/4292 [5:48:37<2:38:17,  5.60s/it]

MN_12647_2020 completed in 0:00:04.801075

 60%|██████    | 2596/4292 [5:48:42<2:36:00,  5.52s/it]

MN_13781_2020 completed in 0:00:05.333621

 61%|██████    | 2597/4292 [5:48:52<3:15:21,  6.92s/it]

MN_14232_2020 completed in 0:00:10.171046

 61%|██████    | 2598/4292 [5:48:58<3:00:00,  6.38s/it]

MN_16181_2020 completed in 0:00:05.116929

 61%|██████    | 2599/4292 [5:49:03<2:54:05,  6.17s/it]

MN_17267_2020 completed in 0:00:05.688298

 61%|██████    | 2600/4292 [5:49:09<2:47:45,  5.95s/it]

MN_20996_2020 completed in 0:00:05.432273

 61%|██████    | 2601/4292 [5:49:14<2:42:27,  5.76s/it]

MN_25177_2020 completed in 0:00:05.332839

 61%|██████    | 2602/4292 [5:49:19<2:36:42,  5.56s/it]

MO_4675_2020 completed in 0:00:05.094010

 61%|██████    | 2603/4292 [5:49:25<2:36:42,  5.57s/it]

MO_5860_2020 completed in 0:00:05.574727

 61%|██████    | 2604/4292 [5:49:31<2:40:04,  5.69s/it]

MO_9231_2020 completed in 0:00:05.974438

 61%|██████    | 2605/4292 [5:49:38<2:50:48,  6.07s/it]

MO_10000_2020 completed in 0:00:06.972561

 61%|██████    | 2606/4292 [5:49:44<2:51:41,  6.11s/it]

MO_12698_2020 completed in 0:00:06.192082

 61%|██████    | 2607/4292 [5:49:51<3:01:30,  6.46s/it]

MO_17833_2020 completed in 0:00:07.286344

 61%|██████    | 2608/4292 [5:49:58<3:02:18,  6.50s/it]

MO_19436_2020 completed in 0:00:06.569096

 61%|██████    | 2609/4292 [5:50:04<2:57:47,  6.34s/it]

MS_3841_2020 completed in 0:00:05.971988

 61%|██████    | 2610/4292 [5:50:11<3:02:52,  6.52s/it]

MS_12685_2020 completed in 0:00:06.954171

 61%|██████    | 2611/4292 [5:50:17<3:01:24,  6.47s/it]

MS_12686_2020 completed in 0:00:06.360398

 61%|██████    | 2612/4292 [5:50:23<2:54:18,  6.23s/it]

MS_17647_2020 completed in 0:00:05.638730

 61%|██████    | 2613/4292 [5:50:28<2:43:33,  5.84s/it]

MT_6395_2020 completed in 0:00:04.956578

 61%|██████    | 2614/4292 [5:50:33<2:38:43,  5.68s/it]

MT_12199_2020 completed in 0:00:05.279474

 61%|██████    | 2615/4292 [5:50:37<2:29:11,  5.34s/it]

MT_12692_2020 completed in 0:00:04.549915

 61%|██████    | 2616/4292 [5:50:44<2:40:34,  5.75s/it]

MT_12825_2020 completed in 0:00:06.705713

 61%|██████    | 2617/4292 [5:50:49<2:35:38,  5.58s/it]

MT_19603_2020 completed in 0:00:05.170100

 61%|██████    | 2618/4292 [5:50:56<2:48:19,  6.03s/it]

MT_20997_2020 completed in 0:00:07.100506

 61%|██████    | 2619/4292 [5:51:03<2:54:45,  6.27s/it]

NC_3046_2020 completed in 0:00:06.813153

 61%|██████    | 2620/4292 [5:51:10<2:55:59,  6.32s/it]

NC_5416_2020 completed in 0:00:06.426121

 61%|██████    | 2621/4292 [5:51:17<3:06:06,  6.68s/it]

NC_9837_2020 completed in 0:00:07.538759

 61%|██████    | 2622/4292 [5:51:23<2:59:39,  6.45s/it]

NC_16496_2020 completed in 0:00:05.917839

 61%|██████    | 2623/4292 [5:51:27<2:39:09,  5.72s/it]

NC_19876_2020 completed in 0:00:04.009748

 61%|██████    | 2624/4292 [5:51:32<2:32:13,  5.48s/it]

NC_24889_2020 completed in 0:00:04.901054

 61%|██████    | 2625/4292 [5:51:37<2:30:00,  5.40s/it]

ND_12090_2020 completed in 0:00:05.214569

 61%|██████    | 2626/4292 [5:51:41<2:15:18,  4.87s/it]

ND_12301_2020 completed in 0:00:03.644512

 61%|██████    | 2627/4292 [5:51:46<2:17:41,  4.96s/it]

ND_14232_2020 completed in 0:00:05.167724

 61%|██████    | 2628/4292 [5:51:51<2:20:32,  5.07s/it]

ND_19790_2020 completed in 0:00:05.314795

 61%|██████▏   | 2629/4292 [5:51:56<2:20:55,  5.08s/it]

ND_24949_2020 completed in 0:00:05.122200

 61%|██████▏   | 2630/4292 [5:52:02<2:27:37,  5.33s/it]

NE_4373_2020 completed in 0:00:05.900728

 61%|██████▏   | 2631/4292 [5:52:11<2:52:41,  6.24s/it]

NE_4911_2020 completed in 0:00:08.357677

 61%|██████▏   | 2632/4292 [5:52:14<2:30:38,  5.44s/it]

NE_6779_2020 completed in 0:00:03.593047

 61%|██████▏   | 2633/4292 [5:52:19<2:26:03,  5.28s/it]

NE_11018_2020 completed in 0:00:04.902275

 61%|██████▏   | 2634/4292 [5:52:25<2:26:37,  5.31s/it]

NE_11251_2020 completed in 0:00:05.355228

 61%|██████▏   | 2635/4292 [5:52:28<2:12:58,  4.81s/it]

NE_12539_2020 completed in 0:00:03.668483

 61%|██████▏   | 2636/4292 [5:52:35<2:27:47,  5.35s/it]

NE_13337_2020 completed in 0:00:06.612949

 61%|██████▏   | 2637/4292 [5:52:39<2:15:33,  4.91s/it]

NE_13664_2020 completed in 0:00:03.886292

 61%|██████▏   | 2638/4292 [5:52:42<2:03:45,  4.49s/it]

NE_14127_2020 completed in 0:00:03.496842

 61%|██████▏   | 2639/4292 [5:52:46<1:58:32,  4.30s/it]

NE_17642_2020 completed in 0:00:03.861782

 62%|██████▏   | 2640/4292 [5:52:52<2:08:22,  4.66s/it]

NE_27058_2020 completed in 0:00:05.500587

 62%|██████▏   | 2641/4292 [5:52:57<2:17:45,  5.01s/it]

NE_40606_2020 completed in 0:00:05.807593

 62%|██████▏   | 2642/4292 [5:53:03<2:25:43,  5.30s/it]

NH_13441_2020 completed in 0:00:05.980996

 62%|██████▏   | 2643/4292 [5:53:08<2:23:36,  5.23s/it]

NH_15472_2020 completed in 0:00:05.053206

 62%|██████▏   | 2644/4292 [5:53:13<2:20:36,  5.12s/it]

NJ_963_2020 completed in 0:00:04.870399

 62%|██████▏   | 2645/4292 [5:53:19<2:28:38,  5.42s/it]

NJ_9726_2020 completed in 0:00:06.104165

 62%|██████▏   | 2646/4292 [5:53:23<2:12:41,  4.84s/it]

NJ_15477_2020 completed in 0:00:03.482243

 62%|██████▏   | 2647/4292 [5:53:28<2:12:01,  4.82s/it]

NJ_16213_2020 completed in 0:00:04.764816

 62%|██████▏   | 2648/4292 [5:53:33<2:12:49,  4.85s/it]

NM_3287_2020 completed in 0:00:04.921331

 62%|██████▏   | 2649/4292 [5:53:37<2:07:59,  4.67s/it]

NM_5701_2020 completed in 0:00:04.268869

 62%|██████▏   | 2650/4292 [5:53:42<2:15:11,  4.94s/it]

NM_6204_2020 completed in 0:00:05.558761

 62%|██████▏   | 2651/4292 [5:53:47<2:13:09,  4.87s/it]

NM_11204_2020 completed in 0:00:04.700795

 62%|██████▏   | 2652/4292 [5:53:53<2:21:42,  5.18s/it]

NM_15473_2020 completed in 0:00:05.920582

 62%|██████▏   | 2653/4292 [5:53:57<2:15:36,  4.96s/it]

NM_17718_2020 completed in 0:00:04.450323

 62%|██████▏   | 2654/4292 [5:54:03<2:23:57,  5.27s/it]

NV_2008_2020 completed in 0:00:05.993247

 62%|██████▏   | 2655/4292 [5:54:08<2:17:20,  5.03s/it]

NV_13073_2020 completed in 0:00:04.473349

 62%|██████▏   | 2656/4292 [5:54:12<2:11:29,  4.82s/it]

NV_13407_2020 completed in 0:00:04.325086

 62%|██████▏   | 2657/4292 [5:54:17<2:13:13,  4.89s/it]

NV_17166_2020 completed in 0:00:05.043245

 62%|██████▏   | 2658/4292 [5:54:21<2:05:39,  4.61s/it]

NV_19840_2020 completed in 0:00:03.972391

 62%|██████▏   | 2659/4292 [5:54:26<2:02:56,  4.52s/it]

NY_3249_2020 completed in 0:00:04.288486

 62%|██████▏   | 2660/4292 [5:54:30<1:58:52,  4.37s/it]

NY_4226_2020 completed in 0:00:04.027995

 62%|██████▏   | 2661/4292 [5:54:34<1:57:18,  4.32s/it]

NY_11171_2020 completed in 0:00:04.186911

 62%|██████▏   | 2662/4292 [5:54:41<2:17:12,  5.05s/it]

NY_13511_2020 completed in 0:00:06.764380

 62%|██████▏   | 2663/4292 [5:54:48<2:35:55,  5.74s/it]

NY_13573_2020 completed in 0:00:07.359236

 62%|██████▏   | 2664/4292 [5:54:52<2:19:37,  5.15s/it]

NY_14154_2020 completed in 0:00:03.751387

 62%|██████▏   | 2665/4292 [5:54:55<2:06:44,  4.67s/it]

NY_14711_2020 completed in 0:00:03.572167

 62%|██████▏   | 2666/4292 [5:55:01<2:15:07,  4.99s/it]

NY_16183_2020 completed in 0:00:05.711262

 62%|██████▏   | 2667/4292 [5:55:07<2:19:51,  5.16s/it]

OH_3542_2020 completed in 0:00:05.577451

 62%|██████▏   | 2668/4292 [5:55:12<2:21:39,  5.23s/it]

OH_3755_2020 completed in 0:00:05.396235

 62%|██████▏   | 2669/4292 [5:55:18<2:29:22,  5.52s/it]

OH_4922_2020 completed in 0:00:06.194493

 62%|██████▏   | 2670/4292 [5:55:25<2:39:47,  5.91s/it]

OH_13998_2020 completed in 0:00:06.815830

 62%|██████▏   | 2671/4292 [5:55:31<2:43:43,  6.06s/it]

OH_14006_2020 completed in 0:00:06.409173

 62%|██████▏   | 2672/4292 [5:55:37<2:39:37,  5.91s/it]

OH_18997_2020 completed in 0:00:05.564146

 62%|██████▏   | 2673/4292 [5:55:44<2:45:44,  6.14s/it]

OK_5860_2020 completed in 0:00:06.678959

 62%|██████▏   | 2674/4292 [5:55:49<2:39:20,  5.91s/it]

OK_13734_2020 completed in 0:00:05.363053

 62%|██████▏   | 2675/4292 [5:55:53<2:25:03,  5.38s/it]

OK_14062_2020 completed in 0:00:04.153283

 62%|██████▏   | 2676/4292 [5:55:59<2:29:36,  5.55s/it]

OK_14063_2020 completed in 0:00:05.956860

 62%|██████▏   | 2677/4292 [5:56:04<2:20:33,  5.22s/it]

OK_15474_2020 completed in 0:00:04.444170

 62%|██████▏   | 2678/4292 [5:56:10<2:31:18,  5.62s/it]

OK_19785_2020 completed in 0:00:06.563620

 62%|██████▏   | 2679/4292 [5:56:15<2:29:07,  5.55s/it]

OR_6022_2020 completed in 0:00:05.364438

 62%|██████▏   | 2680/4292 [5:56:21<2:30:17,  5.59s/it]

OR_9191_2020 completed in 0:00:05.702534

 62%|██████▏   | 2681/4292 [5:56:28<2:40:43,  5.99s/it]

OR_14354_2020 completed in 0:00:06.899111

 62%|██████▏   | 2682/4292 [5:56:31<2:18:08,  5.15s/it]

OR_15248_2020 completed in 0:00:03.192076

 63%|██████▎   | 2683/4292 [5:56:35<2:06:26,  4.72s/it]

OR_18260_2020 completed in 0:00:03.704180

 63%|██████▎   | 2684/4292 [5:56:40<2:06:41,  4.73s/it]

OR_28541_2020 completed in 0:00:04.754331

 63%|██████▎   | 2685/4292 [5:56:45<2:12:17,  4.94s/it]

OR_40437_2020 completed in 0:00:05.433633

 63%|██████▎   | 2686/4292 [5:56:51<2:19:48,  5.22s/it]

PA_3597_2020 completed in 0:00:05.885251

 63%|██████▎   | 2687/4292 [5:57:00<2:46:08,  6.21s/it]

PA_5487_2020 completed in 0:00:08.514188

 63%|██████▎   | 2688/4292 [5:57:06<2:46:58,  6.25s/it]

PA_12390_2020 completed in 0:00:06.327018

 63%|██████▎   | 2689/4292 [5:57:14<3:04:21,  6.90s/it]

PA_14711_2020 completed in 0:00:08.425933

 63%|██████▎   | 2690/4292 [5:57:22<3:08:15,  7.05s/it]

PA_14715_2020 completed in 0:00:07.398740

 63%|██████▎   | 2691/4292 [5:57:27<2:56:30,  6.61s/it]

PA_14716_2020 completed in 0:00:05.596414

 63%|██████▎   | 2692/4292 [5:57:33<2:46:21,  6.24s/it]

PA_14940_2020 completed in 0:00:05.360019

 63%|██████▎   | 2693/4292 [5:57:36<2:22:49,  5.36s/it]

PA_15045_2020 completed in 0:00:03.306347

 63%|██████▎   | 2694/4292 [5:57:42<2:28:24,  5.57s/it]

PA_19390_2020 completed in 0:00:06.067848

 63%|██████▎   | 2695/4292 [5:57:46<2:17:05,  5.15s/it]

PA_20334_2020 completed in 0:00:04.167120

 63%|██████▎   | 2696/4292 [5:57:52<2:20:35,  5.29s/it]

PA_20387_2020 completed in 0:00:05.597594

 63%|██████▎   | 2697/4292 [5:57:56<2:09:00,  4.85s/it]

RI_1857_2020 completed in 0:00:03.843824

 63%|██████▎   | 2698/4292 [5:58:02<2:17:22,  5.17s/it]

RI_13214_2020 completed in 0:00:05.911637

 63%|██████▎   | 2699/4292 [5:58:07<2:16:19,  5.13s/it]

RI_14537_2020 completed in 0:00:05.048472

 63%|██████▎   | 2700/4292 [5:58:12<2:14:56,  5.09s/it]

SC_1613_2020 completed in 0:00:04.970409

 63%|██████▎   | 2701/4292 [5:58:17<2:19:41,  5.27s/it]

SC_3046_2020 completed in 0:00:05.687892

 63%|██████▎   | 2702/4292 [5:58:23<2:24:58,  5.47s/it]

SC_5416_2020 completed in 0:00:05.942745

 63%|██████▎   | 2703/4292 [5:58:28<2:23:12,  5.41s/it]

SC_14398_2020 completed in 0:00:05.258338

 63%|██████▎   | 2704/4292 [5:58:34<2:24:02,  5.44s/it]

SC_17539_2020 completed in 0:00:05.523568

 63%|██████▎   | 2705/4292 [5:58:40<2:27:14,  5.57s/it]

SC_17543_2020 completed in 0:00:05.852069

 63%|██████▎   | 2706/4292 [5:58:47<2:36:11,  5.91s/it]

SD_1769_2020 completed in 0:00:06.705199

 63%|██████▎   | 2707/4292 [5:58:51<2:26:51,  5.56s/it]

SD_14232_2020 completed in 0:00:04.739122

 63%|██████▎   | 2708/4292 [5:58:56<2:20:11,  5.31s/it]

SD_17267_2020 completed in 0:00:04.727838

 63%|██████▎   | 2709/4292 [5:59:03<2:32:04,  5.76s/it]

SD_19293_2020 completed in 0:00:06.823249

 63%|██████▎   | 2710/4292 [5:59:10<2:43:45,  6.21s/it]

SD_20401_2020 completed in 0:00:07.251983

 63%|██████▎   | 2711/4292 [5:59:17<2:45:57,  6.30s/it]

TN_10331_2020 completed in 0:00:06.501687

 63%|██████▎   | 2712/4292 [5:59:23<2:48:34,  6.40s/it]

TX_5701_2020 completed in 0:00:06.641886

 63%|██████▎   | 2713/4292 [5:59:29<2:44:13,  6.24s/it]

TX_16604_2020 completed in 0:00:05.861531

 63%|██████▎   | 2714/4292 [5:59:38<3:07:04,  7.11s/it]

TX_55937_2020 completed in 0:00:09.147445

 63%|██████▎   | 2715/4292 [5:59:45<3:01:43,  6.91s/it]

UT_2010_2020 completed in 0:00:06.449368

 63%|██████▎   | 2716/4292 [5:59:55<3:24:42,  7.79s/it]

UT_11135_2020 completed in 0:00:09.844771

 63%|██████▎   | 2717/4292 [6:00:01<3:17:03,  7.51s/it]

UT_12866_2020 completed in 0:00:06.837003

 63%|██████▎   | 2718/4292 [6:00:12<3:43:45,  8.53s/it]

UT_14354_2020 completed in 0:00:10.914483

 63%|██████▎   | 2719/4292 [6:00:19<3:28:45,  7.96s/it]

UT_15444_2020 completed in 0:00:06.634798

 63%|██████▎   | 2720/4292 [6:00:26<3:24:14,  7.80s/it]

UT_17845_2020 completed in 0:00:07.404292

 63%|██████▎   | 2721/4292 [6:00:34<3:26:12,  7.88s/it]

UT_17874_2020 completed in 0:00:08.062362

 63%|██████▎   | 2722/4292 [6:00:39<3:03:33,  7.02s/it]

UT_18206_2020 completed in 0:00:05.004399

 63%|██████▎   | 2723/4292 [6:00:47<3:05:01,  7.08s/it]

VA_84_2020 completed in 0:00:07.215048

 63%|██████▎   | 2724/4292 [6:00:53<2:58:30,  6.83s/it]

VA_733_2020 completed in 0:00:06.259896

 63%|██████▎   | 2725/4292 [6:01:01<3:05:56,  7.12s/it]

VA_10171_2020 completed in 0:00:07.791996

 64%|██████▎   | 2726/4292 [6:01:08<3:05:25,  7.10s/it]

VA_17066_2020 completed in 0:00:07.064049

 64%|██████▎   | 2727/4292 [6:01:16<3:17:18,  7.56s/it]

VA_19876_2020 completed in 0:00:08.636216

 64%|██████▎   | 2728/4292 [6:01:22<2:59:50,  6.90s/it]

VA_19882_2020 completed in 0:00:05.347624

 64%|██████▎   | 2729/4292 [6:01:27<2:43:47,  6.29s/it]

VA_40228_2020 completed in 0:00:04.858804

 64%|██████▎   | 2730/4292 [6:01:32<2:35:39,  5.98s/it]

VT_2548_2020 completed in 0:00:05.258978

 64%|██████▎   | 2731/4292 [6:01:38<2:36:56,  6.03s/it]

VT_7601_2020 completed in 0:00:06.154945

 64%|██████▎   | 2732/4292 [6:01:44<2:37:56,  6.07s/it]

VT_19791_2020 completed in 0:00:06.172031

 64%|██████▎   | 2733/4292 [6:01:49<2:24:34,  5.56s/it]

WA_3660_2020 completed in 0:00:04.372187

 64%|██████▎   | 2734/4292 [6:01:56<2:35:18,  5.98s/it]

WA_14354_2020 completed in 0:00:06.952810

 64%|██████▎   | 2735/4292 [6:02:02<2:35:42,  6.00s/it]

WA_15500_2020 completed in 0:00:06.045168

 64%|██████▎   | 2736/4292 [6:02:07<2:34:49,  5.97s/it]

WA_16868_2020 completed in 0:00:05.898275

 64%|██████▍   | 2737/4292 [6:02:13<2:28:39,  5.74s/it]

WA_17470_2020 completed in 0:00:05.188530

 64%|██████▍   | 2738/4292 [6:02:19<2:31:46,  5.86s/it]

WA_18429_2020 completed in 0:00:06.147203

 64%|██████▍   | 2739/4292 [6:02:25<2:33:23,  5.93s/it]

WA_20169_2020 completed in 0:00:06.079936

 64%|██████▍   | 2740/4292 [6:02:32<2:42:55,  6.30s/it]

WI_4715_2020 completed in 0:00:07.166612

 64%|██████▍   | 2741/4292 [6:02:36<2:26:01,  5.65s/it]

WI_5574_2020 completed in 0:00:04.132471

 64%|██████▍   | 2742/4292 [6:02:42<2:27:51,  5.72s/it]

WI_11479_2020 completed in 0:00:05.896959

 64%|██████▍   | 2743/4292 [6:02:46<2:13:37,  5.18s/it]

WI_13697_2020 completed in 0:00:03.897166

 64%|██████▍   | 2744/4292 [6:02:55<2:40:00,  6.20s/it]

WI_13780_2020 completed in 0:00:08.594676

 64%|██████▍   | 2745/4292 [6:02:59<2:29:47,  5.81s/it]

WI_13815_2020 completed in 0:00:04.893829

 64%|██████▍   | 2746/4292 [6:03:04<2:18:10,  5.36s/it]

WI_20847_2020 completed in 0:00:04.318270

 64%|██████▍   | 2747/4292 [6:03:10<2:23:24,  5.57s/it]

WI_20856_2020 completed in 0:00:06.051087

 64%|██████▍   | 2748/4292 [6:03:17<2:31:42,  5.90s/it]

WI_20860_2020 completed in 0:00:06.655379

 64%|██████▍   | 2749/4292 [6:03:21<2:20:44,  5.47s/it]

WV_733_2020 completed in 0:00:04.484885

 64%|██████▍   | 2750/4292 [6:03:28<2:31:41,  5.90s/it]

WV_12796_2020 completed in 0:00:06.904822

 64%|██████▍   | 2751/4292 [6:03:33<2:23:17,  5.58s/it]

WV_15263_2020 completed in 0:00:04.824369

 64%|██████▍   | 2752/4292 [6:03:39<2:30:08,  5.85s/it]

WV_20521_2020 completed in 0:00:06.478888

 64%|██████▍   | 2753/4292 [6:03:43<2:12:55,  5.18s/it]

WY_3461_2020 completed in 0:00:03.620093

 64%|██████▍   | 2754/4292 [6:03:58<3:29:00,  8.15s/it]

WY_7222_2020 completed in 0:00:15.085705

 64%|██████▍   | 2755/4292 [6:04:04<3:12:59,  7.53s/it]

WY_8566_2020 completed in 0:00:06.086075

 64%|██████▍   | 2756/4292 [6:04:12<3:14:52,  7.61s/it]

WY_11273_2020 completed in 0:00:07.791241

 64%|██████▍   | 2757/4292 [6:04:15<2:44:34,  6.43s/it]

WY_12199_2020 completed in 0:00:03.680274

 64%|██████▍   | 2758/4292 [6:04:26<3:13:49,  7.58s/it]

WY_14354_2020 completed in 0:00:10.258892

 64%|██████▍   | 2759/4292 [6:04:32<3:02:13,  7.13s/it]

WY_19156_2020 completed in 0:00:06.084053

 64%|██████▍   | 2760/4292 [6:04:36<2:38:01,  6.19s/it]

WY_27058_2020 completed in 0:00:03.987509

 64%|██████▍   | 2761/4292 [6:04:42<2:34:50,  6.07s/it]

NH_24590_2020 completed in 0:00:05.785193

 64%|██████▍   | 2762/4292 [6:04:53<3:12:19,  7.54s/it]

AK_219_2021 completed in 0:00:10.979768

 64%|██████▍   | 2763/4292 [6:05:01<3:21:56,  7.92s/it]

AK_3522_2021 completed in 0:00:08.815786

 64%|██████▍   | 2764/4292 [6:05:13<3:49:14,  9.00s/it]

AK_7353_2021 completed in 0:00:11.515113

 64%|██████▍   | 2765/4292 [6:05:21<3:45:45,  8.87s/it]

AK_11824_2021 completed in 0:00:08.563288

 64%|██████▍   | 2766/4292 [6:05:28<3:25:14,  8.07s/it]

AK_19558_2021 completed in 0:00:06.201129

 64%|██████▍   | 2767/4292 [6:05:35<3:21:41,  7.94s/it]

AR_814_2021 completed in 0:00:07.615241

 64%|██████▍   | 2768/4292 [6:05:45<3:33:31,  8.41s/it]

AR_817_2021 completed in 0:00:09.504378

 65%|██████▍   | 2769/4292 [6:05:51<3:18:47,  7.83s/it]

AR_3093_2021 completed in 0:00:06.488829

 65%|██████▍   | 2770/4292 [6:05:59<3:21:16,  7.93s/it]

AR_5860_2021 completed in 0:00:08.175298

 65%|██████▍   | 2771/4292 [6:06:05<3:02:12,  7.19s/it]

AR_6342_2021 completed in 0:00:05.437709

 65%|██████▍   | 2772/4292 [6:06:09<2:36:54,  6.19s/it]

AR_13718_2021 completed in 0:00:03.873365

 65%|██████▍   | 2773/4292 [6:06:16<2:42:24,  6.42s/it]

AR_14063_2021 completed in 0:00:06.931594

 65%|██████▍   | 2774/4292 [6:06:20<2:24:03,  5.69s/it]

AR_17698_2021 completed in 0:00:04.009241

 65%|██████▍   | 2775/4292 [6:06:23<2:07:22,  5.04s/it]

AZ_176_2021 completed in 0:00:03.507088

 65%|██████▍   | 2776/4292 [6:06:30<2:17:37,  5.45s/it]

AZ_803_2021 completed in 0:00:06.394712

 65%|██████▍   | 2777/4292 [6:06:37<2:34:14,  6.11s/it]

AZ_12919_2021 completed in 0:00:07.652003

 65%|██████▍   | 2778/4292 [6:06:44<2:40:45,  6.37s/it]

AZ_16572_2021 completed in 0:00:06.980849

 65%|██████▍   | 2779/4292 [6:06:52<2:53:29,  6.88s/it]

AZ_19189_2021 completed in 0:00:08.067597

 65%|██████▍   | 2780/4292 [6:07:02<3:16:15,  7.79s/it]

AZ_19728_2021 completed in 0:00:09.901067

 65%|██████▍   | 2781/4292 [6:07:09<3:11:09,  7.59s/it]

AZ_21538_2021 completed in 0:00:07.129487

 65%|██████▍   | 2782/4292 [6:07:15<2:56:16,  7.00s/it]

AZ_24211_2021 completed in 0:00:05.634601

 65%|██████▍   | 2783/4292 [6:07:23<3:04:05,  7.32s/it]

CA_4390_2021 completed in 0:00:08.056106

 65%|██████▍   | 2784/4292 [6:07:32<3:15:09,  7.76s/it]

CA_9216_2021 completed in 0:00:08.801325

 65%|██████▍   | 2785/4292 [6:07:36<2:46:17,  6.62s/it]

CA_11208_2021 completed in 0:00:03.950751

 65%|██████▍   | 2786/4292 [6:07:41<2:36:58,  6.25s/it]

CA_12745_2021 completed in 0:00:05.397454

 65%|██████▍   | 2787/4292 [6:07:55<3:34:59,  8.57s/it]

CA_14328_2021 completed in 0:00:13.972065

 65%|██████▍   | 2788/4292 [6:08:03<3:28:46,  8.33s/it]

CA_14354_2021 completed in 0:00:07.762315

 65%|██████▍   | 2789/4292 [6:08:08<3:00:16,  7.20s/it]

CA_14534_2021 completed in 0:00:04.554579

 65%|██████▌   | 2790/4292 [6:08:15<3:02:49,  7.30s/it]

CA_16534_2021 completed in 0:00:07.551071

 65%|██████▌   | 2791/4292 [6:08:20<2:43:35,  6.54s/it]

CA_16609_2021 completed in 0:00:04.754341

 65%|██████▌   | 2792/4292 [6:08:23<2:19:06,  5.56s/it]

CA_16655_2021 completed in 0:00:03.290178

 65%|██████▌   | 2793/4292 [6:08:31<2:33:51,  6.16s/it]

CA_17609_2021 completed in 0:00:07.543305

 65%|██████▌   | 2794/4292 [6:08:42<3:11:25,  7.67s/it]

CA_17612_2021 completed in 0:00:11.182706

 65%|██████▌   | 2795/4292 [6:08:50<3:16:44,  7.89s/it]

CA_18260_2021 completed in 0:00:08.389004

 65%|██████▌   | 2796/4292 [6:08:56<2:58:39,  7.17s/it]

CA_19281_2021 completed in 0:00:05.483093

 65%|██████▌   | 2797/4292 [6:09:02<2:55:21,  7.04s/it]

CO_3989_2021 completed in 0:00:06.735972

 65%|██████▌   | 2798/4292 [6:09:12<3:11:33,  7.69s/it]

CO_6604_2021 completed in 0:00:09.219451

 65%|██████▌   | 2799/4292 [6:09:18<3:00:30,  7.25s/it]

CO_9336_2021 completed in 0:00:06.230288

 65%|██████▌   | 2800/4292 [6:09:21<2:31:36,  6.10s/it]

CO_12866_2021 completed in 0:00:03.396013

 65%|██████▌   | 2801/4292 [6:09:26<2:22:43,  5.74s/it]

CO_15257_2021 completed in 0:00:04.916805

 65%|██████▌   | 2802/4292 [6:09:34<2:38:14,  6.37s/it]

CO_15466_2021 completed in 0:00:07.838210

 65%|██████▌   | 2803/4292 [6:09:40<2:33:14,  6.18s/it]

CO_16603_2021 completed in 0:00:05.715000

 65%|██████▌   | 2804/4292 [6:09:45<2:23:10,  5.77s/it]

CO_19499_2021 completed in 0:00:04.833801

 65%|██████▌   | 2805/4292 [6:09:51<2:27:17,  5.94s/it]

CO_27058_2021 completed in 0:00:06.339156

 65%|██████▌   | 2806/4292 [6:09:57<2:26:21,  5.91s/it]

CO_56146_2021 completed in 0:00:05.830183

 65%|██████▌   | 2807/4292 [6:10:02<2:21:15,  5.71s/it]

CT_4176_2021 completed in 0:00:05.235497

 65%|██████▌   | 2808/4292 [6:10:08<2:22:15,  5.75s/it]

CT_7716_2021 completed in 0:00:05.853437

 65%|██████▌   | 2809/4292 [6:10:15<2:35:08,  6.28s/it]

CT_19497_2021 completed in 0:00:07.500336

 65%|██████▌   | 2810/4292 [6:10:21<2:31:04,  6.12s/it]

CT_20038_2021 completed in 0:00:05.742422

 65%|██████▌   | 2811/4292 [6:10:27<2:30:17,  6.09s/it]

DC_15270_2021 completed in 0:00:06.023120

 66%|██████▌   | 2812/4292 [6:10:34<2:36:46,  6.36s/it]

DE_5027_2021 completed in 0:00:06.978965

 66%|██████▌   | 2813/4292 [6:10:42<2:45:55,  6.73s/it]

DE_5070_2021 completed in 0:00:07.605999

 66%|██████▌   | 2814/4292 [6:10:48<2:45:37,  6.72s/it]

DE_5335_2021 completed in 0:00:06.704156

 66%|██████▌   | 2815/4292 [6:10:55<2:41:55,  6.58s/it]

DE_13519_2021 completed in 0:00:06.237989

 66%|██████▌   | 2816/4292 [6:11:04<2:58:11,  7.24s/it]

FL_6452_2021 completed in 0:00:08.796215

 66%|██████▌   | 2817/4292 [6:11:13<3:15:56,  7.97s/it]

FL_6455_2021 completed in 0:00:09.661524

 66%|██████▌   | 2818/4292 [6:11:19<2:59:35,  7.31s/it]

FL_6457_2021 completed in 0:00:05.768742

 66%|██████▌   | 2819/4292 [6:11:25<2:51:44,  7.00s/it]

FL_7801_2021 completed in 0:00:06.255322

 66%|██████▌   | 2820/4292 [6:11:31<2:45:49,  6.76s/it]

FL_9617_2021 completed in 0:00:06.205640

 66%|██████▌   | 2821/4292 [6:11:38<2:41:06,  6.57s/it]

FL_18454_2021 completed in 0:00:06.133168

 66%|██████▌   | 2822/4292 [6:11:44<2:40:06,  6.54s/it]

GA_3916_2021 completed in 0:00:06.449023

 66%|██████▌   | 2823/4292 [6:11:52<2:47:14,  6.83s/it]

GA_9601_2021 completed in 0:00:07.515472

 66%|██████▌   | 2824/4292 [6:11:58<2:44:10,  6.71s/it]

HI_8287_2021 completed in 0:00:06.427723

 66%|██████▌   | 2825/4292 [6:12:04<2:41:53,  6.62s/it]

HI_10071_2021 completed in 0:00:06.408230

 66%|██████▌   | 2826/4292 [6:12:11<2:45:02,  6.75s/it]

HI_11843_2021 completed in 0:00:07.064701

 66%|██████▌   | 2827/4292 [6:12:19<2:53:39,  7.11s/it]

HI_19547_2021 completed in 0:00:07.946692

 66%|██████▌   | 2828/4292 [6:12:27<2:53:58,  7.13s/it]

IA_9417_2021 completed in 0:00:07.170814

 66%|██████▌   | 2829/4292 [6:12:34<2:53:52,  7.13s/it]

IA_12341_2021 completed in 0:00:07.130191

 66%|██████▌   | 2830/4292 [6:12:40<2:50:58,  7.02s/it]

ID_9187_2021 completed in 0:00:06.744843

 66%|██████▌   | 2831/4292 [6:12:50<3:08:45,  7.75s/it]

ID_9191_2021 completed in 0:00:09.467590

 66%|██████▌   | 2832/4292 [6:12:55<2:52:25,  7.09s/it]

ID_10454_2021 completed in 0:00:05.529728

 66%|██████▌   | 2833/4292 [6:13:02<2:49:07,  6.95s/it]

ID_11273_2021 completed in 0:00:06.648600

 66%|██████▌   | 2834/4292 [6:13:09<2:51:14,  7.05s/it]

ID_14354_2021 completed in 0:00:07.261693

 66%|██████▌   | 2835/4292 [6:13:17<2:54:32,  7.19s/it]

ID_20169_2021 completed in 0:00:07.510267

 66%|██████▌   | 2836/4292 [6:13:25<2:59:00,  7.38s/it]

IL_4110_2021 completed in 0:00:07.816404

 66%|██████▌   | 2837/4292 [6:13:31<2:51:05,  7.06s/it]

IL_12341_2021 completed in 0:00:06.305406

 66%|██████▌   | 2838/4292 [6:13:38<2:54:20,  7.19s/it]

IL_13032_2021 completed in 0:00:07.516541

 66%|██████▌   | 2839/4292 [6:13:50<3:25:14,  8.48s/it]

IL_56697_2021 completed in 0:00:11.464165

 66%|██████▌   | 2840/4292 [6:13:58<3:20:55,  8.30s/it]

IN_9273_2021 completed in 0:00:07.898658

 66%|██████▌   | 2841/4292 [6:14:05<3:10:58,  7.90s/it]

IN_9324_2021 completed in 0:00:06.948743

 66%|██████▌   | 2842/4292 [6:14:12<3:07:15,  7.75s/it]

IN_13756_2021 completed in 0:00:07.400559

 66%|██████▌   | 2843/4292 [6:14:22<3:21:45,  8.35s/it]

IN_15470_2021 completed in 0:00:09.768027

 66%|██████▋   | 2844/4292 [6:14:27<3:00:23,  7.48s/it]

IN_17633_2021 completed in 0:00:05.416658

 66%|██████▋   | 2845/4292 [6:14:34<2:54:39,  7.24s/it]

KS_5860_2021 completed in 0:00:06.699297

 66%|██████▋   | 2846/4292 [6:14:41<2:50:28,  7.07s/it]

KS_9996_2021 completed in 0:00:06.678246

 66%|██████▋   | 2847/4292 [6:14:49<3:00:01,  7.48s/it]

KS_10000_2021 completed in 0:00:08.412034

 66%|██████▋   | 2848/4292 [6:14:56<2:54:40,  7.26s/it]

KS_10005_2021 completed in 0:00:06.749936

 66%|██████▋   | 2849/4292 [6:15:08<3:26:33,  8.59s/it]

KS_22500_2021 completed in 0:00:11.692568

 66%|██████▋   | 2850/4292 [6:15:14<3:11:09,  7.95s/it]

KY_9964_2021 completed in 0:00:06.472297

 66%|██████▋   | 2851/4292 [6:15:24<3:26:21,  8.59s/it]

KY_10171_2021 completed in 0:00:10.081279

 66%|██████▋   | 2852/4292 [6:15:30<3:09:44,  7.91s/it]

KY_11249_2021 completed in 0:00:06.302996

 66%|██████▋   | 2853/4292 [6:15:36<2:55:29,  7.32s/it]

KY_17564_2021 completed in 0:00:05.943200

 66%|██████▋   | 2854/4292 [6:15:43<2:48:32,  7.03s/it]

KY_19446_2021 completed in 0:00:06.366368

 67%|██████▋   | 2855/4292 [6:15:49<2:42:46,  6.80s/it]

KY_22053_2021 completed in 0:00:06.244375

 67%|██████▋   | 2856/4292 [6:15:56<2:42:04,  6.77s/it]

KY_49998_2021 completed in 0:00:06.714625

 67%|██████▋   | 2857/4292 [6:16:03<2:45:08,  6.90s/it]

LA_3265_2021 completed in 0:00:07.213845

 67%|██████▋   | 2858/4292 [6:16:09<2:41:52,  6.77s/it]

LA_11241_2021 completed in 0:00:06.465286

 67%|██████▋   | 2859/4292 [6:16:23<3:29:43,  8.78s/it]

LA_13478_2021 completed in 0:00:13.464871

 67%|██████▋   | 2860/4292 [6:16:30<3:14:40,  8.16s/it]

LA_17698_2021 completed in 0:00:06.698309

 67%|██████▋   | 2861/4292 [6:16:36<2:58:53,  7.50s/it]

MA_6374_2021 completed in 0:00:05.968672

 67%|██████▋   | 2862/4292 [6:16:43<2:58:07,  7.47s/it]

MA_8774_2021 completed in 0:00:07.404542

 67%|██████▋   | 2863/4292 [6:16:52<3:07:21,  7.87s/it]

MA_11804_2021 completed in 0:00:08.782976

 67%|██████▋   | 2864/4292 [6:17:00<3:11:12,  8.03s/it]

MA_13206_2021 completed in 0:00:08.422153

 67%|██████▋   | 2865/4292 [6:17:07<3:05:38,  7.81s/it]

MA_15748_2021 completed in 0:00:07.268912

 67%|██████▋   | 2866/4292 [6:17:16<3:08:31,  7.93s/it]

MA_54913_2021 completed in 0:00:08.227291

 67%|██████▋   | 2867/4292 [6:17:22<2:59:45,  7.57s/it]

MD_1167_2021 completed in 0:00:06.720216

 67%|██████▋   | 2868/4292 [6:17:30<2:58:49,  7.54s/it]

MD_5027_2021 completed in 0:00:07.454797

 67%|██████▋   | 2869/4292 [6:17:35<2:44:17,  6.93s/it]

MD_15263_2021 completed in 0:00:05.507547

 67%|██████▋   | 2870/4292 [6:17:42<2:38:35,  6.69s/it]

MD_15270_2021 completed in 0:00:06.140598

 67%|██████▋   | 2871/4292 [6:17:47<2:33:20,  6.47s/it]

MD_17637_2021 completed in 0:00:05.968471

 67%|██████▋   | 2872/4292 [6:17:54<2:35:37,  6.58s/it]

ME_1179_2021 completed in 0:00:06.811097

 67%|██████▋   | 2873/4292 [6:18:01<2:35:44,  6.59s/it]

ME_3266_2021 completed in 0:00:06.605705

 67%|██████▋   | 2874/4292 [6:18:08<2:41:30,  6.83s/it]

ME_5609_2021 completed in 0:00:07.408166

 67%|██████▋   | 2875/4292 [6:18:14<2:32:04,  6.44s/it]

MI_392_2021 completed in 0:00:05.518540

 67%|██████▋   | 2876/4292 [6:18:21<2:34:57,  6.57s/it]

MI_3828_2021 completed in 0:00:06.855692

 67%|██████▋   | 2877/4292 [6:18:27<2:31:28,  6.42s/it]

MI_4254_2021 completed in 0:00:06.087193

 67%|██████▋   | 2878/4292 [6:18:33<2:32:39,  6.48s/it]

MI_5109_2021 completed in 0:00:06.606472

 67%|██████▋   | 2879/4292 [6:18:38<2:20:39,  5.97s/it]

MI_9324_2021 completed in 0:00:04.792113

 67%|██████▋   | 2880/4292 [6:18:45<2:26:59,  6.25s/it]

MI_10704_2021 completed in 0:00:06.880554

 67%|██████▋   | 2881/4292 [6:18:50<2:20:19,  5.97s/it]

MI_19578_2021 completed in 0:00:05.312878

 67%|██████▋   | 2882/4292 [6:18:57<2:27:06,  6.26s/it]

MN_689_2021 completed in 0:00:06.936674

 67%|██████▋   | 2883/4292 [6:19:04<2:30:31,  6.41s/it]

MN_5574_2021 completed in 0:00:06.758102

 67%|██████▋   | 2884/4292 [6:19:10<2:24:20,  6.15s/it]

MN_10596_2021 completed in 0:00:05.547607

 67%|██████▋   | 2885/4292 [6:19:17<2:31:06,  6.44s/it]

MN_12647_2021 completed in 0:00:07.126030

 67%|██████▋   | 2886/4292 [6:19:25<2:42:46,  6.95s/it]

MN_13781_2021 completed in 0:00:08.117879

 67%|██████▋   | 2887/4292 [6:19:34<2:56:31,  7.54s/it]

MN_14232_2021 completed in 0:00:08.918835

 67%|██████▋   | 2888/4292 [6:19:42<2:58:23,  7.62s/it]

MN_16181_2021 completed in 0:00:07.821509

 67%|██████▋   | 2889/4292 [6:19:49<2:54:01,  7.44s/it]

MN_17267_2021 completed in 0:00:07.018853

 67%|██████▋   | 2890/4292 [6:19:57<2:59:11,  7.67s/it]

MN_20996_2021 completed in 0:00:08.194648

 67%|██████▋   | 2891/4292 [6:20:03<2:46:50,  7.15s/it]

MN_25177_2021 completed in 0:00:05.923763

 67%|██████▋   | 2892/4292 [6:20:10<2:43:57,  7.03s/it]

MO_4675_2021 completed in 0:00:06.748954

 67%|██████▋   | 2893/4292 [6:20:16<2:36:28,  6.71s/it]

MO_5860_2021 completed in 0:00:05.972710

 67%|██████▋   | 2894/4292 [6:20:25<2:58:29,  7.66s/it]

MO_9231_2021 completed in 0:00:09.875794

 67%|██████▋   | 2895/4292 [6:20:32<2:50:04,  7.30s/it]

MO_10000_2021 completed in 0:00:06.471762

 67%|██████▋   | 2896/4292 [6:20:38<2:42:23,  6.98s/it]

MO_12698_2021 completed in 0:00:06.221977

 67%|██████▋   | 2897/4292 [6:20:44<2:36:05,  6.71s/it]

MO_17833_2021 completed in 0:00:06.090857

 68%|██████▊   | 2898/4292 [6:20:52<2:42:05,  6.98s/it]

MO_19436_2021 completed in 0:00:07.590582

 68%|██████▊   | 2899/4292 [6:21:03<3:14:48,  8.39s/it]

MS_3841_2021 completed in 0:00:11.688519

 68%|██████▊   | 2900/4292 [6:21:11<3:07:14,  8.07s/it]

MS_12685_2021 completed in 0:00:07.319613

 68%|██████▊   | 2901/4292 [6:21:17<2:52:46,  7.45s/it]

MS_12686_2021 completed in 0:00:06.007001

 68%|██████▊   | 2902/4292 [6:21:26<3:05:45,  8.02s/it]

MS_17647_2021 completed in 0:00:09.336493

 68%|██████▊   | 2903/4292 [6:21:33<2:59:04,  7.74s/it]

MT_6395_2021 completed in 0:00:07.074992

 68%|██████▊   | 2904/4292 [6:21:40<2:49:27,  7.33s/it]

MT_12199_2021 completed in 0:00:06.367711

 68%|██████▊   | 2905/4292 [6:21:46<2:40:19,  6.94s/it]

MT_12692_2021 completed in 0:00:06.018262

 68%|██████▊   | 2906/4292 [6:21:55<2:58:34,  7.73s/it]

MT_12825_2021 completed in 0:00:09.585005

 68%|██████▊   | 2907/4292 [6:22:01<2:45:02,  7.15s/it]

MT_19603_2021 completed in 0:00:05.793030

 68%|██████▊   | 2908/4292 [6:22:09<2:49:10,  7.33s/it]

MT_20997_2021 completed in 0:00:07.762777

 68%|██████▊   | 2909/4292 [6:22:19<3:12:07,  8.34s/it]

NC_3046_2021 completed in 0:00:10.670316

 68%|██████▊   | 2910/4292 [6:22:25<2:55:08,  7.60s/it]

NC_5416_2021 completed in 0:00:05.897827

 68%|██████▊   | 2911/4292 [6:22:30<2:36:44,  6.81s/it]

NC_9837_2021 completed in 0:00:04.956177

 68%|██████▊   | 2912/4292 [6:22:40<2:59:49,  7.82s/it]

NC_16496_2021 completed in 0:00:10.170726

 68%|██████▊   | 2913/4292 [6:22:46<2:41:12,  7.01s/it]

NC_19876_2021 completed in 0:00:05.135345

 68%|██████▊   | 2914/4292 [6:22:53<2:45:15,  7.20s/it]

NC_24889_2021 completed in 0:00:07.619274

 68%|██████▊   | 2915/4292 [6:23:01<2:49:04,  7.37s/it]

ND_12090_2021 completed in 0:00:07.760381

 68%|██████▊   | 2916/4292 [6:23:10<3:02:46,  7.97s/it]

ND_12301_2021 completed in 0:00:09.376646

 68%|██████▊   | 2917/4292 [6:23:16<2:49:54,  7.41s/it]

ND_14232_2021 completed in 0:00:06.116035

 68%|██████▊   | 2918/4292 [6:23:24<2:48:55,  7.38s/it]

ND_19790_2021 completed in 0:00:07.283925

 68%|██████▊   | 2919/4292 [6:23:30<2:44:13,  7.18s/it]

ND_24949_2021 completed in 0:00:06.707860

 68%|██████▊   | 2920/4292 [6:23:36<2:29:36,  6.54s/it]

NE_4373_2021 completed in 0:00:05.063931

 68%|██████▊   | 2921/4292 [6:23:40<2:17:40,  6.02s/it]

NE_4911_2021 completed in 0:00:04.814892

 68%|██████▊   | 2922/4292 [6:23:52<2:54:28,  7.64s/it]

NE_6779_2021 completed in 0:00:11.411068

 68%|██████▊   | 2923/4292 [6:23:59<2:52:45,  7.57s/it]

NE_11018_2021 completed in 0:00:07.408199

 68%|██████▊   | 2924/4292 [6:24:05<2:37:48,  6.92s/it]

NE_11251_2021 completed in 0:00:05.403912

 68%|██████▊   | 2925/4292 [6:24:12<2:38:02,  6.94s/it]

NE_12539_2021 completed in 0:00:06.970853

 68%|██████▊   | 2926/4292 [6:24:17<2:26:25,  6.43s/it]

NE_13337_2021 completed in 0:00:05.251298

 68%|██████▊   | 2927/4292 [6:24:26<2:48:06,  7.39s/it]

NE_13664_2021 completed in 0:00:09.623553

 68%|██████▊   | 2928/4292 [6:24:33<2:45:42,  7.29s/it]

NE_14127_2021 completed in 0:00:07.054977

 68%|██████▊   | 2929/4292 [6:24:39<2:34:02,  6.78s/it]

NE_17642_2021 completed in 0:00:05.593849

 68%|██████▊   | 2930/4292 [6:24:45<2:31:00,  6.65s/it]

NE_27058_2021 completed in 0:00:06.352263

 68%|██████▊   | 2931/4292 [6:24:52<2:30:53,  6.65s/it]

NE_40606_2021 completed in 0:00:06.650692

 68%|██████▊   | 2932/4292 [6:24:58<2:26:15,  6.45s/it]

NH_13441_2021 completed in 0:00:05.985976

 68%|██████▊   | 2933/4292 [6:25:04<2:25:35,  6.43s/it]

NH_15472_2021 completed in 0:00:06.368079

 68%|██████▊   | 2934/4292 [6:25:13<2:37:26,  6.96s/it]

NH_24590_2021 completed in 0:00:08.189431

 68%|██████▊   | 2935/4292 [6:25:19<2:31:12,  6.69s/it]

NJ_963_2021 completed in 0:00:06.051775

 68%|██████▊   | 2936/4292 [6:25:24<2:21:14,  6.25s/it]

NJ_9726_2021 completed in 0:00:05.231727

 68%|██████▊   | 2937/4292 [6:25:30<2:19:45,  6.19s/it]

NJ_15477_2021 completed in 0:00:06.043993

 68%|██████▊   | 2938/4292 [6:25:36<2:15:53,  6.02s/it]

NJ_16213_2021 completed in 0:00:05.633653

 68%|██████▊   | 2939/4292 [6:25:40<2:07:42,  5.66s/it]

NM_3287_2021 completed in 0:00:04.825385

 68%|██████▊   | 2940/4292 [6:25:46<2:07:26,  5.66s/it]

NM_5701_2021 completed in 0:00:05.636921

 69%|██████▊   | 2941/4292 [6:25:51<2:01:34,  5.40s/it]

NM_6204_2021 completed in 0:00:04.799165

 69%|██████▊   | 2942/4292 [6:25:59<2:17:26,  6.11s/it]

NM_11204_2021 completed in 0:00:07.762875

 69%|██████▊   | 2943/4292 [6:26:04<2:13:38,  5.94s/it]

NM_15473_2021 completed in 0:00:05.558792

 69%|██████▊   | 2944/4292 [6:26:14<2:38:25,  7.05s/it]

NM_17718_2021 completed in 0:00:09.636368

 69%|██████▊   | 2945/4292 [6:26:19<2:26:38,  6.53s/it]

NV_2008_2021 completed in 0:00:05.317180

 69%|██████▊   | 2946/4292 [6:26:28<2:43:55,  7.31s/it]

NV_13073_2021 completed in 0:00:09.110034

 69%|██████▊   | 2947/4292 [6:26:36<2:47:22,  7.47s/it]

NV_13407_2021 completed in 0:00:07.837306

 69%|██████▊   | 2948/4292 [6:26:42<2:37:09,  7.02s/it]

NV_17166_2021 completed in 0:00:05.964912

 69%|██████▊   | 2949/4292 [6:26:48<2:31:47,  6.78s/it]

NV_19840_2021 completed in 0:00:06.231895

 69%|██████▊   | 2950/4292 [6:26:55<2:28:34,  6.64s/it]

NY_3249_2021 completed in 0:00:06.317993

 69%|██████▉   | 2951/4292 [6:27:02<2:30:39,  6.74s/it]

NY_4226_2021 completed in 0:00:06.968786

 69%|██████▉   | 2952/4292 [6:27:08<2:26:27,  6.56s/it]

NY_11171_2021 completed in 0:00:06.130408

 69%|██████▉   | 2953/4292 [6:27:19<2:55:19,  7.86s/it]

NY_13511_2021 completed in 0:00:10.879048

 69%|██████▉   | 2954/4292 [6:27:27<2:58:37,  8.01s/it]

NY_13573_2021 completed in 0:00:08.367851

 69%|██████▉   | 2955/4292 [6:27:33<2:48:18,  7.55s/it]

NY_14154_2021 completed in 0:00:06.485922

 69%|██████▉   | 2956/4292 [6:27:39<2:37:13,  7.06s/it]

NY_14711_2021 completed in 0:00:05.910764

 69%|██████▉   | 2957/4292 [6:27:47<2:37:54,  7.10s/it]

NY_16183_2021 completed in 0:00:07.181309

 69%|██████▉   | 2958/4292 [6:27:51<2:22:45,  6.42s/it]

OH_3542_2021 completed in 0:00:04.841328

 69%|██████▉   | 2959/4292 [6:27:57<2:17:55,  6.21s/it]

OH_3755_2021 completed in 0:00:05.710578

 69%|██████▉   | 2960/4292 [6:28:02<2:11:36,  5.93s/it]

OH_4922_2021 completed in 0:00:05.269547

 69%|██████▉   | 2961/4292 [6:28:08<2:12:20,  5.97s/it]

OH_13998_2021 completed in 0:00:06.052837

 69%|██████▉   | 2962/4292 [6:28:16<2:23:02,  6.45s/it]

OH_14006_2021 completed in 0:00:07.584837

 69%|██████▉   | 2963/4292 [6:28:22<2:21:58,  6.41s/it]

OH_18997_2021 completed in 0:00:06.307761

 69%|██████▉   | 2964/4292 [6:28:28<2:17:08,  6.20s/it]

OK_5860_2021 completed in 0:00:05.694534

 69%|██████▉   | 2965/4292 [6:28:33<2:08:52,  5.83s/it]

OK_13734_2021 completed in 0:00:04.963824

 69%|██████▉   | 2966/4292 [6:28:38<2:05:10,  5.66s/it]

OK_14062_2021 completed in 0:00:05.280322

 69%|██████▉   | 2967/4292 [6:28:44<2:07:49,  5.79s/it]

OK_14063_2021 completed in 0:00:06.077154

 69%|██████▉   | 2968/4292 [6:28:51<2:10:24,  5.91s/it]

OK_15474_2021 completed in 0:00:06.191198

 69%|██████▉   | 2969/4292 [6:28:56<2:06:39,  5.74s/it]

OK_19785_2021 completed in 0:00:05.356787

 69%|██████▉   | 2970/4292 [6:29:01<2:02:14,  5.55s/it]

OR_6022_2021 completed in 0:00:05.090387

 69%|██████▉   | 2971/4292 [6:29:06<1:58:31,  5.38s/it]

OR_9191_2021 completed in 0:00:04.999480

 69%|██████▉   | 2972/4292 [6:29:13<2:07:55,  5.81s/it]

OR_14354_2021 completed in 0:00:06.819968

 69%|██████▉   | 2973/4292 [6:29:19<2:09:50,  5.91s/it]

OR_15248_2021 completed in 0:00:06.119101

 69%|██████▉   | 2974/4292 [6:29:31<2:51:27,  7.81s/it]

OR_18260_2021 completed in 0:00:12.236569

 69%|██████▉   | 2975/4292 [6:29:37<2:36:42,  7.14s/it]

OR_28541_2021 completed in 0:00:05.584195

 69%|██████▉   | 2976/4292 [6:29:41<2:18:29,  6.31s/it]

OR_40437_2021 completed in 0:00:04.387326

 69%|██████▉   | 2977/4292 [6:29:46<2:11:44,  6.01s/it]

PA_3597_2021 completed in 0:00:05.302173

 69%|██████▉   | 2978/4292 [6:29:53<2:14:37,  6.15s/it]

PA_5487_2021 completed in 0:00:06.456019

 69%|██████▉   | 2979/4292 [6:30:01<2:28:38,  6.79s/it]

PA_12390_2021 completed in 0:00:08.296269

 69%|██████▉   | 2980/4292 [6:30:11<2:45:10,  7.55s/it]

PA_14711_2021 completed in 0:00:09.329070

 69%|██████▉   | 2981/4292 [6:30:19<2:48:06,  7.69s/it]

PA_14715_2021 completed in 0:00:08.015219

 69%|██████▉   | 2982/4292 [6:30:24<2:35:13,  7.11s/it]

PA_14716_2021 completed in 0:00:05.740129

 70%|██████▉   | 2983/4292 [6:30:30<2:23:42,  6.59s/it]

PA_14940_2021 completed in 0:00:05.367623

 70%|██████▉   | 2984/4292 [6:30:35<2:14:05,  6.15s/it]

PA_15045_2021 completed in 0:00:05.131672

 70%|██████▉   | 2985/4292 [6:30:39<2:00:15,  5.52s/it]

PA_19390_2021 completed in 0:00:04.048267

 70%|██████▉   | 2986/4292 [6:30:45<2:01:37,  5.59s/it]

PA_20334_2021 completed in 0:00:05.744823

 70%|██████▉   | 2987/4292 [6:30:51<2:09:24,  5.95s/it]

PA_20387_2021 completed in 0:00:06.793434

 70%|██████▉   | 2988/4292 [6:30:55<1:54:30,  5.27s/it]

RI_1857_2021 completed in 0:00:03.678607

 70%|██████▉   | 2989/4292 [6:30:58<1:41:39,  4.68s/it]

RI_13214_2021 completed in 0:00:03.309326

 70%|██████▉   | 2990/4292 [6:31:05<1:51:06,  5.12s/it]

RI_14537_2021 completed in 0:00:06.143223

 70%|██████▉   | 2991/4292 [6:31:10<1:52:47,  5.20s/it]

SC_1613_2021 completed in 0:00:05.391330

 70%|██████▉   | 2992/4292 [6:31:18<2:13:58,  6.18s/it]

SC_3046_2021 completed in 0:00:08.473725

 70%|██████▉   | 2993/4292 [6:31:24<2:08:33,  5.94s/it]

SC_5416_2021 completed in 0:00:05.364013

 70%|██████▉   | 2994/4292 [6:31:31<2:18:25,  6.40s/it]

SC_14398_2021 completed in 0:00:07.467268

 70%|██████▉   | 2995/4292 [6:31:40<2:36:39,  7.25s/it]

SC_17539_2021 completed in 0:00:09.225400

 70%|██████▉   | 2996/4292 [6:31:49<2:46:41,  7.72s/it]

SC_17543_2021 completed in 0:00:08.812864

 70%|██████▉   | 2997/4292 [6:31:56<2:39:45,  7.40s/it]

SD_1769_2021 completed in 0:00:06.666901

 70%|██████▉   | 2998/4292 [6:32:02<2:32:41,  7.08s/it]

SD_14232_2021 completed in 0:00:06.327521

 70%|██████▉   | 2999/4292 [6:32:11<2:45:52,  7.70s/it]

SD_17267_2021 completed in 0:00:09.135543

 70%|██████▉   | 3000/4292 [6:32:19<2:46:27,  7.73s/it]

SD_19293_2021 completed in 0:00:07.805607

 70%|██████▉   | 3001/4292 [6:32:29<2:57:58,  8.27s/it]

SD_20401_2021 completed in 0:00:09.534970

 70%|██████▉   | 3002/4292 [6:32:36<2:51:12,  7.96s/it]

TN_10331_2021 completed in 0:00:07.243119

 70%|██████▉   | 3003/4292 [6:32:43<2:44:40,  7.67s/it]

TX_5701_2021 completed in 0:00:06.965138

 70%|██████▉   | 3004/4292 [6:32:51<2:48:13,  7.84s/it]

TX_16604_2021 completed in 0:00:08.233501

 70%|███████   | 3005/4292 [6:33:03<3:14:13,  9.05s/it]

TX_55937_2021 completed in 0:00:11.895964

 70%|███████   | 3006/4292 [6:33:10<3:03:09,  8.55s/it]

UT_2010_2021 completed in 0:00:07.356434

 70%|███████   | 3007/4292 [6:33:17<2:53:17,  8.09s/it]

UT_11135_2021 completed in 0:00:07.030966

 70%|███████   | 3008/4292 [6:33:25<2:47:09,  7.81s/it]

UT_12866_2021 completed in 0:00:07.156470

 70%|███████   | 3009/4292 [6:33:34<2:54:31,  8.16s/it]

UT_14354_2021 completed in 0:00:08.976771

 70%|███████   | 3010/4292 [6:33:40<2:44:56,  7.72s/it]

UT_15444_2021 completed in 0:00:06.687483

 70%|███████   | 3011/4292 [6:33:53<3:19:11,  9.33s/it]

UT_17845_2021 completed in 0:00:13.085298

 70%|███████   | 3012/4292 [6:34:00<3:00:38,  8.47s/it]

UT_17874_2021 completed in 0:00:06.455700

 70%|███████   | 3013/4292 [6:34:07<2:50:33,  8.00s/it]

UT_18206_2021 completed in 0:00:06.911898

 70%|███████   | 3014/4292 [6:34:15<2:53:11,  8.13s/it]

VA_84_2021 completed in 0:00:08.433737

 70%|███████   | 3015/4292 [6:34:28<3:21:46,  9.48s/it]

VA_733_2021 completed in 0:00:12.626856

 70%|███████   | 3016/4292 [6:34:36<3:10:19,  8.95s/it]

VA_10171_2021 completed in 0:00:07.710948

 70%|███████   | 3017/4292 [6:34:45<3:10:23,  8.96s/it]

VA_17066_2021 completed in 0:00:08.982022

 70%|███████   | 3018/4292 [6:34:53<3:08:40,  8.89s/it]

VA_19876_2021 completed in 0:00:08.713008

 70%|███████   | 3019/4292 [6:35:01<2:59:55,  8.48s/it]

VA_19882_2021 completed in 0:00:07.533477

 70%|███████   | 3020/4292 [6:35:09<2:55:46,  8.29s/it]

VA_40228_2021 completed in 0:00:07.848404

 70%|███████   | 3021/4292 [6:35:17<2:56:43,  8.34s/it]

VT_2548_2021 completed in 0:00:08.460747

 70%|███████   | 3022/4292 [6:35:26<3:00:12,  8.51s/it]

VT_7601_2021 completed in 0:00:08.908422

 70%|███████   | 3023/4292 [6:35:34<2:56:37,  8.35s/it]

VT_19791_2021 completed in 0:00:07.966135

 70%|███████   | 3024/4292 [6:35:43<3:00:09,  8.53s/it]

WA_3660_2021 completed in 0:00:08.930736

 70%|███████   | 3025/4292 [6:35:54<3:17:39,  9.36s/it]

WA_14354_2021 completed in 0:00:11.308769

 71%|███████   | 3026/4292 [6:36:07<3:38:23, 10.35s/it]

WA_15500_2021 completed in 0:00:12.659977

 71%|███████   | 3027/4292 [6:36:15<3:21:45,  9.57s/it]

WA_16868_2021 completed in 0:00:07.746679

 71%|███████   | 3028/4292 [6:36:27<3:42:29, 10.56s/it]

WA_17470_2021 completed in 0:00:12.868962

 71%|███████   | 3029/4292 [6:36:38<3:39:46, 10.44s/it]

WA_18429_2021 completed in 0:00:10.153702

 71%|███████   | 3030/4292 [6:36:48<3:36:39, 10.30s/it]

WA_20169_2021 completed in 0:00:09.973075

 71%|███████   | 3031/4292 [6:36:54<3:14:05,  9.24s/it]

WI_4715_2021 completed in 0:00:06.748085

 71%|███████   | 3032/4292 [6:37:01<2:55:26,  8.35s/it]

WI_5574_2021 completed in 0:00:06.297738

 71%|███████   | 3033/4292 [6:37:12<3:12:16,  9.16s/it]

WI_11479_2021 completed in 0:00:11.050964

 71%|███████   | 3034/4292 [6:37:20<3:05:43,  8.86s/it]

WI_13697_2021 completed in 0:00:08.144915

 71%|███████   | 3035/4292 [6:37:29<3:08:02,  8.98s/it]

WI_13780_2021 completed in 0:00:09.248963

 71%|███████   | 3036/4292 [6:37:36<2:57:05,  8.46s/it]

WI_13815_2021 completed in 0:00:07.255923

 71%|███████   | 3037/4292 [6:37:48<3:14:51,  9.32s/it]

WI_20847_2021 completed in 0:00:11.310865

 71%|███████   | 3038/4292 [6:37:57<3:13:54,  9.28s/it]

WI_20856_2021 completed in 0:00:09.189521

 71%|███████   | 3039/4292 [6:38:11<3:46:06, 10.83s/it]

WI_20860_2021 completed in 0:00:14.439808

 71%|███████   | 3040/4292 [6:38:18<3:22:37,  9.71s/it]

WV_733_2021 completed in 0:00:07.105671

 71%|███████   | 3041/4292 [6:38:27<3:12:26,  9.23s/it]

WV_12796_2021 completed in 0:00:08.105746

 71%|███████   | 3042/4292 [6:38:35<3:06:38,  8.96s/it]

WV_15263_2021 completed in 0:00:08.326738

 71%|███████   | 3043/4292 [6:38:40<2:43:56,  7.88s/it]

WV_20521_2021 completed in 0:00:05.346810

 71%|███████   | 3044/4292 [6:38:48<2:42:07,  7.79s/it]

WY_3461_2021 completed in 0:00:07.599637

 71%|███████   | 3045/4292 [6:38:56<2:43:29,  7.87s/it]

WY_7222_2021 completed in 0:00:08.033065

 71%|███████   | 3046/4292 [6:39:04<2:47:49,  8.08s/it]

WY_8566_2021 completed in 0:00:08.583304

 71%|███████   | 3047/4292 [6:39:12<2:44:40,  7.94s/it]

WY_11273_2021 completed in 0:00:07.591734

 71%|███████   | 3048/4292 [6:39:19<2:38:01,  7.62s/it]

WY_12199_2021 completed in 0:00:06.887482

 71%|███████   | 3049/4292 [6:39:28<2:44:24,  7.94s/it]

WY_14354_2021 completed in 0:00:08.668520

 71%|███████   | 3050/4292 [6:39:35<2:42:32,  7.85s/it]

WY_19156_2021 completed in 0:00:07.655113

 71%|███████   | 3051/4292 [6:39:43<2:40:10,  7.74s/it]

WY_27058_2021 completed in 0:00:07.490331

 71%|███████   | 3052/4292 [6:39:49<2:33:08,  7.41s/it]

CA_16612_2021 completed in 0:00:06.629818

 71%|███████   | 3053/4292 [6:39:57<2:32:08,  7.37s/it]

CO_10066_2021 completed in 0:00:07.268465

 71%|███████   | 3054/4292 [6:40:04<2:34:47,  7.50s/it]

MA_20310_2021 completed in 0:00:07.815096

 71%|███████   | 3055/4292 [6:40:18<3:11:26,  9.29s/it]

AK_219_2022 completed in 0:00:13.446887

 71%|███████   | 3056/4292 [6:40:28<3:18:04,  9.62s/it]

AK_3522_2022 completed in 0:00:10.377615

 71%|███████   | 3057/4292 [6:40:37<3:10:33,  9.26s/it]

AK_7353_2022 completed in 0:00:08.423777

 71%|███████   | 3058/4292 [6:40:48<3:26:10, 10.02s/it]

AK_11824_2022 completed in 0:00:11.811595

 71%|███████▏  | 3059/4292 [6:40:55<3:04:14,  8.97s/it]

AK_19558_2022 completed in 0:00:06.493186

 71%|███████▏  | 3060/4292 [6:41:01<2:48:27,  8.20s/it]

AR_814_2022 completed in 0:00:06.423063

 71%|███████▏  | 3061/4292 [6:41:09<2:41:43,  7.88s/it]

AR_817_2022 completed in 0:00:07.130717

 71%|███████▏  | 3062/4292 [6:41:15<2:34:45,  7.55s/it]

AR_3093_2022 completed in 0:00:06.771423

 71%|███████▏  | 3063/4292 [6:41:23<2:36:53,  7.66s/it]

AR_5860_2022 completed in 0:00:07.915887

 71%|███████▏  | 3064/4292 [6:41:32<2:43:16,  7.98s/it]

AR_6342_2022 completed in 0:00:08.718386

 71%|███████▏  | 3065/4292 [6:41:38<2:29:37,  7.32s/it]

AR_13718_2022 completed in 0:00:05.774800

 71%|███████▏  | 3066/4292 [6:41:45<2:27:36,  7.22s/it]

AR_14063_2022 completed in 0:00:07.004613

 71%|███████▏  | 3067/4292 [6:41:52<2:26:30,  7.18s/it]

AR_17698_2022 completed in 0:00:07.062743

 71%|███████▏  | 3068/4292 [6:41:58<2:20:45,  6.90s/it]

AZ_176_2022 completed in 0:00:06.256610

 72%|███████▏  | 3069/4292 [6:42:07<2:35:31,  7.63s/it]

AZ_803_2022 completed in 0:00:09.333147

 72%|███████▏  | 3070/4292 [6:42:15<2:36:57,  7.71s/it]

AZ_12919_2022 completed in 0:00:07.879406

 72%|███████▏  | 3071/4292 [6:42:25<2:49:09,  8.31s/it]

AZ_16572_2022 completed in 0:00:09.725133

 72%|███████▏  | 3072/4292 [6:42:32<2:38:32,  7.80s/it]

AZ_19189_2022 completed in 0:00:06.594252

 72%|███████▏  | 3073/4292 [6:42:40<2:40:14,  7.89s/it]

AZ_19728_2022 completed in 0:00:08.092639

 72%|███████▏  | 3074/4292 [6:42:51<3:01:11,  8.93s/it]

AZ_21538_2022 completed in 0:00:11.343159

 72%|███████▏  | 3075/4292 [6:42:58<2:46:03,  8.19s/it]

AZ_24211_2022 completed in 0:00:06.457328

 72%|███████▏  | 3076/4292 [6:43:10<3:11:43,  9.46s/it]

CA_4390_2022 completed in 0:00:12.430111

 72%|███████▏  | 3077/4292 [6:43:23<3:34:12, 10.58s/it]

CA_9216_2022 completed in 0:00:13.185000

 72%|███████▏  | 3078/4292 [6:43:34<3:34:13, 10.59s/it]

CA_11208_2022 completed in 0:00:10.610938

 72%|███████▏  | 3079/4292 [6:43:44<3:33:43, 10.57s/it]

CA_12745_2022 completed in 0:00:10.531894

 72%|███████▏  | 3080/4292 [6:44:02<4:17:22, 12.74s/it]

CA_14328_2022 completed in 0:00:17.798658

 72%|███████▏  | 3081/4292 [6:44:15<4:15:12, 12.64s/it]

CA_14354_2022 completed in 0:00:12.417576

 72%|███████▏  | 3082/4292 [6:44:25<4:04:35, 12.13s/it]

CA_14534_2022 completed in 0:00:10.924389

 72%|███████▏  | 3083/4292 [6:44:32<3:30:40, 10.46s/it]

CA_16534_2022 completed in 0:00:06.550319

 72%|███████▏  | 3084/4292 [6:44:38<3:04:27,  9.16s/it]

CA_16609_2022 completed in 0:00:06.140179

 72%|███████▏  | 3085/4292 [6:44:44<2:46:06,  8.26s/it]

CA_16655_2022 completed in 0:00:06.145869

 72%|███████▏  | 3086/4292 [6:45:00<3:33:26, 10.62s/it]

CA_17609_2022 completed in 0:00:16.128051

 72%|███████▏  | 3087/4292 [6:45:10<3:24:44, 10.19s/it]

CA_17612_2022 completed in 0:00:09.203120

 72%|███████▏  | 3088/4292 [6:45:24<3:47:35, 11.34s/it]

CA_18260_2022 completed in 0:00:14.013904

 72%|███████▏  | 3089/4292 [6:45:31<3:21:00, 10.03s/it]

CA_19281_2022 completed in 0:00:06.952297

 72%|███████▏  | 3090/4292 [6:45:46<3:53:29, 11.66s/it]

CO_3989_2022 completed in 0:00:15.457130

 72%|███████▏  | 3091/4292 [6:45:55<3:35:19, 10.76s/it]

CO_6604_2022 completed in 0:00:08.655451

 72%|███████▏  | 3092/4292 [6:46:02<3:13:33,  9.68s/it]

CO_9336_2022 completed in 0:00:07.158549

 72%|███████▏  | 3093/4292 [6:46:16<3:39:32, 10.99s/it]

CO_12866_2022 completed in 0:00:14.039036

 72%|███████▏  | 3094/4292 [6:46:22<3:10:53,  9.56s/it]

CO_15257_2022 completed in 0:00:06.231869

 72%|███████▏  | 3095/4292 [6:46:40<4:00:05, 12.03s/it]

CO_15466_2022 completed in 0:00:17.801055

 72%|███████▏  | 3096/4292 [6:46:52<3:57:33, 11.92s/it]

CO_16603_2022 completed in 0:00:11.643612

 72%|███████▏  | 3097/4292 [6:47:03<3:52:47, 11.69s/it]

CO_19499_2022 completed in 0:00:11.153685

 72%|███████▏  | 3098/4292 [6:47:10<3:26:51, 10.40s/it]

CO_27058_2022 completed in 0:00:07.376012

 72%|███████▏  | 3099/4292 [6:47:23<3:41:25, 11.14s/it]

CO_56146_2022 completed in 0:00:12.863560

 72%|███████▏  | 3100/4292 [6:47:34<3:40:51, 11.12s/it]

CT_4176_2022 completed in 0:00:11.068506

 72%|███████▏  | 3101/4292 [6:47:43<3:29:06, 10.53s/it]

CT_7716_2022 completed in 0:00:09.174273

 72%|███████▏  | 3102/4292 [6:47:56<3:42:43, 11.23s/it]

CT_19497_2022 completed in 0:00:12.851480

 72%|███████▏  | 3103/4292 [6:48:05<3:29:59, 10.60s/it]

CT_20038_2022 completed in 0:00:09.119408

 72%|███████▏  | 3104/4292 [6:48:12<3:07:24,  9.47s/it]

DC_15270_2022 completed in 0:00:06.823590

 72%|███████▏  | 3105/4292 [6:48:21<3:04:10,  9.31s/it]

DE_5027_2022 completed in 0:00:08.942062

 72%|███████▏  | 3106/4292 [6:48:30<2:59:55,  9.10s/it]

DE_5070_2022 completed in 0:00:08.618288

 72%|███████▏  | 3107/4292 [6:48:39<3:03:20,  9.28s/it]

DE_5335_2022 completed in 0:00:09.703101

 72%|███████▏  | 3108/4292 [6:48:47<2:56:28,  8.94s/it]

DE_13519_2022 completed in 0:00:08.148385

 72%|███████▏  | 3109/4292 [6:48:55<2:50:15,  8.64s/it]

FL_6452_2022 completed in 0:00:07.911698

 72%|███████▏  | 3110/4292 [6:49:04<2:52:51,  8.77s/it]

FL_6455_2022 completed in 0:00:09.099845

 72%|███████▏  | 3111/4292 [6:49:12<2:47:34,  8.51s/it]

FL_6457_2022 completed in 0:00:07.902469

 73%|███████▎  | 3112/4292 [6:49:18<2:32:53,  7.77s/it]

FL_9617_2022 completed in 0:00:06.042546

 73%|███████▎  | 3113/4292 [6:49:27<2:40:19,  8.16s/it]

FL_18454_2022 completed in 0:00:09.055803

 73%|███████▎  | 3114/4292 [6:49:35<2:39:22,  8.12s/it]

GA_3916_2022 completed in 0:00:08.021709

 73%|███████▎  | 3115/4292 [6:49:42<2:30:19,  7.66s/it]

GA_9601_2022 completed in 0:00:06.600173

 73%|███████▎  | 3116/4292 [6:49:47<2:14:03,  6.84s/it]

HI_8287_2022 completed in 0:00:04.919435

 73%|███████▎  | 3117/4292 [6:49:54<2:13:49,  6.83s/it]

HI_10071_2022 completed in 0:00:06.817891

 73%|███████▎  | 3118/4292 [6:50:01<2:16:13,  6.96s/it]

HI_11843_2022 completed in 0:00:07.260399

 73%|███████▎  | 3119/4292 [6:50:07<2:12:32,  6.78s/it]

HI_19547_2022 completed in 0:00:06.348624

 73%|███████▎  | 3120/4292 [6:50:15<2:19:52,  7.16s/it]

IA_9417_2022 completed in 0:00:08.048630

 73%|███████▎  | 3121/4292 [6:50:22<2:17:59,  7.07s/it]

IA_12341_2022 completed in 0:00:06.858525

 73%|███████▎  | 3122/4292 [6:50:30<2:22:48,  7.32s/it]

ID_9187_2022 completed in 0:00:07.913134

 73%|███████▎  | 3123/4292 [6:50:39<2:28:03,  7.60s/it]

ID_9191_2022 completed in 0:00:08.240470

 73%|███████▎  | 3124/4292 [6:50:46<2:26:01,  7.50s/it]

ID_10454_2022 completed in 0:00:07.268127

 73%|███████▎  | 3125/4292 [6:50:53<2:26:18,  7.52s/it]

ID_11273_2022 completed in 0:00:07.569116

 73%|███████▎  | 3126/4292 [6:50:58<2:10:52,  6.73s/it]

ID_14354_2022 completed in 0:00:04.897722

 73%|███████▎  | 3127/4292 [6:51:07<2:21:13,  7.27s/it]

ID_20169_2022 completed in 0:00:08.530243

 73%|███████▎  | 3128/4292 [6:51:12<2:09:16,  6.66s/it]

IL_4110_2022 completed in 0:00:05.240314

 73%|███████▎  | 3129/4292 [6:51:17<2:00:42,  6.23s/it]

IL_12341_2022 completed in 0:00:05.206703

 73%|███████▎  | 3130/4292 [6:51:24<2:05:04,  6.46s/it]

IL_13032_2022 completed in 0:00:06.998247

 73%|███████▎  | 3131/4292 [6:51:37<2:43:24,  8.45s/it]

IL_56697_2022 completed in 0:00:13.079550

 73%|███████▎  | 3132/4292 [6:51:46<2:41:54,  8.37s/it]

IN_9273_2022 completed in 0:00:08.205229

 73%|███████▎  | 3133/4292 [6:51:51<2:22:32,  7.38s/it]

IN_9324_2022 completed in 0:00:05.054303

 73%|███████▎  | 3134/4292 [6:51:59<2:28:16,  7.68s/it]

IN_13756_2022 completed in 0:00:08.386015

 73%|███████▎  | 3135/4292 [6:52:09<2:43:01,  8.45s/it]

IN_15470_2022 completed in 0:00:10.254575

 73%|███████▎  | 3136/4292 [6:52:14<2:22:08,  7.38s/it]

IN_17633_2022 completed in 0:00:04.865218

 73%|███████▎  | 3137/4292 [6:52:19<2:06:58,  6.60s/it]

KS_5860_2022 completed in 0:00:04.766572

 73%|███████▎  | 3138/4292 [6:52:23<1:55:17,  5.99s/it]

KS_9996_2022 completed in 0:00:04.589145

In [ ]:
result_df.head()

,year,month,cloudy_days,avg_tcc,median_tcc,eiaid,utility,full_id,full_id_y
0,2011.0,1,1,27.707476,5.199951,19728.0,"UNS Electric, Inc",AZ_19728,AZ_19728_2011
1,2011.0,2,3,33.373883,10.649902,19728.0,"UNS Electric, Inc",AZ_19728,AZ_19728_2011
2,2011.0,3,4,36.572689,28.399902,19728.0,"UNS Electric, Inc",AZ_19728,AZ_19728_2011
3,2011.0,4,1,31.474212,23.149902,19728.0,"UNS Electric, Inc",AZ_19728,AZ_19728_2011
4,2011.0,5,0,23.497922,21.199951,19728.0,"UNS Electric, Inc",AZ_19728,AZ_19728_2011

In [2]:
utility_monthly_tcc.tail(30)

NameError: name 'utility_monthly_tcc' is not defined

[link text](https://)keep typing something: 1011